OpenMS: TOPPAS.cpp File Reference
TOPPAS.cpp File Reference
#include <QApplication>
#include <QPainter>
#include <QtWidgets/QSplashScreen>
#include <QtCore/QDir>
#include <OpenMS/CONCEPT/LogStream.h>
#include <OpenMS/CONCEPT/VersionInfo.h>
#include <OpenMS/DATASTRUCTURES/Map.h>
#include <OpenMS/SYSTEM/StopWatch.h>
#include <OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h>
#include <OpenMS/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.h>
#include <iostream>
#include <map>
#include <vector>
Functions
void print_usage (Logger::LogStream &stream=OpenMS_Log_info)
int main (int argc, const char **argv)
Variables
const char * tool_name = "TOPPAS"
Function Documentation
main()
int main (int argc, const char ** argv)
References Param::exists(), StopWatch::getClockTime(), BaseException::getFile(), BaseException::getLine(), Param::getValue(), VersionInfo::getVersion(), String::hasSubstring(), TOPPASBase::IDINITIALUNTITLED, LogStream::insert(), TOPPASBase::loadFiles(), TOPPASBase::loadPreferences(), TOPPASBase::newPipeline(), OpenMS::OpenMS_Log_debug, OPENMS_LOG_ERROR, OpenMS::OpenMS_Log_error, OPENMS_LOG_INFO, Param::parseCommandLine(), print_usage(), StopWatch::start(), StopWatch::stop(), DataValue::toString(), and BaseException::what().
print_usage()
void print_usage (Logger::LogStream & stream = OpenMS_Log_info)
References tool_name.
Referenced by main().
Variable Documentation
tool_name
const char* tool_name = "TOPPAS"
Referenced by TOPPASBase::insertNewVertex_(), and print_usage().