OpenMS: INIFileEditor.cpp File Reference
INIFileEditor.cpp File Reference
#include <OpenMS/VISUAL/APPLICATIONS/INIFileEditorWindow.h>
#include <OpenMS/CONCEPT/Exception.h>
#include <OpenMS/CONCEPT/LogStream.h>
#include <OpenMS/FORMAT/ParamXMLFile.h>
#include <OpenMS/SYSTEM/File.h>
#include <OpenMS/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.h>
#include <QtWidgets/QStyleFactory>
#include <OpenMS/DATASTRUCTURES/Map.h>
Functions
int main (int argc, const char **argv)
Function Documentation
main()
int main (int argc, const char ** argv)
References Param::begin(), Param::end(), Param::exists(), Param::getValue(), ParamXMLFile::load(), INIFileEditorWindow::openFile(), OPENMS_LOG_ERROR, and Param::parseCommandLine().