OpenMS: OpenSwath Namespace Reference
OpenSwath Namespace Reference
Namespaces
Scoring
Scoring functions used by MRMScoring.
Classes
struct CSVWriter
struct DataMatrix
struct IDataFrameWriter
class IFeature
class IMRMFeature
struct ISignalToNoise
class ISpectrumAccess
The interface of a mass spectrometry experiment.
struct ITransitionGroup
struct LightCompound
struct LightModification
struct LightProtein
struct LightTargetedExperiment
struct LightTransition
class mean_and_stddev
functor to compute the mean and stddev of sequence using the std::foreach algorithm
class MockFeature
Mock object implementing IFeature.
class MockMRMFeature
Mock object implementing IMRMFeature.
class MockSignalToNoise
Mock object implementing ISignalToNoise.
class MockTransitionGroup
Mock object implementing ITransitionGroup.
class MRMScoring
This class implements different scores for peaks found in SRM/MRM.
struct mySqrt
struct OSBinaryDataArray
The datastructures used by the OpenSwath interfaces.
struct OSChromatogram
A single chromatogram.
struct OSChromatogramMeta
Identifying information for a chromatogram.
struct OSSpectrum
The structure that captures the generation of a peak list (including the underlying acquisitions)
struct OSSpectrumMeta
Identifying information for a spectrum.
struct Peptide
struct Protein
struct SwathMap
Data structure to hold one SWATH map with information about upper / lower isolation window and whether the map is MS1 or MS2.
class SwathQC
Quality Control function for OpenSwath.
struct TargetedExperiment
struct TransitionHelper
Typedefs
typedef OSBinaryDataArray BinaryDataArray
typedef boost::shared_ptr< BinaryDataArray > BinaryDataArrayPtr
typedef OSChromatogramMeta ChromatogramMeta
typedef boost::shared_ptr< ChromatogramMeta > ChromatogramMetaPtr
typedef OSChromatogram Chromatogram
typedef boost::shared_ptr< Chromatogram > ChromatogramPtr
typedef OSSpectrumMeta SpectrumMeta
typedef boost::shared_ptr< SpectrumMeta > SpectrumMetaPtr
typedef OSSpectrum Spectrum
typedef boost::shared_ptr< Spectrum > SpectrumPtr
typedef boost::shared_ptr< ISpectrumAccess > SpectrumAccessPtr
typedef boost::shared_ptr< ISignalToNoise > ISignalToNoisePtr
Functions
OPENSWATHALGO_DLLAPI void normalize (const std::vector< double > &intensities, double normalization_factor, std::vector< double > &normalized_intensities)
Normalize intensities in vector by normalization_factor.
template<typename T >
double norm (T beg, T end)
compute the norm of the vector
template<typename Texp , typename Ttheo >
double dotProd (Texp intExpBeg, Texp intExpEnd, Ttheo intTheo)
compute dotprod of vectors
OPENSWATHALGO_DLLAPI double dotprodScoring (std::vector< double > intExp, std::vector< double > theorint)
the dot product scoring
template<typename Texp , typename Ttheo >
double manhattanDist (Texp itExpBeg, Texp itExpEnd, Ttheo itTheo)
compute manhattan distance between Exp and Theo
OPENSWATHALGO_DLLAPI double manhattanScoring (std::vector< double > intExp, std::vector< double > theorint)
manhattan scoring
template<typename TInputIterator , typename TInputIteratorY >
std::iterator_traits< TInputIterator >::value_type cor_pearson (TInputIterator xBeg, TInputIterator xEnd, TInputIteratorY yBeg)
compute pearson correlation of vector x and y
Class Documentation
OpenSwath::LightModification
struct OpenSwath::LightModification
Class Members
int location
int unimod_id
OpenSwath::LightProtein
struct OpenSwath::LightProtein
Class Members
string id
string sequence
OpenSwath::OSBinaryDataArray
struct OpenSwath::OSBinaryDataArray
The datastructures used by the OpenSwath interfaces.
Many of them are closely related to Proteowizard data structures, originally written by Darren Kessner and released under the Apache 2.0 licence.
Original author: Darren Kessner darre.nosp@m.n@pr.nosp@m.oteow.nosp@m.izar.nosp@m.d.org
Copyright 2007 Spielberg Family Center for Applied Proteomics Cedars-Sinai Medical Center, Los Angeles, California 90048
The following datastructures are used :
BinaryDataArray : a struct that holds a std::vector<double> with the data
ChromatogramMeta : meta information of a chromatogram (index)
Chromatogram : chromatogram data. Contains a vector of pointers to BinaryDataArray, the first one is time array (RT), the second one is intensity
SpectrumMeta : meta information of a spectrum (index, identifier, RT, ms_level)
Spectrum : spectrum data. Contains a vector of pointers to BinaryDataArray, the first one is mz array, the second one is intensity The structure into which encoded binary data goes.
Class Members
vector< double > data this optional attribute may reference the 'id' attribute of the appropriate dataProcessing.
the binary data.
string description (optional) data description for non-standard arrays.
OpenSwath::Protein
struct OpenSwath::Protein
Class Members
string id
vector< Peptide > peptides
string sequence
OpenSwath::TargetedExperiment
struct OpenSwath::TargetedExperiment
Class Members
vector< Protein > proteins
Typedef Documentation
BinaryDataArray
typedef OSBinaryDataArray BinaryDataArray
BinaryDataArrayPtr
typedef boost::shared_ptr<BinaryDataArray> BinaryDataArrayPtr
Chromatogram
typedef OSChromatogram Chromatogram
ChromatogramMeta
typedef OSChromatogramMeta ChromatogramMeta
ChromatogramMetaPtr
typedef boost::shared_ptr<ChromatogramMeta> ChromatogramMetaPtr
ChromatogramPtr
typedef boost::shared_ptr<Chromatogram> ChromatogramPtr
ISignalToNoisePtr
typedef boost::shared_ptr<ISignalToNoise> ISignalToNoisePtr
Spectrum
typedef OSSpectrum Spectrum
SpectrumAccessPtr
typedef boost::shared_ptr<ISpectrumAccess> SpectrumAccessPtr
SpectrumMeta
typedef OSSpectrumMeta SpectrumMeta
SpectrumMetaPtr
typedef boost::shared_ptr<SpectrumMeta> SpectrumMetaPtr
SpectrumPtr
typedef boost::shared_ptr<Spectrum> SpectrumPtr
Function Documentation
cor_pearson()
std::iterator_traits<TInputIterator>::value_type OpenSwath::cor_pearson (TInputIterator xBeg, TInputIterator xEnd, TInputIteratorY yBeg)
compute pearson correlation of vector x and y
dotProd()
double OpenSwath::dotProd (Texp intExpBeg, Texp intExpEnd, Ttheo intTheo)
compute dotprod of vectors
References OpenMS::Math::sum().
dotprodScoring()
OPENSWATHALGO_DLLAPI double OpenSwath::dotprodScoring (std::vector< double > intExp, std::vector< double > theorint)
the dot product scoring
sqrt data, normalize by vector norm compute dotprod
manhattanDist()
double OpenSwath::manhattanDist (Texp itExpBeg, Texp itExpEnd, Ttheo itTheo)
compute manhattan distance between Exp and Theo
References OpenMS::Math::sum().
manhattanScoring()
OPENSWATHALGO_DLLAPI double OpenSwath::manhattanScoring (std::vector< double > intExp, std::vector< double > theorint)
manhattan scoring
sqrt intensities normalize vector by TIC compute manhattan score
norm()
double OpenSwath::norm (T beg, T end)
compute the norm of the vector
Referenced by GaussFilterAlgorithm::integrate_(), and FLASHDeconv::PrecalcularedAveragine::PrecalcularedAveragine().
normalize()
OPENSWATHALGO_DLLAPI void OpenSwath::normalize (const std::vector< double > & intensities, double normalization_factor, std::vector< double > & normalized_intensities)
Normalize intensities in vector by normalization_factor.