OpenMS: seqan Namespace Reference
seqan Namespace Reference
Classes
struct AAcid_
struct AdaptedIdentity
struct BitsPerValue< AAcid >
struct CompareTypeImpl< AAcid, char >
struct CompareTypeImpl< AAcid, uint8_t >
struct Host< Pattern< TNeedle, FuzzyAC > >
struct Host< Pattern< TNeedle, FuzzyAC > const >
struct OMS_TranslateTableAAToChar_
struct OMS_TranslateTableByteToAA_
struct OMS_TranslateTableCharToAA_
struct PAM30MS
class Pattern< TNeedle, FuzzyAC >
struct PatternAuxData
struct ScoringMatrixData_< int, AminoAcid, AdaptedIdentity >
struct ScoringMatrixData_< int, AminoAcid, PAM30MS >
struct Spawn
state of an AC spawn, operating on a trie
struct ValueSize< AAcid >
Typedefs
typedef SimpleType< unsigned char, AAcid_ > AAcid
typedef String< AAcid, Alloc< void > > AAString
typedef Iterator< const AAString, Rooted >::Type AAStringIterator
typedef Tag< FuzzyAC_ > FuzzyAC
Functions
AAcid unknownValueImpl (AAcid *)
void assign (char &c_target, AAcid const &source)
void assign (AAcid &target, uint8_t c_source)
void assign (AAcid &target, char c_source)
template<typename T >
void _getSpawnRange (const AAcid c, T &idxFirst, T &idxLast)
given an ambAA c, return a range of AA's (including idxLast) which need to be spawned.
template<typename TNeedle >
void _createAcTrie (Pattern< TNeedle, FuzzyAC > &me)
template<typename TNeedle , typename TNeedle2 >
void setHost (Pattern< TNeedle, FuzzyAC > &me, TNeedle2 const &needle)
template<typename TNeedle , typename TNeedle2 >
void setHost (Pattern< TNeedle, FuzzyAC > &me, TNeedle2 &needle)
template<typename TNeedle >
Size< TNeedle >::Type position (const PatternAuxData< TNeedle > &dh)
template<typename TFinder , typename TNeedle >
void _reportHit (TFinder &finder, const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh)
bool isAmbiguous (AAcid c)
bool isAmbiguous (const AAString &s)
template<typename TNeedle >
bool _createSecondarySpawns (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, Spawn< TNeedle > &spawn, const AAcid c)
template<class TNeedle >
std::string getPath (const Pattern< TNeedle, FuzzyAC > &me, typename Pattern< TNeedle, FuzzyAC >::TVert current_state)
for debug only
template<class TNeedle >
void addHits (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, const Spawn< TNeedle > &spawn)
template<class TNeedle >
void addHits (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, const typename Pattern< TNeedle, FuzzyAC >::TVert &current_state)
template<typename TNeedle >
bool _consumeChar (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, typename Pattern< TNeedle, FuzzyAC >::TVert &current, const AAcid c)
Universal UN-ambiguous char consumer. Works for Master and Spawns.
template<typename TNeedle >
bool _consumeChar (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, Spawn< TNeedle > &spawn, const AAcid c)
Consume UN-ambiguous char, while checking prefix/root conditions.
template<typename TNeedle >
bool _spawnConsumeChar (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, Spawn< TNeedle > &spawn, const AAcid c)
template<typename TNeedle >
void _masterConsumeChar (const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh, const AAcid c)
template<typename TFinder , typename TNeedle >
bool find (TFinder &finder, const Pattern< TNeedle, FuzzyAC > &me, PatternAuxData< TNeedle > &dh)
Class Documentation
seqan::AAcid_
struct seqan::AAcid_
seqan::AdaptedIdentity
struct seqan::AdaptedIdentity
seqan::CompareTypeImpl< AAcid, char >
struct seqan::CompareTypeImpl< AAcid, char >
template<>
struct seqan::CompareTypeImpl< AAcid, char >
Class Members
typedef AAcid Type
seqan::CompareTypeImpl< AAcid, uint8_t >
struct seqan::CompareTypeImpl< AAcid, uint8_t >
template<>
struct seqan::CompareTypeImpl< AAcid, uint8_t >
Class Members
typedef AAcid Type
seqan::Host< Pattern< TNeedle, FuzzyAC > >
struct seqan::Host< Pattern< TNeedle, FuzzyAC > >
template<typename TNeedle>
struct seqan::Host< Pattern< TNeedle, FuzzyAC > >
Class Members
typedef TNeedle Type
seqan::Host< Pattern< TNeedle, FuzzyAC > const >
struct seqan::Host< Pattern< TNeedle, FuzzyAC > const >
template<typename TNeedle>
struct seqan::Host< Pattern< TNeedle, FuzzyAC > const >
Class Members
typedef const TNeedle Type
seqan::PAM30MS
struct seqan::PAM30MS
Typedef Documentation
AAcid
typedef SimpleType<unsigned char, AAcid_> AAcid
AAString
typedef String<AAcid, Alloc<void> > AAString
AAStringIterator
typedef Iterator<const AAString, Rooted>::Type AAStringIterator
FuzzyAC
typedef Tag<FuzzyAC_> FuzzyAC
Function Documentation
_consumeChar() [1/2]
bool seqan::_consumeChar (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, Spawn< TNeedle > & spawn, const AAcid c) inline
Consume UN-ambiguous char, while checking prefix/root conditions.
Adds hits to dh and updates spawn.current_state and spawn.max_depth_decrease
Return false if new state is root, true otherwise.
References addHits(), OpenMS::Constants::c, Spawn< TNeedle >::current_state, Pattern< TNeedle, FuzzyAC >::data_graph, Pattern< TNeedle, FuzzyAC >::data_node_depth, Spawn< TNeedle >::max_depth_decrease, and Pattern< TNeedle, FuzzyAC >::nilVal.
_consumeChar() [2/2]
bool seqan::_consumeChar (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, typename Pattern< TNeedle, FuzzyAC >::TVert & current, const AAcid c) inline
Universal UN-ambiguous char consumer. Works for Master and Spawns.
Updates current by consuming the char. Adds hits to dh after settling.
Returns
False if it reached the 'root', true otherwise
References addHits(), OpenMS::Constants::c, Pattern< TNeedle, FuzzyAC >::data_graph, and Pattern< TNeedle, FuzzyAC >::nilVal.
Referenced by _createSecondarySpawns(), _masterConsumeChar(), and _spawnConsumeChar().
_createAcTrie()
void seqan::_createAcTrie (Pattern< TNeedle, FuzzyAC > & me) inline
< allows to find parent of each node
< allows to find character that led us to current node
< allows to find parent of each node
< trie suffix links (temporary only)
< node depths
< range of unambiguous AAcids: AAcid(idx)
create failure function (suffix links) and output function
References _getSpawnRange(), Pattern< TNeedle, FuzzyAC >::data_graph, Pattern< TNeedle, FuzzyAC >::data_map_outputNodes, Pattern< TNeedle, FuzzyAC >::data_node_depth, and Pattern< TNeedle, FuzzyAC >::parentMap.
Referenced by setHost().
_createSecondarySpawns()
bool seqan::_createSecondarySpawns (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, Spawn< TNeedle > & spawn, const AAcid c) inline
References _consumeChar(), _getSpawnRange(), Spawn< TNeedle >::ambAA_seen, OpenMS::Constants::c, Spawn< TNeedle >::current_state, DEBUG_ONLY, getPath(), isAmbiguous(), Spawn< TNeedle >::max_depth_decrease, and PatternAuxData< TNeedle >::spawns.
_getSpawnRange()
void seqan::_getSpawnRange (const AAcid c, T & idxFirst, T & idxLast) inline
given an ambAA c, return a range of AA's (including idxLast) which need to be spawned.
The range can be converted to AAcids via 'AAcid(T)'.
References OpenMS::Constants::c.
Referenced by _createAcTrie(), _createSecondarySpawns(), _masterConsumeChar(), and _spawnConsumeChar().
_masterConsumeChar()
void seqan::_masterConsumeChar (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, const AAcid c) inline
References _consumeChar(), _getSpawnRange(), OpenMS::Constants::c, Pattern< TNeedle, FuzzyAC >::data_graph, PatternAuxData< TNeedle >::data_lastState, Pattern< TNeedle, FuzzyAC >::data_node_depth, DEBUG_ONLY, isAmbiguous(), Pattern< TNeedle, FuzzyAC >::max_ambAA, Pattern< TNeedle, FuzzyAC >::max_mmAA, and PatternAuxData< TNeedle >::spawns.
Referenced by find().
_reportHit()
void seqan::_reportHit (TFinder & finder, const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh) inline
References PatternAuxData< TNeedle >::data_keywordIndex, PatternAuxData< TNeedle >::data_needleLength, PatternAuxData< TNeedle >::hits_endPositions, and position().
Referenced by find().
_spawnConsumeChar()
bool seqan::_spawnConsumeChar (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, Spawn< TNeedle > & spawn, const AAcid c) inline
References _consumeChar(), _getSpawnRange(), Spawn< TNeedle >::ambAA_seen, OpenMS::Constants::c, Spawn< TNeedle >::current_state, DEBUG_ONLY, getPath(), isAmbiguous(), Pattern< TNeedle, FuzzyAC >::max_ambAA, Spawn< TNeedle >::max_depth_decrease, Pattern< TNeedle, FuzzyAC >::max_mmAA, Spawn< TNeedle >::mismatches_seen, and PatternAuxData< TNeedle >::spawns.
Referenced by find().
addHits() [1/2]
void seqan::addHits (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, const Spawn< TNeedle > & spawn) inline
References OpenMS::StringConversions::append(), Spawn< TNeedle >::current_state, Pattern< TNeedle, FuzzyAC >::data_map_outputNodes, Pattern< TNeedle, FuzzyAC >::data_node_depth, DEBUG_ONLY, PatternAuxData< TNeedle >::hits_endPositions, and Spawn< TNeedle >::max_depth_decrease.
Referenced by _consumeChar().
addHits() [2/2]
void seqan::addHits (const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh, const typename Pattern< TNeedle, FuzzyAC >::TVert & current_state) inline
References OpenMS::StringConversions::append(), Pattern< TNeedle, FuzzyAC >::data_map_outputNodes, DEBUG_ONLY, and PatternAuxData< TNeedle >::hits_endPositions.
assign() [1/3]
void seqan::assign (AAcid & target, char c_source) inline
assign() [2/3]
void seqan::assign (AAcid & target, uint8_t c_source) inline
assign() [3/3]
void seqan::assign (char & c_target, AAcid const & source) inline
find()
bool seqan::find (TFinder & finder, const Pattern< TNeedle, FuzzyAC > & me, PatternAuxData< TNeedle > & dh) inline
References _masterConsumeChar(), _reportHit(), _spawnConsumeChar(), OpenMS::Constants::c, PatternAuxData< TNeedle >::data_lastState, PatternAuxData< TNeedle >::data_needleLength, Pattern< TNeedle, FuzzyAC >::data_node_depth, DEBUG_ONLY, getPath(), PatternAuxData< TNeedle >::hits_endPositions, and PatternAuxData< TNeedle >::spawns.
Referenced by ScoredProcessingResult::addProcessingStep(), ListUtils::contains(), XMLHandler::cvStringToEnum_(), KDTree< 2, KDTreeFeatureNode >::erase(), MessagePasserFactory< Label >::fillVectorsOfMessagePassers(), WindowMower::filterPeakSpectrumForTopNInJumpingWindow(), AhoCorasickAmbiguous::findNext(), ListUtils::getIndex(), MzTab::getOptionalColumnNames_(), ScoredProcessingResult::getScore(), Map< char, double >::has(), GridBasedClustering< Metric >::mergeVeto_(), InMSLevelRange< SpectrumType >::operator()(), HasPrecursorCharge< SpectrumType >::operator()(), Map< char, double >::operator[](), TwoDOptimization::optimize(), MSNumpressCoder::NumpressConfig::setCompression(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
getPath()
std::string seqan::getPath (const Pattern< TNeedle, FuzzyAC > & me, typename Pattern< TNeedle, FuzzyAC >::TVert current_state) inline
for debug only
Referenced by _createSecondarySpawns(), _spawnConsumeChar(), and find().
isAmbiguous() [1/2]
bool seqan::isAmbiguous (AAcid c) inline
References OpenMS::Constants::c.
Referenced by _createSecondarySpawns(), _masterConsumeChar(), _spawnConsumeChar(), Pattern< TNeedle, FuzzyAC >::init(), isAmbiguous(), and PeptideIndexing::run().
isAmbiguous() [2/2]
bool seqan::isAmbiguous (const AAString & s) inline
References isAmbiguous().
position()
Size<TNeedle>::Type seqan::position (const PatternAuxData< TNeedle > & dh) inline
References PatternAuxData< TNeedle >::data_keywordIndex.
Referenced by _reportHit(), AveragePosition< D >::add(), PeptideIndexing::FoundProteinFunctor::addHit(), NASequence::ConstIterator::ConstIterator(), AASequence::ConstIterator::ConstIterator(), ConstRefVector< ContainerT >::ConstRefVectorConstIterator< ValueT >::ConstRefVectorConstIterator(), DBoundingBox< 2 >::encloses(), DRange< 3 >::encloses(), AhoCorasickAmbiguous::getHitDBIndex(), AhoCorasickAmbiguous::getHitProteinPosition(), GridBasedClustering< Metric >::init_(), NASequence::Iterator::Iterator(), AASequence::Iterator::Iterator(), OpenMS::operator*(), OpenMS::operator/(), EnzymaticDigestionLogModel::BindingSite_::operator<(), DeNovoIonScoring::IonScore::operator=(), EnzymaticDigestionLogModel::BindingSite_::operator==(), MultiGradient::precalculatedColorAt(), MultiGradient::precalculatedColorIndex(), DIntervalBase< D >::setMax(), DIntervalBase< D >::setMin(), Peak1D::setPosition(), ChromatogramPeak::setPosition(), Peak2D::setPosition(), and PeptideIndexing::PeptideProteinMatchInformation::tie().
setHost() [1/2]
void seqan::setHost (Pattern< TNeedle, FuzzyAC > & me, TNeedle2 & needle) inline
References setHost().
setHost() [2/2]
void seqan::setHost (Pattern< TNeedle, FuzzyAC > & me, TNeedle2 const & needle)
References _createAcTrie(), Pattern< TNeedle, FuzzyAC >::data_graph, Pattern< TNeedle, FuzzyAC >::data_host, and Pattern< TNeedle, FuzzyAC >::data_map_outputNodes.
Referenced by Pattern< TNeedle, FuzzyAC >::init(), and setHost().
unknownValueImpl()
AAcid seqan::unknownValueImpl (AAcid *) inline