OpenMS: OpenMS::detail Namespace Reference
OpenMS::detail Namespace Reference
Functions
template<typename T >
T convert (const String &s)
template<>
Int convert (const String &s)
template<>
double convert (const String &s)
template<>
float convert (const String &s)
Function Documentation
convert() [1/4]
T OpenMS::detail::convert (const String & s) inline
References String::toDouble(), String::toFloat(), and String::toInt().
convert() [2/4]
Int OpenMS::detail::convert (const String & s) inline
References String::toInt().
convert() [3/4]
double OpenMS::detail::convert (const String & s) inline
References String::toDouble().
convert() [4/4]
float OpenMS::detail::convert (const String & s) inline
References String::toFloat().