OpenMS: Sets FDRs/qVals
Sets FDRs/qVals
Sets FDRs/qVals from a scores_to_FDR map in the ID data structures.
Functions
template<typename IDType , class ... Args>
static void setScores_ (const std::map< double, double > &scores_to_FDR, std::vector< IDType > &ids, const std::string &score_type, bool higher_better, Args &... args)
template<typename IDType >
static String setScoreType_ (IDType &id, const std::string &score_type, bool higher_better)
template<typename IDType >
static void setScores_ (const std::map< double, double > &scores_to_FDR, IDType &id, const std::string &score_type, bool higher_better, bool keep_decoy)
template<typename IDType >
static void setScores_ (const std::map< double, double > &scores_to_FDR, IDType &id, const String &old_score_type)
template<typename IDType , class ... Args>
static void setScoresAndRemoveDecoys_ (const std::map< double, double > &scores_to_FDR, IDType &id, const String &old_score_type, Args ... args)
template<typename HitType >
static void setScore_ (const std::map< double, double > &scores_to_FDR, HitType &hit, const std::string &old_score_type)
template<typename IDType >
static void setScores_ (const std::map< double, double > &scores_to_FDR, IDType &id, const std::string &score_type, bool higher_better)
static void setScores_ (const std::map< double, double > &scores_to_FDR, PeptideIdentification &id, const std::string &score_type, bool higher_better, bool keep_decoy, int charge)
static void setScores_ (const std::map< double, double > &scores_to_FDR, PeptideIdentification &id, const std::string &score_type, bool higher_better, bool keep_decoy, int charge, const String &identifier)
template<typename IDType >
static void setScores_ (const std::map< double, double > &scores_to_FDR, IDType &id, const std::string &score_type, bool higher_better, bool keep_decoy, const String &identifier)
static void setScores_ (const std::map< double, double > &scores_to_FDR, PeptideIdentification &id, const std::string &score_type, bool higher_better, int charge, const String &identifier)
template<typename IDType >
static void setScores_ (const std::map< double, double > &scores_to_FDR, IDType &id, const std::string &score_type, bool higher_better, const String &identifier)
static void setScores_ (const std::map< double, double > &scores_to_FDR, std::vector< ProteinIdentification::ProteinGroup > &grps, const std::string &score_type, bool higher_better)
Detailed Description
Sets FDRs/qVals from a scores_to_FDR map in the ID data structures.
Parameters
scores_to_FDR Maps original score to calculated FDR or q-Value
score_type FDR or q-Value
higher_better should usually be false
Todo:
remove?
Just use the one you need.
Function Documentation
setScore_()
static void setScore_ (const std::map< double, double > & scores_to_FDR, HitType & hit, const std::string & old_score_type) inline static
Referenced by IDScoreGetterSetter::setScores_().
setScores_() [1/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, IDType & id, const std::string & score_type, bool higher_better) inline static
References IDScoreGetterSetter::setScores_(), and IDScoreGetterSetter::setScoreType_().
setScores_() [2/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, IDType & id, const std::string & score_type, bool higher_better, bool keep_decoy) inline static
References IDScoreGetterSetter::setScores_(), IDScoreGetterSetter::setScoresAndRemoveDecoys_(), and IDScoreGetterSetter::setScoreType_().
setScores_() [3/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, IDType & id, const std::string & score_type, bool higher_better, bool keep_decoy, const String & identifier) inline static
References IDScoreGetterSetter::setScores_().
setScores_() [4/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, IDType & id, const std::string & score_type, bool higher_better, const String & identifier) inline static
References IDScoreGetterSetter::setScores_().
setScores_() [5/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, IDType & id, const String & old_score_type) inline static
References IDScoreGetterSetter::setScore_().
setScores_() [6/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, PeptideIdentification & id, const std::string & score_type, bool higher_better, bool keep_decoy, int charge) inline static
References IDScoreGetterSetter::setScores_(), and IDScoreGetterSetter::setScoreType_().
setScores_() [7/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, PeptideIdentification & id, const std::string & score_type, bool higher_better, bool keep_decoy, int charge, const String & identifier) inline static
References IDScoreGetterSetter::setScores_().
setScores_() [8/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, PeptideIdentification & id, const std::string & score_type, bool higher_better, int charge, const String & identifier) inline static
References IDScoreGetterSetter::setScores_().
setScores_() [9/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, std::vector< IDType > & ids, const std::string & score_type, bool higher_better, Args &... args) inline static
Referenced by IDScoreGetterSetter::setPeptideScoresForMap_(), and IDScoreGetterSetter::setScores_().
setScores_() [10/10]
static void setScores_ (const std::map< double, double > & scores_to_FDR, std::vector< ProteinIdentification::ProteinGroup > & grps, const std::string & score_type, bool higher_better) static
setScoresAndRemoveDecoys_()
static void setScoresAndRemoveDecoys_ (const std::map< double, double > & scores_to_FDR, IDType & id, const String & old_score_type, Args ... args) inline static
References IDScoreGetterSetter::setScoreAndMoveIfTarget_().
Referenced by IDScoreGetterSetter::setScores_().
setScoreType_()
static String setScoreType_ (IDType & id, const std::string & score_type, bool higher_better) inline static
Referenced by IDScoreGetterSetter::setScores_().