OpenMS: OpenMS Namespace Reference
OpenMS Namespace Reference
Main OpenMS namespace.
Namespaces
Constants
Mathematical and physical constants namespace.
DataArrays
detail
DIAHelpers
Exception
Exception namespace
FastLowessSmoothing
LOWESS (locally weighted scatterplot smoothing).
Helpers
IdentificationDataInternal
ims
Interfaces
Internal
Namespace used to hide implementation details from users.
Logger
Log streams.
Math
Math namespace.
NNLS
OpenMSBoost
OptimizationFunctions
SimTypes
StringConversions
TargetedExperimentHelper
This class stores helper structures that are used in multiple classes of the TargetedExperiment (e.g. ReactionMonitoringTransition and IncludeExcludeTarget).
Test
Classes
class AAIndex
Representation of selected AAIndex properties.
class AASequence
Representation of a peptide/protein sequence.
class AbsoluteQuantitation
AbsoluteQuantitation is a class to support absolute or relative quantitation for targeted or untargeted quantitation workflows (e.g., Isotope Dilution Mass Spectrometry).
class AbsoluteQuantitationMethod
AbsoluteQuantitationMethod is a class to hold information about the quantitation method and for applying and/or generating the quantitation method.
class AbsoluteQuantitationMethodFile
File adapter for AbsoluteQuantitationMethod files.
class AbsoluteQuantitationStandards
AbsoluteQuantitationStandards is a class to handle the relationship between runs, components, and their actual concentrations.
class AbsoluteQuantitationStandardsFile
Load files containing runConcentration data.
class AccurateMassSearchEngine
An algorithm to search for exact mass matches from a spectrum against a database (e.g. HMDB).
class AccurateMassSearchResult
class Acquisition
Information about one raw data spectrum that was combined with several other raw data spectra.
class AcquisitionInfo
Description of the combination of raw data to a single spectrum.
class AcquisitionInfoVisualizer
Class that displays all meta information for AcquisitionInfo objects.
class AcquisitionVisualizer
Class that displays all meta information for Acquisition objects.
class Adduct
class AdductInfo
class AhoCorasickAmbiguous
Extended Aho-Corasick algorithm capable of matching ambiguous amino acids in the pattern (i.e. proteins).
class Annotation1DCaret
An annotation item which paints a set of carets on the canvas.
class Annotation1DDistanceItem
An annotation item which represents a measured distance between two peaks.
class Annotation1DItem
An abstract class acting as an interface for the different 1D annotation items.
class Annotation1DPeakItem
A peak annotation item.
class Annotation1DTextItem
An annotation item which represents an arbitrary text on the canvas.
class Annotations1DContainer
Container for annotations to content of Spectrum1DCanvas.
struct AnnotationStatistics
class AScore
Implementation of the Ascore For a given peptide sequence and its MS/MS spectrum it identifies the most probable phosphorylation-site(s). For each phosphorylation site a probability score is calculated. The algorithm is implemented according to Beausoleil et al. (Nat. Biotechnol. 2006).
class AverageLinkage
AverageLinkage ClusterMethod.
class AxisPainter
Draws a coordinate axis. It has only static methods, that's why the constructor is private.
class AxisTickCalculator
Calculates ticks for a given value range.
class AxisWidget
Widget that represents an axis of a graph.
class BackgroundControl
class BackgroundIntensityBin
class Base64
Class to encode and decode Base64.
class BaseFeature
A basic LC-MS feature.
class BaseGroupFinder
The base class of all element group finding algorithms.
class BaseLabeler
Abstract base class for all kinds of labeling techniques.
class BaseModel
Abstract base class for all D-dimensional models.
class BaseSuperimposer
The base class of all superimposer algorithms.
class BaseVisualizer
A base class for all visualizer classes.
class BaseVisualizerGUI
A base class for all visualizer classes.
class BasicProteinInferenceAlgorithm
Algorithm class that implements simple protein inference by aggregation of peptide scores. It has multiple parameter options like the aggregation method, when to distinguish peptidoforms, and if you want to use shared peptides ("use_shared_peptides"). First, the best PSM per spectrum is used, then only the best PSM per peptidoform is aggregated. Peptidoforms can optionally be distinguished via the treat_X_separate parameters:
class BayesianProteinInferenceAlgorithm
Performs a Bayesian protein inference on Protein/Peptide identifications or ConsensusMap (experimental).
class BernNorm
BernNorm scales the peaks by ranking them and then scaling them according to rank.
class BiGaussFitter1D
BiGaussian distribution fitter (1-dim.) approximated using linear interpolation.
class BiGaussModel
BiGaussian distribution approximated using linear interpolation.
class BinaryTreeNode
Elements of a binary tree used to represent a hierarchical clustering process.
class BinnedSharedPeakCount
Compare functor scoring the shared peaks for similarity measurement.
class BinnedSpectralContrastAngle
Compare functor scoring the spectral contrast angle for similarity measurement.
class BinnedSpectrum
This is a binned representation of a PeakSpectrum.
class BinnedSpectrumCompareFunctor
Base class for compare functors of BinnedSpectra.
class BinnedSumAgreeingIntensities
Sum of agreeing intensities for similarity measurement.
class BSpline2d
b spline interpolation
class Bzip2Ifstream
Decompresses files which are compressed in the bzip2 format (*.bz2)
class Bzip2InputStream
Implements the BinInputStream class of the xerces-c library in order to read bzip2 compressed XML files.
class CachedmzML
An class that uses on-disk caching to read and write spectra and chromatograms.
class CachedSwathFileConsumer
On-disk cached implementation of FullSwathFileConsumer.
class CalibrationData
A helper class, holding all calibration points.
class CentroidData
class CentroidPeak
class ChargePair
Representation of a (putative) link between two Features, which stem from the same compound but have different charge (including different adduct ions (H+, Na+, ..)
class ChromatogramExtractor
The ChromatogramExtractor extracts chromatograms from a spectra file.
class ChromatogramExtractorAlgorithm
The ChromatogramExtractorAlgorithm extracts chromatograms from a MS data.
class ChromatogramPeak
A 1-dimensional raw data point or peak for chromatograms.
class ChromatogramSettings
Representation of chromatogram settings, e.g. SRM/MRM chromatograms.
class ChromatogramTools
Conversion class to convert chromatograms.
class ChromeleonFile
Load Chromeleon HPLC text file and save it into a `MSExperiment`.
struct ChromExtractParams
ChromatogramExtractor parameters.
struct Citation
Stores Citations for individual TOPP tools.
class ClusterAnalyzer
Bundles analyzing tools for a clustering (given as sequence of BinaryTreeNode's)
class ClusteredMS2ConsensusSpectrum
class ClusterFunctor
Base class for cluster functors.
class ClusterHierarchical
Hierarchical clustering with generic clustering functions.
class ClusteringGrid
data structure to store 2D data to be clustered e.g. (m/z, retention time) coordinates from multiplex filtering
class ClusterProxyKD
Proxy for a (potential) cluster.
class CmpHypothesesByScore
class CmpMassTraceByMZ
class CoarseIsotopePatternGenerator
Isotope pattern generator for coarse isotope distributions.
class ColorSelector
A widget for selecting a color.
class ComplementFilter
total intensity of peak pairs that could result from complementing fragments of charge state 1
class ComplementMarker
ComplementMarker marks peak pairs which could represent y - b ion pairs.
class CompleteLinkage
CompleteLinkage ClusterMethod.
class CompNovoIdentification
run with CompNovoIdentification
class CompNovoIdentificationBase
run with CompNovoIdentificationBase
class CompNovoIdentificationCID
run with CompNovoIdentificationCID
class CompNovoIonScoring
run with CompNovoIonScoring
class CompNovoIonScoringBase
run with CompNovoIonScoringBase
class CompNovoIonScoringCID
run with CompNovoIonScoringCID
class Compomer
Holds information on an edge connecting two features from a (putative) charge ladder.
class CompressedInputSource
This class is based on xercesc::LocalFileInputSource.
class ConfidenceScoring
struct ConnectedComponent
class ConsensusFeature
A consensus feature spanning multiple LC-MS/MS experiments.
class ConsensusIDAlgorithm
Abstract base class for all ConsensusID algorithms (that calculate a consensus from multiple ID runs).
class ConsensusIDAlgorithmAverage
Calculates a consensus from multiple ID runs by averaging the search scores.
class ConsensusIDAlgorithmBest
Calculates a consensus from multiple ID runs by taking the best search score.
class ConsensusIDAlgorithmIdentity
Abstract base class for ConsensusID algorithms that compare only identical sequences.
class ConsensusIDAlgorithmPEPIons
Calculates a consensus from multiple ID runs based on PEPs and shared ions.
class ConsensusIDAlgorithmPEPMatrix
Calculates a consensus from multiple ID runs based on PEPs and sequence similarities.
class ConsensusIDAlgorithmRanks
Calculates a consensus from multiple ID runs based on the ranks of the search hits.
class ConsensusIDAlgorithmSimilarity
Abstract base class for ConsensusID algorithms that take peptide similarity into account.
class ConsensusIDAlgorithmWorst
Calculates a consensus from multiple ID runs by taking the worst search score (conservative approach).
class ConsensusIsotopePattern
class ConsensusMap
A container for consensus elements.
class ConsensusMapMergerAlgorithm
Merges identification data in ConsensusMaps.
class ConsensusMapNormalizerAlgorithmMedian
Algorithms of ConsensusMapNormalizer.
class ConsensusMapNormalizerAlgorithmQuantile
Algorithms of ConsensusMapNormalizer.
class ConsensusMapNormalizerAlgorithmThreshold
Algorithms of ConsensusMapNormalizer.
class ConsensusXMLFile
This class provides Input functionality for ConsensusMaps and Output functionality for alignments and quantitation.
class ConsoleUtils
class ConstRefVector
This vector holds pointer to the elements of another container.
class ContactPerson
Contact person information.
class ContactPersonVisualizer
Class that displays all meta information for ContactPerson objects.
class Contaminants
This class is a metric for the QualityControl TOPP tool.
class ContinuousWaveletTransform
This class is the base class of the continuous wavelet transformation.
class ContinuousWaveletTransformNumIntegration
This class computes the continuous wavelet transformation using a marr wavelet.
class ControlledVocabulary
Representation of a controlled vocabulary.
class ConvexHull2D
A 2-dimensional hull representation in [counter]clockwise direction - depending on axis labelling.
class CrossLinksDB
class CsiFingerIdMzTabWriter
class CsvFile
This class handles csv files. Currently only loading is implemented.
class CubicSpline2d
cubic spline interpolation as described in R.L. Burden, J.D. Faires, Numerical Analysis, 4th ed. PWS-Kent, 1989, ISBN 0-53491-585-X, pp. 126-131.
class CVMappingFile
Used to load CvMapping files.
class CVMappingRule
Representation of a CV Mapping rule used by CVMappings.
class CVMappings
Representation of controlled vocabulary mapping rules (for PSI formats)
class CVMappingTerm
Representation of controlled vocabulary term.
class CVReference
Controlled Vocabulary Reference.
class CVTerm
Representation of controlled vocabulary term.
class CVTermList
Representation of controlled vocabulary term list.
class CVTermListInterface
Interface to the controlled vocabulary term list.
class DataFilterDialog
Dialog for creating and changing a DataFilter.
class DataFilters
DataFilter array providing some convenience functions.
class DataProcessing
Description of the applied preprocessing steps.
class DataProcessingVisualizer
Class that displays all meta information for DataProcessing objects.
class DataValue
Class to hold strings, numeric values, lists of strings and lists of numeric values.
class Date
Date Class.
class DateTime
DateTime Class.
struct DaTrait
class DBoundingBox
A D-dimensional bounding box.
class DeconvPeak
class DecoyHelper
Helper class for calculcations on decoy proteins.
class DefaultParamHandler
A base class for all classes handling default parameters.
class Deisotoper
class DeNovoAlgorithm
Base class for ion scoring implementation for de novo algorithms.
class DeNovoIdentification
Base class for de novo identification.
class DeNovoIonScoring
Base class for ion scoring implementation for de novo algorithms.
class DeNovoPostScoring
Base class for ion scoring implementation for de novo algorithms.
class DetectabilitySimulation
Simulates peptide detectability.
class DiaPrescore
Scoring of an spectrum given library intensities of a transition group.
class DIAScoring
Scoring of an spectrum at the peak apex of an chromatographic elution peak.
class Digestion
Meta information about digestion of a sample.
class DigestionEnzyme
Abstract base class for digestion enzymes.
class DigestionEnzymeDB
Digestion enzyme database (base class)
class DigestionEnzymeProtein
Representation of a digestion enzyme for proteins (protease)
class DigestionEnzymeRNA
Representation of a digestion enzyme for RNA (RNase)
class DigestionVisualizer
Class that displays all meta information of digestion objects.
class DigestSimulation
Simulates protein digestion.
class DistanceMatrix
A two-dimensional distance matrix, similar to OpenMS::Matrix.
class DocumentIdentifier
Manage source document information.
class DocumentIdentifierVisualizer
Class that displays all meta information for DocumentIdentifier objects.
class DocumentIDTagger
Tags OpenMS file containers with a DocumentID.
struct DPeak
Metafunction to choose among Peak1D respectively Peak2D through a template argument.
class DPosition
Representation of a coordinate in D-dimensional space.
class DRange
A D-dimensional half-open interval.
class DTA2DFile
DTA2D File adapter.
class DTAFile
File adapter for DTA files.
class EDTAFile
File adapter for Enhanced DTA files.
class EGHFitter1D
Exponential-Gaussian hybrid distribution fitter (1-dim.) using Levenberg-Marquardt algorithm (Eigen implementation) for parameter optimization.
class EGHModel
Exponential-Gaussian hybrid distribution model for elution profiles.
class EGHTraceFitter
A RT Profile fitter using an Exponential Gaussian Hybrid background model.
class Element
Representation of an element.
class ElementDB
Stores elements.
class ElutionModelFitter
Helper class for fitting elution models to features.
class ElutionPeakDetection
Extracts chromatographic peaks from a mass trace.
class EmgFitter1D
Exponentially modified gaussian distribution fitter (1-dim.) using Levenberg-Marquardt algorithm (Eigen implementation) for parameter optimization.
class EmgGradientDescent
Compute the area, background and shape metrics of a peak.
class EmgGradientDescent_friend
class EmgModel
Exponentially modified gaussian distribution model for elution profiles.
class EmgScoring
Scoring of an elution peak using an exponentially modified gaussian distribution model.
class EmpiricalFormula
Representation of an empirical formula.
class EnhancedTabBar
Convenience tab bar implementation.
class EnhancedTabBarWidgetInterface
Widgets that are placed into an EnhancedTabBar must implement this interface.
class EnhancedWorkspace
class EnzymaticDigestion
Class for the enzymatic digestion of sequences.
class EnzymaticDigestionLogModel
Class for the Log L model of enzymatic digestion of proteins.
struct EqualInTolerance
Struct for binary predicate to consider equality with a certain tolerance.
class EuclideanSimilarity
CompareFunctor for 2Dpoints.
class ExperimentalDesign
Representation of the Experimental Design in OpenMS. Instances can be loaded via the ExperimentalDesignFile class.
class ExperimentalDesignFile
Provides means to load an ExperimentalDesign from a TSV file.
class ExperimentalSettings
Description of the experimental settings.
class ExperimentalSettingsVisualizer
Class that displays all meta information for ExperimentalSettings objects.
class ExtendedIsotopeFitter1D
Extended isotope distribution fitter (1-dim.) approximated using linear interpolation.
class ExtendedIsotopeModel
Extended isotope distribution approximated using linear interpolation.
class Factory
Returns FactoryProduct* based on the name of the desired concrete FactoryProduct.
class FactoryBase
Base class for Factory<T>
class FakeProcess
A FakeProcess class.
class FalseDiscoveryRate
Calculates false discovery rates (FDR) from identifications.
class FASTAContainer
template parameter for vector-based FASTA access
class FASTAContainer< TFI_File >
FASTAContainer<TFI_File> will make FASTA entries available chunk-wise from start to end by loading it from a FASTA file. This avoids having to load the full file into memory. While loading, the container will memorize the file offsets of each entry, allowing to read an arbitrary i'th entry again from disk. If possible, only entries from the currently cached chunk should be queried, otherwise access will be slow.
class FASTAContainer< TFI_Vector >
FASTAContainer<TFI_Vector> simply takes an existing vector of FASTAEntries and provides the same interface with a potentially huge speed benefit over FASTAContainer<TFI_File> since it does not need disk access, but at the cost of memory.
class FASTAFile
This class serves for reading in and writing FASTA files.
class Feature
An LC-MS feature.
class FeatureDeconvolution
An algorithm to decharge features (i.e. as found by FeatureFinder).
class FeatureDistance
A functor class for the calculation of distances between features or consensus features.
class FeatureEditDialog
Dialog for editing a feature.
class FeatureFileOptions
Options for loading files containing features.
class FeatureFinder
The main feature finder class.
class FeatureFinderAlgorithm
Abstract base class for FeatureFinder algorithms.
class FeatureFinderAlgorithmIsotopeWavelet
Implements the isotope wavelet feature finder.
class FeatureFinderAlgorithmMRM
FeatureFinderAlgorithm for MRM experiments.
class FeatureFinderAlgorithmPicked
FeatureFinderAlgorithm for picked peaks.
struct FeatureFinderAlgorithmPickedHelperStructs
Wrapper struct for all the classes needed by the FeatureFinderAlgorithmPicked and the associated classes.
class FeatureFinderAlgorithmSH
The Superhirn FeatureFinderAlgorithm.
class FeatureFinderAlgorithmSHCtrl
A facade for various Superhirn FeatureFinder classes. Use FeatureFinderAlgorithmSH instead.
struct FeatureFinderDefs
The purpose of this struct is to provide definitions of classes and typedefs which are used throughout all FeatureFinder classes.
class FeatureFinderIdentificationAlgorithm
class FeatureFinderMultiplexAlgorithm
class FeatureFindingMetabo
Method for the assembly of mass traces belonging to the same isotope pattern, i.e., that are compatible in retention times, mass-to-charge ratios, and isotope abundances.
class FeatureGroupingAlgorithm
Base class for all feature grouping algorithms.
class FeatureGroupingAlgorithmKD
A feature grouping algorithm for unlabeled data.
class FeatureGroupingAlgorithmLabeled
A map feature grouping algorithm for labeling techniques with two labels.
class FeatureGroupingAlgorithmQT
A feature grouping algorithm for unlabeled data.
class FeatureGroupingAlgorithmUnlabeled
A map feature grouping algorithm for unlabeled data.
class FeatureHandle
Representation of a Peak2D, RichPeak2D or Feature .
class FeatureHypothesis
Internal structure used in FeatureFindingMetabo that keeps track of a feature hypothesis (isotope group hypothesis).
class FeatureLCProfile
class FeatureMap
A container for features.
class FeatureMapping
class FeatureOpenMS
An implementation of the OpenSWATH Feature Access interface using OpenMS.
class FeatureXMLFile
This class provides Input/Output functionality for feature maps.
class File
Basic file handling operations.
class FileHandler
Facilitates file handling by file type recognition.
struct FileTypes
Centralizes the file types recognized by FileHandler.
class FileWatcher
Watcher that monitors file changes.
class FilterFunctor
A FilterFunctor extracts some spectrum characteristics for quality assessment.
class FineIsotopePatternGenerator
Isotope pattern generator for fine isotope distributions.
class Fitter1D
Abstract base class for all 1D-dimensional model fitter.
class FLASHDeconvAlgorithm
struct FLASHDeconvHelperStructs
Wrapper struct for all the structs needed by the FLASHDeconv.
class FragmentMassError
class FTPeakDetectController
class FullSwathFileConsumer
Abstract base class which can consume spectra coming from SWATH experiment stored in a single file.
class FuzzyStringComparator
Fuzzy comparison of strings, tolerates numeric differences.
class GaussFilter
This class represents a Gaussian lowpass-filter which works on uniform as well as on non-uniform profile data.
class GaussFilterAlgorithm
This class represents a Gaussian lowpass-filter which works on uniform as well as on non-uniform profile data.
class GaussFitter1D
Gaussian distribution fitter (1-dim.) approximated using linear interpolation.
class GaussModel
Normal distribution approximated using linear interpolation.
class GaussTraceFitter
Fitter for RT profiles using a Gaussian background model.
class GoodDiffFilter
GoodDiffFilter counts the number ob peak pairs whose m/z difference can be explained by a amino acid loss.
class Gradient
Representation of a HPLC gradient.
class GradientVisualizer
GradientVisualizer is a visualizer class for objects of type gradient.
class GridBasedCluster
basic data structure for clustering
class GridBasedClustering
2D hierarchical clustering implementation optimized for large data sets containing many small clusters i.e. dimensions of clusters << dimension of entire dataset
class GridFeature
Representation of a feature in a hash grid.
class GridSearch
class GUIHelpers
Class which holds static GUI-related helper functions.
class GUIProgressLoggerImpl
Implements a GUI version of the ProgressLoggerImpl.
class GzipIfstream
Decompresses files which are compressed in the gzip format (*.gzip)
class GzipInputStream
Implements the BinInputStream class of the xerces-c library in order to read gzip compressed XML files.
class HasActivationMethod
Predicate that determines if a spectrum was generated using any activation method given in the constructor list.
class HashGrid
Container for (2-dimensional coordinate, value) pairs.
class HasMetaValue
Predicate that determines if a class has a certain metavalue.
class HasPrecursorCharge
Predicate that determines if a spectrum has a certain precursor charge as given in the constructor list.
class HasScanMode
Predicate that determines if a spectrum has a certain scan mode.
class HasScanPolarity
Predicate that determines if a spectrum has a certain scan polarity.
class HDF5Connector
File adapter for HDF5 files.
class HiddenMarkovModel
Hidden Markov Model implementation of PILIS.
class HistogramDialog
Dialog that show a HistogramWidget.
class HistogramWidget
Widget which can visualize a histogram.
class HMMState
Hidden Markov Model State class for the Hidden Markov Model.
class HPLC
Representation of a HPLC experiment.
class HPLCVisualizer
Class that displays all meta information for HPLC objects.
struct HyperScore
An implementation of the X!Tandem HyperScore PSM scoring function.
class IBSpectraFile
Implements the export of consensusmaps into the IBSpectra format used by isobar to load quantification results.
class ICPLLabeler
Simulate ICPL experiments.
class IDConflictResolverAlgorithm
class IDDecoyProbability
IDDecoyProbability calculates probabilities using decoy approach.
class Identification
Represents a object which can store the information of an analysisXML instance.
class IdentificationData
Representation of spectrum identification results and associated data.
class IdentificationDataConverter
class IdentificationHit
Represents a object which can store the information of an analysisXML instance.
class IDFilter
Collection of functions for filtering peptide and protein identifications.
class IDMapper
Annotates an MSExperiment, FeatureMap or ConsensusMap with peptide identifications.
class IDMergerAlgorithm
Creates a new Protein ID run into which other runs can be inserted. Creates union of protein hits but concatenates PSMs. Checks search engine consistency of all inserted runs. It differs from the IDMerger tool, in that it is an algorithm class and it allows inserting multiple peptide hits per peptide sequence (not only the first occurrence).
class IDRipper
Ripping protein/peptide identification according their file origin.
class IDScoreGetterSetter
A class for extracting and reinserting IDScores from Peptide/ProteinIdentifications and from ConsensusMaps.
class IdXMLFile
Used to load and store idXML files.
class ILPDCWrapper
class IncludeExcludeTarget
This class stores a SRM/MRM transition.
class InclusionExclusionList
Provides functionality for writing inclusion or exclusion lists.
class IndexedMzMLDecoder
A class to analyze indexedmzML files and extract the offsets of individual tags.
class IndexedMzMLFileLoader
A class to load an indexedmzML file.
class INIFileEditorWindow
shows the ParamEditor widget in a QMainWindow with a toolbar
class InIntensityRange
Predicate that determines if a peak lies inside/outside a specific intensity range.
class INIUpdater
class InMSLevelRange
Predicate that determines if a spectrum lies inside/outside a specific MS level set.
class InMzRange
Predicate that determines if a peak lies inside/outside a specific m/z range.
class InPrecursorMZRange
Predicate that determines if a spectrum's precursor is within a certain m/z range.
class InRTRange
Predicate that determines if a spectrum lies inside/outside a specific retention time range.
class InspectInfile
Inspect input file adapter.
class InspectOutfile
Representation of an Inspect outfile.
class Instrument
Description of a MS instrument.
class InstrumentSettings
Description of the settings a MS Instrument was run with.
class InstrumentSettingsVisualizer
Class that displays all meta information for InstrumentSettings objects.
class InstrumentVisualizer
Class that displays all meta information for an MS instrument.
class IntensityBalanceFilter
IntensityBalanceFilter divides the m/z-range into ten regions and sums the intensity in these regions.
class InternalCalibration
A mass recalibration method using linear/quadratic interpolation (robust/weighted) of given reference masses.
class InterpolationModel
Abstract class for 1D-models that are approximated using linear interpolation.
class IonDetector
Description of a ion detector (part of a MS Instrument)
class IonDetectorVisualizer
Class that displays all meta information for IonDetector objects.
class IonizationSimulation
Simulates Protein ionization.
class IonMobilityScoring
A class that calls the ion mobility scoring routines.
class IonSource
Description of an ion source (part of a MS Instrument)
class IonSourceVisualizer
Class that displays all meta information for IonSource objects.
class IsEmptySpectrum
Predicate that determines if a spectrum is empty.
class IsInCollisionEnergyRange
Predicate that determines if an MSn spectrum was generated with a collision energy in the given range.
class IsInIsolationWindow
Predicate that determines if the isolation window covers ANY of the given m/z values.
class IsInIsolationWindowSizeRange
Predicate that determines if the width of the isolation window of an MSn spectrum is in the given range.
class IsobaricChannelExtractor
Extracts individual channels from MS/MS spectra for isobaric labeling experiments.
class IsobaricIsotopeCorrector
Performs isotope impurity correction on the intensities extracted from an isobaric labeling experiment.
class IsobaricNormalizer
Performs median normalization on the extracted ratios of isobaric labeling experiment.
class IsobaricQuantifier
Given the extracted channel intensities the IsobaricQuantifier corrects and normalizes the intensities for further processing.
struct IsobaricQuantifierStatistics
Statistics for quantitation performance and comparison of NNLS vs. naive method (aka matrix inversion)
class IsobaricQuantitationMethod
Abstract base class describing an isobaric quantitation method in terms of the used channels and an isotope correction matrix.
class IsoSpecGeneratorWrapper
Interface for the IsoSpec algorithm - a generator of infinitely-resolved theoretical spectra.
class IsoSpecOrderedGeneratorWrapper
Generate the stream of configurations, ordered from most likely to least likely.
class IsoSpecThresholdGeneratorWrapper
Provides a threshold-based generator of isotopologues: generates all isotopologues more probable than a given probability threshold.
class IsoSpecThresholdWrapper
A non-generator version of IsoSpecThresholdGeneratorWrapper.
class IsoSpecTotalProbGeneratorWrapper
Generate a p-set of configurations for a given p (that is, a set of configurations such that their probabilities sum up to p). The p in normal usage will usually be close to 1 (e.g. 0.99).
class IsoSpecTotalProbWrapper
Create a p-set of configurations for a given p (that is, a set of configurations such that their probabilities sum up to p). The p in normal usage will usually be close to 1 (e.g. 0.99).
class IsoSpecWrapper
A convenience class for the IsoSpec algorithm - easier to use than the IsoSpecGeneratorWrapper classes.
struct IsotopeCluster
Stores information about an isotopic cluster (i.e. potential peptide charge variants)
class IsotopeDiffFilter
IsotopeDiffFilter returns total intensity of peak pairs that could result from isotope peaks.
class IsotopeDistribution
class IsotopeDistributionCache
Pre-calculate isotope distributions for interesting mass ranges.
class IsotopeFitter1D
Isotope distribution fitter (1-dim.) approximated using linear interpolation.
class IsotopeMarker
IsotopeMarker marks peak pairs which could represent an ion and its isotope.
class IsotopeModel
Isotope distribution approximated using linear interpolation.
class IsotopePatternGenerator
Provides an interface for different isotope pattern generator methods.
class IsotopeWavelet
Implements the isotope wavelet function.
class IsotopeWaveletTransform
A class implementing the isotope wavelet transform. If you just want to find features using the isotope wavelet, take a look at the FeatureFinderAlgorithmIsotopeWavelet class. Usually, you only have to consider the class at hand if you plan to change the basic implementation of the transform.
class IsotopicDist
class IsZoomSpectrum
Predicate that determines if a spectrum is a zoom (enhanced resolution) spectrum.
class ItraqConstants
Some constants used throughout iTRAQ classes.
class ItraqEightPlexQuantitationMethod
iTRAQ 8 plex quantitation to be used with the IsobaricQuantitation.
class ItraqFourPlexQuantitationMethod
iTRAQ 4 plex quantitation to be used with the IsobaricQuantitation.
class ITRAQLabeler
Simulate iTRAQ experiments.
class JavaInfo
Detect Java and retrieve information.
class KDTreeFeatureMaps
Stores a set of features, together with a 2D tree for fast search.
class KDTreeFeatureNode
A node of the kD-tree with pointer to corresponding data and index.
class KroenikFile
File adapter for Kroenik (HardKloer sibling) files.
class LabeledPairFinder
The LabeledPairFinder allows the matching of labeled features (features with a fixed distance).
class LabelFreeLabeler
Abstract base class for all kinds of labeling techniques.
class LayerData
Class that stores the data for one layer.
class LayerStatisticsDialog
Dialog showing statistics about the data of the current layer.
class LCElutionPeak
class LCMS
class LCMSCData
class LevMarqFitter1D
Abstract class for 1D-model fitter using Levenberg-Marquardt algorithm for parameter optimization.
struct LexicographicComparator
A wrapper class that combines two comparators lexicographically. Normally you should use the make-function lexicographicComparator() because then you do not need to specify the template arguments.
class LibSVMEncoder
Serves for encoding sequences into feature vectors.
class LinearResampler
Linear Resampling of raw data.
class LinearResamplerAlign
Linear Resampling of raw data with alignment.
class ListEditor
Editor for editing int, double and string lists (including output and input file lists)
class ListUtils
Collection of utility functions for management of vectors.
class LocalLinearMap
Trained Local Linear Map (LLM) model for peak intensity prediction.
class LogConfigHandler
The LogConfigHandler provides the functionality to configure the internal logging of OpenMS algorithms that use the global instances of LogStream.
class LowessSmoothing
LOWESS (locally weighted scatterplot smoothing).
class LPWrapper
class Map
Map class based on the STL map (containing several convenience functions)
class MapAlignmentAlgorithmIdentification
A map alignment algorithm based on peptide identifications from MS2 spectra.
class MapAlignmentAlgorithmKD
An efficient reference-free feature map alignment algorithm for unlabeled data.
class MapAlignmentAlgorithmPoseClustering
A map alignment algorithm based on pose clustering.
class MapAlignmentAlgorithmSpectrumAlignment
A map alignment algorithm based on spectrum similarity (dynamic programming).
class MapAlignmentEvaluationAlgorithm
Base class for all Caap evaluation algorithms.
class MapAlignmentEvaluationAlgorithmPrecision
Caap evaluation algorithm to obtain a precision value.
class MapAlignmentEvaluationAlgorithmRecall
Caap evaluation algorithm to obtain a recall value.
class MapAlignmentTransformer
This class collects functions for applying retention time transformations to data structures.
class MapConversion
class MarkerMower
MarkerMower uses PeakMarker to find peaks, those that are not marked get removed.
class MascotGenericFile
Read/write Mascot generic files (MGF).
class MascotInfile
Mascot input file adapter.
class MascotRemoteQuery
Class which handles the communication between OpenMS and the Mascot server.
class MascotXMLFile
Used to load Mascot XML files.
class MassAnalyzer
Description of a mass analyzer (part of a MS Instrument)
class MassAnalyzerVisualizer
Class that displays all meta information for MassAnalyzer objects.
class MassDecomposition
Class represents a decomposition of a mass into amino acids.
class MassDecompositionAlgorithm
Mass decomposition algorithm, given a mass it suggests possible compositions.
class MassExplainer
computes empirical formulas for given mass differences using a set of allowed elements
class MassFeatureTrace
class MassTrace
A container type that gathers peaks similar in m/z and moving along retention time.
class MasstraceCorrelator
Correlates individual masstraces found in mass spectrometric maps.
class MassTraceDetection
A mass trace extraction method that gathers peaks similar in m/z and moving along retention time.
class MatchedIterator
For each element in the reference container the closest peak in the target will be searched. If no match is found within the tolerance window, the peak will be skipped over.
class Matrix
A two-dimensional matrix. Similar to std::vector, but uses a binary operator(,) for element access.
class MaxLikeliFitter1D
Abstract base class for all 1D-model fitters using maximum likelihood optimization.
class MetaboliteFeatureDeconvolution
An algorithm to decharge small molecule features (i.e. as found by FeatureFinder).
class MetaboliteSpectralMatching
class MetaboTargetedAssay
This class provides methods for the extraction of targeted assays for metabolomics.
class MetaDataBrowser
A meta data visualization widget.
class MetaInfo
A Type-Name-Value tuple class.
class MetaInfoDescription
Description of the meta data arrays of MSSpectrum.
class MetaInfoDescriptionVisualizer
Class that displays all meta information for MetaInfoDescription objects.
class MetaInfoInterface
Interface for classes that can store arbitrary meta information (Type-Name-Value tuples).
class MetaInfoInterfaceUtils
Utilities operating on containers inheriting from MetaInfoInterface.
class MetaInfoRegistry
Registry which assigns unique integer indices to strings.
class MetaInfoVisualizer
MetaInfoVisualizer is a visualizer class for all classes that use one MetaInfo object as member.
class MinimumDistance
basic data structure for distances between clusters
class MissedCleavages
This class is a metric for the QualityControl TOPP Tool.
class ModelDescription
Stores the name and parameters of a model.
class Modification
Meta information about chemical modification of a sample.
class ModificationDefinition
Representation of modification definition.
class ModificationDefinitionsSet
Representation of a set of modification definitions.
class ModificationsDB
database which holds all residue modifications from UniMod
class ModificationVisualizer
Class that displays all meta information of modification objects.
class ModifiedNASequenceGenerator
class ModifiedPeptideGenerator
struct MorpheusScore
An implementation of the Morpheus PSM scoring function Inspired by a C# implementation by C. Wenger released under MIT license.
class MorphologicalFilter
This class implements baseline filtering operations using methods from mathematical morphology.
class MRMAssay
Generate assays from a TargetedExperiment.
class MRMBatchFeatureSelector
class MRMDecoy
This class generates a TargetedExperiment object with decoys based on a TargetedExperiment object.
class MRMFeature
A multi-chromatogram MRM feature.
class MRMFeatureFilter
The MRMFeatureFilter either flags components and/or transitions that do not pass the QC criteria or filters out components and/or transitions that do not pass the QC criteria.
class MRMFeatureFinderScoring
The MRMFeatureFinder finds and scores peaks of transitions that co-elute.
class MRMFeatureOpenMS
An implementation of the OpenSWATH MRM Feature Access interface using OpenMS.
class MRMFeaturePicker
_MRMFeaturePicker_ defines the structures containing parameters to be used in [MRMTransitionGroupPicker](MRMTransitionGroupPicker) for components and components groups.
class MRMFeaturePickerFile
_MRMFeaturePickerFile_ loads components and components groups parameters from a .csv file.
class MRMFeatureQC
The MRMFeatureQC is a class to handle the parameters and options for MRMFeatureFilter.
class MRMFeatureQCFile
File adapter for MRMFeatureQC files.
class MRMFeatureSelector
class MRMFeatureSelector_test
class MRMFeatureSelectorQMIP
class MRMFeatureSelectorScore
class MRMFragmentSelection
This class can select appropriate fragment ions of an MS/MS spectrum of a peptide.
class MRMIonSeries
Generate theoretical fragment ion series for use in MRMAssay and MRMDecoy.
class MRMMapping
A class to map targeted assays to chromatograms.
class MRMRTNormalizer
The MRMRTNormalizer will find retention time peptides in data.
class MRMTransitionGroup
The representation of a group of transitions in a targeted proteomics experiment.
class MRMTransitionGroupPicker
The MRMTransitionGroupPicker finds peaks in chromatograms that belong to the same precursors.
class MS1FeatureMerger
struct MS1Signal
class MS2ConsensusSpectrum
class MS2Feature
class MS2File
MS2 input file adapter.
class MS2Fragment
class Ms2IdentificationRate
This class is a metric for the QualityControl-ToppTool.
class MS2Info
class Ms2SpectrumStats
QC metric to determine the number of MS2 scans per MS1 scan over RT.
class MSChromatogram
The representation of a chromatogram.
class MSDataAggregatingConsumer
Aggregates spectra by retention time.
class MSDataCachedConsumer
Transforming and cached writing consumer of MS data.
class MSDataChainingConsumer
Consumer class that passes all consumed data through a set of operations.
class MSDataSqlConsumer
A data consumer that inserts MS data into a SQLite database.
class MSDataStoringConsumer
Consumer class that simply stores the data.
class MSDataTransformingConsumer
Transforming consumer of MS data.
class MSDataWritingConsumer
Consumer class that writes MS data to disk using the mzML format.
class MSExperiment
In-Memory representation of a mass spectrometry experiment.
class MsInspectFile
File adapter for MsInspect files.
class MSNumpressCoder
Class to encode and decode data encoded with MSNumpress.
class MSPeak
class MSPFile
File adapter for MSP files (NIST spectra library)
class MSPGenericFile
Load MSP text file and save it into an `MSExperiment`.
class MSPGenericFile_friend
class MSQuantifications
class MSSim
Central class for simulation of mass spectrometry experiments.
class MSSpectrum
The representation of a 1D spectrum.
class MSstatsFile
File adapter for MzTab files.
class MultiGradient
A gradient of multiple colors and arbitrary distances between colors.
class MultiGradientSelector
A widget witch allows constructing gradients of multiple colors.
class MultiplexClustering
clusters results from multiplex filtering
class MultiplexDeltaMasses
data structure for mass shift pattern
class MultiplexDeltaMassesGenerator
generates complete list of all possible mass shifts due to isotopic labelling
class MultiplexFilteredMSExperiment
data structure storing all peaks (and optionally their raw data points) of an experiment corresponding to one specific peak pattern
class MultiplexFilteredPeak
data structure storing a single peak that passed all filters
class MultiplexFiltering
base class for filtering centroided and profile data for peak patterns
class MultiplexFilteringCentroided
filters centroided data for peak patterns
class MultiplexFilteringProfile
filters centroided and profile data for peak patterns
class MultiplexIsotopicPeakPattern
data structure for pattern of isotopic peaks
class MultiplexSatelliteCentroided
data structure storing a single satellite peak
class MultiplexSatelliteProfile
data structure storing a single satellite data point
class MzCalibration
QC metric calculating (un)calibrated m/z error.
class MzDataFile
File adapter for MzData files.
class MzIdentMLFile
File adapter for MzIdentML files.
class MzMLFile
File adapter for MzML files.
class MzMLSpectrumDecoder
A class to decode input strings that contain an mzML chromatogram or spectrum tag.
class MzMLSwathFileConsumer
On-disk mzML implementation of FullSwathFileConsumer.
class MzQuantMLFile
File adapter for MzQuantML files.
class MzTab
Data model of MzTab files. Please see the official MzTab specification at https://code.google.com/p/mztab/.
struct MzTabAssayMetaData
class MzTabBoolean
struct MzTabContactMetaData
struct MzTabCVMetaData
class MzTabDouble
class MzTabDoubleList
class MzTabFile
File adapter for MzTab files.
struct MzTabInstrumentMetaData
class MzTabInteger
class MzTabIntegerList
class MzTabMetaData
all meta data of a mzTab file. Please refer to specification for documentation.
class MzTabModification
class MzTabModificationList
struct MzTabModificationMetaData
struct MzTabMSRunMetaData
struct MzTabNucleicAcidSectionRow
NUC - Nucleic acid section (table-based)
class MzTabNullAbleBase
base class for atomic, non-container types (Double, Int)
class MzTabNullAbleInterface
basic interface for all MzTab datatypes (can be null; are converted from and to cell string)
class MzTabNullNaNAndInfAbleBase
base class for the atomic non-container like MzTab data types (Double, Int)
class MzTabNullNaNAndInfAbleInterface
interface for NaN- and Inf- able datatypes (Double and Integer in MzTab). These are as well null-able
struct MzTabOligonucleotideSectionRow
OLI - Oligonucleotide section (table-based)
struct MzTabOSMSectionRow
OSM - OSM (oligonucleotide-spectrum match) section (table-based)
class MzTabParameter
class MzTabParameterList
struct MzTabPeptideSectionRow
PEP - Peptide section (Table based)
struct MzTabProteinSectionRow
PRT - Protein section (Table based)
struct MzTabPSMSectionRow
PSM - PSM section (Table based)
struct MzTabSampleMetaData
struct MzTabSmallMoleculeSectionRow
SML Small molecule section (table based)
struct MzTabSoftwareMetaData
class MzTabSpectraRef
class MzTabString
class MzTabStringList
struct MzTabStudyVariableMetaData
class MZTrafoModel
Create and apply models of a mass recalibration function.
class MzXMLFile
File adapter for MzXML 3.1 files.
class NASequence
Representation of a nucleic acid sequence.
class NetworkGetRequest
class NeutralLossDiffFilter
NeutralLossDiffFilter returns the total intensity ob peak pairs whose m/z difference can be explained by a neutral loss.
class NeutralLossMarker
NeutralLossMarker marks peak pairs which could represent an ion an its neutral loss (water, ammonia)
class NLargest
NLargest removes all but the n largest peaks.
class NonNegativeLeastSquaresSolver
Wrapper for a non-negative least squares (NNLS) solver.
class NoopMSDataConsumer
Consumer class that performs no operation.
class NoopMSDataWritingConsumer
Consumer class that perform no operation.
class Normalizer
Normalizes the peak intensities spectrum-wise.
class NucleicAcidSpectrumGenerator
Generates theoretical spectra for nucleic acid sequences.
class O18Labeler
Simulate O-18 experiments.
class OfflinePrecursorIonSelection
Implements different algorithms for precursor ion selection.
class OMSSACSVFile
File adapter for OMSSACSV files.
class OMSSAXMLFile
Used to load OMSSAXML files.
class OnDiscMSExperiment
Representation of a mass spectrometry experiment on disk.
class OpenPepXLAlgorithm
class OpenPepXLLFAlgorithm
struct OpenSwath_Ind_Scores
struct OpenSwath_Scores
A structure to hold the different scores computed by OpenSWATH.
struct OpenSwath_Scores_Usage
A structure to store which scores should be used by the OpenSWATH Algorithm.
class OpenSwathCalibrationWorkflow
Execute all steps for retention time and m/z calibration of SWATH-MS data.
class OpenSwathDataAccessHelper
Several helpers to convert OpenMS datastructures to structures that implement the OpenSWATH interfaces.
class OpenSwathHelper
A helper class that is used by several OpenSWATH tools.
class OpenSwathOSWWriter
Class to write out an OpenSwath OSW SQLite output (PyProphet input).
class OpenSwathScoring
A class that calls the scoring routines.
class OpenSwathTSVWriter
Class to write out an OpenSwath TSV output (mProphet input).
class OpenSwathWorkflow
Execute all steps in an OpenSwath analysis.
class OpenSwathWorkflowBase
class OpenSwathWorkflowSonar
Execute all steps in an OpenEcho analysis (OpenSwath for SONAR data)
class OptimizePeakDeconvolution
This class provides the deconvolution of peak regions using non-linear optimization.
class OptimizePick
This class provides the non-linear optimization of the peak parameters.
class OPXLDataStructs
class OPXLHelper
The OPXLHelper class contains functions needed by OpenPepXL and OpenPepXLLF to reduce duplicated code.
class OPXLSpectrumProcessingAlgorithms
class OSWFile
This class serves for reading in and writing OpenSWATH OSW files.
struct PairComparatorFirstElement
Class for comparison of std::pair using first ONLY e.g. for use with std::sort.
struct PairComparatorFirstElementMore
Class for comparison of std::pair using first ONLY e.g. for use with std::sort.
struct PairComparatorSecondElement
Class for comparison of std::pair using second ONLY e.g. for use with std::sort.
struct PairComparatorSecondElementMore
Class for comparison of std::pair using second ONLY e.g. for use with std::sort.
struct PairMatcherFirstElement
Class for comparison of std::pair using first ONLY e.g. for use with std::sort.
struct PairMatcherSecondElement
Struct for comparison of std::pair using second ONLY e.g. for use with std::sort.
class Param
Management and storage of parameters / INI files.
class ParamEditor
A GUI for editing or viewing a Param object.
struct ParameterInformation
Struct that captures all information of a command line parameter.
class ParamXMLFile
The file pendant of the Param class used to load and store the param datastructure as paramXML.
class ParentPeakMower
ParentPeakMower gets rid of high peaks that could stem from unfragmented precursor ions.
class Peak1D
A 1-dimensional raw data point or peak.
class Peak2D
A 2-dimensional raw data point or peak.
class PeakAlignment
make a PeakAlignment of two PeakSpectra
struct PeakCandidate
A small structure to hold peak candidates.
class PeakFileOptions
Options for loading files containing peak data.
class PeakGroupScoring
struct PeakIndex
Index of a peak or feature.
class PeakIntegrator
Compute the area, background and shape metrics of a peak.
class PeakIntensityPredictor
Predict peak heights of peptides based on Local Linear Map model.
class PeakMarker
PeakMarker marks peaks that seem to fulfill some criterion.
class PeakPickerCWT
This class implements a peak picking algorithm using wavelet techniques.
class PeakPickerHiRes
This class implements a fast peak-picking algorithm best suited for high resolution MS data (FT-ICR-MS, Orbitrap). In high resolution data, the signals of ions with similar mass-to-charge ratios (m/z) exhibit little or no overlapping and therefore allow for a clear separation. Furthermore, ion signals tend to show well-defined peak shapes with narrow peak width.
class PeakPickerIterative
This class implements a peak-picking algorithm for high-resolution MS data (specifically designed for TOF-MS data).
class PeakPickerMaxima
This class implements a fast peak-picking algorithm best suited for high resolution MS data (FT-ICR-MS, Orbitrap). In high resolution data, the signals of ions with similar mass-to-charge ratios (m/z) exhibit little or no overlapping and therefore allow for a clear separation. Furthermore, ion signals tend to show well-defined peak shapes with narrow peak width.
class PeakPickerMRM
The PeakPickerMRM finds peaks a single chromatogram.
class PeakPickerSH
class PeakShape
Internal representation of a peak shape (used by the PeakPickerCWT)
class PeakSpectrumCompareFunctor
Base class for compare functors of spectra, that return a similarity value for two spectra.
class PeakTypeEstimator
Estimates if the data of a spectrum is raw data or peak data.
class PeakWidthEstimator
Rough estimation of the peak width at m/z.
class PepNovoInfile
PepNovo input file adapter.
class PepNovoOutfile
Representation of a PepNovo output file.
class PeptideAndProteinQuant
Helper class for peptide and protein quantification based on feature data annotated with IDs.
class PeptideEvidence
Representation of a peptide evidence.
class PeptideHit
Representation of a peptide hit.
class PeptideHitVisualizer
Class that displays all meta information for PeptideHit objects.
class PeptideIdentification
Represents the peptide hits for a spectrum.
class PeptideIdentificationVisualizer
Class that displays all meta information for PeptideIdentification objects.
class PeptideIndexing
Refreshes the protein references for all peptide hits in a vector of PeptideIdentifications and adds target/decoy information.
class PeptideProteinResolution
Resolves shared peptides based on protein scores.
class PepXMLFile
Used to load and store PepXML files.
class PepXMLFileMascot
Used to load Mascot PepXML files.
class PercolatorFeatureSetHelper
Percolator feature set and integration helper.
class PercolatorOutfile
Class for reading Percolator tab-delimited output files.
class PlainMSDataWritingConsumer
Consumer class that writes MS data to disk using the mzML format.
struct PointerComparator
Wrapper that takes a comparator for `something' and makes a comparator for pointers to `something' out of it. Normally you should use the make-function pointerComparator() because then you do not need to specify the template arguments.
class PoseClusteringAffineSuperimposer
A superimposer that uses a voting scheme, also known as pose clustering, to find a good affine transformation.
class PoseClusteringShiftSuperimposer
A superimposer that uses a voting scheme, also known as pose clustering, to find a good shift transformation.
struct PpmTrait
struct PrecisionWrapper
Wrapper class to implement output with appropriate precision. See precisionWrapper().
class Precursor
Precursor meta information.
class PrecursorCorrection
This class provides methods for precursor correction.
class PrecursorIonSelection
This class implements different precursor ion selection strategies.
class PrecursorIonSelectionPreprocessing
This class implements the database preprocessing needing for precursor ion selection.
struct PrecursorMassComparator
class PrecursorPurity
Precursor purity or noise estimation.
class PrecursorVisualizer
Class that displays all meta information for Precursor objects.
struct ProbablePhosphoSites
class ProcessData
class Product
Product meta information.
class ProductModel
Class for product models i.e. models with D independent dimensions.
class ProductModel< 2 >
The class template is only implemented for D=2 because we use Peak2D here.
class ProductVisualizer
Class that displays all meta information for Product objects.
class ProgressLogger
Base class for all classes that want to report their progress.
class ProteaseDB
Database for enzymes that digest proteins (proteases)
class ProteaseDigestion
Class for the enzymatic digestion of proteins.
class ProteinHit
Representation of a protein hit.
class ProteinHitVisualizer
Class that displays all meta information for ProteinHit objects.
class ProteinIdentification
Representation of a protein identification run.
class ProteinIdentificationVisualizer
Class that displays all meta information for ProteinIdentification objects.
class ProteinInference
[experimental class] given a peptide quantitation, infer corresponding protein quantities
class ProteinResolver
Helper class for peptide and protein quantification based on feature data annotated with IDs.
class ProtonDistributionModel
A proton distribution model to calculate the proton distribution over charged peptides.
class ProtXMLFile
Used to load (storing not supported, yet) ProtXML files.
struct PScore
Implementation of the PScore PSM scoring algorithm.
class PSLPFormulation
Implements ILP formulation of precursor selection problems.
class PSProteinInference
This class implements protein inference for the precursor ion selection strategies.
class PTMXMLFile
Used to load and store PTMXML files.
class QApplicationTOPP
Extension to the QApplication for running TOPPs GUI tools.
class QCBase
This class serves as an abstract base class for all QC classes.
class QcMLFile
File adapter for QcML files used to load and store QcML files.
class QTCluster
A representation of a QT cluster used for feature grouping.
class QTClusterFinder
A variant of QT clustering for the detection of feature groups.
class QuantitativeExperimentalDesign
Merge files according to experimental design.
class RangeManager
Handles the management of a position and intensity range.
class RawData
class RawMSSignalSimulation
Simulates MS signals for a given set of peptides.
class RawTandemMSSignalSimulation
Simulates tandem MS signals for a given set of peptides.
class ReactionMonitoringTransition
This class stores a SRM/MRM transition.
class RegularSwathFileConsumer
In-memory implementation of FullSwathFileConsumer.
class Residue
Representation of a residue.
class ResidueDB
residue data base which holds residues
class ResidueModification
Representation of a modification.
struct ReverseComparator
Wrapper that reverses (exchanges) the two arguments of a comparator. Normally you should use the make-function reverseComparator() because then you do not need to specify the template arguments.
class Ribonucleotide
Representation of a ribonucleotide (modified or unmodified)
class RibonucleotideDB
Database of ribonucleotides (modified and unmodified)
class RichPeak2D
A 2-dimensional raw data point or peak with meta information.
class RNaseDB
Database for enzymes that digest RNA (RNases)
class RNaseDigestion
Class for the enzymatic digestion of RNAs.
struct RNPxlMarkerIonExtractor
struct RNPxlModificationMassesResult
class RNPxlModificationsGenerator
struct RNPxlReport
create report
struct RNPxlReportRow
struct to hold a single report line
struct RNPxlReportRowHeader
create header line
class RTAlignment
Take the original retention time before map alignment and use the alignment's trafoXML for calculation of the new alignment retention times.
class RTSimulation
Simulates/Predicts retention times for peptides or peptide separation.
class RWrapper
R-Wrapper Class.
class Sample
Meta information about the sample.
class SampleTreatment
Base class for sample treatments (Digestion, Modification, Tagging, ...)
class SampleVisualizer
Class that displays all meta information of sample objects.
class SaveImageDialog
Dialog for saving an image.
class SavitzkyGolayFilter
Computes the Savitzky-Golay filter coefficients using QR decomposition.
class Scaler
Scaler scales the peak by ranking the peaks and assigning intensity according to rank.
struct ScanWindow
Scan window description.
class ScanWindowVisualizer
Class that displays all meta information for ScanWindow objects.
struct ScoreToTgtDecLabelPairs
class SeedListGenerator
Generate seed lists for feature detection.
class SequestInfile
Sequest input file adapter.
class SequestOutfile
Representation of a Sequest output file.
class SHFeature
class SignalToNoiseEstimator
This class represents the abstract base class of a signal to noise estimator.
class SignalToNoiseEstimatorMeanIterative
Estimates the signal/noise (S/N) ratio of each data point in a scan based on an iterative scheme which discards high intensities.
class SignalToNoiseEstimatorMedian
Estimates the signal/noise (S/N) ratio of each data point in a scan by using the median (histogram based)
class SignalToNoiseEstimatorMedianRapid
Estimates the signal/noise (S/N) ratio of each data point in a scan by using the median (window based)
class SignalToNoiseOpenMS
An implementation of the OpenSWATH SignalToNoise Access interface using OpenMS.
class SILACLabeler
Simulate SILAC experiments.
class SimpleOpenMSSpectraFactory
A factory method that returns two ISpectrumAccess implementations.
class SimplePairFinder
This class implements a simple point pair finding algorithm.
class SimpleSearchEngineAlgorithm
class SimpleSVM
Simple interface to support vector machines for classification (via LIBSVM).
class SimpleTSGXLMS
Generates theoretical spectra for cross-linked peptides.
class SingleLinkage
SingleLinkage ClusterMethod.
class SingletonRegistry
Holds pointers to unique instance of a singleton factory.
class SiriusAdapterAlgorithm
class SiriusFragmentAnnotation
class SiriusMSFile
class SiriusMzTabWriter
class Software
Description of the software used for processing.
class SoftwareVisualizer
Class that displays all meta information for Software objects.
class SONARScoring
Scoring of an spectrum using SONAR data.
class SourceFile
Description of a file location, used to store the origin of (meta) data.
class SourceFileVisualizer
Class that displays all meta information for SourceFile objects.
class SpecArrayFile
File adapter for SpecArray (.pepList) files.
class SpectraIdentificationViewWidget
Tabular visualization / selection of identified spectra.
class SpectralMatch
struct SpectralMatchScoreComparator
class SpectraMerger
Merges blocks of MS or MS2 spectra.
class SpectraSTSimilarityScore
Similarity score of SpectraST.
class SpectraViewWidget
Hierarchical visualization and selection of spectra.
class Spectrum1DCanvas
Canvas for visualization of one or several spectra.
class Spectrum1DGoToDialog
simple goto/set visible area dialog for exact placement of the viewing window
class Spectrum1DWidget
Widget for visualization of several spectra.
class Spectrum2DCanvas
Canvas for 2D-visualization of peak map, feature map and consensus map data.
class Spectrum2DGoToDialog
GoTo dialog used to zoom to a m/z and retention time range or to a feature.
class Spectrum2DWidget
Widget for 2D-visualization of peak map and feature map data.
class Spectrum3DCanvas
Canvas for 3D-visualization of peak map data.
class Spectrum3DOpenGLCanvas
OpenGL Canvas for 3D-visualization of map data.
class Spectrum3DWidget
Widget for 3D-visualization of map data.
class SpectrumAccessOpenMS
An implementation of the OpenSWATH Spectrum Access interface using OpenMS.
class SpectrumAccessOpenMSCached
An implementation of the Spectrum Access interface using on-disk caching.
class SpectrumAccessOpenMSInMemory
An implementation of the OpenSWATH Spectrum Access interface completely in memory.
class SpectrumAccessQuadMZTransforming
A transforming m/z wrapper around spectrum access using a quadratic equation.
class SpectrumAccessSqMass
An implementation of the Spectrum Access interface using SQL files.
class SpectrumAccessTransforming
An abstract base class implementing a transforming wrapper around spectrum access.
class SpectrumAddition
The SpectrumAddition is used to add up individual spectra.
class SpectrumAlignment
Aligns the peaks of two sorted spectra Method 1: Using a banded (width via 'tolerance' parameter) alignment if absolute tolerances are given. Scoring function is the m/z distance between peaks. Intensity does not play a role!
class SpectrumAlignmentDialog
Lets the user select two spectra and set the parameters for the spectrum alignment.
class SpectrumAlignmentScore
Similarity score via spectra alignment.
class SpectrumAnnotator
Annotates spectra from identifications and theoretical spectra or identifications from spectra and theoretical spectra matching with various options.
class SpectrumCanvas
Base class for visualization canvas classes.
class SpectrumCheapDPCorr
SpectrumCheapDPCorr calculates an optimal alignment on stick spectra.
class SpectrumDeconvolution
class SpectrumIdentification
Represents a object which can store the information of an analysisXML instance.
class SpectrumLookup
Helper class for looking up spectra based on different attributes.
class SpectrumMetaDataLookup
Helper class for looking up spectrum meta data.
class SpectrumPrecursorComparator
SpectrumPrecursorComparator compares just the parent mass of two spectra.
class SpectrumSettings
Representation of 1D spectrum settings.
class SpectrumSettingsVisualizer
Class that displays all meta information for SpectrumSettings objects.
class SpectrumWidget
Base class for spectrum widgets.
class SplineInterpolatedPeaks
Data structure for spline interpolation of MS1 spectra and chromatograms.
class SplinePackage
fundamental data structure for SplineInterpolatedPeaks
class SqliteConnector
File adapter for Sqlite files.
class SqMassFile
An class that uses on-disk SQLite database to read and write spectra and chromatograms.
class SqrtMower
Scales the intensity of peaks to the sqrt.
class StablePairFinder
This class implements a pair finding algorithm for consensus features.
class SteinScottImproveScore
Similarity score based of Stein & Scott.
class StopWatch
StopWatch Class.
class StreamHandler
Provides a central class to register globally used output streams. Currently supported streams are.
class String
A more convenient string class.
class StringListUtils
Utilities operating on lists of Strings.
class StringUtils
class StringView
StringView provides a non-owning view on an existing string.
struct Summary
Summary of fitting results.
class SuperHirnParameters
SuperHirn parameters singleton class containing all static configuration variables.
class SuperHirnUtil
struct SVMData
Data structure used in SVMWrapper.
class SvmTheoreticalSpectrumGenerator
Simulates MS2 spectra with support vector machines.
class SvmTheoreticalSpectrumGeneratorSet
Loads SvmTheoreticalSpectrumGenerator instances for different charges.
class SvmTheoreticalSpectrumGeneratorTrainer
Train SVM models that are used by SvmTheoreticalSpectrumGenerator.
class SVMWrapper
Serves as a wrapper for the libsvm.
class SVOutStream
Stream class for writing to comma/tab/...-separated values files.
class SwathFile
File adapter for Swath files.
class SwathMapMassCorrection
A class containing correction functions for Swath MS maps.
class SwathWindowLoader
Class to read a file describing the Swath Windows.
class SysInfo
Some functions to get system information.
class Tagging
Meta information about tagging of a sample e.g. ICAT labeling.
class TaggingVisualizer
Class that displays all meta information of tagging objects.
class TargetedExperiment
A description of a targeted experiment containing precursor and production ions.
class TargetedSpectraExtractor
This class filters, annotates, picks, and scores spectra (e.g., taken from a DDA experiment) based on a target list.
class TextFile
This class provides some basic file handling methods for text files.
class TheoreticalSpectrumGenerationDialog
Dialog which allows to enter an AA sequence and generates a theoretical spectrum for it.
class TheoreticalSpectrumGenerator
Generates theoretical spectra for peptides with various options.
class TheoreticalSpectrumGeneratorXLMS
Generates theoretical spectra for cross-linked peptides.
class ThresholdMower
ThresholdMower removes all peaks below a threshold.
class TIC
class TICFilter
TICFilter calculates TIC.
class TMTElevenPlexQuantitationMethod
TMT 11plex quantitation to be used with the IsobaricQuantitation.
class TMTSixPlexQuantitationMethod
TMT 6plex quantitation to be used with the IsobaricQuantitation.
class TMTSixteenPlexQuantitationMethod
TMT 16plex quantitation to be used with the IsobaricQuantitation.
class TMTTenPlexQuantitationMethod
TMT 10plex quantitation to be used with the IsobaricQuantitation.
class TOFCalibration
This class implements an external calibration for TOF data using external calibrant spectra.
class ToolDescriptionFile
File adapter for ToolDescriptor files.
class ToolHandler
class ToolsDialog
TOPP tool selection dialog.
class TOPPASBase
Main window of the TOPPAS tool.
class TOPPASEdge
An edge representing a data flow in TOPPAS.
class TOPPASInputFileDialog
Dialog which allows to specify an input file.
class TOPPASInputFileListVertex
A vertex representing an input file list.
class TOPPASInputFilesDialog
Dialog which allows to specify a list of input files.
class TOPPASIOMappingDialog
Dialog which allows to configure the input/output parameter mapping of an edge.
class TOPPASLogWindow
QTextEdit implementation with a "clear" button in the context menu.
class TOPPASMergerVertex
A special vertex that allows to merge several inputs.
class TOPPASOutputFileListVertex
A vertex representing an output file list.
class TOPPASOutputFilesDialog
Dialog which allows to specify the directory for the output files.
class TOPPASResource
Represents a data resource for TOPPAS workflows.
class TOPPASResources
A dictionary mapping string keys to lists of TOPPASResource objects.
class TOPPASScene
A container for all visual items of a TOPPAS workflow.
class TOPPASSplitterVertex
A special vertex that allows to split a list of inputs.
class TOPPASTabBar
Convenience tab bar implementation.
class TOPPASToolConfigDialog
TOPP tool configuration dialog.
class TOPPASToolVertex
A vertex representing a TOPP tool.
class TOPPASTreeView
Tree view implementation for the list of TOPP tools.
class TOPPASVertex
The base class of the different vertex classes.
class TOPPASVertexNameDialog
Dialog which allows to change the name of an input/output vertex.
class TOPPASWidget
Widget visualizing and allowing to edit TOPP pipelines.
class TOPPBase
Base class for TOPP applications.
class TOPPOpenSwathBase
class TOPPViewBase
Main window of TOPPView tool.
class TOPPViewIdentificationViewBehavior
Behavior of TOPPView in identification mode.
class TOPPViewOpenDialog
Dataset opening options for TOPPView.
class TOPPViewSpectraViewBehavior
Behavior of TOPPView in spectra view mode.
class TraceFitter
Abstract fitter for RT profile fitting.
class TraMLFile
File adapter for HUPO PSI TraML files.
class TransformationDescription
Generic description of a coordinate transformation.
class TransformationModel
Base class for transformation models.
class TransformationModelBSpline
B-spline (non-linear) model for transformations.
class TransformationModelInterpolated
Interpolation model for transformations.
class TransformationModelLinear
Linear model for transformations.
class TransformationModelLowess
Lowess (non-linear) model for transformations.
class TransformationXMLFile
Used to load and store TransformationXML files.
class TransitionGroupOpenMS
An implementation of the OpenSWATH Transition Group Access interface using OpenMS.
class TransitionPQPFile
This class supports reading and writing of PQP files.
class TransitionTSVFile
This class supports reading and writing of OpenSWATH transition lists.
class TwoDOptimization
This class provides the two-dimensional optimization of the picked peak parameters.
class UnimodXMLFile
Used to load XML files from unimod.org files.
class UniqueIdGenerator
A generator for unique ids.
class UniqueIdIndexer
A base class for random access containers for classes derived from UniqueIdInterface that adds functionality to convert a unique id into an index into the container.
class UniqueIdInterface
A base class defining a common interface for all classes having a unique id.
class UnnormalizedComparator
Exception thrown if clustering is attempted without a normalized compare functor.
class UpdateCheck
Helper Functions to perform an update query to the OpenMS REST server.
struct ValueTrait
Trait for MatchedIterator to find pairs with a certain distance, which is computed directly on the value_type of the container.
struct VecLowPrecision
class VersionInfo
Version information class.
class WeightWrapper
Encapsulated weight queries to simplify mono vs average weight computation.
class WindowMower
WindowMower augments the highest peaks in a sliding or jumping window.
class XFDRAlgorithm
class XMassFile
File adapter for 'XMass Analysis (fid)' files.
class XMLValidator
Validator for XML files.
class XQuestResultXMLFile
Used to load and store xQuest result files.
class XQuestScores
An implementation of the scores for cross-link identification from the xQuest algorithm (O. Rinner et al., 2008, "Identification of cross-linked peptides from large sequence databases")
class XTandemInfile
XTandem input file.
class XTandemXMLFile
Used to load XTandemXML files.
class ZhangSimilarityScore
Similarity score of Zhang.
class ZlibCompression
Compresses and uncompresses data using zlib.
Typedefs
typedef Map< Internal::ToolDescriptionInternal, Internal::ToolDescriptionInternal > ToolMapping
Updates an INI.
typedef Map< String, Internal::ToolDescription > ToolListType
Handles lists of TOPP and UTILS tools and their categories (for TOPPAS)
typedef DigestionEnzymeProtein Protease
typedef DigestionEnzymeRNA RNase
using RibonucleotideChainEnd = Ribonucleotide
Dummy nucleotide used to represent 5' and 3' chain ends. Usually, just the phosphates.
typedef OPENMS_INT32_TYPE Int32
Signed integer type (32bit)
typedef OPENMS_UINT32_TYPE UInt32
Unsigned integer type (32bit)
typedef OPENMS_INT64_TYPE Int64
Signed integer type (64bit)
typedef OPENMS_UINT64_TYPE UInt64
Unsigned integer type (64bit)
typedef time_t Time
Time type.
typedef unsigned int UInt
Unsigned integer type.
typedef int Int
Signed integer type.
typedef OPENMS_BYTE_TYPE Byte
Byte type.
typedef OPENMS_UINT64_TYPE UID
A unique object ID (as unsigned 64bit type).
typedef size_t Size
Size type e.g. used as variable which can hold result of size()
typedef ptrdiff_t SignedSize
Signed Size type e.g. used as pointer difference.
typedef std::vector< Int > IntList
Vector of signed integers.
typedef std::vector< double > DoubleList
Vector of double precision real types.
typedef std::vector< String > StringList
Vector of String.
typedef boost::shared_ptr< const Eigen::MatrixXd > EigenMatrixXdPtr
typedef boost::shared_ptr< Eigen::MatrixXd > MutableEigenMatrixXdPtr
using IndProtGrp = OpenMS::ProteinIdentification::ProteinGroup
using IndProtGrps = std::vector< IndProtGrp >
typedef std::pair< String, MzTabString > MzTabOptionalColumnEntry
typedef std::vector< MzTabProteinSectionRow > MzTabProteinSectionRows
typedef std::vector< MzTabPeptideSectionRow > MzTabPeptideSectionRows
typedef std::vector< MzTabPSMSectionRow > MzTabPSMSectionRows
typedef std::vector< MzTabSmallMoleculeSectionRow > MzTabSmallMoleculeSectionRows
typedef std::vector< MzTabNucleicAcidSectionRow > MzTabNucleicAcidSectionRows
typedef std::vector< MzTabOligonucleotideSectionRow > MzTabOligonucleotideSectionRows
typedef std::vector< MzTabOSMSectionRow > MzTabOSMSectionRows
typedef Peak2D PeakType
typedef OpenMS::OnDiscMSExperiment OnDiscPeakMap
typedef MSSpectrum PeakSpectrum
Spectrum consisting of raw data points or peaks.
typedef MSExperiment PeakMap
Two-dimensional map of raw data points or peaks.
typedef MSChromatogram Chromatogram
Chromatogram consisting of raw data points or peaks.
typedef boost::shared_ptr< DataProcessing > DataProcessingPtr
typedef boost::shared_ptr< const DataProcessing > ConstDataProcessingPtr
typedef std::multimap< int, MSPeak > elution_peak
typedef std::vector< elution_peak > MZ_series
typedef std::vector< elution_peak >::iterator MZ_series_ITERATOR
typedef std::multimap< int, MSPeak >::iterator SIGNAL_iterator
Enumerations
enum ASCII {
ASCII__BACKSPACE = '\b', ASCII__BELL = '\a', ASCII__CARRIAGE_RETURN = '\r', ASCII__HORIZONTAL_TAB = '\t',
ASCII__NEWLINE = '\n', ASCII__RETURN = ASCII__NEWLINE, ASCII__SPACE = ' ', ASCII__TAB = ASCII__HORIZONTAL_TAB,
ASCII__VERTICAL_TAB = '\v', ASCII__COLON = ':', ASCII__COMMA = ',', ASCII__EXCLAMATION_MARK = '!',
ASCII__POINT = '.', ASCII__QUESTION_MARK = '?', ASCII__SEMICOLON = ';'
}
enum MzTabCellStateType {
MZTAB_CELLSTATE_DEFAULT, MZTAB_CELLSTATE_NULL, MZTAB_CELLSTATE_NAN, MZTAB_CELLSTATE_INF,
SIZE_OF_MZTAB_CELLTYPE
}
Data model of MzTab files.
enum Newline { nl }
custom newline indicator
enum IntensityAveragingMethod : int {
MEDIAN, MEAN, SUM, MIN,
MAX
}
Possible methods for merging peak intensities.
enum IMType { IM_NONE, IM_STACKED, IM_MULTIPLE_SPECTRA }
Functions
std::ostream & operator<< (std::ostream &os, const AccurateMassSearchResult &amsr)
template<>
String ChromatogramExtractor::extract_id_< OpenSwath::LightTargetedExperiment > (OpenSwath::LightTargetedExperiment &transition_exp_used, const String &id, int &prec_charge)
template<>
String ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment > (OpenMS::TargetedExperiment &transition_exp_used, const String &id, int &prec_charge)
std::ostream & operator<< (std::ostream &os, const PSLPFormulation::IndexTriple &triple)
std::ostream & operator<< (std::ostream &os, const AASequence &peptide)
std::istream & operator>> (std::istream &os, const AASequence &peptide)
std::ostream & operator<< (std::ostream &os, const DigestionEnzyme &enzyme)
std::ostream & operator<< (std::ostream &os, const DigestionEnzymeProtein &enzyme)
std::ostream & operator<< (std::ostream &, const Element &)
std::ostream & operator<< (std::ostream &os, const EmpiricalFormula &formula)
std::ostream & operator<< (std::ostream &os, const Residue &residue)
std::ostream & operator<< (std::ostream &os, const Ribonucleotide &ribo)
Stream output operator.
bool compareBinaryTreeNode (const BinaryTreeNode &x, const BinaryTreeNode &y)
returns the value of (x.distance < y.distance) for use with sort
template<UInt N, typename T >
std::size_t hash_value (const DPosition< N, T > &b)
std::ostream & operator<< (std::ostream &os, const Exception::BaseException &e)
Output operator for exceptions.
std::ostream & operator<< (std::ostream &os, LogConfigHandler const &lch)
Overload for the insertion operator (operator<<) to have a formatted output of the LogConfigHandler.
template<typename FloatingPointType >
const PrecisionWrapper< FloatingPointType > precisionWrapper (const FloatingPointType rhs)
Wrapper function that sets the appropriate precision for output temporarily. The original precision is restored afterwards so that no side effects remain. This is a "make"-function that deduces the typename FloatingPointType from its argument and returns a PrecisionWrapper<FloatingPointType>.
template<typename FloatingPointType >
std::ostream & operator<< (std::ostream &os, const PrecisionWrapper< FloatingPointType > &rhs)
Output operator for a PrecisionWrapper. Specializations are defined for float, double, long double.
std::ostream & operator<< (std::ostream &os, StreamHandler const &stream_handler)
Overload for the insertion operator (operator<<) to have a formatted output of the StreamHandler.
template<typename Type >
std::string typeAsString (const Type &=Type())
Returns the Type as as std::string.
std::ostream & operator<< (std::ostream &os, const ChargePair &cons)
Print the contents of a ChargePair to a stream.
template<UInt D>
std::ostream & operator<< (std::ostream &os, const DBoundingBox< D > &bounding_box)
Print the contents to a stream.
template<typename Value >
std::ostream & operator<< (std::ostream &os, const DistanceMatrix< Value > &matrix)
Print the contents to a stream.
template<UInt D, typename TCoordinateType >
DPosition< D, TCoordinateType > operator* (DPosition< D, TCoordinateType > position, typename DPosition< D, TCoordinateType >::CoordinateType scalar)
Scalar multiplication (a bit inefficient)
template<UInt D, typename TCoordinateType >
DPosition< D, TCoordinateType > operator* (typename DPosition< D, TCoordinateType >::CoordinateType scalar, DPosition< D, TCoordinateType > position)
Scalar multiplication (a bit inefficient)
template<UInt D, typename TCoordinateType >
DPosition< D, TCoordinateType > operator/ (DPosition< D, TCoordinateType > position, typename DPosition< D, TCoordinateType >::CoordinateType scalar)
Scalar multiplication (a bit inefficient)
template<UInt D, typename TCoordinateType >
std::ostream & operator<< (std::ostream &os, const DPosition< D, TCoordinateType > &pos)
Print the contents to a stream.
template<UInt D>
std::ostream & operator<< (std::ostream &os, const DRange< D > &area)
Print the contents to a stream.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &v)
Output stream operator for std::vectors.
template<typename T >
std::ostream & operator<< (std::ostream &os, const VecLowPrecision< T > &val)
template<typename TString >
std::vector< String > & operator<< (std::vector< String > &sl, const TString &string)
Operator for appending entries with less code.
template<typename Value >
std::ostream & operator<< (std::ostream &os, const Matrix< Value > &matrix)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const Param &param)
Output of Param to a stream.
::size_t hash_value (OpenMS::String const &s)
static EigenMatrixXdPtr convertOpenMSMatrix2EigenMatrixXd (const Matrix< double > &m)
static bool matrixIsIdentityMatrix (const Matrix< double > &channel_frequency)
UInt32 endianize32 (const UInt32 &n)
Endianizes a 32 bit type from big endian to little endian and vice versa.
UInt64 endianize64 (const UInt64 &n)
Endianizes a 64 bit type from big endian to little endian and vice versa.
std::ostream & operator<< (std::ostream &os, const ControlledVocabulary &cv)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const ChromatogramPeak &point)
Print the contents to a stream.
template<class Cmp >
PointerComparator< Cmp > pointerComparator (Cmp const &cmp)
Make-function to create a PointerComparator from another comparator without the need to specify the template arguments.
template<class Cmp >
ReverseComparator< Cmp > reverseComparator (Cmp const &cmp)
Make-function to create a ReverseComparator from another comparator without the need to specify the template arguments.
template<typename Cmp1 , typename Cmp2 >
LexicographicComparator< Cmp1, Cmp2 > lexicographicComparator (Cmp1 const &cmp1, Cmp2 const &cmp2)
Make-function to create a LexicographicComparator from two other comparators without the need to specify the template arguments.
std::ostream & operator<< (std::ostream &os, const ConsensusFeature &cons)
Print the contents of a ConsensusFeature to a stream.
std::ostream & operator<< (std::ostream &os, const ConsensusMap &cons_map)
Print the contents of a ConsensusMap to a stream.
std::ostream & operator<< (std::ostream &os, const FeatureHandle &cons)
Print the contents of a FeatureHandle to a stream.
std::ostream & operator<< (std::ostream &os, const AnnotationStatistics &ann)
Print content of an AnnotationStatistics object to a stream.
std::ostream & operator<< (std::ostream &os, const FeatureMap &map)
std::ostream & operator<< (std::ostream &os, const MSChromatogram &chrom)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const MSExperiment &exp)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const MSSpectrum &spec)
std::ostream & operator<< (std::ostream &os, const Peak1D &point)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const Peak2D &point)
Print the contents to a stream.
template<class DataArrayT >
DataArrayT::iterator getDataArrayByName (DataArrayT &a, const String &name)
Helper functions for MSSpectrum and MSChromatogram.
template<class DataArrayT >
DataArrayT::const_iterator getDataArrayByName (const DataArrayT &a, const String &name)
template<typename PeakContainerT >
void removePeaks (PeakContainerT &p, const double pos_start, const double pos_end, const bool ignore_data_arrays=false)
remove all peaks EXCEPT in the given range
template<typename PeakContainerT >
void subtractMinimumIntensity (PeakContainerT &p)
template<typename PeakContainerT >
void makePeakPositionUnique (PeakContainerT &p, const IntensityAveragingMethod m=IntensityAveragingMethod::MEDIAN)
Make peak positions unique.
std::ostream & operator<< (std::ostream &os, const ChromatogramSettings &spec)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const ExperimentalSettings &exp)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const SpectrumSettings &spec)
Print the contents to a stream.
std::ostream & operator<< (std::ostream &os, const QCBase::Status &stat)
template<typename PeakType >
bool intensityComparator (const PeakType &a, const PeakType &b)
template<typename PeakType >
bool intensityAscendingComparator (const PeakType &a, const PeakType &b)
template<typename PeakType >
bool intensityPointerComparator (PeakType *a, PeakType *b)
template<typename PeakType >
bool positionComparator (const PeakType &a, const PeakType &b)
bool operator< (const MultiplexDeltaMasses &dm1, const MultiplexDeltaMasses &dm2)
bool sort_peaks_by_intensity (const PeakCandidate &a, const PeakCandidate &b)
std::ostream & operator<< (std::ostream &, CentroidData &)
std::ostream & operator<< (std::ostream &, CentroidPeak &)
std::ostream & operator<< (std::ostream &, DeconvPeak &)
SUPERHIRN_DLLAPI std::ostream & operator<< (std::ostream &, Deisotoper &)
std::ostream & operator<< (std::ostream &out, RawData &data)
std::ostream & operator<< (std::ostream &os, const LayerData &rhs)
Print the contents to a stream.
IMType determineIMType (const MSExperiment &exp)
void processDriftTimeStack (const std::vector< MSSpectrum > &stack, std::vector< MSSpectrum > &result)
Process a stack of drift time spectra.
void expandIMSpectrum (const MSSpectrum &tmps, std::vector< MSSpectrum > &result)
Expands a single MSSpectrum (single frame) into individual ion mobility spectrum.
void collapseIMSpectrum (const MSExperiment &exp, std::vector< MSSpectrum > &result)
Collapses multiple IM spectra from the same frame into a single MSSpectrum.
Numbers of digits used for writing floating point numbers (a.k.a. precision).
These functions are provided to unify the handling of this issue throughout OpenMS. (So please don't use ad-hoc numbers ;-))
If you want to avoid side effects you can use precisionWrapper() to write a floating point number with appropriate precision; in this case the original state of the stream is automatically restored afterwards. See precisionWrapper() for details.
In practice, the number of decimal digits that the type can represent without loss of precision are 6 digits for single precision and 15 digits for double precision. We have and , so rounding will remove the remaining difference.
Example:
#define NUMBER 12345.67890123456789012345678901
std::cout << NUMBER << '\n'; // default precision, writes: 12345.7
double d = NUMBER;
std::cout.precision(writtenDigits<double>(0.0)); // explicit template instantiation
std::cout << writtenDigits<double>(0.0) << ": " << d << '\n'; // writes: 15: 12345.6789012346
float r = NUMBER;
std::cout.precision(writtenDigits(r)); // type deduced from argument
std::cout << writtenDigits(r) << ": " << r << '\n'; // writes: 6: 12345.7
long double l = NUMBER;
std::cout.precision(writtenDigits(1L)); // argument is not used, but L suffix indicates a long double
std::cout << writtenDigits(1L) << ": " << l << '\n'; // writes: 18: 12345.6789012345671
double x = 88.99;
std::cout.precision(15);
std::cout << "15: " << x << '\n'; // writes: 15: 88.99
std::cout.precision(16);
std::cout << "16: " << x << '\n'; // writes: 16: 88.98999999999999
template<typename FloatingPointType >
constexpr Int writtenDigits (const FloatingPointType &=FloatingPointType())
Number of digits commonly used for writing a floating point type (a.k.a. precision). Specializations are defined for float, double, long double.
template<>
constexpr Int writtenDigits< float > (const float &)
Number of digits commonly used for writing a float (a.k.a. precision).
template<>
constexpr Int writtenDigits< double > (const double &)
Number of digits commonly used for writing a double (a.k.a. precision).
template<>
constexpr Int writtenDigits< int > (const int &)
We do not want to bother people who unintentionally provide an int argument to this.
template<>
constexpr Int writtenDigits< unsigned int > (const unsigned int &)
We do not want to bother people who unintentionally provide an unsigned int argument to this.
template<>
constexpr Int writtenDigits< long int > (const long int &)
We do not want to bother people who unintentionally provide a long int argument to this.
template<>
constexpr Int writtenDigits< unsigned long int > (const unsigned long int &)
We do not want to bother people who unintentionally provide an unsigned long int argument to this.
template<>
constexpr Int writtenDigits< DataValue > (const DataValue &)
DataValue will be printed like double.
template<>
constexpr Int writtenDigits< long double > (const long double &)
Number of digits commonly used for writing a long double (a.k.a. precision). ...
Variables
struct OpenMS::PrecursorMassComparator PrecursorMZLess
struct OpenMS::SpectralMatchScoreComparator SpectralMatchScoreGreater
Logger::LogStream OpenMS_Log_fatal
Global static instance of a LogStream to capture messages classified as fatal errors. By default it is bound to cerr.
Logger::LogStream OpenMS_Log_error
Global static instance of a LogStream to capture messages classified as errors. By default it is bound to cerr.
Logger::LogStream OpenMS_Log_warn
Global static instance of a LogStream to capture messages classified as warnings. By default it is bound to cout.
Logger::LogStream OpenMS_Log_info
Global static instance of a LogStream to capture messages classified as information. By default it is bound to cout.
Logger::LogStream OpenMS_Log_debug
Global static instance of a LogStream to capture messages classified as debug output. By default it is not bound to any output stream. TOPP(AS)Base will connect cout, iff 0 < debug-level.
StreamHandler STREAM_HANDLER
Global StreamHandler instance.
const double BinaryDataEncoder_default_numpressErrorTolerance = .0001
Detailed Description
Main OpenMS namespace.
Total Ion Count (TIC) as a QC metric.
In this namespace all the main OpenMS classes are located.
Simple class to calculate the TIC of an MSExperiment. Allows for multiple usage, because each calculated TIC is stored internally. Those results can then be returned using getResults().
Class Documentation
OpenMS::ChromExtractParams
struct OpenMS::ChromExtractParams
ChromatogramExtractor parameters.
A small helper struct to pass the parameters for the chromatogram extraction through to the actual algorithm.
Class Members
double extra_rt_extract Whether to extract some extra in the retention time (can be useful if one wants to look at the chromatogram outside the window)
String extraction_function The extraction function in mass space.
double im_extraction_window Extraction window in ion mobility.
double min_upper_edge_dist Whether to not extract anything closer than this (in Da) from the upper edge.
double mz_extraction_window Extraction window in Da or ppm (e.g. 50ppm means extraction +/- 25ppm)
bool ppm Whether the extraction window is given in ppm or Da.
double rt_extraction_window The retention time extraction window.
OpenMS::DPeak
struct OpenMS::DPeak
template<UInt dimensions>
struct OpenMS::DPeak< dimensions >
Metafunction to choose among Peak1D respectively Peak2D through a template argument.
The result is accessible via typedef Type:
DPeak<1>::Type is Peak1D
DPeak<2>::Type is Peak2D
Example:
template class BaseModel<UInt D>
{
    // BaseModel<D>::PeakType is either Peak1D or Peak2D, depending on D
    typedef typename DPeak<D>::Type PeakType;
};
OpenMS::FASTAContainer
class OpenMS::FASTAContainer
template<typename TBackend>
class OpenMS::FASTAContainer< TBackend >
template parameter for vector-based FASTA access
This class allows for a chunk-wise single linear read over a (large) FASTA file, with spurious (since potentially slow) access to earlier entries which are currently not in the active chunk.
Internally uses FASTAFile class to read single sequences.
FASTAContainer supports two template specializations FASTAContainer<TFI_File> and FASTAContainer<TFI_Vector>.
FASTAContainer<TFI_File> will make FASTA entries available chunk-wise from start to end by loading it from a FASTA file. This avoids having to load the full file into memory. While loading, the container will memorize the file offsets of each entry, allowing to read an arbitrary i'th entry again from disk. If possible, only entries from the currently cached chunk should be queried, otherwise access will be slow.
FASTAContainer<TFI_Vector> simply takes an existing vector of FASTAEntries and provides the same interface (with a potentially huge speed benefit over FASTAContainer<TFI_File> since it does not need disk access, but at the cost of memory).
If an algorithm searches through a FASTA file linearly, you can use FASTAContainer<TFI_File> to pre-load a small chunk and start working, while loading the next chunk in a background thread and swap it in when the active chunk was processed.
OpenMS::FeatureFinderAlgorithmPickedHelperStructs
struct OpenMS::FeatureFinderAlgorithmPickedHelperStructs
Wrapper struct for all the classes needed by the FeatureFinderAlgorithmPicked and the associated classes.
See also
FeatureFinderAlgorithmPicked
TraceFitter
OpenMS::MS1Signal
struct OpenMS::MS1Signal
Class Members
int charge
double intensity
double mass
int scan
double TR
OpenMS::MzTabAssayMetaData
struct OpenMS::MzTabAssayMetaData
Class Members
vector< int > ms_run_ref
map< Size, MzTabModificationMetaData > quantification_mod
MzTabParameter quantification_reagent
MzTabString sample_ref
OpenMS::MzTabContactMetaData
struct OpenMS::MzTabContactMetaData
Class Members
MzTabString affiliation
MzTabString email
MzTabString name
OpenMS::MzTabCVMetaData
struct OpenMS::MzTabCVMetaData
Class Members
MzTabString full_name
MzTabString label
MzTabString url
MzTabString version
OpenMS::MzTabInstrumentMetaData
struct OpenMS::MzTabInstrumentMetaData
Class Members
map< Size, MzTabParameter > analyzer
MzTabParameter detector
MzTabParameter name
MzTabParameter source
OpenMS::MzTabModificationMetaData
struct OpenMS::MzTabModificationMetaData
Class Members
MzTabParameter modification
MzTabString position
MzTabString site
OpenMS::MzTabMSRunMetaData
struct OpenMS::MzTabMSRunMetaData
Class Members
MzTabParameter format
MzTabParameterList fragmentation_method
MzTabParameter id_format
MzTabString location
OpenMS::MzTabNucleicAcidSectionRow
struct OpenMS::MzTabNucleicAcidSectionRow
NUC - Nucleic acid section (table-based)
Class Members
MzTabString accession The nucleic acids accession.
MzTabStringList ambiguity_members Alternative nucleic acid identifications.
map< Size, MzTabDouble > best_search_engine_score Best search engine(s) score(s) (over all MS runs)
MzTabDouble coverage (0-1) Fraction of nucleic acid sequence identified.
MzTabString database Name of the sequence database.
MzTabString database_version Version of the sequence database.
MzTabString description Human readable description (i.e. the name)
MzTabStringList go_terms List of GO terms for the nucleic acid.
MzTabModificationList modifications Modifications identified in the nucleic acid.
map< Size, MzTabInteger > num_oligos_distinct_ms_run
map< Size, MzTabInteger > num_oligos_unique_ms_run
map< Size, MzTabInteger > num_osms_ms_run
vector< MzTabOptionalColumnEntry > opt_ Optional Columns must start with opt_
MzTabInteger reliability
MzTabParameterList search_engine Search engine(s) that identified the nucleic acid.
map< Size, map< Size, MzTabDouble > > search_engine_score_ms_run
MzTabString species Human readable name of the species.
MzTabInteger taxid NEWT taxonomy for the species.
MzTabString uri Location of the nucleic acids source entry.
OpenMS::MzTabOligonucleotideSectionRow
struct OpenMS::MzTabOligonucleotideSectionRow
OLI - Oligonucleotide section (table-based)
Class Members
MzTabString accession The nucleic acids accession.
map< Size, MzTabDouble > best_search_engine_score Search engine(s) score(s) for the match.
MzTabString end
MzTabModificationList modifications Modifications identified in the oligonucleotide.
vector< MzTabOptionalColumnEntry > opt_ Optional columns must start with opt_.
MzTabString post
MzTabString pre
MzTabInteger reliability (1-3) 0=null Identification reliability for the match.
MzTabDoubleList retention_time Time points in seconds. Semantics may vary.
MzTabDoubleList retention_time_window
MzTabParameterList search_engine Search engine(s) that identified the match.
map< Size, map< Size, MzTabDouble > > search_engine_score_ms_run Search engine(s) score(s) per individual MS run.
MzTabString sequence The oligonucleotides sequence.
MzTabString start
MzTabBoolean unique 0=false, 1=true, null else: Oligonucleotide maps uniquely to the nucleic acid sequence.
MzTabString uri Location of the oligonucleotide's source entry.
OpenMS::MzTabOSMSectionRow
struct OpenMS::MzTabOSMSectionRow
OSM - OSM (oligonucleotide-spectrum match) section (table-based)
Class Members
MzTabDouble calc_mass_to_charge The theoretical m/z ratio of the oligonucleotide.
MzTabInteger charge The charge of the experimental precursor ion.
MzTabDouble exp_mass_to_charge The m/z ratio of the experimental precursor ion.
MzTabModificationList modifications Modifications identified in the oligonucleotide.
vector< MzTabOptionalColumnEntry > opt_ Optional columns must start with opt_.
MzTabInteger reliability (1-3) 0=null Identification reliability for the match.
MzTabDoubleList retention_time Time points in seconds. Semantics may vary.
MzTabParameterList search_engine Search engine(s) that identified the match.
map< Size, MzTabDouble > search_engine_score Search engine(s) score(s) for the match.
MzTabString sequence The oligonucleotides sequence.
MzTabSpectraRef spectra_ref Reference to the spectrum underlying the match.
MzTabString uri Location of the OSMs source entry.
OpenMS::MzTabPeptideSectionRow
struct OpenMS::MzTabPeptideSectionRow
PEP - Peptide section (Table based)
Class Members
MzTabString accession The proteins accession.
map< Size, MzTabDouble > best_search_engine_score Search engine(s) score(s) for the peptide.
MzTabInteger charge Precursor ions charge.
MzTabString database Name of the sequence database.
MzTabString database_version Version (and optionally # of entries).
MzTabDouble mass_to_charge Precursor ions m/z.
MzTabModificationList modifications Modifications identified in the peptide.
vector< MzTabOptionalColumnEntry > opt_ Optional columns must start with opt_.
map< Size, MzTabDouble > peptide_abundance_assay
map< Size, MzTabDouble > peptide_abundance_std_error_study_variable
map< Size, MzTabDouble > peptide_abundance_stdev_study_variable
map< Size, MzTabDouble > peptide_abundance_study_variable
MzTabInteger reliability (1-3) 0=null Identification reliability for the peptide.
MzTabDoubleList retention_time Time points in seconds. Semantics may vary.
MzTabDoubleList retention_time_window
MzTabParameterList search_engine Search engine(s) that identified the peptide.
map< Size, map< Size, MzTabDouble > > search_engine_score_ms_run
MzTabString sequence The peptides sequence.
MzTabSpectraRef spectra_ref Spectra identifying the peptide.
MzTabBoolean unique 0=false, 1=true, null else: Peptide is unique for the protein.
MzTabString uri Location of the PSMs source entry.
OpenMS::MzTabPSMSectionRow
struct OpenMS::MzTabPSMSectionRow
PSM - PSM section (Table based)
Class Members
MzTabString accession The proteins accession.
MzTabDouble calc_mass_to_charge
MzTabInteger charge The charge of the experimental precursor ion.
MzTabString database Name of the sequence database.
MzTabString database_version Version (and optionally # of entries).
MzTabString end
MzTabDouble exp_mass_to_charge The m/z ratio of the experimental precursor ion.
MzTabModificationList modifications Modifications identified in the peptide.
vector< MzTabOptionalColumnEntry > opt_ Optional columns must start with opt_.
MzTabString post
MzTabString pre
MzTabInteger PSM_ID
MzTabInteger reliability (1-3) 0=null Identification reliability for the peptide.
MzTabDoubleList retention_time Time points in seconds. Semantics may vary.
MzTabParameterList search_engine Search engine(s) that identified the peptide.
map< Size, MzTabDouble > search_engine_score Search engine(s) score(s) for the peptide.
MzTabString sequence The peptides sequence.
MzTabSpectraRef spectra_ref Spectra identifying the peptide.
MzTabString start
MzTabBoolean unique 0=false, 1=true, null else: Peptide is unique for the protein.
MzTabString uri Location of the PSMs source entry.
OpenMS::MzTabSampleMetaData
struct OpenMS::MzTabSampleMetaData
Class Members
map< Size, MzTabParameter > cell_type
map< Size, MzTabParameter > custom
MzTabString description
map< Size, MzTabParameter > disease
map< Size, MzTabParameter > species
map< Size, MzTabParameter > tissue
OpenMS::MzTabSmallMoleculeSectionRow
struct OpenMS::MzTabSmallMoleculeSectionRow
SML Small molecule section (table based)
Class Members
map< Size, MzTabDouble > best_search_engine_score Search engine(s) identifications score(s).
MzTabDouble calc_mass_to_charge Precursor ions m/z.
MzTabInteger charge Precursor ions charge.
MzTabString chemical_formula Chemical formula of the identified compound.
MzTabString database Name of the used database.
MzTabString database_version String Version of the database (and optionally # of compounds).
MzTabString description Human readable description (i.e. the name)
MzTabDouble exp_mass_to_charge Precursor ions m/z.
MzTabStringList identifier The small molecules identifier.
MzTabString inchi_key InChi Key of the identified compound.
MzTabString modifications Modifications identified on the small molecule.
vector< MzTabOptionalColumnEntry > opt_ Optional columns must start with opt_.
MzTabInteger reliability (1-3) The identification reliability.
MzTabDoubleList retention_time Time points in seconds. Semantics may vary.
MzTabParameterList search_engine Search engine(s) identifying the small molecule.
map< Size, map< Size, MzTabDouble > > search_engine_score_ms_run
map< Size, MzTabDouble > smallmolecule_abundance_assay
map< Size, MzTabDouble > smallmolecule_abundance_std_error_study_variable
map< Size, MzTabDouble > smallmolecule_abundance_stdev_study_variable
map< Size, MzTabDouble > smallmolecule_abundance_study_variable
MzTabString smiles Molecular structure in SMILES format.
MzTabString species Human readable name of the species.
MzTabSpectraRef spectra_ref Spectra identifying the small molecule.
MzTabInteger taxid NEWT taxonomy for the species.
MzTabString uri The source entrys location.
OpenMS::MzTabSoftwareMetaData
struct OpenMS::MzTabSoftwareMetaData
Class Members
map< Size, MzTabString > setting
MzTabParameter software
OpenMS::MzTabStudyVariableMetaData
struct OpenMS::MzTabStudyVariableMetaData
Class Members
vector< int > assay_refs
MzTabString description
vector< int > sample_refs
OpenMS::OpenSwath_Scores_Usage
struct OpenMS::OpenSwath_Scores_Usage
A structure to store which scores should be used by the OpenSWATH Algorithm.
This can be used to turn on/off individual scores.
Class Members
bool use_coelution_score_
bool use_dia_scores_
bool use_elution_model_score_
bool use_im_scores
bool use_intensity_score_
bool use_library_score_
bool use_mi_score_
bool use_ms1_correlation
bool use_ms1_fullscan
bool use_ms1_mi
bool use_nr_peaks_score_
bool use_rt_score_
bool use_shape_score_
bool use_sn_score_
bool use_sonar_scores
bool use_total_mi_score_
bool use_total_xic_score_
bool use_uis_scores
OpenMS::PeakCandidate
struct OpenMS::PeakCandidate
A small structure to hold peak candidates.
Class Members
int index
double integrated_intensity
double leftWidth
float mz
double peak_apex_intensity
double rightWidth
OpenMS::ProbablePhosphoSites
struct OpenMS::ProbablePhosphoSites
Class Members
Size AScore
Size first
Size peak_depth filtering level that gave rise to maximum discriminatory score
Size second
Size seq_1 index of best permutation with site in phosphorylated state
Size seq_2 index of permutation with site in unphosphorylated state
OpenMS::RNPxlModificationMassesResult
struct OpenMS::RNPxlModificationMassesResult
Class Members
map< String, set< String > > mod_combinations empirical formula -> nucleotide formula(s) (formulas if modifications lead to ambiguities)
map< String, double > mod_masses empirical formula -> mass
Typedef Documentation
ConstDataProcessingPtr
typedef boost::shared_ptr<const DataProcessing> ConstDataProcessingPtr
DataProcessingPtr
typedef boost::shared_ptr<DataProcessing> DataProcessingPtr
EigenMatrixXdPtr
typedef boost::shared_ptr< const Eigen::MatrixXd > EigenMatrixXdPtr
Matrix utility functions.
elution_peak
typedef std::multimap<int, MSPeak> elution_peak
IndProtGrp
using IndProtGrp = OpenMS::ProteinIdentification::ProteinGroup
IndProtGrps
using IndProtGrps = std::vector<IndProtGrp>
MutableEigenMatrixXdPtr
typedef boost::shared_ptr< Eigen::MatrixXd > MutableEigenMatrixXdPtr
MZ_series
typedef std::vector<elution_peak> MZ_series
MZ_series_ITERATOR
typedef std::vector<elution_peak>::iterator MZ_series_ITERATOR
MzTabNucleicAcidSectionRows
typedef std::vector<MzTabNucleicAcidSectionRow> MzTabNucleicAcidSectionRows
MzTabOligonucleotideSectionRows
typedef std::vector<MzTabOligonucleotideSectionRow> MzTabOligonucleotideSectionRows
MzTabOptionalColumnEntry
typedef std::pair<String, MzTabString> MzTabOptionalColumnEntry
MzTabOSMSectionRows
typedef std::vector<MzTabOSMSectionRow> MzTabOSMSectionRows
MzTabPeptideSectionRows
typedef std::vector<MzTabPeptideSectionRow> MzTabPeptideSectionRows
MzTabProteinSectionRows
typedef std::vector<MzTabProteinSectionRow> MzTabProteinSectionRows
MzTabPSMSectionRows
typedef std::vector<MzTabPSMSectionRow> MzTabPSMSectionRows
MzTabSmallMoleculeSectionRows
typedef std::vector<MzTabSmallMoleculeSectionRow> MzTabSmallMoleculeSectionRows
OnDiscPeakMap
typedef OpenMS::OnDiscMSExperiment OnDiscPeakMap
PeakType
typedef Peak2D PeakType
Protease
typedef DigestionEnzymeProtein Protease
RibonucleotideChainEnd
using RibonucleotideChainEnd = Ribonucleotide
Dummy nucleotide used to represent 5' and 3' chain ends. Usually, just the phosphates.
RNase
typedef DigestionEnzymeRNA RNase
SIGNAL_iterator
typedef std::multimap<int, MSPeak>::iterator SIGNAL_iterator
ToolListType
typedef Map<String, Internal::ToolDescription> ToolListType
Handles lists of TOPP and UTILS tools and their categories (for TOPPAS)
Path's were *.ttd files are searched for:
Default: The OpenMS share directory ([OpenMS]/share/TOOLS/EXTERNAL) OS specific directories
[OpenMS]/share/TOOLS/EXTERNAL/LINUX (for Mac and Linux)
[OpenMS]/share/TOOLS/EXTERNAL/WINDOWS (for Windows) Environment: OPENMS_TTD_PATH (use only one path here!) map each TOPP/UTIL to its ToolDescription
ToolMapping
typedef Map<Internal::ToolDescriptionInternal, Internal::ToolDescriptionInternal> ToolMapping
Updates an INI.
map each old TOPP/UTIL to its new Name
Enumeration Type Documentation
ASCII
enum ASCII
Enumerator
ASCII__BACKSPACE
ASCII__BELL
ASCII__CARRIAGE_RETURN
ASCII__HORIZONTAL_TAB
ASCII__NEWLINE
ASCII__RETURN
ASCII__SPACE
ASCII__TAB
ASCII__VERTICAL_TAB
ASCII__COLON
ASCII__COMMA
ASCII__EXCLAMATION_MARK
ASCII__POINT
ASCII__QUESTION_MARK
ASCII__SEMICOLON
IMType
enum IMType
Enumerator
IM_NONE
no ion mobility
IM_STACKED
ion mobility frame is stacked in a single spectrum
IM_MULTIPLE_SPECTRA
ion mobility is recorded as multiple spectra per frame
IntensityAveragingMethod
enum IntensityAveragingMethod : int strong
Possible methods for merging peak intensities.
See also
makePeakPositionUnique()
Enumerator
MEDIAN
MEAN
SUM
MIN
MAX
Newline
enum Newline
custom newline indicator
Enumerator
nl
Function Documentation
ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment >()
String OpenMS::ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment > (OpenMS::TargetedExperiment & transition_exp_used, const String & id, int & prec_charge) inline
References OpenMS::Constants::c, PeptideCompound::getChargeState(), TargetedExperiment::getCompoundByRef(), TargetedExperiment::getPeptideByRef(), PeptideCompound::hasCharge(), TargetedExperiment::hasCompound(), TargetedExperiment::hasPeptide(), and Peptide::sequence.
ChromatogramExtractor::extract_id_< OpenSwath::LightTargetedExperiment >()
String OpenMS::ChromatogramExtractor::extract_id_< OpenSwath::LightTargetedExperiment > (OpenSwath::LightTargetedExperiment & transition_exp_used, const String & id, int & prec_charge) inline
References LightCompound::charge, LightCompound::compound_name, LightTargetedExperiment::getCompoundByRef(), and LightCompound::sequence.
collapseIMSpectrum()
void OpenMS::collapseIMSpectrum (const MSExperiment & exp, std::vector< MSSpectrum > & result)
Collapses multiple IM spectra from the same frame into a single MSSpectrum.
Parameters
exp The input experiment with multiple spectra per frame
result The output spectra collapsed to a single spectrum per frame
Note
: this requires that all spectra from the same frame have the same RT ("scan start time")
References MSExperiment::empty(), OpenMS::Constants::k, processDriftTimeStack(), and MSExperiment::size().
compareBinaryTreeNode()
bool OpenMS::compareBinaryTreeNode (const BinaryTreeNode & x, const BinaryTreeNode & y)
returns the value of (x.distance < y.distance) for use with sort
convertOpenMSMatrix2EigenMatrixXd()
static EigenMatrixXdPtr OpenMS::convertOpenMSMatrix2EigenMatrixXd (const Matrix< double > & m) static
References Matrix< Value >::cols(), and Matrix< Value >::rows().
determineIMType()
IMType OpenMS::determineIMType (const MSExperiment & exp)
References MSExperiment::empty(), IM_MULTIPLE_SPECTRA, IM_NONE, IM_STACKED, OpenMS::Constants::k, and MSExperiment::size().
endianize32()
UInt32 OpenMS::endianize32 (const UInt32 & n) inline
Endianizes a 32 bit type from big endian to little endian and vice versa.
Referenced by Base64::decodeCompressed_(), Base64::decodeIntegersCompressed_(), Base64::encode(), and Base64::encodeIntegers().
endianize64()
UInt64 OpenMS::endianize64 (const UInt64 & n) inline
Endianizes a 64 bit type from big endian to little endian and vice versa.
Referenced by Base64::decodeCompressed_(), Base64::decodeIntegersCompressed_(), Base64::encode(), and Base64::encodeIntegers().
expandIMSpectrum()
void OpenMS::expandIMSpectrum (const MSSpectrum & tmps, std::vector< MSSpectrum > & result)
Expands a single MSSpectrum (single frame) into individual ion mobility spectrum.
Parameters
tmps The input spectrum (a single spectrum per frame)
result The output spectra with multiple spectra per frame
References MSSpectrum::clear(), MSSpectrum::getFloatDataArrays(), MSSpectrum::getName(), OpenMS::Constants::k, MSSpectrum::setDriftTime(), MSSpectrum::setDriftTimeUnit(), MSSpectrum::setFloatDataArrays(), and MSSpectrum::setName().
getDataArrayByName()
DataArrayT::const_iterator OpenMS::getDataArrayByName (const DataArrayT & a, const String & name)
hash_value() [1/2]
std::size_t OpenMS::hash_value (const DPosition< N, T > & b)
Hash value for OpenMS::DPosition.
References DPosition< D, TCoordinateType >::begin(), and DPosition< D, TCoordinateType >::end().
hash_value() [2/2]
::size_t OpenMS::hash_value (OpenMS::String const & s)
intensityAscendingComparator()
bool OpenMS::intensityAscendingComparator (const PeakType & a, const PeakType & b)
References Peak2D::getIntensity().
intensityComparator()
bool OpenMS::intensityComparator (const PeakType & a, const PeakType & b)
References Peak2D::getIntensity().
intensityPointerComparator()
bool OpenMS::intensityPointerComparator (PeakType * a, PeakType * b)
References Peak2D::getIntensity().
lexicographicComparator()
LexicographicComparator< Cmp1, Cmp2 > lexicographicComparator (Cmp1 const & cmp1, Cmp2 const & cmp2)
Make-function to create a LexicographicComparator from two other comparators without the need to specify the template arguments.
The usage is similar to pointerComparator() or reverseComparator(), which see.
makePeakPositionUnique()
void OpenMS::makePeakPositionUnique (PeakContainerT & p, const IntensityAveragingMethod m = IntensityAveragingMethod::MEDIAN)
Make peak positions unique.
A peak container may contain multiple peaks with the same position, i.e. either an MSSpectrum containing peaks with the same m/z position, or an MSChromatogram containing peaks with identical RT position. One scenario where this might happen is when multiple spectra are merged to a single one.
The method combines peaks with the same position to a single one with the intensity determined by method m.
Parameters
[in] p The peak container to be manipulated.
[in] m The method for determining peak intensity from peaks with same position (median, mean, sum, min, max).
References MAX, OpenMS::Math::mean(), MEAN, OpenMS::Math::median(), MEDIAN, MIN, OPENMS_LOG_WARN, OpenMS::Math::sum(), and SUM.
matrixIsIdentityMatrix()
static bool OpenMS::matrixIsIdentityMatrix (const Matrix< double > & channel_frequency) static
References Matrix< Value >::rows().
operator*() [1/2]
DPosition<D, TCoordinateType> OpenMS::operator* (DPosition< D, TCoordinateType > position, typename DPosition< D, TCoordinateType >::CoordinateType scalar)
Scalar multiplication (a bit inefficient)
References seqan::position().
operator*() [2/2]
DPosition<D, TCoordinateType> OpenMS::operator* (typename DPosition< D, TCoordinateType >::CoordinateType scalar, DPosition< D, TCoordinateType > position)
Scalar multiplication (a bit inefficient)
References seqan::position().
operator/()
DPosition<D, TCoordinateType> OpenMS::operator/ (DPosition< D, TCoordinateType > position, typename DPosition< D, TCoordinateType >::CoordinateType scalar)
Scalar multiplication (a bit inefficient)
References seqan::position().
operator<()
bool OpenMS::operator< (const MultiplexDeltaMasses & dm1, const MultiplexDeltaMasses & dm2)
operator<<() [1/44]
std::ostream& OpenMS::operator<< (std::ostream & , CentroidData &)
operator<<() [2/44]
std::ostream& OpenMS::operator<< (std::ostream & , CentroidPeak &)
operator<<() [3/44]
std::ostream& OpenMS::operator<< (std::ostream & , const Element &)
operator<<() [4/44]
std::ostream& OpenMS::operator<< (std::ostream & , DeconvPeak &)
operator<<() [5/44]
SUPERHIRN_DLLAPI std::ostream& OpenMS::operator<< (std::ostream & , Deisotoper &)
operator<<() [6/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const AASequence & peptide)
operator<<() [7/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const AccurateMassSearchResult & amsr)
Referenced by SVOutStream::writeValueOrNan().
operator<<() [8/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const AnnotationStatistics & ann)
Print content of an AnnotationStatistics object to a stream.
operator<<() [9/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ChargePair & cons)
Print the contents of a ChargePair to a stream.
operator<<() [10/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ChromatogramPeak & point)
Print the contents to a stream.
operator<<() [11/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ChromatogramSettings & spec)
Print the contents to a stream.
operator<<() [12/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ConsensusFeature & cons)
Print the contents of a ConsensusFeature to a stream.
operator<<() [13/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ConsensusMap & cons_map)
Print the contents of a ConsensusMap to a stream.
operator<<() [14/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ControlledVocabulary & cv)
Print the contents to a stream.
operator<<() [15/44]
std::ostream & operator<< (std::ostream & os, const DBoundingBox< D > & bounding_box)
Print the contents to a stream.
References DIntervalBase< D >::maxPosition(), and DIntervalBase< D >::minPosition().
operator<<() [16/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const DigestionEnzyme & enzyme)
operator<<() [17/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const DigestionEnzymeProtein & enzyme)
operator<<() [18/44]
std::ostream & operator<< (std::ostream & os, const DistanceMatrix< Value > & matrix)
Print the contents to a stream.
References DistanceMatrix< Value >::dimensionsize(), and writtenDigits< double >().
operator<<() [19/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const DPosition< D, TCoordinateType > & pos)
Print the contents to a stream.
References precisionWrapper().
operator<<() [20/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const DRange< D > & area)
Print the contents to a stream.
References DRange< D >::max_, and DRange< D >::min_.
operator<<() [21/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const EmpiricalFormula & formula)
operator<<() [22/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const ExperimentalSettings & exp)
Print the contents to a stream.
operator<<() [23/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const FeatureHandle & cons)
Print the contents of a FeatureHandle to a stream.
operator<<() [24/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const FeatureMap & map)
operator<<() [25/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const LayerData & rhs)
Print the contents to a stream.
operator<<() [26/44]
std::ostream & operator<< (std::ostream & os, const Matrix< Value > & matrix)
Print the contents to a stream.
operator<<() [27/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const MSChromatogram & chrom)
Print the contents to a stream.
operator<<() [28/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const MSExperiment & exp)
Print the contents to a stream.
operator<<() [29/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const MSSpectrum & spec) inline
operator<<() [30/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const Param & param)
Output of Param to a stream.
operator<<() [31/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const Peak1D & point)
Print the contents to a stream.
operator<<() [32/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const Peak2D & point)
Print the contents to a stream.
operator<<() [33/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const PrecisionWrapper< FloatingPointType > & rhs) inline
Output operator for a PrecisionWrapper. Specializations are defined for float, double, long double.
References PrecisionWrapper< FloatingPointType >::ref_.
operator<<() [34/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const PSLPFormulation::IndexTriple & triple) inline
References PSLPFormulation::IndexTriple::feature, PSLPFormulation::IndexTriple::prot_acc, PSLPFormulation::IndexTriple::scan, and PSLPFormulation::IndexTriple::variable.
operator<<() [35/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const QCBase::Status & stat) inline
References QCBase::Status::value_.
operator<<() [36/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const Residue & residue)
operator<<() [37/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const Ribonucleotide & ribo)
Stream output operator.
ostream iterator to write the residue to a stream
operator<<() [38/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const SpectrumSettings & spec)
Print the contents to a stream.
operator<<() [39/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const std::vector< T > & v) inline
Output stream operator for std::vectors.
Parameters
os The target stream.
v The vector to write to stream.
operator<<() [40/44]
std::ostream& OpenMS::operator<< (std::ostream & os, const VecLowPrecision< T > & val) inline
modified version of the stream operator (works for vectors of float, double, long double) which prints only three fractional digits; usage 'os << VecLowPrecision(my_vec);'
References VecLowPrecision< T >::value.
operator<<() [41/44]
std::ostream& OpenMS::operator<< (std::ostream & os, LogConfigHandler const & lch)
Overload for the insertion operator (operator<<) to have a formatted output of the LogConfigHandler.
operator<<() [42/44]
std::ostream& OpenMS::operator<< (std::ostream & os, StreamHandler const & stream_handler)
Overload for the insertion operator (operator<<) to have a formatted output of the StreamHandler.
operator<<() [43/44]
std::ostream& OpenMS::operator<< (std::ostream & out, RawData & data)
operator<<() [44/44]
std::vector<String>& OpenMS::operator<< (std::vector< String > & sl, const TString & string) inline
Operator for appending entries with less code.
operator>>()
std::istream& OpenMS::operator>> (std::istream & os, const AASequence & peptide)
pointerComparator()
PointerComparator< Cmp > pointerComparator (Cmp const & cmp)
Make-function to create a PointerComparator from another comparator without the need to specify the template arguments.
For example,
int i = 88, j = 99;
if (pointerComparator(std::less<int>())(&i,&j))
{
  //    // yes, 88 < 99.
}
Referenced by ConstRefVector< ContainerT >::sortByComparator(), ConstRefVector< ContainerT >::sortByIntensity(), and ConstRefVector< ContainerT >::sortByPosition().
positionComparator()
bool OpenMS::positionComparator (const PeakType & a, const PeakType & b)
References Peak2D::getMZ().
precisionWrapper()
const PrecisionWrapper<FloatingPointType> OpenMS::precisionWrapper (const FloatingPointType rhs) inline
Wrapper function that sets the appropriate precision for output temporarily. The original precision is restored afterwards so that no side effects remain. This is a "make"-function that deduces the typename FloatingPointType from its argument and returns a PrecisionWrapper<FloatingPointType>.
Example:
std::cout
<< 0.1234567890123456789f << ' ' << 0.1234567890123456789 << ' ' << 0.1234567890123456789l << '\n'
<< precisionWrapper(0.1234567890123456789f) << '\n' // float
<< 0.1234567890123456789f << ' ' << 0.1234567890123456789 << ' ' << 0.1234567890123456789l << '\n'
<< precisionWrapper(0.1234567890123456789) << '\n' // double
<< 0.1234567890123456789f << ' ' << 0.1234567890123456789 << ' ' << 0.1234567890123456789l << '\n'
<< precisionWrapper(0.1234567890123456789l) << '\n' // long double
<< 0.1234567890123456789f << ' ' << 0.1234567890123456789 << ' ' << 0.1234567890123456789l << '\n';
Result:
0.123457 0.123457 0.123457
0.123457
0.123457 0.123457 0.123457
0.123456789012346
0.123457 0.123457 0.123457
0.123456789012345679
0.123457 0.123457 0.123457
Note: Unfortunately we cannot return a const& - this will change when rvalue references become part of the new C++ standard. In the meantime, we need a copy constructor for PrecisionWrapper.
Referenced by operator<<(), DTA2DFile::store(), and DTA2DFile::storeTIC().
processDriftTimeStack()
void OpenMS::processDriftTimeStack (const std::vector< MSSpectrum > & stack, std::vector< MSSpectrum > & result)
Process a stack of drift time spectra.
References MSSpectrum::clear(), MSSpectrum::getDriftTimeUnit(), OPENMS_PRECONDITION, MSSpectrum::setDriftTime(), MSSpectrum::setDriftTimeUnit(), MSSpectrum::setFloatDataArrays(), and MetaInfoDescription::setName().
Referenced by collapseIMSpectrum().
removePeaks()
void OpenMS::removePeaks (PeakContainerT & p, const double pos_start, const double pos_end, const bool ignore_data_arrays = false)
remove all peaks EXCEPT in the given range
reverseComparator()
ReverseComparator< Cmp > reverseComparator (Cmp const & cmp)
Make-function to create a ReverseComparator from another comparator without the need to specify the template arguments.
For example,
int i = 88, j = 99;
if (reverseComparator(std::less<int>())(j,i))
{
  //    // yes, 99 > 88.
}
Referenced by WindowMower::filterPeakSpectrumForTopNInJumpingWindow(), and ConstRefVector< ContainerT >::sortByIntensity().
sort_peaks_by_intensity()
bool sort_peaks_by_intensity (const PeakCandidate & a, const PeakCandidate & b)
References PeakCandidate::peak_apex_intensity.
Referenced by PeakPickerIterative::pick().
subtractMinimumIntensity()
void OpenMS::subtractMinimumIntensity (PeakContainerT & p)
typeAsString()
std::string OpenMS::typeAsString (const Type & = Type())
Returns the Type as as std::string.
Have you ever spent a long time trying to find out what a typedef actually "points" to? Then this can help.
typeAsString is implemented as a function template. There are two ways to us this:
SomeType instance;
string what_type_1 = typeAsString(instance);
string what_type_2 = typeAsString< SomeType >();
The typeAsString< SomeType >() version seems to go a bit deeper. Sometimes the results depend on how the typeAsString() is instantiated in the first place. The argument given to the function is never used, it only serves to infer the type. You can even supply function pointers, etc.
Example (Tutorial_typeAsString.cpp):
// --------------------------------------------------------------------------
//                   OpenMS -- Open-Source Mass Spectrometry
// --------------------------------------------------------------------------
// Copyright The OpenMS Team -- Eberhard Karls University Tuebingen,
// ETH Zurich, and Freie Universitaet Berlin 2002-2018.
//
// This software is released under a three-clause BSD license:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of any author or any participating institution
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
// For a full list of authors, refer to the file AUTHORS.
// --------------------------------------------------------------------------
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL ANY OF THE AUTHORS OR THE CONTRIBUTING
// INSTITUTIONS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#include <OpenMS/CONCEPT/Types.h>
#include <OpenMS/CONCEPT/TypeAsString.h>
#include <OpenMS/KERNEL/DPeak.h>
#include <iostream>
double someFunc(int, int *)
{
  return 9.9;
}
template <typename, int = 5>
struct WOW
{
  static float staticMemberFunc(float &) {return 0; }
  double memberFunc(const double &) {return 0; }
};
template <typename X, int I, unsigned J = 666, template <class, int> class WauWau = WOW>
struct Oink {};
int main()
{
  using namespace OpenMS;
  using namespace std;
  cout << typeAsString(1) << endl;
  cout << typeAsString(2u) << endl;
  cout << typeAsString(3.) << endl;
  cout << typeAsString(4.f) << endl;
  cout << endl;
  cout << typeAsString<Int>() << endl;
  cout << typeAsString<PointerSizeUInt>() << endl;
  cout << endl;
  cout << typeAsString(Peak1D()) << endl;
  cout << typeAsString(DPeak<1>::Type()) << endl;
  cout << typeAsString(DPeak<1>::Type::PositionType()) << endl;
  cout << typeAsString<DPeak<1>::Type::CoordinateType>() << endl;
  cout << typeAsString<DPeak<1>::Type::IntensityType>() << endl;
  cout << endl;
  cout << typeAsString(&someFunc) << endl;
  cout << typeAsString<WOW<char const * const *** const &> >() << endl;
  cout << typeAsString<Oink<double, 55> >() << endl;
  cout << typeAsString(&WOW<string, 8>::staticMemberFunc) << endl;
  cout << typeAsString(&WOW<char, 8>::memberFunc) << endl;
  return 0;
} // end of Tutorial_typeAsString.cpp
On a 64 bit platform running GCC 4.3.1, this produced the following output:
int
unsigned int
double
float
int
long unsigned int
OpenMS::Peak1D
OpenMS::Peak1D
OpenMS::DPosition<1u>
double
float
double ()(int, int*)
WOW<const char* const*** const&, 5>
Oink<double, 55, 666u, WOW>
float ()(float&)
double (WOW<char, 8>::*)(const double&)
writtenDigits()
constexpr Int writtenDigits (const FloatingPointType & = FloatingPointType()) inline constexpr
Number of digits commonly used for writing a floating point type (a.k.a. precision). Specializations are defined for float, double, long double.
The general template definition will return the default precision of 6 according to 27.4.4.1 basic_iosconstructors (C++ Standard).
Referenced by StringUtils::numberLength().
writtenDigits< DataValue >()
constexpr Int OpenMS::writtenDigits< DataValue > (const DataValue &) inline constexpr
DataValue will be printed like double.
writtenDigits< double >()
constexpr Int OpenMS::writtenDigits< double > (const double &) inline constexpr
Number of digits commonly used for writing a double (a.k.a. precision).
Referenced by operator<<(), and DTAFile::store().
writtenDigits< float >()
constexpr Int OpenMS::writtenDigits< float > (const float &) inline constexpr
Number of digits commonly used for writing a float (a.k.a. precision).
writtenDigits< int >()
constexpr Int OpenMS::writtenDigits< int > (const int &) inline constexpr
We do not want to bother people who unintentionally provide an int argument to this.
writtenDigits< long double >()
constexpr Int OpenMS::writtenDigits< long double > (const long double &) inline constexpr
Number of digits commonly used for writing a long double (a.k.a. precision). ...
Note: On Microsoft platforms, the I/O system seems to treat long double just like double. We observed that std::numeric_limits<long double>::digits10 == 18 with GCC 3.4 on MinGW, but this promise is not kept by the Microsoft I/O system libraries. Therefore we use the value of digits10 for double also for long double. See http://msdn.microsoft.com/ + search: "long double".
writtenDigits< long int >()
constexpr Int OpenMS::writtenDigits< long int > (const long int &) inline constexpr
We do not want to bother people who unintentionally provide a long int argument to this.
writtenDigits< unsigned int >()
constexpr Int OpenMS::writtenDigits< unsigned int > (const unsigned int &) inline constexpr
We do not want to bother people who unintentionally provide an unsigned int argument to this.
writtenDigits< unsigned long int >()
constexpr Int OpenMS::writtenDigits< unsigned long int > (const unsigned long int &) inline constexpr
We do not want to bother people who unintentionally provide an unsigned long int argument to this.
Variable Documentation
BinaryDataEncoder_default_numpressErrorTolerance
const double BinaryDataEncoder_default_numpressErrorTolerance = .0001
OpenMS_Log_debug
Logger::LogStream OpenMS_Log_debug
Global static instance of a LogStream to capture messages classified as debug output. By default it is not bound to any output stream. TOPP(AS)Base will connect cout, iff 0 < debug-level.
Referenced by UTILProteomicsLFQ::align_(), main(), TOPPXFDR::main_(), TOPPOpenPepXLLF::main_(), and TOPPOpenPepXL::main_().
OpenMS_Log_error
Logger::LogStream OpenMS_Log_error
Global static instance of a LogStream to capture messages classified as errors. By default it is bound to cerr.
Referenced by main().
OpenMS_Log_fatal
Logger::LogStream OpenMS_Log_fatal
Global static instance of a LogStream to capture messages classified as fatal errors. By default it is bound to cerr.
OpenMS_Log_info
Logger::LogStream OpenMS_Log_info
Global static instance of a LogStream to capture messages classified as information. By default it is bound to cout.
OpenMS_Log_warn
Logger::LogStream OpenMS_Log_warn
Global static instance of a LogStream to capture messages classified as warnings. By default it is bound to cout.
PrecursorMZLess
struct OpenMS::PrecursorMassComparator PrecursorMZLess
SpectralMatchScoreGreater
struct OpenMS::SpectralMatchScoreComparator SpectralMatchScoreGreater
STREAM_HANDLER
StreamHandler STREAM_HANDLER
Global StreamHandler instance.