OpenMS: Get scores from ID structures for FDR
Get scores from ID structures for FDR
Fills the scores_labels vector from an ID data structure.
Functions
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const std::vector< ProteinIdentification::ProteinGroup > &grps, const std::unordered_set< std::string > &decoy_accs)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const ProteinIdentification &id)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideIdentification &id, bool all_hits, int charge, const String &identifier)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideIdentification &id, bool all_hits, const String &identifier)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideIdentification &id, int charge, const String &identifier)
template<typename IDType , typename std::enable_if< IsIDType< IDType >::value >::type * = nullptr>
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const IDType &id, const String &identifier)
template<class ... Args>
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideIdentification &id, bool all_hits, Args &&... args)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideHit &hit, int charge)
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const PeptideIdentification &id, int charge)
template<typename HitType , typename std::enable_if< IsHitType< HitType >::value >::type * = nullptr>
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const HitType &hit)
template<typename IDType , typename std::enable_if< IsIDType< IDType >::value >::type * = nullptr>
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const IDType &id)
template<class ... Args>
static void getScores_ (ScoreToTgtDecLabelPairs &scores_labels, const std::vector< PeptideIdentification > &ids, Args &&... args)
Detailed Description
Fills the scores_labels vector from an ID data structure.
Parameters
scores_labels Pairs of scores and boolean target decoy labels to be filled. target = true.
Just use the one you need.
Function Documentation
getScores_() [1/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const HitType & hit) inline static
References IDScoreGetterSetter::checkTDAnnotation_(), and IDScoreGetterSetter::getTDLabel_().
getScores_() [2/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const IDType & id) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [3/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const IDType & id, const String & identifier) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [4/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideHit & hit, int charge) inline static
References IDScoreGetterSetter::checkTDAnnotation_(), PeptideHit::getCharge(), PeptideHit::getScore(), and IDScoreGetterSetter::getTDLabel_().
getScores_() [5/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideIdentification & id, bool all_hits, Args &&... args) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [6/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideIdentification & id, bool all_hits, const String & identifier) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [7/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideIdentification & id, bool all_hits, int charge, const String & identifier) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [8/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideIdentification & id, int charge) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [9/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const PeptideIdentification & id, int charge, const String & identifier) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [10/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const ProteinIdentification & id) inline static
References IDScoreGetterSetter::checkTDAnnotation_(), ProteinHit::getScore(), and IDScoreGetterSetter::getTDLabel_().
getScores_() [11/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const std::vector< PeptideIdentification > & ids, Args &&... args) inline static
References IDScoreGetterSetter::getScores_().
getScores_() [12/12]
static void getScores_ (ScoreToTgtDecLabelPairs & scores_labels, const std::vector< ProteinIdentification::ProteinGroup > & grps, const std::unordered_set< std::string > & decoy_accs) static
Referenced by IDScoreGetterSetter::getPeptideScoresFromMap_(), and IDScoreGetterSetter::getScores_().