OpenMS: OpenMS::Internal Namespace Reference
OpenMS::Internal Namespace Reference
Namespace used to hide implementation details from users.
Namespaces
ClassTest
Namespace for class tests.
SqliteHelper
Classes
class AcqusHandler
Read-only acqus File handler for XMass Analysis.
class AreaIterator
Forward iterator for an area of peaks in an experiment.
class CachedMzMLHandler
An class that uses on-disk caching to read and write spectra and chromatograms.
class DIntervalBase
A base class for D-dimensional interval.
class FidHandler
Read-only fid File handler for XMass Analysis.
struct FileMapping
Maps input/output files to filenames for the external program.
class IDBoostGraph
Creates and maintains a boost graph based on the OpenMS ID datastructures.
class IndexedMzMLHandler
A low-level class to read an indexedmzML file.
class IntensityIteratorWrapper
An iterator wrapper to access peak intensities instead of the peak itself.
class ListEditorDelegate
Internal delegate class.
class ListTable
struct Looper
struct Looper< grid_size, grid_size, EvalResult, Tuple, TupleTypes... >
struct Looper< param_index, grid_size, EvalResult, Tuple, FirstTupleType, TupleTypes... >
struct MappingParam
Filename mappings for all input/output files.
class MascotXMLHandler
Handler that is used for parsing MascotXML data.
class MessagePasserFactory
class MzDataHandler
class MzDataValidator
Semantically validates MzXML files.
class MzIdentMLDOMHandler
XML DOM handler for MzIdentMLFile.
class MzIdentMLHandler
XML STREAM handler for MzIdentMLFile.
class MzIdentMLValidator
Semantically validates MzXML files.
class MzMLHandler
Handler for mzML file format.
class MzMLHandlerHelper
Helper for mzML file format.
class MzMLSqliteHandler
Sqlite handler for storing spectra and chromatograms in sqMass format.
class MzMLSqliteSwathHandler
Sqlite handler for SWATH data sets.
class MzMLValidator
Semantically validates MzXML files.
class MzQuantMLHandler
XML handler for MzQuantMLFile.
class MzQuantMLValidator
Semantically validates MzQuantML files.
class MzXMLHandler
class OpenMSLineEdit
Custom QLineEdit which emits a signal when losing focus (such that we can commit its data)
struct OpenMSOSInfo
class ParamEditorDelegate
Internal delegate class for QTreeWidget.
class ParamTree
QTreeWidget that emits a signal whenever a new row is selected.
class ParamXMLHandler
XML Handler for Param files.
class PTMXMLHandler
Handler that is used for parsing PTMXML data.
class RNPxlFragmentAnnotationHelper
Convenience functions to construct appealing fragment annotation strings and store them as PeptideHit::PeakAnnotation.
class SemanticValidator
Semantically validates XML files using CVMappings and a ControlledVocabulary.
class Spectrum1DPrefDialog
Preferences dialog for Spectrum1DWidget.
class Spectrum2DPrefDialog
Preferences dialog for Spectrum2DWidget.
class Spectrum3DPrefDialog
Preferences dialog for Spectrum3DWidget.
class StringManager
struct ToolDescription
class ToolDescriptionHandler
XML handler for ToolDescriptionFile.
struct ToolDescriptionInternal
ToolDescription Class.
struct ToolExternalDetails
class TOPPViewPrefDialog
Preferences dialog for TOPPView.
class TraMLHandler
XML handler for TraMLFile.
class TraMLValidator
Semantically validates MzXML files.
class UnimodXMLHandler
Handler that is used for parsing XTandemXML data.
class XMLFile
Base class for loading/storing XML files that have a handler derived from XMLHandler.
class XMLHandler
Base class for XML handlers.
class XQuestResultXMLHandler
XMLHandler for the result files of XQuest.
Typedefs
typedef PeakMap MapType
XML handler for MzDataFile.
typedef MSSpectrum SpectrumType
typedef MSChromatogram ChromatogramType
Enumerations
enum OpenMS_OS { OS_UNKNOWN, OS_MACOS, OS_WINDOWS, OS_LINUX }
enum OpenMS_Architecture { ARCH_UNKNOWN, ARCH_32BIT, ARCH_64BIT }
Functions
bool PermutScoreComparator (const CompNovoIdentificationBase::Permut &p1, const CompNovoIdentificationBase::Permut &p2)
template<UInt D>
std::ostream & operator<< (std::ostream &os, const DIntervalBase< D > &rhs)
Print the contents to a stream.
template<typename IteratorT >
IntensityIteratorWrapper< IteratorT > intensityIteratorWrapper (const IteratorT &rhs)
make-function so that we need no write out all those type names to get the wrapped iterator.
String encodeTab (const String &to_encode)
Encodes tabs '\t' in the string as &#x9; and returns the encoded string.
static OpenMSOSInfo getOSInfo ()
OpenMS_Architecture getBinaryArchitecture ()
Variables
const char * OpenMS_locale
std::string OpenMS_OSNames [] = {"unknown", "MacOS", "Windows", "Linux"}
std::string OpenMS_ArchNames [] = {"unknown", "32 bit", "64 bit"}
Detailed Description
Namespace used to hide implementation details from users.
Class Documentation
OpenMS::Internal::Looper
struct OpenMS::Internal::Looper
template<size_t param_index, size_t grid_size, typename EvalResult, typename Tuple, typename... TupleTypes>
struct OpenMS::Internal::Looper< param_index, grid_size, EvalResult, Tuple, TupleTypes >
OpenMS::Internal::ToolExternalDetails
struct OpenMS::Internal::ToolExternalDetails
Class Members
String category
String commandline
Param param
String path filename to external tool
String text_fail
String text_finish
String text_startup
MappingParam tr_table
String working_directory folder where the command will be executed from
Typedef Documentation
ChromatogramType
typedef MSChromatogram ChromatogramType
MapType
typedef PeakMap MapType
XML handler for MzDataFile.
XML handlers for MzXMLFile.
MapType has to be a MSExperiment or have the same interface. Do not use this class. It is only needed in MzDataFile.
Improvement:
Add implementation and tests of 'supDataArray' to store IntegerDataArray and StringDataArray of MSSpectrum (Hiwi)
MapType has to be a MSExperiment or have the same interface. Do not use this class. It is only needed in MzXMLFile.
SpectrumType
typedef MSSpectrum SpectrumType
Enumeration Type Documentation
OpenMS_Architecture
enum OpenMS_Architecture
Enumerator
ARCH_UNKNOWN
ARCH_32BIT
ARCH_64BIT
OpenMS_OS
enum OpenMS_OS
Enumerator
OS_UNKNOWN
OS_MACOS
OS_WINDOWS
OS_LINUX
Function Documentation
encodeTab()
String OpenMS::Internal::encodeTab (const String & to_encode)
Encodes tabs '\t' in the string as &#x9; and returns the encoded string.
Parameters
to_encode The String to encode.
Returns
The encoded string.
getBinaryArchitecture()
OpenMS_Architecture OpenMS::Internal::getBinaryArchitecture ()
References ARCH_32BIT, ARCH_64BIT, and ARCH_UNKNOWN.
getOSInfo()
static OpenMSOSInfo OpenMS::Internal::getOSInfo () static
References OpenMSOSInfo::arch, ARCH_32BIT, ARCH_64BIT, OpenMSOSInfo::os, OS_LINUX, OS_MACOS, OpenMSOSInfo::os_version, and OS_WINDOWS.
intensityIteratorWrapper()
IntensityIteratorWrapper<IteratorT> OpenMS::Internal::intensityIteratorWrapper (const IteratorT & rhs)
make-function so that we need no write out all those type names to get the wrapped iterator.
Referenced by MorphologicalFilter::filter().
operator<<()
std::ostream& OpenMS::Internal::operator<< (std::ostream & os, const DIntervalBase< D > & rhs)
Print the contents to a stream.
References DIntervalBase< D >::maxPosition(), and DIntervalBase< D >::minPosition().
PermutScoreComparator()
bool OpenMS::Internal::PermutScoreComparator (const CompNovoIdentificationBase::Permut & p1, const CompNovoIdentificationBase::Permut & p2)
Variable Documentation
OpenMS_ArchNames
std::string OpenMS_ArchNames[] = {"unknown", "32 bit", "64 bit"}
Referenced by OpenMSOSInfo::getArchAsString().
OpenMS_locale
const char* OpenMS_locale
Used to set the locale to "C", to avoid problems on machines with incompatible locale settings (this overwrites the locale setting of the environment!)
OpenMS_OSNames
std::string OpenMS_OSNames[] = {"unknown", "MacOS", "Windows", "Linux"}
Referenced by OpenMSOSInfo::getOSAsString().