OpenMS: OpenMS::StringConversions Namespace Reference
OpenMS::StringConversions Namespace Reference
Classes
class BK_PrecPolicy
Typedefs
typedef boost::spirit::karma::real_generator< float, BK_PrecPolicy< float > > BK_PrecPolicyFloat_type
typedef boost::spirit::karma::real_generator< double, BK_PrecPolicy< double > > BK_PrecPolicyDouble_type
typedef boost::spirit::karma::real_generator< long double, BK_PrecPolicy< long double > > BK_PrecPolicyLongDouble_type
Functions
template<typename T >
void append (const T &i, String &target)
template<typename T >
String toString (const T &i)
fallback template for general purpose using Boost::Karma; more specializations below
void appendLowP (float f, String &target)
String toStringLowP (float f)
low precision (3 fractional digits) conversion to string (Karma default)
void appendLowP (double d, String &target)
String toStringLowP (double d)
low precision (3 fractional digits) conversion to string (Karma default)
void appendLowP (long double ld, String &target)
low precision (3 fractional digits) conversion to string (Karma default)
String toStringLowP (long double ld)
low precision (3 fractional digits) conversion to string (Karma default)
void append (float f, String &target)
high precision (6 fractional digits) conversion to String
String toString (float f)
high precision (6 fractional digits) conversion to String
void append (double d, String &target)
high precision (15 fractional digits) conversion to String
String toString (double d)
high precision (15 fractional digits) conversion to String
void append (long double ld, String &target)
high precision (15 fractional digits) conversion to String
String toString (long double ld)
high precision (15 fractional digits) conversion to String
void append (const DataValue &d, bool full_precision, String &target)
String toString (const DataValue &d, bool full_precision)
String toString (const char c)
String toString (const std::string &s)
String toString (const char *s)
String toString ()
Other toString functions (different number of arguments)
String toString (const char *s, size_t length)
Variables
const BK_PrecPolicyFloat_type BK_PrecPolicyFloat
const BK_PrecPolicyDouble_type BK_PrecPolicyDouble
const BK_PrecPolicyLongDouble_type BK_PrecPolicyLongDouble
Typedef Documentation
BK_PrecPolicyDouble_type
typedef boost::spirit::karma::real_generator<double, BK_PrecPolicy<double> > BK_PrecPolicyDouble_type
BK_PrecPolicyFloat_type
typedef boost::spirit::karma::real_generator<float, BK_PrecPolicy<float> > BK_PrecPolicyFloat_type
BK_PrecPolicyLongDouble_type
typedef boost::spirit::karma::real_generator<long double, BK_PrecPolicy<long double> > BK_PrecPolicyLongDouble_type
Function Documentation
append() [1/5]
void OpenMS::StringConversions::append (const DataValue & d, bool full_precision, String & target) inline
References DataValue::toString().
append() [2/5]
void OpenMS::StringConversions::append (const T & i, String & target) inline
fallback template for general purpose using Boost::Karma; more specializations below does NOT clear the input string target, so appending is as efficient as possible
Referenced by seqan::addHits(), and toString().
append() [3/5]
void OpenMS::StringConversions::append (double d, String & target) inline
high precision (15 fractional digits) conversion to String
References BK_PrecPolicyDouble.
append() [4/5]
void OpenMS::StringConversions::append (float f, String & target) inline
high precision (6 fractional digits) conversion to String
References BK_PrecPolicyFloat.
append() [5/5]
void OpenMS::StringConversions::append (long double ld, String & target) inline
high precision (15 fractional digits) conversion to String
References BK_PrecPolicyLongDouble.
appendLowP() [1/3]
void OpenMS::StringConversions::appendLowP (double d, String & target) inline
low precision (3 fractional digits) conversion to string (Karma default) does NOT clear the input string target, so appending is as efficient as possible
appendLowP() [2/3]
void OpenMS::StringConversions::appendLowP (float f, String & target) inline
low precision (3 fractional digits) conversion to string (Karma default) does NOT clear the input string target, so appending is as efficient as possible
Referenced by toStringLowP().
appendLowP() [3/3]
void OpenMS::StringConversions::appendLowP (long double ld, String & target) inline
low precision (3 fractional digits) conversion to string (Karma default)
toString() [1/10]
String OpenMS::StringConversions::toString () inline
Other toString functions (different number of arguments)
toString() [2/10]
String OpenMS::StringConversions::toString (const char * s) inline
toString() [3/10]
String OpenMS::StringConversions::toString (const char * s, size_t length) inline
toString() [4/10]
String OpenMS::StringConversions::toString (const char c) inline
References OpenMS::Constants::c.
toString() [5/10]
String OpenMS::StringConversions::toString (const DataValue & d, bool full_precision) inline
References DataValue::toString().
toString() [6/10]
String OpenMS::StringConversions::toString (const std::string & s) inline
toString() [7/10]
String OpenMS::StringConversions::toString (const T & i) inline
fallback template for general purpose using Boost::Karma; more specializations below
References append().
Referenced by TOPPViewBase::updateFilterBar().
toString() [8/10]
String OpenMS::StringConversions::toString (double d) inline
high precision (15 fractional digits) conversion to String
References append().
toString() [9/10]
String OpenMS::StringConversions::toString (float f) inline
high precision (6 fractional digits) conversion to String
References append().
toString() [10/10]
String OpenMS::StringConversions::toString (long double ld) inline
high precision (15 fractional digits) conversion to String
References append().
toStringLowP() [1/3]
String OpenMS::StringConversions::toStringLowP (double d) inline
low precision (3 fractional digits) conversion to string (Karma default)
References appendLowP().
toStringLowP() [2/3]
String OpenMS::StringConversions::toStringLowP (float f) inline
low precision (3 fractional digits) conversion to string (Karma default)
References appendLowP().
toStringLowP() [3/3]
String OpenMS::StringConversions::toStringLowP (long double ld) inline
low precision (3 fractional digits) conversion to string (Karma default)
References appendLowP().
Variable Documentation
BK_PrecPolicyDouble
const BK_PrecPolicyDouble_type BK_PrecPolicyDouble
Referenced by append().
BK_PrecPolicyFloat
const BK_PrecPolicyFloat_type BK_PrecPolicyFloat
Referenced by append().
BK_PrecPolicyLongDouble
const BK_PrecPolicyLongDouble_type BK_PrecPolicyLongDouble
Referenced by append().