OpenMS: LightTargetedExperiment Struct Reference
LightTargetedExperiment Struct Reference
#include <OpenMS/OPENSWATHALGO/DATAACCESS/TransitionExperiment.h>
Public Types
typedef LightTransition Transition
typedef LightCompound Peptide
typedef LightCompound Compound
typedef LightProtein Protein
Public Member Functions
LightTargetedExperiment ()
std::vector< LightTransition > & getTransitions ()
const std::vector< LightTransition > & getTransitions () const
std::vector< LightCompound > & getCompounds ()
const std::vector< LightCompound > & getCompounds () const
std::vector< LightProtein > & getProteins ()
const std::vector< LightProtein > & getProteins () const
const LightCompound & getPeptideByRef (const std::string &ref)
const LightCompound & getCompoundByRef (const std::string &ref)
Public Attributes
std::vector< LightTransition > transitions
std::vector< LightCompound > compounds
std::vector< LightProtein > proteins
Private Member Functions
void createPeptideReferenceMap_ ()
Private Attributes
bool compound_reference_map_dirty_
std::map< std::string, LightCompound * > compound_reference_map_
Member Typedef Documentation
Compound
typedef LightCompound Compound
Peptide
typedef LightCompound Peptide
Protein
typedef LightProtein Protein
Transition
typedef LightTransition Transition
Constructor & Destructor Documentation
LightTargetedExperiment()
LightTargetedExperiment () inline
Member Function Documentation
createPeptideReferenceMap_()
void createPeptideReferenceMap_ () inline private
References LightTargetedExperiment::compound_reference_map_, LightTargetedExperiment::compound_reference_map_dirty_, and LightTargetedExperiment::getCompounds().
Referenced by LightTargetedExperiment::getCompoundByRef().
getCompoundByRef()
const LightCompound& getCompoundByRef (const std::string & ref) inline
References LightTargetedExperiment::compound_reference_map_, LightTargetedExperiment::compound_reference_map_dirty_, and LightTargetedExperiment::createPeptideReferenceMap_().
Referenced by OpenMS::ChromatogramExtractor::extract_id_< OpenSwath::LightTargetedExperiment >(), and LightTargetedExperiment::getPeptideByRef().
getCompounds() [1/2]
std::vector<LightCompound>& getCompounds () inline
References LightTargetedExperiment::compounds.
Referenced by LightTargetedExperiment::createPeptideReferenceMap_().
getCompounds() [2/2]
const std::vector<LightCompound>& getCompounds () const inline
References LightTargetedExperiment::compounds.
getPeptideByRef()
const LightCompound& getPeptideByRef (const std::string & ref) inline
References LightTargetedExperiment::getCompoundByRef().
getProteins() [1/2]
std::vector<LightProtein>& getProteins () inline
References LightTargetedExperiment::proteins.
getProteins() [2/2]
const std::vector<LightProtein>& getProteins () const inline
References LightTargetedExperiment::proteins.
getTransitions() [1/2]
std::vector<LightTransition>& getTransitions () inline
References LightTargetedExperiment::transitions.
getTransitions() [2/2]
const std::vector<LightTransition>& getTransitions () const inline
References LightTargetedExperiment::transitions.
Member Data Documentation
compound_reference_map_
std::map<std::string, LightCompound*> compound_reference_map_ private
Referenced by LightTargetedExperiment::createPeptideReferenceMap_(), and LightTargetedExperiment::getCompoundByRef().
compound_reference_map_dirty_
bool compound_reference_map_dirty_ private
Referenced by LightTargetedExperiment::createPeptideReferenceMap_(), and LightTargetedExperiment::getCompoundByRef().
compounds
std::vector<LightCompound> compounds
Referenced by LightTargetedExperiment::getCompounds().
proteins
std::vector<LightProtein> proteins
Referenced by LightTargetedExperiment::getProteins().
transitions
std::vector<LightTransition> transitions
Referenced by LightTargetedExperiment::getTransitions(), and TOPPOpenSwathBase::prepareChromOutput().