OpenMS: IDBoostGraph::PrintAddressVisitor< CharT > Class Template Reference
IDBoostGraph::PrintAddressVisitor< CharT > Class Template Reference
#include <OpenMS/ANALYSIS/ID/IDBoostGraph.h>
Public Member Functions
PrintAddressVisitor (std::basic_ostream< CharT > stream)
void operator() (PeptideHit *pep) const
void operator() (ProteinHit *prot) const
void operator() (const ProteinGroup &) const
void operator() (const PeptideCluster &) const
void operator() (const Peptide &peptide) const
void operator() (const RunIndex &ri) const
void operator() (const Charge &chg) const
Public Attributes
std::basic_ostream< CharT > stream_
Detailed Description
template<class CharT>
class OpenMS::Internal::IDBoostGraph::PrintAddressVisitor< CharT >
Visits nodes in the boost graph (ptrs to an ID Object) and depending on their type prints the address. For debugging purposes only
Constructor & Destructor Documentation
PrintAddressVisitor()
PrintAddressVisitor (std::basic_ostream< CharT > stream) inline explicit
Member Function Documentation
operator()() [1/7]
void operator() (const Charge & chg) const inline
operator()() [2/7]
void operator() (const Peptide & peptide) const inline
operator()() [3/7]
void operator() (const PeptideCluster &) const inline
operator()() [4/7]
void operator() (const ProteinGroup &) const inline
operator()() [5/7]
void operator() (const RunIndex & ri) const inline
operator()() [6/7]
void operator() (PeptideHit * pep) const inline
References PeptideHit::getSequence(), and AASequence::toUnmodifiedString().
operator()() [7/7]
void operator() (ProteinHit * prot) const inline
References ProteinHit::getAccession().
Member Data Documentation
stream_
std::basic_ostream<CharT> stream_