OpenMS: IDBoostGraph::LabelVisitor Class Reference
IDBoostGraph::LabelVisitor Class Reference
Visits nodes in the boost graph (ptrs to an ID Object) and depending on their type creates a label.
#include <OpenMS/ANALYSIS/ID/IDBoostGraph.h>
Public Member Functions
OpenMS::String operator() (const PeptideHit *pep) const
OpenMS::String operator() (const ProteinHit *prot) const
OpenMS::String operator() (const ProteinGroup &) const
OpenMS::String operator() (const PeptideCluster &) const
OpenMS::String operator() (const Peptide &peptide) const
OpenMS::String operator() (const RunIndex &ri) const
OpenMS::String operator() (const Charge &chg) const
Detailed Description
Visits nodes in the boost graph (ptrs to an ID Object) and depending on their type creates a label.
Member Function Documentation
operator()() [1/7]
OpenMS::String operator() (const Charge & chg) const inline
operator()() [2/7]
OpenMS::String operator() (const Peptide & peptide) const inline
operator()() [3/7]
OpenMS::String operator() (const PeptideCluster &) const inline
operator()() [4/7]
OpenMS::String operator() (const PeptideHit * pep) const inline
References PeptideHit::getCharge(), PeptideHit::getSequence(), and AASequence::toString().
operator()() [5/7]
OpenMS::String operator() (const ProteinGroup &) const inline
operator()() [6/7]
OpenMS::String operator() (const ProteinHit * prot) const inline
References ProteinHit::getAccession().
operator()() [7/7]
OpenMS::String operator() (const RunIndex & ri) const inline