OpenMS: PeptideIndexing::FoundProteinFunctor Struct Reference
PeptideIndexing::FoundProteinFunctor Struct Reference
#include <OpenMS/ANALYSIS/ID/PeptideIndexing.h>
Public Types
typedef std::map< OpenMS::Size, std::set< PeptideProteinMatchInformation > > MapType
Public Member Functions
FoundProteinFunctor (const ProteaseDigestion &enzyme, bool xtandem)
void merge (FoundProteinFunctor &other)
void addHit (const OpenMS::Size idx_pep, const OpenMS::Size idx_prot, const OpenMS::Size len_pep, const OpenMS::String &seq_prot, OpenMS::Int position)
Public Attributes
MapType pep_to_prot
OpenMS::Size filter_passed
OpenMS::Size filter_rejected
Private Attributes
ProteaseDigestion enzyme_
bool xtandem_
Member Typedef Documentation
MapType
typedef std::map<OpenMS::Size, std::set<PeptideProteinMatchInformation> > MapType
Constructor & Destructor Documentation
FoundProteinFunctor()
FoundProteinFunctor (const ProteaseDigestion & enzyme, bool xtandem) inline explicit
Member Function Documentation
addHit()
void addHit (const OpenMS::Size idx_pep, const OpenMS::Size idx_prot, const OpenMS::Size len_pep, const OpenMS::String & seq_prot, OpenMS::Int position) inline
References PeptideIndexing::PeptideProteinMatchInformation::AAAfter, PeptideIndexing::PeptideProteinMatchInformation::AABefore, PeptideEvidence::C_TERMINAL_AA, ProteaseDigestion::isValidProduct(), PeptideEvidence::N_TERMINAL_AA, seqan::position(), PeptideIndexing::PeptideProteinMatchInformation::position, and PeptideIndexing::PeptideProteinMatchInformation::protein_index.
Referenced by PeptideIndexing::addHits_().
merge()
void merge (FoundProteinFunctor & other) inline
References PeptideIndexing::FoundProteinFunctor::filter_passed, PeptideIndexing::FoundProteinFunctor::filter_rejected, and PeptideIndexing::FoundProteinFunctor::pep_to_prot.
Referenced by PeptideIndexing::run().
Member Data Documentation
enzyme_
ProteaseDigestion enzyme_ private
filter_passed
OpenMS::Size filter_passed
Referenced by PeptideIndexing::FoundProteinFunctor::merge(), and PeptideIndexing::run().
filter_rejected
OpenMS::Size filter_rejected
Referenced by PeptideIndexing::FoundProteinFunctor::merge(), and PeptideIndexing::run().
pep_to_prot
MapType pep_to_prot
Referenced by PeptideIndexing::FoundProteinFunctor::merge(), and PeptideIndexing::run().
xtandem_
bool xtandem_ private