OpenMS: PeptideIndexing::PeptideProteinMatchInformation Struct Reference
PeptideIndexing::PeptideProteinMatchInformation Struct Reference
#include <OpenMS/ANALYSIS/ID/PeptideIndexing.h>
Public Member Functions
const std::tuple< const Size &, const Int &, const char &, const char & > tie () const
bool operator< (const PeptideProteinMatchInformation &other) const
bool operator== (const PeptideProteinMatchInformation &other) const
Public Attributes
OpenMS::Size protein_index
OpenMS::Int position
char AABefore
char AAAfter
Member Function Documentation
operator<()
bool operator< (const PeptideProteinMatchInformation & other) const inline
References PeptideIndexing::PeptideProteinMatchInformation::tie().
operator==()
bool operator== (const PeptideProteinMatchInformation & other) const inline
References PeptideIndexing::PeptideProteinMatchInformation::tie().
tie()
const std::tuple<const Size&, const Int&, const char&, const char&> tie () const inline
References seqan::position().
Referenced by PeptideIndexing::PeptideProteinMatchInformation::operator<(), and PeptideIndexing::PeptideProteinMatchInformation::operator==().
Member Data Documentation
AAAfter
char AAAfter
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().
AABefore
char AABefore
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().
position
OpenMS::Int position
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().
protein_index
OpenMS::Size protein_index
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().