OpenMS: ReactionMonitoringTransition Class Reference
ReactionMonitoringTransition Class Reference
This class stores a SRM/MRM transition.
#include <OpenMS/ANALYSIS/MRM/ReactionMonitoringTransition.h>
Classes
struct ProductMZLess
Comparator by Product ion MZ.
Public Types
enum DecoyTransitionType { UNKNOWN, TARGET, DECOY }
typedef TargetedExperimentHelper::Configuration Configuration
typedef TargetedExperimentHelper::RetentionTime RetentionTime
typedef TargetedExperimentHelper::TraMLProduct Product
typedef TargetedExperimentHelper::Prediction Prediction
Public Member Functions
Constructors and destructors
ReactionMonitoringTransition ()
default constructor
ReactionMonitoringTransition (const ReactionMonitoringTransition &rhs)
copy constructor
ReactionMonitoringTransition (ReactionMonitoringTransition &&) noexcept
Move constructor.
~ReactionMonitoringTransition () override
destructor
ReactionMonitoringTransition & operator= (const ReactionMonitoringTransition &rhs)
assignment operator
ReactionMonitoringTransition & operator= (ReactionMonitoringTransition &&rhs)
move assignment operator
Accessors
void setName (const String &name)
const String & getName () const
void setNativeID (const String &name)
const String & getNativeID () const
void setPeptideRef (const String &peptide_ref)
const String & getPeptideRef () const
void setCompoundRef (const String &compound_ref)
const String & getCompoundRef () const
void setPrecursorMZ (double mz)
sets the precursor mz (Q1 value)
double getPrecursorMZ () const
get the precursor mz (Q1 value)
bool hasPrecursorCVTerms () const
Returns true if precursor CV Terms exist (means it is safe to call getPrecursorCVTermList)
void setPrecursorCVTermList (const CVTermList &list)
void addPrecursorCVTerm (const CVTerm &cv_term)
const CVTermList & getPrecursorCVTermList () const
Obtain the list of CV Terms for the precursor.
void setProductMZ (double mz)
double getProductMZ () const
int getProductChargeState () const
bool isProductChargeStateSet () const
void addProductCVTerm (const CVTerm &cv_term)
const std::vector< Product > & getIntermediateProducts () const
void addIntermediateProduct (Product product)
void setIntermediateProducts (const std::vector< Product > &products)
void setProduct (Product product)
const Product & getProduct () const
bool hasPrediction () const
Returns true if a Prediction object exists (means it is safe to call getPrediction)
void setPrediction (const Prediction &prediction)
void addPredictionTerm (const CVTerm &prediction)
const Prediction & getPrediction () const
Obtain the Prediction object.
DecoyTransitionType getDecoyTransitionType () const
Returns the type of transition (target or decoy)
void setDecoyTransitionType (const DecoyTransitionType &d)
Sets the type of transition (target or decoy)
double getLibraryIntensity () const
Returns the library intensity (ion count or normalized ion count from a spectral library)
void setLibraryIntensity (double intensity)
Sets the library intensity (ion count or normalized ion count from a spectral library)
Retention time
Retention time set on transition level
Note
Retention time can be set on analyte level (peptide / compound level) or transition level – usually the retention time set here on transition level is ignored, therefore only use this if you have a good reason.
void setRetentionTime (RetentionTime rt)
Sets the retention time on transition level.
const RetentionTime & getRetentionTime () const
Gets the retention time on transition level.
Detecting transitions
Transitions used for detection of analyte
Detecting transitions represent the set of transitions of an assay that should be used to enable candidate peak group detection. Ideally they were observed and validated in previous experiments and have an associated library intensity.
For an overview, see Schubert OT et al., Building high-quality assay libraries for targeted analysis of SWATH MS data., Nat Protoc. 2015 Mar;10(3):426-41. doi: 10.1038/nprot.2015.015. Epub 2015 Feb 12. PMID: 25675208
bool isDetectingTransition () const
void setDetectingTransition (bool val)
Identifying transitions
Transitions used for differentiation between different analyte isomers (peptidoforms).
Identifying transitions represent the set of transitions of an assay that should be used for the independent identification of a candidate peak group (often in relation to another analyte isomer or peptidoform). These transitions could for example be site-determining transitions in a phospho-proteomic DIA experiment. These transitions will be scored independently of the detecting transitions.
bool isIdentifyingTransition () const
void setIdentifyingTransition (bool val)
Quantifying transitions
Transitions used for quantification
Quantifying transitions represent the set of transitions of an assay that should be used for the quantification of the peptide. This includes exclusion of e.g. interfered transitions (example: light/heavy peptide pairs isolated in the same swath window), that should not be used for quantification of the peptide.
bool isQuantifyingTransition () const
void setQuantifyingTransition (bool val)
Predicates
bool operator== (const ReactionMonitoringTransition &rhs) const
equality operator
bool operator!= (const ReactionMonitoringTransition &rhs) const
inequality operator
Public Member Functions inherited from CVTermList
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Protected Member Functions
Comparator classes.
These classes implement binary predicates that can be used to compare two transitions with respect to their product ions.
void updateMembers_ ()
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes
Attributes
String name_
id, required attribute
String peptide_ref_
Reference to a specific peptide.
String compound_ref_
Reference to a specific compound.
double library_intensity_
Intensity of the product (q3) ion (stored in CV Term 1001226 inside the <Transition> tag)
DecoyTransitionType decoy_type_
specific properties of a transition (e.g. specific CV terms)
Subelements
double precursor_mz_
A transition has exactly one precursor and it must supply the CV Term 1000827 (isolation window target m/z)
CVTermList * precursor_cv_terms_
(Other) CV Terms of the Precursor (Q1) of the transition or target
Product product_
Product (Q3) of the transition.
std::vector< Product > intermediate_products_
Intermediate product ion information of the transition when using MS3 or above (optional)
RetentionTime rts
Information about predicted or calibrated retention time (optional)
Prediction * prediction_
Information about a prediction for a suitable transition using some software (optional)
std::bitset< 3 > transition_flags_
Protected Attributes inherited from CVTermList
Map< String, std::vector< CVTerm > > cv_terms_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Detailed Description
This class stores a SRM/MRM transition.
This class is capable of representing a <Transition> tag in a TraML document completely and contains all associated information.
The default values for precursor m/z is 0.0 which indicates that it is uninitialized.
Member Typedef Documentation
Configuration
typedef TargetedExperimentHelper::Configuration Configuration
Prediction
typedef TargetedExperimentHelper::Prediction Prediction
Product
typedef TargetedExperimentHelper::TraMLProduct Product
RetentionTime
typedef TargetedExperimentHelper::RetentionTime RetentionTime
Member Enumeration Documentation
DecoyTransitionType
enum DecoyTransitionType
Enumerator
UNKNOWN
Unknown type.
TARGET
Target transition.
DECOY
Decoy transition.
Constructor & Destructor Documentation
ReactionMonitoringTransition() [1/3]
ReactionMonitoringTransition ()
default constructor
ReactionMonitoringTransition() [2/3]
ReactionMonitoringTransition (const ReactionMonitoringTransition & rhs)
copy constructor
ReactionMonitoringTransition() [3/3]
ReactionMonitoringTransition (ReactionMonitoringTransition &&) noexcept
Move constructor.
~ReactionMonitoringTransition()
~ReactionMonitoringTransition () override
destructor
Member Function Documentation
addIntermediateProduct()
void addIntermediateProduct (Product product)
addPrecursorCVTerm()
void addPrecursorCVTerm (const CVTerm & cv_term)
addPredictionTerm()
void addPredictionTerm (const CVTerm & prediction)
addProductCVTerm()
void addProductCVTerm (const CVTerm & cv_term)
getCompoundRef()
const String& getCompoundRef () const
Referenced by ChromatogramExtractor::prepareSpectra_().
getDecoyTransitionType()
DecoyTransitionType getDecoyTransitionType () const
Returns the type of transition (target or decoy)
getIntermediateProducts()
const std::vector<Product>& getIntermediateProducts () const
getLibraryIntensity()
double getLibraryIntensity () const
Returns the library intensity (ion count or normalized ion count from a spectral library)
getName()
const String& getName () const
getNativeID()
const String& getNativeID () const
Referenced by ChromatogramExtractor::prepareSpectra_().
getPeptideRef()
const String& getPeptideRef () const
Referenced by ChromatogramExtractor::prepareSpectra_().
getPrecursorCVTermList()
const CVTermList& getPrecursorCVTermList () const
Obtain the list of CV Terms for the precursor.
Note
You first need to check whether they exist using hasPrecursorCVTerms()
getPrecursorMZ()
double getPrecursorMZ () const
get the precursor mz (Q1 value)
Referenced by ChromatogramExtractor::prepareSpectra_().
getPrediction()
const Prediction& getPrediction () const
Obtain the Prediction object.
Note
You first need to check whether the object is accessible using hasPrediction()
getProduct()
const Product& getProduct () const
getProductChargeState()
int getProductChargeState () const
getProductMZ()
double getProductMZ () const
Referenced by ReactionMonitoringTransition::ProductMZLess::operator()(), and ChromatogramExtractor::prepareSpectra_().
getRetentionTime()
const RetentionTime& getRetentionTime () const
Gets the retention time on transition level.
Stores a retention time on the level of an individual transition
Note
This is very likely not what you want, to set the retention time of an analyte use TargetedExperimentHelper::PeptideCompound::getRetentionTime()
hasPrecursorCVTerms()
bool hasPrecursorCVTerms () const
Returns true if precursor CV Terms exist (means it is safe to call getPrecursorCVTermList)
hasPrediction()
bool hasPrediction () const
Returns true if a Prediction object exists (means it is safe to call getPrediction)
isDetectingTransition()
bool isDetectingTransition () const
isIdentifyingTransition()
bool isIdentifyingTransition () const
isProductChargeStateSet()
bool isProductChargeStateSet () const
isQuantifyingTransition()
bool isQuantifyingTransition () const
operator!=()
bool operator!= (const ReactionMonitoringTransition & rhs) const
inequality operator
operator=() [1/2]
ReactionMonitoringTransition& operator= (const ReactionMonitoringTransition & rhs)
assignment operator
operator=() [2/2]
ReactionMonitoringTransition& operator= (ReactionMonitoringTransition && rhs)
move assignment operator
operator==()
bool operator== (const ReactionMonitoringTransition & rhs) const
equality operator
setCompoundRef()
void setCompoundRef (const String & compound_ref)
setDecoyTransitionType()
void setDecoyTransitionType (const DecoyTransitionType & d)
Sets the type of transition (target or decoy)
setDetectingTransition()
void setDetectingTransition (bool val)
setIdentifyingTransition()
void setIdentifyingTransition (bool val)
setIntermediateProducts()
void setIntermediateProducts (const std::vector< Product > & products)
setLibraryIntensity()
void setLibraryIntensity (double intensity)
Sets the library intensity (ion count or normalized ion count from a spectral library)
setName()
void setName (const String & name)
setNativeID()
void setNativeID (const String & name)
setPeptideRef()
void setPeptideRef (const String & peptide_ref)
setPrecursorCVTermList()
void setPrecursorCVTermList (const CVTermList & list)
setPrecursorMZ()
void setPrecursorMZ (double mz)
sets the precursor mz (Q1 value)
setPrediction()
void setPrediction (const Prediction & prediction)
setProduct()
void setProduct (Product product)
setProductMZ()
void setProductMZ (double mz)
setQuantifyingTransition()
void setQuantifyingTransition (bool val)
setRetentionTime()
void setRetentionTime (RetentionTime rt)
Sets the retention time on transition level.
Stores a retention time on the level of an individual transition
Note
This is very likely not what you want, to set the retention time of an analyte use TargetedExperimentHelper::PeptideCompound::getRetentionTime()
updateMembers_()
void updateMembers_ () protected
Member Data Documentation
compound_ref_
String compound_ref_ protected
Reference to a specific compound.
decoy_type_
DecoyTransitionType decoy_type_ protected
specific properties of a transition (e.g. specific CV terms)
intermediate_products_
std::vector<Product> intermediate_products_ protected
Intermediate product ion information of the transition when using MS3 or above (optional)
library_intensity_
double library_intensity_ protected
Intensity of the product (q3) ion (stored in CV Term 1001226 inside the <Transition> tag)
name_
String name_ protected
id, required attribute
peptide_ref_
String peptide_ref_ protected
Reference to a specific peptide.
precursor_cv_terms_
CVTermList* precursor_cv_terms_ protected
(Other) CV Terms of the Precursor (Q1) of the transition or target
precursor_mz_
double precursor_mz_ protected
A transition has exactly one precursor and it must supply the CV Term 1000827 (isolation window target m/z)
prediction_
Prediction* prediction_ protected
Information about a prediction for a suitable transition using some software (optional)
product_
Product product_ protected
Product (Q3) of the transition.
rts
RetentionTime rts protected
Information about predicted or calibrated retention time (optional)
transition_flags_
std::bitset<3> transition_flags_ protected
A set of flags to store information about the transition at hand (currently: detecting, identifying and quantifying)