OpenMS: TransitionGroupOpenMS< SpectrumT, TransitionT > Class Template Reference
TransitionGroupOpenMS< SpectrumT, TransitionT > Class Template Reference
An implementation of the OpenSWATH Transition Group Access interface using OpenMS.
#include <OpenMS/ANALYSIS/OPENSWATH/DATAACCESS/MRMFeatureAccessOpenMS.h>
Public Member Functions
TransitionGroupOpenMS (MRMTransitionGroup< SpectrumT, TransitionT > &trgroup)
~TransitionGroupOpenMS () override
std::size_t size () const override
std::vector< std::string > getNativeIDs () const override
void getLibraryIntensities (std::vector< double > &intensities) const override
Public Member Functions inherited from ITransitionGroup
virtual ~ITransitionGroup ()
Private Attributes
const MRMTransitionGroup< SpectrumT, TransitionT > & trgroup_
Detailed Description
template<typename SpectrumT, typename TransitionT>
class OpenMS::TransitionGroupOpenMS< SpectrumT, TransitionT >
An implementation of the OpenSWATH Transition Group Access interface using OpenMS.
Constructor & Destructor Documentation
TransitionGroupOpenMS()
TransitionGroupOpenMS (MRMTransitionGroup< SpectrumT, TransitionT > & trgroup) inline
~TransitionGroupOpenMS()
~TransitionGroupOpenMS () inline override
Member Function Documentation
getLibraryIntensities()
void getLibraryIntensities (std::vector< double > & intensities) const inline override virtual
Implements ITransitionGroup.
References MRMTransitionGroup< ChromatogramType, TransitionType >::getLibraryIntensity(), and TransitionGroupOpenMS< SpectrumT, TransitionT >::trgroup_.
getNativeIDs()
std::vector<std::string> getNativeIDs () const inline override virtual
Implements ITransitionGroup.
References MRMTransitionGroup< ChromatogramType, TransitionType >::getChromatograms(), TransitionGroupOpenMS< SpectrumT, TransitionT >::size(), and TransitionGroupOpenMS< SpectrumT, TransitionT >::trgroup_.
size()
std::size_t size () const inline override virtual
Implements ITransitionGroup.
References MRMTransitionGroup< ChromatogramType, TransitionType >::size(), and TransitionGroupOpenMS< SpectrumT, TransitionT >::trgroup_.
Referenced by TransitionGroupOpenMS< SpectrumT, TransitionT >::getNativeIDs().
Member Data Documentation
trgroup_
const MRMTransitionGroup<SpectrumT, TransitionT>& trgroup_ private
Referenced by TransitionGroupOpenMS< SpectrumT, TransitionT >::getLibraryIntensities(), TransitionGroupOpenMS< SpectrumT, TransitionT >::getNativeIDs(), and TransitionGroupOpenMS< SpectrumT, TransitionT >::size().