OpenMS: SignalToNoiseOpenMS< ContainerT > Class Template Reference
SignalToNoiseOpenMS< ContainerT > Class Template Reference
An implementation of the OpenSWATH SignalToNoise Access interface using OpenMS.
#include <OpenMS/ANALYSIS/OPENSWATH/DATAACCESS/MRMFeatureAccessOpenMS.h>
Public Member Functions
SignalToNoiseOpenMS (ContainerT &chromat, double sn_win_len_, unsigned int sn_bin_count_, bool write_log_messages)
double getValueAtRT (double RT) override
Public Member Functions inherited from ISignalToNoise
virtual ~ISignalToNoise ()
Private Attributes
const ContainerT & chromatogram_
OpenMS::SignalToNoiseEstimatorMedian< ContainerT > sn_
Detailed Description
template<typename ContainerT>
class OpenMS::SignalToNoiseOpenMS< ContainerT >
An implementation of the OpenSWATH SignalToNoise Access interface using OpenMS.
Constructor & Destructor Documentation
SignalToNoiseOpenMS()
SignalToNoiseOpenMS (ContainerT & chromat, double sn_win_len_, unsigned int sn_bin_count_, bool write_log_messages) inline
References SignalToNoiseOpenMS< ContainerT >::chromatogram_, DefaultParamHandler::getParameters(), SignalToNoiseEstimator< Container >::init(), DefaultParamHandler::setParameters(), Param::setValue(), and SignalToNoiseOpenMS< ContainerT >::sn_.
Member Function Documentation
getValueAtRT()
double getValueAtRT (double RT) inline override virtual
Implements ISignalToNoise.
References SignalToNoiseOpenMS< ContainerT >::chromatogram_, SignalToNoiseEstimator< Container >::getSignalToNoise(), and SignalToNoiseOpenMS< ContainerT >::sn_.
Member Data Documentation
chromatogram_
const ContainerT& chromatogram_ private
Referenced by SignalToNoiseOpenMS< ContainerT >::getValueAtRT(), and SignalToNoiseOpenMS< ContainerT >::SignalToNoiseOpenMS().
sn_
OpenMS::SignalToNoiseEstimatorMedian< ContainerT > sn_ private
Referenced by SignalToNoiseOpenMS< ContainerT >::getValueAtRT(), and SignalToNoiseOpenMS< ContainerT >::SignalToNoiseOpenMS().