OpenMS: OpenSwathHelper Class Reference
OpenSwathHelper Class Reference
A helper class that is used by several OpenSWATH tools.
#include <OpenMS/ANALYSIS/OPENSWATH/OpenSwathHelper.h>
Static Public Member Functions
static String computePrecursorId (const String &transition_group_id, int isotope)
Compute unique precursor identifier.
static String computeTransitionGroupId (const String &precursor_id)
Compute transition group id.
static void selectSwathTransitions (const OpenMS::TargetedExperiment &targeted_exp, OpenMS::TargetedExperiment &selected_transitions, double min_upper_edge_dist, double lower, double upper)
Select transitions between lower and upper and write them into the new TargetedExperiment.
static void selectSwathTransitions (const OpenSwath::LightTargetedExperiment &targeted_exp, OpenSwath::LightTargetedExperiment &selected_transitions, double min_upper_edge_dist, double lower, double upper)
Select transitions between lower and upper and write them into the new TargetedExperiment.
static void checkSwathMap (const OpenMS::PeakMap &swath_map, double &lower, double &upper, double &center)
Get the lower / upper offset for this SWATH map and do some sanity checks.
template<class TargetedExperimentT >
static bool checkSwathMapAndSelectTransitions (const OpenMS::PeakMap &exp, const TargetedExperimentT &targeted_exp, TargetedExperimentT &selected_transitions, double min_upper_edge_dist)
Check the map and select transition in one function.
static std::pair< double, double > estimateRTRange (const OpenSwath::LightTargetedExperiment &exp)
Computes the min and max retention time value.
static std::map< std::string, double > simpleFindBestFeature (const OpenMS::MRMFeatureFinderScoring::TransitionGroupMapType &transition_group_map, bool useQualCutoff=false, double qualCutoff=0.0)
Returns the feature with the highest score for each transition group.
Detailed Description
A helper class that is used by several OpenSWATH tools.
Member Function Documentation
checkSwathMap()
static void checkSwathMap (const OpenMS::PeakMap & swath_map, double & lower, double & upper, double & center) static
Get the lower / upper offset for this SWATH map and do some sanity checks.
Sanity check for the whole map:
all scans need to have exactly one precursor
all scans need to have the same MS levels (otherwise extracting an XIC from them makes no sense)
all scans need to have the same precursor isolation window (otherwise extracting an XIC from them makes no sense)
Parameters
[in] swath_map Input SWATH map to check
[in] lower Lower edge of SWATH window (in Th)
[in] upper Upper edge of SWATH window (in Th)
Exceptions
throws IllegalArgument exception if the sanity checks fail.
Referenced by OpenSwathHelper::checkSwathMapAndSelectTransitions().
checkSwathMapAndSelectTransitions()
static bool checkSwathMapAndSelectTransitions (const OpenMS::PeakMap & exp, const TargetedExperimentT & targeted_exp, TargetedExperimentT & selected_transitions, double min_upper_edge_dist) inline static
Check the map and select transition in one function.
Computes lower and upper offset for the SWATH map and performs some sanity checks (see checkSwathMap()). Then selects transitions.
Parameters
[in] exp Input SWATH map to check
[in] targeted_exp Transition list for selection
[out] selected_transitions Selected transitions for SWATH window
[in] min_upper_edge_dist Distance in Th to the upper edge
References OpenSwathHelper::checkSwathMap(), DocumentIdentifier::getLoadedFilePath(), OpenSwathHelper::selectSwathTransitions(), and MSExperiment::size().
computePrecursorId()
static String computePrecursorId (const String & transition_group_id, int isotope) inline static
Compute unique precursor identifier.
Uses transition_group_id and isotope number to compute a unique precursor id of the form "groupID_Precursor_ix" where x is the isotope number, e.g. the monoisotopic precursor would become "groupID_Precursor_i0".
Parameters
[in] transition_group_id Unique id of the transition group (peptide/compound)
[in] isotope Precursor isotope number
Returns
Unique precursor identifier
computeTransitionGroupId()
static String computeTransitionGroupId (const String & precursor_id) inline static
Compute transition group id.
Uses the unique precursor identifier to compute the transition group id (peptide/compound identifier), reversing the operation performed by computePrecursorId().
Parameters
[in] precursor_id Precursor identifier as computed by computePrecursorId()
Returns
Original transition group id
References OpenMS::Constants::k, String::prefix(), and String::split().
Referenced by ChromatogramExtractor::return_chromatogram().
estimateRTRange()
static std::pair<double,double> estimateRTRange (const OpenSwath::LightTargetedExperiment & exp) static
Computes the min and max retention time value.
Estimate the retention time span of a targeted experiment by returning the min/max values in retention time as a pair.
Returns
A std::pair that contains (min,max)
selectSwathTransitions() [1/2]
static void selectSwathTransitions (const OpenMS::TargetedExperiment & targeted_exp, OpenMS::TargetedExperiment & selected_transitions, double min_upper_edge_dist, double lower, double upper) static
Select transitions between lower and upper and write them into the new TargetedExperiment.
Version for the OpenMS TargetedExperiment
Parameters
[in] targeted_exp Transition list for selection
[out] selected_transitions Selected transitions for SWATH window
[in] min_upper_edge_dist Distance in Th to the upper edge
[in] lower Lower edge of SWATH window (in Th)
[in] upper Upper edge of SWATH window (in Th)
Referenced by OpenSwathHelper::checkSwathMapAndSelectTransitions().
selectSwathTransitions() [2/2]
static void selectSwathTransitions (const OpenSwath::LightTargetedExperiment & targeted_exp, OpenSwath::LightTargetedExperiment & selected_transitions, double min_upper_edge_dist, double lower, double upper) static
Select transitions between lower and upper and write them into the new TargetedExperiment.
Version for the LightTargetedExperiment
Parameters
[in] targeted_exp Transition list for selection
[out] selected_transitions Selected transitions for SWATH window
[in] min_upper_edge_dist Distance in Th to the upper edge
[in] lower Lower edge of SWATH window (in Th)
[in] upper Upper edge of SWATH window (in Th)
simpleFindBestFeature()
static std::map<std::string, double> simpleFindBestFeature (const OpenMS::MRMFeatureFinderScoring::TransitionGroupMapType & transition_group_map, bool useQualCutoff = false, double qualCutoff = 0.0) static
Returns the feature with the highest score for each transition group.
Simple method to extract the best feature for each transition group (e.g. for RT alignment). A quality cutoff can be used to skip some low-quality features altogether.
Parameters
[in] transition_group_map Input data containing the picked and scored map
useQualCutoff Whether to apply a quality cutoff to the data
qualCutoff What quality cutoff should be applied (all data above the cutoff will be kept)
Returns
Result of the best scoring peaks (stored as map of peptide id and RT)