OpenMS: MRMFeatureSelector_test Class Reference
MRMFeatureSelector_test Class Reference
#include <OpenMS/ANALYSIS/OPENSWATH/MRMFeatureSelector.h>
Public Member Functions
MRMFeatureSelector_test ()=default
~MRMFeatureSelector_test ()=default
void constructTargTransList_ (const FeatureMap &features, std::vector< std::pair< double, String >> &time_to_name, std::map< String, std::vector< Feature >> &feature_name_map, const bool select_transition_group) const
double weightScore_ (const double score, const LambdaScore lambda_score) const
double computeScore_ (const Feature &feature, const std::map< String, LambdaScore > &score_weights) const
String removeSpaces_ (String str) const
Public Member Functions inherited from MRMFeatureSelectorQMIP
void optimize (const std::vector< std::pair< double, String >> &time_to_name, const std::map< String, std::vector< Feature >> &feature_name_map, std::vector< String > &result, const SelectorParameters &parameters) const override
Public Member Functions inherited from MRMFeatureSelector
MRMFeatureSelector ()=default
virtual ~MRMFeatureSelector ()=default
void selectMRMFeature (const FeatureMap &features, FeatureMap &selected_filtered, const SelectorParameters &parameters) const
Public Attributes
MRMFeatureSelectorQMIP selector_
Additional Inherited Members
Public Types inherited from MRMFeatureSelector
enum VariableType { INTEGER = 1, CONTINUOUS }
enum LambdaScore {
LINEAR = 1, INVERSE, LOG, INVERSE_LOG,
INVERSE_LOG10
}
Protected Member Functions inherited from MRMFeatureSelector
Int addVariable_ (LPWrapper &problem, const String &name, const bool bounded, const double obj, const VariableType variableType) const
double computeScore_ (const Feature &feature, const std::map< String, LambdaScore > &score_weights) const
void addConstraint_ (LPWrapper &problem, std::vector< Int > indices, std::vector< double > values, const String &name, const double lb, const double ub, const LPWrapper::Type param) const
Constructor & Destructor Documentation
MRMFeatureSelector_test()
MRMFeatureSelector_test () default
~MRMFeatureSelector_test()
~MRMFeatureSelector_test () default
Member Function Documentation
computeScore_()
double computeScore_ (const Feature & feature, const std::map< String, LambdaScore > & score_weights) const inline
References MRMFeatureSelector::computeScore_(), and MRMFeatureSelector_test::selector_.
constructTargTransList_()
void constructTargTransList_ (const FeatureMap & features, std::vector< std::pair< double, String >> & time_to_name, std::map< String, std::vector< Feature >> & feature_name_map, const bool select_transition_group) const inline
References MRMFeatureSelector::constructTargTransList_(), and MRMFeatureSelector_test::selector_.
removeSpaces_()
String removeSpaces_ (String str) const inline
References MRMFeatureSelector::removeSpaces_(), and MRMFeatureSelector_test::selector_.
weightScore_()
double weightScore_ (const double score, const LambdaScore lambda_score) const inline
References MRMFeatureSelector_test::selector_, and MRMFeatureSelector::weightScore_().
Member Data Documentation
selector_
MRMFeatureSelectorQMIP selector_
Referenced by MRMFeatureSelector_test::computeScore_(), MRMFeatureSelector_test::constructTargTransList_(), MRMFeatureSelector_test::removeSpaces_(), and MRMFeatureSelector_test::weightScore_().