OpenMS: TargetedExperiment Class Reference
TargetedExperiment Class Reference
A description of a targeted experiment containing precursor and production ions.
#include <OpenMS/ANALYSIS/TARGETED/TargetedExperiment.h>
Public Types
typedef TargetedExperimentHelper::CV CV
typedef TargetedExperimentHelper::Protein Protein
typedef TargetedExperimentHelper::RetentionTime RetentionTime
typedef TargetedExperimentHelper::Compound Compound
typedef TargetedExperimentHelper::Peptide Peptide
typedef TargetedExperimentHelper::Contact Contact
typedef TargetedExperimentHelper::Publication Publication
typedef TargetedExperimentHelper::Instrument Instrument
typedef TargetedExperimentHelper::Prediction Prediction
typedef TargetedExperimentHelper::Interpretation Interpretation
typedef ReactionMonitoringTransition Transition
typedef Residue IonType
typedef std::map< String, const Protein * > ProteinReferenceMapType
typedef std::map< String, const Peptide * > PeptideReferenceMapType
typedef std::map< String, const Compound * > CompoundReferenceMapType
Public Member Functions
Constructors and destructors
TargetedExperiment ()
default constructor
TargetedExperiment (const TargetedExperiment &rhs)
copy constructor
virtual ~TargetedExperiment ()
destructor
TargetedExperiment & operator= (const TargetedExperiment &rhs)
assignment operator
Predicates
bool operator== (const TargetedExperiment &rhs) const
bool operator!= (const TargetedExperiment &rhs) const
TargetedExperiment operator+ (const TargetedExperiment &rhs) const
Joins two targeted experiments.
TargetedExperiment & operator+= (const TargetedExperiment &rhs)
Add one targeted experiment to another.
void clear (bool clear_meta_data)
Clears all data and meta data.
Accessors
void setCVs (const std::vector< CV > &cvs)
const std::vector< CV > & getCVs () const
void addCV (const CV &cv)
void setContacts (const std::vector< Contact > &contacts)
const std::vector< Contact > & getContacts () const
void addContact (const Contact &contact)
void setPublications (const std::vector< Publication > &publications)
const std::vector< Publication > & getPublications () const
void addPublication (const Publication &publication)
void setTargetCVTerms (const CVTermList &cv_terms)
const CVTermList & getTargetCVTerms () const
void addTargetCVTerm (const CVTerm &cv_term)
void setTargetMetaValue (const String &name, const DataValue &value)
void setInstruments (const std::vector< Instrument > &instruments)
const std::vector< Instrument > & getInstruments () const
void addInstrument (const Instrument &instrument)
void setSoftware (const std::vector< Software > &software)
const std::vector< Software > & getSoftware () const
void addSoftware (const Software &software)
void setProteins (const std::vector< Protein > &proteins)
const std::vector< Protein > & getProteins () const
const Protein & getProteinByRef (const String &ref) const
bool hasProtein (const String &ref) const
void addProtein (const Protein &protein)
void setCompounds (const std::vector< Compound > &rhs)
const std::vector< Compound > & getCompounds () const
void addCompound (const Compound &rhs)
void setPeptides (const std::vector< Peptide > &rhs)
const std::vector< Peptide > & getPeptides () const
bool hasPeptide (const String &ref) const
const Peptide & getPeptideByRef (const String &ref) const
bool hasCompound (const String &ref) const
const Compound & getCompoundByRef (const String &ref) const
void addPeptide (const Peptide &rhs)
void setTransitions (const std::vector< ReactionMonitoringTransition > &transitions)
set transition list
const std::vector< ReactionMonitoringTransition > & getTransitions () const
returns the transition list
void addTransition (const ReactionMonitoringTransition &transition)
adds a transition to the list
void setIncludeTargets (const std::vector< IncludeExcludeTarget > &targets)
const std::vector< IncludeExcludeTarget > & getIncludeTargets () const
void addIncludeTarget (const IncludeExcludeTarget &target)
void setExcludeTargets (const std::vector< IncludeExcludeTarget > &targets)
const std::vector< IncludeExcludeTarget > & getExcludeTargets () const
void addExcludeTarget (const IncludeExcludeTarget &target)
void setSourceFiles (const std::vector< SourceFile > &source_files)
sets the source files
const std::vector< SourceFile > & getSourceFiles () const
returns the source file list
void addSourceFile (const SourceFile &source_file)
adds a source file to the list
Sorting peaks
std::vector< CV > cvs_
std::vector< Contact > contacts_
std::vector< Publication > publications_
std::vector< Instrument > instruments_
CVTermList targets_
std::vector< Software > software_
std::vector< Protein > proteins_
std::vector< Compound > compounds_
std::vector< Peptide > peptides_
std::vector< ReactionMonitoringTransition > transitions_
std::vector< IncludeExcludeTarget > include_targets_
std::vector< IncludeExcludeTarget > exclude_targets_
std::vector< SourceFile > source_files_
ProteinReferenceMapType protein_reference_map_
bool protein_reference_map_dirty_
PeptideReferenceMapType peptide_reference_map_
bool peptide_reference_map_dirty_
CompoundReferenceMapType compound_reference_map_
bool compound_reference_map_dirty_
void sortTransitionsByProductMZ ()
Lexicographically sorts the transitions by their product m/z.
bool containsInvalidReferences () const
Checks whether the data structure (and the underlying TraML file) contains invalid references.
void createProteinReferenceMap_ () const
void createPeptideReferenceMap_ () const
void createCompoundReferenceMap_ () const
Detailed Description
A description of a targeted experiment containing precursor and production ions.
A targeted experiment contains transitions used in SRM/MRM as well as SWATH-MS/DIA analysis using a targeted approach. This container holds descriptions of the precursors and product ions analyzed in such a targeted experiment. Generally, the precursor ions can be peptides or small molecules (for metabolomics) and each precursor has a set of product ions associated with it.
The TargetedExperiment can be stored to disk either in .traml format using the TraMLFile or in .tsv format using the TransitionTSVFile.
Member Typedef Documentation
Compound
typedef TargetedExperimentHelper::Compound Compound
CompoundReferenceMapType
typedef std::map<String, const Compound *> CompoundReferenceMapType
Contact
typedef TargetedExperimentHelper::Contact Contact
CV
typedef TargetedExperimentHelper::CV CV
Instrument
typedef TargetedExperimentHelper::Instrument Instrument
Interpretation
typedef TargetedExperimentHelper::Interpretation Interpretation
IonType
typedef Residue IonType
Peptide
typedef TargetedExperimentHelper::Peptide Peptide
PeptideReferenceMapType
typedef std::map<String, const Peptide *> PeptideReferenceMapType
Prediction
typedef TargetedExperimentHelper::Prediction Prediction
Protein
typedef TargetedExperimentHelper::Protein Protein
ProteinReferenceMapType
typedef std::map<String, const Protein *> ProteinReferenceMapType
Publication
typedef TargetedExperimentHelper::Publication Publication
RetentionTime
typedef TargetedExperimentHelper::RetentionTime RetentionTime
Transition
typedef ReactionMonitoringTransition Transition
Constructor & Destructor Documentation
TargetedExperiment() [1/2]
TargetedExperiment ()
default constructor
TargetedExperiment() [2/2]
TargetedExperiment (const TargetedExperiment & rhs)
copy constructor
~TargetedExperiment()
virtual ~TargetedExperiment () virtual
destructor
Member Function Documentation
addCompound()
void addCompound (const Compound & rhs)
addContact()
void addContact (const Contact & contact)
addCV()
void addCV (const CV & cv)
addExcludeTarget()
void addExcludeTarget (const IncludeExcludeTarget & target)
addIncludeTarget()
void addIncludeTarget (const IncludeExcludeTarget & target)
addInstrument()
void addInstrument (const Instrument & instrument)
addPeptide()
void addPeptide (const Peptide & rhs)
addProtein()
void addProtein (const Protein & protein)
addPublication()
void addPublication (const Publication & publication)
addSoftware()
void addSoftware (const Software & software)
addSourceFile()
void addSourceFile (const SourceFile & source_file)
adds a source file to the list
addTargetCVTerm()
void addTargetCVTerm (const CVTerm & cv_term)
addTransition()
void addTransition (const ReactionMonitoringTransition & transition)
adds a transition to the list
clear()
void clear (bool clear_meta_data)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
containsInvalidReferences()
bool containsInvalidReferences () const
Checks whether the data structure (and the underlying TraML file) contains invalid references.
First checks whether all of the references are unique (protein, peptide, compound). Secondly, checks that each reference is valid and points either to a protein, peptide or compound.
Returns false if the file is valid.
createCompoundReferenceMap_()
void createCompoundReferenceMap_ () const protected
createPeptideReferenceMap_()
void createPeptideReferenceMap_ () const protected
createProteinReferenceMap_()
void createProteinReferenceMap_ () const protected
getCompoundByRef()
const Compound& getCompoundByRef (const String & ref) const
Referenced by OpenMS::ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment >().
getCompounds()
const std::vector<Compound>& getCompounds () const
Referenced by ChromatogramExtractor::prepareSpectra_().
getContacts()
const std::vector<Contact>& getContacts () const
getCVs()
const std::vector<CV>& getCVs () const
getExcludeTargets()
const std::vector<IncludeExcludeTarget>& getExcludeTargets () const
getIncludeTargets()
const std::vector<IncludeExcludeTarget>& getIncludeTargets () const
getInstruments()
const std::vector<Instrument>& getInstruments () const
getPeptideByRef()
const Peptide& getPeptideByRef (const String & ref) const
Referenced by OpenMS::ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment >().
getPeptides()
const std::vector<Peptide>& getPeptides () const
Referenced by ChromatogramExtractor::prepareSpectra_(), and ConfidenceScoring::scoreMap().
getProteinByRef()
const Protein& getProteinByRef (const String & ref) const
getProteins()
const std::vector<Protein>& getProteins () const
getPublications()
const std::vector<Publication>& getPublications () const
getSoftware()
const std::vector<Software>& getSoftware () const
getSourceFiles()
const std::vector<SourceFile>& getSourceFiles () const
returns the source file list
getTargetCVTerms()
const CVTermList& getTargetCVTerms () const
getTransitions()
const std::vector<ReactionMonitoringTransition>& getTransitions () const
returns the transition list
Referenced by ChromatogramExtractor::extractChromatograms(), ChromatogramExtractor::prepareSpectra_(), and ConfidenceScoring::scoreMap().
hasCompound()
bool hasCompound (const String & ref) const
Referenced by OpenMS::ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment >().
hasPeptide()
bool hasPeptide (const String & ref) const
Referenced by OpenMS::ChromatogramExtractor::extract_id_< OpenMS::TargetedExperiment >().
hasProtein()
bool hasProtein (const String & ref) const
operator!=()
bool operator!= (const TargetedExperiment & rhs) const
operator+()
TargetedExperiment operator+ (const TargetedExperiment & rhs) const
Joins two targeted experiments.
Proteins, peptides and transitions are merged (see operator+= for details).
operator+=()
TargetedExperiment& operator+= (const TargetedExperiment & rhs)
Add one targeted experiment to another.
Parameters
rhs The targeted experiment to add to this one.
operator=()
TargetedExperiment& operator= (const TargetedExperiment & rhs)
assignment operator
operator==()
bool operator== (const TargetedExperiment & rhs) const
setCompounds()
void setCompounds (const std::vector< Compound > & rhs)
setContacts()
void setContacts (const std::vector< Contact > & contacts)
setCVs()
void setCVs (const std::vector< CV > & cvs)
setExcludeTargets()
void setExcludeTargets (const std::vector< IncludeExcludeTarget > & targets)
setIncludeTargets()
void setIncludeTargets (const std::vector< IncludeExcludeTarget > & targets)
setInstruments()
void setInstruments (const std::vector< Instrument > & instruments)
setPeptides()
void setPeptides (const std::vector< Peptide > & rhs)
setProteins()
void setProteins (const std::vector< Protein > & proteins)
setPublications()
void setPublications (const std::vector< Publication > & publications)
setSoftware()
void setSoftware (const std::vector< Software > & software)
setSourceFiles()
void setSourceFiles (const std::vector< SourceFile > & source_files)
sets the source files
setTargetCVTerms()
void setTargetCVTerms (const CVTermList & cv_terms)
setTargetMetaValue()
void setTargetMetaValue (const String & name, const DataValue & value)
setTransitions()
void setTransitions (const std::vector< ReactionMonitoringTransition > & transitions)
set transition list
sortTransitionsByProductMZ()
void sortTransitionsByProductMZ ()
Lexicographically sorts the transitions by their product m/z.
Referenced by ChromatogramExtractor::extractChromatograms().
Member Data Documentation
compound_reference_map_
CompoundReferenceMapType compound_reference_map_ mutable protected
compound_reference_map_dirty_
bool compound_reference_map_dirty_ mutable protected
compounds_
std::vector<Compound> compounds_ protected
contacts_
std::vector<Contact> contacts_ protected
cvs_
std::vector<CV> cvs_ protected
exclude_targets_
std::vector<IncludeExcludeTarget> exclude_targets_ protected
include_targets_
std::vector<IncludeExcludeTarget> include_targets_ protected
instruments_
std::vector<Instrument> instruments_ protected
peptide_reference_map_
PeptideReferenceMapType peptide_reference_map_ mutable protected
peptide_reference_map_dirty_
bool peptide_reference_map_dirty_ mutable protected
peptides_
std::vector<Peptide> peptides_ protected
protein_reference_map_
ProteinReferenceMapType protein_reference_map_ mutable protected
protein_reference_map_dirty_
bool protein_reference_map_dirty_ mutable protected
proteins_
std::vector<Protein> proteins_ protected
publications_
std::vector<Publication> publications_ protected
software_
std::vector<Software> software_ protected
source_files_
std::vector<SourceFile> source_files_ protected
targets_
CVTermList targets_ protected
transitions_
std::vector<ReactionMonitoringTransition> transitions_ protected