OpenMS: Element Class Reference
Element Class Reference
Chemistry
Representation of an element.
#include <OpenMS/CHEMISTRY/Element.h>
Public Member Functions
Constructor and Destructors
Element ()
default constructor
Element (const Element &element)
copy constructor
Element (const String &name, const String &symbol, UInt atomic_number, double average_weight, double mono_weight, const IsotopeDistribution &isotopes)
detailed constructor
virtual ~Element ()
destructor
Accessors
void setAtomicNumber (UInt atomic_number)
sets unique atomic number
UInt getAtomicNumber () const
returns the unique atomic number
void setAverageWeight (double weight)
sets the average weight of the element
double getAverageWeight () const
returns the average weight of the element
void setMonoWeight (double weight)
sets the mono isotopic weight of the element
double getMonoWeight () const
returns the mono isotopic weight of the element
void setIsotopeDistribution (const IsotopeDistribution &isotopes)
sets the isotope distribution of the element
const IsotopeDistribution & getIsotopeDistribution () const
returns the isotope distribution of the element
void setName (const String &name)
set the name of the element
const String & getName () const
returns the name of the element
void setSymbol (const String &symbol)
sets symbol of the element
const String & getSymbol () const
returns symbol of the element
Assignment
Element & operator= (const Element &element)
assignment operator
Predicates
String name_
name of the element
String symbol_
symbol of the element
UInt atomic_number_
atomic number of the element
double average_weight_
average weight over all isotopes
double mono_weight_
mono isotopic weight of the most frequent isotope
IsotopeDistribution isotopes_
distribution of the isotopes
bool operator== (const Element &element) const
equality operator
bool operator!= (const Element &element) const
inequality operator
bool operator< (const Element &element) const
less operator
std::ostream & operator<< (std::ostream &os, const Element &element)
writes the element to an output stream
Detailed Description
Representation of an element.
Constructor & Destructor Documentation
Element() [1/3]
Element ()
default constructor
Element() [2/3]
Element (const Element & element)
copy constructor
Element() [3/3]
Element (const String & name, const String & symbol, UInt atomic_number, double average_weight, double mono_weight, const IsotopeDistribution & isotopes)
detailed constructor
~Element()
virtual ~Element () virtual
destructor
Member Function Documentation
getAtomicNumber()
UInt getAtomicNumber () const
returns the unique atomic number
getAverageWeight()
double getAverageWeight () const
returns the average weight of the element
getIsotopeDistribution()
const IsotopeDistribution& getIsotopeDistribution () const
returns the isotope distribution of the element
getMonoWeight()
double getMonoWeight () const
returns the mono isotopic weight of the element
getName()
const String& getName () const
returns the name of the element
getSymbol()
const String& getSymbol () const
returns symbol of the element
operator!=()
bool operator!= (const Element & element) const
inequality operator
operator<()
bool operator< (const Element & element) const
less operator
operator=()
Element& operator= (const Element & element)
assignment operator
operator==()
bool operator== (const Element & element) const
equality operator
setAtomicNumber()
void setAtomicNumber (UInt atomic_number)
sets unique atomic number
setAverageWeight()
void setAverageWeight (double weight)
sets the average weight of the element
setIsotopeDistribution()
void setIsotopeDistribution (const IsotopeDistribution & isotopes)
sets the isotope distribution of the element
Referenced by MetaProSIPDecomposition::calculateIsotopePatternsFor13CRange(), MetaProSIPDecomposition::calculateIsotopePatternsFor13CRangeOfAveraginePeptide(), MetaProSIPDecomposition::calculateIsotopePatternsFor15NRange(), MetaProSIPDecomposition::calculateIsotopePatternsFor15NRangeOfAveraginePeptide(), MetaProSIPDecomposition::calculateIsotopePatternsFor18ORange(), MetaProSIPDecomposition::calculateIsotopePatternsFor18ORangeOfAveraginePeptide(), MetaProSIPDecomposition::calculateIsotopePatternsFor2HRange(), and MetaProSIPDecomposition::calculateIsotopePatternsFor2HRangeOfAveraginePeptide().
setMonoWeight()
void setMonoWeight (double weight)
sets the mono isotopic weight of the element
setName()
void setName (const String & name)
set the name of the element
setSymbol()
void setSymbol (const String & symbol)
sets symbol of the element
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Element & element) friend
writes the element to an output stream
Member Data Documentation
atomic_number_
UInt atomic_number_ protected
atomic number of the element
average_weight_
double average_weight_ protected
average weight over all isotopes
isotopes_
IsotopeDistribution isotopes_ protected
distribution of the isotopes
mono_weight_
double mono_weight_ protected
mono isotopic weight of the most frequent isotope
name_
String name_ protected
name of the element
symbol_
String symbol_ protected
symbol of the element