OpenMS: TOPPOpenSwathBase Class Reference
TOPPOpenSwathBase Class Reference
#include <OpenMS/APPLICATIONS/OpenSwathBase.h>
Public Member Functions
TOPPOpenSwathBase (String name, String description, bool official=true)
Public Member Functions inherited from TOPPBase
TOPPBase (const String &name, const String &description, bool official=true, const std::vector< Citation > &citations={})
Constructor.
virtual ~TOPPBase ()
Destructor.
ExitCodes main (int argc, const char **argv)
Main routine of all TOPP applications.
Protected Member Functions
bool loadSwathFiles (const StringList &file_list, boost::shared_ptr< ExperimentalSettings > &exp_meta, std::vector< OpenSwath::SwathMap > &swath_maps, const bool split_file, const String &tmp, const String &readoptions, const String &swath_windows_file, const double min_upper_edge_dist, const bool force, const bool sort_swath_maps, const bool sonar, const bool prm, Interfaces::IMSDataConsumer *plugin_consumer=nullptr)
Load the DIA files into internal data structures.
void prepareChromOutput (Interfaces::IMSDataConsumer **chromatogramConsumer, const boost::shared_ptr< ExperimentalSettings > &exp_meta, const OpenSwath::LightTargetedExperiment &transition_exp, const String &out_chrom)
Prepare chromatogram output.
OpenSwath::LightTargetedExperiment loadTransitionList (const FileTypes::Type &tr_type, const String &tr_file, const Param &tsv_reader_param)
Loads transition list from TraML / TSV or PQP.
TransformationDescription performCalibration (String trafo_in, String irt_tr_file, std::vector< OpenSwath::SwathMap > &swath_maps, double min_rsq, double min_coverage, const Param &feature_finder_param, const ChromExtractParams &cp_irt, const Param &irt_detection_param, const Param &calibration_param, Size debug_level, bool sonar, bool load_into_memory, const String &irt_trafo_out, const String &irt_mzml_out)
Perform retention time and m/z calibration.
Protected Member Functions inherited from TOPPBase
virtual void registerOptionsAndFlags_ ()=0
Sets the valid command line options (with argument) and flags (without argument).
String getParamArgument_ (const Param::ParamEntry &entry) const
Utility function that determines a suitable argument value for the given Param::ParamEntry.
std::vector< ParameterInformation > paramToParameterInformation_ (const Param &param) const
Translates the given parameter object into a vector of ParameterInformation, that can be utilized for cl parsing.
ParameterInformation paramEntryToParameterInformation_ (const Param::ParamEntry &entry, const String &argument="", const String &full_name="") const
Transforms a ParamEntry object to command line parameter (ParameterInformation).
void registerParamSubsectionsAsTOPPSubsections_ (const Param &param)
void registerFullParam_ (const Param &param)
Register command line parameters for all entries in a Param object.
void registerStringOption_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers a string option.
void setValidStrings_ (const String &name, const std::vector< String > &strings)
Sets the valid strings for a string option or a whole string list.
void setValidStrings_ (const String &name, const std::string vstrings[], int count)
Sets the valid strings for a string option or a whole string list.
void registerInputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers an input file option.
void registerOutputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers an output file option.
void setValidFormats_ (const String &name, const std::vector< String > &formats, const bool force_OpenMS_format=true)
Sets the formats for a input/output file option or for all members of an input/output file lists.
void registerDoubleOption_ (const String &name, const String &argument, double default_value, const String &description, bool required=true, bool advanced=false)
Registers a double option.
void setMinInt_ (const String &name, Int min)
Sets the minimum value for the integer parameter(can be a list of integers,too) name.
void setMaxInt_ (const String &name, Int max)
Sets the maximum value for the integer parameter(can be a list of integers,too) name.
void setMinFloat_ (const String &name, double min)
Sets the minimum value for the floating point parameter(can be a list of floating points,too) name.
void setMaxFloat_ (const String &name, double max)
Sets the maximum value for the floating point parameter(can be a list of floating points,too) name.
void registerIntOption_ (const String &name, const String &argument, Int default_value, const String &description, bool required=true, bool advanced=false)
Registers an integer option.
void registerIntList_ (const String &name, const String &argument, IntList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of integers option.
void registerDoubleList_ (const String &name, const String &argument, DoubleList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of doubles option.
void registerStringList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of strings option.
void registerInputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers a list of input files option.
void registerOutputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of output files option.
void registerFlag_ (const String &name, const String &description, bool advanced=false)
Registers a flag.
void registerSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file (usually from OpenMS algorithms).
void registerTOPPSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file originating from the TOPP tool itself.
void addEmptyLine_ ()
Adds an empty line between registered variables in the documentation.
String getStringOption_ (const String &name) const
Returns the value of a previously registered string option.
double getDoubleOption_ (const String &name) const
Returns the value of a previously registered double option.
Int getIntOption_ (const String &name) const
Returns the value of a previously registered integer option.
StringList getStringList_ (const String &name) const
Returns the value of a previously registered StringList.
IntList getIntList_ (const String &name) const
Returns the value of a previously registered IntList.
DoubleList getDoubleList_ (const String &name) const
Returns the value of a previously registered DoubleList.
bool getFlag_ (const String &name) const
Returns the value of a previously registered flag.
const ParameterInformation & findEntry_ (const String &name) const
Finds the entry in the parameters_ array that has the name name.
Param const & getParam_ () const
Return all parameters relevant to this TOPP tool.
void checkParam_ (const Param &param, const String &filename, const String &location) const
Checks top-level entries of param according to the information during registration.
void fileParamValidityCheck_ (String &filename, const String &param_name, const ParameterInformation &p) const
checks if an input file exists (respecting the flags)
void checkIfIniParametersAreApplicable_ (const Param &ini_params)
Checks if the parameters of the provided ini file are applicable to this tool.
void printUsage_ ()
Prints the tool-specific command line options and appends the common options.
virtual ExitCodes main_ (int argc, const char **argv)=0
The actual "main" method. main_() is invoked by main().
void writeLog_ (const String &text) const
Writes a string to the log file and to std::cout.
void writeDebug_ (const String &text, UInt min_level) const
Writes a text to the log file and to std::cout if the debug level is at least min_level.
void writeDebug_ (const String &text, const Param &param, UInt min_level) const
Writes a String followed by a Param to the log file and to std::cout if the debug level is at least min_level.
String makeTempDirectory_ () const
Creates a unique temporary directory and returns its name (you have to clean it up yourself)
String makeAutoRemoveTempDirectory_ (Int keep_debug=2)
Creates a unique temporary directory and returns its name (will be cleaned up automatically if debug level is high enough)
void removeTempDirectory_ (const String &dirname, Int keep_debug=2) const
Removes a (temporary) directory.
ExitCodes runExternalProcess_ (const QString &executable, const QStringList &arguments, const QString &workdir="") const
Runs an external process via QProcess and reports its status in the logs.
const String & getIniLocation_ () const
Returns the location of the ini file where parameters are taken from. E.g. if the command line was TOPPTool -instance 17, then this will be "TOPPTool:17:". Note the ':' at the end.
const String & toolName_ () const
Returns the tool name.
void inputFileReadable_ (const String &filename, const String &param_name) const
Checks if an input file exists, is readable and is not empty.
void outputFileWritable_ (const String &filename, const String &param_name) const
Checks if an output file is writable.
bool parseRange_ (const String &text, double &low, double &high) const
Parses a range string ([a]:[b]) into two variables (doubles)
bool parseRange_ (const String &text, Int &low, Int &high) const
Parses a range string ([a]:[b]) into two variables (integers)
void addDataProcessing_ (ConsensusMap &map, const DataProcessing &dp) const
Data processing setter for consensus maps.
void addDataProcessing_ (FeatureMap &map, const DataProcessing &dp) const
Data processing setter for feature maps.
void addDataProcessing_ (PeakMap &map, const DataProcessing &dp) const
Data processing setter for peak maps.
DataProcessing getProcessingInfo_ (DataProcessing::ProcessingAction action) const
Returns the data processing information.
DataProcessing getProcessingInfo_ (const std::set< DataProcessing::ProcessingAction > &actions) const
Returns the data processing information.
bool writeCTD_ ()
Write common tool description (CTD) file.
Private Member Functions
void loadSwathFiles_ (const StringList &file_list, const bool split_file, const String &tmp, const String &readoptions, boost::shared_ptr< ExperimentalSettings > &exp_meta, std::vector< OpenSwath::SwathMap > &swath_maps, Interfaces::IMSDataConsumer *plugin_consumer)
Additional Inherited Members
Public Types inherited from TOPPBase
enum ExitCodes {
EXECUTION_OK, INPUT_FILE_NOT_FOUND, INPUT_FILE_NOT_READABLE, INPUT_FILE_CORRUPT,
INPUT_FILE_EMPTY, CANNOT_WRITE_OUTPUT_FILE, ILLEGAL_PARAMETERS, MISSING_PARAMETERS,
UNKNOWN_ERROR, EXTERNAL_PROGRAM_ERROR, PARSE_ERROR, INCOMPATIBLE_INPUT_DATA,
INTERNAL_ERROR, UNEXPECTED_RESULT
}
Exit codes.
Static Public Member Functions inherited from TOPPBase
static void setMaxNumberOfThreads (int num_threads)
Sets the maximal number of usable threads.
Protected Attributes inherited from TOPPBase
String version_
Version string (if empty, the OpenMS/TOPP version is printed)
String verboseVersion_
Version string including additional revision/date time information. Note: This differs from version_ only if not provided by the user.
bool official_
Flag indicating if this an official TOPP tool.
std::vector< Citation > citations_
Papers, specific for this tool (will be shown in '–help')
ProgressLogger::LogType log_type_
Type of progress logging.
bool test_mode_
Test mode.
Int debug_level_
Debug level set by -debug.
Static Protected Attributes inherited from TOPPBase
static String topp_ini_file_
.TOPP.ini file for storing system default parameters
static const Citation cite_openms_
The OpenMS citation.
Constructor & Destructor Documentation
TOPPOpenSwathBase()
TOPPOpenSwathBase (String name, String description, bool official = true) inline
Member Function Documentation
loadSwathFiles()
bool loadSwathFiles (const StringList & file_list, boost::shared_ptr< ExperimentalSettings > & exp_meta, std::vector< OpenSwath::SwathMap > & swath_maps, const bool split_file, const String & tmp, const String & readoptions, const String & swath_windows_file, const double min_upper_edge_dist, const bool force, const bool sort_swath_maps, const bool sonar, const bool prm, Interfaces::IMSDataConsumer * plugin_consumer = nullptr) inline protected
Load the DIA files into internal data structures.
Loads SWATH files into the provided OpenSwath::SwathMap data structures. It uses the SwathFile class to load files from either mzML, mzXML or SqMass. The files will be either loaded into memory or cached to disk (depending on the readoptions parameter).
Parameters
file_list The input file(s)
exp_meta The output (meta data about experiment)
swath_maps The output (ptr to raw data)
file_list The input file(s)
split_file If loading a single file that contains a single SWATH window
tmp Temporary directory
readoptions Description on how to read the data ("normal", "cache")
swath_windows_file Provided file containing the SWATH windows which will be mapped to the experimental windows
min_upper_edge_dist Distance for each assay to the upper edge of the SWATH window
force Whether to override the sanity check
sort_swath_maps Whether to sort the provided windows first before mapping
sonar Whether data is in sonar format
Returns
Returns whether loading and sanity check was successful
References SwathWindowLoader::annotateSwathMapsFromFile(), TOPPOpenSwathBase::loadSwathFiles_(), OPENMS_LOG_DEBUG, OPENMS_LOG_ERROR, and OPENMS_LOG_WARN.
loadSwathFiles_()
void loadSwathFiles_ (const StringList & file_list, const bool split_file, const String & tmp, const String & readoptions, boost::shared_ptr< ExperimentalSettings > & exp_meta, std::vector< OpenSwath::SwathMap > & swath_maps, Interfaces::IMSDataConsumer * plugin_consumer) inline private
References FileHandler::getTypeByFileName(), SwathFile::loadMzML(), SwathFile::loadMzXML(), SwathFile::loadSplit(), SwathFile::loadSqMass(), TOPPBase::log_type_, FileTypes::MZML, FileTypes::MZXML, ProgressLogger::setLogType(), and FileTypes::SQMASS.
Referenced by TOPPOpenSwathBase::loadSwathFiles().
loadTransitionList()
OpenSwath::LightTargetedExperiment loadTransitionList (const FileTypes::Type & tr_type, const String & tr_file, const Param & tsv_reader_param) inline protected
Loads transition list from TraML / TSV or PQP.
Parameters
tr_type Input file type
tr_file Input file name
tsv_reader_param Parameters on how to interpret spectral data
References TransitionPQPFile::convertPQPToTargetedExperiment(), OpenSwathDataAccessHelper::convertTargetedExp(), TransitionTSVFile::convertTSVToTargetedExperiment(), ProgressLogger::endProgress(), TraMLFile::load(), TOPPBase::log_type_, OPENMS_LOG_ERROR, FileTypes::PQP, ProgressLogger::setLogType(), DefaultParamHandler::setParameters(), ProgressLogger::startProgress(), FileTypes::TRAML, and FileTypes::TSV.
Referenced by TOPPOpenSwathBase::performCalibration().
performCalibration()
TransformationDescription performCalibration (String trafo_in, String irt_tr_file, std::vector< OpenSwath::SwathMap > & swath_maps, double min_rsq, double min_coverage, const Param & feature_finder_param, const ChromExtractParams & cp_irt, const Param & irt_detection_param, const Param & calibration_param, Size debug_level, bool sonar, bool load_into_memory, const String & irt_trafo_out, const String & irt_mzml_out) inline protected
Perform retention time and m/z calibration.
This function will create the retention time transformation either by loading a provided .trafoXML file or determine it from the data itself by extracting the transitions specified in the irt_tr_file TraML file. It will also perform the m/z calibration.
Note
Internally, the retention time and m/z calibration are performed by OpenMS::OpenSwathCalibrationWorkflow::performRTNormalization
Parameters
trafo_in Input trafoXML file (if not empty, transformation will be loaded from this file)
irt_tr_file Input TraML file containing transitions (if trafo_in is empty, this file will be loaded and transitions will be extracted)
swath_maps The raw data (swath maps)
min_rsq Minimal R^2 value that is expected for the RT regression
min_coverage Minimal coverage of the chromatographic space that needs to be achieved
feature_finder_param Parameter set for the feature finding in chromatographic dimension
cp_irt Parameter set for the chromatogram extraction
irt_detection_param Parameter set for the detection of the iRTs (outlier detection, peptides per bin etc)
calibration_param Parameter for the m/z and im calibration (see SwathMapMassCorrection)
debug_level Debug level (writes out the RT normalization chromatograms if larger than 1)
sonar Whether the data is SONAR data
load_into_memory Whether to cache the current SWATH map in memory
irt_trafo_out Output trafoXML file (if not empty and no input trafoXML file is given, the transformation parameters will be stored in this file)
irt_mzml_out Output Chromatogram mzML containing the iRT peptides (if not empty, iRT chromatograms will be stored in this file)
References Param::copy(), TransformationDescription::fitModel(), DefaultParamHandler::getDefaults(), TOPPBase::getParam_(), FileHandler::getType(), Param::getValue(), TransformationXMLFile::load(), TOPPOpenSwathBase::loadTransitionList(), TOPPBase::log_type_, OpenSwathCalibrationWorkflow::performRTNormalization(), ProgressLogger::setLogType(), Param::setValue(), and TransformationXMLFile::store().
prepareChromOutput()
void prepareChromOutput (Interfaces::IMSDataConsumer ** chromatogramConsumer, const boost::shared_ptr< ExperimentalSettings > & exp_meta, const OpenSwath::LightTargetedExperiment & transition_exp, const String & out_chrom) inline protected
Prepare chromatogram output.
Sets up the chromatogram output, either sqMass or mzML (using numpress lossy compression). This assumes that 0.05 accuracy in RT is sufficient for all purposes.
Parameters
chromatogramConsumer The consumer to process chromatograms
exp_meta meta data about experiment
transition_exp The spectral library
out_chrom The output file for the chromatograms
References MSDataWritingConsumer::addDataProcessing(), MSNumpressCoder::NumpressConfig::estimate_fixed_point, MzMLHandler::getOptions(), TOPPBase::getProcessingInfo_(), String::hasSuffix(), MSNumpressCoder::NumpressConfig::linear_fp_mass_acc, MSNumpressCoder::NumpressConfig::numpressErrorTolerance, PeakFileOptions::setCompression(), MSNumpressCoder::NumpressConfig::setCompression(), MSDataWritingConsumer::setExpectedSize(), MSDataWritingConsumer::setExperimentalSettings(), PeakFileOptions::setNumpressConfigurationIntensity(), PeakFileOptions::setNumpressConfigurationMassTime(), PeakFileOptions::setWriteIndex(), DataProcessing::SMOOTHING, String::toLower(), and LightTargetedExperiment::transitions.