OpenMS: OPXLHelper::PeptideIDScoreComparator Struct Reference
OPXLHelper::PeptideIDScoreComparator Struct Reference
A comparator for PeptideIdentifications that compares the scores in the first PeptideHit.
#include <OpenMS/ANALYSIS/XLMS/OPXLHelper.h>
Public Member Functions
bool operator() (const PeptideIdentification &a, const PeptideIdentification &b) const
bool operator() (const PeptideIdentification &a, const double &b) const
bool operator() (const double &a, const PeptideIdentification &b) const
Detailed Description
A comparator for PeptideIdentifications that compares the scores in the first PeptideHit.
Member Function Documentation
operator()() [1/3]
bool operator() (const double & a, const PeptideIdentification & b) const inline
References PeptideIdentification::getHits().
operator()() [2/3]
bool operator() (const PeptideIdentification & a, const double & b) const inline
References PeptideIdentification::getHits().
operator()() [3/3]
bool operator() (const PeptideIdentification & a, const PeptideIdentification & b) const inline
References PeptideIdentification::getHits().