OpenMS: ToolHandler Class Reference
ToolHandler Class Reference
#include <OpenMS/APPLICATIONS/ToolHandler.h>
Static Public Member Functions
static ToolListType getTOPPToolList (const bool includeGenericWrapper=false)
Returns the list of official TOPP tools contained in the OpenMS/TOPP release.
static ToolListType getUtilList ()
Returns the list of official UTIL tools contained in the OpenMS/TOPP release.
static StringList getTypes (const String &toolname)
get all types of a tool (empty if none)
static String getCategory (const String &toolname)
static String getExternalToolsPath ()
get getOpenMSDataPath() + "/TOOLS/EXTERNAL"
static String getInternalToolsPath ()
get File::getOpenMSDataPath() + "/TOOLS/INTERNAL"
Static Private Member Functions
static Internal::ToolDescription getExternalTools_ ()
static QStringList getExternalToolConfigFiles_ ()
static void loadExternalToolConfig_ ()
static std::vector< Internal::ToolDescription > getInternalTools_ ()
static QStringList getInternalToolConfigFiles_ ()
static void loadInternalToolConfig_ ()
Static Private Attributes
static Internal::ToolDescription tools_external_
static bool tools_external_loaded_
static std::vector< Internal::ToolDescription > tools_internal_
static bool tools_internal_loaded_
Member Function Documentation
getCategory()
static String getCategory (const String & toolname) static
Returns the category string from TOPP or UTIL tools
Returns
empty string if tool was not found
getExternalToolConfigFiles_()
static QStringList getExternalToolConfigFiles_ () static private
getExternalTools_()
static Internal::ToolDescription getExternalTools_ () static private
getExternalToolsPath()
static String getExternalToolsPath () static
get getOpenMSDataPath() + "/TOOLS/EXTERNAL"
getInternalToolConfigFiles_()
static QStringList getInternalToolConfigFiles_ () static private
getInternalTools_()
static std::vector<Internal::ToolDescription> getInternalTools_ () static private
getInternalToolsPath()
static String getInternalToolsPath () static
get File::getOpenMSDataPath() + "/TOOLS/INTERNAL"
getTOPPToolList()
static ToolListType getTOPPToolList (const bool includeGenericWrapper = false) static
Returns the list of official TOPP tools contained in the OpenMS/TOPP release.
Referenced by TOPPASBase::createTOPPToolsTreeWidget().
getTypes()
static StringList getTypes (const String & toolname) static
get all types of a tool (empty if none)
Referenced by TOPPASBase::createTOPPToolsTreeWidget().
getUtilList()
static ToolListType getUtilList () static
Returns the list of official UTIL tools contained in the OpenMS/TOPP release.
Referenced by TOPPASBase::createTOPPToolsTreeWidget().
loadExternalToolConfig_()
static void loadExternalToolConfig_ () static private
loadInternalToolConfig_()
static void loadInternalToolConfig_ () static private
Member Data Documentation
tools_external_
Internal::ToolDescription tools_external_ static private
tools_external_loaded_
bool tools_external_loaded_ static private
tools_internal_
std::vector<Internal::ToolDescription> tools_internal_ static private
tools_internal_loaded_
bool tools_internal_loaded_ static private