OpenMS: XFDRAlgorithm Class Reference
XFDRAlgorithm Class Reference
#include <OpenMS/ANALYSIS/XLMS/XFDRAlgorithm.h>
Public Types
enum ExitCodes { EXECUTION_OK, ILLEGAL_PARAMETERS, UNEXPECTED_RESULT }
Exit codes.
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Public Member Functions
XFDRAlgorithm ()
Default constructor.
~XFDRAlgorithm () override
Default destructor.
ExitCodes run (std::vector< PeptideIdentification > &peptide_ids, ProteinIdentification &protein_id)
Performs the main function of this class, the FDR estimation for cross-linked peptide experiments.
ExitCodes validateClassArguments () const
Checks whether the parameters of the object are valid.
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Private Member Functions
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
void initDataStructures_ (std::vector< PeptideIdentification > &peptide_ids, ProteinIdentification &protein_id)
Prepares vector of PeptideIdentification such that it can be processed downstream. The encompassed steps are: * Set min_score_ and max_score_ encountered in the data * Ensure that crosslink_type and crosslink_rank are available in the PeptideIdentification * Define the crosslink as either inter/or intraprotein * Set the identifier of the Peptide Identification if there is only one protein identification.
void fdr_xprophet_ (std::map< String, Math::Histogram<> > &cum_histograms, const String &targetclass, const String &decoyclass, const String &fulldecoyclass, std::vector< double > &fdr, bool mono)
xprophet method for target hits counting as implemented in xProphet
void findTopUniqueHits_ (std::vector< PeptideIdentification > &peptide_ids)
void writeArgumentsLog_ () const
String getId_ (const PeptideHit &ph) const
Static Private Member Functions
static void assignTypes_ (PeptideHit &ph, StringList &types)
Inspects PeptideIdentification pep_id and assigns all cross-link types that this identification belongs to.
static void calc_qfdr_ (const std::vector< double > &fdr, std::vector< double > &qfdr)
Calculates the qFDR values for the provided FDR values, assuming that the FDRs are sorted by score in the input vector.
static Size getMinIonsMatched_ (const PeptideHit &ph)
static void setIntraProtein_ (PeptideHit &ph, const bool value)
static void setInterProtein_ (PeptideHit &ph, const bool value)
static bool isSameProtein_ (String prot1, String prot2, const String &decoy_string)
Determines whether the Petide Evidences belong to the same protein, modulo decoy.
Private Attributes
Int min_score_
Int max_score_
std::vector< String > unique_ids_
std::vector< double > unique_id_scores_
std::map< String, std::vector< String > > cross_link_classes_
String decoy_string_
double arg_mindeltas_
double arg_minborder_
double arg_maxborder_
Int arg_minionsmatched_
double arg_minscore_
bool arg_uniquex_
bool arg_no_qvalues_
double arg_binsize_
Static Private Attributes
static const String param_decoy_string_
static const String param_minborder_
static const String param_maxborder_
static const String param_mindeltas_
static const String param_minionsmatched_
static const String param_uniquexl_
static const String param_no_qvalues_
static const String param_minscore_
static const String param_binsize_
static const String crosslink_class_intradecoys_
static const String crosslink_class_fulldecoysintralinks_
static const String crosslink_class_interdecoys_
static const String crosslink_class_fulldecoysinterlinks_
static const String crosslink_class_monodecoys_
static const String crosslink_class_intralinks_
static const String crosslink_class_interlinks_
static const String crosslink_class_monolinks_
static const String crosslink_class_decoys_
static const String crosslink_class_targets_
static const String crosslink_class_hybriddecoysintralinks_
static const String crosslink_class_hybriddecoysinterlinks_
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Member Enumeration Documentation
ExitCodes
enum ExitCodes
Exit codes.
Enumerator
EXECUTION_OK
ILLEGAL_PARAMETERS
UNEXPECTED_RESULT
Constructor & Destructor Documentation
XFDRAlgorithm()
XFDRAlgorithm ()
Default constructor.
~XFDRAlgorithm()
~XFDRAlgorithm () override
Default destructor.
Member Function Documentation
assignTypes_()
static void assignTypes_ (PeptideHit & ph, StringList & types) static private
Inspects PeptideIdentification pep_id and assigns all cross-link types that this identification belongs to.
Parameters
pep_id Peptide ID to be assigned.
types Result vector containing the names of the crosslink classes
calc_qfdr_()
static void calc_qfdr_ (const std::vector< double > & fdr, std::vector< double > & qfdr) static private
Calculates the qFDR values for the provided FDR values, assuming that the FDRs are sorted by score in the input vector.
Parameters
fdr Vector with FDR values which should be used for qFDR calculation
qfdr Result qFDR values
fdr_xprophet_()
void fdr_xprophet_ (std::map< String, Math::Histogram<> > & cum_histograms, const String & targetclass, const String & decoyclass, const String & fulldecoyclass, std::vector< double > & fdr, bool mono) private
xprophet method for target hits counting as implemented in xProphet
Target counting as performed by the xProphet software package
Parameters
cum_histograms Cumulative score distributions
findTopUniqueHits_()
void findTopUniqueHits_ (std::vector< PeptideIdentification > & peptide_ids) private
getId_()
String getId_ (const PeptideHit & ph) const private
getMinIonsMatched_()
static Size getMinIonsMatched_ (const PeptideHit & ph) inline static private
References MetaInfoInterface::getMetaValue().
initDataStructures_()
void initDataStructures_ (std::vector< PeptideIdentification > & peptide_ids, ProteinIdentification & protein_id) private
Prepares vector of PeptideIdentification such that it can be processed downstream. The encompassed steps are: * Set min_score_ and max_score_ encountered in the data * Ensure that crosslink_type and crosslink_rank are available in the PeptideIdentification * Define the crosslink as either inter/or intraprotein * Set the identifier of the Peptide Identification if there is only one protein identification.
isSameProtein_()
static bool isSameProtein_ (String prot1, String prot2, const String & decoy_string) inline static private
Determines whether the Petide Evidences belong to the same protein, modulo decoy.
References String::hasSubstring(), and String::substitute().
run()
ExitCodes run (std::vector< PeptideIdentification > & peptide_ids, ProteinIdentification & protein_id)
Performs the main function of this class, the FDR estimation for cross-linked peptide experiments.
Parameters
peptide_ids The PeptideIdentifications from an XL-MS experiment
Referenced by TOPPXFDR::main_().
setInterProtein_()
static void setInterProtein_ (PeptideHit & ph, const bool value) inline static private
References MetaInfoInterface::setMetaValue().
setIntraProtein_()
static void setIntraProtein_ (PeptideHit & ph, const bool value) inline static private
References MetaInfoInterface::setMetaValue().
updateMembers_()
void updateMembers_ () override private virtual
This method is used to update extra member variables at the end of the setParameters() method.
Also call it at the end of the derived classes' copy constructor and assignment operator.
The default implementation is empty.
Reimplemented from DefaultParamHandler.
validateClassArguments()
ExitCodes validateClassArguments () const
Checks whether the parameters of the object are valid.
Returns
ExitCode EXECUTION_OK if they are valid, ILLEGAL_PARAMETERS otherwise
Referenced by TOPPXFDR::main_().
writeArgumentsLog_()
void writeArgumentsLog_ () const private
Member Data Documentation
arg_binsize_
double arg_binsize_ private
arg_maxborder_
double arg_maxborder_ private
arg_minborder_
double arg_minborder_ private
arg_mindeltas_
double arg_mindeltas_ private
arg_minionsmatched_
Int arg_minionsmatched_ private
arg_minscore_
double arg_minscore_ private
arg_no_qvalues_
bool arg_no_qvalues_ private
arg_uniquex_
bool arg_uniquex_ private
cross_link_classes_
std::map<String, std::vector<String> > cross_link_classes_ private
crosslink_class_decoys_
const String crosslink_class_decoys_ static private
crosslink_class_fulldecoysinterlinks_
const String crosslink_class_fulldecoysinterlinks_ static private
crosslink_class_fulldecoysintralinks_
const String crosslink_class_fulldecoysintralinks_ static private
crosslink_class_hybriddecoysinterlinks_
const String crosslink_class_hybriddecoysinterlinks_ static private
crosslink_class_hybriddecoysintralinks_
const String crosslink_class_hybriddecoysintralinks_ static private
crosslink_class_interdecoys_
const String crosslink_class_interdecoys_ static private
crosslink_class_interlinks_
const String crosslink_class_interlinks_ static private
crosslink_class_intradecoys_
const String crosslink_class_intradecoys_ static private
crosslink_class_intralinks_
const String crosslink_class_intralinks_ static private
crosslink_class_monodecoys_
const String crosslink_class_monodecoys_ static private
crosslink_class_monolinks_
const String crosslink_class_monolinks_ static private
crosslink_class_targets_
const String crosslink_class_targets_ static private
decoy_string_
String decoy_string_ private
max_score_
Int max_score_ private
min_score_
Int min_score_ private
param_binsize_
const String param_binsize_ static private
param_decoy_string_
const String param_decoy_string_ static private
param_maxborder_
const String param_maxborder_ static private
param_minborder_
const String param_minborder_ static private
param_mindeltas_
const String param_mindeltas_ static private
param_minionsmatched_
const String param_minionsmatched_ static private
param_minscore_
const String param_minscore_ static private
param_no_qvalues_
const String param_no_qvalues_ static private
param_uniquexl_
const String param_uniquexl_ static private
unique_id_scores_
std::vector<double> unique_id_scores_ private
unique_ids_
std::vector<String> unique_ids_ private