OpenMS: HashGrid< Cluster >::ConstIterator Class Reference
HashGrid< Cluster >::ConstIterator Class Reference
Constant element iterator for the hash grid.
Public Member Functions
ConstIterator (const Grid &grid)
ConstIterator (const Grid &grid, grid_iterator grid_it, cell_iterator cell_it)
ConstIterator (const Iterator &it)
ConstIterator & operator++ ()
ConstIterator operator++ (int)
bool operator== (const ConstIterator &rhs) const
bool operator!= (const ConstIterator &rhs) const
const value_type & operator* () const
const value_type * operator-> () const
const CellIndex index () const
Private Types
typedef Grid::const_iterator grid_iterator
typedef CellContent::const_iterator cell_iterator
Private Member Functions
void searchNextCell_ ()
Private Attributes
const Grid & grid_
grid_iterator grid_it_
cell_iterator cell_it_
Friends
class HashGrid
Detailed Description
template<typename Cluster>
class OpenMS::HashGrid< Cluster >::ConstIterator
Constant element iterator for the hash grid.
Member Typedef Documentation
cell_iterator
typedef CellContent::const_iterator cell_iterator private
grid_iterator
typedef Grid::const_iterator grid_iterator private
Constructor & Destructor Documentation
ConstIterator() [1/3]
ConstIterator (const Grid & grid) inline
ConstIterator() [2/3]
ConstIterator (const Grid & grid, grid_iterator grid_it, cell_iterator cell_it) inline
References HashGrid< Cluster >::ConstIterator::searchNextCell_().
ConstIterator() [3/3]
ConstIterator (const Iterator & it) inline
Member Function Documentation
index()
const CellIndex index () const inline
References HashGrid< Cluster >::ConstIterator::grid_it_.
operator!=()
bool operator!= (const ConstIterator & rhs) const inline
operator*()
const value_type& operator* () const inline
References HashGrid< Cluster >::ConstIterator::cell_it_.
operator++() [1/2]
ConstIterator& operator++ () inline
References HashGrid< Cluster >::ConstIterator::cell_it_, and HashGrid< Cluster >::ConstIterator::searchNextCell_().
Referenced by HashGrid< Cluster >::ConstIterator::operator++().
operator++() [2/2]
ConstIterator operator++ (int) inline
References HashGrid< Cluster >::ConstIterator::operator++().
operator->()
const value_type* operator-> () const inline
References HashGrid< Cluster >::ConstIterator::cell_it_.
operator==()
bool operator== (const ConstIterator & rhs) const inline
References HashGrid< Cluster >::ConstIterator::cell_it_, and HashGrid< Cluster >::ConstIterator::grid_it_.
searchNextCell_()
void searchNextCell_ () inline private
References HashGrid< Cluster >::ConstIterator::cell_it_, HashGrid< Cluster >::ConstIterator::grid_, and HashGrid< Cluster >::ConstIterator::grid_it_.
Referenced by HashGrid< Cluster >::ConstIterator::ConstIterator(), and HashGrid< Cluster >::ConstIterator::operator++().
Friends And Related Function Documentation
HashGrid
friend class HashGrid friend
Member Data Documentation
cell_it_
cell_iterator cell_it_ private
Referenced by HashGrid< Cluster >::ConstIterator::operator*(), HashGrid< Cluster >::ConstIterator::operator++(), HashGrid< Cluster >::ConstIterator::operator->(), HashGrid< Cluster >::ConstIterator::operator==(), and HashGrid< Cluster >::ConstIterator::searchNextCell_().
grid_
const Grid& grid_ private
Referenced by HashGrid< Cluster >::ConstIterator::searchNextCell_().
grid_it_
grid_iterator grid_it_ private
Referenced by HashGrid< Cluster >::ConstIterator::index(), HashGrid< Cluster >::ConstIterator::operator==(), and HashGrid< Cluster >::ConstIterator::searchNextCell_().