OpenMS: SpectrumAlignment Class Reference
SpectrumAlignment Class Reference
Spectrum Comparison
Aligns the peaks of two sorted spectra Method 1: Using a banded (width via 'tolerance' parameter) alignment if absolute tolerances are given. Scoring function is the m/z distance between peaks. Intensity does not play a role!
#include <OpenMS/COMPARISON/SPECTRA/SpectrumAlignment.h>
Public Member Functions
SpectrumAlignment ()
default constructor
SpectrumAlignment (const SpectrumAlignment &source)
copy constructor
~SpectrumAlignment () override
destructor
SpectrumAlignment & operator= (const SpectrumAlignment &source)
assignment operator
template<typename SpectrumType1 , typename SpectrumType2 >
void getSpectrumAlignment (std::vector< std::pair< Size, Size > > &alignment, const SpectrumType1 &s1, const SpectrumType2 &s2) const
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
Aligns the peaks of two sorted spectra Method 1: Using a banded (width via 'tolerance' parameter) alignment if absolute tolerances are given. Scoring function is the m/z distance between peaks. Intensity does not play a role!
Method 2: If relative tolerance (ppm) is specified a simple matching of peaks is performed: Peaks from s1 (usually the theoretical spectrum) are assigned to the closest peak in s2 if it lies in the tolerance window
Note
: a peak in s2 can be matched to none, one or multiple peaks in s1. Peaks in s1 may be matched to none or one peak in s2.
: intensity is ignored TODO: improve time complexity, currently O(|s1|*log(|s2|))
Parameters of this class are:
Name Type Default Restrictions Description
tolerance float 0.3 Defines the absolute (in Da) or relative (in ppm) tolerance
is_relative_tolerance string false true, false If true, the 'tolerance' is interpreted as ppm-value
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Constructor & Destructor Documentation
SpectrumAlignment() [1/2]
SpectrumAlignment ()
default constructor
SpectrumAlignment() [2/2]
SpectrumAlignment (const SpectrumAlignment & source)
copy constructor
~SpectrumAlignment()
~SpectrumAlignment () override
destructor
Member Function Documentation
getSpectrumAlignment()
void getSpectrumAlignment (std::vector< std::pair< Size, Size > > & alignment, const SpectrumType1 & s1, const SpectrumType2 & s2) const inline
References MatchedIterator< CONT_T, TRAIT, CONST_T >::end(), MatchedIterator< CONT_T, TRAIT, CONST_T >::refIdx(), and MatchedIterator< CONT_T, TRAIT, CONST_T >::tgtIdx().
Referenced by SpectraMerger::mergeSpectra_().
operator=()
SpectrumAlignment& operator= (const SpectrumAlignment & source)
assignment operator