OpenMS: HashGrid< Cluster >::Iterator Class Reference
HashGrid< Cluster >::Iterator Class Reference
Element iterator for the hash grid.
Public Member Functions
Iterator (Grid &grid)
Iterator (Grid &grid, grid_iterator grid_it, cell_iterator cell_it)
Iterator & operator++ ()
Iterator operator++ (int)
bool operator== (const Iterator &rhs) const
bool operator!= (const Iterator &rhs) const
value_type & operator* () const
value_type * operator-> () const
const CellIndex index () const
Private Types
typedef Grid::iterator grid_iterator
typedef CellContent::iterator cell_iterator
Private Member Functions
void searchNextCell_ ()
Private Attributes
Grid & grid_
grid_iterator grid_it_
cell_iterator cell_it_
Friends
class HashGrid
Detailed Description
template<typename Cluster>
class OpenMS::HashGrid< Cluster >::Iterator
Element iterator for the hash grid.
Member Typedef Documentation
cell_iterator
typedef CellContent::iterator cell_iterator private
grid_iterator
typedef Grid::iterator grid_iterator private
Constructor & Destructor Documentation
Iterator() [1/2]
Iterator (Grid & grid) inline
Iterator() [2/2]
Iterator (Grid & grid, grid_iterator grid_it, cell_iterator cell_it) inline
References HashGrid< Cluster >::Iterator::searchNextCell_().
Member Function Documentation
index()
const CellIndex index () const inline
References HashGrid< Cluster >::Iterator::grid_it_.
operator!=()
bool operator!= (const Iterator & rhs) const inline
operator*()
value_type& operator* () const inline
References HashGrid< Cluster >::Iterator::cell_it_.
operator++() [1/2]
Iterator& operator++ () inline
References HashGrid< Cluster >::Iterator::cell_it_, and HashGrid< Cluster >::Iterator::searchNextCell_().
Referenced by HashGrid< Cluster >::Iterator::operator++().
operator++() [2/2]
Iterator operator++ (int) inline
References HashGrid< Cluster >::Iterator::operator++().
operator->()
value_type* operator-> () const inline
References HashGrid< Cluster >::Iterator::cell_it_.
operator==()
bool operator== (const Iterator & rhs) const inline
References HashGrid< Cluster >::Iterator::cell_it_, and HashGrid< Cluster >::Iterator::grid_it_.
searchNextCell_()
void searchNextCell_ () inline private
References HashGrid< Cluster >::Iterator::cell_it_, HashGrid< Cluster >::Iterator::grid_, and HashGrid< Cluster >::Iterator::grid_it_.
Referenced by HashGrid< Cluster >::Iterator::Iterator(), and HashGrid< Cluster >::Iterator::operator++().
Friends And Related Function Documentation
HashGrid
friend class HashGrid friend
Member Data Documentation
cell_it_
cell_iterator cell_it_ private
Referenced by HashGrid< Cluster >::erase(), HashGrid< Cluster >::Iterator::operator*(), HashGrid< Cluster >::Iterator::operator++(), HashGrid< Cluster >::Iterator::operator->(), HashGrid< Cluster >::Iterator::operator==(), and HashGrid< Cluster >::Iterator::searchNextCell_().
grid_
Grid& grid_ private
Referenced by HashGrid< Cluster >::Iterator::searchNextCell_().
grid_it_
grid_iterator grid_it_ private
Referenced by HashGrid< Cluster >::erase(), HashGrid< Cluster >::Iterator::index(), HashGrid< Cluster >::Iterator::operator==(), and HashGrid< Cluster >::Iterator::searchNextCell_().