OpenMS: ProgressLogger Class Reference
ProgressLogger Class Reference
Base class for all classes that want to report their progress.
#include <OpenMS/CONCEPT/ProgressLogger.h>
Classes
class ProgressLoggerImpl
This class represents an actual implementation of a logger.
Public Types
enum LogType { CMD, GUI, NONE }
Possible log types.
Public Member Functions
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Static Protected Member Functions
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes
static int recursion_depth_
Detailed Description
Base class for all classes that want to report their progress.
Per default the progress log is disabled. Use setLogType to enable it.
Use startProgress, setProgress and endProgress for the actual logging.
Note
All methods are const, so it can be used through a const reference or in const methods as well!
Member Enumeration Documentation
LogType
enum LogType
Possible log types.
Enumerator
CMD
Command line progress.
GUI
Progress dialog.
NONE
No progress logging.
Constructor & Destructor Documentation
ProgressLogger() [1/2]
ProgressLogger ()
Constructor.
~ProgressLogger()
~ProgressLogger ()
Destructor.
ProgressLogger() [2/2]
ProgressLogger (const ProgressLogger & other)
Copy constructor.
Member Function Documentation
endProgress()
void endProgress () const
Ends the progress display.
Referenced by SpectraMerger::averageCentroidSpectra_(), GridBasedClustering< Metric >::cluster(), SignalToNoiseEstimatorMeanIterative< Container >::computeSTN_(), SignalToNoiseEstimatorMedian< ContainerT >::computeSTN_(), TOPPOpenSwathBase::loadTransitionList(), TOPPGNPSExport::main_(), TOPPOpenPepXLLF::main_(), TOPPOpenPepXL::main_(), and NucleicAcidSearchEngine::main_().
getLogType()
LogType getLogType () const
Returns the type of progress log being used.
logTypeToFactoryName_()
static String logTypeToFactoryName_ (LogType type) static protected
Return the name of the factory product used for this log type.
nextProgress()
void nextProgress () const
increment progress by 1 (according to range begin-end)
operator=()
ProgressLogger& operator= (const ProgressLogger & other)
Assignment Operator.
Referenced by SignalToNoiseEstimator< ContainerT >::operator=().
setLogType()
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
Referenced by UTILProteomicsLFQ::align_(), UTILProteomicsLFQ::centroidAndCorrectPrecursors_(), TOPPOpenSwathBase::loadSwathFiles_(), TOPPOpenSwathBase::loadTransitionList(), TDfeatureDeconvolution::main_(), TOPPGNPSExport::main_(), TOPPXFDR::main_(), TOPPFLASHDeconv::main_(), TOPPOpenPepXLLF::main_(), TOPPOpenPepXL::main_(), FLASHDeconv::main_(), NucleicAcidSearchEngine::main_(), TOPPOpenSwathBase::performCalibration(), UTILProteomicsLFQ::quantifyFraction_(), UTILProteomicsLFQ::recalibrateMasses_(), and TOPPViewBase::runTOPPTool_().
setProgress()
void setProgress (SignedSize value) const
Sets the current progress.
Referenced by SpectraMerger::averageCentroidSpectra_(), GridBasedClustering< Metric >::cluster(), SignalToNoiseEstimatorMeanIterative< Container >::computeSTN_(), SignalToNoiseEstimatorMedian< ContainerT >::computeSTN_(), TOPPGNPSExport::main_(), and NucleicAcidSearchEngine::main_().
startProgress()
void startProgress (SignedSize begin, SignedSize end, const String & label) const
Initializes the progress display.
Sets the progress range from begin to end. If begin equals end, setProgress only indicates that the program is still running, but without showing any absolute progress value.
Sets the label to label.
Note
Make sure to call setLogType first!
Referenced by SpectraMerger::averageCentroidSpectra_(), GridBasedClustering< Metric >::cluster(), SignalToNoiseEstimatorMeanIterative< Container >::computeSTN_(), SignalToNoiseEstimatorMedian< ContainerT >::computeSTN_(), TOPPOpenSwathBase::loadTransitionList(), TOPPGNPSExport::main_(), TOPPOpenPepXLLF::main_(), TOPPOpenPepXL::main_(), and NucleicAcidSearchEngine::main_().
Member Data Documentation
current_logger_
ProgressLoggerImpl* current_logger_ mutable protected
last_invoke_
time_t last_invoke_ mutable protected
recursion_depth_
int recursion_depth_ static protected
type_
LogType type_ mutable protected