OpenMS: DBoundingBox< D > Class Template Reference
DBoundingBox< D > Class Template Reference
Datastructures
A D-dimensional bounding box.
#include <OpenMS/DATASTRUCTURES/DBoundingBox.h>
Public Member Functions
Constructors and Destructor
DBoundingBox ()
Default constructor.
DBoundingBox (const DBoundingBox &rhs)
Copy constructor.
DBoundingBox & operator= (const DBoundingBox &rhs)
Assignment operator.
DBoundingBox & operator= (const Base &rhs)
Assignment operator for the base class.
~DBoundingBox ()
Destructor.
DBoundingBox (const PositionType &minimum, const PositionType &maximum)
Constructor from two positions.
Accessors
void enlarge (const PositionType &p)
Enlarges the bounding box such that it contains a position.
void enlarge (CoordinateType x, CoordinateType y)
Enlarges the bounding box such that it contains a position specified by two coordinates.
Predicates
bool operator== (const DBoundingBox &rhs) const
Equality operator.
bool operator== (const Base &rhs) const
Equality operator.
bool encloses (const PositionType &position) const
Checks whether this range contains a certain point.
bool encloses (CoordinateType x, CoordinateType y) const
2D-version encloses(x,y) is for convenience only
bool intersects (const DBoundingBox &bounding_box) const
bool isEmpty () const
Test if bounding box is empty.
Public Member Functions inherited from DIntervalBase< D >
DIntervalBase ()
Default constructor.
DIntervalBase (const DIntervalBase &rhs)
Copy constructor.
DIntervalBase (DIntervalBase &&) noexcept=default
Move constructor.
DIntervalBase & operator= (const DIntervalBase &rhs)
Assignment operator.
~DIntervalBase ()
Destructor.
DIntervalBase (PositionType const &minimum, PositionType const &maximum)
This constructor sets min_ and max_ directly.
PositionType const & minPosition () const
Accessor to minimum position.
PositionType const & maxPosition () const
Accessor to maximum position.
void setMin (PositionType const &position)
Mutator for minimum position.
void setMax (PositionType const &position)
Mutator for maximum position.
void setMinMax (PositionType const &min, PositionType const &max)
Mutator for minimum and maximum position.
template<UInt D2>
void assign (const DIntervalBase< D2 > rhs)
Assignment from a DIntervalBase of different dimensions.
bool operator== (const DIntervalBase &rhs) const
Equality operator.
bool operator!= (const DIntervalBase &rhs) const
Equality operator.
void clear ()
Make the interval empty.
PositionType center () const
Returns the center of the interval.
PositionType diagonal () const
Returns the diagonal of the area, i.e. max_ - min_.
CoordinateType minX () const
Accessor for min_ coordinate minimum.
CoordinateType minY () const
Accessor for max_ coordinate minimum.
CoordinateType maxX () const
Accessor for min_ coordinate maximum.
CoordinateType maxY () const
Accessor for max_ coordinate maximum.
void setMinX (CoordinateType const c)
Mutator for min_ coordinate of the smaller point.
void setMinY (CoordinateType const c)
Mutator for max_ coordinate of the smaller point.
void setMaxX (CoordinateType const c)
Mutator for min_ coordinate of the larger point.
void setMaxY (CoordinateType const c)
Mutator for max_ coordinate of the larger point.
CoordinateType width () const
Returns the width of the area i.e. the difference of dimension zero (X).
CoordinateType height () const
Returns the height of the area i.e. the difference of dimension one (Y).
Related Functions
(Note that these are not member functions.)
template<UInt D>
std::ostream & operator<< (std::ostream &os, const DBoundingBox< D > &bounding_box)
Print the contents to a stream.
Type definitions
enum { DIMENSION = D }
Dimensions.
typedef Internal::DIntervalBase< D > Base
Base class type.
typedef Base::PositionType PositionType
Position type.
typedef Base::CoordinateType CoordinateType
Coordinate type of the positions.
PositionType min_
lower left point
PositionType max_
upper right point
Additional Inherited Members
Public Types inherited from DIntervalBase< D >
enum { DIMENSION = D }
Dimensions.
typedef DPosition< D > PositionType
Position type.
typedef PositionType::CoordinateType CoordinateType
Coordinate type of the positions.
Static Public Attributes inherited from DIntervalBase< D >
static const DIntervalBase empty = DIntervalBase<D>(std::make_pair(DIntervalBase<D>::PositionType::maxPositive(), DIntervalBase<D>::PositionType::minNegative()))
empty instance
static const DIntervalBase zero = DIntervalBase<D>(DIntervalBase<D>::PositionType::zero(), DIntervalBase<D>::PositionType::zero())
instance with all positions zero
Protected Member Functions inherited from DIntervalBase< D >
void normalize_ ()
normalization to keep all dimensions in the right geometrical order (min_[X] < max_[X])
DIntervalBase (const std::pair< PositionType, PositionType > &pair)
Protected constructor for the construction of static instances.
Protected Attributes inherited from DIntervalBase< D >
PositionType min_
lower left point
PositionType max_
upper right point
Detailed Description
template<UInt D>
class OpenMS::DBoundingBox< D >
A D-dimensional bounding box.
A DBoundingBox denotes a closed interval. Upper and lower margins are both contained.
Member Typedef Documentation
Base
typedef Internal::DIntervalBase<D> Base
Base class type.
CoordinateType
typedef Base::CoordinateType CoordinateType
Coordinate type of the positions.
PositionType
typedef Base::PositionType PositionType
Position type.
Member Enumeration Documentation
anonymous enum
anonymous enum
Dimensions.
Enumerator
DIMENSION
Constructor & Destructor Documentation
DBoundingBox() [1/3]
DBoundingBox () inline
Default constructor.
DBoundingBox() [2/3]
DBoundingBox (const DBoundingBox< D > & rhs) inline
Copy constructor.
~DBoundingBox()
~DBoundingBox () inline
Destructor.
DBoundingBox() [3/3]
DBoundingBox (const PositionType & minimum, const PositionType & maximum) inline
Constructor from two positions.
Member Function Documentation
encloses() [1/2]
bool encloses (const PositionType & position) const inline
Checks whether this range contains a certain point.
Parameters
position The point's position.
Returns
true if point lies inside this area.
Referenced by DBoundingBox< 2 >::encloses().
encloses() [2/2]
bool encloses (CoordinateType x, CoordinateType y) const inline
2D-version encloses(x,y) is for convenience only
enlarge() [1/2]
void enlarge (const PositionType & p) inline
Enlarges the bounding box such that it contains a position.
Referenced by GridBasedClustering< Metric >::cluster(), and DBoundingBox< 2 >::enlarge().
enlarge() [2/2]
void enlarge (CoordinateType x, CoordinateType y) inline
Enlarges the bounding box such that it contains a position specified by two coordinates.
intersects()
bool intersects (const DBoundingBox< D > & bounding_box) const inline
Checks whether this bounding box intersects with another bounding box
isEmpty()
bool isEmpty () const inline
Test if bounding box is empty.
operator=() [1/2]
DBoundingBox& operator= (const Base & rhs) inline
Assignment operator for the base class.
operator=() [2/2]
DBoundingBox& operator= (const DBoundingBox< D > & rhs) inline
Assignment operator.
operator==() [1/2]
bool operator== (const Base & rhs) const inline
Equality operator.
operator==() [2/2]
bool operator== (const DBoundingBox< D > & rhs) const inline
Equality operator.
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const DBoundingBox< D > & bounding_box) related
Print the contents to a stream.
Member Data Documentation
max_
PositionType max_
upper right point
Referenced by DBoundingBox< 2 >::intersects().
min_
PositionType min_
lower left point
Referenced by DBoundingBox< 2 >::intersects().