OpenMS: _Region< __K, _Val, _SubVal, _Acc, _Cmp > Struct Template Reference
_Region< __K, _Val, _SubVal, _Acc, _Cmp > Struct Template Reference
#include <OpenMS/DATASTRUCTURES/KDTree.h>
Public Types
typedef _Val value_type
typedef _SubVal subvalue_type
typedef std::pair< _Region, _SubVal > _CenterPt
Public Member Functions
_Region (_Acc const &__acc=_Acc(), const _Cmp &__cmp=_Cmp())
template<typename Val >
_Region (Val const &__V, _Acc const &__acc=_Acc(), const _Cmp &__cmp=_Cmp())
template<typename Val >
_Region (Val const &__V, subvalue_type const &__R, _Acc const &__acc=_Acc(), const _Cmp &__cmp=_Cmp())
bool intersects_with (_CenterPt const &__THAT) const
bool intersects_with (_Region const &__THAT) const
bool encloses (value_type const &__V) const
_Region & set_high_bound (value_type const &__V, size_t const __L)
_Region & set_low_bound (value_type const &__V, size_t const __L)
Public Attributes
subvalue_type _M_low_bounds [__K]
subvalue_type _M_high_bounds [__K]
_Acc _M_acc
_Cmp _M_cmp
Member Typedef Documentation
_CenterPt
typedef std::pair<_Region,_SubVal> _CenterPt
subvalue_type
typedef _SubVal subvalue_type
value_type
typedef _Val value_type
Constructor & Destructor Documentation
_Region() [1/3]
_Region (_Acc const & __acc = _Acc(), const _Cmp & __cmp = _Cmp()) inline
_Region() [2/3]
_Region (Val const & __V, _Acc const & __acc = _Acc(), const _Cmp & __cmp = _Cmp()) inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_acc, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
_Region() [3/3]
_Region (Val const & __V, subvalue_type const & __R, _Acc const & __acc = _Acc(), const _Cmp & __cmp = _Cmp()) inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_acc, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
Member Function Documentation
encloses()
bool encloses (value_type const & __V) const inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_acc, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_cmp, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
Referenced by KDTree< 2, KDTreeFeatureNode >::_M_count_within_range(), KDTree< 2, KDTreeFeatureNode >::_M_find_within_range(), and KDTree< 2, KDTreeFeatureNode >::_M_visit_within_range().
intersects_with() [1/2]
bool intersects_with (_CenterPt const & __THAT) const inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_cmp, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
Referenced by KDTree< 2, KDTreeFeatureNode >::_M_count_within_range(), KDTree< 2, KDTreeFeatureNode >::_M_find_within_range(), and KDTree< 2, KDTreeFeatureNode >::_M_visit_within_range().
intersects_with() [2/2]
bool intersects_with (_Region< __K, _Val, _SubVal, _Acc, _Cmp > const & __THAT) const inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_cmp, _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
set_high_bound()
_Region& set_high_bound (value_type const & __V, size_t const __L) inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_acc, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_high_bounds.
Referenced by KDTree< 2, KDTreeFeatureNode >::_M_count_within_range(), KDTree< 2, KDTreeFeatureNode >::_M_find_within_range(), and KDTree< 2, KDTreeFeatureNode >::_M_visit_within_range().
set_low_bound()
_Region& set_low_bound (value_type const & __V, size_t const __L) inline
References _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_acc, and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_M_low_bounds.
Referenced by KDTree< 2, KDTreeFeatureNode >::_M_count_within_range(), KDTree< 2, KDTreeFeatureNode >::_M_find_within_range(), and KDTree< 2, KDTreeFeatureNode >::_M_visit_within_range().
Member Data Documentation
_M_acc
_Acc _M_acc
Referenced by _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_Region(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::encloses(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::set_high_bound(), and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::set_low_bound().
_M_cmp
_Cmp _M_cmp
Referenced by _Region< __K, _Val, _SubVal, _Acc, _Cmp >::encloses(), and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::intersects_with().
_M_high_bounds
subvalue_type _M_high_bounds[__K]
Referenced by _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_Region(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::encloses(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::intersects_with(), and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::set_high_bound().
_M_low_bounds
subvalue_type _M_low_bounds[__K]
Referenced by _Region< __K, _Val, _SubVal, _Acc, _Cmp >::_Region(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::encloses(), _Region< __K, _Val, _SubVal, _Acc, _Cmp >::intersects_with(), and _Region< __K, _Val, _SubVal, _Acc, _Cmp >::set_low_bound().