OpenMS: DRange< D > Class Template Reference
DRange< D > Class Template Reference
Datastructures
A D-dimensional half-open interval.
#include <OpenMS/DATASTRUCTURES/DRange.h>
Public Member Functions
Constructors and Destructor
DRange ()
Default constructor.
DRange (const PositionType &lower, const PositionType &upper)
Constructor that takes two Points and constructs a range.
DRange (const DRange &range)
Copy constructor.
DRange (DRange &&) noexcept=default
Move constructor.
DRange (const Base &range)
Copy constructor for the base class.
DRange (CoordinateType minx, CoordinateType miny, CoordinateType maxx, CoordinateType maxy)
Convenient constructor for DRange<2>
DRange & operator= (const DRange &rhs)
Assignment operator.
DRange & operator= (const Base &rhs)
Assignment operator for the base class.
~DRange ()
Destructor.
Predicates
bool operator== (const DRange &rhs) const
Equality operator.
bool operator== (const Base &rhs) const
Equality operator.
bool encloses (const PositionType &position) const
Checks whether this range contains a certain point.
bool encloses (CoordinateType x, CoordinateType y) const
2D-version of encloses for convenience only
DRange united (const DRange< D > &other_range) const
Returns the smallest range containing this range and other_range.
DRangeIntersection intersects (const DRange &range) const
Checks how this range intersects with another range.
bool isIntersected (const DRange &range) const
Checks whether this range intersects with another range.
bool isEmpty () const
Checks if the range is empty.
void extend (double factor)
Extends the range in all dimensions by a certain multiplier.
Public Member Functions inherited from DIntervalBase< D >
DIntervalBase ()
Default constructor.
DIntervalBase (const DIntervalBase &rhs)
Copy constructor.
DIntervalBase (DIntervalBase &&) noexcept=default
Move constructor.
DIntervalBase & operator= (const DIntervalBase &rhs)
Assignment operator.
~DIntervalBase ()
Destructor.
DIntervalBase (PositionType const &minimum, PositionType const &maximum)
This constructor sets min_ and max_ directly.
PositionType const & minPosition () const
Accessor to minimum position.
PositionType const & maxPosition () const
Accessor to maximum position.
void setMin (PositionType const &position)
Mutator for minimum position.
void setMax (PositionType const &position)
Mutator for maximum position.
void setMinMax (PositionType const &min, PositionType const &max)
Mutator for minimum and maximum position.
template<UInt D2>
void assign (const DIntervalBase< D2 > rhs)
Assignment from a DIntervalBase of different dimensions.
bool operator== (const DIntervalBase &rhs) const
Equality operator.
bool operator!= (const DIntervalBase &rhs) const
Equality operator.
void clear ()
Make the interval empty.
PositionType center () const
Returns the center of the interval.
PositionType diagonal () const
Returns the diagonal of the area, i.e. max_ - min_.
CoordinateType minX () const
Accessor for min_ coordinate minimum.
CoordinateType minY () const
Accessor for max_ coordinate minimum.
CoordinateType maxX () const
Accessor for min_ coordinate maximum.
CoordinateType maxY () const
Accessor for max_ coordinate maximum.
void setMinX (CoordinateType const c)
Mutator for min_ coordinate of the smaller point.
void setMinY (CoordinateType const c)
Mutator for max_ coordinate of the smaller point.
void setMaxX (CoordinateType const c)
Mutator for min_ coordinate of the larger point.
void setMaxY (CoordinateType const c)
Mutator for max_ coordinate of the larger point.
CoordinateType width () const
Returns the width of the area i.e. the difference of dimension zero (X).
CoordinateType height () const
Returns the height of the area i.e. the difference of dimension one (Y).
Type definitions
enum { DIMENSION = D }
Dimensions.
enum DRangeIntersection { Disjoint, Intersects, Inside }
Types that describe the kind of intersection between two ranges.
typedef Internal::DIntervalBase< D > Base
Base class type.
typedef Base::PositionType PositionType
Position type.
typedef Base::CoordinateType CoordinateType
Coordinate type of the positions.
PositionType min_
lower left point
PositionType max_
upper right point
Additional Inherited Members
Public Types inherited from DIntervalBase< D >
enum { DIMENSION = D }
Dimensions.
typedef DPosition< D > PositionType
Position type.
typedef PositionType::CoordinateType CoordinateType
Coordinate type of the positions.
Static Public Attributes inherited from DIntervalBase< D >
static const DIntervalBase empty = DIntervalBase<D>(std::make_pair(DIntervalBase<D>::PositionType::maxPositive(), DIntervalBase<D>::PositionType::minNegative()))
empty instance
static const DIntervalBase zero = DIntervalBase<D>(DIntervalBase<D>::PositionType::zero(), DIntervalBase<D>::PositionType::zero())
instance with all positions zero
Protected Member Functions inherited from DIntervalBase< D >
void normalize_ ()
normalization to keep all dimensions in the right geometrical order (min_[X] < max_[X])
DIntervalBase (const std::pair< PositionType, PositionType > &pair)
Protected constructor for the construction of static instances.
Protected Attributes inherited from DIntervalBase< D >
PositionType min_
lower left point
PositionType max_
upper right point
Detailed Description
template<UInt D>
class OpenMS::DRange< D >
A D-dimensional half-open interval.
This class describes a range in D-dimensional space delimited by two points (i.e. a D-dimensional hyper-rectangle). The two points define the lower left and the upper right corner in 2D and analogous points in higher dimensions.
A range is a pair of positions in D-space represented by DPosition. The two limiting points are accessed as minPosition() and maxPosition().
A range denotes a semi-open interval. A lower coordinate of each dimension is part of the range, the higher coordinate is not.
Member Typedef Documentation
Base
typedef Internal::DIntervalBase<D> Base
Base class type.
CoordinateType
typedef Base::CoordinateType CoordinateType
Coordinate type of the positions.
PositionType
typedef Base::PositionType PositionType
Position type.
Member Enumeration Documentation
anonymous enum
anonymous enum
Dimensions.
Enumerator
DIMENSION
DRangeIntersection
enum DRangeIntersection
Types that describe the kind of intersection between two ranges.
Enumerator
Disjoint
No intersection.
Intersects
Intersection.
Inside
One contains the other.
Constructor & Destructor Documentation
DRange() [1/6]
DRange () inline
Default constructor.
Creates a range with all coordinates zero.
DRange() [2/6]
DRange (const PositionType & lower, const PositionType & upper) inline
Constructor that takes two Points and constructs a range.
DRange() [3/6]
DRange (const DRange< D > & range) inline
Copy constructor.
DRange() [4/6]
DRange (DRange< D > &&) default noexcept
Move constructor.
DRange() [5/6]
DRange (const Base & range) inline
Copy constructor for the base class.
DRange() [6/6]
DRange (CoordinateType minx, CoordinateType miny, CoordinateType maxx, CoordinateType maxy) inline
Convenient constructor for DRange<2>
~DRange()
~DRange () inline
Destructor.
Member Function Documentation
encloses() [1/2]
bool encloses (const PositionType & position) const inline
Checks whether this range contains a certain point.
Parameters
position The point's position.
Returns
true if point lies inside this area.
Referenced by DRange< 3 >::intersects(), DRange< 3 >::isIntersected(), and DTA2DFile::load().
encloses() [2/2]
bool encloses (CoordinateType x, CoordinateType y) const inline
2D-version of encloses for convenience only
extend()
void extend (double factor) inline
Extends the range in all dimensions by a certain multiplier.
Extends the range, while maintaining the original center position.
Examples (for D=1): factor = 1.01 extends the range by 1% in total, i.e. 0.5% left and right. factor = 2.00 doubles the total range, e.g. from [0,100] to [-50,150]
Parameters
factor Multiplier (allowed is [0, inf)).
intersects()
DRangeIntersection intersects (const DRange< D > & range) const inline
Checks how this range intersects with another range.
Parameters
range The max_ range.
isEmpty()
bool isEmpty () const inline
Checks if the range is empty.
isIntersected()
bool isIntersected (const DRange< D > & range) const inline
Checks whether this range intersects with another range.
Parameters
range The max_ range.
Returns
True if the areas intersect (i.e. they intersect or one contains the other).
operator=() [1/2]
DRange& operator= (const Base & rhs) inline
Assignment operator for the base class.
operator=() [2/2]
DRange& operator= (const DRange< D > & rhs) inline
Assignment operator.
operator==() [1/2]
bool operator== (const Base & rhs) const inline
Equality operator.
operator==() [2/2]
bool operator== (const DRange< D > & rhs) const inline
Equality operator.
united()
DRange united (const DRange< D > & other_range) const inline
Returns the smallest range containing this range and other_range.
Member Data Documentation
max_
PositionType max_
upper right point
Referenced by DRange< 3 >::intersects(), DRange< 3 >::isIntersected(), and OpenMS::operator<<().
min_
PositionType min_
lower left point
Referenced by DRange< 3 >::intersects(), DRange< 3 >::isIntersected(), and OpenMS::operator<<().