OpenMS: _Iterator< _Val, _Ref, _Ptr > Class Template Reference
_Iterator< _Val, _Ref, _Ptr > Class Template Reference
#include <OpenMS/DATASTRUCTURES/KDTree.h>
Public Types
typedef _Val value_type
typedef _Ref reference
typedef _Ptr pointer
typedef _Iterator< _Val, _Val &, _Val * > iterator
typedef _Iterator< _Val, _Val const &, _Val const * > const_iterator
typedef _Iterator< _Val, _Ref, _Ptr > _Self
typedef _Node< _Val > const * _Link_const_type
typedef std::bidirectional_iterator_tag iterator_category
typedef ptrdiff_t difference_type
Public Member Functions
_Iterator ()
_Iterator (_Link_const_type const __N)
_Iterator (iterator const &__THAT)
_Link_const_type get_raw_node () const
reference operator* () const
pointer operator-> () const
_Self operator++ ()
_Self operator++ (int)
_Self & operator-- ()
_Self operator-- (int)
Friends
bool operator== (_Iterator< _Val, _Ref, _Ptr > const &, _Iterator< _Val, _Ref, _Ptr > const &)
bool operator== (_Iterator< _Val, const _Val &, const _Val * > const &, _Iterator< _Val, _Val &, _Val * > const &)
bool operator== (_Iterator< _Val, _Val &, _Val * > const &, _Iterator< _Val, const _Val &, const _Val * > const &)
bool operator!= (_Iterator< _Val, _Ref, _Ptr > const &, _Iterator< _Val, _Ref, _Ptr > const &)
bool operator!= (_Iterator< _Val, const _Val &, const _Val * > const &, _Iterator< _Val, _Val &, _Val * > const &)
bool operator!= (_Iterator< _Val, _Val &, _Val * > const &, _Iterator< _Val, const _Val &, const _Val * > const &)
Additional Inherited Members
Protected Types inherited from _Base_iterator
typedef _Node_base::_Base_const_ptr _Base_const_ptr
Protected Member Functions inherited from _Base_iterator
_Base_iterator (_Base_const_ptr const __N=nullptr)
_Base_iterator (_Base_iterator const &__THAT)
void _M_increment ()
void _M_decrement ()
Protected Attributes inherited from _Base_iterator
_Base_const_ptr _M_node
Member Typedef Documentation
_Link_const_type
typedef _Node<_Val> const* _Link_const_type
_Self
typedef _Iterator<_Val, _Ref, _Ptr> _Self
const_iterator
typedef _Iterator<_Val, _Val const&, _Val const*> const_iterator
difference_type
typedef ptrdiff_t difference_type
iterator
typedef _Iterator<_Val, _Val&, _Val*> iterator
iterator_category
typedef std::bidirectional_iterator_tag iterator_category
pointer
typedef _Ptr pointer
reference
typedef _Ref reference
value_type
typedef _Val value_type
Constructor & Destructor Documentation
_Iterator() [1/3]
_Iterator () inline
_Iterator() [2/3]
_Iterator (_Link_const_type const __N) inline
_Iterator() [3/3]
_Iterator (iterator const & __THAT) inline
Member Function Documentation
get_raw_node()
_Link_const_type get_raw_node () const inline
References _Base_iterator::_M_node.
Referenced by KDTree< 2, KDTreeFeatureNode >::erase().
operator*()
reference operator* () const inline
References _Base_iterator::_M_node.
Referenced by _Iterator< _Val, _Ref, _Ptr >::operator->().
operator++() [1/2]
_Self operator++ () inline
References _Base_iterator::_M_increment().
operator++() [2/2]
_Self operator++ (int) inline
References _Base_iterator::_M_increment().
operator--() [1/2]
_Self& operator-- () inline
References _Base_iterator::_M_decrement().
operator--() [2/2]
_Self operator-- (int) inline
References _Base_iterator::_M_decrement().
operator->()
pointer operator-> () const inline
References _Iterator< _Val, _Ref, _Ptr >::operator*().
Friends And Related Function Documentation
operator!= [1/3]
bool operator!= (_Iterator< _Val, _Ref, _Ptr > const & __X, _Iterator< _Val, _Ref, _Ptr > const & __Y) friend
operator!= [2/3]
bool operator!= (_Iterator< _Val, _Val &, _Val * > const & __X, _Iterator< _Val, const _Val &, const _Val * > const & __Y) friend
operator!= [3/3]
bool operator!= (_Iterator< _Val, const _Val &, const _Val * > const & __X, _Iterator< _Val, _Val &, _Val * > const & __Y) friend
operator== [1/3]
bool operator== (_Iterator< _Val, _Ref, _Ptr > const & __X, _Iterator< _Val, _Ref, _Ptr > const & __Y) friend
operator== [2/3]
bool operator== (_Iterator< _Val, _Val &, _Val * > const & __X, _Iterator< _Val, const _Val &, const _Val * > const & __Y) friend
operator== [3/3]
bool operator== (_Iterator< _Val, const _Val &, const _Val * > const & __X, _Iterator< _Val, _Val &, _Val * > const & __Y) friend