OpenMS: DPosition< D, TCoordinateType > Class Template Reference
DPosition< D, TCoordinateType > Class Template Reference
Datastructures
Representation of a coordinate in D-dimensional space.
#include <OpenMS/DATASTRUCTURES/DPosition.h>
Public Types
enum { DIMENSION = D }
Dimensions.
typedef TCoordinateType CoordinateType
Coordinate type.
typedef CoordinateType * Iterator
Mutable iterator.
Public Member Functions
Constructors and Destructor
DPosition ()
Default constructor.
~DPosition ()
Destructor (not-virtual as this will save a lot of space!)
DPosition (CoordinateType x)
Constructor that fills all dimensions with the value x.
DPosition (const DPosition &pos)
Copy constructor.
DPosition (DPosition &&rhs) noexcept
Move constructor.
DPosition (CoordinateType x, CoordinateType y)
Constructor only for DPosition<2> that takes two Coordinates.
DPosition & operator= (const DPosition &source)
Assignment operator.
Static Public Member Functions
Static values
static const DPosition zero ()
all zero
static const DPosition minPositive ()
smallest positive
static const DPosition minNegative ()
smallest negative
static const DPosition maxPositive ()
largest positive
Public Attributes
const typedef CoordinateType * ConstIterator
Non-mutable iterator.
STL compatibility type definitions
typedef CoordinateType value_type
typedef CoordinateType & reference
typedef CoordinateType * pointer
typedef CoordinateType * iterator
const typedef CoordinateType * const_iterator
Accessors
CoordinateType operator[] (Size index) const
Const accessor for the dimensions.
CoordinateType & operator[] (Size index)
Accessor for the dimensions.
CoordinateType getX () const
Name accessor for the first dimension. Only for DPosition<2>, for visualization.
CoordinateType getY () const
Name accessor for the second dimension. Only for DPosition<2>, for visualization.
void setX (CoordinateType c)
Name mutator for the first dimension. Only for DPosition<2>, for visualization.
void setY (CoordinateType c)
Name mutator for the second dimension. Only for DPosition<2>, for visualization.
bool operator== (const DPosition &point) const
Equality operator.
bool operator!= (const DPosition &point) const
Equality operator.
bool operator< (const DPosition &point) const
Lexicographical less than operator. Lexicographical comparison from dimension 0 to dimension D-1 is done.
bool operator<= (const DPosition &point) const
Lexicographical greater less or equal operator.
bool spatiallyLessEqual (const DPosition &point) const
Spatially (geometrically) less or equal operator. All coordinates must be "<=".
bool spatiallyGreaterEqual (const DPosition &point) const
Spatially (geometrically) greater or equal operator. All coordinates must be ">=".
bool operator> (const DPosition &point) const
Lexicographical greater than operator.
bool operator>= (const DPosition &point) const
Lexicographical greater or equal operator.
DPosition operator+ (const DPosition &point) const
Addition (a bit inefficient)
DPosition & operator+= (const DPosition &point)
Addition.
DPosition operator- (const DPosition &point) const
Subtraction (a bit inefficient)
DPosition & operator-= (const DPosition &point)
Subtraction.
DPosition operator- () const
Negation (a bit inefficient)
CoordinateType operator* (const DPosition &point) const
Inner product.
DPosition & operator*= (CoordinateType scalar)
Scalar multiplication.
DPosition & operator/= (CoordinateType scalar)
Scalar division.
void clear ()
Set all dimensions to zero.
static Size size ()
Returns the number of dimensions.
Iteration
CoordinateType coordinate_ [D]
ConstIterator begin () const
Non-mutable begin iterator.
ConstIterator end () const
Non-mutable end iterator.
Iterator begin ()
Mutable begin iterator.
Iterator end ()
Mutable end iterator.
Detailed Description
template<UInt D, typename TCoordinateType = double>
class OpenMS::DPosition< D, TCoordinateType >
Representation of a coordinate in D-dimensional space.
Member Typedef Documentation
CoordinateType
typedef TCoordinateType CoordinateType
Coordinate type.
Iterator
typedef CoordinateType* Iterator
Mutable iterator.
iterator
typedef CoordinateType* iterator
pointer
typedef CoordinateType* pointer
reference
typedef CoordinateType& reference
value_type
typedef CoordinateType value_type
Member Enumeration Documentation
anonymous enum
anonymous enum
Dimensions.
Enumerator
DIMENSION
Constructor & Destructor Documentation
DPosition() [1/5]
DPosition () inline
Default constructor.
Creates a position with all coordinates zero.
Referenced by DPosition< DIMENSION >::maxPositive(), DPosition< DIMENSION >::minNegative(), and DPosition< DIMENSION >::minPositive().
~DPosition()
~DPosition () inline
Destructor (not-virtual as this will save a lot of space!)
DPosition() [2/5]
DPosition (CoordinateType x) inline
Constructor that fills all dimensions with the value x.
DPosition() [3/5]
DPosition (const DPosition< D, TCoordinateType > & pos) inline
Copy constructor.
DPosition() [4/5]
DPosition (DPosition< D, TCoordinateType > && rhs) inline noexcept
Move constructor.
DPosition() [5/5]
DPosition (CoordinateType x, CoordinateType y) inline
Constructor only for DPosition<2> that takes two Coordinates.
Member Function Documentation
begin() [1/2]
Iterator begin () inline
Mutable begin iterator.
begin() [2/2]
ConstIterator begin () const inline
Non-mutable begin iterator.
Referenced by HashGrid< Cluster >::cellindexAtClustercenter_(), OpenMS::hash_value(), and HashGrid< Cluster >::updateGridDimension_().
clear()
void clear () inline
Set all dimensions to zero.
Referenced by AveragePosition< D >::add(), AveragePosition< D >::clear(), and DPosition< DIMENSION >::DPosition().
end() [1/2]
Iterator end () inline
Mutable end iterator.
end() [2/2]
ConstIterator end () const inline
Non-mutable end iterator.
Referenced by HashGrid< Cluster >::cellindexAtClustercenter_(), OpenMS::hash_value(), and HashGrid< Cluster >::updateGridDimension_().
getX()
CoordinateType getX () const inline
Name accessor for the first dimension. Only for DPosition<2>, for visualization.
Referenced by GridBasedClustering< Metric >::cluster().
getY()
CoordinateType getY () const inline
Name accessor for the second dimension. Only for DPosition<2>, for visualization.
Referenced by GridBasedClustering< Metric >::cluster().
maxPositive()
static const DPosition maxPositive () inline static
largest positive
minNegative()
static const DPosition minNegative () inline static
smallest negative
minPositive()
static const DPosition minPositive () inline static
smallest positive
operator!=()
bool operator!= (const DPosition< D, TCoordinateType > & point) const inline
Equality operator.
operator*()
CoordinateType operator* (const DPosition< D, TCoordinateType > & point) const inline
Inner product.
operator*=()
DPosition& operator*= (CoordinateType scalar) inline
Scalar multiplication.
operator+()
DPosition operator+ (const DPosition< D, TCoordinateType > & point) const inline
Addition (a bit inefficient)
operator+=()
DPosition& operator+= (const DPosition< D, TCoordinateType > & point) inline
Addition.
operator-() [1/2]
DPosition operator- () const inline
Negation (a bit inefficient)
operator-() [2/2]
DPosition operator- (const DPosition< D, TCoordinateType > & point) const inline
Subtraction (a bit inefficient)
operator-=()
DPosition& operator-= (const DPosition< D, TCoordinateType > & point) inline
Subtraction.
operator/=()
DPosition& operator/= (CoordinateType scalar) inline
Scalar division.
operator<()
bool operator< (const DPosition< D, TCoordinateType > & point) const inline
Lexicographical less than operator. Lexicographical comparison from dimension 0 to dimension D-1 is done.
Referenced by DPosition< DIMENSION >::operator>=().
operator<=()
bool operator<= (const DPosition< D, TCoordinateType > & point) const inline
Lexicographical greater less or equal operator.
Referenced by DPosition< DIMENSION >::operator>().
operator=()
DPosition& operator= (const DPosition< D, TCoordinateType > & source) inline
Assignment operator.
operator==()
bool operator== (const DPosition< D, TCoordinateType > & point) const inline
Equality operator.
Referenced by DPosition< DIMENSION >::operator!=().
operator>()
bool operator> (const DPosition< D, TCoordinateType > & point) const inline
Lexicographical greater than operator.
operator>=()
bool operator>= (const DPosition< D, TCoordinateType > & point) const inline
Lexicographical greater or equal operator.
operator[]() [1/2]
CoordinateType& operator[] (Size index) inline
Accessor for the dimensions.
operator[]() [2/2]
CoordinateType operator[] (Size index) const inline
Const accessor for the dimensions.
setX()
void setX (CoordinateType c) inline
Name mutator for the first dimension. Only for DPosition<2>, for visualization.
setY()
void setY (CoordinateType c) inline
Name mutator for the second dimension. Only for DPosition<2>, for visualization.
size()
static Size size () inline static
Returns the number of dimensions.
spatiallyGreaterEqual()
bool spatiallyGreaterEqual (const DPosition< D, TCoordinateType > & point) const inline
Spatially (geometrically) greater or equal operator. All coordinates must be ">=".
spatiallyLessEqual()
bool spatiallyLessEqual (const DPosition< D, TCoordinateType > & point) const inline
Spatially (geometrically) less or equal operator. All coordinates must be "<=".
zero()
static const DPosition zero () inline static
all zero
Member Data Documentation
const_iterator
const typedef CoordinateType* const_iterator
Referenced by HashGrid< Cluster >::cellindexAtClustercenter_().
ConstIterator
const typedef CoordinateType* ConstIterator
Non-mutable iterator.
coordinate_
CoordinateType coordinate_[D] protected
Referenced by DPosition< DIMENSION >::begin(), DPosition< DIMENSION >::clear(), DPosition< DIMENSION >::DPosition(), DPosition< DIMENSION >::end(), DPosition< DIMENSION >::getX(), DPosition< DIMENSION >::getY(), DPosition< DIMENSION >::operator*(), DPosition< DIMENSION >::operator*=(), DPosition< DIMENSION >::operator+(), DPosition< DIMENSION >::operator+=(), DPosition< DIMENSION >::operator-(), DPosition< DIMENSION >::operator-=(), DPosition< DIMENSION >::operator/=(), DPosition< DIMENSION >::operator<(), DPosition< DIMENSION >::operator<=(), DPosition< DIMENSION >::operator=(), DPosition< DIMENSION >::operator==(), DPosition< DIMENSION >::operator[](), DPosition< DIMENSION >::setX(), DPosition< DIMENSION >::setY(), DPosition< DIMENSION >::spatiallyGreaterEqual(), and DPosition< DIMENSION >::spatiallyLessEqual().