OpenMS: String Class Reference
String Class Reference
Datastructures
A more convenient string class.
#include <OpenMS/DATASTRUCTURES/String.h>
Public Types
Type definitions
enum QuotingMethod { NONE, ESCAPE, DOUBLE }
How to handle embedded quotes when quoting strings.
typedef iterator Iterator
Iterator.
typedef const_iterator ConstIterator
Const Iterator.
typedef reverse_iterator ReverseIterator
Reverse Iterator.
typedef const_reverse_iterator ConstReverseIterator
Const reverse Iterator.
typedef size_type SizeType
UInt type.
Public Member Functions
Constructors
String ()
Default constructor.
String (const String &)=default
Copy constructor.
String (String &&)=default
Move constructor.
String (const std::string &s)
Constructor from std::string.
String (const QString &s)
Constructor from Qt QString.
String (const char *s)
Constructor from char*.
String (const char c)
Constructor from a char.
String (const char *s, SizeType length)
Constructor from char* (only length characters)
String (size_t len, char c)
Constructor from char (repeats the char len times)
template<class InputIterator >
String (InputIterator first, InputIterator last)
Constructor from a char range.
String (int i)
Constructor from an integer.
String (unsigned int i)
Constructor from an unsigned integer.
String (short int i)
Constructor from an integer.
String (short unsigned int i)
Constructor from an unsigned integer.
String (long int i)
Constructor from an integer.
String (long unsigned int i)
Constructor from an unsigned integer.
String (long long unsigned int i)
Constructor from an unsigned integer.
String (long long signed int i)
Constructor from an unsigned integer.
String (float f, bool full_precision=true)
Constructor from float (full_precision controls number of fractional digits, 3 digits when false, and 6 when true)
String (double d, bool full_precision=true)
Constructor from double (full_precision controls number of fractional digits, 3 digits when false, and 15 when true)
String (long double ld, bool full_precision=true)
Constructor from long double (full_precision controls number of fractional digits, 3 digits when false, and 15 when true)
String (const DataValue &d, bool full_precision=true)
Constructor from DataValue (full_precision controls number of fractional digits for all double types or lists of double, 3 digits when false, and 15 when true)
Predicates
bool hasPrefix (const String &string) const
true if String begins with string, false otherwise
bool hasSuffix (const String &string) const
true if String ends with string, false otherwise
bool hasSubstring (const String &string) const
true if String contains the string, false otherwise
bool has (Byte byte) const
true if String contains the byte, false otherwise
String & operator= (const String &)=default
Assignment operator.
String & operator= (String &&) &=default
Move assignment operator.
Accessors
String prefix (SizeType length) const
returns the prefix of length length
String suffix (SizeType length) const
returns the suffix of length length
String prefix (Int length) const
returns the prefix of length length
String suffix (Int length) const
returns the suffix of length length
String prefix (char delim) const
returns the prefix up to the first occurrence of char delim (excluding it)
String suffix (char delim) const
returns the suffix up to the last occurrence of char delim (excluding it)
String substr (size_t pos=0, size_t n=npos) const
Wrapper for the STL substr() method. Returns a String object with its contents initialized to a substring of the current object.
String chop (Size n) const
Returns a substring where n characters were removed from the end of the string.
Mutators
All these methods return a reference to the string in order to make them chainable
String & reverse ()
inverts the direction of the string
String & trim ()
removes whitespaces (space, tab, line feed, carriage return) at the beginning and the end of the string
String & quote (char q='"', QuotingMethod method = ESCAPE)
Wraps the string in quotation marks.
String & unquote (char q='"', QuotingMethod method = ESCAPE)
Reverses changes made by the quote method.
String & simplify ()
merges subsequent whitespaces to one blank character
String & fillLeft (char c, UInt size)
Adds c on the left side until the size of the string is size.
String & fillRight (char c, UInt size)
Adds c on the right side until the size of the string is size.
String & toUpper ()
Converts the string to uppercase.
String & toLower ()
Converts the string to lowercase.
String & firstToUpper ()
Converts the first letter of the string to uppercase.
String & substitute (char from, char to)
Replaces all occurrences of the character from by the character to.
String & substitute (const String &from, const String &to)
Replaces all occurrences of the string from by the string to.
String & remove (char what)
Remove all occurrences of the character what.
String & ensureLastChar (char end)
Makes sure the string ends with the character end.
String & removeWhitespaces ()
removes whitespaces (space, tab, line feed, carriage return)
Converters
Int toInt () const
Conversion to int.
float toFloat () const
Conversion to float.
double toDouble () const
Conversion to double.
QString toQString () const
Conversion to Qt QString.
Sum operator overloads
String operator+ (int i) const
Sum operator for an integer.
String operator+ (unsigned int i) const
Sum operator for an unsigned integer.
String operator+ (short int i) const
Sum operator for an integer.
String operator+ (short unsigned int i) const
Sum operator for an unsigned integer.
String operator+ (long int i) const
Sum operator for an integer.
String operator+ (long unsigned int i) const
Sum operator for an unsigned integer.
String operator+ (long long unsigned int i) const
Sum operator for an unsigned integer.
String operator+ (float f) const
Sum operator for float.
String operator+ (double d) const
Sum operator for double.
String operator+ (long double ld) const
Sum operator for long double.
String operator+ (char c) const
Sum operator for char.
String operator+ (const char *s) const
Sum operator for char*.
String operator+ (const String &s) const
Sum operator for String.
String operator+ (const std::string &s) const
Sum operator for std::string.
Static Public Attributes
static const String EMPTY
Empty string for comparisons.
Append operator overloads
String & operator+= (int i)
Sum operator for an integer.
String & operator+= (unsigned int i)
Sum operator for an unsigned integer.
String & operator+= (short int i)
Sum operator for an integer.
String & operator+= (short unsigned int i)
Sum operator for an unsigned integer.
String & operator+= (long int i)
Sum operator for an integer.
String & operator+= (long unsigned int i)
Sum operator for an unsigned integer.
String & operator+= (long long unsigned int i)
Sum operator for an unsigned integer.
String & operator+= (float f)
Sum operator for float.
String & operator+= (double d)
Sum operator for double.
String & operator+= (long double d)
Sum operator for long double.
String & operator+= (char c)
Sum operator for char.
String & operator+= (const char *s)
Sum operator for char*.
String & operator+= (const String &s)
Sum operator for String.
String & operator+= (const std::string &s)
Sum operator for std::string.
bool split (const char splitter, std::vector< String > &substrings, bool quote_protect=false) const
Splits a string into substrings using splitter as delimiter.
bool split (const String &splitter, std::vector< String > &substrings) const
Splits a string into substrings using splitter (the whole string) as delimiter.
bool split_quoted (const String &splitter, std::vector< String > &substrings, char q='"', QuotingMethod method = ESCAPE) const
Splits a string into substrings using splitter (the whole string) as delimiter, but does not split within quoted substrings.
template<class StringIterator >
void concatenate (StringIterator first, StringIterator last, const String &glue="")
Concatenates all elements from first to last-1 and inserts glue between the elements.
static String random (UInt length)
returns a random string of the given length. It consists of [0-9a-zA-Z]
static String number (double d, UInt n)
returns a string for d with exactly n decimal places
static String numberLength (double d, UInt n)
Returns a string with at maximum n characters for d.
Detailed Description
A more convenient string class.
It is based on std::string but adds a lot of methods for convenience.
Member Typedef Documentation
ConstIterator
typedef const_iterator ConstIterator
Const Iterator.
ConstReverseIterator
typedef const_reverse_iterator ConstReverseIterator
Const reverse Iterator.
Iterator
typedef iterator Iterator
Iterator.
ReverseIterator
typedef reverse_iterator ReverseIterator
Reverse Iterator.
SizeType
typedef size_type SizeType
UInt type.
Member Enumeration Documentation
QuotingMethod
enum QuotingMethod
How to handle embedded quotes when quoting strings.
Enumerator
NONE
ESCAPE
DOUBLE
Constructor & Destructor Documentation
String() [1/22]
String ()
Default constructor.
String() [2/22]
String (const String &) default
Copy constructor.
String() [3/22]
String (String &&) default
Move constructor.
String() [4/22]
String (const std::string & s)
Constructor from std::string.
String() [5/22]
String (const QString & s)
Constructor from Qt QString.
String() [6/22]
String (const char * s)
Constructor from char*.
String() [7/22]
String (const char c)
Constructor from a char.
String() [8/22]
String (const char * s, SizeType length)
Constructor from char* (only length characters)
String() [9/22]
String (size_t len, char c)
Constructor from char (repeats the char len times)
String() [10/22]
String (InputIterator first, InputIterator last) inline
Constructor from a char range.
String() [11/22]
String (int i)
Constructor from an integer.
String() [12/22]
String (unsigned int i)
Constructor from an unsigned integer.
String() [13/22]
String (short int i)
Constructor from an integer.
String() [14/22]
String (short unsigned int i)
Constructor from an unsigned integer.
String() [15/22]
String (long int i)
Constructor from an integer.
String() [16/22]
String (long unsigned int i)
Constructor from an unsigned integer.
String() [17/22]
String (long long unsigned int i)
Constructor from an unsigned integer.
String() [18/22]
String (long long signed int i)
Constructor from an unsigned integer.
String() [19/22]
String (float f, bool full_precision = true)
Constructor from float (full_precision controls number of fractional digits, 3 digits when false, and 6 when true)
String() [20/22]
String (double d, bool full_precision = true)
Constructor from double (full_precision controls number of fractional digits, 3 digits when false, and 15 when true)
String() [21/22]
String (long double ld, bool full_precision = true)
Constructor from long double (full_precision controls number of fractional digits, 3 digits when false, and 15 when true)
String() [22/22]
String (const DataValue & d, bool full_precision = true)
Constructor from DataValue (full_precision controls number of fractional digits for all double types or lists of double, 3 digits when false, and 15 when true)
Member Function Documentation
chop()
String chop (Size n) const
Returns a substring where n characters were removed from the end of the string.
If n is greater than size(), the result is an empty string.
Parameters
n Number of characters that will be removed from the end of the string.
concatenate()
void concatenate (StringIterator first, StringIterator last, const String & glue = "") inline
Concatenates all elements from first to last-1 and inserts glue between the elements.
See also
split().
Referenced by MetaProSIPReporting::plotFilteredSpectra(), MetaProSIPReporting::plotHeatMap(), MetaProSIPReporting::plotScoresAndWeights(), and StringUtils::substitute().
ensureLastChar()
String& ensureLastChar (char end)
Makes sure the string ends with the character end.
fillLeft()
String& fillLeft (char c, UInt size)
Adds c on the left side until the size of the string is size.
fillRight()
String& fillRight (char c, UInt size)
Adds c on the right side until the size of the string is size.
firstToUpper()
String& firstToUpper ()
Converts the first letter of the string to uppercase.
has()
bool has (Byte byte) const
true if String contains the byte, false otherwise
Referenced by DTAFile::load(), DTA2DFile::load(), PeptideIndexing::run(), and XMLHandler::writeXMLEscape().
hasPrefix()
bool hasPrefix (const String & string) const
true if String begins with string, false otherwise
Referenced by XMLHandler::expectList_(), MascotGenericFile::getNextSpectrum_(), XMassFile::load(), DTA2DFile::load(), and PeptideIndexing::run().
hasSubstring()
bool hasSubstring (const String & string) const
true if String contains the string, false otherwise
Referenced by MascotGenericFile::getNextSpectrum_(), XFDRAlgorithm::isSameProtein_(), and main().
hasSuffix()
bool hasSuffix (const String & string) const
true if String ends with string, false otherwise
Referenced by StringUtils::ensureLastChar(), XMLHandler::expectList_(), XMassFile::load(), TOPPOpenSwathBase::prepareChromOutput(), PeptideIndexing::run(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
number()
static String number (double d, UInt n) static
returns a string for d with exactly n decimal places
Referenced by MetaProSIPReporting::createCSVReport(), MetaProSIPReporting::createPeptideCentricCSVReport(), TOPPViewBase::showCursorStatus(), and MetaProSIPReporting::writeHTML().
numberLength()
static String numberLength (double d, UInt n) static
Returns a string with at maximum n characters for d.
If d is larger, scientific notation is used.
operator+() [1/14]
String operator+ (char c) const
Sum operator for char.
operator+() [2/14]
String operator+ (const char * s) const
Sum operator for char*.
operator+() [3/14]
String operator+ (const std::string & s) const
Sum operator for std::string.
operator+() [4/14]
String operator+ (const String & s) const
Sum operator for String.
operator+() [5/14]
String operator+ (double d) const
Sum operator for double.
operator+() [6/14]
String operator+ (float f) const
Sum operator for float.
operator+() [7/14]
String operator+ (int i) const
Sum operator for an integer.
operator+() [8/14]
String operator+ (long double ld) const
Sum operator for long double.
operator+() [9/14]
String operator+ (long int i) const
Sum operator for an integer.
operator+() [10/14]
String operator+ (long long unsigned int i) const
Sum operator for an unsigned integer.
operator+() [11/14]
String operator+ (long unsigned int i) const
Sum operator for an unsigned integer.
operator+() [12/14]
String operator+ (short int i) const
Sum operator for an integer.
operator+() [13/14]
String operator+ (short unsigned int i) const
Sum operator for an unsigned integer.
operator+() [14/14]
String operator+ (unsigned int i) const
Sum operator for an unsigned integer.
operator+=() [1/14]
String& operator+= (char c)
Sum operator for char.
operator+=() [2/14]
String& operator+= (const char * s)
Sum operator for char*.
operator+=() [3/14]
String& operator+= (const std::string & s)
Sum operator for std::string.
operator+=() [4/14]
String& operator+= (const String & s)
Sum operator for String.
operator+=() [5/14]
String& operator+= (double d)
Sum operator for double.
operator+=() [6/14]
String& operator+= (float f)
Sum operator for float.
operator+=() [7/14]
String& operator+= (int i)
Sum operator for an integer.
operator+=() [8/14]
String& operator+= (long double d)
Sum operator for long double.
operator+=() [9/14]
String& operator+= (long int i)
Sum operator for an integer.
operator+=() [10/14]
String& operator+= (long long unsigned int i)
Sum operator for an unsigned integer.
operator+=() [11/14]
String& operator+= (long unsigned int i)
Sum operator for an unsigned integer.
operator+=() [12/14]
String& operator+= (short int i)
Sum operator for an integer.
operator+=() [13/14]
String& operator+= (short unsigned int i)
Sum operator for an unsigned integer.
operator+=() [14/14]
String& operator+= (unsigned int i)
Sum operator for an unsigned integer.
operator=() [1/2]
String& operator= (const String &) default
Assignment operator.
operator=() [2/2]
String& operator= (String &&) & default
Move assignment operator.
prefix() [1/3]
String prefix (char delim) const
returns the prefix up to the first occurrence of char delim (excluding it)
Exceptions
Exception::ElementNotFound is thrown if delim is not found
prefix() [2/3]
String prefix (Int length) const
returns the prefix of length length
Exceptions
Exception::IndexUnderflow is thrown if length is smaller than zero
Exception::IndexOverflow is thrown if length is bigger than the size
prefix() [3/3]
String prefix (SizeType length) const
returns the prefix of length length
Exceptions
Exception::IndexOverflow is thrown if length is bigger than the size
Referenced by OpenSwathHelper::computeTransitionGroupId(), XMassFile::importExperimentalSettings(), XMassFile::load(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and StringUtils::split().
quote()
String& quote (char q = '"', QuotingMethod method = ESCAPE)
Wraps the string in quotation marks.
The quotation mark can be specified by parameter q (typically single or double quote); embedded quotation marks are handled according to method by backslash-escaping, doubling, or not at all.
See also
unquote()
Referenced by PeptideHit::PeakAnnotation::writePeakAnnotationsString_().
random()
static String random (UInt length) static
returns a random string of the given length. It consists of [0-9a-zA-Z]
Referenced by RIntegration::checkRDependencies().
remove()
String& remove (char what)
Remove all occurrences of the character what.
Referenced by MascotGenericFile::getNextSpectrum_(), NucleicAcidSearchEngine::registerOptionsAndFlags_(), and PeptideIndexing::run().
removeWhitespaces()
String& removeWhitespaces ()
removes whitespaces (space, tab, line feed, carriage return)
reverse()
String& reverse ()
inverts the direction of the string
simplify()
String& simplify ()
merges subsequent whitespaces to one blank character
Referenced by MascotGenericFile::getNextSpectrum_(), and MS2File::load().
split() [1/2]
bool split (const char splitter, std::vector< String > & substrings, bool quote_protect = false) const
Splits a string into substrings using splitter as delimiter.
If splitter is not found, the whole string is put into substrings. If splitter is empty, the string is split into individual characters. If the invoking string is empty, substrings will also be empty.
quote_protect (default: false) can be used to split only between quoted blocks e.g. ' "a string" , "another string with , in it" ' results in only two substrings (with double quotation marks removed). Every returned substring is trimmed and then (if present) has surrounding quotation marks removed.
Returns
true if one or more splits occurred, false otherwise
See also
concatenate().
Referenced by OpenSwathHelper::computeTransitionGroupId(), ListUtils::create(), extractCachedMetaFilename(), MascotGenericFile::getNextSpectrum_(), MS2File::load(), MsInspectFile::load(), SpecArrayFile::load(), DTAFile::load(), DTA2DFile::load(), NucleicAcidSearchEngine::parseAdduct_(), DigestionEnzymeDB< DigestionEnzymeRNA, RNaseDB >::readEnzymesFromFile_(), and StringUtils::substitute().
split() [2/2]
bool split (const String & splitter, std::vector< String > & substrings) const
Splits a string into substrings using splitter (the whole string) as delimiter.
If splitter is not found, the whole string is put into substrings. If splitter is empty, the string is split into individual characters. If the invoking string is empty, substrings will also be empty.
Returns
true if one or more splits occurred, false otherwise
See also
concatenate().
split_quoted()
bool split_quoted (const String & splitter, std::vector< String > & substrings, char q = '"', QuotingMethod method = ESCAPE) const
Splits a string into substrings using splitter (the whole string) as delimiter, but does not split within quoted substrings.
A "quoted substring" has the format as produced by quote(q, method), where q is the quoting character and method defines the handling of embedded quotes. Substrings will not be "unquoted" or otherwise processed.
If splitter is not found, the whole string is put into substrings. If splitter or the invoking string is empty, substrings will also be empty.
Returns
true if one or more splits occurred, false otherwise
Exceptions
Exception::ConversionError is thrown if quotation marks are not balanced
See also
concatenate(), quote().
substitute() [1/2]
String& substitute (char from, char to)
Replaces all occurrences of the character from by the character to.
Referenced by MascotGenericFile::getNextSpectrum_(), XFDRAlgorithm::isSameProtein_(), StringUtils::quote(), PeptideIndexing::run(), StringUtils::unquote(), and XMLHandler::writeXMLEscape().
substitute() [2/2]
String& substitute (const String & from, const String & to)
Replaces all occurrences of the string from by the string to.
substr()
String substr (size_t pos = 0, size_t n = npos) const
Wrapper for the STL substr() method. Returns a String object with its contents initialized to a substring of the current object.
Parameters
pos Position of a character in the current string object to be used as starting character for the substring. If the pos is past the end of the string, it is set to the end of the string.
n Length of the substring. If this value would make the substring to span past the end of the current string content, only those characters until the end of the string are used. npos is a static member constant value with the greatest possible value for an element of type size_t, therefore, when this value is used, all the characters between pos and the end of the string are used as the initialization substring.
Referenced by XMLHandler::asDateTime_(), XMLHandler::attributeAsDoubleList_(), XMLHandler::attributeAsIntList_(), XMLHandler::attributeAsStringList_(), MascotGenericFile::getNextSpectrum_(), DTA2DFile::load(), StringUtils::prefix(), PeptideIndexing::run(), StringUtils::split(), StringUtils::split_quoted(), StringUtils::suffix(), and StringUtils::unquote().
suffix() [1/3]
String suffix (char delim) const
returns the suffix up to the last occurrence of char delim (excluding it)
Exceptions
Exception::ElementNotFound is thrown if delim is not found
suffix() [2/3]
String suffix (Int length) const
returns the suffix of length length
Exceptions
Exception::IndexUnderflow is thrown if length is smaller than zero
Exception::IndexOverflow is thrown if length is bigger than the size
suffix() [3/3]
String suffix (SizeType length) const
returns the suffix of length length
Exceptions
Exception::IndexOverflow is thrown if length is bigger than the size
Referenced by XMassFile::load(), and StringUtils::split().
toDouble()
double toDouble () const
Conversion to double.
Exceptions
Exception::ConversionError is thrown if the string could not be converted to double
Referenced by XMLHandler::asDouble_(), OpenMS::detail::convert(), DBsearchDeconvMass::getMassesFromUNIMOD(), and MascotGenericFile::getNextSpectrum_().
toFloat()
float toFloat () const
Conversion to float.
Exceptions
Exception::ConversionError is thrown if the string could not be converted to float
Referenced by XMLHandler::asFloat_(), and OpenMS::detail::convert().
toInt()
Int toInt () const
Conversion to int.
This method extracts only the integral part of the string. If you want the result rounded, use toFloat() and round the result.
Exceptions
Exception::ConversionError is thrown if the string could not be converted to int
Referenced by XMLHandler::asInt_(), XMLHandler::asUInt_(), OpenMS::detail::convert(), and MascotGenericFile::getNextSpectrum_().
toLower()
String& toLower ()
Converts the string to lowercase.
Referenced by DigestionEnzymeDB< DigestionEnzymeRNA, RNaseDB >::addEnzyme_(), ListUtils::contains(), Epifany::convertPSMScores_(), DecoyHelper::findDecoyString(), and TOPPOpenSwathBase::prepareChromOutput().
toQString()
QString toQString () const
Conversion to Qt QString.
Referenced by FileWatcher::addFile(), TOPPViewBase::addRecentFile_(), TOPPASBase::addTOPPASFile(), TOPPViewBase::annotateWithID(), RIntegration::checkRDependencies(), TOPPASBase::createTOPPToolsTreeWidget(), TOPPASBase::exportAsImage(), TOPPViewBase::fileChanged_(), TOPPViewBase::filterContextMenu(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::getFileList_(), TOPPASBase::includePipeline(), TOPPViewBase::layerContextMenu(), TOPPASBase::loadPipelineResourceFile(), TOPPViewBase::loadPreferences(), INIFileEditorWindow::openFile(), TOPPASBase::openFileDialog(), MetaProSIPReporting::plotFilteredSpectra(), MetaProSIPReporting::plotHeatMap(), MetaProSIPReporting::plotScoresAndWeights(), QApplicationTOPP::QApplicationTOPP(), TOPPASBase::refreshParameters(), FileWatcher::removeFile(), TOPPViewBase::runTOPPTool_(), TOPPASBase::saveCurrentPipelineAs(), INIFileEditorWindow::saveFileAs(), TOPPASBase::savePipeline(), TOPPASBase::savePipelineAs(), TOPPASBase::savePipelineResourceFile(), TOPPASBase::showAsWindow_(), TOPPASBase::showLogMessage_(), TOPPViewBase::showLogMessage_(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPASBase::TOPPASBase(), TOPPViewBase::updateLayerBar(), and MetaProSIPReporting::writeHTML().
toUpper()
String& toUpper ()
Converts the string to uppercase.
Referenced by MetaProSIPReporting::createCSVReport(), and MetaProSIPReporting::createPeptideCentricCSVReport().
trim()
String& trim ()
removes whitespaces (space, tab, line feed, carriage return) at the beginning and the end of the string
Referenced by XMLHandler::asDateTime_(), ListUtils::create(), MetaProSIPReporting::createCSVReport(), MetaProSIPReporting::createPeptideCentricCSVReport(), MascotGenericFile::getNextSpectrum_(), MS2File::load(), DTAFile::load(), DTA2DFile::load(), and StringUtils::split().
unquote()
String& unquote (char q = '"', QuotingMethod method = ESCAPE)
Reverses changes made by the quote method.
Removes surrounding quotation marks (given by parameter q); handles embedded quotes according to method.
Exceptions
Exception::ConversionError is thrown if the string does not have the format produced by quote
See also
quote()
Member Data Documentation
EMPTY
const String EMPTY static
Empty string for comparisons.