OpenMS: MassTraceDetection Class Reference
MassTraceDetection Class Reference
A mass trace extraction method that gathers peaks similar in m/z and moving along retention time.
#include <OpenMS/FILTERING/DATAREDUCTION/MassTraceDetection.h>
Public Member Functions
MassTraceDetection ()
Default constructor.
~MassTraceDetection () override
Default destructor.
Helper methods
void updateIterativeWeightedMeanMZ (const double &, const double &, double &, double &, double &)
Allows the iterative computation of the intensity-weighted mean of a mass trace's centroid m/z.
Main computation methods
void run (const PeakMap &, std::vector< MassTrace > &, const Size max_traces=0)
Main method of MassTraceDetection. Extracts mass traces of a MSExperiment and gathers them into a vector container.
void run (PeakMap::ConstAreaIterator &begin, PeakMap::ConstAreaIterator &end, std::vector< MassTrace > &found_masstraces)
Invokes the run method (see above) on merely a subregion of a MSExperiment map.
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Private methods and members
typedef std::multimap< double, std::pair< Size, Size > > MapIdxSortedByInt
double mass_error_ppm_
double mass_error_da_
double noise_threshold_int_
double chrom_peak_snr_
MassTrace::MT_QUANTMETHOD quant_method_
String trace_termination_criterion_
Size trace_termination_outliers_
double min_sample_rate_
double min_trace_length_
double max_trace_length_
bool reestimate_mt_sd_
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
void run_ (const MapIdxSortedByInt &chrom_apices, const Size peak_count, const PeakMap &work_exp, const std::vector< Size > &spec_offsets, std::vector< MassTrace > &found_masstraces, const Size max_traces=0)
The internal run method.
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Protected Member Functions inherited from DefaultParamHandler
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
A mass trace extraction method that gathers peaks similar in m/z and moving along retention time.
Peaks of a MSExperiment are sorted by their intensity and stored in a list of potential chromatographic apex positions. Only peaks that are above the noise threshold (user-defined) are analyzed and only peaks that are n times above this minimal threshold are considered as apices. This saves computational resources and decreases the noise in the resulting output.
Starting with these, mass traces are extended in- and decreasingly in retention time. During this extension phase, the centroid m/z is computed on-line as an intensity-weighted mean of peaks.
The extension phase ends when either the frequency of gathered peaks drops below a threshold (min_sample_rate, see MassTraceDetection parameters) or when the number of missed scans exceeds a threshold (trace_termination_outliers, see MassTraceDetection parameters).
Finally, only mass traces that pass a filter (a certain minimal and maximal length as well as having the minimal sample rate criterion fulfilled) get added to the result.
Member Typedef Documentation
MapIdxSortedByInt
typedef std::multimap<double, std::pair<Size, Size> > MapIdxSortedByInt private
Constructor & Destructor Documentation
MassTraceDetection()
MassTraceDetection ()
Default constructor.
~MassTraceDetection()
~MassTraceDetection () override
Default destructor.
Member Function Documentation
run() [1/2]
void run (const PeakMap & , std::vector< MassTrace > & , const Size max_traces = 0)
Main method of MassTraceDetection. Extracts mass traces of a MSExperiment and gathers them into a vector container.
Referenced by UTILProteomicsLFQ::estimateMedianChromatographicFWHM_(), FLASHDeconv::findFeatures(), and TDfeatureDeconvolution::main_().
run() [2/2]
void run (PeakMap::ConstAreaIterator & begin, PeakMap::ConstAreaIterator & end, std::vector< MassTrace > & found_masstraces)
Invokes the run method (see above) on merely a subregion of a MSExperiment map.
run_()
void run_ (const MapIdxSortedByInt & chrom_apices, const Size peak_count, const PeakMap & work_exp, const std::vector< Size > & spec_offsets, std::vector< MassTrace > & found_masstraces, const Size max_traces = 0) private
The internal run method.
updateIterativeWeightedMeanMZ()
void updateIterativeWeightedMeanMZ (const double & , const double & , double & , double & , double &)
Allows the iterative computation of the intensity-weighted mean of a mass trace's centroid m/z.
updateMembers_()
void updateMembers_ () override protected virtual
This method is used to update extra member variables at the end of the setParameters() method.
Also call it at the end of the derived classes' copy constructor and assignment operator.
The default implementation is empty.
Reimplemented from DefaultParamHandler.
Member Data Documentation
chrom_peak_snr_
double chrom_peak_snr_ private
mass_error_da_
double mass_error_da_ private
mass_error_ppm_
double mass_error_ppm_ private
max_trace_length_
double max_trace_length_ private
min_sample_rate_
double min_sample_rate_ private
min_trace_length_
double min_trace_length_ private
noise_threshold_int_
double noise_threshold_int_ private
quant_method_
MassTrace::MT_QUANTMETHOD quant_method_ private
reestimate_mt_sd_
bool reestimate_mt_sd_ private
trace_termination_criterion_
String trace_termination_criterion_ private
trace_termination_outliers_
Size trace_termination_outliers_ private