OpenMS: IDFilter::PeptideDigestionFilter Class Reference
IDFilter::PeptideDigestionFilter Class Reference
Filter Peptide Hit by its digestion product.
#include <OpenMS/FILTERING/ID/IDFilter.h>
Public Types
typedef PeptideHit argument_type
Public Member Functions
PeptideDigestionFilter (EnzymaticDigestion &digestion, Int min, Int max)
bool operator() (PeptideHit &p)
void filterPeptideSequences (std::vector< PeptideHit > &hits)
Static Public Member Functions
static Int disabledValue ()
Private Attributes
EnzymaticDigestion & digestion_
Int min_cleavages_
Int max_cleavages_
Detailed Description
Filter Peptide Hit by its digestion product.
Member Typedef Documentation
argument_type
typedef PeptideHit argument_type
Constructor & Destructor Documentation
PeptideDigestionFilter()
PeptideDigestionFilter (EnzymaticDigestion & digestion, Int min, Int max) inline
Member Function Documentation
disabledValue()
static Int disabledValue () inline static
filterPeptideSequences()
void filterPeptideSequences (std::vector< PeptideHit > & hits) inline
operator()()
bool operator() (PeptideHit & p) inline
Filter function on min max cutoff values to be used with remove_if returns true if peptide should be removed (does not pass filter)
References EnzymaticDigestion::filterByMissedCleavages(), PeptideHit::getSequence(), and AASequence::toUnmodifiedString().
Member Data Documentation
digestion_
EnzymaticDigestion& digestion_ private
max_cleavages_
Int max_cleavages_ private
min_cleavages_
Int min_cleavages_ private