OpenMS: ComplementFilter Class Reference
ComplementFilter Class Reference
Spectrum filters » Spectra Filters
total intensity of peak pairs that could result from complementing fragments of charge state 1
#include <OpenMS/FILTERING/TRANSFORMERS/ComplementFilter.h>
Public Member Functions
ComplementFilter ()
standard constructor
ComplementFilter (const ComplementFilter &source)
copy constructor
~ComplementFilter () override
destructor
ComplementFilter & operator= (const ComplementFilter &source)
assignment operator
template<typename SpectrumType >
double apply (SpectrumType &spectrum)
returns the total intensity of peak pairs which could result from complementing fragments
Public Member Functions inherited from FilterFunctor
FilterFunctor ()
default constructor
FilterFunctor (const FilterFunctor &source)
copy constructor
~FilterFunctor () override
destructor
FilterFunctor & operator= (const FilterFunctor &source)
assignment operator
template<typename SpectrumType >
double apply (SpectrumType &)
function call operator
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Static Public Member Functions
static FilterFunctor * create ()
static const String getProductName ()
returns the name for registration at the factory
Static Public Member Functions inherited from FilterFunctor
static void registerChildren ()
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
total intensity of peak pairs that could result from complementing fragments of charge state 1
Parameters of this class are:
Name Type Default Restrictions Description
tolerance float 0.37 Tolerance value as defined by Bern et al.
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Constructor & Destructor Documentation
ComplementFilter() [1/2]
ComplementFilter ()
standard constructor
ComplementFilter() [2/2]
ComplementFilter (const ComplementFilter & source)
copy constructor
~ComplementFilter()
~ComplementFilter () override
destructor
Member Function Documentation
apply()
double apply (SpectrumType & spectrum) inline
returns the total intensity of peak pairs which could result from complementing fragments
Improvement:
think about an correct fast algorithm, not just an heuristic (Andreas)
References SpectrumSettings::getPrecursors(), MSSpectrum::sortByPosition(), and OpenMS::Math::sum().
create()
static FilterFunctor* create () inline static
getProductName()
static const String getProductName () inline static
returns the name for registration at the factory
operator=()
ComplementFilter& operator= (const ComplementFilter & source)
assignment operator