OpenMS: SignalToNoiseEstimator< Container > Class Template Reference
SignalToNoiseEstimator< Container > Class Template Reference abstract
This class represents the abstract base class of a signal to noise estimator.
#include <OpenMS/FILTERING/NOISEESTIMATION/SignalToNoiseEstimator.h>
Classes
struct GaussianEstimate
protected struct to store parameters my, sigma for a Gaussian distribution
Type definitions
typedef Container::const_iterator PeakIterator
typedef PeakIterator::value_type PeakType
std::map< PeakType, double, typename PeakType::PositionLess > stn_estimates_
stores the noise estimate for each peak
PeakIterator first_
points to the first raw data point in the interval
PeakIterator last_
points to the right position next to the last raw data point in the interval
bool is_result_valid_
flag: set to true if SignalToNoise estimates are calculated and none of the params were changed. otherwise false.
SignalToNoiseEstimator ()
Constructor.
SignalToNoiseEstimator (const SignalToNoiseEstimator &source)
Copy constructor.
SignalToNoiseEstimator & operator= (const SignalToNoiseEstimator &source)
Assignment operator.
~SignalToNoiseEstimator () override
Destructor.
virtual void init (const PeakIterator &it_begin, const PeakIterator &it_end)
Set the start and endpoint of the raw data interval, for which signal to noise ratios will be estimated immediately.
virtual void init (const Container &c)
Set the start and endpoint of the raw data interval, for which signal to noise ratios will be estimated immediately.
virtual double getSignalToNoise (const PeakIterator &data_point)
virtual double getSignalToNoise (const PeakType &data_point)
virtual void computeSTN_ (const PeakIterator &scan_first_, const PeakIterator &scan_last_)=0
computes the S/N values when init() is called
GaussianEstimate estimate_ (const PeakIterator &scan_first_, const PeakIterator &scan_last_) const
calculate mean & stdev of intensities of a spectrum
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
template<typename Container = MSSpectrum>
class OpenMS::SignalToNoiseEstimator< Container >
This class represents the abstract base class of a signal to noise estimator.
A signal to noise estimator should provide the signal to noise ratio of all raw data points in a given interval [first_,last_).
Class Documentation
OpenMS::SignalToNoiseEstimator::GaussianEstimate
struct OpenMS::SignalToNoiseEstimator::GaussianEstimate
template<typename Container = MSSpectrum>
struct OpenMS::SignalToNoiseEstimator< Container >::GaussianEstimate
protected struct to store parameters my, sigma for a Gaussian distribution
Accessors are : mean and variance
Class Members
double mean mean of estimated Gaussian
double variance variance of estimated Gaussian
Member Typedef Documentation
PeakIterator
typedef Container::const_iterator PeakIterator
PeakType
typedef PeakIterator::value_type PeakType
Constructor & Destructor Documentation
SignalToNoiseEstimator() [1/2]
SignalToNoiseEstimator () inline
Constructor.
SignalToNoiseEstimator() [2/2]
SignalToNoiseEstimator (const SignalToNoiseEstimator< Container > & source) inline
Copy constructor.
~SignalToNoiseEstimator()
~SignalToNoiseEstimator () inline override
Destructor.
Member Function Documentation
computeSTN_()
virtual void computeSTN_ (const PeakIterator & scan_first_, const PeakIterator & scan_last_) protected pure virtual
computes the S/N values when init() is called
Exceptions
Throws Exception::InvalidValue
Implemented in SignalToNoiseEstimatorMedian< Container >, SignalToNoiseEstimatorMedian< OpenMS::MSChromatogram >, SignalToNoiseEstimatorMedian< ContainerT >, and SignalToNoiseEstimatorMeanIterative< Container >.
Referenced by SignalToNoiseEstimator< ContainerT >::init().
estimate_()
GaussianEstimate estimate_ (const PeakIterator & scan_first_, const PeakIterator & scan_last_) const inline protected
calculate mean & stdev of intensities of a spectrum
Referenced by SignalToNoiseEstimatorMeanIterative< Container >::computeSTN_(), and SignalToNoiseEstimatorMedian< ContainerT >::computeSTN_().
getSignalToNoise() [1/2]
virtual double getSignalToNoise (const PeakIterator & data_point) inline virtual
Return to signal/noise estimate for data point data_point
Note
the first query to this function will take longer, as all SignalToNoise values are calculated
you will get a warning to stderr if more than 20% of the noise estimates used sparse windows
Referenced by SignalToNoiseOpenMS< ContainerT >::getValueAtRT(), and PeakPickerIterative::pickRecenterPeaks_().
getSignalToNoise() [2/2]
virtual double getSignalToNoise (const PeakType & data_point) inline virtual
init() [1/2]
virtual void init (const Container & c) inline virtual
Set the start and endpoint of the raw data interval, for which signal to noise ratios will be estimated immediately.
init() [2/2]
virtual void init (const PeakIterator & it_begin, const PeakIterator & it_end) inline virtual
Set the start and endpoint of the raw data interval, for which signal to noise ratios will be estimated immediately.
Referenced by SignalToNoiseEstimator< ContainerT >::getSignalToNoise(), SignalToNoiseEstimator< ContainerT >::init(), and SignalToNoiseOpenMS< ContainerT >::SignalToNoiseOpenMS().
operator=()
SignalToNoiseEstimator& operator= (const SignalToNoiseEstimator< Container > & source) inline
Assignment operator.
Member Data Documentation
first_
PeakIterator first_ protected
points to the first raw data point in the interval
Referenced by SignalToNoiseEstimator< ContainerT >::getSignalToNoise(), SignalToNoiseEstimator< ContainerT >::init(), and SignalToNoiseEstimator< ContainerT >::operator=().
is_result_valid_
bool is_result_valid_ mutable protected
flag: set to true if SignalToNoise estimates are calculated and none of the params were changed. otherwise false.
Referenced by SignalToNoiseEstimator< ContainerT >::getSignalToNoise(), SignalToNoiseEstimator< ContainerT >::init(), SignalToNoiseEstimatorMeanIterative< Container >::updateMembers_(), and SignalToNoiseEstimatorMedian< ContainerT >::updateMembers_().
last_
PeakIterator last_ protected
points to the right position next to the last raw data point in the interval
Referenced by SignalToNoiseEstimator< ContainerT >::getSignalToNoise(), SignalToNoiseEstimator< ContainerT >::init(), and SignalToNoiseEstimator< ContainerT >::operator=().
stn_estimates_
std::map<PeakType, double, typename PeakType::PositionLess> stn_estimates_ protected
stores the noise estimate for each peak
Referenced by SignalToNoiseEstimatorMeanIterative< Container >::computeSTN_(), SignalToNoiseEstimatorMedian< ContainerT >::computeSTN_(), SignalToNoiseEstimator< ContainerT >::getSignalToNoise(), and SignalToNoiseEstimator< ContainerT >::operator=().