OpenMS: IDFilter::HasMatchingAccessionUnordered< HitType > Struct Template Reference
IDFilter::HasMatchingAccessionUnordered< HitType > Struct Template Reference
Given a list of protein accessions, do any occur in the annotation(s) of this hit?
#include <OpenMS/FILTERING/ID/IDFilter.h>
Public Types
typedef HitType argument_type
Public Member Functions
HasMatchingAccessionUnordered (const std::unordered_set< String > &accessions_)
bool operator() (const PeptideHit &hit) const
bool operator() (const ProteinHit &hit) const
bool operator() (const PeptideEvidence &evidence) const
Public Attributes
const std::unordered_set< String > & accessions
Detailed Description
template<class HitType>
struct OpenMS::IDFilter::HasMatchingAccessionUnordered< HitType >
Given a list of protein accessions, do any occur in the annotation(s) of this hit?
Note
This predicate also works for peptide evidence (class PeptideEvidence).
Member Typedef Documentation
argument_type
typedef HitType argument_type
Constructor & Destructor Documentation
HasMatchingAccessionUnordered()
HasMatchingAccessionUnordered (const std::unordered_set< String > & accessions_) inline
Member Function Documentation
operator()() [1/3]
bool operator() (const PeptideEvidence & evidence) const inline
References PeptideEvidence::getProteinAccession().
operator()() [2/3]
bool operator() (const PeptideHit & hit) const inline
References PeptideHit::extractProteinAccessionsSet().
operator()() [3/3]
bool operator() (const ProteinHit & hit) const inline
References ProteinHit::getAccession().
Member Data Documentation
accessions
const std::unordered_set<String>& accessions