OpenMS: IDFilter::DigestionFilter Struct Reference
IDFilter::DigestionFilter Struct Reference
Is peptide evidence digestion product of some protein.
#include <OpenMS/FILTERING/ID/IDFilter.h>
Public Types
typedef PeptideEvidence argument_type
Public Member Functions
DigestionFilter (std::vector< FASTAFile::FASTAEntry > &entries, ProteaseDigestion &digestion, bool ignore_missed_cleavages, bool methionine_cleavage)
bool operator() (const PeptideEvidence &evidence) const
void filterPeptideEvidences (std::vector< PeptideIdentification > &peptides)
Public Attributes
GetMatchingItems< PeptideEvidence, FASTAFile::FASTAEntry > accession_resolver_
ProteaseDigestion & digestion_
bool ignore_missed_cleavages_
bool methionine_cleavage_
Detailed Description
Is peptide evidence digestion product of some protein.
Keeps all valid products
Member Typedef Documentation
argument_type
typedef PeptideEvidence argument_type
Constructor & Destructor Documentation
DigestionFilter()
DigestionFilter (std::vector< FASTAFile::FASTAEntry > & entries, ProteaseDigestion & digestion, bool ignore_missed_cleavages, bool methionine_cleavage) inline
Member Function Documentation
filterPeptideEvidences()
void filterPeptideEvidences (std::vector< PeptideIdentification > & peptides) inline
operator()()
bool operator() (const PeptideEvidence & evidence) const inline
References IDFilter::GetMatchingItems< HitType, Entry >::exists(), AASequence::fromString(), PeptideEvidence::getEnd(), PeptideEvidence::getProteinAccession(), PeptideEvidence::getStart(), IDFilter::GetMatchingItems< HitType, Entry >::getValue(), PeptideEvidence::hasValidLimits(), ProteaseDigestion::isValidProduct(), and OPENMS_LOG_WARN.
Member Data Documentation
accession_resolver_
GetMatchingItems<PeptideEvidence, FASTAFile::FASTAEntry> accession_resolver_
digestion_
ProteaseDigestion& digestion_
ignore_missed_cleavages_
bool ignore_missed_cleavages_
methionine_cleavage_
bool methionine_cleavage_