OpenMS: WindowMower Class Reference
WindowMower Class Reference
Spectrum filters » Spectra Preprocessors
WindowMower augments the highest peaks in a sliding or jumping window.
#include <OpenMS/FILTERING/TRANSFORMERS/WindowMower.h>
Public Member Functions
WindowMower ()
default constructor
~WindowMower () override
destructor
WindowMower (const WindowMower &source)
copy constructor
WindowMower & operator= (const WindowMower &source)
assignment operator
template<typename SpectrumType >
void filterPeakSpectrumForTopNInSlidingWindow (SpectrumType &spectrum)
sliding window version (slower)
void filterPeakSpectrum (PeakSpectrum &spectrum)
void filterPeakMap (PeakMap &exp)
template<typename SpectrumType >
void filterPeakSpectrumForTopNInJumpingWindow (SpectrumType &spectrum)
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Private Attributes
double windowsize_
UInt peakcount_
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
WindowMower augments the highest peaks in a sliding or jumping window.
Parameters of this class are:
Name Type Default Restrictions Description
windowsize float 50.0 The size of the sliding window along the m/z axis.
peakcount int 2 The number of peaks that should be kept.
movetype string slide slide, jump Whether sliding window (one peak steps) or jumping window (window size steps) should be used.
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Constructor & Destructor Documentation
WindowMower() [1/2]
WindowMower ()
default constructor
~WindowMower()
~WindowMower () override
destructor
WindowMower() [2/2]
WindowMower (const WindowMower & source)
copy constructor
Member Function Documentation
filterPeakMap()
void filterPeakMap (PeakMap & exp)
filterPeakSpectrum()
void filterPeakSpectrum (PeakSpectrum & spectrum)
Referenced by NucleicAcidSearchEngine::preprocessSpectra_().
filterPeakSpectrumForTopNInJumpingWindow()
void filterPeakSpectrumForTopNInJumpingWindow (SpectrumType & spectrum) inline
References MSSpectrum::clear(), seqan::find(), OpenMS::reverseComparator(), OpenMS::Math::round(), MSSpectrum::select(), and MSSpectrum::sortByPosition().
filterPeakSpectrumForTopNInSlidingWindow()
void filterPeakSpectrumForTopNInSlidingWindow (SpectrumType & spectrum) inline
sliding window version (slower)
References MSSpectrum::select(), MSSpectrum::sortByIntensity(), and MSSpectrum::sortByPosition().
operator=()
WindowMower& operator= (const WindowMower & source)
assignment operator
Member Data Documentation
peakcount_
UInt peakcount_ private
windowsize_
double windowsize_ private