OpenMS: NLargest Class Reference
NLargest Class Reference
Spectrum filters » Spectra Preprocessors
NLargest removes all but the n largest peaks.
#include <OpenMS/FILTERING/TRANSFORMERS/NLargest.h>
Public Member Functions
NLargest ()
default constructor
NLargest (UInt n)
detailed constructor
~NLargest () override
destructor
NLargest (const NLargest &source)
copy constructor
NLargest & operator= (const NLargest &source)
assignment operator
template<typename SpectrumType >
void filterSpectrum (SpectrumType &spectrum)
void filterPeakSpectrum (PeakSpectrum &spectrum)
void filterPeakMap (PeakMap &exp)
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Protected Member Functions
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
void init_ ()
handles the initialization of the default parameters for the 2 constructors
Protected Member Functions inherited from DefaultParamHandler
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes
UInt peakcount_
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
NLargest removes all but the n largest peaks.
Parameters of this class are:
Name Type Default Restrictions Description
n int 200 The number of peaks to keep
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Constructor & Destructor Documentation
NLargest() [1/3]
NLargest ()
default constructor
NLargest() [2/3]
NLargest (UInt n)
detailed constructor
~NLargest()
~NLargest () override
destructor
NLargest() [3/3]
NLargest (const NLargest & source)
copy constructor
Member Function Documentation
filterPeakMap()
void filterPeakMap (PeakMap & exp)
filterPeakSpectrum()
void filterPeakSpectrum (PeakSpectrum & spectrum)
Referenced by NucleicAcidSearchEngine::preprocessSpectra_().
filterSpectrum()
void filterSpectrum (SpectrumType & spectrum) inline
References MSSpectrum::select(), and MSSpectrum::sortByIntensity().
init_()
void init_ () protected
handles the initialization of the default parameters for the 2 constructors
operator=()
NLargest& operator= (const NLargest & source)
assignment operator
updateMembers_()
void updateMembers_ () override protected virtual
This method is used to update extra member variables at the end of the setParameters() method.
Also call it at the end of the derived classes' copy constructor and assignment operator.
The default implementation is empty.
Reimplemented from DefaultParamHandler.
Member Data Documentation
peakcount_
UInt peakcount_ protected