OpenMS: SpectraMerger Class Reference
SpectraMerger Class Reference
Merges blocks of MS or MS2 spectra.
#include <OpenMS/FILTERING/TRANSFORMERS/SpectraMerger.h>
Classes
class SpectraDistance_
Public Types
typedef Map< Size, std::vector< Size > > MergeBlocks
blocks of spectra (master-spectrum index to sacrifice-spectra(the ones being merged into the master-spectrum))
typedef Map< Size, std::vector< std::pair< Size, double > > > AverageBlocks
blocks of spectra (master-spectrum index to update to spectra to average over)
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Public Member Functions
SpectraMerger ()
default constructor
SpectraMerger (const SpectraMerger &source)
copy constructor
~SpectraMerger () override
destructor
SpectraMerger & operator= (const SpectraMerger &source)
assignment operator
template<typename MapType >
void mergeSpectraBlockWise (MapType &exp)
template<typename MapType >
void mergeSpectraPrecursors (MapType &exp)
merges spectra with similar precursors (must have MS2 level)
template<typename MapType >
void average (MapType &exp, const String &average_type)
average over neighbouring spectra
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Protected Member Functions
template<typename MapType >
void mergeSpectra_ (MapType &exp, const MergeBlocks &spectra_to_merge, const UInt ms_level)
merges blocks of spectra of a certain level
template<typename MapType >
void averageProfileSpectra_ (MapType &exp, const AverageBlocks &spectra_to_average_over, const UInt ms_level)
average spectra (profile mode)
template<typename MapType >
void averageCentroidSpectra_ (MapType &exp, const AverageBlocks &spectra_to_average_over, const UInt ms_level)
average spectra (centroid mode)
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Static Protected Member Functions
static bool compareByFirst (std::pair< double, double > i, std::pair< double, double > j)
comparator for sorting peaks (m/z, intensity)
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Additional Inherited Members
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
Merges blocks of MS or MS2 spectra.
Parameter's are accessible via the DefaultParamHandler.
Parameters of this class are:
Name Type Default Restrictions Description
mz_binning_width float 5.0 min: 0.0 minimum m/z distance for two data points (profile data) or peaks (centroided data) to be considered distinct. Closer data points or peaks will be merged.
mz_binning_width_unit string ppm Da, ppm Unit in which the distance between two data points or peaks is given.
sort_blocks string RT_ascending RT_ascending, RT_descending Sort blocks by before merging them (useful for precursor order)
average_gaussian:spectrum_type string automatic profile, centroid, automatic Spectrum type of the MS level to be averaged
average_gaussian:ms_level int 1 min: 1 Average spectra of this level. All other spectra remain unchanged.
average_gaussian:rt_FWHM float 5.0 min: 0.0 max: 1.0e11 FWHM of Gauss curve in seconds to be averaged over.
average_gaussian:cutoff float 0.01 min: 0.0 max: 1.0 Intensity cutoff for Gaussian. The Gaussian RT profile decreases from 1 at its apex to 0 at infinity. Spectra for which the intensity of the Gaussian drops below the cutoff do not contribute to the average.
average_tophat:spectrum_type string automatic profile, centroid, automatic Spectrum type of the MS level to be averaged
average_tophat:ms_level int 1 min: 1 Average spectra of this level. All other spectra remain unchanged.
average_tophat:rt_range float 5.0 min: 0.0 max: 1.0e11 RT range to be averaged over, i.e. +/-(RT range)/2 from each spectrum.
average_tophat:rt_unit string scans scans, seconds Unit for RT range.
block_method:ms_levels int list [1] min: 1 Merge spectra of this level. All spectra with other MS levels remain untouched.
block_method:rt_block_size int 5 min: 1 Maximum number of scans to be summed up.
block_method:rt_max_length float 0.0 min: 0.0 max: 1.0e11 Maximum RT size of the block in seconds (0.0 = no size restriction).
precursor_method:mz_tolerance float 1.0e-04 min: 0.0 Max m/z distance of the precursor entries of two spectra to be merged in [Da].
precursor_method:rt_tolerance float 5.0 min: 0.0 Max RT distance of the precursor entries of two spectra to be merged in [s].
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Member Typedef Documentation
AverageBlocks
typedef Map<Size, std::vector<std::pair<Size, double> > > AverageBlocks
blocks of spectra (master-spectrum index to update to spectra to average over)
MergeBlocks
typedef Map<Size, std::vector<Size> > MergeBlocks
blocks of spectra (master-spectrum index to sacrifice-spectra(the ones being merged into the master-spectrum))
Constructor & Destructor Documentation
SpectraMerger() [1/2]
SpectraMerger ()
default constructor
SpectraMerger() [2/2]
SpectraMerger (const SpectraMerger & source)
copy constructor
~SpectraMerger()
~SpectraMerger () override
destructor
Member Function Documentation
average()
void average (MapType & exp, const String & average_type) inline
average over neighbouring spectra
Parameters
exp experimental data to be averaged
average_type averaging type to be used ("gaussian" or "tophat")
References MSExperiment::begin(), SpectrumSettings::CENTROID, MSExperiment::end(), SpectrumSettings::PROFILE, MSExperiment::sortSpectra(), and OpenMS::Math::sum().
averageCentroidSpectra_()
void averageCentroidSpectra_ (MapType & exp, const AverageBlocks & spectra_to_average_over, const UInt ms_level) inline protected
average spectra (centroid mode)
Averages spectra in centroid mode of one MS level in an experiment. The blocks of spectra to be combined and their relative weights have previously determined. The averaged spectra are generated in two steps: (1) The m/z of all spectra in a block are collected and sorted. Their corresponding intensities are weighted. (2) m/z positions closer than mz_binning_width are combined to a single peak. The m/z are averaged and the corresponding intensities summed.
Parameters
exp experimental data to be averaged
spectra_to_average_over mapping of spectral index to set of spectra to average over with corresponding weights
ms_level MS level of spectra to be averaged
References MSExperiment::addSpectrum(), MSExperiment::begin(), MSSpectrum::clear(), SpectraMerger::compareByFirst(), MSExperiment::end(), ProgressLogger::endProgress(), Peak1D::setIntensity(), Peak1D::setMZ(), ProgressLogger::setProgress(), and ProgressLogger::startProgress().
averageProfileSpectra_()
void averageProfileSpectra_ (MapType & exp, const AverageBlocks & spectra_to_average_over, const UInt ms_level) inline protected
average spectra (profile mode)
Averages spectra in profile mode of one MS level in an experiment. The blocks of spectra to be combined and their relative weights have previously been determined. The averaged spectra are generated in two steps: (1) The m/z of all spectra in a block are collected and sorted. m/z positions closer than mz_binning_width are removed. (2) At these positions the weighted sum of all spline interpolations is calculated.
The first step ensures roughly the same sampling rate as the one of the original spectra. The exact m/z position is not crucial, since not the original intensities but the spline-interpolated intensities are used.
Parameters
exp experimental data to be averaged
spectra_to_average_over mapping of spectral index to set of spectra to average over with corresponding weights
ms_level MS level of spectra to be averaged
References MSExperiment::addSpectrum(), MSExperiment::begin(), MSSpectrum::clear(), MSExperiment::end(), SplineInterpolatedPeaks::Navigator::eval(), SplineInterpolatedPeaks::getNavigator(), SplineInterpolatedPeaks::getPosMax(), SplineInterpolatedPeaks::getPosMin(), Peak1D::setIntensity(), and Peak1D::setMZ().
compareByFirst()
static bool compareByFirst (std::pair< double, double > i, std::pair< double, double > j) inline static protected
comparator for sorting peaks (m/z, intensity)
Referenced by SpectraMerger::averageCentroidSpectra_().
mergeSpectra_()
void mergeSpectra_ (MapType & exp, const MergeBlocks & spectra_to_merge, const UInt ms_level) inline protected
merges blocks of spectra of a certain level
Merges spectra belonging to the same block, setting their MS level to ms_level. All old spectra of level ms_level are removed, and the new consensus spectra (one per block) are added. All spectra with other MS levels remain untouched. The resulting map is NOT sorted!
References MSExperiment::addSpectrum(), MSExperiment::begin(), MSExperiment::clear(), MSExperiment::end(), SpectrumSettings::getPrecursors(), MSSpectrum::getRT(), MSExperiment::getSpectra(), SpectrumAlignment::getSpectrumAlignment(), OPENMS_LOG_INFO, OPENMS_LOG_WARN, MSSpectrum::setMSLevel(), DefaultParamHandler::setParameters(), SpectrumSettings::setPrecursors(), MSSpectrum::setRT(), Param::setValue(), MSExperiment::size(), MSSpectrum::sortByPosition(), and SpectrumSettings::unify().
mergeSpectraBlockWise()
void mergeSpectraBlockWise (MapType & exp) inline
References MSExperiment::begin(), MSExperiment::end(), and MSExperiment::sortSpectra().
mergeSpectraPrecursors()
void mergeSpectraPrecursors (MapType & exp) inline
merges spectra with similar precursors (must have MS2 level)
References ClusterHierarchical::cluster(), ClusterAnalyzer::cut(), OPENMS_LOG_WARN, Peak2D::setMZ(), DefaultParamHandler::setParameters(), Peak2D::setRT(), MSExperiment::size(), and MSExperiment::sortSpectra().
operator=()
SpectraMerger& operator= (const SpectraMerger & source)
assignment operator