OpenMS: FileTypes Struct Reference
FileTypes Struct Reference
Format » File IO
Centralizes the file types recognized by FileHandler.
#include <OpenMS/FORMAT/FileTypes.h>
Public Types
enum Type {
UNKNOWN, DTA, DTA2D, MZDATA,
MZXML, FEATUREXML, IDXML, CONSENSUSXML,
MGF, INI, TOPPAS, TRANSFORMATIONXML,
MZML, CACHEDMZML, MS2, PEPXML,
PROTXML, MZIDENTML, MZQUANTML, QCML,
GELML, TRAML, MSP, OMSSAXML,
MASCOTXML, PNG, XMASS, TSV,
MZTAB, PEPLIST, HARDKLOER, KROENIK,
FASTA, EDTA, CSV, TXT,
OBO, HTML, XML, ANALYSISXML,
XSD, PSQ, MRM, SQMASS,
PQP, MS, OSW, PSMS,
PIN, PARAMXML, SPLIB, NOVOR,
XQUESTXML, JSON, RAW, EXE,
SIZE_OF_TYPE
}
Actual file types enum.
Static Public Member Functions
static String typeToName (Type type)
Returns the name/extension of the type.
static String typeToMZML (Type type)
Returns the mzML name (TODO: switch to accession since they are more stable!)
static Type nameToType (const String &name)
Converts a file type name into a Type.
Static Private Member Functions
static std::map< Type, String > initializeMap_ ()
Initializer for the file extension map.
static std::map< Type, String > initializeMZMLMap_ ()
Initializer for the file extension map.
Static Private Attributes
static const std::map< Type, String > name_of_types_
Maps the FileType::Type to the preferred extension.
static const std::map< Type, String > name_of_MZMLtypes_
Maps the FileType::Type to the preferred mzML CV name.
Detailed Description
Centralizes the file types recognized by FileHandler.
FileType separate from FileHandler to avoid circular inclusions by DocumentIdentifier, ExperimentalSettings and FileHandler and respective fileclasses (e.g. DTA2DFile).
Member Enumeration Documentation
Type
enum Type
Actual file types enum.
Enumerator
UNKNOWN
Unknown file extension.
DTA
DTA file (.dta)
DTA2D
DTA2D file (.dta2d)
MZDATA
MzData file (.mzData)
MZXML
MzXML file (.mzXML)
FEATUREXML
OpenMS feature file (.featureXML)
IDXML
OpenMS identification format (.idXML)
CONSENSUSXML
OpenMS consensus map format (.consensusXML)
MGF
Mascot Generic Format (.mgf)
INI
OpenMS parameters file (.ini)
TOPPAS
OpenMS parameters file with workflow information (.toppas)
TRANSFORMATIONXML
Transformation description file (.trafoXML)
MZML
MzML file (.mzML)
CACHEDMZML
CachedMzML file (.cachedmzML)
MS2
MS2 file (.ms2)
PEPXML
TPP pepXML file (.pepXML)
PROTXML
TPP protXML file (.protXML)
MZIDENTML
mzIdentML (HUPO PSI AnalysisXML followup format) (.mzid)
MZQUANTML
mzQuantML (HUPO PSI AnalysisXML followup format) (.mzq)
QCML
qcML (will undergo standardisation maybe) (.qcml)
GELML
GelML (HUPO PSI format) (.gelML)
TRAML
TraML (HUPO PSI format) for transitions (.traML)
MSP
NIST spectra library file format (.msp)
OMSSAXML
OMSSA XML file format for peptide identifications (.xml)
MASCOTXML
Mascot XML file format for peptide identifications (.xml)
PNG
Portable Network Graphics (.png)
XMASS
XMass Analysis file (fid)
TSV
any TSV file, for example msInspect file or OpenSWATH transition file (see TransitionTSVFile)
MZTAB
mzTab file (.mzTab)
PEPLIST
specArray file (.peplist)
HARDKLOER
hardkloer file (.hardkloer)
KROENIK
kroenik file (.kroenik)
FASTA
FASTA file (.fasta)
EDTA
enhanced comma separated files (RT, m/z, Intensity, [meta])
CSV
general comma separated files format (might also be tab or space separated!!!), data should be regular, i.e. matrix form
TXT
any text format, which has only loose definition of what it actually contains – thus it is usually hard to say where the file actually came from (e.g. PepNovo).
OBO
Controlled Vocabulary format.
HTML
any HTML format
XML
any XML format
ANALYSISXML
analysisXML format
XSD
XSD schema format.
PSQ
NCBI binary blast db.
MRM
SpectraST MRM List.
SQMASS
SqLite format for mass and chromatograms, see SqMassFile.
PQP
OpenSWATH Peptide Query Parameter (PQP) SQLite DB, see TransitionPQPFile.
MS
SIRIUS file format (.ms)
OSW
OpenSWATH OpenSWATH report (OSW) SQLite DB.
PSMS
Percolator tab-delimited output (PSM level)
PIN
Percolator tab-delimited input (PSM level)
PARAMXML
internal format for writing and reading parameters (also used as part of CTD)
SPLIB
SpectraST binary spectral library file (sptxt is the equivalent text-based format, similar to the MSP format)
NOVOR
Novor custom parameter file.
XQUESTXML
xQuest XML file format for protein-protein cross-link identifications (.xquest.xml)
JSON
JavaScript Object Notation file (.json)
RAW
Thermo Raw File (.raw)
EXE
Executable (.exe)
SIZE_OF_TYPE
No file type. Simply stores the number of types.
Member Function Documentation
initializeMap_()
static std::map<Type, String> initializeMap_ () static private
Initializer for the file extension map.
initializeMZMLMap_()
static std::map<Type, String> initializeMZMLMap_ () static private
Initializer for the file extension map.
nameToType()
static Type nameToType (const String & name) static
Converts a file type name into a Type.
Referenced by TOPPXFDR::loadInputFile_().
typeToMZML()
static String typeToMZML (Type type) static
Returns the mzML name (TODO: switch to accession since they are more stable!)
typeToName()
static String typeToName (Type type) static
Returns the name/extension of the type.
Referenced by TOPPViewBase::addDataFile(), and InspectOutfile::getExperiment().
Member Data Documentation
name_of_MZMLtypes_
const std::map<Type, String> name_of_MZMLtypes_ static private
Maps the FileType::Type to the preferred mzML CV name.
name_of_types_
const std::map<Type, String> name_of_types_ static private
Maps the FileType::Type to the preferred extension.