OpenMS: StringManager Class Reference
StringManager Class Reference
#include <OpenMS/FORMAT/HANDLERS/XMLHandler.h>
Public Member Functions
StringManager ()
Constructor.
~StringManager ()
Destructor.
XercesString convert (const char *str) const
Transcode the supplied C string to a xerces string.
XercesString convert (const std::string &str) const
Transcode the supplied C++ string to a xerces string.
XercesString convert (const String &str) const
Transcode the supplied OpenMS string to a xerces string.
String convert (const XMLCh *str) const
Transcode the supplied XMLCh* to a String.
Static Public Member Functions
static void appendASCII (const XMLCh *str, const XMLSize_t length, String &result)
Transcodes the supplied XMLCh* and appends it to the OpenMS String.
Private Types
typedef std::basic_string< XMLCh > XercesString
Private Member Functions
XercesString fromNative_ (const char *str) const
XercesString fromNative_ (const String &str) const
String toNative_ (const XMLCh *str) const
String toNative_ (const XercesString &str) const
Member Typedef Documentation
XercesString
typedef std::basic_string<XMLCh> XercesString private
Constructor & Destructor Documentation
StringManager()
StringManager ()
Constructor.
~StringManager()
~StringManager ()
Destructor.
Member Function Documentation
appendASCII()
static void appendASCII (const XMLCh * str, const XMLSize_t length, String & result) static
Transcodes the supplied XMLCh* and appends it to the OpenMS String.
Note
Assumes that the XMLCh* only contains ASCII characters
convert() [1/4]
XercesString convert (const char * str) const inline
Transcode the supplied C string to a xerces string.
Referenced by XMLHandler::attributeAsDouble_(), XMLHandler::attributeAsInt_(), XMLHandler::attributeAsString_(), XMLHandler::optionalAttributeAsDouble_(), XMLHandler::optionalAttributeAsDoubleList_(), XMLHandler::optionalAttributeAsInt_(), XMLHandler::optionalAttributeAsIntList_(), XMLHandler::optionalAttributeAsString_(), XMLHandler::optionalAttributeAsStringList_(), and XMLHandler::optionalAttributeAsUInt_().
convert() [2/4]
XercesString convert (const std::string & str) const inline
Transcode the supplied C++ string to a xerces string.
convert() [3/4]
XercesString convert (const String & str) const inline
Transcode the supplied OpenMS string to a xerces string.
convert() [4/4]
String convert (const XMLCh * str) const inline
Transcode the supplied XMLCh* to a String.
fromNative_() [1/2]
XercesString fromNative_ (const char * str) const inline private
fromNative_() [2/2]
XercesString fromNative_ (const String & str) const inline private
toNative_() [1/2]
String toNative_ (const XercesString & str) const inline private
toNative_() [2/2]
String toNative_ (const XMLCh * str) const inline private