OpenMS: MS2File Class Reference
MS2File Class Reference
Format » File IO
MS2 input file adapter.
#include <OpenMS/FORMAT/MS2File.h>
Public Member Functions
MS2File ()
constructor
virtual ~MS2File ()
constructor
template<typename MapType >
void load (const String &filename, MapType &exp)
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
MS2 input file adapter.
For the format description take a look at: Rapid Communications in Mass Spectrometry. 2004;18(18):2162-8.
MS1, MS2, and SQT-three unified, compact, and easily parsed file formats for the storage of shotgun proteomic spectra and identifications.
McDonald WH, Tabb DL, Sadygov RG, MacCoss MJ, Venable J, Graumann J, Johnson JR, Cociorva D, Yates JR 3rd.
PMID: 15317041
Constructor & Destructor Documentation
MS2File()
MS2File ()
constructor
~MS2File()
virtual ~MS2File () virtual
constructor
Member Function Documentation
load()
void load (const String & filename, MapType & exp) inline
References MSExperiment::addSpectrum(), MSSpectrum::clear(), File::exists(), SpectrumSettings::getPrecursors(), File::readable(), MSExperiment::reset(), Peak1D::setIntensity(), DocumentIdentifier::setLoadedFilePath(), DocumentIdentifier::setLoadedFileType(), MSSpectrum::setMSLevel(), SpectrumSettings::setNativeID(), Peak1D::setPosition(), String::simplify(), String::split(), and String::trim().