OpenMS: MsInspectFile Class Reference
MsInspectFile Class Reference
Format » File IO
File adapter for MsInspect files.
#include <OpenMS/FORMAT/MsInspectFile.h>
Public Member Functions
MsInspectFile ()
Default constructor.
virtual ~MsInspectFile ()
Destructor.
template<typename FeatureMapType >
void load (const String &filename, FeatureMapType &feature_map)
Loads a MsInspect file into a featureXML.
template<typename SpectrumType >
void store (const String &filename, const SpectrumType &spectrum) const
Stores a featureXML as a MsInspect file.
Detailed Description
File adapter for MsInspect files.
Lines with "#" are comments and are ignored.
The first non-comment line is the header and contains the column names:
scan time mz accurateMZ mass intensity charge chargeStates kl background median peaks scanFirst scanLast scanCount totalIntensity sumSquaresDist description
Every subsequent line is a feature.
Constructor & Destructor Documentation
MsInspectFile()
MsInspectFile ()
Default constructor.
~MsInspectFile()
virtual ~MsInspectFile () virtual
Destructor.
Member Function Documentation
load()
void load (const String & filename, FeatureMapType & feature_map) inline
Loads a MsInspect file into a featureXML.
The content of the file is stored in features.
Exceptions
Exception::FileNotFound is thrown if the file could not be opened
Exception::ParseError is thrown if an error occurs during parsing
References TextFile::begin(), TextFile::end(), BaseFeature::setCharge(), Peak2D::setIntensity(), MetaInfoInterface::setMetaValue(), Peak2D::setMZ(), Feature::setOverallQuality(), Peak2D::setRT(), and String::split().
store()
void store (const String & filename, const SpectrumType & spectrum) const inline
Stores a featureXML as a MsInspect file.
NOT IMPLEMENTED
Exceptions
Exception::UnableToCreateFile is thrown if the file could not be created