OpenMS: IndexedMzMLFileLoader Class Reference
IndexedMzMLFileLoader Class Reference
A class to load an indexedmzML file.
#include <OpenMS/FORMAT/IndexedMzMLFileLoader.h>
Public Member Functions
IndexedMzMLFileLoader ()
Constructor.
~IndexedMzMLFileLoader ()
Destructor.
PeakFileOptions & getOptions ()
Mutable access to the options for loading/storing.
const PeakFileOptions & getOptions () const
Non-mutable access to the options for loading/storing.
void setOptions (const PeakFileOptions &)
set options for loading/storing
bool load (const String &filename, OnDiscPeakMap &exp)
Load a file.
void store (const String &filename, OnDiscPeakMap &exp)
Store a file from an on-disc data-structure.
void store (const String &filename, PeakMap &exp)
Store a file from an in-memory data-structure.
Private Attributes
PeakFileOptions options_
Options for storing.
Detailed Description
A class to load an indexedmzML file.
Providing the same interface as the other classes such as MzMLFile, MzXMLFile etc. to load and store a file. Reading a file from disk will load the file into a OnDiscMSExperiment while the class can write to disk both, a MSExperiment and a OnDiscMSExperiment.
Constructor & Destructor Documentation
IndexedMzMLFileLoader()
IndexedMzMLFileLoader ()
Constructor.
~IndexedMzMLFileLoader()
~IndexedMzMLFileLoader ()
Destructor.
Member Function Documentation
getOptions() [1/2]
PeakFileOptions& getOptions ()
Mutable access to the options for loading/storing.
getOptions() [2/2]
const PeakFileOptions& getOptions () const
Non-mutable access to the options for loading/storing.
load()
bool load (const String & filename, OnDiscPeakMap & exp) inline
Load a file.
Tries to parse the file, success needs to be checked with the return value.
Parameters
filename Filename determines where the file is located
exp Object which will contain the data after the call
Returns
Indicates whether parsing was successful (if it is false, the file most likely was not an mzML or not indexed).
References OnDiscMSExperiment::openFile().
setOptions()
void setOptions (const PeakFileOptions &)
set options for loading/storing
store() [1/2]
void store (const String & filename, OnDiscPeakMap & exp) inline
Store a file from an on-disc data-structure.
Parameters
filename Filename determines where the file will be stored
exp MS data to be stored
References OpenMS::Constants::c, MSDataWritingConsumer::consumeChromatogram(), MSDataWritingConsumer::consumeSpectrum(), OnDiscMSExperiment::getChromatogram(), OnDiscMSExperiment::getExperimentalSettings(), OnDiscMSExperiment::getNrChromatograms(), OnDiscMSExperiment::getNrSpectra(), OnDiscMSExperiment::getSpectrum(), MSDataWritingConsumer::setExpectedSize(), MSDataWritingConsumer::setExperimentalSettings(), and MzMLHandler::setOptions().
store() [2/2]
void store (const String & filename, PeakMap & exp) inline
Store a file from an in-memory data-structure.
Parameters
filename Filename determines where the file will be stored
exp MS data to be stored
References MzMLFile::setOptions(), and MzMLFile::store().
Member Data Documentation
options_
PeakFileOptions options_ private
Options for storing.