OpenMS: MzTabString Class Reference
MzTabString Class Reference
#include <OpenMS/FORMAT/MzTab.h>
Public Member Functions
MzTabString ()
MzTabString (const String &s)
~MzTabString () override
void set (const String &value)
String get () const
bool isNull () const override
void setNull (bool b) override
String toCellString () const override
void fromCellString (const String &s) override
Public Member Functions inherited from MzTabNullAbleInterface
virtual ~MzTabNullAbleInterface ()
Protected Attributes
String value_
Constructor & Destructor Documentation
MzTabString() [1/2]
MzTabString ()
MzTabString() [2/2]
MzTabString (const String & s) explicit
~MzTabString()
~MzTabString () override
Member Function Documentation
fromCellString()
void fromCellString (const String & s) override virtual
Implements MzTabNullAbleInterface.
get()
String get () const
Referenced by MzTabProteinSectionRow::RowCompare::operator()(), MzTabPeptideSectionRow::RowCompare::operator()(), MzTabPSMSectionRow::RowCompare::operator()(), MzTabNucleicAcidSectionRow::RowCompare::operator()(), MzTabOligonucleotideSectionRow::RowCompare::operator()(), and MzTabOSMSectionRow::RowCompare::operator()().
isNull()
bool isNull () const override virtual
Implements MzTabNullAbleInterface.
set()
void set (const String & value)
setNull()
void setNull (bool b) override virtual
Implements MzTabNullAbleInterface.
toCellString()
String toCellString () const override virtual
Implements MzTabNullAbleInterface.
Member Data Documentation
value_
String value_ protected