OpenMS: MzTabSpectraRef Class Reference
MzTabSpectraRef Class Reference
#include <OpenMS/FORMAT/MzTab.h>
Public Member Functions
MzTabSpectraRef ()
~MzTabSpectraRef () override
bool isNull () const override
void setNull (bool b) override
void setMSFile (Size index)
void setSpecRef (const String &spec_ref)
String getSpecRef () const
Size getMSFile () const
void setSpecRefFile (const String &spec_ref)
String toCellString () const override
void fromCellString (const String &s) override
Public Member Functions inherited from MzTabNullAbleInterface
virtual ~MzTabNullAbleInterface ()
Protected Attributes
Size ms_run_
String spec_ref_
Constructor & Destructor Documentation
MzTabSpectraRef()
MzTabSpectraRef ()
~MzTabSpectraRef()
~MzTabSpectraRef () override
Member Function Documentation
fromCellString()
void fromCellString (const String & s) override virtual
Implements MzTabNullAbleInterface.
getMSFile()
Size getMSFile () const
Referenced by MzTabPSMSectionRow::RowCompare::operator()(), and MzTabOSMSectionRow::RowCompare::operator()().
getSpecRef()
String getSpecRef () const
Referenced by MzTabPSMSectionRow::RowCompare::operator()(), and MzTabOSMSectionRow::RowCompare::operator()().
isNull()
bool isNull () const override virtual
Implements MzTabNullAbleInterface.
setMSFile()
void setMSFile (Size index)
setNull()
void setNull (bool b) override virtual
Implements MzTabNullAbleInterface.
setSpecRef()
void setSpecRef (const String & spec_ref)
setSpecRefFile()
void setSpecRefFile (const String & spec_ref)
toCellString()
String toCellString () const override virtual
Implements MzTabNullAbleInterface.
Member Data Documentation
ms_run_
Size ms_run_ protected
spec_ref_
String spec_ref_ protected