OpenMS: ParamXMLFile Class Reference
ParamXMLFile Class Reference
The file pendant of the Param class used to load and store the param datastructure as paramXML.
#include <OpenMS/FORMAT/ParamXMLFile.h>
Public Member Functions
ParamXMLFile ()
Constructor.
void store (const String &filename, const Param &param) const
Write XML file.
void writeXMLToStream (std::ostream *os_ptr, const Param &param) const
Write XML to output stream.
void load (const String &filename, Param &param)
Read XML file.
Public Member Functions inherited from XMLFile
XMLFile ()
Default constructor.
XMLFile (const String &schema_location, const String &version)
Constructor that sets the schema location.
virtual ~XMLFile ()
Destructor.
bool isValid (const String &filename, std::ostream &os)
Checks if a file validates against the XML schema.
const String & getVersion () const
return the version of the schema
Additional Inherited Members
Protected Member Functions inherited from XMLFile
void parse_ (const String &filename, XMLHandler *handler)
Parses the XML file given by filename using the handler given by handler.
void parseBuffer_ (const std::string &buffer, XMLHandler *handler)
Parses the in-memory buffer given by buffer using the handler given by handler.
void save_ (const String &filename, XMLHandler *handler) const
Stores the contents of the XML handler given by handler in the file given by filename.
void enforceEncoding_ (const String &encoding)
Protected Attributes inherited from XMLFile
String schema_location_
XML schema file location.
String schema_version_
Version string.
String enforced_encoding_
Encoding string that replaces the encoding (system dependent or specified in the XML). Disabled if empty. Used as a workaround for XTandem output xml.
Detailed Description
The file pendant of the Param class used to load and store the param datastructure as paramXML.
A documented schema for this format can be found at https://github.com/OpenMS/OpenMS/tree/develop/share/OpenMS/SCHEMAS
Constructor & Destructor Documentation
ParamXMLFile()
ParamXMLFile ()
Constructor.
Member Function Documentation
load()
void load (const String & filename, Param & param)
Read XML file.
Parameters
filename The file from where to read the Param object.
param The param object where the read data should be stored.
Exceptions
Exception::FileNotFound is thrown if the file could not be found
Exception::ParseError is thrown if an error occurs during parsing
Referenced by TOPPASBase::loadPreferences(), TOPPViewBase::loadPreferences(), main(), INIFileEditorWindow::openFile(), and DigestionEnzymeDB< DigestionEnzymeRNA, RNaseDB >::readEnzymesFromFile_().
store()
void store (const String & filename, const Param & param) const
Write XML file.
Parameters
filename The filename where the param data structure should be stored.
param The Param class that should be stored in the file.
Exceptions
Exception::UnableToCreateFile is thrown if the file could not be created
Referenced by INIFileEditorWindow::saveFile(), INIFileEditorWindow::saveFileAs(), TOPPASBase::savePreferences(), and TOPPViewBase::savePreferences().
writeXMLToStream()
void writeXMLToStream (std::ostream * os_ptr, const Param & param) const
Write XML to output stream.
Parameters
os_ptr The stream where the param class should be written to.
param The Param class that should be written to the stream.