OpenMS: XQuestResultXMLFile Class Reference
XQuestResultXMLFile Class Reference
Format » File IO
Used to load and store xQuest result files.
#include <OpenMS/FORMAT/XQuestResultXMLFile.h>
Public Member Functions
XQuestResultXMLFile ()
~XQuestResultXMLFile () override
void load (const String &filename, std::vector< PeptideIdentification > &pep_ids, std::vector< ProteinIdentification > &prot_ids)
Load the content of the xquest.xml file into the provided data structures.
void store (const String &filename, const std::vector< ProteinIdentification > &poid, const std::vector< PeptideIdentification > &peid) const
Stores the identifications in a xQuest XML file.
int getNumberOfHits () const
Returns the total number of hits in the file.
double getMinScore () const
Returns minimum score among the hits in the file.
double getMaxScore () const
Returns maximum score among the hits in the file.
Public Member Functions inherited from XMLFile
XMLFile ()
Default constructor.
XMLFile (const String &schema_location, const String &version)
Constructor that sets the schema location.
virtual ~XMLFile ()
Destructor.
bool isValid (const String &filename, std::ostream &os)
Checks if a file validates against the XML schema.
const String & getVersion () const
return the version of the schema
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Static Public Member Functions
static void writeXQuestXMLSpec (const String &out_file, const String &base_name, const OPXLDataStructs::PreprocessedPairSpectra &preprocessed_pair_spectra, const std::vector< std::pair< Size, Size > > &spectrum_pairs, const std::vector< std::vector< OPXLDataStructs::CrossLinkSpectrumMatch > > &all_top_csms, const PeakMap &spectra)
Writes spec.xml output containing matching peaks between heavy and light spectra after comparing and filtering.
static void writeXQuestXMLSpec (const String &out_file, const String &base_name, const std::vector< std::vector< OPXLDataStructs::CrossLinkSpectrumMatch > > &all_top_csms, const PeakMap &spectra)
Writes spec.xml output containing spectra for visualization. This version of the function is meant to be used for label-free linkers.
Static Private Member Functions
static String getxQuestBase64EncodedSpectrum_ (const PeakSpectrum &spec, String header)
Transforms a PeakSpectrum into a base 64 encoded string, which is the format used in spec.xml for xQuest.
static void wrap_ (const String &input, Size width, String &output)
A helper function, that takes one string containing one line and wraps it into several lines of a given width.
Private Attributes
int n_hits_
Total number of hits within the result file.
double min_score_
Minimum score encountered in file.
double max_score_
Maximum score encountered in file.
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Protected Member Functions inherited from XMLFile
void parse_ (const String &filename, XMLHandler *handler)
Parses the XML file given by filename using the handler given by handler.
void parseBuffer_ (const std::string &buffer, XMLHandler *handler)
Parses the in-memory buffer given by buffer using the handler given by handler.
void save_ (const String &filename, XMLHandler *handler) const
Stores the contents of the XML handler given by handler in the file given by filename.
void enforceEncoding_ (const String &encoding)
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from XMLFile
String schema_location_
XML schema file location.
String schema_version_
Version string.
String enforced_encoding_
Encoding string that replaces the encoding (system dependent or specified in the XML). Disabled if empty. Used as a workaround for XTandem output xml.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
Used to load and store xQuest result files.
These files are used to store results derived from chemical cross-linking coupled to MS experiments.
A documented schema for this format can be found at https://github.com/OpenMS/OpenMS/tree/develop/share/OpenMS/SCHEMAS
Constructor & Destructor Documentation
XQuestResultXMLFile()
XQuestResultXMLFile ()
~XQuestResultXMLFile()
~XQuestResultXMLFile () override
Member Function Documentation
getMaxScore()
double getMaxScore () const
Returns maximum score among the hits in the file.
Returns
Maximum score among the hits in the file.
getMinScore()
double getMinScore () const
Returns minimum score among the hits in the file.
Returns
Minimum score among the hits in the file.
getNumberOfHits()
int getNumberOfHits () const
Returns the total number of hits in the file.
Returns
total number of hits in the file
Referenced by TOPPXFDR::loadInputFile_().
getxQuestBase64EncodedSpectrum_()
static String getxQuestBase64EncodedSpectrum_ (const PeakSpectrum & spec, String header) static private
Transforms a PeakSpectrum into a base 64 encoded string, which is the format used in spec.xml for xQuest.
Parameters
The spectrum
A header for the spectrum, build using the base_name parameter for writeXQuestXMLSpec and the index of the spectrum.
load()
void load (const String & filename, std::vector< PeptideIdentification > & pep_ids, std::vector< ProteinIdentification > & prot_ids)
Load the content of the xquest.xml file into the provided data structures.
Parameters
filename Filename of the file which is to be loaded.
pep_ids Where the spectra with identifications of the input file will be loaded to.
prot_ids Where the protein identification of the input file will be loaded to.
Referenced by TOPPXFDR::loadInputFile_().
store()
void store (const String & filename, const std::vector< ProteinIdentification > & poid, const std::vector< PeptideIdentification > & peid) const
Stores the identifications in a xQuest XML file.
Exceptions
Exception::UnableToCreateFile is thrown if the file could not be created
Referenced by TOPPXFDR::main_(), TOPPOpenPepXLLF::main_(), and TOPPOpenPepXL::main_().
wrap_()
static void wrap_ (const String & input, Size width, String & output) static private
A helper function, that takes one string containing one line and wraps it into several lines of a given width.
Parameters
The string as one line
The preferred line width
String in which the output is written
writeXQuestXMLSpec() [1/2]
static void writeXQuestXMLSpec (const String & out_file, const String & base_name, const OPXLDataStructs::PreprocessedPairSpectra & preprocessed_pair_spectra, const std::vector< std::pair< Size, Size > > & spectrum_pairs, const std::vector< std::vector< OPXLDataStructs::CrossLinkSpectrumMatch > > & all_top_csms, const PeakMap & spectra) static
Writes spec.xml output containing matching peaks between heavy and light spectra after comparing and filtering.
Parameters
Path and filename for the output file
The base_name should be the name of the input spectra file without the file ending. Used as part of an identifier string for the spectra.
The preprocessed spectra after comparing and filtering
Indices of spectrum pairs in the input map
CrossLinkSpectrumMatches,from which the IDs were generated. Only spectra with matches are written out.
The spectra, that were searched as a PeakMap. The indices in spectrum_pairs correspond to spectra in this map.
writeXQuestXMLSpec() [2/2]
static void writeXQuestXMLSpec (const String & out_file, const String & base_name, const std::vector< std::vector< OPXLDataStructs::CrossLinkSpectrumMatch > > & all_top_csms, const PeakMap & spectra) static
Writes spec.xml output containing spectra for visualization. This version of the function is meant to be used for label-free linkers.
Parameters
Path and filename for the output file
The base_name should be the name of the input spectra file without the file ending. Used as part of an identifier string for the spectra.
CrossLinkSpectrumMatches,from which the IDs were generated. Only spectra with matches are written out.
The spectra, that were searched as a PeakMap.
Member Data Documentation
max_score_
double max_score_ private
Maximum score encountered in file.
min_score_
double min_score_ private
Minimum score encountered in file.
n_hits_
int n_hits_ private
Total number of hits within the result file.