OpenMS: XMassFile Class Reference
XMassFile Class Reference
Format » File IO
File adapter for 'XMass Analysis (fid)' files.
#include <OpenMS/FORMAT/XMassFile.h>
Public Member Functions
XMassFile ()
Default constructor.
virtual ~XMassFile ()
Destructor.
void load (const String &filename, MSSpectrum &spectrum)
Loads a spectrum from a XMass file.
void importExperimentalSettings (const String &filename, PeakMap &exp)
Import settings from a XMass file.
void store (const String &, const MSSpectrum &)
Stores a spectrum in a XMass file (not available)
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
File adapter for 'XMass Analysis (fid)' files.
XMass Analysis files is native format for Bruker spectrometer Flex Series.
Each spectrum are saved in one directory. Each directory contains several files. We use 2 files for import in OpenMS :
acqus : contains meta data about calibration (conversion for time to mz ratio), instrument specification and acquisition method.
fid : contains intensity array. Intensity for each point are coded in 4 bytes integer.
Note
MZ ratio are calculated with formula based on article :
A database application for pre-processing, storage and comparison of mass spectra derived from patients and controls
Mark K Titulaer, Ivar Siccama, Lennard J Dekker, Angelique LCT van Rijswijk, Ron MA Heeren, Peter A Sillevis Smitt, and Theo M Luider
BMC Bioinformatics. 2006; 7: 403
http://www.pubmedcentral.nih.gov/picrender.fcgi?artid=1594579&blobtype=pdf
Constructor & Destructor Documentation
XMassFile()
XMassFile ()
Default constructor.
~XMassFile()
virtual ~XMassFile () virtual
Destructor.
Member Function Documentation
importExperimentalSettings()
void importExperimentalSettings (const String & filename, PeakMap & exp) inline
Import settings from a XMass file.
Parameters
filename File from which the experimental settings should be loaded.
exp MSExperiment where the experimental settings will be stored.
Exceptions
Exception::FileNotFound is thrown if the file could not be opened.
References MassAnalyzer::ANALYZERNULL, IonSource::DIRECT, MSExperiment::getExperimentalSettings(), Instrument::getIonSources(), Instrument::getMassAnalyzers(), IonSource::INLETNULL, IonSource::MALDI, IonSource::NEGATIVE, IonSource::POLNULL, IonSource::POSITIVE, String::prefix(), DateTime::set(), Instrument::setModel(), Instrument::setName(), Instrument::setVendor(), and MassAnalyzer::TOF.
load()
void load (const String & filename, MSSpectrum & spectrum) inline
Loads a spectrum from a XMass file.
Parameters
filename Name of the XMass file which should be loaded.
spectrum Spectrum in which the data loaded from the file should be stored.
Exceptions
Exception::FileNotFound is thrown if the file could not be read
References DataProcessing::BASELINE_REDUCTION, DataProcessing::CALIBRATION, MSSpectrum::clear(), String::hasPrefix(), String::hasSuffix(), InstrumentSettings::MASSSPECTRUM, IonSource::NEGATIVE, DateTime::now(), IonSource::POLNULL, IonSource::POSITIVE, String::prefix(), SpectrumSettings::PROFILE, SpectrumSettings::setAcquisitionInfo(), SpectrumSettings::setComment(), DataProcessing::setCompletionTime(), SpectrumSettings::setDataProcessing(), SourceFile::setFileSize(), SourceFile::setFileType(), SpectrumSettings::setInstrumentSettings(), Peak1D::setIntensity(), MetaInfoInterface::setMetaValue(), AcquisitionInfo::setMethodOfCombination(), MSSpectrum::setMSLevel(), Software::setName(), MSSpectrum::setName(), SourceFile::setNameOfFile(), SpectrumSettings::setNativeID(), SourceFile::setPathToFile(), InstrumentSettings::setPolarity(), Peak1D::setPosition(), DataProcessing::setProcessingActions(), MSSpectrum::setRT(), InstrumentSettings::setScanMode(), DataProcessing::setSoftware(), SpectrumSettings::setSourceFile(), SpectrumSettings::setType(), Software::setVersion(), InstrumentSettings::setZoomScan(), DataProcessing::SMOOTHING, and String::suffix().
store()
void store (const String & , const MSSpectrum &) inline
Stores a spectrum in a XMass file (not available)
Exceptions
Exception::FileNotWritable is thrown