OpenMS: SwathFile Class Reference
SwathFile Class Reference
File adapter for Swath files.
#include <OpenMS/FORMAT/SwathFile.h>
Public Member Functions
std::vector< OpenSwath::SwathMap > loadSplit (StringList file_list, String tmp, boost::shared_ptr< ExperimentalSettings > &exp_meta, String readoptions="normal")
Loads a Swath run from a list of split mzML files.
std::vector< OpenSwath::SwathMap > loadMzML (const String &file, const String &tmp, boost::shared_ptr< ExperimentalSettings > &exp_meta, const String &readoptions="normal", Interfaces::IMSDataConsumer *plugin_consumer=nullptr)
Loads a Swath run from a single mzML file.
std::vector< OpenSwath::SwathMap > loadMzXML (String file, String tmp, boost::shared_ptr< ExperimentalSettings > &exp_meta, String readoptions="normal")
Loads a Swath run from a single mzXML file.
std::vector< OpenSwath::SwathMap > loadSqMass (String file, boost::shared_ptr< ExperimentalSettings > &)
Loads a Swath run from a single sqMass file.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Protected Member Functions
OpenSwath::SpectrumAccessPtr doCacheFile_ (const String &in, const String &tmp, const String &tmp_fname, boost::shared_ptr< PeakMap > experiment_metadata)
Cache a file to disk.
boost::shared_ptr< PeakMap > populateMetaData_ (const String &file)
Only read the meta data from a file and use it to populate exp_meta.
void countScansInSwath_ (const std::vector< MSSpectrum > &exp, std::vector< int > &swath_counter, int &nr_ms1_spectra, std::vector< OpenSwath::SwathMap > &known_window_boundaries)
Counts the number of scans in a full Swath file (e.g. concatenated non-split file)
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
File adapter for Swath files.
This class can load SWATH files in different storage versions. The most convenient file is a single MzML file which contains one experiment. However, also the loading of a list of files is supported (loadSplit) where it is assumed that each individual file only contains scans from one precursor isolation window (one SWATH). Finally, experimental support for mzXML is available but needs to be selected with a specific compile flag (this is not for everyday use).
Member Function Documentation
countScansInSwath_()
void countScansInSwath_ (const std::vector< MSSpectrum > & exp, std::vector< int > & swath_counter, int & nr_ms1_spectra, std::vector< OpenSwath::SwathMap > & known_window_boundaries) protected
Counts the number of scans in a full Swath file (e.g. concatenated non-split file)
doCacheFile_()
OpenSwath::SpectrumAccessPtr doCacheFile_ (const String & in, const String & tmp, const String & tmp_fname, boost::shared_ptr< PeakMap > experiment_metadata) protected
Cache a file to disk.
loadMzML()
std::vector<OpenSwath::SwathMap> loadMzML (const String & file, const String & tmp, boost::shared_ptr< ExperimentalSettings > & exp_meta, const String & readoptions = "normal", Interfaces::IMSDataConsumer * plugin_consumer = nullptr)
Loads a Swath run from a single mzML file.
Using the plugin_consumer, you can provide a custom consumer which will be chained into the process of loading the data and making it available (depending on readoptions). This is useful if you want to modify the data a priori or extract some other information using MSDataTransformingConsumer (for example). Make sure it leaves the data intact, such that the returned SwathMaps are actually useful.
Parameters
[IN] file Input filename
[IN] tmp Temporary directory (for cached data)
[OUT] exp_meta Experimental metadata from mzML file
[IN] readoptions How are spectra accessed after reading - tradeoff between memory usage and time (disk caching)
[IN] plugin_consumer An intermediate custom consumer
Returns
Swath maps for MS2 and MS1 (unless readoptions == split, which returns no data)
Referenced by TOPPOpenSwathBase::loadSwathFiles_().
loadMzXML()
std::vector<OpenSwath::SwathMap> loadMzXML (String file, String tmp, boost::shared_ptr< ExperimentalSettings > & exp_meta, String readoptions = "normal")
Loads a Swath run from a single mzXML file.
Referenced by TOPPOpenSwathBase::loadSwathFiles_().
loadSplit()
std::vector<OpenSwath::SwathMap> loadSplit (StringList file_list, String tmp, boost::shared_ptr< ExperimentalSettings > & exp_meta, String readoptions = "normal")
Loads a Swath run from a list of split mzML files.
Referenced by TOPPOpenSwathBase::loadSwathFiles_().
loadSqMass()
std::vector<OpenSwath::SwathMap> loadSqMass (String file, boost::shared_ptr< ExperimentalSettings > &)
Loads a Swath run from a single sqMass file.
Referenced by TOPPOpenSwathBase::loadSwathFiles_().
populateMetaData_()
boost::shared_ptr< PeakMap > populateMetaData_ (const String & file) protected
Only read the meta data from a file and use it to populate exp_meta.