OpenMS: ChromatogramPeak::RTLess Struct Reference
ChromatogramPeak::RTLess Struct Reference
Comparator by RT position.
#include <OpenMS/KERNEL/ChromatogramPeak.h>
Public Member Functions
bool operator() (const ChromatogramPeak &left, const ChromatogramPeak &right) const
bool operator() (ChromatogramPeak const &left, CoordinateType right) const
bool operator() (CoordinateType left, ChromatogramPeak const &right) const
bool operator() (CoordinateType left, CoordinateType right) const
Detailed Description
Comparator by RT position.
Member Function Documentation
operator()() [1/4]
bool operator() (ChromatogramPeak const & left, CoordinateType right) const inline
References ChromatogramPeak::getRT().
operator()() [2/4]
bool operator() (const ChromatogramPeak & left, const ChromatogramPeak & right) const inline
References ChromatogramPeak::getPos(), and ChromatogramPeak::getRT().
operator()() [3/4]
bool operator() (CoordinateType left, ChromatogramPeak const & right) const inline
References ChromatogramPeak::getRT().
operator()() [4/4]
bool operator() (CoordinateType left, CoordinateType right) const inline