OpenMS: ChromatogramPeak::PositionLess Struct Reference
ChromatogramPeak::PositionLess Struct Reference
Comparator by position. As this class has dimension 1, this is basically an alias for RTLess.
#include <OpenMS/KERNEL/ChromatogramPeak.h>
Public Member Functions
bool operator() (const ChromatogramPeak &left, const ChromatogramPeak &right) const
bool operator() (const ChromatogramPeak &left, const PositionType &right) const
bool operator() (const PositionType &left, const ChromatogramPeak &right) const
bool operator() (const PositionType &left, const PositionType &right) const
Detailed Description
Comparator by position. As this class has dimension 1, this is basically an alias for RTLess.
Member Function Documentation
operator()() [1/4]
bool operator() (const ChromatogramPeak & left, const ChromatogramPeak & right) const inline
References ChromatogramPeak::getPosition().
operator()() [2/4]
bool operator() (const ChromatogramPeak & left, const PositionType & right) const inline
References ChromatogramPeak::getPosition().
operator()() [3/4]
bool operator() (const PositionType & left, const ChromatogramPeak & right) const inline
References ChromatogramPeak::getPosition().
operator()() [4/4]
bool operator() (const PositionType & left, const PositionType & right) const inline