OpenMS: BaseFeature::QualityLess Struct Reference
BaseFeature::QualityLess Struct Reference
Compare by quality.
#include <OpenMS/KERNEL/BaseFeature.h>
Public Member Functions
bool operator() (const BaseFeature &left, const BaseFeature &right) const
bool operator() (const BaseFeature &left, const QualityType &right) const
bool operator() (const QualityType &left, const BaseFeature &right) const
bool operator() (const QualityType &left, const QualityType &right) const
Detailed Description
Compare by quality.
Member Function Documentation
operator()() [1/4]
bool operator() (const BaseFeature & left, const BaseFeature & right) const inline
References BaseFeature::getQuality().
operator()() [2/4]
bool operator() (const BaseFeature & left, const QualityType & right) const inline
References BaseFeature::getQuality().
operator()() [3/4]
bool operator() (const QualityType & left, const BaseFeature & right) const inline
References BaseFeature::getQuality().
operator()() [4/4]
bool operator() (const QualityType & left, const QualityType & right) const inline