OpenMS: BaseFeature Class Reference
BaseFeature Class Reference
Kernel
A basic LC-MS feature.
#include <OpenMS/KERNEL/BaseFeature.h>
Classes
struct QualityLess
Compare by quality.
Public Member Functions
Constructors and Destructor
BaseFeature ()
Default constructor.
BaseFeature (const BaseFeature &feature)=default
Copy constructor.
BaseFeature (BaseFeature &&feature)=default
Move constructor.
BaseFeature (const BaseFeature &rhs, UInt64 map_index)
Copy constructor with a new map_index.
BaseFeature (const Peak2D &point)
Constructor from raw data point.
BaseFeature (const RichPeak2D &point)
Constructor from raw data point with meta information.
~BaseFeature () override
Destructor.
Public Member Functions inherited from RichPeak2D
RichPeak2D ()
Default constructor.
RichPeak2D (const RichPeak2D &p)=default
Copy constructor.
RichPeak2D (const Peak2D &p)
Constructor from Peak2D.
RichPeak2D (const PositionType &pos, const IntensityType in)
Member constructor.
RichPeak2D (RichPeak2D &&p)=default
Move constructor.
~RichPeak2D () override
Destructor.
RichPeak2D & operator= (const RichPeak2D &rhs)=default
Assignment operator.
RichPeak2D & operator= (RichPeak2D &&rhs) &=default
Move Assignment operator.
RichPeak2D & operator= (const Peak2D &rhs)
Assignment operator.
bool operator== (const RichPeak2D &rhs) const
Equality operator.
bool operator!= (const RichPeak2D &rhs) const
Equality operator.
Public Member Functions inherited from Peak2D
Peak2D & operator= (const Peak2D &rhs)=default
Assignment operator.
Peak2D & operator= (Peak2D &&) &=default
Move assignment operator.
bool operator== (const Peak2D &rhs) const
Equality operator.
bool operator!= (const Peak2D &rhs) const
Equality operator.
Peak2D ()
Peak2D (const PositionType &pos, const IntensityType in)
Member constructor.
Peak2D (const Peak2D &p)=default
Copy constructor.
Peak2D (Peak2D &&)=default
Move constructor.
~Peak2D ()
Destructor.
IntensityType getIntensity () const
void setIntensity (IntensityType intensity)
Non-mutable access to the data point intensity (height)
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (const PositionType &position)
Mutable access to the position.
CoordinateType getMZ () const
Returns the m/z coordinate (index 1)
void setMZ (CoordinateType coordinate)
Mutable access to the m/z coordinate (index 1)
CoordinateType getRT () const
Returns the RT coordinate (index 0)
void setRT (CoordinateType coordinate)
Mutable access to the RT coordinate (index 0)
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from UniqueIdInterface
UniqueIdInterface ()
Default constructor - the unique id will be invalid
UniqueIdInterface (const UniqueIdInterface &rhs)=default
Copy constructor - copies the unique id.
UniqueIdInterface (UniqueIdInterface &&rhs)=default
Move constructor.
UniqueIdInterface & operator= (UniqueIdInterface const &rhs)=default
Assignment operator - copies the unique id.
UniqueIdInterface & operator= (UniqueIdInterface &&) &=default
Move Assignment operator - copies the unique id.
virtual ~UniqueIdInterface ()=default
Destructor.
bool operator== (UniqueIdInterface const &rhs) const
Equality comparison operator - the unique ids must be equal (!)
UInt64 getUniqueId () const
Non-mutable access to unique id - returns the unique id.
Size clearUniqueId ()
Clear the unique id. The new unique id will be invalid. Returns 1 if the unique id was changed, 0 otherwise.
void swap (UniqueIdInterface &from)
Size hasValidUniqueId () const
Returns whether the unique id is valid. Returns 1 if the unique id is valid, 0 otherwise.
Size hasInvalidUniqueId () const
Returns whether the unique id is invalid. Returns 1 if the unique id is invalid, 0 otherwise.
Size setUniqueId ()
Assigns a new, valid unique id. Always returns 1.
Size ensureUniqueId ()
Assigns a valid unique id, but only if the present one is invalid. Returns 1 if the unique id was changed, 0 otherwise.
void setUniqueId (UInt64 rhs)
Assigns the given unique id.
void setUniqueId (const String &rhs)
Mutable access to unique id.
Type definitions
enum AnnotationState {
FEATURE_ID_NONE, FEATURE_ID_SINGLE, FEATURE_ID_MULTIPLE_SAME, FEATURE_ID_MULTIPLE_DIVERGENT,
SIZE_OF_ANNOTATIONSTATE
}
state of identification, use getIDState() to query it
typedef float QualityType
Type of quality values.
typedef Int ChargeType
Type of charge values.
typedef float WidthType
Type of feature width/FWHM (RT)
static const std::string NamesOfAnnotationState [SIZE_OF_ANNOTATIONSTATE]
Quality methods
QualityType quality_
Overall quality measure of the feature.
ChargeType charge_
Charge of the peptide represented by this feature. The default value is 0, which represents an unknown charge state.
WidthType width_
Width (FWHM) for the feature. The default value is 0.0, a feature finding algorithm can compute this form the model.
std::vector< PeptideIdentification > peptides_
Peptide PeptideIdentifications belonging to the feature.
QualityType getQuality () const
Non-mutable access to the overall quality.
void setQuality (QualityType q)
Set the overall quality.
WidthType getWidth () const
Non-mutable access to the features width (full width at half max, FWHM)
void setWidth (WidthType fwhm)
Set the width of the feature (FWHM)
const ChargeType & getCharge () const
Non-mutable access to charge state.
void setCharge (const ChargeType &ch)
Set charge state.
BaseFeature & operator= (const BaseFeature &rhs)=default
Assignment operator.
BaseFeature & operator= (BaseFeature &&rhs) &=default
Move Assignment operator.
bool operator== (const BaseFeature &rhs) const
Equality operator.
bool operator!= (const BaseFeature &rhs) const
Inequality operator.
const std::vector< PeptideIdentification > & getPeptideIdentifications () const
returns a const reference to the PeptideIdentification vector
std::vector< PeptideIdentification > & getPeptideIdentifications ()
returns a mutable reference to the PeptideIdentification vector
void setPeptideIdentifications (const std::vector< PeptideIdentification > &peptides)
sets the PeptideIdentification vector
AnnotationState getAnnotationState () const
state of peptide identifications attached to this feature. If one ID has multiple hits, the output depends on the top-hit only
Additional Inherited Members
Public Types inherited from Peak2D
typedef float IntensityType
Intensity type.
typedef double CoordinateType
Coordinate type (of the position)
typedef DPosition< 2 > PositionType
Position type.
enum DimensionDescription { RT = 0, MZ = 1, DIMENSION = 2 }
This enum maps the symbolic names of the dimensions to numbers.
Public Types inherited from UniqueIdInterface
enum { INVALID = 0 }
This is the invalid unique id (cast it to a UInt64 if you like)
Static Public Member Functions inherited from Peak2D
static const char * shortDimensionName (UInt const dim)
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameRT ()
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameMZ ()
Short name of the dimension (abbreviated form)
static const char * fullDimensionName (UInt const dim)
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameRT ()
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameMZ ()
Full name of the dimension (self-explanatory form)
static const char * shortDimensionUnit (UInt const dim)
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitRT ()
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitMZ ()
Unit of measurement (abbreviated form)
static const char * fullDimensionUnit (UInt const dim)
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitRT ()
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitMZ ()
Unit of measurement (self-explanatory form)
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Member Functions inherited from UniqueIdInterface
static bool isValid (UInt64 unique_id)
Returns true if the unique_id is valid, false otherwise.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from Peak2D
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from UniqueIdInterface
UInt64 unique_id_
the unique id
Static Protected Attributes inherited from Peak2D
static const char *const dimension_name_short_ [DIMENSION]
Short name of the dimension (abbreviated form)
static const char *const dimension_name_full_ [DIMENSION]
Full name of the dimension (self-explanatory form)
static const char *const dimension_unit_short_ [DIMENSION]
Unit of measurement (abbreviated form)
static const char *const dimension_unit_full_ [DIMENSION]
Unit of measurement (self-explanatory form)
Detailed Description
A basic LC-MS feature.
This class represents a "minimal" feature, defined by a position in RT and m/z, intensity, charge, quality, and annotated peptides. Most classes dealing with features will use the subclasses Feature or ConsensusFeature directly. However, algorithms that rely on very general characteristics of features can use this class to provide a unified solution for both "normal" features and consensus features.
Member Typedef Documentation
ChargeType
typedef Int ChargeType
Type of charge values.
QualityType
typedef float QualityType
Type of quality values.
WidthType
typedef float WidthType
Type of feature width/FWHM (RT)
Member Enumeration Documentation
AnnotationState
enum AnnotationState
state of identification, use getIDState() to query it
Enumerator
FEATURE_ID_NONE
FEATURE_ID_SINGLE
FEATURE_ID_MULTIPLE_SAME
FEATURE_ID_MULTIPLE_DIVERGENT
SIZE_OF_ANNOTATIONSTATE
Constructor & Destructor Documentation
BaseFeature() [1/6]
BaseFeature ()
Default constructor.
BaseFeature() [2/6]
BaseFeature (const BaseFeature & feature) default
Copy constructor.
BaseFeature() [3/6]
BaseFeature (BaseFeature && feature) default
Move constructor.
BaseFeature() [4/6]
BaseFeature (const BaseFeature & rhs, UInt64 map_index)
Copy constructor with a new map_index.
BaseFeature() [5/6]
BaseFeature (const Peak2D & point) explicit
Constructor from raw data point.
BaseFeature() [6/6]
BaseFeature (const RichPeak2D & point) explicit
Constructor from raw data point with meta information.
~BaseFeature()
~BaseFeature () override
Destructor.
Member Function Documentation
getAnnotationState()
AnnotationState getAnnotationState () const
state of peptide identifications attached to this feature. If one ID has multiple hits, the output depends on the top-hit only
getCharge()
const ChargeType& getCharge () const
Non-mutable access to charge state.
Referenced by TOPPGNPSExport::main_().
getPeptideIdentifications() [1/2]
std::vector<PeptideIdentification>& getPeptideIdentifications ()
returns a mutable reference to the PeptideIdentification vector
getPeptideIdentifications() [2/2]
const std::vector<PeptideIdentification>& getPeptideIdentifications () const
returns a const reference to the PeptideIdentification vector
Referenced by TOPPGNPSExport::main_(), and FeatureFinderIdentificationAlgorithm::FeatureFilterPeptides::operator()().
getQuality()
QualityType getQuality () const
Non-mutable access to the overall quality.
Referenced by BaseFeature::QualityLess::operator()().
getWidth()
WidthType getWidth () const
Non-mutable access to the features width (full width at half max, FWHM)
operator!=()
bool operator!= (const BaseFeature & rhs) const
Inequality operator.
operator=() [1/2]
BaseFeature& operator= (BaseFeature && rhs) & default
Move Assignment operator.
operator=() [2/2]
BaseFeature& operator= (const BaseFeature & rhs) default
Assignment operator.
operator==()
bool operator== (const BaseFeature & rhs) const
Equality operator.
setCharge()
void setCharge (const ChargeType & ch)
Set charge state.
Referenced by MsInspectFile::load(), SpecArrayFile::load(), and IsotopeWaveletTransform< PeakType >::mapSeeds2Features().
setPeptideIdentifications()
void setPeptideIdentifications (const std::vector< PeptideIdentification > & peptides)
sets the PeptideIdentification vector
setQuality()
void setQuality (QualityType q)
Set the overall quality.
setWidth()
void setWidth (WidthType fwhm)
Set the width of the feature (FWHM)
Member Data Documentation
charge_
ChargeType charge_ protected
Charge of the peptide represented by this feature. The default value is 0, which represents an unknown charge state.
NamesOfAnnotationState
const std::string NamesOfAnnotationState[SIZE_OF_ANNOTATIONSTATE] static
peptides_
std::vector<PeptideIdentification> peptides_ protected
Peptide PeptideIdentifications belonging to the feature.
quality_
QualityType quality_ protected
Overall quality measure of the feature.
width_
WidthType width_ protected
Width (FWHM) for the feature. The default value is 0.0, a feature finding algorithm can compute this form the model.