OpenMS: ChromatogramPeak Class Reference
ChromatogramPeak Class Reference
Kernel
A 1-dimensional raw data point or peak for chromatograms.
#include <OpenMS/KERNEL/ChromatogramPeak.h>
Classes
struct IntensityLess
Comparator by intensity.
struct PositionLess
Comparator by position. As this class has dimension 1, this is basically an alias for RTLess.
struct RTLess
Comparator by RT position.
Public Types
Type definitions
enum { DIMENSION = 1 }
Dimension.
typedef double IntensityType
Intensity type.
typedef DPosition< 1 > PositionType
Position type.
typedef double CoordinateType
Coordinate type.
Public Member Functions
Constructors and Destructor
ChromatogramPeak ()
Default constructor.
ChromatogramPeak (const ChromatogramPeak &p)
Copy constructor.
ChromatogramPeak (const PositionType retention_time, const IntensityType intensity)
Constructor with position and intensity.
~ChromatogramPeak ()
Destructor.
Accessors
IntensityType getIntensity () const
Non-mutable access to the data point intensity (height)
void setIntensity (IntensityType intensity)
Mutable access to the data point intensity (height)
CoordinateType getRT () const
Non-mutable access to RT.
void setRT (CoordinateType rt)
Mutable access to RT.
CoordinateType getPos () const
Alias for getRT()
void setPos (CoordinateType pos)
Alias for setRT()
CoordinateType getMZ () const
Alias for getRT()
void setMZ (CoordinateType rt)
Alias for setRT()
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (PositionType const &position)
Mutable access to the position.
ChromatogramPeak & operator= (const ChromatogramPeak &rhs)
Assignment operator.
bool operator== (const ChromatogramPeak &rhs) const
Equality operator.
bool operator!= (const ChromatogramPeak &rhs) const
Equality operator.
Protected Attributes
Comparator classes.
These classes implement binary predicates that can be used to compare two peaks with respect to their intensities, positions.
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Detailed Description
A 1-dimensional raw data point or peak for chromatograms.
This datastructure is intended for chromatograms. If you want to annotated single peaks with meta data, use RichChromatogramPeak instead.
Member Typedef Documentation
CoordinateType
typedef double CoordinateType
Coordinate type.
IntensityType
typedef double IntensityType
Intensity type.
PositionType
typedef DPosition<1> PositionType
Position type.
Member Enumeration Documentation
anonymous enum
anonymous enum
Dimension.
Enumerator
DIMENSION
Constructor & Destructor Documentation
ChromatogramPeak() [1/3]
ChromatogramPeak () inline
Default constructor.
ChromatogramPeak() [2/3]
ChromatogramPeak (const ChromatogramPeak & p) inline
Copy constructor.
ChromatogramPeak() [3/3]
ChromatogramPeak (const PositionType retention_time, const IntensityType intensity) inline
Constructor with position and intensity.
~ChromatogramPeak()
~ChromatogramPeak () inline
Destructor.
Note
The destructor is non-virtual although many classes are derived from ChromatogramPeak. This is intentional, since otherwise we would "waste" space for a vtable pointer in each instance. Normally you should not derive other classes from ChromatogramPeak (unless you know what you are doing, of course).
Member Function Documentation
getIntensity()
IntensityType getIntensity () const inline
Non-mutable access to the data point intensity (height)
Referenced by ChromatogramPeak::IntensityLess::operator()().
getMZ()
CoordinateType getMZ () const inline
Alias for getRT()
getPos()
CoordinateType getPos () const inline
Alias for getRT()
Referenced by ChromatogramPeak::RTLess::operator()().
getPosition() [1/2]
PositionType& getPosition () inline
Mutable access to the position.
getPosition() [2/2]
const PositionType& getPosition () const inline
Non-mutable access to the position.
Referenced by ChromatogramPeak::PositionLess::operator()().
getRT()
CoordinateType getRT () const inline
Non-mutable access to RT.
Referenced by ChromatogramPeak::RTLess::operator()().
operator!=()
bool operator!= (const ChromatogramPeak & rhs) const inline
Equality operator.
References KDTree::operator==().
operator=()
ChromatogramPeak& operator= (const ChromatogramPeak & rhs) inline
Assignment operator.
References ChromatogramPeak::intensity_, and ChromatogramPeak::position_.
operator==()
bool operator== (const ChromatogramPeak & rhs) const inline
Equality operator.
References ChromatogramPeak::intensity_, and ChromatogramPeak::position_.
setIntensity()
void setIntensity (IntensityType intensity) inline
Mutable access to the data point intensity (height)
Referenced by ChromatogramTools::convertSpectraToChromatograms().
setMZ()
void setMZ (CoordinateType rt) inline
Alias for setRT()
setPos()
void setPos (CoordinateType pos) inline
Alias for setRT()
setPosition()
void setPosition (PositionType const & position) inline
Mutable access to the position.
References seqan::position().
setRT()
void setRT (CoordinateType rt) inline
Mutable access to RT.
Referenced by ChromatogramTools::convertSpectraToChromatograms().
Member Data Documentation
intensity_
IntensityType intensity_ protected
The data point intensity.
Referenced by ChromatogramPeak::operator=(), and ChromatogramPeak::operator==().
position_
PositionType position_ protected
The data point position.
Referenced by ChromatogramPeak::operator=(), and ChromatogramPeak::operator==().