OpenMS: MSSpectrum Class Reference
MSSpectrum Class Reference
Kernel
The representation of a 1D spectrum.
#include <OpenMS/KERNEL/MSSpectrum.h>
Classes
struct RTLess
Comparator for the retention time.
Public Types
Base type definitions
typedef OpenMS::Peak1D PeakType
Peak type.
typedef PeakType::CoordinateType CoordinateType
Coordinate (m/z) type.
typedef std::vector< PeakType > ContainerType
Spectrum base type.
typedef OpenMS::DataArrays::FloatDataArray FloatDataArray
Float data array vector type.
typedef std::vector< FloatDataArray > FloatDataArrays
typedef OpenMS::DataArrays::StringDataArray StringDataArray
String data array vector type.
typedef std::vector< StringDataArray > StringDataArrays
typedef OpenMS::DataArrays::IntegerDataArray IntegerDataArray
Integer data array vector type.
typedef std::vector< IntegerDataArray > IntegerDataArrays
Peak container iterator type definitions
typedef ContainerType::iterator Iterator
Mutable iterator.
typedef ContainerType::const_iterator ConstIterator
Non-mutable iterator.
typedef ContainerType::reverse_iterator ReverseIterator
Mutable reverse iterator.
typedef ContainerType::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
Public Types inherited from RangeManager< 1 >
enum
Dimension of the position range.
typedef DRange< D > PositionRangeType
Position range type.
typedef DPosition< D > PositionType
Position Type.
typedef DRange< 1 > IntensityRangeType
Intensity range type.
Public Types inherited from SpectrumSettings
enum SpectrumType { UNKNOWN, CENTROID, PROFILE, SIZE_OF_SPECTRUMTYPE }
Spectrum peak type.
Public Member Functions
Accessors for meta information
Returns the absolute retention time (in seconds)
double getRT () const
void setRT (double rt)
Sets the absolute retention time (in seconds)
double getDriftTime () const
Returns the ion mobility drift time (-1 means it is not set)
void setDriftTime (double dt)
Sets the ion mobility drift time.
DriftTimeUnit getDriftTimeUnit () const
Returns the ion mobility drift time unit.
void setDriftTimeUnit (DriftTimeUnit dt)
Sets the ion mobility drift time unit.
UInt getMSLevel () const
Returns the MS level.
void setMSLevel (UInt ms_level)
Sets the MS level.
const String & getName () const
Returns the name.
void setName (const String &name)
Sets the name.
Peak data array methods
These methods are used to annotate each peak in a spectrum with meta information. It is an intermediate way between storing the information in the peak's MetaInfoInterface and deriving a new peak type with members for this information.
These statements should help you chose which approach to use
Access to meta info arrays is slower than to a member variable
Access to meta info arrays is faster than to a MetaInfoInterface
Meta info arrays are stored when using mzML format for storing
const FloatDataArrays & getFloatDataArrays () const
Returns a const reference to the float meta data arrays.
FloatDataArrays & getFloatDataArrays ()
Returns a mutable reference to the float meta data arrays.
void setFloatDataArrays (const FloatDataArrays &fda)
Sets the float meta data arrays.
const StringDataArrays & getStringDataArrays () const
Returns a const reference to the string meta data arrays.
StringDataArrays & getStringDataArrays ()
Returns a mutable reference to the string meta data arrays.
void setStringDataArrays (const StringDataArrays &sda)
Sets the string meta data arrays.
const IntegerDataArrays & getIntegerDataArrays () const
Returns a const reference to the integer meta data arrays.
IntegerDataArrays & getIntegerDataArrays ()
Returns a mutable reference to the integer meta data arrays.
void setIntegerDataArrays (const IntegerDataArrays &ida)
Sets the integer meta data arrays.
Sorting peaks
void sortByIntensity (bool reverse=false)
Lexicographically sorts the peaks by their intensity.
void sortByPosition ()
Lexicographically sorts the peaks by their position.
bool isSorted () const
Checks if all peaks are sorted with respect to ascending m/z.
Public Member Functions inherited from RangeManager< 1 >
RangeManager ()
Default constructor.
RangeManager (const RangeManager &rhs)
Copy constructor.
RangeManager (RangeManager &&) noexcept=default
Move constructor.
virtual ~RangeManager ()
Destructor.
RangeManager & operator= (const RangeManager &rhs)
Assignment operator.
bool operator== (const RangeManager &rhs) const
Equality operator.
bool operator!= (const RangeManager &rhs) const
Equality operator.
const PositionType & getMin () const
Returns the minimum position.
const PositionType & getMax () const
Returns the maximum position.
double getMinInt () const
Returns the minimum intensity.
double getMaxInt () const
Returns the maximum intensity.
void clearRanges ()
Resets the ranges.
Public Member Functions inherited from SpectrumSettings
SpectrumSettings ()
Constructor.
SpectrumSettings (const SpectrumSettings &)=default
Copy constructor.
SpectrumSettings (SpectrumSettings &&)=default
Move constructor.
~SpectrumSettings ()
Destructor.
SpectrumSettings & operator= (const SpectrumSettings &)=default
SpectrumSettings & operator= (SpectrumSettings &&) &=default
Move assignment operator.
bool operator== (const SpectrumSettings &rhs) const
Equality operator.
bool operator!= (const SpectrumSettings &rhs) const
Equality operator.
void unify (const SpectrumSettings &rhs)
merge another spectrum setting into this one (data is usually appended, except for spectrum type which needs to be unambiguous to be kept)
SpectrumType getType () const
returns the spectrum type (centroided (PEAKS) or profile data (RAW))
void setType (SpectrumType type)
sets the spectrum type
const String & getNativeID () const
returns the native identifier for the spectrum, used by the acquisition software.
void setNativeID (const String &native_id)
sets the native identifier for the spectrum, used by the acquisition software.
const String & getComment () const
returns the free-text comment
void setComment (const String &comment)
sets the free-text comment
const InstrumentSettings & getInstrumentSettings () const
returns a const reference to the instrument settings of the current spectrum
InstrumentSettings & getInstrumentSettings ()
returns a mutable reference to the instrument settings of the current spectrum
void setInstrumentSettings (const InstrumentSettings &instrument_settings)
sets the instrument settings of the current spectrum
const AcquisitionInfo & getAcquisitionInfo () const
returns a const reference to the acquisition info
AcquisitionInfo & getAcquisitionInfo ()
returns a mutable reference to the acquisition info
void setAcquisitionInfo (const AcquisitionInfo &acquisition_info)
sets the acquisition info
const SourceFile & getSourceFile () const
returns a const reference to the source file
SourceFile & getSourceFile ()
returns a mutable reference to the source file
void setSourceFile (const SourceFile &source_file)
sets the source file
const std::vector< Precursor > & getPrecursors () const
returns a const reference to the precursors
std::vector< Precursor > & getPrecursors ()
returns a mutable reference to the precursors
void setPrecursors (const std::vector< Precursor > &precursors)
sets the precursors
const std::vector< Product > & getProducts () const
returns a const reference to the products
std::vector< Product > & getProducts ()
returns a mutable reference to the products
void setProducts (const std::vector< Product > &products)
sets the products
const std::vector< PeptideIdentification > & getPeptideIdentifications () const
returns a const reference to the PeptideIdentification vector
std::vector< PeptideIdentification > & getPeptideIdentifications ()
returns a mutable reference to the PeptideIdentification vector
void setPeptideIdentifications (const std::vector< PeptideIdentification > &identifications)
sets the PeptideIdentification vector
void setDataProcessing (const std::vector< DataProcessingPtr > &data_processing)
sets the description of the applied processing
std::vector< DataProcessingPtr > & getDataProcessing ()
returns a mutable reference to the description of the applied processing
const std::vector< boost::shared_ptr< const DataProcessing > > getDataProcessing () const
returns a const reference to the description of the applied processing
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Export methods from std::vector<Peak1D>
typedef Precursor::DriftTimeUnit DriftTimeUnit
MSSpectrum ()
Constructor.
MSSpectrum (const MSSpectrum &source)
Copy constructor.
MSSpectrum (MSSpectrum &&)=default
Move constructor.
~MSSpectrum () override
Destructor.
MSSpectrum & operator= (const MSSpectrum &source)
Assignment operator.
MSSpectrum & operator= (MSSpectrum &&) &=default
Move assignment operator.
MSSpectrum & operator= (const SpectrumSettings &source)
Assignment operator.
bool operator== (const MSSpectrum &rhs) const
Equality operator.
bool operator!= (const MSSpectrum &rhs) const
Equality operator.
void updateRanges () override
Updates minimum and maximum position/intensity.
Searching a peak or peak range
double retention_time_
Retention time.
double drift_time_
Drift time.
DriftTimeUnit drift_time_unit_
Drift time unit.
UInt ms_level_
MS level.
String name_
Name.
FloatDataArrays float_data_arrays_
Float data arrays.
StringDataArrays string_data_arrays_
String data arrays.
IntegerDataArrays integer_data_arrays_
Integer data arrays.
Size findNearest (CoordinateType mz) const
Binary search for the peak nearest to a specific m/z.
Int findNearest (CoordinateType mz, CoordinateType tolerance) const
Binary search for the peak nearest to a specific m/z given a +/- tolerance windows in Th.
Int findNearest (CoordinateType mz, CoordinateType tolerance_left, CoordinateType tolerance_right) const
Search for the peak nearest to a specific m/z given two +/- tolerance windows in Th.
Iterator MZBegin (CoordinateType mz)
Binary search for peak range begin.
Iterator MZBegin (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range begin.
Iterator MZEnd (CoordinateType mz)
Binary search for peak range end (returns the past-the-end iterator)
Iterator MZEnd (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator MZBegin (CoordinateType mz) const
Binary search for peak range begin.
ConstIterator MZBegin (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range begin.
ConstIterator MZEnd (CoordinateType mz) const
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator MZEnd (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Iterator PosBegin (CoordinateType mz)
Binary search for peak range begin.
Iterator PosBegin (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range begin.
ConstIterator PosBegin (CoordinateType mz) const
Binary search for peak range begin.
ConstIterator PosBegin (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range begin.
Iterator PosEnd (CoordinateType mz)
Binary search for peak range end (returns the past-the-end iterator)
Iterator PosEnd (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator PosEnd (CoordinateType mz) const
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator PosEnd (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
void clear (bool clear_meta_data)
Clears all data and meta data.
MSSpectrum & select (const std::vector< Size > &indices)
SpectrumSettings::SpectrumType getType (const bool query_data) const
Determine if spectrum is profile or centroided using up to three layers of information.
ConstIterator getBasePeak () const
Iterator getBasePeak ()
PeakType::IntensityType getTIC () const
compute the total ion count (sum of all peak intensities)
SpectrumType getType () const
returns the spectrum type (centroided (PEAKS) or profile data (RAW))
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Attributes inherited from SpectrumSettings
static const std::string NamesOfSpectrumType [SIZE_OF_SPECTRUMTYPE]
Names of spectrum types.
Protected Member Functions inherited from RangeManager< 1 >
void updateRanges_ (const PeakIteratorType &begin, const PeakIteratorType &end)
Updates the range using data points in the iterator range.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from RangeManager< 1 >
IntensityRangeType int_range_
Intensity range (1-dimensional)
PositionRangeType pos_range_
Position range (D-dimensional)
Protected Attributes inherited from SpectrumSettings
SpectrumType type_
String native_id_
String comment_
InstrumentSettings instrument_settings_
SourceFile source_file_
AcquisitionInfo acquisition_info_
std::vector< Precursor > precursors_
std::vector< Product > products_
std::vector< PeptideIdentification > identification_
std::vector< DataProcessingPtr > data_processing_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
The representation of a 1D spectrum.
It contains peak data and metadata about specific instrument settings, acquisition settings, description of the meta values used in the peaks and precursor info (SpectrumSettings).
Several MSSpectrum instances are contained in a peak map (MSExperiment), which is essentially a vector of spectra with additional information about the experiment.
Precursor info from SpectrumSettings should only be used if this spectrum is a tandem-MS spectrum. The precursor spectrum is the first spectrum in MSExperiment, that has a lower MS-level than the current spectrum.
Note
For range operations, see RangeUtils module!
Member Typedef Documentation
ConstIterator
typedef ContainerType::const_iterator ConstIterator
Non-mutable iterator.
ConstReverseIterator
typedef ContainerType::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
ContainerType
typedef std::vector<PeakType> ContainerType
Spectrum base type.
CoordinateType
typedef PeakType::CoordinateType CoordinateType
Coordinate (m/z) type.
DriftTimeUnit
typedef Precursor::DriftTimeUnit DriftTimeUnit
FloatDataArray
typedef OpenMS::DataArrays::FloatDataArray FloatDataArray
Float data array vector type.
FloatDataArrays
typedef std::vector<FloatDataArray> FloatDataArrays
IntegerDataArray
typedef OpenMS::DataArrays::IntegerDataArray IntegerDataArray
Integer data array vector type.
IntegerDataArrays
typedef std::vector<IntegerDataArray> IntegerDataArrays
Iterator
typedef ContainerType::iterator Iterator
Mutable iterator.
PeakType
typedef OpenMS::Peak1D PeakType
Peak type.
ReverseIterator
typedef ContainerType::reverse_iterator ReverseIterator
Mutable reverse iterator.
StringDataArray
typedef OpenMS::DataArrays::StringDataArray StringDataArray
String data array vector type.
StringDataArrays
typedef std::vector<StringDataArray> StringDataArrays
Constructor & Destructor Documentation
MSSpectrum() [1/3]
MSSpectrum ()
Constructor.
MSSpectrum() [2/3]
MSSpectrum (const MSSpectrum & source)
Copy constructor.
MSSpectrum() [3/3]
MSSpectrum (MSSpectrum &&) default
Move constructor.
~MSSpectrum()
~MSSpectrum () inline override
Destructor.
Member Function Documentation
clear()
void clear (bool clear_meta_data)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
Referenced by SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), MzMLSwathFileConsumer::consumeSwathSpectrum_(), ChromatogramTools::convertSpectraToChromatograms(), NucleicAcidSearchEngine::deisotopeAndSingleChargeMSSpectrum_(), OpenMS::expandIMSpectrum(), WindowMower::filterPeakSpectrumForTopNInJumpingWindow(), MS2File::load(), DTAFile::load(), XMassFile::load(), DTA2DFile::load(), PeakPickerIterative::pick(), and OpenMS::processDriftTimeStack().
findNearest() [1/3]
Size findNearest (CoordinateType mz) const
Binary search for the peak nearest to a specific m/z.
Parameters
mz The searched for mass-to-charge ratio searched
Returns
Returns the index of the peak.
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
Exceptions
Exception::Precondition is thrown if the spectrum is empty (not only in debug mode)
Referenced by NucleicAcidSearchEngine::deisotopeAndSingleChargeMSSpectrum_().
findNearest() [2/3]
Int findNearest (CoordinateType mz, CoordinateType tolerance) const
Binary search for the peak nearest to a specific m/z given a +/- tolerance windows in Th.
Parameters
mz The searched for mass-to-charge ratio searched
tolerance The non-negative tolerance applied to both sides of mz
Returns
Returns the index of the peak or -1 if no peak present in tolerance window or if spectrum is empty
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
Peaks exactly on borders are considered in tolerance window.
findNearest() [3/3]
Int findNearest (CoordinateType mz, CoordinateType tolerance_left, CoordinateType tolerance_right) const
Search for the peak nearest to a specific m/z given two +/- tolerance windows in Th.
Parameters
mz The searched for mass-to-charge ratio searched
tolerance_left The non-negative tolerance applied left of mz
tolerance_right The non-negative tolerance applied right of mz
Returns
Returns the index of the peak or -1 if no peak present in tolerance window or if spectrum is empty
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
Peaks exactly on borders are considered in tolerance window.
Search for the left border is done using a binary search followed by a linear scan
getBasePeak() [1/2]
Iterator getBasePeak ()
return the peak with the highest intensity. If the peak is not unique, the first peak in the container is returned. The function works correctly, even if the spectrum is unsorted.
getBasePeak() [2/2]
ConstIterator getBasePeak () const
return the peak with the highest intensity. If the peak is not unique, the first peak in the container is returned. The function works correctly, even if the spectrum is unsorted.
getDriftTime()
double getDriftTime () const
Returns the ion mobility drift time (-1 means it is not set)
Note
Drift times may be stored directly as an attribute of the spectrum (if they relate to the spectrum as a whole). In case of ion mobility spectra, the drift time of the spectrum will always be set here while the drift times attribute in the Precursor class may often be unpopulated.
getDriftTimeUnit()
DriftTimeUnit getDriftTimeUnit () const
Returns the ion mobility drift time unit.
Referenced by OpenMS::processDriftTimeStack().
getFloatDataArrays() [1/2]
FloatDataArrays& getFloatDataArrays () inline
Returns a mutable reference to the float meta data arrays.
getFloatDataArrays() [2/2]
const FloatDataArrays& getFloatDataArrays () const
Returns a const reference to the float meta data arrays.
Referenced by MetaDataBrowser::add(), MSExperiment::ContainerAdd_< ContainerValueType, false >::addData_(), TOPPViewBase::containsIMData(), OpenMS::expandIMSpectrum(), TwoDOptimization::optimizeRegionsScanwise_(), DataFilters::passes(), PeakPickerIterative::pick(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
getIntegerDataArrays() [1/2]
IntegerDataArrays& getIntegerDataArrays ()
Returns a mutable reference to the integer meta data arrays.
getIntegerDataArrays() [2/2]
const IntegerDataArrays& getIntegerDataArrays () const
Returns a const reference to the integer meta data arrays.
Referenced by MetaDataBrowser::add(), and DataFilters::passes().
getMSLevel()
UInt getMSLevel () const
Returns the MS level.
For survey scans this is 1, for MS/MS scans 2, ...
Referenced by FullSwathFileConsumer::consumeSpectrum(), ParentPeakMower::filterSpectrum(), InMSLevelRange< SpectrumType >::operator()(), IsInCollisionEnergyRange< SpectrumType >::operator()(), IsInIsolationWindowSizeRange< SpectrumType >::operator()(), IsInIsolationWindow< SpectrumType >::operator()(), PeakPickerIterative::pick(), TOPPFLASHDeconv::writePeakGroup(), and TOPPFLASHDeconv::writePeakGroupMfile().
getName()
const String& getName () const
Returns the name.
Referenced by OpenMS::expandIMSpectrum(), and PeakPickerIterative::pick().
getRT()
double getRT () const
Referenced by IsotopeWaveletTransform< PeakType >::checkPositionForPlausibility_(), GaussFilter::filter(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getRT(), IsotopeWaveletTransform< PeakType >::identifyCharge(), IsotopeWaveletTransform< PeakType >::initializeScan(), DTA2DFile::load(), IDMapper::mapPrecursorsToIdentifications(), SpectraMerger::mergeSpectra_(), InRTRange< SpectrumType >::operator()(), FLASHDeconv::PeakGroup::operator<(), FLASHDeconv::PeakGroup::operator==(), FLASHDeconv::PeakGroup::operator>(), PeakPickerIterative::pick(), NucleicAcidSearchEngine::postProcessHits_(), SpectrumLookup::readSpectra(), TOPPFLASHDeconv::writePeakGroup(), and FLASHDeconv::writePeakGroup().
getStringDataArrays() [1/2]
StringDataArrays& getStringDataArrays ()
Returns a mutable reference to the string meta data arrays.
getStringDataArrays() [2/2]
const StringDataArrays& getStringDataArrays () const
Returns a const reference to the string meta data arrays.
Referenced by MetaDataBrowser::add().
getTIC()
PeakType::IntensityType getTIC () const
compute the total ion count (sum of all peak intensities)
getType() [1/2]
SpectrumType getType
returns the spectrum type (centroided (PEAKS) or profile data (RAW))
getType() [2/2]
SpectrumSettings::SpectrumType getType (const bool query_data) const
Determine if spectrum is profile or centroided using up to three layers of information.
First, the SpectrumSettings are inquired and the type is returned unless it is unknown. Second, all data processing entries are searched for a centroiding step. If that is unsuccessful as well and query_data is true, the data is fed into PeakTypeEstimator().
Parameters
[query_data] If SpectrumSettings and DataProcessing information are not sufficient, should the data be queried? (potentially expensive)
Returns
The spectrum type (centroided, profile or unknown)
isSorted()
bool isSorted () const
Checks if all peaks are sorted with respect to ascending m/z.
MZBegin() [1/4]
ConstIterator MZBegin (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range begin.
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
MZBegin() [2/4]
Iterator MZBegin (CoordinateType mz)
Binary search for peak range begin.
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
Referenced by IsotopeWaveletTransform< PeakType >::checkPositionForPlausibility_(), IsotopeWaveletTransform< PeakType >::checkPPMTheoModel_(), IsotopeWaveletTransform< PeakType >::identifyCharge(), IsotopeWaveletTransform< PeakType >::initializeScan(), IsotopeWaveletTransform< PeakType >::mapSeeds2Features(), IsotopeWaveletTransform< PeakType >::TransSpectrum::MZBegin(), and IsotopeWaveletTransform< PeakType >::scoreThis_().
MZBegin() [3/4]
ConstIterator MZBegin (CoordinateType mz) const
Binary search for peak range begin.
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
MZBegin() [4/4]
Iterator MZBegin (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range begin.
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
MZEnd() [1/4]
ConstIterator MZEnd (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
MZEnd() [2/4]
Iterator MZEnd (CoordinateType mz)
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
Referenced by IsotopeWaveletTransform< PeakType >::identifyCharge(), IsotopeWaveletTransform< PeakType >::initializeScan(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::MZEnd().
MZEnd() [3/4]
ConstIterator MZEnd (CoordinateType mz) const
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
MZEnd() [4/4]
Iterator MZEnd (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
operator!=()
bool operator!= (const MSSpectrum & rhs) const inline
Equality operator.
References KDTree::operator==().
operator=() [1/3]
MSSpectrum& operator= (const MSSpectrum & source)
Assignment operator.
operator=() [2/3]
MSSpectrum& operator= (const SpectrumSettings & source)
Assignment operator.
operator=() [3/3]
MSSpectrum& operator= (MSSpectrum &&) & default
Move assignment operator.
operator==()
bool operator== (const MSSpectrum & rhs) const
Equality operator.
PosBegin() [1/4]
ConstIterator PosBegin (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range begin.
Alias for MZBegin()
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
PosBegin() [2/4]
Iterator PosBegin (CoordinateType mz)
Binary search for peak range begin.
Alias for MZBegin()
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
PosBegin() [3/4]
ConstIterator PosBegin (CoordinateType mz) const
Binary search for peak range begin.
Alias for MZBegin()
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
PosBegin() [4/4]
Iterator PosBegin (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range begin.
Alias for MZBegin()
Note
Make sure the spectrum is sorted with respect to m/z! Otherwise the result is undefined.
PosEnd() [1/4]
ConstIterator PosEnd (ConstIterator begin, CoordinateType mz, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Alias for MZEnd()
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
PosEnd() [2/4]
Iterator PosEnd (CoordinateType mz)
Binary search for peak range end (returns the past-the-end iterator)
Alias for MZEnd()
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
PosEnd() [3/4]
ConstIterator PosEnd (CoordinateType mz) const
Binary search for peak range end (returns the past-the-end iterator)
Alias for MZEnd()
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
PosEnd() [4/4]
Iterator PosEnd (Iterator begin, CoordinateType mz, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
Alias for MZEnd()
Note
Make sure the spectrum is sorted with respect to m/z. Otherwise the result is undefined.
select()
MSSpectrum& select (const std::vector< Size > & indices)
Referenced by WindowMower::filterPeakSpectrumForTopNInJumpingWindow(), WindowMower::filterPeakSpectrumForTopNInSlidingWindow(), ThresholdMower::filterSpectrum(), and NLargest::filterSpectrum().
setDriftTime()
void setDriftTime (double dt)
Sets the ion mobility drift time.
Referenced by OpenMS::expandIMSpectrum(), and OpenMS::processDriftTimeStack().
setDriftTimeUnit()
void setDriftTimeUnit (DriftTimeUnit dt)
Sets the ion mobility drift time unit.
Referenced by OpenMS::expandIMSpectrum(), and OpenMS::processDriftTimeStack().
setFloatDataArrays()
void setFloatDataArrays (const FloatDataArrays & fda)
Sets the float meta data arrays.
Referenced by OpenMS::expandIMSpectrum(), and OpenMS::processDriftTimeStack().
setIntegerDataArrays()
void setIntegerDataArrays (const IntegerDataArrays & ida)
Sets the integer meta data arrays.
setMSLevel()
void setMSLevel (UInt ms_level)
Sets the MS level.
Referenced by MS2File::load(), DTAFile::load(), MascotInfile::load(), XMassFile::load(), MascotGenericFile::load(), SpectraMerger::mergeSpectra_(), PeakPickerIterative::pick(), TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showSpectrumGenerationDialog().
setName()
void setName (const String & name)
Sets the name.
Referenced by OpenMS::expandIMSpectrum(), DTAFile::load(), XMassFile::load(), NucleicAcidSearchEngine::main_(), and PeakPickerIterative::pick().
setRT()
void setRT (double rt)
Sets the absolute retention time (in seconds)
Referenced by MascotGenericFile::getNextSpectrum_(), TwoDOptimization::getRegionEndpoints_(), MascotInfile::load(), XMassFile::load(), DTA2DFile::load(), SpectraMerger::mergeSpectra_(), TwoDOptimization::optimize(), and PeakPickerIterative::pick().
setStringDataArrays()
void setStringDataArrays (const StringDataArrays & sda)
Sets the string meta data arrays.
sortByIntensity()
void sortByIntensity (bool reverse = false)
Lexicographically sorts the peaks by their intensity.
Sorts the peaks according to ascending intensity. Meta data arrays will be sorted accordingly.
Referenced by WindowMower::filterPeakSpectrumForTopNInSlidingWindow(), Scaler::filterSpectrum(), and NLargest::filterSpectrum().
sortByPosition()
void sortByPosition ()
Lexicographically sorts the peaks by their position.
The spectrum is sorted with respect to position. Meta data arrays will be sorted accordingly.
Referenced by ComplementFilter::apply(), ComplementMarker::apply(), NeutralLossMarker::apply(), IsotopeMarker::apply(), NucleicAcidSearchEngine::deisotopeAndSingleChargeMSSpectrum_(), WindowMower::filterPeakSpectrumForTopNInJumpingWindow(), WindowMower::filterPeakSpectrumForTopNInSlidingWindow(), BernNorm::filterSpectrum(), SpectraMerger::mergeSpectra_(), PeakPickerIterative::pick(), NucleicAcidSearchEngine::preprocessSpectra_(), and LayerData::sortCurrentSpectrumByPosition().
updateRanges()
void updateRanges () override virtual
Updates minimum and maximum position/intensity.
This method is usually implemented by calling clearRanges() and updateRanges_().
Implements RangeManager< 1 >.
Member Data Documentation
drift_time_
double drift_time_ protected
Drift time.
drift_time_unit_
DriftTimeUnit drift_time_unit_ protected
Drift time unit.
float_data_arrays_
FloatDataArrays float_data_arrays_ protected
Float data arrays.
integer_data_arrays_
IntegerDataArrays integer_data_arrays_ protected
Integer data arrays.
ms_level_
UInt ms_level_ protected
MS level.
name_
String name_ protected
Name.
retention_time_
double retention_time_ protected
Retention time.
string_data_arrays_
StringDataArrays string_data_arrays_ protected
String data arrays.