OpenMS: FeatureMap Class Reference
FeatureMap Class Reference
Kernel
A container for features.
#include <OpenMS/KERNEL/FeatureMap.h>
Public Member Functions
Constructors and Destructor
FeatureMap ()
Default constructor.
FeatureMap (const FeatureMap &source)
Copy constructor.
~FeatureMap () override
Destructor.
FeatureMap & operator= (const FeatureMap &rhs)
Assignment operator.
bool operator== (const FeatureMap &rhs) const
Equality operator.
bool operator!= (const FeatureMap &rhs) const
Equality operator.
FeatureMap operator+ (const FeatureMap &rhs) const
Joins two feature maps.
FeatureMap & operator+= (const FeatureMap &rhs)
Add one feature map to another.
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from RangeManager< 2 >
RangeManager ()
Default constructor.
RangeManager (const RangeManager &rhs)
Copy constructor.
RangeManager (RangeManager &&) noexcept=default
Move constructor.
virtual ~RangeManager ()
Destructor.
RangeManager & operator= (const RangeManager &rhs)
Assignment operator.
bool operator== (const RangeManager &rhs) const
Equality operator.
bool operator!= (const RangeManager &rhs) const
Equality operator.
const PositionType & getMin () const
Returns the minimum position.
const PositionType & getMax () const
Returns the maximum position.
double getMinInt () const
Returns the minimum intensity.
double getMaxInt () const
Returns the maximum intensity.
void clearRanges ()
Resets the ranges.
Public Member Functions inherited from DocumentIdentifier
DocumentIdentifier ()
Default constructor.
DocumentIdentifier (const DocumentIdentifier &)=default
Copy constructor.
DocumentIdentifier (DocumentIdentifier &&)=default
Move constructor.
virtual ~DocumentIdentifier ()
Destructor.
DocumentIdentifier & operator= (const DocumentIdentifier &)=default
Assignment operator.
DocumentIdentifier & operator= (DocumentIdentifier &&) &=default
Move assignment operator.
bool operator== (const DocumentIdentifier &rhs) const
Equality operator.
void setIdentifier (const String &id)
set document identifier (e.g. an LSID)
const String & getIdentifier () const
retrieve document identifier (e.g. an LSID)
void swap (DocumentIdentifier &from)
exchange content with from
void setLoadedFilePath (const String &file_name)
set the file_name_ according to absolute path of the file loaded from preferably done whilst loading
const String & getLoadedFilePath () const
get the file_name_ which is the absolute path to the file loaded from
void setLoadedFileType (const String &file_name)
set the file_type according to the type of the file loaded from (see FileHandler::Type) preferably done whilst loading
const FileTypes::Type & getLoadedFileType () const
get the file_type (e.g. featureXML, consensusXML, mzData, mzXML, mzML, ...) of the file loaded from
Public Member Functions inherited from UniqueIdInterface
UniqueIdInterface ()
Default constructor - the unique id will be invalid
UniqueIdInterface (const UniqueIdInterface &rhs)=default
Copy constructor - copies the unique id.
UniqueIdInterface (UniqueIdInterface &&rhs)=default
Move constructor.
UniqueIdInterface & operator= (UniqueIdInterface const &rhs)=default
Assignment operator - copies the unique id.
UniqueIdInterface & operator= (UniqueIdInterface &&) &=default
Move Assignment operator - copies the unique id.
virtual ~UniqueIdInterface ()=default
Destructor.
bool operator== (UniqueIdInterface const &rhs) const
Equality comparison operator - the unique ids must be equal (!)
UInt64 getUniqueId () const
Non-mutable access to unique id - returns the unique id.
Size clearUniqueId ()
Clear the unique id. The new unique id will be invalid. Returns 1 if the unique id was changed, 0 otherwise.
void swap (UniqueIdInterface &from)
Size hasValidUniqueId () const
Returns whether the unique id is valid. Returns 1 if the unique id is valid, 0 otherwise.
Size hasInvalidUniqueId () const
Returns whether the unique id is invalid. Returns 1 if the unique id is invalid, 0 otherwise.
Size setUniqueId ()
Assigns a new, valid unique id. Always returns 1.
Size ensureUniqueId ()
Assigns a valid unique id, but only if the present one is invalid. Returns 1 if the unique id was changed, 0 otherwise.
void setUniqueId (UInt64 rhs)
Assigns the given unique id.
void setUniqueId (const String &rhs)
Mutable access to unique id.
Public Member Functions inherited from UniqueIdIndexer< FeatureMap >
Size uniqueIdToIndex (UInt64 unique_id) const
Returns the index of the feature with the given unique id, or Size(-1) if none exists in this random access container.
void updateUniqueIdToIndex () const
Updates the hash map from unique id to index.
Size resolveUniqueIdConflicts ()
Assign new UID's to doubly occurring UID's.
void swap (UniqueIdIndexer &rhs)
Swap.
Type definitions
typedef std::vector< Feature > privvec
typedef Feature FeatureType
typedef RangeManager< 2 > RangeManagerType
typedef std::vector< FeatureType > Base
typedef Base::iterator Iterator
typedef Base::const_iterator ConstIterator
typedef Base::reverse_iterator ReverseIterator
typedef Base::const_reverse_iterator ConstReverseIterator
typedef FeatureType & Reference
const typedef FeatureType & ConstReference
Sorting.
These simplified sorting methods are supported in addition to the standard sorting methods of std::vector.
std::vector< ProteinIdentification > protein_identifications_
protein identifications
std::vector< PeptideIdentification > unassigned_peptide_identifications_
peptide identifications not matched to a specific feature
std::vector< DataProcessing > data_processing_
applied data processing
void sortByIntensity (bool reverse=false)
Sorts the peaks according to ascending intensity.
void sortByPosition ()
Sort features by position. Lexicographical comparison (first RT then m/z) is done.
void sortByRT ()
Sort features by RT position.
void sortByMZ ()
Sort features by m/z position.
void sortByOverallQuality (bool reverse=false)
Sort features by ascending overall quality.
void updateRanges () override
Updates minimum and maximum position/intensity.
void swapFeaturesOnly (FeatureMap &from)
Swaps the feature content (plus its range information) of this map with the content of from.
void swap (FeatureMap &from)
const std::vector< ProteinIdentification > & getProteinIdentifications () const
non-mutable access to the protein identifications
std::vector< ProteinIdentification > & getProteinIdentifications ()
mutable access to the protein identifications
void setProteinIdentifications (const std::vector< ProteinIdentification > &protein_identifications)
sets the protein identifications
const std::vector< PeptideIdentification > & getUnassignedPeptideIdentifications () const
non-mutable access to the unassigned peptide identifications
std::vector< PeptideIdentification > & getUnassignedPeptideIdentifications ()
mutable access to the unassigned peptide identifications
void setUnassignedPeptideIdentifications (const std::vector< PeptideIdentification > &unassigned_peptide_identifications)
sets the unassigned peptide identifications
const std::vector< DataProcessing > & getDataProcessing () const
returns a const reference to the description of the applied data processing
std::vector< DataProcessing > & getDataProcessing ()
returns a mutable reference to the description of the applied data processing
void setDataProcessing (const std::vector< DataProcessing > &processing_method)
sets the description of the applied data processing
void setPrimaryMSRunPath (const StringList &s)
set the file path to the primary MS run (usually the mzML file obtained after data conversion from raw files)
void setPrimaryMSRunPath (const StringList &s, MSExperiment &e)
void getPrimaryMSRunPath (StringList &toFill) const
get the file path to the first MS run
void clear (bool clear_meta_data=true)
Clears all data and meta data.
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)())
Applies a member function of Type to the container itself and all features (including subordinates). The returned values are accumulated.
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)() const) const
The "const" variant.
AnnotationStatistics getAnnotationStatistics () const
Additional Inherited Members
Public Types inherited from RangeManager< 2 >
enum
Dimension of the position range.
typedef DRange< D > PositionRangeType
Position range type.
typedef DPosition< D > PositionType
Position Type.
typedef DRange< 1 > IntensityRangeType
Intensity range type.
Public Types inherited from UniqueIdInterface
enum { INVALID = 0 }
This is the invalid unique id (cast it to a UInt64 if you like)
Public Types inherited from UniqueIdIndexer< FeatureMap >
typedef boost::unordered_map< UInt64, Size > UniqueIdMap
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Member Functions inherited from UniqueIdInterface
static bool isValid (UInt64 unique_id)
Returns true if the unique_id is valid, false otherwise.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Member Functions inherited from RangeManager< 2 >
void updateRanges_ (const PeakIteratorType &begin, const PeakIteratorType &end)
Updates the range using data points in the iterator range.
Protected Member Functions inherited from UniqueIdIndexer< FeatureMap >
const FeatureMap & getBase_ () const
A little helper to get access to the base (!) class RandomAccessContainer.
FeatureMap & getBase_ ()
A little helper to get access to the base (!) class RandomAccessContainer.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from RangeManager< 2 >
IntensityRangeType int_range_
Intensity range (1-dimensional)
PositionRangeType pos_range_
Position range (D-dimensional)
Protected Attributes inherited from DocumentIdentifier
String id_
the ID (e.g. LSID)
String file_path_
the path to the loaded file
FileTypes::Type file_type_
the type of the loaded file
Protected Attributes inherited from UniqueIdInterface
UInt64 unique_id_
the unique id
Protected Attributes inherited from UniqueIdIndexer< FeatureMap >
UniqueIdMap uniqueid_to_index_
hash map from unique id to index of features
Detailed Description
A container for features.
A feature map is a container holding features, which represent chemical entities (peptides, proteins, small molecules etc.) found in an LC-MS/MS experiment.
Maps are implemented as vectors of features and have basically the same interface as an STL vector has (model of Random Access Container and Back Insertion Sequence).
Feature maps are typically created from peak data of 2D runs through the FeatureFinder.
Member Typedef Documentation
Base
typedef std::vector<FeatureType> Base
ConstIterator
typedef Base::const_iterator ConstIterator
ConstReverseIterator
typedef Base::const_reverse_iterator ConstReverseIterator
FeatureType
typedef Feature FeatureType
Iterator
typedef Base::iterator Iterator
privvec
typedef std::vector<Feature> privvec
RangeManagerType
typedef RangeManager<2> RangeManagerType
Reference
typedef FeatureType& Reference
ReverseIterator
typedef Base::reverse_iterator ReverseIterator
Constructor & Destructor Documentation
FeatureMap() [1/2]
FeatureMap ()
Default constructor.
FeatureMap() [2/2]
FeatureMap (const FeatureMap & source)
Copy constructor.
~FeatureMap()
~FeatureMap () override
Destructor.
Member Function Documentation
applyMemberFunction() [1/2]
Size applyMemberFunction (Size(Type::*)() const member_function) const inline
The "const" variant.
applyMemberFunction() [2/2]
Size applyMemberFunction (Size(Type::*)() member_function) inline
Applies a member function of Type to the container itself and all features (including subordinates). The returned values are accumulated.
Example: The following will print the number of features with invalid unique ids (plus 1 if the container has an invalid UID as well):
FeatureMap fm;
(...)
std::cout << fm.applyMemberFunction(&UniqueIdInterface::hasInvalidUniqueId) << std::endl;
See e.g. UniqueIdInterface for what else can be done this way.
clear()
void clear (bool clear_meta_data = true)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
getAnnotationStatistics()
AnnotationStatistics getAnnotationStatistics () const
getDataProcessing() [1/2]
std::vector<DataProcessing>& getDataProcessing ()
returns a mutable reference to the description of the applied data processing
getDataProcessing() [2/2]
const std::vector<DataProcessing>& getDataProcessing () const
returns a const reference to the description of the applied data processing
getPrimaryMSRunPath()
void getPrimaryMSRunPath (StringList & toFill) const
get the file path to the first MS run
getProteinIdentifications() [1/2]
std::vector<ProteinIdentification>& getProteinIdentifications ()
mutable access to the protein identifications
getProteinIdentifications() [2/2]
const std::vector<ProteinIdentification>& getProteinIdentifications () const
non-mutable access to the protein identifications
Referenced by MetaDataBrowser::add(), and TOPPViewBase::annotateWithID().
getUnassignedPeptideIdentifications() [1/2]
std::vector<PeptideIdentification>& getUnassignedPeptideIdentifications ()
mutable access to the unassigned peptide identifications
getUnassignedPeptideIdentifications() [2/2]
const std::vector<PeptideIdentification>& getUnassignedPeptideIdentifications () const
non-mutable access to the unassigned peptide identifications
Referenced by MetaDataBrowser::add().
operator!=()
bool operator!= (const FeatureMap & rhs) const
Equality operator.
operator+()
FeatureMap operator+ (const FeatureMap & rhs) const
Joins two feature maps.
Features are merged into one container (see operator+= for details).
operator+=()
FeatureMap& operator+= (const FeatureMap & rhs)
Add one feature map to another.
Features are merged into one container, simply by appending. UnassignedPeptides and ProteinIdentifications are appended. Information on DocumentIdentifier, UniqueIdInterface (of container only) are reset to default.
For conflicting UID's, new UID's will be assigned.
Parameters
rhs The feature to add to this one.
operator=()
FeatureMap& operator= (const FeatureMap & rhs)
Assignment operator.
operator==()
bool operator== (const FeatureMap & rhs) const
Equality operator.
setDataProcessing()
void setDataProcessing (const std::vector< DataProcessing > & processing_method)
sets the description of the applied data processing
setPrimaryMSRunPath() [1/2]
void setPrimaryMSRunPath (const StringList & s)
set the file path to the primary MS run (usually the mzML file obtained after data conversion from raw files)
Referenced by UTILProteomicsLFQ::quantifyFraction_().
setPrimaryMSRunPath() [2/2]
void setPrimaryMSRunPath (const StringList & s, MSExperiment & e)
set the file path to the primary MS run using the mzML annotated in the MSExperiment
Parameters
e. If it doesn't exist, fallback to
s.
setProteinIdentifications()
void setProteinIdentifications (const std::vector< ProteinIdentification > & protein_identifications)
sets the protein identifications
setUnassignedPeptideIdentifications()
void setUnassignedPeptideIdentifications (const std::vector< PeptideIdentification > & unassigned_peptide_identifications)
sets the unassigned peptide identifications
sortByIntensity()
void sortByIntensity (bool reverse = false)
Sorts the peaks according to ascending intensity.
sortByMZ()
void sortByMZ ()
Sort features by m/z position.
sortByOverallQuality()
void sortByOverallQuality (bool reverse = false)
Sort features by ascending overall quality.
sortByPosition()
void sortByPosition ()
Sort features by position. Lexicographical comparison (first RT then m/z) is done.
sortByRT()
void sortByRT ()
Sort features by RT position.
swap()
void swap (FeatureMap & from)
swapFeaturesOnly()
void swapFeaturesOnly (FeatureMap & from)
Swaps the feature content (plus its range information) of this map with the content of from.
updateRanges()
void updateRanges () override virtual
Updates minimum and maximum position/intensity.
This method is usually implemented by calling clearRanges() and updateRanges_().
Implements RangeManager< 2 >.
Member Data Documentation
ConstReference
const typedef FeatureType& ConstReference
data_processing_
std::vector<DataProcessing> data_processing_ protected
applied data processing
protein_identifications_
std::vector<ProteinIdentification> protein_identifications_ protected
protein identifications
unassigned_peptide_identifications_
std::vector<PeptideIdentification> unassigned_peptide_identifications_ protected
peptide identifications not matched to a specific feature