OpenMS: MRMFeature Class Reference
MRMFeature Class Reference
A multi-chromatogram MRM feature.
#include <OpenMS/KERNEL/MRMFeature.h>
Public Types
typedef std::vector< Feature > FeatureListType
Type definitions.
Public Types inherited from Feature
typedef QualityLess OverallQualityLess
Compare by quality.
Public Types inherited from BaseFeature
enum AnnotationState {
FEATURE_ID_NONE, FEATURE_ID_SINGLE, FEATURE_ID_MULTIPLE_SAME, FEATURE_ID_MULTIPLE_DIVERGENT,
SIZE_OF_ANNOTATIONSTATE
}
state of identification, use getIDState() to query it
typedef float QualityType
Type of quality values.
typedef Int ChargeType
Type of charge values.
typedef float WidthType
Type of feature width/FWHM (RT)
Public Types inherited from Peak2D
typedef float IntensityType
Intensity type.
typedef double CoordinateType
Coordinate type (of the position)
typedef DPosition< 2 > PositionType
Position type.
enum DimensionDescription { RT = 0, MZ = 1, DIMENSION = 2 }
This enum maps the symbolic names of the dimensions to numbers.
Public Types inherited from UniqueIdInterface
enum { INVALID = 0 }
This is the invalid unique id (cast it to a UInt64 if you like)
Public Member Functions
Constructors and Destructor
MRMFeature ()
Default constructor.
MRMFeature (const MRMFeature &rhs)
Copy constructor.
MRMFeature (MRMFeature &&rhs)=default
Move constructor.
MRMFeature & operator= (const MRMFeature &rhs)
Assignment operator.
MRMFeature & operator= (MRMFeature &&) &=default
Move assignment operator.
~MRMFeature () override
Destructor.
Public Member Functions inherited from Feature
Feature ()
Default constructor.
Feature (const Feature &feature)
Copy constructor.
Feature (Feature &&) noexcept
Move constructor.
~Feature () override
Destructor.
QualityType getOverallQuality () const
Non-mutable access to the overall quality.
void setOverallQuality (QualityType q)
Set the overall quality.
QualityType getQuality (Size index) const
Non-mutable access to the quality in dimension c.
void setQuality (Size index, QualityType q)
Set the quality in dimension c.
const std::vector< ConvexHull2D > & getConvexHulls () const
Non-mutable access to the convex hulls.
std::vector< ConvexHull2D > & getConvexHulls ()
Mutable access to the convex hulls of single mass traces.
void setConvexHulls (const std::vector< ConvexHull2D > &hulls)
Set the convex hulls of single mass traces.
ConvexHull2D & getConvexHull () const
Returns the overall convex hull of the feature (calculated from the convex hulls of the mass traces)
bool encloses (double rt, double mz) const
Returns if the mass trace convex hulls of the feature enclose the position specified by rt and mz.
Feature & operator= (const Feature &rhs)
Assignment operator.
Feature & operator= (Feature &&) &noexcept
Move assignment operator.
bool operator== (const Feature &rhs) const
Equality operator.
const std::vector< Feature > & getSubordinates () const
immutable access to subordinate features
std::vector< Feature > & getSubordinates ()
mutable access to subordinate features
void setSubordinates (const std::vector< Feature > &rhs)
mutable access to subordinate features
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)())
Applies a member function of Type to the feature (including subordinates). The returned values are accumulated.
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)() const) const
The "const" variant.
Public Member Functions inherited from BaseFeature
BaseFeature ()
Default constructor.
BaseFeature (const BaseFeature &feature)=default
Copy constructor.
BaseFeature (BaseFeature &&feature)=default
Move constructor.
BaseFeature (const BaseFeature &rhs, UInt64 map_index)
Copy constructor with a new map_index.
BaseFeature (const Peak2D &point)
Constructor from raw data point.
BaseFeature (const RichPeak2D &point)
Constructor from raw data point with meta information.
~BaseFeature () override
Destructor.
QualityType getQuality () const
Non-mutable access to the overall quality.
void setQuality (QualityType q)
Set the overall quality.
WidthType getWidth () const
Non-mutable access to the features width (full width at half max, FWHM)
void setWidth (WidthType fwhm)
Set the width of the feature (FWHM)
const ChargeType & getCharge () const
Non-mutable access to charge state.
void setCharge (const ChargeType &ch)
Set charge state.
BaseFeature & operator= (const BaseFeature &rhs)=default
Assignment operator.
BaseFeature & operator= (BaseFeature &&rhs) &=default
Move Assignment operator.
bool operator== (const BaseFeature &rhs) const
Equality operator.
bool operator!= (const BaseFeature &rhs) const
Inequality operator.
const std::vector< PeptideIdentification > & getPeptideIdentifications () const
returns a const reference to the PeptideIdentification vector
std::vector< PeptideIdentification > & getPeptideIdentifications ()
returns a mutable reference to the PeptideIdentification vector
void setPeptideIdentifications (const std::vector< PeptideIdentification > &peptides)
sets the PeptideIdentification vector
AnnotationState getAnnotationState () const
state of peptide identifications attached to this feature. If one ID has multiple hits, the output depends on the top-hit only
Public Member Functions inherited from RichPeak2D
RichPeak2D ()
Default constructor.
RichPeak2D (const RichPeak2D &p)=default
Copy constructor.
RichPeak2D (const Peak2D &p)
Constructor from Peak2D.
RichPeak2D (const PositionType &pos, const IntensityType in)
Member constructor.
RichPeak2D (RichPeak2D &&p)=default
Move constructor.
~RichPeak2D () override
Destructor.
RichPeak2D & operator= (const RichPeak2D &rhs)=default
Assignment operator.
RichPeak2D & operator= (RichPeak2D &&rhs) &=default
Move Assignment operator.
RichPeak2D & operator= (const Peak2D &rhs)
Assignment operator.
bool operator== (const RichPeak2D &rhs) const
Equality operator.
bool operator!= (const RichPeak2D &rhs) const
Equality operator.
Public Member Functions inherited from Peak2D
Peak2D & operator= (const Peak2D &rhs)=default
Assignment operator.
Peak2D & operator= (Peak2D &&) &=default
Move assignment operator.
bool operator== (const Peak2D &rhs) const
Equality operator.
bool operator!= (const Peak2D &rhs) const
Equality operator.
Peak2D ()
Peak2D (const PositionType &pos, const IntensityType in)
Member constructor.
Peak2D (const Peak2D &p)=default
Copy constructor.
Peak2D (Peak2D &&)=default
Move constructor.
~Peak2D ()
Destructor.
IntensityType getIntensity () const
void setIntensity (IntensityType intensity)
Non-mutable access to the data point intensity (height)
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (const PositionType &position)
Mutable access to the position.
CoordinateType getMZ () const
Returns the m/z coordinate (index 1)
void setMZ (CoordinateType coordinate)
Mutable access to the m/z coordinate (index 1)
CoordinateType getRT () const
Returns the RT coordinate (index 0)
void setRT (CoordinateType coordinate)
Mutable access to the RT coordinate (index 0)
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from UniqueIdInterface
UniqueIdInterface ()
Default constructor - the unique id will be invalid
UniqueIdInterface (const UniqueIdInterface &rhs)=default
Copy constructor - copies the unique id.
UniqueIdInterface (UniqueIdInterface &&rhs)=default
Move constructor.
UniqueIdInterface & operator= (UniqueIdInterface const &rhs)=default
Assignment operator - copies the unique id.
UniqueIdInterface & operator= (UniqueIdInterface &&) &=default
Move Assignment operator - copies the unique id.
virtual ~UniqueIdInterface ()=default
Destructor.
bool operator== (UniqueIdInterface const &rhs) const
Equality comparison operator - the unique ids must be equal (!)
UInt64 getUniqueId () const
Non-mutable access to unique id - returns the unique id.
Size clearUniqueId ()
Clear the unique id. The new unique id will be invalid. Returns 1 if the unique id was changed, 0 otherwise.
void swap (UniqueIdInterface &from)
Size hasValidUniqueId () const
Returns whether the unique id is valid. Returns 1 if the unique id is valid, 0 otherwise.
Size hasInvalidUniqueId () const
Returns whether the unique id is invalid. Returns 1 if the unique id is invalid, 0 otherwise.
Size setUniqueId ()
Assigns a new, valid unique id. Always returns 1.
Size ensureUniqueId ()
Assigns a valid unique id, but only if the present one is invalid. Returns 1 if the unique id was changed, 0 otherwise.
void setUniqueId (UInt64 rhs)
Assigns the given unique id.
void setUniqueId (const String &rhs)
Mutable access to unique id.
Accessors
FeatureListType features_
FeatureListType precursor_features_
OpenSwath_Scores pg_scores_
peak group scores
std::map< String, int > feature_map_
map native ids to the features
std::map< String, int > precursor_feature_map_
map native ids to the precursor features
const OpenSwath_Scores & getScores () const
get all peakgroup scores
OpenSwath_Scores & getScores ()
get all peakgroup scores
Feature & getFeature (const String &key)
get a specified feature
const Feature & getFeature (const String &key) const
get a specified feature (const)
void setScores (const OpenSwath_Scores &scores)
set all peakgroup scores
void addScore (const String &score_name, double score)
set a single peakgroup score
void addFeature (const Feature &feature, const String &key)
Adds an feature from a single chromatogram into the feature.
void addFeature (Feature &&feature, const String &key)
const std::vector< Feature > & getFeatures () const
get a list of features
void getFeatureIDs (std::vector< String > &result) const
get a list of IDs of available features
void addPrecursorFeature (const Feature &feature, const String &key)
Adds a precursor feature from a single chromatogram into the feature.
void addPrecursorFeature (Feature &&feature, const String &key)
void getPrecursorFeatureIDs (std::vector< String > &result) const
get a list of IDs of available precursor features
Feature & getPrecursorFeature (String key)
get a specified precursor feature
const Feature & getPrecursorFeature (String key) const
get a specified precursor feature (const)
void IDScoresAsMetaValue (bool decoy, const OpenSwath_Ind_Scores &idscores)
Additional Inherited Members
Static Public Member Functions inherited from Peak2D
static const char * shortDimensionName (UInt const dim)
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameRT ()
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameMZ ()
Short name of the dimension (abbreviated form)
static const char * fullDimensionName (UInt const dim)
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameRT ()
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameMZ ()
Full name of the dimension (self-explanatory form)
static const char * shortDimensionUnit (UInt const dim)
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitRT ()
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitMZ ()
Unit of measurement (abbreviated form)
static const char * fullDimensionUnit (UInt const dim)
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitRT ()
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitMZ ()
Unit of measurement (self-explanatory form)
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Member Functions inherited from UniqueIdInterface
static bool isValid (UInt64 unique_id)
Returns true if the unique_id is valid, false otherwise.
Static Public Attributes inherited from BaseFeature
static const std::string NamesOfAnnotationState [SIZE_OF_ANNOTATIONSTATE]
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from Feature
QualityType qualities_ [2]
Quality measures for each dimension.
std::vector< ConvexHull2D > convex_hulls_
Array of convex hulls (one for each mass trace)
bool convex_hulls_modified_
Flag that indicates if the overall convex hull needs to be recomputed (i.e. mass trace convex hulls were modified)
ConvexHull2D convex_hull_
Overall convex hull of the feature.
std::vector< Feature > subordinates_
subordinate features (e.g. features that represent alternative explanations, usually with lower quality)
Protected Attributes inherited from BaseFeature
QualityType quality_
Overall quality measure of the feature.
ChargeType charge_
Charge of the peptide represented by this feature. The default value is 0, which represents an unknown charge state.
WidthType width_
Width (FWHM) for the feature. The default value is 0.0, a feature finding algorithm can compute this form the model.
std::vector< PeptideIdentification > peptides_
Peptide PeptideIdentifications belonging to the feature.
Protected Attributes inherited from Peak2D
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from UniqueIdInterface
UInt64 unique_id_
the unique id
Static Protected Attributes inherited from Peak2D
static const char *const dimension_name_short_ [DIMENSION]
Short name of the dimension (abbreviated form)
static const char *const dimension_name_full_ [DIMENSION]
Full name of the dimension (self-explanatory form)
static const char *const dimension_unit_short_ [DIMENSION]
Unit of measurement (abbreviated form)
static const char *const dimension_unit_full_ [DIMENSION]
Unit of measurement (self-explanatory form)
Detailed Description
A multi-chromatogram MRM feature.
An MRM feature contains corresponding features in multiple chromatograms, it is thus a representation of a peak group. The individual features in each chromatogram are represented by OpenMS Features.
Member Typedef Documentation
FeatureListType
typedef std::vector<Feature> FeatureListType
Type definitions.
Feature list type
Constructor & Destructor Documentation
MRMFeature() [1/3]
MRMFeature ()
Default constructor.
MRMFeature() [2/3]
MRMFeature (const MRMFeature & rhs)
Copy constructor.
MRMFeature() [3/3]
MRMFeature (MRMFeature && rhs) default
Move constructor.
~MRMFeature()
~MRMFeature () override
Destructor.
Member Function Documentation
addFeature() [1/2]
void addFeature (const Feature & feature, const String & key)
Adds an feature from a single chromatogram into the feature.
Referenced by MRMTransitionGroupPicker::pickFragmentChromatograms(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
addFeature() [2/2]
void addFeature (Feature && feature, const String & key)
addPrecursorFeature() [1/2]
void addPrecursorFeature (const Feature & feature, const String & key)
Adds a precursor feature from a single chromatogram into the feature.
Referenced by MRMTransitionGroupPicker::pickPrecursorChromatograms(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
addPrecursorFeature() [2/2]
void addPrecursorFeature (Feature && feature, const String & key)
addScore()
void addScore (const String & score_name, double score)
set a single peakgroup score
getFeature() [1/2]
Feature& getFeature (const String & key)
get a specified feature
Referenced by EmgScoring::calcElutionFitScore().
getFeature() [2/2]
const Feature& getFeature (const String & key) const
get a specified feature (const)
getFeatureIDs()
void getFeatureIDs (std::vector< String > & result) const
get a list of IDs of available features
getFeatures()
const std::vector<Feature>& getFeatures () const
get a list of features
getPrecursorFeature() [1/2]
Feature& getPrecursorFeature (String key)
get a specified precursor feature
getPrecursorFeature() [2/2]
const Feature& getPrecursorFeature (String key) const
get a specified precursor feature (const)
getPrecursorFeatureIDs()
void getPrecursorFeatureIDs (std::vector< String > & result) const
get a list of IDs of available precursor features
getScores() [1/2]
OpenSwath_Scores& getScores ()
get all peakgroup scores
getScores() [2/2]
const OpenSwath_Scores& getScores () const
get all peakgroup scores
IDScoresAsMetaValue()
void IDScoresAsMetaValue (bool decoy, const OpenSwath_Ind_Scores & idscores)
operator=() [1/2]
MRMFeature& operator= (const MRMFeature & rhs)
Assignment operator.
operator=() [2/2]
MRMFeature& operator= (MRMFeature &&) & default
Move assignment operator.
setScores()
void setScores (const OpenSwath_Scores & scores)
set all peakgroup scores
Member Data Documentation
feature_map_
std::map<String, int> feature_map_ protected
map native ids to the features
features_
FeatureListType features_ protected
pg_scores_
OpenSwath_Scores pg_scores_ protected
peak group scores
precursor_feature_map_
std::map<String, int> precursor_feature_map_ protected
map native ids to the precursor features
precursor_features_
FeatureListType precursor_features_ protected