OpenMS: MRMTransitionGroup< ChromatogramType, TransitionType > Class Template Reference
MRMTransitionGroup< ChromatogramType, TransitionType > Class Template Reference
The representation of a group of transitions in a targeted proteomics experiment.
#include <OpenMS/KERNEL/MRMTransitionGroup.h>
Public Types
typedef std::vector< MRMFeature > MRMFeatureListType
Type definitions.
typedef std::vector< TransitionType > TransitionsType
List of Reaction Monitoring transitions (meta data) type.
typedef ChromatogramType::PeakType PeakType
Peak type.
Public Member Functions
Constructors and Destructor
MRMTransitionGroup ()
Default constructor.
MRMTransitionGroup (const MRMTransitionGroup &rhs)
Copy Constructor.
virtual ~MRMTransitionGroup ()
Destructor.
MRMTransitionGroup & operator= (const MRMTransitionGroup &rhs)
Size size () const
const String & getTransitionGroupID () const
void setTransitionGroupID (const String &tr_gr_id)
Transition access
const std::vector< TransitionType > & getTransitions () const
std::vector< TransitionType > & getTransitionsMuteable ()
void addTransition (const TransitionType &transition, String key)
bool hasTransition (String key) const
const TransitionType & getTransition (String key)
(Fragment ion) chromatogram access
std::vector< ChromatogramType > & getChromatograms ()
const std::vector< ChromatogramType > & getChromatograms () const
void addChromatogram (const ChromatogramType &chromatogram, const String &key)
bool hasChromatogram (const String &key) const
ChromatogramType & getChromatogram (const String &key)
const ChromatogramType & getChromatogram (const String &key) const
(Precursor ion) chromatogram access
std::vector< ChromatogramType > & getPrecursorChromatograms ()
const std::vector< ChromatogramType > & getPrecursorChromatograms () const
void addPrecursorChromatogram (const ChromatogramType &chromatogram, const String &key)
bool hasPrecursorChromatogram (const String &key) const
ChromatogramType & getPrecursorChromatogram (const String &key)
const ChromatogramType & getPrecursorChromatogram (const String &key) const
MRM feature access (positions in RT where a peak was found across all chromatograms)
const std::vector< MRMFeature > & getFeatures () const
std::vector< MRMFeature > & getFeaturesMuteable ()
void addFeature (const MRMFeature &feature)
void addFeature (MRMFeature &&feature)
Helper functions
String tr_gr_id_
transition group id (peak group id)
TransitionsType transitions_
transition list
std::vector< ChromatogramType > chromatograms_
chromatogram list
std::vector< ChromatogramType > precursor_chromatograms_
precursor chromatogram list
MRMFeatureListType mrm_features_
feature list
std::map< String, int > chromatogram_map_
std::map< String, int > precursor_chromatogram_map_
std::map< String, int > transition_map_
bool isInternallyConsistent () const
Check whether internal state is consistent, e.g. same number of chromatograms and transitions are present (no runtime overhead in release mode)
bool chromatogramIdsMatch () const
Ensure that chromatogram native ids match their keys in the map.
void getLibraryIntensity (std::vector< double > &result) const
MRMTransitionGroup subset (std::vector< std::string > tr_ids) const
MRMTransitionGroup subsetDependent (std::vector< std::string > tr_ids) const
const MRMFeature & getBestFeature () const
Returns the best feature by overall quality.
bool isMappingConsistent_ () const
Checks that the mapping between chromatograms and transitions is consistent.
Detailed Description
template<typename ChromatogramType, typename TransitionType>
class OpenMS::MRMTransitionGroup< ChromatogramType, TransitionType >
The representation of a group of transitions in a targeted proteomics experiment.
The transition group carries information about the transitions (assays), the individual chromatograms as well as features found on these chromatograms.
On the one hand, the MRMTransitionGroup provides a convenient way to store the mapping between the individual transitions (containing the meta-data) and the actual chromatographic data points (measured data) relating to it. In addition, the structure allows storage of features found (regions of the chromatograms) where a potential elution peak was detected (see MRMFeature). Note that these features are usually found on the full collection of chromatograms and therefore relate to the whole collection of chromatograms.
Note that for the data structure to be consistent, it needs to have the same identifiers for the chromatograms as well as for the transitions.
Since not all the functions in OpenMS will work with MSChromatogram data structures, this needs to accept also MSSpectrum as a type for raw data storage.
Member Typedef Documentation
MRMFeatureListType
typedef std::vector<MRMFeature> MRMFeatureListType
Type definitions.
List of MRM Features type
PeakType
typedef ChromatogramType::PeakType PeakType
Peak type.
TransitionsType
typedef std::vector<TransitionType> TransitionsType
List of Reaction Monitoring transitions (meta data) type.
Constructor & Destructor Documentation
MRMTransitionGroup() [1/2]
MRMTransitionGroup () inline
Default constructor.
MRMTransitionGroup() [2/2]
MRMTransitionGroup (const MRMTransitionGroup< ChromatogramType, TransitionType > & rhs) inline
Copy Constructor.
~MRMTransitionGroup()
virtual ~MRMTransitionGroup () inline virtual
Destructor.
Member Function Documentation
addChromatogram()
void addChromatogram (const ChromatogramType & chromatogram, const String & key) inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
addFeature() [1/2]
void addFeature (const MRMFeature & feature) inline
Referenced by MRMTransitionGroupPicker::pickTransitionGroup(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
addFeature() [2/2]
void addFeature (MRMFeature && feature) inline
addPrecursorChromatogram()
void addPrecursorChromatogram (const ChromatogramType & chromatogram, const String & key) inline
Add a precursor chromatogram (extracted from an MS1 map) to the feature
While any key can be used, it is expected that the monoisotopic trace is called "Precursor_i0" and subsequent traces "Precursor_i1" etc. This policy is not enforced but highly encouraged.
Parameters
chromatogram Chromatographic traces from the MS1 map to be added
key Identifier for this trace, please use use consistent naming like "Precursor_i0", "Precursor_i1", "Precursor_i2" ...
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::subset().
addTransition()
void addTransition (const TransitionType & transition, String key) inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
chromatogramIdsMatch()
bool chromatogramIdsMatch () const inline
Ensure that chromatogram native ids match their keys in the map.
Referenced by MRMTransitionGroupPicker::createMRMFeature(), and MRMTransitionGroupPicker::pickTransitionGroup().
getBestFeature()
const MRMFeature& getBestFeature () const inline
Returns the best feature by overall quality.
For the given transition group, return the best feature as determined by the overall quality score. Requires the feature list to not be empty.
getChromatogram() [1/2]
ChromatogramType& getChromatogram (const String & key) inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::chromatogramIdsMatch(), and MRMTransitionGroupPicker::selectChromHelper_().
getChromatogram() [2/2]
const ChromatogramType& getChromatogram (const String & key) const inline
getChromatograms() [1/2]
std::vector<ChromatogramType>& getChromatograms () inline
Referenced by EmgScoring::calcElutionFitScore(), TransitionGroupOpenMS< SpectrumT, TransitionT >::getNativeIDs(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), and MRMTransitionGroupPicker::pickTransitionGroup().
getChromatograms() [2/2]
const std::vector<ChromatogramType>& getChromatograms () const inline
getFeatures()
const std::vector<MRMFeature>& getFeatures () const inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::getBestFeature().
getFeaturesMuteable()
std::vector<MRMFeature>& getFeaturesMuteable () inline
getLibraryIntensity()
void getLibraryIntensity (std::vector< double > & result) const inline
Referenced by TransitionGroupOpenMS< SpectrumT, TransitionT >::getLibraryIntensities().
getPrecursorChromatogram() [1/2]
ChromatogramType& getPrecursorChromatogram (const String & key) inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::chromatogramIdsMatch(), and MRMTransitionGroupPicker::selectChromHelper_().
getPrecursorChromatogram() [2/2]
const ChromatogramType& getPrecursorChromatogram (const String & key) const inline
getPrecursorChromatograms() [1/2]
std::vector<ChromatogramType>& getPrecursorChromatograms () inline
Referenced by MRMTransitionGroupPicker::pickPrecursorChromatograms(), and MRMTransitionGroupPicker::pickTransitionGroup().
getPrecursorChromatograms() [2/2]
const std::vector<ChromatogramType>& getPrecursorChromatograms () const inline
getTransition()
const TransitionType& getTransition (String key) inline
Referenced by MRMTransitionGroupPicker::pickTransitionGroup().
getTransitionGroupID()
const String& getTransitionGroupID () const inline
Referenced by MRMTransitionGroupPicker::createMRMFeature().
getTransitions()
const std::vector<TransitionType>& getTransitions () const inline
Referenced by MRMTransitionGroupPicker::pickFragmentChromatograms(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), and MRMTransitionGroupPicker::pickTransitionGroup().
getTransitionsMuteable()
std::vector<TransitionType>& getTransitionsMuteable () inline
hasChromatogram()
bool hasChromatogram (const String & key) const inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::getChromatogram(), MRMTransitionGroupPicker::selectChromHelper_(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
hasPrecursorChromatogram()
bool hasPrecursorChromatogram (const String & key) const inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::getPrecursorChromatogram(), and MRMTransitionGroupPicker::selectChromHelper_().
hasTransition()
bool hasTransition (String key) const inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::getTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::isMappingConsistent_(), MRMTransitionGroupPicker::pickTransitionGroup(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
isInternallyConsistent()
bool isInternallyConsistent () const inline
Check whether internal state is consistent, e.g. same number of chromatograms and transitions are present (no runtime overhead in release mode)
Referenced by MRMTransitionGroupPicker::createMRMFeature(), and MRMTransitionGroupPicker::pickTransitionGroup().
isMappingConsistent_()
bool isMappingConsistent_ () const inline protected
Checks that the mapping between chromatograms and transitions is consistent.
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::isInternallyConsistent().
operator=()
MRMTransitionGroup& operator= (const MRMTransitionGroup< ChromatogramType, TransitionType > & rhs) inline
setTransitionGroupID()
void setTransitionGroupID (const String & tr_gr_id) inline
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
size()
Size size () const inline
Referenced by EmgScoring::calcElutionFitScore(), and TransitionGroupOpenMS< SpectrumT, TransitionT >::size().
subset()
MRMTransitionGroup subset (std::vector< std::string > tr_ids) const inline
subsetDependent()
MRMTransitionGroup subsetDependent (std::vector< std::string > tr_ids) const inline
Member Data Documentation
chromatogram_map_
std::map<String, int> chromatogram_map_ protected
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::chromatogramIdsMatch(), MRMTransitionGroup< SpectrumT, TransitionT >::getChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::hasChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::isInternallyConsistent(), MRMTransitionGroup< SpectrumT, TransitionT >::isMappingConsistent_(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
chromatograms_
std::vector<ChromatogramType> chromatograms_ protected
chromatogram list
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::getChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::getChromatograms(), MRMTransitionGroup< SpectrumT, TransitionT >::isInternallyConsistent(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), MRMTransitionGroup< SpectrumT, TransitionT >::size(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
mrm_features_
MRMFeatureListType mrm_features_ protected
feature list
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addFeature(), MRMTransitionGroup< SpectrumT, TransitionT >::getFeatures(), MRMTransitionGroup< SpectrumT, TransitionT >::getFeaturesMuteable(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
precursor_chromatogram_map_
std::map<String, int> precursor_chromatogram_map_ protected
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addPrecursorChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::chromatogramIdsMatch(), MRMTransitionGroup< SpectrumT, TransitionT >::getPrecursorChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::hasPrecursorChromatogram(), and MRMTransitionGroup< SpectrumT, TransitionT >::operator=().
precursor_chromatograms_
std::vector<ChromatogramType> precursor_chromatograms_ protected
precursor chromatogram list
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addPrecursorChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::getPrecursorChromatogram(), MRMTransitionGroup< SpectrumT, TransitionT >::getPrecursorChromatograms(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
tr_gr_id_
String tr_gr_id_ protected
transition group id (peak group id)
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::getTransitionGroupID(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), MRMTransitionGroup< SpectrumT, TransitionT >::setTransitionGroupID(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().
transition_map_
std::map<String, int> transition_map_ protected
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::getTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::hasTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::isInternallyConsistent(), MRMTransitionGroup< SpectrumT, TransitionT >::isMappingConsistent_(), and MRMTransitionGroup< SpectrumT, TransitionT >::operator=().
transitions_
TransitionsType transitions_ protected
transition list
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::addTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::getLibraryIntensity(), MRMTransitionGroup< SpectrumT, TransitionT >::getTransition(), MRMTransitionGroup< SpectrumT, TransitionT >::getTransitions(), MRMTransitionGroup< SpectrumT, TransitionT >::getTransitionsMuteable(), MRMTransitionGroup< SpectrumT, TransitionT >::isInternallyConsistent(), MRMTransitionGroup< SpectrumT, TransitionT >::operator=(), MRMTransitionGroup< SpectrumT, TransitionT >::subset(), and MRMTransitionGroup< SpectrumT, TransitionT >::subsetDependent().