OpenMS: ConsensusFeature::SizeLess Struct Reference
ConsensusFeature::SizeLess Struct Reference
Compare by size(), the number of consensus elements.
#include <OpenMS/KERNEL/ConsensusFeature.h>
Public Member Functions
bool operator() (ConsensusFeature const &left, ConsensusFeature const &right) const
bool operator() (ConsensusFeature const &left, UInt64 const &right) const
bool operator() (UInt64 const &left, ConsensusFeature const &right) const
bool operator() (const UInt64 &left, const UInt64 &right) const
Detailed Description
Compare by size(), the number of consensus elements.
Member Function Documentation
operator()() [1/4]
bool operator() (ConsensusFeature const & left, ConsensusFeature const & right) const inline
References ConsensusFeature::size().
operator()() [2/4]
bool operator() (ConsensusFeature const & left, UInt64 const & right) const inline
References ConsensusFeature::size().
operator()() [3/4]
bool operator() (const UInt64 & left, const UInt64 & right) const inline
operator()() [4/4]
bool operator() (UInt64 const & left, ConsensusFeature const & right) const inline
References ConsensusFeature::size().