OpenMS: MSExperiment Class Reference
MSExperiment Class Reference
Kernel
In-Memory representation of a mass spectrometry experiment.
#include <OpenMS/KERNEL/MSExperiment.h>
Classes
struct ContainerAdd_
Helper class to add either general data points in set2DData or use mass traces from meta values.
struct ContainerAdd_< ContainerValueType, false >
struct ContainerAdd_< ContainerValueType, true >
Public Types
typedef Peak1D PeakT
typedef ChromatogramPeak ChromatogramPeakT
Base type definitions
typedef PeakT PeakType
Peak type.
typedef ChromatogramPeakT ChromatogramPeakType
Chromatogram peak type.
typedef DRange< 2 > AreaType
Area type.
typedef PeakType::CoordinateType CoordinateType
Coordinate type of peak positions.
typedef PeakType::IntensityType IntensityType
Intensity type of peaks.
typedef RangeManager< 2 > RangeManagerType
RangeManager type.
typedef MSSpectrum SpectrumType
Spectrum Type.
typedef MSChromatogram ChromatogramType
Chromatogram type.
typedef std::vector< SpectrumType > Base
STL base class type.
Iterator type definitions
typedef std::vector< SpectrumType >::iterator Iterator
Mutable iterator.
typedef std::vector< SpectrumType >::const_iterator ConstIterator
Non-mutable iterator.
typedef Internal::AreaIterator< PeakT, PeakT &, PeakT *, Iterator, SpectrumType::Iterator > AreaIterator
Mutable area iterator type (for traversal of a rectangular subset of the peaks)
typedef Internal::AreaIterator< const PeakT, const PeakT &, const PeakT *, ConstIterator, SpectrumType::ConstIterator > ConstAreaIterator
Immutable area iterator type (for traversal of a rectangular subset of the peaks)
Public Types inherited from RangeManager< 2 >
enum
Dimension of the position range.
typedef DRange< D > PositionRangeType
Position range type.
typedef DPosition< D > PositionType
Position Type.
typedef DRange< 1 > IntensityRangeType
Intensity range type.
Public Member Functions
Conversion to/from 2D data
template<class Container >
void get2DData (Container &cont) const
Reads out a 2D Spectrum.
template<class Container >
void set2DData (const Container &container)
Assignment of a data container with RT and MZ to an MSExperiment.
template<class Container >
void set2DData (const Container &container, const StringList &store_metadata_names)
Assignment of a data container with RT and MZ to an MSExperiment.
template<bool add_mass_traces, class Container >
void set2DData (const Container &container)
Assignment of a data container with RT and MZ to an MSExperiment.
Iterating ranges and areas
AreaIterator areaBegin (CoordinateType min_rt, CoordinateType max_rt, CoordinateType min_mz, CoordinateType max_mz)
Returns an area iterator for area.
AreaIterator areaEnd ()
Returns an invalid area iterator marking the end of an area.
ConstAreaIterator areaBeginConst (CoordinateType min_rt, CoordinateType max_rt, CoordinateType min_mz, CoordinateType max_mz) const
Returns a non-mutable area iterator for area.
ConstAreaIterator areaEndConst () const
Returns an non-mutable invalid area iterator marking the end of an area.
ConstIterator RTBegin (CoordinateType rt) const
Fast search for spectrum range begin.
ConstIterator RTEnd (CoordinateType rt) const
Fast search for spectrum range end (returns the past-the-end iterator)
Iterator RTBegin (CoordinateType rt)
Fast search for spectrum range begin.
Iterator RTEnd (CoordinateType rt)
Fast search for spectrum range end (returns the past-the-end iterator)
Range methods
Note
The range values (min, max, etc.) are not updated automatically. Call updateRanges() to update the values!
void updateRanges () override
Updates minimum and maximum position/intensity.
void updateRanges (Int ms_level)
Updates the m/z, intensity, retention time and MS level ranges of all spectra with a certain ms level.
CoordinateType getMinMZ () const
returns the minimal m/z value
CoordinateType getMaxMZ () const
returns the maximal m/z value
CoordinateType getMinRT () const
returns the minimal retention time value
CoordinateType getMaxRT () const
returns the maximal retention time value
const AreaType & getDataRange () const
Returns RT and m/z range the data lies in.
UInt64 getSize () const
returns the total number of peaks
const std::vector< UInt > & getMSLevels () const
returns an array of MS levels
Sorting spectra and peaks
void sortSpectra (bool sort_mz=true)
Sorts the data points by retention time.
void sortChromatograms (bool sort_rt=true)
Sorts the data points of the chromatograms by m/z.
bool isSorted (bool check_mz=true) const
Checks if all spectra are sorted with respect to ascending RT.
void reset ()
Resets all internal values.
bool clearMetaDataArrays ()
Clears the meta data arrays of all contained spectra (float, integer and string arrays)
const ExperimentalSettings & getExperimentalSettings () const
returns the meta information of this experiment (const access)
ExperimentalSettings & getExperimentalSettings ()
returns the meta information of this experiment (mutable access)
void getPrimaryMSRunPath (StringList &toFill) const
get the file path to the first MS run
ConstIterator getPrecursorSpectrum (ConstIterator iterator) const
Returns the precursor spectrum of the scan pointed to by iterator.
void swap (MSExperiment &from)
Swaps the content of this map with the content of from.
void setSpectra (const std::vector< MSSpectrum > &spectra)
sets the spectrum list
void addSpectrum (const MSSpectrum &spectrum)
adds a spectrum to the list
void addSpectrum (MSSpectrum &&spectrum)
const std::vector< MSSpectrum > & getSpectra () const
returns the spectrum list
std::vector< MSSpectrum > & getSpectra ()
returns the spectrum list (mutable)
void setChromatograms (const std::vector< MSChromatogram > &chromatograms)
sets the chromatogram list
void addChromatogram (const MSChromatogram &chromatogram)
adds a chromatogram to the list
void addChromatogram (MSChromatogram &&chrom)
const std::vector< MSChromatogram > & getChromatograms () const
returns the chromatogram list
std::vector< MSChromatogram > & getChromatograms ()
returns the chromatogram list (mutable)
Public Member Functions inherited from RangeManager< 2 >
RangeManager ()
Default constructor.
RangeManager (const RangeManager &rhs)
Copy constructor.
RangeManager (RangeManager &&) noexcept=default
Move constructor.
virtual ~RangeManager ()
Destructor.
RangeManager & operator= (const RangeManager &rhs)
Assignment operator.
bool operator== (const RangeManager &rhs) const
Equality operator.
bool operator!= (const RangeManager &rhs) const
Equality operator.
const PositionType & getMin () const
Returns the minimum position.
const PositionType & getMax () const
Returns the maximum position.
double getMinInt () const
Returns the minimum intensity.
double getMaxInt () const
Returns the maximum intensity.
void clearRanges ()
Resets the ranges.
Public Member Functions inherited from ExperimentalSettings
ExperimentalSettings ()=default
Constructor.
ExperimentalSettings (const ExperimentalSettings &)=default
Copy constructor.
ExperimentalSettings (ExperimentalSettings &&)=default
Move constructor.
~ExperimentalSettings () override
Destructor.
ExperimentalSettings & operator= (const ExperimentalSettings &)=default
Assignment operator.
ExperimentalSettings & operator= (ExperimentalSettings &&) &=default
Move assignment operator.
bool operator== (const ExperimentalSettings &rhs) const
Equality operator.
bool operator!= (const ExperimentalSettings &rhs) const
Equality operator.
const Sample & getSample () const
returns a const reference to the sample description
Sample & getSample ()
returns a mutable reference to the sample description
void setSample (const Sample &sample)
sets the sample description
const std::vector< SourceFile > & getSourceFiles () const
returns a const reference to the source data file
std::vector< SourceFile > & getSourceFiles ()
returns a mutable reference to the source data file
void setSourceFiles (const std::vector< SourceFile > &source_files)
sets the source data file
const std::vector< ContactPerson > & getContacts () const
returns a const reference to the list of contact persons
std::vector< ContactPerson > & getContacts ()
returns a mutable reference to the list of contact persons
void setContacts (const std::vector< ContactPerson > &contacts)
sets the list of contact persons
const Instrument & getInstrument () const
returns a const reference to the MS instrument description
Instrument & getInstrument ()
returns a mutable reference to the MS instrument description
void setInstrument (const Instrument &instrument)
sets the MS instrument description
const HPLC & getHPLC () const
returns a const reference to the description of the HPLC run
HPLC & getHPLC ()
returns a mutable reference to the description of the HPLC run
void setHPLC (const HPLC &hplc)
sets the description of the HPLC run
const DateTime & getDateTime () const
returns the date the experiment was performed
void setDateTime (const DateTime &date)
sets the date the experiment was performed
const String & getComment () const
returns the free-text comment
void setComment (const String &comment)
sets the free-text comment
const std::vector< ProteinIdentification > & getProteinIdentifications () const
returns a const reference to the protein ProteinIdentification vector
std::vector< ProteinIdentification > & getProteinIdentifications ()
returns a mutable reference to the protein ProteinIdentification vector
void setProteinIdentifications (const std::vector< ProteinIdentification > &protein_identifications)
sets the protein ProteinIdentification vector
const String & getFractionIdentifier () const
returns fraction identifier
void setFractionIdentifier (const String &fraction_identifier)
sets the fraction identifier
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from DocumentIdentifier
DocumentIdentifier ()
Default constructor.
DocumentIdentifier (const DocumentIdentifier &)=default
Copy constructor.
DocumentIdentifier (DocumentIdentifier &&)=default
Move constructor.
virtual ~DocumentIdentifier ()
Destructor.
DocumentIdentifier & operator= (const DocumentIdentifier &)=default
Assignment operator.
DocumentIdentifier & operator= (DocumentIdentifier &&) &=default
Move assignment operator.
bool operator== (const DocumentIdentifier &rhs) const
Equality operator.
void setIdentifier (const String &id)
set document identifier (e.g. an LSID)
const String & getIdentifier () const
retrieve document identifier (e.g. an LSID)
void swap (DocumentIdentifier &from)
exchange content with from
void setLoadedFilePath (const String &file_name)
set the file_name_ according to absolute path of the file loaded from preferably done whilst loading
const String & getLoadedFilePath () const
get the file_name_ which is the absolute path to the file loaded from
void setLoadedFileType (const String &file_name)
set the file_type according to the type of the file loaded from (see FileHandler::Type) preferably done whilst loading
const FileTypes::Type & getLoadedFileType () const
get the file_type (e.g. featureXML, consensusXML, mzData, mzXML, mzML, ...) of the file loaded from
Delegations of calls to the vector of MSSpectra
typedef Base::value_type value_type
typedef Base::iterator iterator
typedef Base::const_iterator const_iterator
Size size () const
void resize (Size s)
bool empty () const
void reserve (Size s)
SpectrumType & operator[] (Size n)
const SpectrumType & operator[] (Size n) const
Iterator begin ()
ConstIterator begin () const
Iterator end ()
ConstIterator end () const
void reserveSpaceSpectra (Size s)
void reserveSpaceChromatograms (Size s)
MSExperiment ()
Constructor.
MSExperiment (const MSExperiment &source)
Copy constructor.
MSExperiment (MSExperiment &&)=default
Move constructor.
MSExperiment & operator= (const MSExperiment &source)
Assignment operator.
MSExperiment & operator= (MSExperiment &&) &=default
Move assignment operator.
MSExperiment & operator= (const ExperimentalSettings &source)
Assignment operator.
bool operator== (const MSExperiment &rhs) const
Equality operator.
bool operator!= (const MSExperiment &rhs) const
Equality operator.
Easy Access interface
std::vector< UInt > ms_levels_
MS levels of the data.
UInt64 total_size_
Number of all data points.
std::vector< MSChromatogram > chromatograms_
chromatograms
std::vector< SpectrumType > spectra_
spectra
MSChromatogram & getChromatogram (Size id)
returns a single chromatogram
MSSpectrum & getSpectrum (Size id)
returns a single spectrum
Size getNrSpectra () const
get the total number of spectra available
Size getNrChromatograms () const
get the total number of chromatograms available
const MSChromatogram getTIC (float rt_bin_size=0) const
Compute Total Ion Count per MS1 spectrum and applies the resampling algorithm, if a bin size in RT seconds greater than 0 is given.
void clear (bool clear_meta_data)
Clears all data and meta data.
SpectrumType * createSpec_ (PeakType::CoordinateType rt)
SpectrumType * createSpec_ (PeakType::CoordinateType rt, const StringList &metadata_names)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from RangeManager< 2 >
void updateRanges_ (const PeakIteratorType &begin, const PeakIteratorType &end)
Updates the range using data points in the iterator range.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from RangeManager< 2 >
IntensityRangeType int_range_
Intensity range (1-dimensional)
PositionRangeType pos_range_
Position range (D-dimensional)
Protected Attributes inherited from ExperimentalSettings
Sample sample_
std::vector< SourceFile > source_files_
std::vector< ContactPerson > contacts_
Instrument instrument_
HPLC hplc_
DateTime datetime_
String comment_
std::vector< ProteinIdentification > protein_identifications_
String fraction_identifier_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from DocumentIdentifier
String id_
the ID (e.g. LSID)
String file_path_
the path to the loaded file
FileTypes::Type file_type_
the type of the loaded file
Detailed Description
In-Memory representation of a mass spectrometry experiment.
Contains the data and metadata of an experiment performed with an MS (or HPLC and MS). This representation of an MS experiment is organized as list of spectra and chromatograms and provides an in-memory representation of popular mass-spectrometric file formats such as mzXML or mzML. The meta-data associated with an experiment is contained in ExperimentalSettings (by inheritance) while the raw data (as well as spectra and chromatogram level meta data) is stored in objects of type MSSpectrum and MSChromatogram, which are accessible through the getSpectrum and getChromatogram functions.
Be careful when changing the order of contained MSSpectrum instances, if tandem-MS data is stored in this class. The only way to find a precursor spectrum of MSSpectrum x is to search for the first spectrum before x that has a lower MS-level!
Note
For range operations, see RangeUtils module!
Some of the meta data is associated with the spectra directly (e.g. DataProcessing) and therefore the spectra need to be present to retain this information.
For an on-disc representation of an MS experiment, see OnDiskExperiment.
Member Typedef Documentation
AreaIterator
typedef Internal::AreaIterator<PeakT, PeakT&, PeakT*, Iterator, SpectrumType::Iterator> AreaIterator
Mutable area iterator type (for traversal of a rectangular subset of the peaks)
AreaType
typedef DRange<2> AreaType
Area type.
Base
typedef std::vector<SpectrumType> Base
STL base class type.
ChromatogramPeakT
typedef ChromatogramPeak ChromatogramPeakT
ChromatogramPeakType
typedef ChromatogramPeakT ChromatogramPeakType
Chromatogram peak type.
ChromatogramType
typedef MSChromatogram ChromatogramType
Chromatogram type.
const_iterator
typedef Base::const_iterator const_iterator
ConstAreaIterator
typedef Internal::AreaIterator<const PeakT, const PeakT&, const PeakT*, ConstIterator, SpectrumType::ConstIterator> ConstAreaIterator
Immutable area iterator type (for traversal of a rectangular subset of the peaks)
ConstIterator
typedef std::vector<SpectrumType>::const_iterator ConstIterator
Non-mutable iterator.
CoordinateType
typedef PeakType::CoordinateType CoordinateType
Coordinate type of peak positions.
IntensityType
typedef PeakType::IntensityType IntensityType
Intensity type of peaks.
Iterator
typedef std::vector<SpectrumType>::iterator Iterator
Mutable iterator.
iterator
typedef Base::iterator iterator
PeakT
typedef Peak1D PeakT
PeakType
typedef PeakT PeakType
Peak type.
RangeManagerType
typedef RangeManager<2> RangeManagerType
RangeManager type.
SpectrumType
typedef MSSpectrum SpectrumType
Spectrum Type.
value_type
typedef Base::value_type value_type
Constructor & Destructor Documentation
MSExperiment() [1/3]
MSExperiment ()
Constructor.
MSExperiment() [2/3]
MSExperiment (const MSExperiment & source)
Copy constructor.
MSExperiment() [3/3]
MSExperiment (MSExperiment &&) default
Move constructor.
Member Function Documentation
addChromatogram() [1/2]
void addChromatogram (const MSChromatogram & chromatogram)
adds a chromatogram to the list
addChromatogram() [2/2]
void addChromatogram (MSChromatogram && chrom) inline
addSpectrum() [1/2]
void addSpectrum (const MSSpectrum & spectrum)
adds a spectrum to the list
Referenced by SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), UTILProteomicsLFQ::calculateSeeds_(), TOPPViewBase::copyLayer(), FLASHDeconv::findFeatures(), MS2File::load(), MascotInfile::load(), MascotGenericFile::load(), DTA2DFile::load(), SpectraMerger::mergeSpectra_(), OPXLDataStructs::PreprocessedPairSpectra::PreprocessedPairSpectra(), and TOPPViewBase::showSpectrumGenerationDialog().
addSpectrum() [2/2]
void addSpectrum (MSSpectrum && spectrum) inline
areaBegin()
AreaIterator areaBegin (CoordinateType min_rt, CoordinateType max_rt, CoordinateType min_mz, CoordinateType max_mz)
Returns an area iterator for area.
areaBeginConst()
ConstAreaIterator areaBeginConst (CoordinateType min_rt, CoordinateType max_rt, CoordinateType min_mz, CoordinateType max_mz) const
Returns a non-mutable area iterator for area.
Referenced by MetaProSIPXICExtraction::extractXICs().
areaEnd()
AreaIterator areaEnd ()
Returns an invalid area iterator marking the end of an area.
areaEndConst()
ConstAreaIterator areaEndConst () const
Returns an non-mutable invalid area iterator marking the end of an area.
Referenced by MetaProSIPXICExtraction::extractXICs().
begin() [1/2]
Iterator begin () inline
Referenced by KDTreeFeatureMaps::addMaps(), SpectraMerger::average(), SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), FLASHDeconv::Deconvolution(), IsotopeWaveletTransform< PeakType >::extendBox_(), IDFilter::filterHitsByScore(), FLASHDeconv::findFeatures(), MapAlignmentAlgorithmIdentification::getRetentionTimes_(), IDFilter::keepHitsMatchingProteins(), IDFilter::keepNBestHits(), TOPPFLASHDeconv::main_(), FLASHDeconv::main_(), NucleicAcidSearchEngine::main_(), SpectraMerger::mergeSpectra_(), SpectraMerger::mergeSpectraBlockWise(), TwoDOptimization::optimize(), DTA2DFile::store(), TOPPFLASHDeconv::writeAnnotatedSpectra(), and FLASHDeconv::writeAnnotatedSpectra().
begin() [2/2]
ConstIterator begin () const inline
clear()
void clear (bool clear_meta_data)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
Referenced by UTILProteomicsLFQ::centroidAndCorrectPrecursors_(), SpectraMerger::mergeSpectra_(), PeakPickerIterative::pickExperiment(), and IsotopeWaveletTransform< PeakType >::updateBoxStates().
clearMetaDataArrays()
bool clearMetaDataArrays ()
Clears the meta data arrays of all contained spectra (float, integer and string arrays)
Returns
true if meta data arrays were present and removed. false otherwise.
Referenced by UTILProteomicsLFQ::centroidAndCorrectPrecursors_().
createSpec_() [1/2]
SpectrumType* createSpec_ (PeakType::CoordinateType rt) private
createSpec_() [2/2]
SpectrumType* createSpec_ (PeakType::CoordinateType rt, const StringList & metadata_names) private
empty()
bool empty () const inline
Referenced by UTILProteomicsLFQ::centroidAndCorrectPrecursors_(), OpenMS::collapseIMSpectrum(), OpenMS::determineIMType(), TOPPViewBase::hasPeptideIdentifications(), and TwoDOptimization::optimize().
end() [1/2]
Iterator end () inline
Referenced by KDTreeFeatureMaps::addMaps(), SpectraMerger::average(), SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), FLASHDeconv::Deconvolution(), TOPPViewBase::estimateNoiseFromRandomMS1Scans(), IDFilter::filterHitsByScore(), FLASHDeconv::findFeatures(), MapAlignmentAlgorithmIdentification::getRetentionTimes_(), IDFilter::keepHitsMatchingProteins(), IDFilter::keepNBestHits(), TOPPFLASHDeconv::main_(), FLASHDeconv::main_(), NucleicAcidSearchEngine::main_(), SpectraMerger::mergeSpectra_(), SpectraMerger::mergeSpectraBlockWise(), TwoDOptimization::optimize(), DTA2DFile::store(), TOPPFLASHDeconv::writeAnnotatedSpectra(), and FLASHDeconv::writeAnnotatedSpectra().
end() [2/2]
ConstIterator end () const inline
get2DData()
void get2DData (Container & cont) const inline
Reads out a 2D Spectrum.
Container can be a PeakArray or an STL container of peaks which supports push_back(), end() and back()
getChromatogram()
MSChromatogram& getChromatogram (Size id)
returns a single chromatogram
Referenced by GaussFilter::filterExperiment(), and SavitzkyGolayFilter::filterExperiment().
getChromatograms() [1/2]
std::vector<MSChromatogram>& getChromatograms ()
returns the chromatogram list (mutable)
getChromatograms() [2/2]
const std::vector<MSChromatogram>& getChromatograms () const
returns the chromatogram list
Referenced by GaussFilter::filterExperiment(), and SavitzkyGolayFilter::filterExperiment().
getDataRange()
const AreaType& getDataRange () const
Returns RT and m/z range the data lies in.
RT is dimension 0, m/z is dimension 1
getExperimentalSettings() [1/2]
ExperimentalSettings& getExperimentalSettings ()
returns the meta information of this experiment (mutable access)
getExperimentalSettings() [2/2]
const ExperimentalSettings& getExperimentalSettings () const
returns the meta information of this experiment (const access)
Referenced by XMassFile::importExperimentalSettings().
getMaxMZ()
CoordinateType getMaxMZ () const
returns the maximal m/z value
getMaxRT()
CoordinateType getMaxRT () const
returns the maximal retention time value
getMinMZ()
CoordinateType getMinMZ () const
returns the minimal m/z value
getMinRT()
CoordinateType getMinRT () const
returns the minimal retention time value
getMSLevels()
const std::vector<UInt>& getMSLevels () const
returns an array of MS levels
getNrChromatograms()
Size getNrChromatograms () const
get the total number of chromatograms available
getNrSpectra()
Size getNrSpectra () const
get the total number of spectra available
Referenced by NucleicAcidSearchEngine::main_().
getPrecursorSpectrum()
ConstIterator getPrecursorSpectrum (ConstIterator iterator) const
Returns the precursor spectrum of the scan pointed to by iterator.
If there is no precursor scan the past-the-end iterator is returned.
getPrimaryMSRunPath()
void getPrimaryMSRunPath (StringList & toFill) const
get the file path to the first MS run
Referenced by NucleicAcidSearchEngine::main_().
getSize()
UInt64 getSize () const
returns the total number of peaks
getSpectra() [1/2]
std::vector<MSSpectrum>& getSpectra ()
returns the spectrum list (mutable)
getSpectra() [2/2]
const std::vector<MSSpectrum>& getSpectra () const
returns the spectrum list
Referenced by SpectraMerger::mergeSpectra_().
getSpectrum()
MSSpectrum& getSpectrum (Size id)
returns a single spectrum
getTIC()
const MSChromatogram getTIC (float rt_bin_size = 0) const
Compute Total Ion Count per MS1 spectrum and applies the resampling algorithm, if a bin size in RT seconds greater than 0 is given.
By default, each MS1 spectrum's intensity just gets summed up. Regular RT bins can be obtained by specifying rt_bin_size.
Parameters
bin_size RT bin size in seconds
Returns
TIC Chromatogram
Referenced by DTA2DFile::storeTIC().
isSorted()
bool isSorted (bool check_mz = true) const
Checks if all spectra are sorted with respect to ascending RT.
Parameters
check_mz if true, checks if all peaks are sorted with respect to ascending m/z
operator!=()
bool operator!= (const MSExperiment & rhs) const
Equality operator.
operator=() [1/3]
MSExperiment& operator= (const ExperimentalSettings & source)
Assignment operator.
operator=() [2/3]
MSExperiment& operator= (const MSExperiment & source)
Assignment operator.
operator=() [3/3]
MSExperiment& operator= (MSExperiment &&) & default
Move assignment operator.
operator==()
bool operator== (const MSExperiment & rhs) const
Equality operator.
operator[]() [1/2]
SpectrumType& operator[] (Size n) inline
operator[]() [2/2]
const SpectrumType& operator[] (Size n) const inline
reserve()
void reserve (Size s) inline
reserveSpaceChromatograms()
void reserveSpaceChromatograms (Size s)
reserveSpaceSpectra()
void reserveSpaceSpectra (Size s)
reset()
void reset ()
Resets all internal values.
Referenced by InspectOutfile::getExperiment(), MS2File::load(), MascotInfile::load(), MascotGenericFile::load(), and DTA2DFile::load().
resize()
void resize (Size s) inline
Referenced by PeakPickerIterative::pickExperiment().
RTBegin() [1/2]
Iterator RTBegin (CoordinateType rt)
Fast search for spectrum range begin.
Note
Make sure the spectra are sorted with respect to retention time! Otherwise the result is undefined.
RTBegin() [2/2]
ConstIterator RTBegin (CoordinateType rt) const
Fast search for spectrum range begin.
Returns the first scan which has equal or higher (>=) RT than rt.
Note
Make sure the spectra are sorted with respect to retention time! Otherwise the result is undefined.
Referenced by MetaProSIPXICExtraction::extractXICs(), and TwoDOptimization::getRegionEndpoints_().
RTEnd() [1/2]
Iterator RTEnd (CoordinateType rt)
Fast search for spectrum range end (returns the past-the-end iterator)
Note
Make sure the spectra are sorted with respect to retention time! Otherwise the result is undefined.
RTEnd() [2/2]
ConstIterator RTEnd (CoordinateType rt) const
Fast search for spectrum range end (returns the past-the-end iterator)
Returns the first scan which has higher (>) RT than rt.
Note
Make sure the spectra are sorted with respect to retention time! Otherwise the result is undefined.
set2DData() [1/3]
void set2DData (const Container & container) inline
Assignment of a data container with RT and MZ to an MSExperiment.
Fill MSExperiment with data. Note that all data present (including meta-data) will be deleted prior to adding new data!
Parameters
container An iterable type whose elements support getRT(), getMZ() and getIntensity()
Exceptions
Exception::Precondition is thrown if the container is not sorted according to retention time (in debug AND release mode)
set2DData() [2/3]
void set2DData (const Container & container) inline
Assignment of a data container with RT and MZ to an MSExperiment.
Fill MSExperiment with data. Note that all data present (including meta-data) will be deleted prior to adding new data!
Parameters
container An iterable type whose elements support getRT(), getMZ() and getIntensity()
add_mass_traces If true, each container element is searched for the metavalue "num_of_masstraces". If found, "masstrace_intensity" (X>=0) meta values are added as data points (with 13C spacing). This is useful for, e.g., FF-Metabo output. Note that the actual feature will NOT be added if mass traces are found (since MT0 is usually identical)
Exceptions
Exception::Precondition is thrown if the container is not sorted according to retention time (in debug AND release mode) OR a "masstrace_intensity" value is expected but not found
set2DData() [3/3]
void set2DData (const Container & container, const StringList & store_metadata_names) inline
Assignment of a data container with RT and MZ to an MSExperiment.
Fill MSExperiment with data. Note that all data present (including meta-data) will be deleted prior to adding new data!
Parameters
container An iterable type whose elements support getRT(), getMZ() and getIntensity()
store_metadata_names [MetaInfoInterface input only] Names of metadata arrays which should be created; data is filled from the metainfointerface of each element of the input container. Currently, only float data is supported!
Exceptions
Exception::Precondition is thrown if the container is not sorted according to retention time (in debug AND release mode)
setChromatograms()
void setChromatograms (const std::vector< MSChromatogram > & chromatograms)
sets the chromatogram list
setSpectra()
void setSpectra (const std::vector< MSSpectrum > & spectra)
sets the spectrum list
size()
Size size () const inline
Referenced by SpectrumCanvas::addDataProcessing_(), UTILProteomicsLFQ::centroidAndCorrectPrecursors_(), OpenSwathHelper::checkSwathMapAndSelectTransitions(), OpenMS::collapseIMSpectrum(), TOPPViewBase::containsMS1Scans(), FLASHDeconv::Deconvolution(), OpenMS::determineIMType(), TOPPViewBase::estimateNoiseFromRandomMS1Scans(), GaussFilter::filterExperiment(), SavitzkyGolayFilter::filterExperiment(), MorphologicalFilter::filterExperiment(), TwoDOptimization::getRegionEndpoints_(), TOPPViewBase::hasMS1Zeros(), TOPPViewBase::hasPeptideIdentifications(), TOPPFLASHDeconv::main_(), FLASHDeconv::main_(), NucleicAcidSearchEngine::main_(), IDMapper::mapPrecursorsToIdentifications(), IsotopeWaveletTransform< PeakType >::mapSeeds2Features(), SpectraMerger::mergeSpectra_(), SpectraMerger::mergeSpectraPrecursors(), TwoDOptimization::optimize(), PeakPickerIterative::pickExperiment(), NucleicAcidSearchEngine::preprocessSpectra_(), LinearResampler::rasterExperiment(), DTA2DFile::store(), DTA2DFile::storeTIC(), and IsotopeWaveletTransform< PeakType >::updateBoxStates().
sortChromatograms()
void sortChromatograms (bool sort_rt = true)
Sorts the data points of the chromatograms by m/z.
Parameters
sort_rt if true, chromatograms are sorted by rt position as well
sortSpectra()
void sortSpectra (bool sort_mz = true)
Sorts the data points by retention time.
Parameters
sort_mz if true, spectra are sorted by m/z position as well
Referenced by SpectraMerger::average(), NucleicAcidSearchEngine::main_(), SpectraMerger::mergeSpectraBlockWise(), SpectraMerger::mergeSpectraPrecursors(), and NucleicAcidSearchEngine::preprocessSpectra_().
swap()
void swap (MSExperiment & from)
Swaps the content of this map with the content of from.
Referenced by UTILProteomicsLFQ::quantifyFraction_().
updateRanges() [1/2]
void updateRanges () override virtual
Updates minimum and maximum position/intensity.
This method is usually implemented by calling clearRanges() and updateRanges_().
Implements RangeManager< 2 >.
updateRanges() [2/2]
void updateRanges (Int ms_level)
Updates the m/z, intensity, retention time and MS level ranges of all spectra with a certain ms level.
Parameters
ms_level MS level to consider for m/z range , RT range and intensity range (All MS levels if negative)
Member Data Documentation
chromatograms_
std::vector<MSChromatogram > chromatograms_ protected
chromatograms
ms_levels_
std::vector<UInt> ms_levels_ protected
MS levels of the data.
spectra_
std::vector<SpectrumType> spectra_ protected
spectra
total_size_
UInt64 total_size_ protected
Number of all data points.