OpenMS: MapConversion Class Reference
MapConversion Class Reference
#include <OpenMS/KERNEL/ConversionHelper.h>
Static Public Member Functions
static void convert (UInt64 const input_map_index, PeakMap &input_map, ConsensusMap &output_map, Size n=-1)
Similar to convert for FeatureMaps.
static void convert (ConsensusMap const &input_map, const bool keep_uids, FeatureMap &output_map)
Convert a ConsensusMap to a FeatureMap (of any feature type).
static void convert (UInt64 const input_map_index, FeatureMap const &input_map, ConsensusMap &output_map, Size n=-1)
Convert a FeatureMap (of any feature type) to a ConsensusMap.
Member Function Documentation
convert() [1/3]
static void convert (ConsensusMap const & input_map, const bool keep_uids, FeatureMap & output_map) static
Convert a ConsensusMap to a FeatureMap (of any feature type).
The previous content of output_map is cleared. UID's of the elements and the container is copied if the keep_uids flag is set.
Parameters
input_map The container to be converted.
keep_uids Shall the UID's of the elements and the container be kept or created anew
output_map The resulting ConsensusMap.
convert() [2/3]
static void convert (UInt64 const input_map_index, FeatureMap const & input_map, ConsensusMap & output_map, Size n = -1) static
Convert a FeatureMap (of any feature type) to a ConsensusMap.
Each ConsensusFeature contains a map index, so this has to be given as well. The previous content of output_map is cleared. An arguable design decision is that the unique id of the FeatureMap is copied (!) to the ConsensusMap, because that is the way it is meant to be used in the algorithms.
Only the first (!) n elements are copied. (This parameter exists mainly for compatibility with convert for MSExperiments. To use it in a meaningful way, apply one of the sorting methods to input_map beforehand.)
Parameters
input_map_index The index of the input map.
input_map The container to be converted.
output_map The resulting ConsensusMap.
n The maximum number of elements to be copied.
convert() [3/3]
static void convert (UInt64 const input_map_index, PeakMap & input_map, ConsensusMap & output_map, Size n = -1) static
Similar to convert for FeatureMaps.
Only the n most intense elements are copied.
Currently PeakMap does not have a unique id but ConsensusMap has one, so we assign a new one here.
Parameters
input_map_index The index of the input map.
input_map The input map to be converted.
output_map The resulting ConsensusMap.
n The maximum number of elements to be copied.
Referenced by UTILProteomicsLFQ::alignAndLink_(), FeatureGroupingAlgorithmUnlabeled::setReference(), and MapAlignmentAlgorithmPoseClustering::setReference().