OpenMS: MSChromatogram Class Reference
MSChromatogram Class Reference
Kernel
The representation of a chromatogram.
#include <OpenMS/KERNEL/MSChromatogram.h>
Classes
struct MZLess
Comparator for the retention time.
Public Types
Base type definitions
Peak type
typedef ChromatogramPeak PeakType
typedef PeakType::CoordinateType CoordinateType
Coordinate (RT) type.
typedef std::vector< PeakType > ContainerType
Chromatogram base type.
typedef OpenMS::DataArrays::FloatDataArray FloatDataArray
Float data array vector type.
typedef std::vector< FloatDataArray > FloatDataArrays
typedef OpenMS::DataArrays::StringDataArray StringDataArray
String data array vector type.
typedef std::vector< StringDataArray > StringDataArrays
typedef OpenMS::DataArrays::IntegerDataArray IntegerDataArray
Integer data array vector type.
typedef std::vector< IntegerDataArray > IntegerDataArrays
Peak container iterator type definitions
typedef ContainerType::iterator Iterator
Mutable iterator.
typedef ContainerType::const_iterator ConstIterator
Non-mutable iterator.
typedef ContainerType::reverse_iterator ReverseIterator
Mutable reverse iterator.
typedef ContainerType::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
Public Types inherited from RangeManager< 1 >
enum
Dimension of the position range.
typedef DRange< D > PositionRangeType
Position range type.
typedef DPosition< D > PositionType
Position Type.
typedef DRange< 1 > IntensityRangeType
Intensity range type.
Public Types inherited from ChromatogramSettings
enum ChromatogramType {
MASS_CHROMATOGRAM = 0, TOTAL_ION_CURRENT_CHROMATOGRAM, SELECTED_ION_CURRENT_CHROMATOGRAM, BASEPEAK_CHROMATOGRAM,
SELECTED_ION_MONITORING_CHROMATOGRAM, SELECTED_REACTION_MONITORING_CHROMATOGRAM, ELECTROMAGNETIC_RADIATION_CHROMATOGRAM, ABSORPTION_CHROMATOGRAM,
EMISSION_CHROMATOGRAM, SIZE_OF_CHROMATOGRAM_TYPE
}
Public Member Functions
double getMZ () const
returns the mz of the product entry, makes sense especially for MRM scans
Export methods from std::vector
MSChromatogram ()=default
Constructor.
MSChromatogram (const MSChromatogram &)=default
Copy constructor.
MSChromatogram (MSChromatogram &&)=default
Move constructor.
~MSChromatogram () override
Destructor.
MSChromatogram & operator= (const MSChromatogram &source)
Assignment operator.
MSChromatogram & operator= (MSChromatogram &&) &=default
Move assignment operator.
bool operator== (const MSChromatogram &rhs) const
Equality operator.
bool operator!= (const MSChromatogram &rhs) const
Equality operator.
void updateRanges () override
Updates minimum and maximum position/intensity.
Accessors for meta information
Returns the name
const String & getName () const
void setName (const String &name)
Sets the name.
Peak data array methods
These methods are used to annotate each peak in a chromatogram with meta information. It is an intermediate way between storing the information in the peak's MetaInfoInterface and deriving a new peak type with members for this information.
These statements should help you chose which approach to use
Access to meta info arrays is slower than to a member variable
Access to meta info arrays is faster than to a MetaInfoInterface
Meta info arrays are stored when using mzML format for storing
const FloatDataArrays & getFloatDataArrays () const
FloatDataArrays & getFloatDataArrays ()
Returns a mutable reference to the float meta data arrays.
void setFloatDataArrays (const FloatDataArrays &fda)
Sets the float meta data arrays.
const StringDataArrays & getStringDataArrays () const
Returns a const reference to the string meta data arrays.
StringDataArrays & getStringDataArrays ()
Returns a mutable reference to the string meta data arrays.
void setStringDataArrays (const StringDataArrays &sda)
Sets the string meta data arrays.
const IntegerDataArrays & getIntegerDataArrays () const
Returns a const reference to the integer meta data arrays.
IntegerDataArrays & getIntegerDataArrays ()
Returns a mutable reference to the integer meta data arrays.
void setIntegerDataArrays (const IntegerDataArrays &ida)
Sets the integer meta data arrays.
Sorting peaks
void sortByIntensity (bool reverse=false)
Lexicographically sorts the peaks by their intensity.
void sortByPosition ()
Lexicographically sorts the peaks by their position.
bool isSorted () const
Checks if all peaks are sorted with respect to ascending RT.
Searching a peak or peak range
Size findNearest (CoordinateType rt) const
Binary search for the peak nearest to a specific RT.
Iterator RTBegin (CoordinateType rt)
Binary search for peak range begin.
Iterator RTBegin (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range begin.
Iterator RTEnd (CoordinateType rt)
Binary search for peak range end (returns the past-the-end iterator)
Iterator RTEnd (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator RTBegin (CoordinateType rt) const
Binary search for peak range begin.
ConstIterator RTBegin (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range begin.
ConstIterator RTEnd (CoordinateType rt) const
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator MZEnd (CoordinateType rt) const
ConstIterator RTEnd (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Iterator PosBegin (CoordinateType rt)
Binary search for peak range begin.
Iterator PosBegin (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range begin.
ConstIterator PosBegin (CoordinateType rt) const
Binary search for peak range begin.
ConstIterator PosBegin (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range begin.
Iterator PosEnd (CoordinateType rt)
Binary search for peak range end (returns the past-the-end iterator)
Iterator PosEnd (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator PosEnd (CoordinateType rt) const
Binary search for peak range end (returns the past-the-end iterator)
ConstIterator PosEnd (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
void clear (bool clear_meta_data)
Clears all data and meta data.
Public Member Functions inherited from RangeManager< 1 >
RangeManager ()
Default constructor.
RangeManager (const RangeManager &rhs)
Copy constructor.
RangeManager (RangeManager &&) noexcept=default
Move constructor.
virtual ~RangeManager ()
Destructor.
RangeManager & operator= (const RangeManager &rhs)
Assignment operator.
bool operator== (const RangeManager &rhs) const
Equality operator.
bool operator!= (const RangeManager &rhs) const
Equality operator.
const PositionType & getMin () const
Returns the minimum position.
const PositionType & getMax () const
Returns the maximum position.
double getMinInt () const
Returns the minimum intensity.
double getMaxInt () const
Returns the maximum intensity.
void clearRanges ()
Resets the ranges.
Public Member Functions inherited from ChromatogramSettings
ChromatogramSettings ()
Constructor.
ChromatogramSettings (const ChromatogramSettings &)=default
Copy constructor.
ChromatogramSettings (ChromatogramSettings &&)=default
Move constructor.
virtual ~ChromatogramSettings ()
Destructor.
ChromatogramSettings & operator= (const ChromatogramSettings &)=default
ChromatogramSettings & operator= (ChromatogramSettings &&) &=default
Move assignment operator.
bool operator== (const ChromatogramSettings &rhs) const
Equality operator.
bool operator!= (const ChromatogramSettings &rhs) const
Equality operator.
const String & getNativeID () const
returns the native identifier for the spectrum, used by the acquisition software.
void setNativeID (const String &native_id)
sets the native identifier for the spectrum, used by the acquisition software.
const String & getComment () const
returns the free-text comment
void setComment (const String &comment)
sets the free-text comment
const InstrumentSettings & getInstrumentSettings () const
returns a const reference to the instrument settings of the current spectrum
InstrumentSettings & getInstrumentSettings ()
returns a mutable reference to the instrument settings of the current spectrum
void setInstrumentSettings (const InstrumentSettings &instrument_settings)
sets the instrument settings of the current spectrum
const AcquisitionInfo & getAcquisitionInfo () const
returns a const reference to the acquisition info
AcquisitionInfo & getAcquisitionInfo ()
returns a mutable reference to the acquisition info
void setAcquisitionInfo (const AcquisitionInfo &acquisition_info)
sets the acquisition info
const SourceFile & getSourceFile () const
returns a const reference to the source file
SourceFile & getSourceFile ()
returns a mutable reference to the source file
void setSourceFile (const SourceFile &source_file)
sets the source file
const Precursor & getPrecursor () const
returns a const reference to the precursors
Precursor & getPrecursor ()
returns a mutable reference to the precursors
void setPrecursor (const Precursor &precursor)
sets the precursors
const Product & getProduct () const
returns a const reference to the products
Product & getProduct ()
returns a mutable reference to the products
void setProduct (const Product &product)
sets the products
ChromatogramType getChromatogramType () const
returns the chromatogram type, e.g. a SRM chromatogram
void setChromatogramType (ChromatogramType type)
sets the chromatogram type
void setDataProcessing (const std::vector< DataProcessingPtr > &data_processing)
sets the description of the applied processing
std::vector< DataProcessingPtr > & getDataProcessing ()
returns a mutable reference to the description of the applied processing
const std::vector< boost::shared_ptr< const DataProcessing > > getDataProcessing () const
returns a const reference to the description of the applied processing
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Protected Attributes
String name_
Name.
FloatDataArrays float_data_arrays_
Float data arrays.
StringDataArrays string_data_arrays_
String data arrays.
IntegerDataArrays integer_data_arrays_
Integer data arrays.
Protected Attributes inherited from RangeManager< 1 >
IntensityRangeType int_range_
Intensity range (1-dimensional)
PositionRangeType pos_range_
Position range (D-dimensional)
Protected Attributes inherited from ChromatogramSettings
String native_id_
String comment_
InstrumentSettings instrument_settings_
SourceFile source_file_
AcquisitionInfo acquisition_info_
Precursor precursor_
Product product_
std::vector< DataProcessingPtr > data_processing_
ChromatogramType type_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Attributes inherited from ChromatogramSettings
static const char *const ChromatogramNames [SIZE_OF_CHROMATOGRAM_TYPE+1]
Names of chromatogram types corresponding to enum ChromatogramType.
Protected Member Functions inherited from RangeManager< 1 >
void updateRanges_ (const PeakIteratorType &begin, const PeakIteratorType &end)
Updates the range using data points in the iterator range.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
The representation of a chromatogram.
Member Typedef Documentation
ConstIterator
typedef ContainerType::const_iterator ConstIterator
Non-mutable iterator.
ConstReverseIterator
typedef ContainerType::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
ContainerType
typedef std::vector<PeakType> ContainerType
Chromatogram base type.
CoordinateType
typedef PeakType::CoordinateType CoordinateType
Coordinate (RT) type.
FloatDataArray
typedef OpenMS::DataArrays::FloatDataArray FloatDataArray
Float data array vector type.
FloatDataArrays
typedef std::vector<FloatDataArray> FloatDataArrays
IntegerDataArray
typedef OpenMS::DataArrays::IntegerDataArray IntegerDataArray
Integer data array vector type.
IntegerDataArrays
typedef std::vector<IntegerDataArray> IntegerDataArrays
Iterator
typedef ContainerType::iterator Iterator
Mutable iterator.
PeakType
typedef ChromatogramPeak PeakType
ReverseIterator
typedef ContainerType::reverse_iterator ReverseIterator
Mutable reverse iterator.
StringDataArray
typedef OpenMS::DataArrays::StringDataArray StringDataArray
String data array vector type.
StringDataArrays
typedef std::vector<StringDataArray> StringDataArrays
Constructor & Destructor Documentation
MSChromatogram() [1/3]
MSChromatogram () default
Constructor.
MSChromatogram() [2/3]
MSChromatogram (const MSChromatogram &) default
Copy constructor.
MSChromatogram() [3/3]
MSChromatogram (MSChromatogram &&) default
Move constructor.
~MSChromatogram()
~MSChromatogram () inline override
Destructor.
Member Function Documentation
clear()
void clear (bool clear_meta_data)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
findNearest()
Size findNearest (CoordinateType rt) const
Binary search for the peak nearest to a specific RT.
Parameters
rt The searched for mass-to-charge ratio searched
Returns
Returns the index of the peak.
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
Exceptions
Exception::Precondition is thrown if the chromatogram is empty (not only in debug mode)
getFloatDataArrays() [1/2]
FloatDataArrays& getFloatDataArrays ()
Returns a mutable reference to the float meta data arrays.
getFloatDataArrays() [2/2]
const FloatDataArrays& getFloatDataArrays () const
Returns a const reference to the float meta data arrays
getIntegerDataArrays() [1/2]
IntegerDataArrays& getIntegerDataArrays ()
Returns a mutable reference to the integer meta data arrays.
getIntegerDataArrays() [2/2]
const IntegerDataArrays& getIntegerDataArrays () const
Returns a const reference to the integer meta data arrays.
getMZ()
double getMZ () const
returns the mz of the product entry, makes sense especially for MRM scans
Referenced by GaussFilter::filter().
getName()
const String& getName () const
getStringDataArrays() [1/2]
StringDataArrays& getStringDataArrays ()
Returns a mutable reference to the string meta data arrays.
getStringDataArrays() [2/2]
const StringDataArrays& getStringDataArrays () const
Returns a const reference to the string meta data arrays.
isSorted()
bool isSorted () const
Checks if all peaks are sorted with respect to ascending RT.
MZEnd()
ConstIterator MZEnd (CoordinateType rt) const
operator!=()
bool operator!= (const MSChromatogram & rhs) const inline
Equality operator.
References KDTree::operator==().
operator=() [1/2]
MSChromatogram& operator= (const MSChromatogram & source)
Assignment operator.
operator=() [2/2]
MSChromatogram& operator= (MSChromatogram &&) & default
Move assignment operator.
operator==()
bool operator== (const MSChromatogram & rhs) const
Equality operator.
PosBegin() [1/4]
ConstIterator PosBegin (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range begin.
Alias for RTBegin()
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
PosBegin() [2/4]
Iterator PosBegin (CoordinateType rt)
Binary search for peak range begin.
Alias for RTBegin()
Note
Make sure the chromatogram is sorted with respect to retention time! Otherwise the result is undefined.
PosBegin() [3/4]
ConstIterator PosBegin (CoordinateType rt) const
Binary search for peak range begin.
Alias for RTBegin()
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
PosBegin() [4/4]
Iterator PosBegin (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range begin.
Alias for RTBegin()
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
PosEnd() [1/4]
ConstIterator PosEnd (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Alias for RTEnd()
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
PosEnd() [2/4]
Iterator PosEnd (CoordinateType rt)
Binary search for peak range end (returns the past-the-end iterator)
Alias for RTEnd()
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
PosEnd() [3/4]
ConstIterator PosEnd (CoordinateType rt) const
Binary search for peak range end (returns the past-the-end iterator)
Alias for RTEnd()
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
PosEnd() [4/4]
Iterator PosEnd (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
Alias for RTEnd()
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
RTBegin() [1/4]
ConstIterator RTBegin (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range begin.
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
RTBegin() [2/4]
Iterator RTBegin (CoordinateType rt)
Binary search for peak range begin.
Note
Make sure the chromatogram is sorted with respect to retention time! Otherwise the result is undefined.
RTBegin() [3/4]
ConstIterator RTBegin (CoordinateType rt) const
Binary search for peak range begin.
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
RTBegin() [4/4]
Iterator RTBegin (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range begin.
Note
Make sure the chromatogram is sorted with respect to RT! Otherwise the result is undefined.
RTEnd() [1/4]
ConstIterator RTEnd (ConstIterator begin, CoordinateType rt, ConstIterator end) const
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
RTEnd() [2/4]
Iterator RTEnd (CoordinateType rt)
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
RTEnd() [3/4]
ConstIterator RTEnd (CoordinateType rt) const
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
RTEnd() [4/4]
Iterator RTEnd (Iterator begin, CoordinateType rt, Iterator end)
Binary search for peak range end (returns the past-the-end iterator)
Note
Make sure the chromatogram is sorted with respect to RT. Otherwise the result is undefined.
setFloatDataArrays()
void setFloatDataArrays (const FloatDataArrays & fda) inline
Sets the float meta data arrays.
setIntegerDataArrays()
void setIntegerDataArrays (const IntegerDataArrays & ida) inline
Sets the integer meta data arrays.
setName()
void setName (const String & name)
Sets the name.
setStringDataArrays()
void setStringDataArrays (const StringDataArrays & sda) inline
Sets the string meta data arrays.
sortByIntensity()
void sortByIntensity (bool reverse = false)
Lexicographically sorts the peaks by their intensity.
Sorts the peaks according to ascending intensity. Meta data arrays will be sorted accordingly.
Referenced by MRMTransitionGroupPicker::pickTransitionGroup().
sortByPosition()
void sortByPosition ()
Lexicographically sorts the peaks by their position.
The chromatogram is sorted with respect to position. Meta data arrays will be sorted accordingly.
updateRanges()
void updateRanges () inline override virtual
Updates minimum and maximum position/intensity.
This method is usually implemented by calling clearRanges() and updateRanges_().
Implements RangeManager< 1 >.
Member Data Documentation
float_data_arrays_
FloatDataArrays float_data_arrays_ protected
Float data arrays.
integer_data_arrays_
IntegerDataArrays integer_data_arrays_ protected
Integer data arrays.
name_
String name_ protected
Name.
string_data_arrays_
StringDataArrays string_data_arrays_ protected
String data arrays.