OpenMS: ConsensusMap Class Reference
ConsensusMap Class Reference
Kernel
A container for consensus elements.
#include <OpenMS/KERNEL/ConsensusMap.h>
Classes
struct ColumnHeader
Description of the columns in a consensus map.
Public Types
typedef std::vector< ConsensusFeature > privvec
Public Types inherited from RangeManager< 2 >
enum
Dimension of the position range.
typedef DRange< D > PositionRangeType
Position range type.
typedef DPosition< D > PositionType
Position Type.
typedef DRange< 1 > IntensityRangeType
Intensity range type.
Public Types inherited from UniqueIdInterface
enum { INVALID = 0 }
This is the invalid unique id (cast it to a UInt64 if you like)
Public Types inherited from UniqueIdIndexer< ConsensusMap >
typedef boost::unordered_map< UInt64, Size > UniqueIdMap
Type definitions
typedef std::vector< ConsensusFeature > Base
typedef RangeManager< 2 > RangeManagerType
typedef std::map< UInt64, ColumnHeader > ColumnHeaders
typedef std::vector< ConsensusFeature >::iterator Iterator
Mutable iterator.
typedef std::vector< ConsensusFeature >::const_iterator ConstIterator
Non-mutable iterator.
typedef std::vector< ConsensusFeature >::reverse_iterator ReverseIterator
Mutable reverse iterator.
typedef std::vector< ConsensusFeature >::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
ConsensusMap ()
Default constructor.
ConsensusMap (const ConsensusMap &source)
Copy constructor.
~ConsensusMap () override
Destructor.
ConsensusMap (Base::size_type n)
Creates a ConsensusMap with n elements.
ConsensusMap & operator= (const ConsensusMap &source)
Assignment operator.
ConsensusMap & appendRows (const ConsensusMap &rhs)
Add consensus map entries as new rows.
ConsensusMap & appendColumns (const ConsensusMap &rhs)
Add consensus map entries as new columns.
void clear (bool clear_meta_data=true)
Clears all data and meta data.
const ColumnHeaders & getColumnHeaders () const
Non-mutable access to the file descriptions.
ColumnHeaders & getColumnHeaders ()
Mutable access to the file descriptions.
void setColumnHeaders (const ColumnHeaders &column_description)
Mutable access to the file descriptions.
const String & getExperimentType () const
Non-mutable access to the experiment type.
void setExperimentType (const String &experiment_type)
Mutable access to the experiment type.
Sorting.
These specialized sorting methods are supported in addition to the standard sorting methods of std::vector. All use stable sorting.
ColumnHeaders column_description_
Map from index to file description.
String experiment_type_ = "label-free"
type of experiment (label-free, labeled_MS1, labeled_MS2)
std::vector< ProteinIdentification > protein_identifications_
protein identifications
std::vector< PeptideIdentification > unassigned_peptide_identifications_
unassigned peptide identifications (without feature)
std::vector< DataProcessing > data_processing_
applied data processing
void sortByIntensity (bool reverse=false)
Sorts the peaks according to ascending intensity.
void sortByRT ()
Sorts the peaks to RT position.
void sortByMZ ()
Sorts the peaks to m/z position.
void sortByPosition ()
Lexicographically sorts the peaks by their position (First RT then m/z).
void sortByQuality (bool reverse=false)
Sorts the peaks according to ascending quality.
void sortBySize ()
Sorts with respect to the size (number of elements)
void sortByMaps ()
Sorts with respect to the sets of maps covered by the consensus features (lexicographically).
void sortPeptideIdentificationsByMapIndex ()
Sorts PeptideIdentifications of consensus features with respect to their map index.
void updateRanges () override
Updates minimum and maximum position/intensity.
void swap (ConsensusMap &from)
Swaps the content of this map with the content of from.
const std::vector< ProteinIdentification > & getProteinIdentifications () const
non-mutable access to the protein identifications
std::vector< ProteinIdentification > & getProteinIdentifications ()
mutable access to the protein identifications
void setProteinIdentifications (const std::vector< ProteinIdentification > &protein_identifications)
sets the protein identifications
void setProteinIdentifications (std::vector< ProteinIdentification > &&protein_identifications)
sets the protein identifications by moving
const std::vector< PeptideIdentification > & getUnassignedPeptideIdentifications () const
non-mutable access to the unassigned peptide identifications
std::vector< PeptideIdentification > & getUnassignedPeptideIdentifications ()
mutable access to the unassigned peptide identifications
void setUnassignedPeptideIdentifications (const std::vector< PeptideIdentification > &unassigned_peptide_identifications)
sets the unassigned peptide identifications
const std::vector< DataProcessing > & getDataProcessing () const
returns a const reference to the description of the applied data processing
std::vector< DataProcessing > & getDataProcessing ()
returns a mutable reference to the description of the applied data processing
void setDataProcessing (const std::vector< DataProcessing > &processing_method)
sets the description of the applied data processing
void setPrimaryMSRunPath (const StringList &s)
set the file paths to the primary MS run (stored in ColumnHeaders)
void setPrimaryMSRunPath (const StringList &s, MSExperiment &e)
void getPrimaryMSRunPath (StringList &toFill) const
returns the MS run path (stored in ColumnHeaders)
void applyFunctionOnPeptideHits (std::function< void(PeptideHit &)> &f, bool include_unassigned=true)
applies a function on all PeptideHits or only assigned ones
void applyFunctionOnPeptideIDs (std::function< void(PeptideIdentification &)> &f, bool include_unassigned=true)
applies a function on all PeptideIDs or only assigned ones
void applyFunctionOnPeptideHits (std::function< void(const PeptideHit &)> &, bool include_unassigned=true) const
applies a const function on all PeptideHits or only assigned ones
void applyFunctionOnPeptideIDs (std::function< void(const PeptideIdentification &)> &f, bool include_unassigned=true) const
applies a const function on all PeptideIDs or only assigned ones
bool operator== (const ConsensusMap &rhs) const
Equality operator.
bool operator!= (const ConsensusMap &rhs) const
Equality operator.
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)())
Applies a member function of Type to the container itself and all consensus features. The returned values are accumulated.
template<typename Type >
Size applyMemberFunction (Size(Type::*member_function)() const) const
The "const" variant.
bool isMapConsistent (Logger::LogStream *stream=nullptr) const
checks if the given maps are unique and all FeatureHandles actually refer to a registered map
void applyFunctionOnPeptideIDs_ (const std::vector< PeptideIdentification > &idvec, std::function< void(const PeptideIdentification &)> &f) const
void applyFunctionOnPeptideHits_ (const std::vector< PeptideIdentification > &idvec, std::function< void(const PeptideHit &)> &f) const
void applyFunctionOnPeptideIDs_ (std::vector< PeptideIdentification > &idvec, std::function< void(PeptideIdentification &)> &f)
void applyFunctionOnPeptideHits_ (std::vector< PeptideIdentification > &idvec, std::function< void(PeptideHit &)> &f)
Additional Inherited Members
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from RangeManager< 2 >
RangeManager ()
Default constructor.
RangeManager (const RangeManager &rhs)
Copy constructor.
RangeManager (RangeManager &&) noexcept=default
Move constructor.
virtual ~RangeManager ()
Destructor.
RangeManager & operator= (const RangeManager &rhs)
Assignment operator.
bool operator== (const RangeManager &rhs) const
Equality operator.
bool operator!= (const RangeManager &rhs) const
Equality operator.
const PositionType & getMin () const
Returns the minimum position.
const PositionType & getMax () const
Returns the maximum position.
double getMinInt () const
Returns the minimum intensity.
double getMaxInt () const
Returns the maximum intensity.
void clearRanges ()
Resets the ranges.
Public Member Functions inherited from DocumentIdentifier
DocumentIdentifier ()
Default constructor.
DocumentIdentifier (const DocumentIdentifier &)=default
Copy constructor.
DocumentIdentifier (DocumentIdentifier &&)=default
Move constructor.
virtual ~DocumentIdentifier ()
Destructor.
DocumentIdentifier & operator= (const DocumentIdentifier &)=default
Assignment operator.
DocumentIdentifier & operator= (DocumentIdentifier &&) &=default
Move assignment operator.
bool operator== (const DocumentIdentifier &rhs) const
Equality operator.
void setIdentifier (const String &id)
set document identifier (e.g. an LSID)
const String & getIdentifier () const
retrieve document identifier (e.g. an LSID)
void swap (DocumentIdentifier &from)
exchange content with from
void setLoadedFilePath (const String &file_name)
set the file_name_ according to absolute path of the file loaded from preferably done whilst loading
const String & getLoadedFilePath () const
get the file_name_ which is the absolute path to the file loaded from
void setLoadedFileType (const String &file_name)
set the file_type according to the type of the file loaded from (see FileHandler::Type) preferably done whilst loading
const FileTypes::Type & getLoadedFileType () const
get the file_type (e.g. featureXML, consensusXML, mzData, mzXML, mzML, ...) of the file loaded from
Public Member Functions inherited from UniqueIdInterface
UniqueIdInterface ()
Default constructor - the unique id will be invalid
UniqueIdInterface (const UniqueIdInterface &rhs)=default
Copy constructor - copies the unique id.
UniqueIdInterface (UniqueIdInterface &&rhs)=default
Move constructor.
UniqueIdInterface & operator= (UniqueIdInterface const &rhs)=default
Assignment operator - copies the unique id.
UniqueIdInterface & operator= (UniqueIdInterface &&) &=default
Move Assignment operator - copies the unique id.
virtual ~UniqueIdInterface ()=default
Destructor.
bool operator== (UniqueIdInterface const &rhs) const
Equality comparison operator - the unique ids must be equal (!)
UInt64 getUniqueId () const
Non-mutable access to unique id - returns the unique id.
Size clearUniqueId ()
Clear the unique id. The new unique id will be invalid. Returns 1 if the unique id was changed, 0 otherwise.
void swap (UniqueIdInterface &from)
Size hasValidUniqueId () const
Returns whether the unique id is valid. Returns 1 if the unique id is valid, 0 otherwise.
Size hasInvalidUniqueId () const
Returns whether the unique id is invalid. Returns 1 if the unique id is invalid, 0 otherwise.
Size setUniqueId ()
Assigns a new, valid unique id. Always returns 1.
Size ensureUniqueId ()
Assigns a valid unique id, but only if the present one is invalid. Returns 1 if the unique id was changed, 0 otherwise.
void setUniqueId (UInt64 rhs)
Assigns the given unique id.
void setUniqueId (const String &rhs)
Mutable access to unique id.
Public Member Functions inherited from UniqueIdIndexer< ConsensusMap >
Size uniqueIdToIndex (UInt64 unique_id) const
Returns the index of the feature with the given unique id, or Size(-1) if none exists in this random access container.
void updateUniqueIdToIndex () const
Updates the hash map from unique id to index.
Size resolveUniqueIdConflicts ()
Assign new UID's to doubly occurring UID's.
void swap (UniqueIdIndexer &rhs)
Swap.
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Static Public Member Functions inherited from UniqueIdInterface
static bool isValid (UInt64 unique_id)
Returns true if the unique_id is valid, false otherwise.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Member Functions inherited from RangeManager< 2 >
void updateRanges_ (const PeakIteratorType &begin, const PeakIteratorType &end)
Updates the range using data points in the iterator range.
Protected Member Functions inherited from UniqueIdIndexer< ConsensusMap >
const ConsensusMap & getBase_ () const
A little helper to get access to the base (!) class RandomAccessContainer.
ConsensusMap & getBase_ ()
A little helper to get access to the base (!) class RandomAccessContainer.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from RangeManager< 2 >
IntensityRangeType int_range_
Intensity range (1-dimensional)
PositionRangeType pos_range_
Position range (D-dimensional)
Protected Attributes inherited from DocumentIdentifier
String id_
the ID (e.g. LSID)
String file_path_
the path to the loaded file
FileTypes::Type file_type_
the type of the loaded file
Protected Attributes inherited from UniqueIdInterface
UInt64 unique_id_
the unique id
Protected Attributes inherited from UniqueIdIndexer< ConsensusMap >
UniqueIdMap uniqueid_to_index_
hash map from unique id to index of features
Detailed Description
A container for consensus elements.
A ConsensusMap is a container holding 2-dimensional consensus elements (ConsensusFeature) which in turn represent analytes that have been quantified across multiple LC-MS/MS experiments. Each analyte in a ConsensusFeature is linked to its original LC-MS/MS run, the links are maintained by the ConsensusMap class. The map is implemented as a vector of elements of type ConsensusFeature.
To be consistent, all maps who are referenced by ConsensusFeature objects (through a unique id) need to be registered in this class.
Member Typedef Documentation
Base
typedef std::vector<ConsensusFeature> Base
ColumnHeaders
typedef std::map<UInt64, ColumnHeader> ColumnHeaders
ConstIterator
typedef std::vector<ConsensusFeature>::const_iterator ConstIterator
Non-mutable iterator.
ConstReverseIterator
typedef std::vector<ConsensusFeature>::const_reverse_iterator ConstReverseIterator
Non-mutable reverse iterator.
Iterator
typedef std::vector<ConsensusFeature>::iterator Iterator
Mutable iterator.
privvec
typedef std::vector<ConsensusFeature> privvec
RangeManagerType
typedef RangeManager<2> RangeManagerType
ReverseIterator
typedef std::vector<ConsensusFeature>::reverse_iterator ReverseIterator
Mutable reverse iterator.
Constructor & Destructor Documentation
ConsensusMap() [1/3]
ConsensusMap ()
Default constructor.
ConsensusMap() [2/3]
ConsensusMap (const ConsensusMap & source)
Copy constructor.
~ConsensusMap()
~ConsensusMap () override
Destructor.
ConsensusMap() [3/3]
ConsensusMap (Base::size_type n) explicit
Creates a ConsensusMap with n elements.
Member Function Documentation
appendColumns()
ConsensusMap& appendColumns (const ConsensusMap & rhs)
Add consensus map entries as new columns.
The number of columns (maximum map index) is the sum of both maps.
Parameters
rhs The consensus map to be merged.
Referenced by UTILProteomicsLFQ::main_().
appendRows()
ConsensusMap& appendRows (const ConsensusMap & rhs)
Add consensus map entries as new rows.
Consensus elements are merged into one container, simply by appending.
The number of columns (maximum map index) stays the same.
Parameters
rhs The consensus map to be merged.
applyFunctionOnPeptideHits() [1/2]
void applyFunctionOnPeptideHits (std::function< void(const PeptideHit &)> & , bool include_unassigned = true) const
applies a const function on all PeptideHits or only assigned ones
applyFunctionOnPeptideHits() [2/2]
void applyFunctionOnPeptideHits (std::function< void(PeptideHit &)> & f, bool include_unassigned = true)
applies a function on all PeptideHits or only assigned ones
applyFunctionOnPeptideHits_() [1/2]
void applyFunctionOnPeptideHits_ (const std::vector< PeptideIdentification > & idvec, std::function< void(const PeptideHit &)> & f) const private
applyFunctionOnPeptideHits_() [2/2]
void applyFunctionOnPeptideHits_ (std::vector< PeptideIdentification > & idvec, std::function< void(PeptideHit &)> & f) private
applyFunctionOnPeptideIDs() [1/2]
void applyFunctionOnPeptideIDs (std::function< void(const PeptideIdentification &)> & f, bool include_unassigned = true) const
applies a const function on all PeptideIDs or only assigned ones
applyFunctionOnPeptideIDs() [2/2]
void applyFunctionOnPeptideIDs (std::function< void(PeptideIdentification &)> & f, bool include_unassigned = true)
applies a function on all PeptideIDs or only assigned ones
Referenced by IDScoreGetterSetter::getPeptideScoresFromMap_(), and IDScoreGetterSetter::setPeptideScoresForMap_().
applyFunctionOnPeptideIDs_() [1/2]
void applyFunctionOnPeptideIDs_ (const std::vector< PeptideIdentification > & idvec, std::function< void(const PeptideIdentification &)> & f) const private
applyFunctionOnPeptideIDs_() [2/2]
void applyFunctionOnPeptideIDs_ (std::vector< PeptideIdentification > & idvec, std::function< void(PeptideIdentification &)> & f) private
applyMemberFunction() [1/2]
Size applyMemberFunction (Size(Type::*)() const member_function) const inline
The "const" variant.
applyMemberFunction() [2/2]
Size applyMemberFunction (Size(Type::*)() member_function) inline
Applies a member function of Type to the container itself and all consensus features. The returned values are accumulated.
Example: The following will print the number of features with invalid unique ids (plus 1 if the container has an invalid UID as well):
ConsensusMap cm;
(...)
std::cout << cm.applyMemberFunction(&UniqueIdInterface::hasInvalidUniqueId) << std::endl;
See e.g. UniqueIdInterface for what else can be done this way.
Referenced by UTILProteomicsLFQ::quantifyFraction_().
clear()
void clear (bool clear_meta_data = true)
Clears all data and meta data.
Parameters
clear_meta_data If true, all meta data is cleared in addition to the data.
Referenced by UTILProteomicsLFQ::main_().
getColumnHeaders() [1/2]
ColumnHeaders& getColumnHeaders ()
Mutable access to the file descriptions.
getColumnHeaders() [2/2]
const ColumnHeaders& getColumnHeaders () const
Non-mutable access to the file descriptions.
Referenced by UTILProteomicsLFQ::getPeptideOccurrence_(), and UTILProteomicsLFQ::quantifyFraction_().
getDataProcessing() [1/2]
std::vector<DataProcessing>& getDataProcessing ()
returns a mutable reference to the description of the applied data processing
getDataProcessing() [2/2]
const std::vector<DataProcessing>& getDataProcessing () const
returns a const reference to the description of the applied data processing
getExperimentType()
const String& getExperimentType () const
Non-mutable access to the experiment type.
getPrimaryMSRunPath()
void getPrimaryMSRunPath (StringList & toFill) const
returns the MS run path (stored in ColumnHeaders)
getProteinIdentifications() [1/2]
std::vector<ProteinIdentification>& getProteinIdentifications ()
mutable access to the protein identifications
getProteinIdentifications() [2/2]
const std::vector<ProteinIdentification>& getProteinIdentifications () const
non-mutable access to the protein identifications
Referenced by UTILProteomicsLFQ::main_(), and FeatureGroupingAlgorithm::postprocess_().
getUnassignedPeptideIdentifications() [1/2]
std::vector<PeptideIdentification>& getUnassignedPeptideIdentifications ()
mutable access to the unassigned peptide identifications
getUnassignedPeptideIdentifications() [2/2]
const std::vector<PeptideIdentification>& getUnassignedPeptideIdentifications () const
non-mutable access to the unassigned peptide identifications
Referenced by FeatureGroupingAlgorithm::postprocess_().
isMapConsistent()
bool isMapConsistent (Logger::LogStream * stream = nullptr) const
checks if the given maps are unique and all FeatureHandles actually refer to a registered map
To avoid inconsistencies in map IDs and make sure the maps are unique in terms of name+label
If you want some verbose output, provide a stream.
@hint: alternative to this method we could check the features while they are added to the map directly, but
currently we can't because the interface is not designed for this (derived from std::vector, no encapsulation)
we should restrict the user to first fill the list of maps, before any datapoints can be inserted
operator!=()
bool operator!= (const ConsensusMap & rhs) const
Equality operator.
operator=()
ConsensusMap& operator= (const ConsensusMap & source)
Assignment operator.
operator==()
bool operator== (const ConsensusMap & rhs) const
Equality operator.
setColumnHeaders()
void setColumnHeaders (const ColumnHeaders & column_description)
Mutable access to the file descriptions.
setDataProcessing()
void setDataProcessing (const std::vector< DataProcessing > & processing_method)
sets the description of the applied data processing
setExperimentType()
void setExperimentType (const String & experiment_type)
Mutable access to the experiment type.
setPrimaryMSRunPath() [1/2]
void setPrimaryMSRunPath (const StringList & s)
set the file paths to the primary MS run (stored in ColumnHeaders)
setPrimaryMSRunPath() [2/2]
void setPrimaryMSRunPath (const StringList & s, MSExperiment & e)
set the file path to the primary MS run using the mzML annotated in the MSExperiment
Parameters
e. If it doesn't exist, fallback to
s.
setProteinIdentifications() [1/2]
void setProteinIdentifications (const std::vector< ProteinIdentification > & protein_identifications)
sets the protein identifications
setProteinIdentifications() [2/2]
void setProteinIdentifications (std::vector< ProteinIdentification > && protein_identifications)
sets the protein identifications by moving
setUnassignedPeptideIdentifications()
void setUnassignedPeptideIdentifications (const std::vector< PeptideIdentification > & unassigned_peptide_identifications)
sets the unassigned peptide identifications
sortByIntensity()
void sortByIntensity (bool reverse = false)
Sorts the peaks according to ascending intensity.
sortByMaps()
void sortByMaps ()
Sorts with respect to the sets of maps covered by the consensus features (lexicographically).
Referenced by FeatureGroupingAlgorithm::postprocess_().
sortByMZ()
void sortByMZ ()
Sorts the peaks to m/z position.
sortByPosition()
void sortByPosition ()
Lexicographically sorts the peaks by their position (First RT then m/z).
Referenced by UTILProteomicsLFQ::main_().
sortByQuality()
void sortByQuality (bool reverse = false)
Sorts the peaks according to ascending quality.
Referenced by FeatureGroupingAlgorithm::postprocess_().
sortByRT()
void sortByRT ()
Sorts the peaks to RT position.
sortBySize()
void sortBySize ()
Sorts with respect to the size (number of elements)
Referenced by FeatureGroupingAlgorithm::postprocess_().
sortPeptideIdentificationsByMapIndex()
void sortPeptideIdentificationsByMapIndex ()
Sorts PeptideIdentifications of consensus features with respect to their map index.
Referenced by UTILProteomicsLFQ::main_(), and UTILProteomicsLFQ::quantifyFraction_().
swap()
void swap (ConsensusMap & from)
Swaps the content of this map with the content of from.
updateRanges()
void updateRanges () override virtual
Updates minimum and maximum position/intensity.
This method is usually implemented by calling clearRanges() and updateRanges_().
Implements RangeManager< 2 >.
Member Data Documentation
column_description_
ColumnHeaders column_description_ protected
Map from index to file description.
data_processing_
std::vector<DataProcessing> data_processing_ protected
applied data processing
experiment_type_
String experiment_type_ = "label-free" protected
type of experiment (label-free, labeled_MS1, labeled_MS2)
protein_identifications_
std::vector<ProteinIdentification> protein_identifications_ protected
protein identifications
unassigned_peptide_identifications_
std::vector<PeptideIdentification> unassigned_peptide_identifications_ protected
unassigned peptide identifications (without feature)