OpenMS: Peak2D Class Reference
Peak2D Class Reference
Kernel
A 2-dimensional raw data point or peak.
#include <OpenMS/KERNEL/Peak2D.h>
Classes
struct IntensityLess
struct MZLess
Comparator by m/z position.
struct PositionLess
Comparator by position. Lexicographical comparison (first RT then m/z) is done.
struct RTLess
Comparator by RT position.
Public Types
Type definitions
typedef float IntensityType
Intensity type.
typedef double CoordinateType
Coordinate type (of the position)
typedef DPosition< 2 > PositionType
Position type.
Public Member Functions
Peak2D & operator= (const Peak2D &rhs)=default
Assignment operator.
Peak2D & operator= (Peak2D &&) &=default
Move assignment operator.
bool operator== (const Peak2D &rhs) const
Equality operator.
bool operator!= (const Peak2D &rhs) const
Equality operator.
Constructors and Destructor
Default constructor
Peak2D ()
Peak2D (const PositionType &pos, const IntensityType in)
Member constructor.
Peak2D (const Peak2D &p)=default
Copy constructor.
Peak2D (Peak2D &&)=default
Move constructor.
~Peak2D ()
Destructor.
Accessors
Non-mutable access to the data point intensity (height)
IntensityType getIntensity () const
void setIntensity (IntensityType intensity)
Non-mutable access to the data point intensity (height)
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (const PositionType &position)
Mutable access to the position.
CoordinateType getMZ () const
Returns the m/z coordinate (index 1)
void setMZ (CoordinateType coordinate)
Mutable access to the m/z coordinate (index 1)
CoordinateType getRT () const
Returns the RT coordinate (index 0)
void setRT (CoordinateType coordinate)
Mutable access to the RT coordinate (index 0)
Protected Attributes
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Friends
std::ostream & operator<< (std::ostream &os, const Peak2D &point)
Print the contents to a stream.
Dimension descriptions
enum DimensionDescription { RT = 0, MZ = 1, DIMENSION = 2 }
This enum maps the symbolic names of the dimensions to numbers.
static const char *const dimension_name_short_ [DIMENSION]
Short name of the dimension (abbreviated form)
static const char *const dimension_name_full_ [DIMENSION]
Full name of the dimension (self-explanatory form)
static const char *const dimension_unit_short_ [DIMENSION]
Unit of measurement (abbreviated form)
static const char *const dimension_unit_full_ [DIMENSION]
Unit of measurement (self-explanatory form)
static const char * shortDimensionName (UInt const dim)
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameRT ()
Short name of the dimension (abbreviated form)
static const char * shortDimensionNameMZ ()
Short name of the dimension (abbreviated form)
static const char * fullDimensionName (UInt const dim)
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameRT ()
Full name of the dimension (self-explanatory form)
static const char * fullDimensionNameMZ ()
Full name of the dimension (self-explanatory form)
static const char * shortDimensionUnit (UInt const dim)
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitRT ()
Unit of measurement (abbreviated form)
static const char * shortDimensionUnitMZ ()
Unit of measurement (abbreviated form)
static const char * fullDimensionUnit (UInt const dim)
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitRT ()
Unit of measurement (self-explanatory form)
static const char * fullDimensionUnitMZ ()
Unit of measurement (self-explanatory form)
Detailed Description
A 2-dimensional raw data point or peak.
This data structure is intended for continuous data or peak data. If you want to annotated single peaks with meta data, use RichPeak2D instead.
Member Typedef Documentation
CoordinateType
typedef double CoordinateType
Coordinate type (of the position)
IntensityType
typedef float IntensityType
Intensity type.
PositionType
typedef DPosition<2> PositionType
Position type.
Member Enumeration Documentation
DimensionDescription
enum DimensionDescription
This enum maps the symbolic names of the dimensions to numbers.
Enumerator
RT
Retention time dimension id (0 if used as a const int)
MZ
Mass-to-charge dimension id (1 if used as a const int)
DIMENSION
Number of dimensions.
Constructor & Destructor Documentation
Peak2D() [1/4]
Peak2D () inline
Peak2D() [2/4]
Peak2D (const PositionType & pos, const IntensityType in) inline explicit
Member constructor.
Peak2D() [3/4]
Peak2D (const Peak2D & p) default
Copy constructor.
Peak2D() [4/4]
Peak2D (Peak2D &&) default
Move constructor.
~Peak2D()
~Peak2D () inline
Destructor.
Note
The destructor is non-virtual although many classes are derived from Peak2D. This is intentional, since otherwise we would "waste" space for a vtable pointer in each instance. Normally you should not derive other classes from Peak2D (unless you know what you are doing, of course).
Member Function Documentation
fullDimensionName()
static const char* fullDimensionName (UInt const dim) static
Full name of the dimension (self-explanatory form)
fullDimensionNameMZ()
static const char* fullDimensionNameMZ () static
Full name of the dimension (self-explanatory form)
fullDimensionNameRT()
static const char* fullDimensionNameRT () static
Full name of the dimension (self-explanatory form)
fullDimensionUnit()
static const char* fullDimensionUnit (UInt const dim) static
Unit of measurement (self-explanatory form)
fullDimensionUnitMZ()
static const char* fullDimensionUnitMZ () static
Unit of measurement (self-explanatory form)
fullDimensionUnitRT()
static const char* fullDimensionUnitRT () static
Unit of measurement (self-explanatory form)
getIntensity()
IntensityType getIntensity () const inline
Referenced by OpenMS::intensityAscendingComparator(), OpenMS::intensityComparator(), OpenMS::intensityPointerComparator(), Peak2D::IntensityLess::operator()(), InIntensityRange< PeakType >::operator()(), and MRMTransitionGroupPicker::pickTransitionGroup().
getMZ()
CoordinateType getMZ () const inline
Returns the m/z coordinate (index 1)
Referenced by TDfeatureDeconvolution::detectPeaks(), TOPPGNPSExport::main_(), SpectraMerger::SpectraDistance_::operator()(), Peak2D::MZLess::operator()(), and OpenMS::positionComparator().
getPosition() [1/2]
PositionType& getPosition () inline
Mutable access to the position.
getPosition() [2/2]
const PositionType& getPosition () const inline
Non-mutable access to the position.
Referenced by Peak2D::PositionLess::operator()(), and InMzRange< PeakType >::operator()().
getRT()
CoordinateType getRT () const inline
Returns the RT coordinate (index 0)
Referenced by TDfeatureDeconvolution::detectPeaks(), TOPPGNPSExport::main_(), SpectraMerger::SpectraDistance_::operator()(), PrecursorIonSelection::SeqTotalScoreMore::operator()(), FeatureFinderIdentificationAlgorithm::FeatureCompare::operator()(), and Peak2D::RTLess::operator()().
operator!=()
bool operator!= (const Peak2D & rhs) const inline
Equality operator.
References KDTree::operator==().
operator=() [1/2]
Peak2D& operator= (const Peak2D & rhs) default
Assignment operator.
Referenced by RichPeak2D::operator=().
operator=() [2/2]
Peak2D& operator= (Peak2D &&) & default
Move assignment operator.
operator==()
bool operator== (const Peak2D & rhs) const inline
Equality operator.
References Peak2D::intensity_, and Peak2D::position_.
Referenced by RichPeak2D::operator==().
setIntensity()
void setIntensity (IntensityType intensity) inline
Non-mutable access to the data point intensity (height)
Referenced by MRMTransitionGroupPicker::createMRMFeature(), SpecArrayFile::load(), MsInspectFile::load(), IsotopeWaveletTransform< PeakType >::mapSeeds2Features(), MRMTransitionGroupPicker::pickFragmentChromatograms(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), LinearResamplerAlign::populate_raster_(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
setMZ()
void setMZ (CoordinateType coordinate) inline
Mutable access to the m/z coordinate (index 1)
Referenced by ChromatogramTools::convertChromatogramsToSpectra(), MsInspectFile::load(), SpecArrayFile::load(), IsotopeWaveletTransform< PeakType >::mapSeeds2Features(), SpectraMerger::mergeSpectraPrecursors(), MRMTransitionGroupPicker::pickFragmentChromatograms(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), and LinearResamplerAlign::populate_raster_().
setPosition()
void setPosition (const PositionType & position) inline
Mutable access to the position.
References seqan::position().
setRT()
void setRT (CoordinateType coordinate) inline
Mutable access to the RT coordinate (index 0)
Referenced by ChromatogramTools::convertSpectraToChromatograms(), MsInspectFile::load(), SpecArrayFile::load(), IsotopeWaveletTransform< PeakType >::mapSeeds2Features(), SpectraMerger::mergeSpectraPrecursors(), MRMTransitionGroupPicker::pickFragmentChromatograms(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
shortDimensionName()
static const char* shortDimensionName (UInt const dim) static
Short name of the dimension (abbreviated form)
Referenced by ProductModel< 2 >::ProductModel(), ProductModel< 2 >::setModel(), and ProductModel< 2 >::updateMembers_().
shortDimensionNameMZ()
static const char* shortDimensionNameMZ () static
Short name of the dimension (abbreviated form)
shortDimensionNameRT()
static const char* shortDimensionNameRT () static
Short name of the dimension (abbreviated form)
shortDimensionUnit()
static const char* shortDimensionUnit (UInt const dim) static
Unit of measurement (abbreviated form)
shortDimensionUnitMZ()
static const char* shortDimensionUnitMZ () static
Unit of measurement (abbreviated form)
shortDimensionUnitRT()
static const char* shortDimensionUnitRT () static
Unit of measurement (abbreviated form)
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Peak2D & point) friend
Print the contents to a stream.
Member Data Documentation
dimension_name_full_
const char* const dimension_name_full_[DIMENSION] static protected
Full name of the dimension (self-explanatory form)
dimension_name_short_
const char* const dimension_name_short_[DIMENSION] static protected
Short name of the dimension (abbreviated form)
dimension_unit_full_
const char* const dimension_unit_full_[DIMENSION] static protected
Unit of measurement (self-explanatory form)
dimension_unit_short_
const char* const dimension_unit_short_[DIMENSION] static protected
Unit of measurement (abbreviated form)
intensity_
IntensityType intensity_ protected
The data point intensity.
Referenced by Peak2D::operator==().
position_
PositionType position_ protected
The data point position.
Referenced by Peak2D::operator==().