OpenMS: Peak1D Class Reference
Peak1D Class Reference
Kernel
A 1-dimensional raw data point or peak.
#include <OpenMS/KERNEL/Peak1D.h>
Classes
struct IntensityLess
struct MZLess
Comparator by m/z position.
struct PositionLess
Comparator by position. As this class has dimension 1, this is basically an alias for MZLess.
Public Types
Type definitions
Dimension
enum { DIMENSION = 1 }
typedef float IntensityType
Intensity type.
typedef DPosition< 1 > PositionType
Position type.
typedef double CoordinateType
Coordinate type.
Public Member Functions
Peak1D & operator= (const Peak1D &rhs)
Assignment operator.
bool operator== (const Peak1D &rhs) const
Equality operator.
bool operator!= (const Peak1D &rhs) const
Equality operator.
Constructors and Destructor
Default constructor
Peak1D ()
Peak1D (PositionType a, IntensityType b)
construct with position and intensity
Peak1D (const Peak1D &p)
Copy constructor.
Peak1D (Peak1D &&) noexcept=default
~Peak1D ()
Destructor.
Accessors
IntensityType getIntensity () const
void setIntensity (IntensityType intensity)
Mutable access to the data point intensity (height)
CoordinateType getMZ () const
Non-mutable access to m/z.
void setMZ (CoordinateType mz)
Mutable access to m/z.
CoordinateType getPos () const
Alias for getMZ()
void setPos (CoordinateType pos)
Alias for setMZ()
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (PositionType const &position)
Mutable access to the position.
Protected Attributes
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Detailed Description
A 1-dimensional raw data point or peak.
This data structure is intended for continuous data or peak data. If you want to annotated single peaks with meta data, use RichPeak1D instead.
Member Typedef Documentation
CoordinateType
typedef double CoordinateType
Coordinate type.
IntensityType
typedef float IntensityType
Intensity type.
PositionType
typedef DPosition<1> PositionType
Position type.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DIMENSION
Constructor & Destructor Documentation
Peak1D() [1/4]
Peak1D () inline
Peak1D() [2/4]
Peak1D (PositionType a, IntensityType b) inline
construct with position and intensity
Peak1D() [3/4]
Peak1D (const Peak1D & p) inline
Copy constructor.
Peak1D() [4/4]
Peak1D (Peak1D &&) default noexcept
~Peak1D()
~Peak1D () inline
Destructor.
Note
The destructor is non-virtual although many classes are derived from Peak1D. This is intentional, since otherwise we would "waste" space for a vtable pointer in each instance. Normally you should not derive other classes from Peak1D (unless you know what you are doing, of course).
Member Function Documentation
getIntensity()
IntensityType getIntensity () const inline
Non-mutable access to the data point intensity (height)
Referenced by DTA2DFile::load(), Peak1D::IntensityLess::operator()(), and MetaProSIPReporting::plotFilteredSpectra().
getMZ()
CoordinateType getMZ () const inline
Non-mutable access to m/z.
Referenced by NucleicAcidSearchEngine::deisotopeAndSingleChargeMSSpectrum_(), DTA2DFile::load(), TOPPGNPSExport::main_(), Peak1D::MZLess::operator()(), MetaProSIPReporting::plotFilteredSpectra(), and DTAFile::store().
getPos()
CoordinateType getPos () const inline
Alias for getMZ()
getPosition() [1/2]
PositionType& getPosition () inline
Mutable access to the position.
getPosition() [2/2]
const PositionType& getPosition () const inline
Non-mutable access to the position.
Referenced by Peak1D::PositionLess::operator()().
operator!=()
bool operator!= (const Peak1D & rhs) const inline
Equality operator.
References KDTree::operator==().
operator=()
Peak1D& operator= (const Peak1D & rhs) inline
Assignment operator.
References Peak1D::intensity_, and Peak1D::position_.
operator==()
bool operator== (const Peak1D & rhs) const inline
Equality operator.
References Peak1D::intensity_, and Peak1D::position_.
setIntensity()
void setIntensity (IntensityType intensity) inline
Mutable access to the data point intensity (height)
Referenced by SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), MetaProSIPDecomposition::calculateDecompositionWeightsIsotopicPatterns(), MascotGenericFile::getNextSpectrum_(), MS2File::load(), DTAFile::load(), MascotInfile::load(), XMassFile::load(), DTA2DFile::load(), PeakPickerSH::pick(), PeakPickerIterative::pick(), and EmgScoring::prepareFit_().
setMZ()
void setMZ (CoordinateType mz) inline
Mutable access to m/z.
Referenced by SpectraMerger::averageCentroidSpectra_(), SpectraMerger::averageProfileSpectra_(), MetaProSIPDecomposition::calculateDecompositionWeightsIsotopicPatterns(), NucleicAcidSearchEngine::deisotopeAndSingleChargeMSSpectrum_(), DTAFile::load(), DTA2DFile::load(), PeakPickerSH::pick(), PeakPickerIterative::pick(), EmgScoring::prepareFit_(), ChromatogramExtractor::prepareSpectra_(), ChromatogramExtractor::return_chromatogram(), and TOPPViewBase::showSpectrumGenerationDialog().
setPos()
void setPos (CoordinateType pos) inline
Alias for setMZ()
setPosition()
void setPosition (PositionType const & position) inline
Mutable access to the position.
References seqan::position().
Referenced by MascotGenericFile::getNextSpectrum_(), MS2File::load(), DTAFile::load(), MascotInfile::load(), and XMassFile::load().
Member Data Documentation
intensity_
IntensityType intensity_ protected
The data point intensity.
Referenced by Peak1D::operator=(), and Peak1D::operator==().
position_
PositionType position_ protected
The data point position.
Referenced by Peak1D::operator=(), and Peak1D::operator==().