OpenMS: Peak1D::IntensityLess Struct Reference
Peak1D::IntensityLess Struct Reference
#include <OpenMS/KERNEL/Peak1D.h>
Public Member Functions
bool operator() (Peak1D const &left, Peak1D const &right) const
bool operator() (Peak1D const &left, IntensityType right) const
bool operator() (IntensityType left, Peak1D const &right) const
bool operator() (IntensityType left, IntensityType right) const
Detailed Description
Comparator by intensity
Member Function Documentation
operator()() [1/4]
bool operator() (IntensityType left, IntensityType right) const inline
operator()() [2/4]
bool operator() (IntensityType left, Peak1D const & right) const inline
References Peak1D::getIntensity().
operator()() [3/4]
bool operator() (Peak1D const & left, IntensityType right) const inline
References Peak1D::getIntensity().
operator()() [4/4]
bool operator() (Peak1D const & left, Peak1D const & right) const inline
References Peak1D::getIntensity().