OpenMS: OnDiscMSExperiment Class Reference
OnDiscMSExperiment Class Reference
Kernel
Representation of a mass spectrometry experiment on disk.
#include <OpenMS/KERNEL/OnDiscMSExperiment.h>
Public Member Functions
OnDiscMSExperiment ()
Constructor.
bool openFile (const String &filename, bool skipMetaData=false)
Open a specific file on disk.
OnDiscMSExperiment (const OnDiscMSExperiment &source)
Copy constructor.
bool operator== (const OnDiscMSExperiment &rhs) const
Equality operator.
bool operator!= (const OnDiscMSExperiment &rhs) const
Inequality operator.
bool isSortedByRT () const
Checks if all spectra are sorted with respect to ascending RT.
Size size () const
alias for getNrSpectra
bool empty () const
returns whether spectra are empty
Size getNrSpectra () const
get the total number of spectra available
Size getNrChromatograms () const
get the total number of chromatograms available
boost::shared_ptr< const ExperimentalSettings > getExperimentalSettings () const
returns the meta information of this experiment (const access)
boost::shared_ptr< PeakMap > getMetaData () const
MSSpectrum operator[] (Size n)
alias for getSpectrum
MSSpectrum getSpectrum (Size id)
returns a single spectrum
OpenMS::Interfaces::SpectrumPtr getSpectrumById (Size id)
returns a single spectrum
MSChromatogram getChromatogram (Size id)
returns a single chromatogram
OpenMS::Interfaces::ChromatogramPtr getChromatogramById (Size id)
returns a single chromatogram
void setSkipXMLChecks (bool skip)
sets whether to skip some XML checks and be fast instead
Protected Attributes
String filename_
The filename of the underlying data file.
Internal::IndexedMzMLHandler indexed_mzml_file_
The index of the underlying data file.
boost::shared_ptr< PeakMap > meta_ms_experiment_
The meta-data.
Private Types
typedef ChromatogramPeak ChromatogramPeakT
typedef Peak1D PeakT
Private Member Functions
OnDiscMSExperiment & operator= (const OnDiscMSExperiment &)
Private Assignment operator -> we cannot copy file streams in IndexedMzMLHandler.
void loadMetaData_ (const String &filename)
Detailed Description
Representation of a mass spectrometry experiment on disk.
Note
This implementation is not thread-safe since it keeps internally a single file access pointer which it moves when accessing a specific data item. Please provide a separate copy to each thread, e.g.
#pragma omp parallel for firstprivate(ondisc_map)
Member Typedef Documentation
ChromatogramPeakT
typedef ChromatogramPeak ChromatogramPeakT private
PeakT
typedef Peak1D PeakT private
Constructor & Destructor Documentation
OnDiscMSExperiment() [1/2]
OnDiscMSExperiment () inline
Constructor.
This initializes the object, use openFile to open a file.
OnDiscMSExperiment() [2/2]
OnDiscMSExperiment (const OnDiscMSExperiment & source) inline
Copy constructor.
Member Function Documentation
empty()
bool empty () const inline
returns whether spectra are empty
getChromatogram()
MSChromatogram getChromatogram (Size id) inline
returns a single chromatogram
Parameters
id The index of the chromatogram
Referenced by IndexedMzMLFileLoader::store().
getChromatogramById()
OpenMS::Interfaces::ChromatogramPtr getChromatogramById (Size id) inline
returns a single chromatogram
getExperimentalSettings()
boost::shared_ptr<const ExperimentalSettings> getExperimentalSettings () const inline
returns the meta information of this experiment (const access)
Referenced by IndexedMzMLFileLoader::store().
getMetaData()
boost::shared_ptr<PeakMap> getMetaData () const inline
getNrChromatograms()
Size getNrChromatograms () const inline
get the total number of chromatograms available
Referenced by IndexedMzMLFileLoader::store().
getNrSpectra()
Size getNrSpectra () const inline
get the total number of spectra available
Referenced by IndexedMzMLFileLoader::store().
getSpectrum()
MSSpectrum getSpectrum (Size id) inline
returns a single spectrum
Parameters
id The index of the spectrum
Referenced by IndexedMzMLFileLoader::store().
getSpectrumById()
OpenMS::Interfaces::SpectrumPtr getSpectrumById (Size id) inline
returns a single spectrum
isSortedByRT()
bool isSortedByRT () const inline
Checks if all spectra are sorted with respect to ascending RT.
Note that we cannot check whether all spectra are sorted (except if we were to load them all and check).
loadMetaData_()
void loadMetaData_ (const String & filename) private
openFile()
bool openFile (const String & filename, bool skipMetaData = false) inline
Open a specific file on disk.
This tries to read the indexed mzML by parsing the index and then reading the meta information into memory.
Returns
Whether the parsing of the file was successful (if false, the file most likely was not an indexed mzML file)
Referenced by IndexedMzMLFileLoader::load().
operator!=()
bool operator!= (const OnDiscMSExperiment & rhs) const inline
Inequality operator.
References KDTree::operator==().
operator=()
OnDiscMSExperiment& operator= (const OnDiscMSExperiment &) private
Private Assignment operator -> we cannot copy file streams in IndexedMzMLHandler.
operator==()
bool operator== (const OnDiscMSExperiment & rhs) const inline
Equality operator.
This only checks whether the underlying file is the same and the parsed meta-information is the same. Note that the file reader (e.g. the std::ifstream of the file) might be in a different state.
References OnDiscMSExperiment::filename_, and OnDiscMSExperiment::meta_ms_experiment_.
operator[]()
MSSpectrum operator[] (Size n) inline
alias for getSpectrum
setSkipXMLChecks()
void setSkipXMLChecks (bool skip) inline
sets whether to skip some XML checks and be fast instead
size()
Size size () const inline
alias for getNrSpectra
Member Data Documentation
filename_
String filename_ protected
The filename of the underlying data file.
Referenced by OnDiscMSExperiment::operator==().
indexed_mzml_file_
Internal::IndexedMzMLHandler indexed_mzml_file_ protected
The index of the underlying data file.
meta_ms_experiment_
boost::shared_ptr<PeakMap> meta_ms_experiment_ protected
The meta-data.
Referenced by OnDiscMSExperiment::operator==().