OpenMS: Peak1D::MZLess Struct Reference
Peak1D::MZLess Struct Reference
Comparator by m/z position.
#include <OpenMS/KERNEL/Peak1D.h>
Public Member Functions
bool operator() (const Peak1D &left, const Peak1D &right) const
bool operator() (Peak1D const &left, CoordinateType right) const
bool operator() (CoordinateType left, Peak1D const &right) const
bool operator() (CoordinateType left, CoordinateType right) const
Detailed Description
Comparator by m/z position.
Member Function Documentation
operator()() [1/4]
bool operator() (const Peak1D & left, const Peak1D & right) const inline
References Peak1D::getMZ().
operator()() [2/4]
bool operator() (CoordinateType left, CoordinateType right) const inline
operator()() [3/4]
bool operator() (CoordinateType left, Peak1D const & right) const inline
References Peak1D::getMZ().
operator()() [4/4]
bool operator() (Peak1D const & left, CoordinateType right) const inline
References Peak1D::getMZ().