OpenMS: EmgGradientDescent_friend Class Reference
EmgGradientDescent_friend Class Reference
#include <OpenMS/MATH/MISC/EmgGradientDescent.h>
Public Member Functions
EmgGradientDescent_friend ()=default
~EmgGradientDescent_friend ()=default
double Loss_function (const std::vector< double > &xs, const std::vector< double > &ys, const double h, const double mu, const double sigma, const double tau) const
double computeMuMaxDistance (const std::vector< double > &xs) const
void extractTrainingSet (const std::vector< double > &xs, const std::vector< double > &ys, std::vector< double > &TrX, std::vector< double > &TrY) const
double computeInitialMean (const std::vector< double > &xs, const std::vector< double > &ys) const
void iRpropPlus (const double prev_diff_E_param, double &diff_E_param, double &param_lr, double &param_update, double &param, const double current_E, const double previous_E) const
double compute_z (const double x, const double mu, const double sigma, const double tau) const
void applyEstimatedParameters (const std::vector< double > &xs, const double h, const double mu, const double sigma, const double tau, std::vector< double > &out_xs, std::vector< double > &out_ys) const
double emg_point (const double x, const double h, const double mu, const double sigma, const double tau) const
Public Attributes
EmgGradientDescent emg_gd_
Constructor & Destructor Documentation
EmgGradientDescent_friend()
EmgGradientDescent_friend () default
~EmgGradientDescent_friend()
~EmgGradientDescent_friend () default
Member Function Documentation
applyEstimatedParameters()
void applyEstimatedParameters (const std::vector< double > & xs, const double h, const double mu, const double sigma, const double tau, std::vector< double > & out_xs, std::vector< double > & out_ys) const inline
References EmgGradientDescent::applyEstimatedParameters(), EmgGradientDescent_friend::emg_gd_, and OpenMS::Constants::h.
compute_z()
double compute_z (const double x, const double mu, const double sigma, const double tau) const inline
References EmgGradientDescent::compute_z(), and EmgGradientDescent_friend::emg_gd_.
computeInitialMean()
double computeInitialMean (const std::vector< double > & xs, const std::vector< double > & ys) const inline
References EmgGradientDescent::computeInitialMean(), and EmgGradientDescent_friend::emg_gd_.
computeMuMaxDistance()
double computeMuMaxDistance (const std::vector< double > & xs) const inline
References EmgGradientDescent::computeMuMaxDistance(), and EmgGradientDescent_friend::emg_gd_.
emg_point()
double emg_point (const double x, const double h, const double mu, const double sigma, const double tau) const inline
References EmgGradientDescent_friend::emg_gd_, EmgGradientDescent::emg_point(), and OpenMS::Constants::h.
extractTrainingSet()
void extractTrainingSet (const std::vector< double > & xs, const std::vector< double > & ys, std::vector< double > & TrX, std::vector< double > & TrY) const inline
References EmgGradientDescent_friend::emg_gd_, and EmgGradientDescent::extractTrainingSet().
iRpropPlus()
void iRpropPlus (const double prev_diff_E_param, double & diff_E_param, double & param_lr, double & param_update, double & param, const double current_E, const double previous_E) const inline
References EmgGradientDescent_friend::emg_gd_, and EmgGradientDescent::iRpropPlus().
Loss_function()
double Loss_function (const std::vector< double > & xs, const std::vector< double > & ys, const double h, const double mu, const double sigma, const double tau) const inline
References EmgGradientDescent_friend::emg_gd_, OpenMS::Constants::h, and EmgGradientDescent::Loss_function().
Member Data Documentation
emg_gd_
EmgGradientDescent emg_gd_
Referenced by EmgGradientDescent_friend::applyEstimatedParameters(), EmgGradientDescent_friend::compute_z(), EmgGradientDescent_friend::computeInitialMean(), EmgGradientDescent_friend::computeMuMaxDistance(), EmgGradientDescent_friend::emg_point(), EmgGradientDescent_friend::extractTrainingSet(), EmgGradientDescent_friend::iRpropPlus(), and EmgGradientDescent_friend::Loss_function().