OpenMS: ChromatogramSettings Class Reference
ChromatogramSettings Class Reference
Metadata
Representation of chromatogram settings, e.g. SRM/MRM chromatograms.
#include <OpenMS/METADATA/ChromatogramSettings.h>
Public Types
enum ChromatogramType {
MASS_CHROMATOGRAM = 0, TOTAL_ION_CURRENT_CHROMATOGRAM, SELECTED_ION_CURRENT_CHROMATOGRAM, BASEPEAK_CHROMATOGRAM,
SELECTED_ION_MONITORING_CHROMATOGRAM, SELECTED_REACTION_MONITORING_CHROMATOGRAM, ELECTROMAGNETIC_RADIATION_CHROMATOGRAM, ABSORPTION_CHROMATOGRAM,
EMISSION_CHROMATOGRAM, SIZE_OF_CHROMATOGRAM_TYPE
}
Public Member Functions
ChromatogramSettings ()
Constructor.
ChromatogramSettings (const ChromatogramSettings &)=default
Copy constructor.
ChromatogramSettings (ChromatogramSettings &&)=default
Move constructor.
virtual ~ChromatogramSettings ()
Destructor.
ChromatogramSettings & operator= (const ChromatogramSettings &)=default
ChromatogramSettings & operator= (ChromatogramSettings &&) &=default
Move assignment operator.
bool operator== (const ChromatogramSettings &rhs) const
Equality operator.
bool operator!= (const ChromatogramSettings &rhs) const
Equality operator.
const String & getNativeID () const
returns the native identifier for the spectrum, used by the acquisition software.
void setNativeID (const String &native_id)
sets the native identifier for the spectrum, used by the acquisition software.
const String & getComment () const
returns the free-text comment
void setComment (const String &comment)
sets the free-text comment
const InstrumentSettings & getInstrumentSettings () const
returns a const reference to the instrument settings of the current spectrum
InstrumentSettings & getInstrumentSettings ()
returns a mutable reference to the instrument settings of the current spectrum
void setInstrumentSettings (const InstrumentSettings &instrument_settings)
sets the instrument settings of the current spectrum
const AcquisitionInfo & getAcquisitionInfo () const
returns a const reference to the acquisition info
AcquisitionInfo & getAcquisitionInfo ()
returns a mutable reference to the acquisition info
void setAcquisitionInfo (const AcquisitionInfo &acquisition_info)
sets the acquisition info
const SourceFile & getSourceFile () const
returns a const reference to the source file
SourceFile & getSourceFile ()
returns a mutable reference to the source file
void setSourceFile (const SourceFile &source_file)
sets the source file
const Precursor & getPrecursor () const
returns a const reference to the precursors
Precursor & getPrecursor ()
returns a mutable reference to the precursors
void setPrecursor (const Precursor &precursor)
sets the precursors
const Product & getProduct () const
returns a const reference to the products
Product & getProduct ()
returns a mutable reference to the products
void setProduct (const Product &product)
sets the products
ChromatogramType getChromatogramType () const
returns the chromatogram type, e.g. a SRM chromatogram
void setChromatogramType (ChromatogramType type)
sets the chromatogram type
void setDataProcessing (const std::vector< DataProcessingPtr > &data_processing)
sets the description of the applied processing
std::vector< DataProcessingPtr > & getDataProcessing ()
returns a mutable reference to the description of the applied processing
const std::vector< boost::shared_ptr< const DataProcessing > > getDataProcessing () const
returns a const reference to the description of the applied processing
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Attributes
static const char *const ChromatogramNames [SIZE_OF_CHROMATOGRAM_TYPE+1]
Names of chromatogram types corresponding to enum ChromatogramType.
Protected Attributes
String native_id_
String comment_
InstrumentSettings instrument_settings_
SourceFile source_file_
AcquisitionInfo acquisition_info_
Precursor precursor_
Product product_
std::vector< DataProcessingPtr > data_processing_
ChromatogramType type_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Representation of chromatogram settings, e.g. SRM/MRM chromatograms.
It contains the metadata about chromatogram specific instrument settings, acquisition settings, description of the meta values used in the peaks and precursor info.
Member Enumeration Documentation
ChromatogramType
enum ChromatogramType
List of chromatogram names, e.g., SELECTED_REACTION_MONITORING_CHROMATOGRAM. Actual names can be accessed using the ChromatogramNames[] array
Enumerator
MASS_CHROMATOGRAM
TOTAL_ION_CURRENT_CHROMATOGRAM
SELECTED_ION_CURRENT_CHROMATOGRAM
BASEPEAK_CHROMATOGRAM
SELECTED_ION_MONITORING_CHROMATOGRAM
SELECTED_REACTION_MONITORING_CHROMATOGRAM
ELECTROMAGNETIC_RADIATION_CHROMATOGRAM
ABSORPTION_CHROMATOGRAM
EMISSION_CHROMATOGRAM
SIZE_OF_CHROMATOGRAM_TYPE
Constructor & Destructor Documentation
ChromatogramSettings() [1/3]
ChromatogramSettings ()
Constructor.
ChromatogramSettings() [2/3]
ChromatogramSettings (const ChromatogramSettings &) default
Copy constructor.
ChromatogramSettings() [3/3]
ChromatogramSettings (ChromatogramSettings &&) default
Move constructor.
~ChromatogramSettings()
virtual ~ChromatogramSettings () virtual
Destructor.
Member Function Documentation
getAcquisitionInfo() [1/2]
AcquisitionInfo& getAcquisitionInfo ()
returns a mutable reference to the acquisition info
getAcquisitionInfo() [2/2]
const AcquisitionInfo& getAcquisitionInfo () const
returns a const reference to the acquisition info
getChromatogramType()
ChromatogramType getChromatogramType () const
returns the chromatogram type, e.g. a SRM chromatogram
getComment()
const String& getComment () const
returns the free-text comment
getDataProcessing() [1/2]
std::vector< DataProcessingPtr >& getDataProcessing ()
returns a mutable reference to the description of the applied processing
Referenced by ChromatogramExtractor::return_chromatogram().
getDataProcessing() [2/2]
const std::vector< boost::shared_ptr<const DataProcessing > > getDataProcessing () const
returns a const reference to the description of the applied processing
getInstrumentSettings() [1/2]
InstrumentSettings& getInstrumentSettings ()
returns a mutable reference to the instrument settings of the current spectrum
getInstrumentSettings() [2/2]
const InstrumentSettings& getInstrumentSettings () const
returns a const reference to the instrument settings of the current spectrum
getNativeID()
const String& getNativeID () const
returns the native identifier for the spectrum, used by the acquisition software.
Referenced by MRMTransitionGroup< SpectrumT, TransitionT >::chromatogramIdsMatch(), and MRMTransitionGroupPicker::pickTransitionGroup().
getPrecursor() [1/2]
Precursor& getPrecursor ()
returns a mutable reference to the precursors
getPrecursor() [2/2]
const Precursor& getPrecursor () const
returns a const reference to the precursors
getProduct() [1/2]
Product& getProduct ()
returns a mutable reference to the products
getProduct() [2/2]
const Product& getProduct () const
returns a const reference to the products
getSourceFile() [1/2]
SourceFile& getSourceFile ()
returns a mutable reference to the source file
getSourceFile() [2/2]
const SourceFile& getSourceFile () const
returns a const reference to the source file
operator!=()
bool operator!= (const ChromatogramSettings & rhs) const
Equality operator.
operator=() [1/2]
ChromatogramSettings& operator= (ChromatogramSettings &&) & default
Move assignment operator.
operator=() [2/2]
ChromatogramSettings& operator= (const ChromatogramSettings &) default
operator==()
bool operator== (const ChromatogramSettings & rhs) const
Equality operator.
setAcquisitionInfo()
void setAcquisitionInfo (const AcquisitionInfo & acquisition_info)
sets the acquisition info
Referenced by ChromatogramExtractor::return_chromatogram().
setChromatogramType()
void setChromatogramType (ChromatogramType type)
sets the chromatogram type
Referenced by ChromatogramExtractor::return_chromatogram().
setComment()
void setComment (const String & comment)
sets the free-text comment
setDataProcessing()
void setDataProcessing (const std::vector< DataProcessingPtr > & data_processing)
sets the description of the applied processing
setInstrumentSettings()
void setInstrumentSettings (const InstrumentSettings & instrument_settings)
sets the instrument settings of the current spectrum
Referenced by ChromatogramExtractor::return_chromatogram().
setNativeID()
void setNativeID (const String & native_id)
sets the native identifier for the spectrum, used by the acquisition software.
Referenced by ChromatogramExtractor::return_chromatogram().
setPrecursor()
void setPrecursor (const Precursor & precursor)
sets the precursors
Referenced by ChromatogramTools::convertSpectraToChromatograms(), and ChromatogramExtractor::return_chromatogram().
setProduct()
void setProduct (const Product & product)
sets the products
Referenced by ChromatogramExtractor::return_chromatogram().
setSourceFile()
void setSourceFile (const SourceFile & source_file)
sets the source file
Referenced by ChromatogramExtractor::return_chromatogram().
Member Data Documentation
acquisition_info_
AcquisitionInfo acquisition_info_ protected
ChromatogramNames
const char* const ChromatogramNames[SIZE_OF_CHROMATOGRAM_TYPE+1] static
Names of chromatogram types corresponding to enum ChromatogramType.
comment_
String comment_ protected
data_processing_
std::vector< DataProcessingPtr > data_processing_ protected
instrument_settings_
InstrumentSettings instrument_settings_ protected
native_id_
String native_id_ protected
precursor_
Precursor precursor_ protected
product_
Product product_ protected
source_file_
SourceFile source_file_ protected
type_
ChromatogramType type_ protected