OpenMS: SummaryStatistics< T > Struct Template Reference
SummaryStatistics< T > Struct Template Reference
Helper class to gather (and dump) some statistics from a e.g. vector<double>.
#include <OpenMS/MATH/STATISTICS/StatisticFunctions.h>
Public Member Functions
SummaryStatistics ()
SummaryStatistics (T &data)
Public Attributes
double mean
double variance
double lowerq
double median
double upperq
T::value_type min
T::value_type max
size_t count
Detailed Description
template<typename T>
struct OpenMS::Math::SummaryStatistics< T >
Helper class to gather (and dump) some statistics from a e.g. vector<double>.
Constructor & Destructor Documentation
SummaryStatistics() [1/2]
SummaryStatistics () inline
SummaryStatistics() [2/2]
SummaryStatistics (T & data) inline
References SummaryStatistics< T >::count, SummaryStatistics< T >::lowerq, SummaryStatistics< T >::max, OpenMS::Math::mean(), SummaryStatistics< T >::mean, OpenMS::Math::median(), SummaryStatistics< T >::median, SummaryStatistics< T >::min, OpenMS::Math::quantile1st(), OpenMS::Math::quantile3rd(), SummaryStatistics< T >::upperq, OpenMS::Math::variance(), and SummaryStatistics< T >::variance.
Member Data Documentation
count
size_t count
Referenced by SummaryStatistics< T >::SummaryStatistics().
lowerq
double lowerq
Referenced by SummaryStatistics< T >::SummaryStatistics().
max
T::value_type max
Referenced by SummaryStatistics< T >::SummaryStatistics().
mean
double mean
Referenced by SummaryStatistics< T >::SummaryStatistics().
median
double median
Referenced by SummaryStatistics< T >::SummaryStatistics().
min
T::value_type min
Referenced by SummaryStatistics< T >::SummaryStatistics().
upperq
double upperq
Referenced by SummaryStatistics< T >::SummaryStatistics().
variance
double variance
Referenced by SummaryStatistics< T >::SummaryStatistics().