OpenMS: CVTermListInterface Class Reference
CVTermListInterface Class Reference
Metadata
Interface to the controlled vocabulary term list.
#include <OpenMS/METADATA/CVTermListInterface.h>
Constructors and Assignment
CVTermList * cvt_ptr_
CVTermListInterface ()
CVTermListInterface (const CVTermListInterface &rhs)
Copy constructor.
CVTermListInterface (CVTermListInterface &&) noexcept
Move constructor.
~CVTermListInterface ()
CVTermListInterface & operator= (const CVTermListInterface &rhs)
Assignment operator.
CVTermListInterface & operator= (CVTermListInterface &&) noexcept
Move assignment operator.
bool operator== (const CVTermListInterface &rhs) const
equality operator
bool operator!= (const CVTermListInterface &rhs) const
inequality operator
void replaceCVTerms (Map< String, std::vector< CVTerm > > &cv_terms)
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
void createIfNotExists_ ()
Additional Inherited Members
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Interface to the controlled vocabulary term list.
This class is an interface to CVTermList, providing the same interface and it can be used instead (direct plug-in). It can be used to inherit from instead of CVTermList. The advantage is that this class only stores a single pointer to a CVTermList which may be more efficient for an empty list than storing the whole object.
Constructor & Destructor Documentation
CVTermListInterface() [1/3]
CVTermListInterface ()
CVTermListInterface() [2/3]
CVTermListInterface (const CVTermListInterface & rhs)
Copy constructor.
CVTermListInterface() [3/3]
CVTermListInterface (CVTermListInterface &&) noexcept
Move constructor.
~CVTermListInterface()
~CVTermListInterface ()
Member Function Documentation
addCVTerm()
void addCVTerm (const CVTerm & term)
adds a CV term
consumeCVTerms()
void consumeCVTerms (const Map< String, std::vector< CVTerm > > & cv_term_map)
merges the given map into the member map, no duplicate checking
createIfNotExists_()
void createIfNotExists_ () private
empty()
bool empty () const
getCVTerms()
const Map<String, std::vector<CVTerm> >& getCVTerms () const
returns the accession string of the term
hasCVTerm()
bool hasCVTerm (const String & accession) const
checks whether the term has a value
operator!=()
bool operator!= (const CVTermListInterface & rhs) const
inequality operator
operator=() [1/2]
CVTermListInterface& operator= (const CVTermListInterface & rhs)
Assignment operator.
operator=() [2/2]
CVTermListInterface& operator= (CVTermListInterface &&) noexcept
Move assignment operator.
operator==()
bool operator== (const CVTermListInterface & rhs) const
equality operator
Referenced by RetentionTime::operator==(), Interpretation::operator==(), and TraMLProduct::operator==().
replaceCVTerm()
void replaceCVTerm (const CVTerm & cv_term)
replaces the specified CV term
replaceCVTerms() [1/3]
void replaceCVTerms (const Map< String, std::vector< CVTerm > > & cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
replaceCVTerms() [2/3]
void replaceCVTerms (const std::vector< CVTerm > & cv_terms, const String & accession)
replaces the specified CV terms using the given accession number
replaceCVTerms() [3/3]
void replaceCVTerms (Map< String, std::vector< CVTerm > > & cv_terms)
setCVTerms()
void setCVTerms (const std::vector< CVTerm > & terms)
sets the CV terms
Member Data Documentation
cvt_ptr_
CVTermList* cvt_ptr_ private