OpenMS: CVTermList Class Reference
CVTermList Class Reference
Metadata
Representation of controlled vocabulary term list.
#include <OpenMS/METADATA/CVTermList.h>
Public Member Functions
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
Accessors
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Predicates
checks whether the spellings of the CV terms stored are correct
corrects the CVTerm names, according to the loaded CV
Map< String, std::vector< CVTerm > > cv_terms_
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Representation of controlled vocabulary term list.
This class should be used to inherit from, to allow to add an arbitrary number of CV terms to the inherited class Representation of a CV term used by CVMappings
Constructor & Destructor Documentation
CVTermList() [1/3]
CVTermList () default
Defaults constructor.
CVTermList() [2/3]
CVTermList (const CVTermList &) default
Copy constructor.
CVTermList() [3/3]
CVTermList (CVTermList &&) noexcept
Move constructor.
~CVTermList()
virtual ~CVTermList () virtual
Destructor.
Member Function Documentation
addCVTerm()
void addCVTerm (const CVTerm & term)
adds a CV term
consumeCVTerms()
void consumeCVTerms (const Map< String, std::vector< CVTerm > > & cv_term_map)
merges the given map into the member map, no duplicate checking
empty()
bool empty () const
return true if no terms are available
checks whether the stored terms fulfill a given CVMappingRule TODO : implement
getCVTerms()
const Map<String, std::vector<CVTerm> >& getCVTerms () const
returns the accession string of the term
hasCVTerm()
bool hasCVTerm (const String & accession) const
checks whether the term has a value
operator!=()
bool operator!= (const CVTermList & cv_term_list) const
inequality operator
operator=() [1/2]
CVTermList& operator= (const CVTermList & rhs) & default
Assignment operator.
operator=() [2/2]
CVTermList& operator= (CVTermList &&) & default
Move assignment operator.
operator==()
bool operator== (const CVTermList & cv_term_list) const
equality operator
Referenced by Protein::operator==(), PeptideCompound::operator==(), Contact::operator==(), Publication::operator==(), Instrument::operator==(), and Prediction::operator==().
replaceCVTerm()
void replaceCVTerm (const CVTerm & cv_term)
replaces the specified CV term
replaceCVTerms() [1/2]
void replaceCVTerms (const Map< String, std::vector< CVTerm > > & cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
replaceCVTerms() [2/2]
void replaceCVTerms (const std::vector< CVTerm > & cv_terms, const String & accession)
replaces the specified CV terms using the given accession number
setCVTerms()
void setCVTerms (const std::vector< CVTerm > & terms)
sets the CV terms
Member Data Documentation
cv_terms_
Map<String, std::vector<CVTerm> > cv_terms_ protected