OpenMS: DataProcessing Class Reference
DataProcessing Class Reference
Metadata
Description of the applied preprocessing steps.
#include <OpenMS/METADATA/DataProcessing.h>
Public Types
enum ProcessingAction {
DATA_PROCESSING, CHARGE_DECONVOLUTION, DEISOTOPING, SMOOTHING,
CHARGE_CALCULATION, PRECURSOR_RECALCULATION, BASELINE_REDUCTION, PEAK_PICKING,
ALIGNMENT, CALIBRATION, NORMALIZATION, FILTERING,
QUANTITATION, FEATURE_GROUPING, IDENTIFICATION_MAPPING, FORMAT_CONVERSION,
CONVERSION_MZDATA, CONVERSION_MZML, CONVERSION_MZXML, CONVERSION_DTA,
SIZE_OF_PROCESSINGACTION
}
Public Member Functions
DataProcessing ()=default
Constructor.
DataProcessing (const DataProcessing &)=default
Copy constructor.
DataProcessing (DataProcessing &&) noexcept
Move constructor.
~DataProcessing ()
Destructor.
DataProcessing & operator= (const DataProcessing &)=default
Assignment operator.
DataProcessing & operator= (DataProcessing &&) &=default
Move assignment operator.
bool operator== (const DataProcessing &rhs) const
Equality operator.
bool operator!= (const DataProcessing &rhs) const
Equality operator.
const Software & getSoftware () const
returns a const reference to the software used for processing
Software & getSoftware ()
returns a mutable reference to the software used for processing
void setSoftware (const Software &software)
sets the software used for processing
const std::set< ProcessingAction > & getProcessingActions () const
returns a const reference to the applied processing actions
std::set< ProcessingAction > & getProcessingActions ()
returns a mutable reference to the description of the applied processing
void setProcessingActions (const std::set< ProcessingAction > &actions)
sets the description of the applied processing
const DateTime & getCompletionTime () const
returns the time of completion of the processing
void setCompletionTime (const DateTime &completion_time)
sets the time of completion taking a DateTime object
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Attributes
static const std::string NamesOfProcessingAction [SIZE_OF_PROCESSINGACTION]
Names of inlet types.
Protected Attributes
Software software_
std::set< ProcessingAction > processing_actions_
DateTime completion_time_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Description of the applied preprocessing steps.
Member Enumeration Documentation
ProcessingAction
enum ProcessingAction
Enumerator
DATA_PROCESSING
General data processing (if no other term applies)
CHARGE_DECONVOLUTION
Charge deconvolution.
DEISOTOPING
Deisotoping.
SMOOTHING
Smoothing of the signal to reduce noise.
CHARGE_CALCULATION
Determination of the peak charge.
PRECURSOR_RECALCULATION
Recalculation of precursor m/z.
BASELINE_REDUCTION
Baseline reduction.
PEAK_PICKING
Peak picking (conversion from raw to peak data)
ALIGNMENT
Retention time alignment of different maps.
CALIBRATION
Calibration of m/z positions.
NORMALIZATION
Normalization of intensity values.
FILTERING
Data filtering or extraction.
QUANTITATION
Quantitation.
FEATURE_GROUPING
Feature grouping
IDENTIFICATION_MAPPING
Identification mapping
FORMAT_CONVERSION
General file format conversion (if no other term applies)
CONVERSION_MZDATA
Conversion to mzData format.
CONVERSION_MZML
Conversion to mzML format.
CONVERSION_MZXML
Conversion to mzXML format.
CONVERSION_DTA
Conversion to DTA format.
SIZE_OF_PROCESSINGACTION
Constructor & Destructor Documentation
DataProcessing() [1/3]
DataProcessing () default
Constructor.
DataProcessing() [2/3]
DataProcessing (const DataProcessing &) default
Copy constructor.
DataProcessing() [3/3]
DataProcessing (DataProcessing &&) noexcept
Move constructor.
~DataProcessing()
~DataProcessing ()
Destructor.
Member Function Documentation
getCompletionTime()
const DateTime& getCompletionTime () const
returns the time of completion of the processing
getProcessingActions() [1/2]
std::set<ProcessingAction>& getProcessingActions ()
returns a mutable reference to the description of the applied processing
getProcessingActions() [2/2]
const std::set<ProcessingAction>& getProcessingActions () const
returns a const reference to the applied processing actions
getSoftware() [1/2]
Software& getSoftware ()
returns a mutable reference to the software used for processing
getSoftware() [2/2]
const Software& getSoftware () const
returns a const reference to the software used for processing
operator!=()
bool operator!= (const DataProcessing & rhs) const
Equality operator.
operator=() [1/2]
DataProcessing& operator= (const DataProcessing &) default
Assignment operator.
operator=() [2/2]
DataProcessing& operator= (DataProcessing &&) & default
Move assignment operator.
operator==()
bool operator== (const DataProcessing & rhs) const
Equality operator.
setCompletionTime()
void setCompletionTime (const DateTime & completion_time)
sets the time of completion taking a DateTime object
Referenced by XMassFile::load().
setProcessingActions()
void setProcessingActions (const std::set< ProcessingAction > & actions)
sets the description of the applied processing
Referenced by XMassFile::load().
setSoftware()
void setSoftware (const Software & software)
sets the software used for processing
Referenced by XMassFile::load().
Member Data Documentation
completion_time_
DateTime completion_time_ protected
NamesOfProcessingAction
const std::string NamesOfProcessingAction[SIZE_OF_PROCESSINGACTION] static
Names of inlet types.
processing_actions_
std::set<ProcessingAction> processing_actions_ protected
software_
Software software_ protected