OpenMS: ExperimentalSettings Class Reference
ExperimentalSettings Class Reference
Metadata
Description of the experimental settings.
#include <OpenMS/METADATA/ExperimentalSettings.h>
Public Member Functions
ExperimentalSettings ()=default
Constructor.
ExperimentalSettings (const ExperimentalSettings &)=default
Copy constructor.
ExperimentalSettings (ExperimentalSettings &&)=default
Move constructor.
~ExperimentalSettings () override
Destructor.
ExperimentalSettings & operator= (const ExperimentalSettings &)=default
Assignment operator.
ExperimentalSettings & operator= (ExperimentalSettings &&) &=default
Move assignment operator.
bool operator== (const ExperimentalSettings &rhs) const
Equality operator.
bool operator!= (const ExperimentalSettings &rhs) const
Equality operator.
const Sample & getSample () const
returns a const reference to the sample description
Sample & getSample ()
returns a mutable reference to the sample description
void setSample (const Sample &sample)
sets the sample description
const std::vector< SourceFile > & getSourceFiles () const
returns a const reference to the source data file
std::vector< SourceFile > & getSourceFiles ()
returns a mutable reference to the source data file
void setSourceFiles (const std::vector< SourceFile > &source_files)
sets the source data file
const std::vector< ContactPerson > & getContacts () const
returns a const reference to the list of contact persons
std::vector< ContactPerson > & getContacts ()
returns a mutable reference to the list of contact persons
void setContacts (const std::vector< ContactPerson > &contacts)
sets the list of contact persons
const Instrument & getInstrument () const
returns a const reference to the MS instrument description
Instrument & getInstrument ()
returns a mutable reference to the MS instrument description
void setInstrument (const Instrument &instrument)
sets the MS instrument description
const HPLC & getHPLC () const
returns a const reference to the description of the HPLC run
HPLC & getHPLC ()
returns a mutable reference to the description of the HPLC run
void setHPLC (const HPLC &hplc)
sets the description of the HPLC run
const DateTime & getDateTime () const
returns the date the experiment was performed
void setDateTime (const DateTime &date)
sets the date the experiment was performed
const String & getComment () const
returns the free-text comment
void setComment (const String &comment)
sets the free-text comment
const std::vector< ProteinIdentification > & getProteinIdentifications () const
returns a const reference to the protein ProteinIdentification vector
std::vector< ProteinIdentification > & getProteinIdentifications ()
returns a mutable reference to the protein ProteinIdentification vector
void setProteinIdentifications (const std::vector< ProteinIdentification > &protein_identifications)
sets the protein ProteinIdentification vector
const String & getFractionIdentifier () const
returns fraction identifier
void setFractionIdentifier (const String &fraction_identifier)
sets the fraction identifier
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from DocumentIdentifier
DocumentIdentifier ()
Default constructor.
DocumentIdentifier (const DocumentIdentifier &)=default
Copy constructor.
DocumentIdentifier (DocumentIdentifier &&)=default
Move constructor.
virtual ~DocumentIdentifier ()
Destructor.
DocumentIdentifier & operator= (const DocumentIdentifier &)=default
Assignment operator.
DocumentIdentifier & operator= (DocumentIdentifier &&) &=default
Move assignment operator.
bool operator== (const DocumentIdentifier &rhs) const
Equality operator.
void setIdentifier (const String &id)
set document identifier (e.g. an LSID)
const String & getIdentifier () const
retrieve document identifier (e.g. an LSID)
void swap (DocumentIdentifier &from)
exchange content with from
void setLoadedFilePath (const String &file_name)
set the file_name_ according to absolute path of the file loaded from preferably done whilst loading
const String & getLoadedFilePath () const
get the file_name_ which is the absolute path to the file loaded from
void setLoadedFileType (const String &file_name)
set the file_type according to the type of the file loaded from (see FileHandler::Type) preferably done whilst loading
const FileTypes::Type & getLoadedFileType () const
get the file_type (e.g. featureXML, consensusXML, mzData, mzXML, mzML, ...) of the file loaded from
Protected Attributes
Sample sample_
std::vector< SourceFile > source_files_
std::vector< ContactPerson > contacts_
Instrument instrument_
HPLC hplc_
DateTime datetime_
String comment_
std::vector< ProteinIdentification > protein_identifications_
String fraction_identifier_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from DocumentIdentifier
String id_
the ID (e.g. LSID)
String file_path_
the path to the loaded file
FileTypes::Type file_type_
the type of the loaded file
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Description of the experimental settings.
These settings are valid for the whole experiment. See SpectrumSettings for settings which are specific to an MSSpectrum. See ChromatogramSettings for settings which are specific to an MSChromatogram.
Constructor & Destructor Documentation
ExperimentalSettings() [1/3]
ExperimentalSettings () default
Constructor.
ExperimentalSettings() [2/3]
ExperimentalSettings (const ExperimentalSettings &) default
Copy constructor.
ExperimentalSettings() [3/3]
ExperimentalSettings (ExperimentalSettings &&) default
Move constructor.
~ExperimentalSettings()
~ExperimentalSettings () override
Destructor.
Member Function Documentation
getComment()
const String& getComment () const
returns the free-text comment
getContacts() [1/2]
std::vector<ContactPerson>& getContacts ()
returns a mutable reference to the list of contact persons
getContacts() [2/2]
const std::vector<ContactPerson>& getContacts () const
returns a const reference to the list of contact persons
getDateTime()
const DateTime& getDateTime () const
returns the date the experiment was performed
getFractionIdentifier()
const String& getFractionIdentifier () const
returns fraction identifier
getHPLC() [1/2]
HPLC& getHPLC ()
returns a mutable reference to the description of the HPLC run
getHPLC() [2/2]
const HPLC& getHPLC () const
returns a const reference to the description of the HPLC run
getInstrument() [1/2]
Instrument& getInstrument ()
returns a mutable reference to the MS instrument description
getInstrument() [2/2]
const Instrument& getInstrument () const
returns a const reference to the MS instrument description
getProteinIdentifications() [1/2]
std::vector<ProteinIdentification>& getProteinIdentifications ()
returns a mutable reference to the protein ProteinIdentification vector
getProteinIdentifications() [2/2]
const std::vector<ProteinIdentification>& getProteinIdentifications () const
returns a const reference to the protein ProteinIdentification vector
Referenced by IDFilter::filterHitsByScore(), IDFilter::keepBestPerPeptidePerRun(), IDFilter::keepHitsMatchingProteins(), and IDFilter::keepNBestHits().
getSample() [1/2]
Sample& getSample ()
returns a mutable reference to the sample description
getSample() [2/2]
const Sample& getSample () const
returns a const reference to the sample description
getSourceFiles() [1/2]
std::vector<SourceFile>& getSourceFiles ()
returns a mutable reference to the source data file
getSourceFiles() [2/2]
const std::vector<SourceFile>& getSourceFiles () const
returns a const reference to the source data file
operator!=()
bool operator!= (const ExperimentalSettings & rhs) const
Equality operator.
operator=() [1/2]
ExperimentalSettings& operator= (const ExperimentalSettings &) default
Assignment operator.
operator=() [2/2]
ExperimentalSettings& operator= (ExperimentalSettings &&) & default
Move assignment operator.
operator==()
bool operator== (const ExperimentalSettings & rhs) const
Equality operator.
setComment()
void setComment (const String & comment)
sets the free-text comment
setContacts()
void setContacts (const std::vector< ContactPerson > & contacts)
sets the list of contact persons
setDateTime()
void setDateTime (const DateTime & date)
sets the date the experiment was performed
setFractionIdentifier()
void setFractionIdentifier (const String & fraction_identifier)
sets the fraction identifier
setHPLC()
void setHPLC (const HPLC & hplc)
sets the description of the HPLC run
setInstrument()
void setInstrument (const Instrument & instrument)
sets the MS instrument description
setProteinIdentifications()
void setProteinIdentifications (const std::vector< ProteinIdentification > & protein_identifications)
sets the protein ProteinIdentification vector
setSample()
void setSample (const Sample & sample)
sets the sample description
setSourceFiles()
void setSourceFiles (const std::vector< SourceFile > & source_files)
sets the source data file
Member Data Documentation
comment_
String comment_ protected
contacts_
std::vector<ContactPerson> contacts_ protected
datetime_
DateTime datetime_ protected
fraction_identifier_
String fraction_identifier_ protected
hplc_
HPLC hplc_ protected
instrument_
Instrument instrument_ protected
protein_identifications_
std::vector<ProteinIdentification> protein_identifications_ protected
sample_
Sample sample_ protected
source_files_
std::vector<SourceFile> source_files_ protected