OpenMS: ScoredProcessingResult Struct Reference
ScoredProcessingResult Struct Reference
Base class for ID data with scores and processing steps (and meta info)
#include <OpenMS/METADATA/ID/ScoredProcessingResult.h>
Public Member Functions
AppliedProcessingSteps::nth_index< 1 >::type & getStepsAndScoresByStep ()
Return the applied processing steps (incl. scores) as a set ordered by processing step reference (option)
const AppliedProcessingSteps::nth_index< 1 >::type & getStepsAndScoresByStep () const
Return the applied processing steps (incl. scores) as a set ordered by processing step reference (option) - const variant.
void addProcessingStep (const AppliedProcessingStep &step)
void addProcessingStep (ProcessingStepRef step_ref, const std::map< ScoreTypeRef, double > &scores=std::map< ScoreTypeRef, double >())
Add a processing step (and associated scores, if any)
void addScore (ScoreTypeRef score_type, double score, const boost::optional< ProcessingStepRef > &processing_step_opt=boost::none)
Add a score (possibly connected to a processing step)
ScoredProcessingResult & operator+= (const ScoredProcessingResult &other)
Merge in data from another object.
std::pair< double, bool > getScore (ScoreTypeRef score_ref) const
std::pair< double, bool > getScore (ScoreTypeRef score_ref, boost::optional< ProcessingStepRef > processing_step_opt) const
std::tuple< double, boost::optional< ProcessingStepRef >, bool > getScoreAndStep (ScoreTypeRef score_ref) const
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Attributes
AppliedProcessingSteps steps_and_scores
Protected Member Functions
ScoredProcessingResult (const AppliedProcessingSteps &steps_and_scores=AppliedProcessingSteps())
ScoredProcessingResult (const ScoredProcessingResult &)=default
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Base class for ID data with scores and processing steps (and meta info)
Constructor & Destructor Documentation
ScoredProcessingResult() [1/2]
ScoredProcessingResult (const AppliedProcessingSteps & steps_and_scores = AppliedProcessingSteps()) inline explicit protected
ScoredProcessingResult() [2/2]
ScoredProcessingResult (const ScoredProcessingResult &) protected default
Member Function Documentation
addProcessingStep() [1/2]
void addProcessingStep (const AppliedProcessingStep & step) inline
Add an applied processing step.
If the step already exists, scores are merged (existing ones updated).
References seqan::find(), AppliedProcessingStep::processing_step_opt, AppliedProcessingStep::scores, and ScoredProcessingResult::steps_and_scores.
Referenced by ScoredProcessingResult::addProcessingStep(), ScoredProcessingResult::addScore(), and ScoredProcessingResult::operator+=().
addProcessingStep() [2/2]
void addProcessingStep (ProcessingStepRef step_ref, const std::map< ScoreTypeRef, double > & scores = std::map<ScoreTypeRef, double>()) inline
Add a processing step (and associated scores, if any)
References ScoredProcessingResult::addProcessingStep().
addScore()
void addScore (ScoreTypeRef score_type, double score, const boost::optional< ProcessingStepRef > & processing_step_opt = boost::none) inline
Add a score (possibly connected to a processing step)
References ScoredProcessingResult::addProcessingStep(), and AppliedProcessingStep::scores.
Referenced by NucleicAcidSearchEngine::postProcessHits_().
getScore() [1/2]
std::pair<double, bool> getScore (ScoreTypeRef score_ref) const inline
Look up a score by score type.
Returns
A pair: score (or NaN), success indicator
All processing steps are considered, in "most recent first" order.
References ScoredProcessingResult::getScoreAndStep().
getScore() [2/2]
std::pair<double, bool> getScore (ScoreTypeRef score_ref, boost::optional< ProcessingStepRef > processing_step_opt) const inline
Look up a score by score type and processing step.
Returns
A pair: score (or NaN), success indicator
References seqan::find(), and ScoredProcessingResult::steps_and_scores.
getScoreAndStep()
std::tuple<double, boost::optional<ProcessingStepRef>, bool> getScoreAndStep (ScoreTypeRef score_ref) const inline
Look up a score and associated processing step by score type.
Returns
A tuple: score (or NaN), processing step reference (option), success indicator
All processing steps are considered, in "most recent first" order.
References ScoredProcessingResult::steps_and_scores.
Referenced by ScoredProcessingResult::getScore().
getStepsAndScoresByStep() [1/2]
AppliedProcessingSteps::nth_index<1>::type& getStepsAndScoresByStep () inline
Return the applied processing steps (incl. scores) as a set ordered by processing step reference (option)
References ScoredProcessingResult::steps_and_scores.
getStepsAndScoresByStep() [2/2]
const AppliedProcessingSteps::nth_index<1>::type& getStepsAndScoresByStep () const inline
Return the applied processing steps (incl. scores) as a set ordered by processing step reference (option) - const variant.
References ScoredProcessingResult::steps_and_scores.
operator+=()
ScoredProcessingResult& operator+= (const ScoredProcessingResult & other) inline
Merge in data from another object.
References ScoredProcessingResult::addProcessingStep(), MetaInfoInterface::getKeys(), MetaInfoInterface::getMetaValue(), MetaInfoInterface::setMetaValue(), and ScoredProcessingResult::steps_and_scores.
Referenced by IdentifiedSequence< SeqType >::operator+=(), ParentMolecule::operator+=(), and MoleculeQueryMatch::operator+=().
Member Data Documentation
steps_and_scores
AppliedProcessingSteps steps_and_scores
Referenced by ScoredProcessingResult::addProcessingStep(), IdentificationDataConverter::exportParentMoleculeToMzTab_(), IdentificationDataConverter::exportQueryMatchToMzTab_(), ScoredProcessingResult::getScore(), ScoredProcessingResult::getScoreAndStep(), ScoredProcessingResult::getStepsAndScoresByStep(), ScoredProcessingResult::operator+=(), and QueryMatchGroup::operator==().