OpenMS: MetaInfoInterface Class Reference
MetaInfoInterface Class Reference
Metadata
Interface for classes that can store arbitrary meta information (Type-Name-Value tuples).
#include <OpenMS/METADATA/MetaInfoInterface.h>
Public Member Functions
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Member Functions
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Interface for classes that can store arbitrary meta information (Type-Name-Value tuples).
MetaInfoInterface is a base class for all classes that use one MetaInfo object as member. If you want to add meta information to a class, let it publicly inherit the MetaInfoInterface. Meta information is an array of Type-Name-Value tuples.
Constructor & Destructor Documentation
MetaInfoInterface() [1/3]
MetaInfoInterface ()
Constructor.
MetaInfoInterface() [2/3]
MetaInfoInterface (const MetaInfoInterface & rhs)
Copy constructor.
MetaInfoInterface() [3/3]
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface()
~MetaInfoInterface ()
Destructor.
Member Function Documentation
clearMetaInfo()
void clearMetaInfo ()
Removes all meta values.
createIfNotExists_()
void createIfNotExists_ () inline protected
Creates the MetaInfo object if it does not exist.
getKeys() [1/2]
void getKeys (std::vector< String > & keys) const
Fills the given vector with a list of all keys for which a value is set.
Referenced by ScoredProcessingResult::operator+=().
getKeys() [2/2]
void getKeys (std::vector< UInt > & keys) const
Fills the given vector with a list of all keys for which a value is set.
getMetaValue() [1/2]
const DataValue& getMetaValue (const String & name, const DataValue & default_value = DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
Referenced by IdentificationDataConverter::exportQueryMatchToMzTab_(), ConsensusMap::ColumnHeader::getLabelAsUInt(), XFDRAlgorithm::getMinIonsMatched_(), IDScoreGetterSetter::getTDLabel_(), DataFilters::metaPasses_(), PrecursorIonSelection::TotalScoreMore::operator()(), PrecursorIonSelection::SeqTotalScoreMore::operator()(), FeatureFinderIdentificationAlgorithm::FeatureCompare::operator()(), ScoredProcessingResult::operator+=(), MRMTransitionGroupPicker::pickTransitionGroup(), and IDScoreGetterSetter::setScoreAndMoveIfTarget_().
getMetaValue() [2/2]
const DataValue& getMetaValue (UInt index, const DataValue & default_value = DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
isMetaEmpty()
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
metaRegistry()
static MetaInfoRegistry& metaRegistry () static
Returns a reference to the MetaInfoRegistry.
metaValueExists() [1/2]
bool metaValueExists (const String & name) const
Returns whether an entry with the given name exists.
Referenced by IDScoreGetterSetter::checkTDAnnotation_(), IdentificationDataConverter::exportQueryMatchToMzTab_(), ConsensusMap::ColumnHeader::getLabelAsUInt(), MascotGenericFile::getNextSpectrum_(), and DataFilters::metaPasses_().
metaValueExists() [2/2]
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
operator!=()
bool operator!= (const MetaInfoInterface & rhs) const
Equality operator.
operator=() [1/2]
MetaInfoInterface& operator= (const MetaInfoInterface & rhs)
Assignment operator.
operator=() [2/2]
MetaInfoInterface& operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
operator==()
bool operator== (const MetaInfoInterface & rhs) const
Equality operator.
Referenced by RichPeak2D::operator==().
removeMetaValue() [1/2]
void removeMetaValue (const String & name)
Removes the DataValue corresponding to name if it exists.
Referenced by MascotGenericFile::getNextSpectrum_().
removeMetaValue() [2/2]
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
setMetaValue() [1/2]
void setMetaValue (const String & name, const DataValue & value)
Sets the DataValue corresponding to a name.
Referenced by IDFilter::annotateBestPerPeptideWithData(), MascotGenericFile::getNextSpectrum_(), SpecArrayFile::load(), MsInspectFile::load(), MascotInfile::load(), XMassFile::load(), TOPPOpenPepXLLF::main_(), TOPPOpenPepXL::main_(), ScoredProcessingResult::operator+=(), MRMTransitionGroupPicker::pickFragmentChromatograms(), MRMTransitionGroupPicker::pickPrecursorChromatograms(), NucleicAcidSearchEngine::postProcessHits_(), ChromatogramExtractor::prepareSpectra_(), ChromatogramExtractor::return_chromatogram(), PeptideIndexing::run(), XFDRAlgorithm::setInterProtein_(), XFDRAlgorithm::setIntraProtein_(), IDScoreGetterSetter::setScoreAndMoveIfTarget_(), and MRMTransitionGroup< SpectrumT, TransitionT >::subset().
setMetaValue() [2/2]
void setMetaValue (UInt index, const DataValue & value)
Sets the DataValue corresponding to an index.
Member Data Documentation
meta_
MetaInfo* meta_ protected
Pointer to the MetaInfo object (0 by default)