OpenMS: PeptideHit Class Reference
PeptideHit Class Reference
Metadata
Representation of a peptide hit.
#include <OpenMS/METADATA/PeptideHit.h>
Classes
struct PeakAnnotation
Contains annotations of a peak.
class PepXMLAnalysisResult
Analysis Result (containing search engine / prophet results)
class RankLess
Lesser predicate for scores of hits.
class ScoreLess
Lesser predicate for scores of hits.
class ScoreMore
Greater predicate for scores of hits.
class SequenceLessComparator
Lesser predicate for (modified) sequence of hits.
Public Member Functions
Constructors and Assignment
PeptideHit ()
Default constructor.
PeptideHit (double score, UInt rank, Int charge, const AASequence &sequence)
Values constructor that copies sequence.
PeptideHit (double score, UInt rank, Int charge, AASequence &&sequence)
Values constructor that moves sequence R-value.
PeptideHit (const PeptideHit &source)
Copy constructor.
PeptideHit (PeptideHit &&) noexcept
Move constructor.
virtual ~PeptideHit ()
Destructor.
PeptideHit & operator= (const PeptideHit &source)
Assignment operator.
PeptideHit & operator= (PeptideHit &&) noexcept
Move assignment operator.
bool operator== (const PeptideHit &rhs) const
Equality operator.
bool operator!= (const PeptideHit &rhs) const
Inequality operator.
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Accessors
AASequence sequence_
double score_
the score of the peptide hit
std::vector< PepXMLAnalysisResult > * analysis_results_
additional scores attached to the original, aggregated score
UInt rank_
the position(rank) where the hit appeared in the hit list
Int charge_
the charge of the peptide
std::vector< PeptideEvidence > peptide_evidences_
information on the potential peptides observed through this PSM.
std::vector< PeptideHit::PeakAnnotation > fragment_annotations_
annotations of fragments in the corresponding spectrum
const AASequence & getSequence () const
returns the peptide sequence without trailing or following spaces
void setSequence (const AASequence &sequence)
sets the peptide sequence
void setSequence (AASequence &&sequence)
sets the peptide sequence
Int getCharge () const
returns the charge of the peptide
void setCharge (Int charge)
sets the charge of the peptide
const std::vector< PeptideEvidence > & getPeptideEvidences () const
returns information on peptides (potentially) identified by this PSM
void setPeptideEvidences (const std::vector< PeptideEvidence > &peptide_evidences)
set information on peptides (potentially) identified by this PSM
void setPeptideEvidences (std::vector< PeptideEvidence > &&peptide_evidences)
void addPeptideEvidence (const PeptideEvidence &peptide_evidence)
adds information on a peptide that is (potentially) identified by this PSM
double getScore () const
returns the PSM score
void setScore (double score)
sets the PSM score
void setAnalysisResults (std::vector< PepXMLAnalysisResult > aresult)
set information on (search engine) sub scores associated with this PSM
void addAnalysisResults (PepXMLAnalysisResult aresult)
add information on (search engine) sub scores associated with this PSM
const std::vector< PepXMLAnalysisResult > & getAnalysisResults () const
returns information on (search engine) sub scores associated with this PSM
UInt getRank () const
returns the PSM rank
void setRank (UInt newrank)
sets the PSM rank
std::vector< PeptideHit::PeakAnnotation > getPeakAnnotations () const
returns the fragment annotations
void setPeakAnnotations (std::vector< PeptideHit::PeakAnnotation > frag_annotations)
sets the fragment annotations
std::set< String > extractProteinAccessionsSet () const
extracts the set of non-empty protein accessions from peptide evidences
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Representation of a peptide hit.
It contains the fields score, score_type, rank, and sequence.
Constructor & Destructor Documentation
PeptideHit() [1/5]
PeptideHit ()
Default constructor.
PeptideHit() [2/5]
PeptideHit (double score, UInt rank, Int charge, const AASequence & sequence)
Values constructor that copies sequence.
PeptideHit() [3/5]
PeptideHit (double score, UInt rank, Int charge, AASequence && sequence)
Values constructor that moves sequence R-value.
PeptideHit() [4/5]
PeptideHit (const PeptideHit & source)
Copy constructor.
PeptideHit() [5/5]
PeptideHit (PeptideHit &&) noexcept
Move constructor.
~PeptideHit()
virtual ~PeptideHit () virtual
Destructor.
Member Function Documentation
addAnalysisResults()
void addAnalysisResults (PepXMLAnalysisResult aresult)
add information on (search engine) sub scores associated with this PSM
addPeptideEvidence()
void addPeptideEvidence (const PeptideEvidence & peptide_evidence)
adds information on a peptide that is (potentially) identified by this PSM
extractProteinAccessionsSet()
std::set<String> extractProteinAccessionsSet () const
extracts the set of non-empty protein accessions from peptide evidences
Referenced by IDFilter::HasMatchingAccessionUnordered< HitType >::operator()(), and IDFilter::HasMatchingAccession< HitType >::operator()().
getAnalysisResults()
const std::vector<PepXMLAnalysisResult>& getAnalysisResults () const
returns information on (search engine) sub scores associated with this PSM
getCharge()
Int getCharge () const
returns the charge of the peptide
Referenced by IDFilter::annotateBestPerPeptideWithData(), IDScoreGetterSetter::getScores_(), IDBoostGraph::LabelVisitor::operator()(), and IDScoreGetterSetter::setScoreAndMoveIfTarget_().
getPeakAnnotations()
std::vector<PeptideHit::PeakAnnotation> getPeakAnnotations () const
returns the fragment annotations
getPeptideEvidences()
const std::vector<PeptideEvidence>& getPeptideEvidences () const
returns information on peptides (potentially) identified by this PSM
getRank()
UInt getRank () const
returns the PSM rank
getScore()
double getScore () const
returns the PSM score
Referenced by IDFilter::annotateBestPerPeptideWithData(), IDScoreGetterSetter::getScores_(), IDBoostGraph::GetPosteriorVisitor::operator()(), and IDScoreGetterSetter::setScoreAndMoveIfTarget_().
getSequence()
const AASequence& getSequence () const
returns the peptide sequence without trailing or following spaces
Referenced by IDFilter::annotateBestPerPeptideWithData(), IDBoostGraph::LabelVisitor::operator()(), IDBoostGraph::PrintAddressVisitor< CharT >::operator()(), IDFilter::PeptideDigestionFilter::operator()(), and IDConflictResolverAlgorithm::resolveBetweenFeatures_().
operator!=()
bool operator!= (const PeptideHit & rhs) const
Inequality operator.
operator=() [1/2]
PeptideHit& operator= (const PeptideHit & source)
Assignment operator.
operator=() [2/2]
PeptideHit& operator= (PeptideHit &&) noexcept
Move assignment operator.
operator==()
bool operator== (const PeptideHit & rhs) const
Equality operator.
setAnalysisResults()
void setAnalysisResults (std::vector< PepXMLAnalysisResult > aresult)
set information on (search engine) sub scores associated with this PSM
setCharge()
void setCharge (Int charge)
sets the charge of the peptide
setPeakAnnotations()
void setPeakAnnotations (std::vector< PeptideHit::PeakAnnotation > frag_annotations)
sets the fragment annotations
setPeptideEvidences() [1/2]
void setPeptideEvidences (const std::vector< PeptideEvidence > & peptide_evidences)
set information on peptides (potentially) identified by this PSM
setPeptideEvidences() [2/2]
void setPeptideEvidences (std::vector< PeptideEvidence > && peptide_evidences)
setRank()
void setRank (UInt newrank)
sets the PSM rank
setScore()
void setScore (double score)
sets the PSM score
Referenced by IDBoostGraph::SetPosteriorVisitor::operator()(), and IDScoreGetterSetter::setScoreAndMoveIfTarget_().
setSequence() [1/2]
void setSequence (AASequence && sequence)
sets the peptide sequence
setSequence() [2/2]
void setSequence (const AASequence & sequence)
sets the peptide sequence
Member Data Documentation
analysis_results_
std::vector<PepXMLAnalysisResult>* analysis_results_ protected
additional scores attached to the original, aggregated score
charge_
Int charge_ protected
the charge of the peptide
fragment_annotations_
std::vector<PeptideHit::PeakAnnotation> fragment_annotations_ protected
annotations of fragments in the corresponding spectrum
peptide_evidences_
std::vector<PeptideEvidence> peptide_evidences_ protected
information on the potential peptides observed through this PSM.
rank_
UInt rank_ protected
the position(rank) where the hit appeared in the hit list
score_
double score_ protected
the score of the peptide hit
sequence_
AASequence sequence_ protected