OpenMS: Precursor Class Reference
Precursor Class Reference
Metadata
Precursor meta information.
#include <OpenMS/METADATA/Precursor.h>
Public Types
enum ActivationMethod {
CID, PSD, PD, SID,
BIRD, ECD, IMD, SORI,
HCID, LCID, PHD, ETD,
PQD, SIZE_OF_ACTIVATIONMETHOD
}
Method of activation.
enum DriftTimeUnit { NONE, MILLISECOND, VSSC, SIZE_OF_DRIFTTIMEUNIT }
Drift time unit.
Public Types inherited from Peak1D
enum { DIMENSION = 1 }
typedef float IntensityType
Intensity type.
typedef DPosition< 1 > PositionType
Position type.
typedef double CoordinateType
Coordinate type.
Public Member Functions
Precursor ()
Constructor.
Precursor (const Precursor &)=default
Copy constructor.
Precursor (Precursor &&) noexcept
Move constructor.
~Precursor () override
Destructor.
Precursor & operator= (const Precursor &)=default
Assignment operator.
Precursor & operator= (Precursor &&) &=default
Move assignment operator.
bool operator== (const Precursor &rhs) const
Equality operator.
bool operator!= (const Precursor &rhs) const
Equality operator.
const std::set< ActivationMethod > & getActivationMethods () const
returns a const reference to the activation methods
std::set< ActivationMethod > & getActivationMethods ()
returns a mutable reference to the activation methods
void setActivationMethods (const std::set< ActivationMethod > &activation_methods)
sets the activation methods
double getActivationEnergy () const
returns the activation energy (in electronvolt)
void setActivationEnergy (double activation_energy)
sets the activation energy (in electronvolt)
double getIsolationWindowLowerOffset () const
Returns the lower offset from the target m/z.
void setIsolationWindowLowerOffset (double bound)
sets the lower offset from the target m/z
double getIsolationWindowUpperOffset () const
Returns the upper offset from the target m/z.
void setIsolationWindowUpperOffset (double bound)
sets the upper offset from the target m/z
double getDriftTime () const
Returns the ion mobility drift time in milliseconds (-1 means it is not set)
void setDriftTime (double drift_time)
sets the ion mobility drift time in milliseconds
DriftTimeUnit getDriftTimeUnit () const
Returns the ion mobility drift time unit.
void setDriftTimeUnit (DriftTimeUnit dt)
Sets the ion mobility drift time unit.
double getDriftTimeWindowLowerOffset () const
Returns the lower offset from the target ion mobility in milliseconds.
void setDriftTimeWindowLowerOffset (double drift_time)
sets the lower offset from the target ion mobility
double getDriftTimeWindowUpperOffset () const
Returns the upper offset from the target ion mobility in milliseconds.
void setDriftTimeWindowUpperOffset (double drift_time)
sets the upper offset from the target ion mobility
Int getCharge () const
Non-mutable access to the charge.
void setCharge (Int charge)
Mutable access to the charge.
std::vector< Int > & getPossibleChargeStates ()
Mutable access to possible charge states.
const std::vector< Int > & getPossibleChargeStates () const
Non-mutable access to possible charge states.
void setPossibleChargeStates (const std::vector< Int > &possible_charge_states)
Sets the possible charge states.
double getUnchargedMass () const
Returns the uncharged mass of the precursor, if charge is unknown, i.e. 0 best guess is its doubly charged.
Public Member Functions inherited from CVTermList
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Public Member Functions inherited from Peak1D
Peak1D & operator= (const Peak1D &rhs)
Assignment operator.
bool operator== (const Peak1D &rhs) const
Equality operator.
bool operator!= (const Peak1D &rhs) const
Equality operator.
Peak1D ()
Peak1D (PositionType a, IntensityType b)
construct with position and intensity
Peak1D (const Peak1D &p)
Copy constructor.
Peak1D (Peak1D &&) noexcept=default
~Peak1D ()
Destructor.
IntensityType getIntensity () const
void setIntensity (IntensityType intensity)
Mutable access to the data point intensity (height)
CoordinateType getMZ () const
Non-mutable access to m/z.
void setMZ (CoordinateType mz)
Mutable access to m/z.
CoordinateType getPos () const
Alias for getMZ()
void setPos (CoordinateType pos)
Alias for setMZ()
const PositionType & getPosition () const
Non-mutable access to the position.
PositionType & getPosition ()
Mutable access to the position.
void setPosition (PositionType const &position)
Mutable access to the position.
Static Public Attributes
static const std::string NamesOfActivationMethod [SIZE_OF_ACTIVATIONMETHOD]
Names of activation methods.
static const std::string NamesOfActivationMethodShort [SIZE_OF_ACTIVATIONMETHOD]
Protected Attributes
std::set< ActivationMethod > activation_methods_
double activation_energy_
double window_low_
double window_up_
double drift_time_
double drift_window_low_
double drift_window_up_
DriftTimeUnit drift_time_unit_
Int charge_
std::vector< Int > possible_charge_states_
Protected Attributes inherited from CVTermList
Map< String, std::vector< CVTerm > > cv_terms_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Protected Attributes inherited from Peak1D
PositionType position_
The data point position.
IntensityType intensity_
The data point intensity.
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Precursor meta information.
This class contains precursor information:
isolation window
activation
selected ion (m/z, intensity, charge, possible charge states)
ion mobility drift time
Member Enumeration Documentation
ActivationMethod
enum ActivationMethod
Method of activation.
Enumerator
CID
Collision-induced dissociation.
PSD
Post-source decay.
PD
Plasma desorption.
SID
Surface-induced dissociation.
BIRD
Blackbody infrared radiative dissociation.
ECD
Electron capture dissociation.
IMD
Infrared multiphoton dissociation.
SORI
Sustained off-resonance irradiation.
HCID
High-energy collision-induced dissociation.
LCID
Low-energy collision-induced dissociation.
PHD
Photodissociation.
ETD
Electron transfer dissociation.
PQD
Pulsed q dissociation.
SIZE_OF_ACTIVATIONMETHOD
DriftTimeUnit
enum DriftTimeUnit
Drift time unit.
Enumerator
NONE
No unit.
MILLISECOND
milliseconds
VSSC
volt-second per square centimeter
SIZE_OF_DRIFTTIMEUNIT
Constructor & Destructor Documentation
Precursor() [1/3]
Precursor ()
Constructor.
Precursor() [2/3]
Precursor (const Precursor &) default
Copy constructor.
Precursor() [3/3]
Precursor (Precursor &&) noexcept
Move constructor.
~Precursor()
~Precursor () override
Destructor.
Member Function Documentation
getActivationEnergy()
double getActivationEnergy () const
returns the activation energy (in electronvolt)
getActivationMethods() [1/2]
std::set<ActivationMethod>& getActivationMethods ()
returns a mutable reference to the activation methods
getActivationMethods() [2/2]
const std::set<ActivationMethod>& getActivationMethods () const
returns a const reference to the activation methods
getCharge()
Int getCharge () const
Non-mutable access to the charge.
Referenced by DTAFile::store().
getDriftTime()
double getDriftTime () const
Returns the ion mobility drift time in milliseconds (-1 means it is not set)
Note
It is possible for the spectrum to not have a Precursor but still have a drift time, please check getDriftTime of MSSpectrum first and only use this function if you need find-grained access to individual precursors.
getDriftTimeUnit()
DriftTimeUnit getDriftTimeUnit () const
Returns the ion mobility drift time unit.
getDriftTimeWindowLowerOffset()
double getDriftTimeWindowLowerOffset () const
Returns the lower offset from the target ion mobility in milliseconds.
Note
This is an offset relative to the target ion mobility. The start of the ion mobility isolation window should thus be computed as:
p.getDriftTime() + p.getDriftTimeWindowLowerOffset()
Returns
the lower offset from the target ion mobility
getDriftTimeWindowUpperOffset()
double getDriftTimeWindowUpperOffset () const
Returns the upper offset from the target ion mobility in milliseconds.
Note
This is an offset relative to the target ion mobility. The end of the ion mobility isolation window should thus be computed as:
p.getDriftTime() + p.getDriftTimeWindowUpperOffset()
Returns
the upper offset from the target ion mobility
getIsolationWindowLowerOffset()
double getIsolationWindowLowerOffset () const
Returns the lower offset from the target m/z.
Note
This is an offset relative to the target m/z. The start of the mass isolation window should thus be computed as:
p.getMZ() - p.getIsolationWindowLowerOffset()
Returns
the lower offset from the target m/z
getIsolationWindowUpperOffset()
double getIsolationWindowUpperOffset () const
Returns the upper offset from the target m/z.
Note
This is an offset relative to the target m/z. The end of the mass isolation window should thus be computed as:
p.getMZ() + p.getIsolationWindowUpperOffset()
Returns
the upper offset from the target m/z
getPossibleChargeStates() [1/2]
std::vector<Int>& getPossibleChargeStates ()
Mutable access to possible charge states.
getPossibleChargeStates() [2/2]
const std::vector<Int>& getPossibleChargeStates () const
Non-mutable access to possible charge states.
getUnchargedMass()
double getUnchargedMass () const inline
Returns the uncharged mass of the precursor, if charge is unknown, i.e. 0 best guess is its doubly charged.
References OpenMS::Constants::c, and OpenMS::Constants::PROTON_MASS_U.
operator!=()
bool operator!= (const Precursor & rhs) const
Equality operator.
operator=() [1/2]
Precursor& operator= (const Precursor &) default
Assignment operator.
operator=() [2/2]
Precursor& operator= (Precursor &&) & default
Move assignment operator.
operator==()
bool operator== (const Precursor & rhs) const
Equality operator.
setActivationEnergy()
void setActivationEnergy (double activation_energy)
sets the activation energy (in electronvolt)
setActivationMethods()
void setActivationMethods (const std::set< ActivationMethod > & activation_methods)
sets the activation methods
setCharge()
void setCharge (Int charge)
Mutable access to the charge.
Referenced by DTAFile::load(), NucleicAcidSearchEngine::preprocessSpectra_(), ChromatogramExtractor::return_chromatogram(), and TOPPViewBase::showSpectrumGenerationDialog().
setDriftTime()
void setDriftTime (double drift_time)
sets the ion mobility drift time in milliseconds
Referenced by ChromatogramExtractor::return_chromatogram().
setDriftTimeUnit()
void setDriftTimeUnit (DriftTimeUnit dt)
Sets the ion mobility drift time unit.
setDriftTimeWindowLowerOffset()
void setDriftTimeWindowLowerOffset (double drift_time)
sets the lower offset from the target ion mobility
Referenced by ChromatogramExtractor::return_chromatogram().
setDriftTimeWindowUpperOffset()
void setDriftTimeWindowUpperOffset (double drift_time)
sets the upper offset from the target ion mobility
Referenced by ChromatogramExtractor::return_chromatogram().
setIsolationWindowLowerOffset()
void setIsolationWindowLowerOffset (double bound)
sets the lower offset from the target m/z
Referenced by ChromatogramExtractor::prepareSpectra_(), and ChromatogramExtractor::return_chromatogram().
setIsolationWindowUpperOffset()
void setIsolationWindowUpperOffset (double bound)
sets the upper offset from the target m/z
Referenced by ChromatogramExtractor::prepareSpectra_(), and ChromatogramExtractor::return_chromatogram().
setPossibleChargeStates()
void setPossibleChargeStates (const std::vector< Int > & possible_charge_states)
Sets the possible charge states.
Member Data Documentation
activation_energy_
double activation_energy_ protected
activation_methods_
std::set<ActivationMethod> activation_methods_ protected
charge_
Int charge_ protected
drift_time_
double drift_time_ protected
drift_time_unit_
DriftTimeUnit drift_time_unit_ protected
drift_window_low_
double drift_window_low_ protected
drift_window_up_
double drift_window_up_ protected
NamesOfActivationMethod
const std::string NamesOfActivationMethod[SIZE_OF_ACTIVATIONMETHOD] static
Names of activation methods.
Referenced by IsobaricChannelExtractor::getActivationMethod_(), and HasActivationMethod< SpectrumType >::operator()().
NamesOfActivationMethodShort
const std::string NamesOfActivationMethodShort[SIZE_OF_ACTIVATIONMETHOD] static
possible_charge_states_
std::vector<Int> possible_charge_states_ protected
window_low_
double window_low_ protected
window_up_
double window_up_ protected