OpenMS: PeptideEvidence Class Reference
PeptideEvidence Class Reference
Metadata
Representation of a peptide evidence.
#include <OpenMS/METADATA/PeptideEvidence.h>
Public Member Functions
PeptideEvidence ()
Constructor.
PeptideEvidence (const String &accession, Int start, Int end, char aa_before, char aa_after)
Constructor.
PeptideEvidence (const PeptideEvidence &)=default
Copy constructor.
PeptideEvidence (PeptideEvidence &&) noexcept=default
Move constructor.
~PeptideEvidence ()
Destructor.
PeptideEvidence & operator= (const PeptideEvidence &)=default
Assignment operator.
PeptideEvidence & operator= (PeptideEvidence &&)=default
Move assignment operator.
bool operator== (const PeptideEvidence &rhs) const
Equality operator.
bool operator< (const PeptideEvidence &rhs) const
Less operator.
bool operator!= (const PeptideEvidence &rhs) const
not equal
bool hasValidLimits () const
start and end numbers in evidence represent actual numeric indices
const String & getProteinAccession () const
get the protein accession the peptide matches to. If not available the empty string is returned.
void setProteinAccession (const String &s)
set the protein accession the peptide matches to. If not available set to empty string.
void setStart (const Int a)
set the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available, set to UNKNOWN_POSITION. N-terminal positions must be marked with N_TERMINAL_AA
Int getStart () const
get the position in the protein (starting at 0 for the N-terminus). If not available UNKNOWN_POSITION constant is returned.
void setEnd (const Int a)
set the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available, set UNKNOWN_POSITION. C-terminal positions must be marked with C_TERMINAL_AA
Int getEnd () const
get the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available UNKNOWN_POSITION constant is returned.
void setAABefore (const char acid)
sets the amino acid single letter code before the sequence (preceding amino acid in the protein). If not available, set to UNKNOWN_AA. If N-terminal set to N_TERMINAL_AA
char getAABefore () const
returns the amino acid single letter code before the sequence (preceding amino acid in the protein). If not available, UNKNOWN_AA is returned. If N-terminal, N_TERMINAL_AA is returned.
void setAAAfter (const char acid)
sets the amino acid single letter code after the sequence (subsequent amino acid in the protein). If not available, set to UNKNOWN_AA. If C-terminal set to C_TERMINAL_AA
char getAAAfter () const
returns the amino acid single letter code after the sequence (subsequent amino acid in the protein). If not available, UNKNOWN_AA is returned. If C-terminal, C_TERMINAL_AA is returned.
Static Public Attributes
static const int UNKNOWN_POSITION
static const int N_TERMINAL_POSITION
static const char UNKNOWN_AA
static const char N_TERMINAL_AA
static const char C_TERMINAL_AA
Protected Attributes
String accession_
Int start_
Int end_
char aa_before_
char aa_after_
Detailed Description
Representation of a peptide evidence.
A peptide evidence object describes a single peptide to protein match.
Constructor & Destructor Documentation
PeptideEvidence() [1/4]
PeptideEvidence ()
Constructor.
PeptideEvidence() [2/4]
PeptideEvidence (const String & accession, Int start, Int end, char aa_before, char aa_after)
Constructor.
PeptideEvidence() [3/4]
PeptideEvidence (const PeptideEvidence &) default
Copy constructor.
PeptideEvidence() [4/4]
PeptideEvidence (PeptideEvidence &&) default noexcept
Move constructor.
~PeptideEvidence()
~PeptideEvidence () inline
Destructor.
Member Function Documentation
getAAAfter()
char getAAAfter () const
returns the amino acid single letter code after the sequence (subsequent amino acid in the protein). If not available, UNKNOWN_AA is returned. If C-terminal, C_TERMINAL_AA is returned.
getAABefore()
char getAABefore () const
returns the amino acid single letter code before the sequence (preceding amino acid in the protein). If not available, UNKNOWN_AA is returned. If N-terminal, N_TERMINAL_AA is returned.
getEnd()
Int getEnd () const
get the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available UNKNOWN_POSITION constant is returned.
Referenced by IDFilter::DigestionFilter::operator()().
getProteinAccession()
const String& getProteinAccession () const
get the protein accession the peptide matches to. If not available the empty string is returned.
Referenced by IDFilter::GetMatchingItems< OpenMS::PeptideEvidence, OpenMS::FASTAFile::FASTAEntry >::getHitKey(), PercolatorFeatureSetHelper::lq_PeptideEvidence::operator()(), IDFilter::HasMatchingAccessionUnordered< HitType >::operator()(), IDFilter::HasMatchingAccession< HitType >::operator()(), and IDFilter::DigestionFilter::operator()().
getStart()
Int getStart () const
get the position in the protein (starting at 0 for the N-terminus). If not available UNKNOWN_POSITION constant is returned.
Referenced by IDFilter::DigestionFilter::operator()().
hasValidLimits()
bool hasValidLimits () const
start and end numbers in evidence represent actual numeric indices
Referenced by IDFilter::DigestionFilter::operator()().
operator!=()
bool operator!= (const PeptideEvidence & rhs) const
not equal
operator<()
bool operator< (const PeptideEvidence & rhs) const
Less operator.
operator=() [1/2]
PeptideEvidence& operator= (const PeptideEvidence &) default
Assignment operator.
operator=() [2/2]
PeptideEvidence& operator= (PeptideEvidence &&) default
Move assignment operator.
operator==()
bool operator== (const PeptideEvidence & rhs) const
Equality operator.
setAAAfter()
void setAAAfter (const char acid)
sets the amino acid single letter code after the sequence (subsequent amino acid in the protein). If not available, set to UNKNOWN_AA. If C-terminal set to C_TERMINAL_AA
setAABefore()
void setAABefore (const char acid)
sets the amino acid single letter code before the sequence (preceding amino acid in the protein). If not available, set to UNKNOWN_AA. If N-terminal set to N_TERMINAL_AA
setEnd()
void setEnd (const Int a)
set the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available, set UNKNOWN_POSITION. C-terminal positions must be marked with C_TERMINAL_AA
setProteinAccession()
void setProteinAccession (const String & s)
set the protein accession the peptide matches to. If not available set to empty string.
setStart()
void setStart (const Int a)
set the position of the last AA of the peptide in protein coordinates (starting at 0 for the N-terminus). If not available, set to UNKNOWN_POSITION. N-terminal positions must be marked with N_TERMINAL_AA
Member Data Documentation
aa_after_
char aa_after_ protected
aa_before_
char aa_before_ protected
accession_
String accession_ protected
C_TERMINAL_AA
const char C_TERMINAL_AA static
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().
end_
Int end_ protected
N_TERMINAL_AA
const char N_TERMINAL_AA static
Referenced by PeptideIndexing::FoundProteinFunctor::addHit().
N_TERMINAL_POSITION
const int N_TERMINAL_POSITION static
start_
Int start_ protected
UNKNOWN_AA
const char UNKNOWN_AA static
UNKNOWN_POSITION
const int UNKNOWN_POSITION static