OpenMS: ProteinHit Class Reference
ProteinHit Class Reference
Metadata
Representation of a protein hit.
#include <OpenMS/METADATA/ProteinHit.h>
Classes
class ProteinHitAccessionHash
Hash of a ProteinHit based on its accession only!
class ProteinHitPtrAccessionHash
class ScoreLess
Lesser predicate for scores of hits.
class ScoreMore
Greater predicate for scores of hits.
Public Member Functions
Constructors and Destructor
ProteinHit ()
Default constructor.
ProteinHit (double score, UInt rank, String accession, String sequence)
Values constructor.
ProteinHit (const ProteinHit &)=default
Copy constructor.
ProteinHit (ProteinHit &&)=default
Move constructor.
ProteinHit & operator= (const ProteinHit &)=default
Assignment operator.
ProteinHit & operator= (ProteinHit &&)=default
Move assignment operator.
ProteinHit & operator= (const MetaInfoInterface &source)
Assignment for MetaInfo.
bool operator== (const ProteinHit &rhs) const
Equality operator.
bool operator!= (const ProteinHit &rhs) const
Inequality operator.
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Attributes
static const double COVERAGE_UNKNOWN
Accessors
double score_
the score of the protein hit
UInt rank_
the position(rank) where the hit appeared in the hit list
String accession_
the protein identifier
String sequence_
the amino acid sequence of the protein hit
double coverage_
coverage of the protein based upon the matched peptide sequences
std::set< std::pair< Size, ResidueModification > > modifications_
modified positions in a protein
double getScore () const
returns the score of the protein hit
UInt getRank () const
returns the rank of the protein hit
const String & getSequence () const
returns the protein sequence
const String & getAccession () const
returns the accession of the protein
String getDescription () const
returns the description of the protein
double getCoverage () const
returns the coverage (in percent) of the protein hit based upon matched peptides
void setScore (const double score)
sets the score of the protein hit
void setRank (UInt newrank)
sets the rank
void setSequence (const String &sequence)
sets the protein sequence
void setAccession (const String &accession)
sets the accession of the protein
void setDescription (const String &description)
sets the description of the protein
void setCoverage (const double coverage)
sets the coverage (in percent) of the protein hit based upon matched peptides
const std::set< std::pair< Size, ResidueModification > > & getModifications () const
returns the set of modified protein positions
void setModifications (std::set< std::pair< Size, ResidueModification > > &mods)
sets the set of modified protein positions
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Detailed Description
Representation of a protein hit.
It contains the fields score, score_type, rank, accession, sequence and coverage.
Constructor & Destructor Documentation
ProteinHit() [1/4]
ProteinHit ()
Default constructor.
ProteinHit() [2/4]
ProteinHit (double score, UInt rank, String accession, String sequence)
Values constructor.
ProteinHit() [3/4]
ProteinHit (const ProteinHit &) default
Copy constructor.
ProteinHit() [4/4]
ProteinHit (ProteinHit &&) default
Move constructor.
Member Function Documentation
getAccession()
const String& getAccession () const
returns the accession of the protein
Referenced by ConsensusMapMergerAlgorithm::accessionEqual_(), IDMergerAlgorithm::accessionEqual_(), ConsensusMapMergerAlgorithm::accessionHash_(), IDMergerAlgorithm::accessionHash_(), ProteinHit::ProteinHitAccessionHash::operator()(), ProteinHit::ProteinHitPtrAccessionHash::operator()(), IDBoostGraph::LabelVisitor::operator()(), PercolatorFeatureSetHelper::lq_ProteinHit::operator()(), IDBoostGraph::PrintAddressVisitor< CharT >::operator()(), IDFilter::HasMatchingAccessionUnordered< HitType >::operator()(), and IDFilter::HasMatchingAccession< HitType >::operator()().
getCoverage()
double getCoverage () const
returns the coverage (in percent) of the protein hit based upon matched peptides
getDescription()
String getDescription () const
returns the description of the protein
getModifications()
const std::set<std::pair<Size, ResidueModification> >& getModifications () const
returns the set of modified protein positions
getRank()
UInt getRank () const
returns the rank of the protein hit
getScore()
double getScore () const
returns the score of the protein hit
Referenced by IDScoreGetterSetter::getScores_(), and IDBoostGraph::GetPosteriorVisitor::operator()().
getSequence()
const String& getSequence () const
returns the protein sequence
operator!=()
bool operator!= (const ProteinHit & rhs) const
Inequality operator.
operator=() [1/3]
ProteinHit& operator= (const MetaInfoInterface & source)
Assignment for MetaInfo.
operator=() [2/3]
ProteinHit& operator= (const ProteinHit &) default
Assignment operator.
operator=() [3/3]
ProteinHit& operator= (ProteinHit &&) default
Move assignment operator.
operator==()
bool operator== (const ProteinHit & rhs) const
Equality operator.
setAccession()
void setAccession (const String & accession)
sets the accession of the protein
Referenced by PeptideIndexing::run().
setCoverage()
void setCoverage (const double coverage)
sets the coverage (in percent) of the protein hit based upon matched peptides
setDescription()
void setDescription (const String & description)
sets the description of the protein
Referenced by PeptideIndexing::run().
setModifications()
void setModifications (std::set< std::pair< Size, ResidueModification > > & mods)
sets the set of modified protein positions
setRank()
void setRank (UInt newrank)
sets the rank
setScore()
void setScore (const double score)
sets the score of the protein hit
Referenced by IDBoostGraph::SetPosteriorVisitor::operator()().
setSequence()
void setSequence (const String & sequence)
sets the protein sequence
Referenced by PeptideIndexing::run().
Member Data Documentation
accession_
String accession_ protected
the protein identifier
coverage_
double coverage_ protected
coverage of the protein based upon the matched peptide sequences
COVERAGE_UNKNOWN
const double COVERAGE_UNKNOWN static
modifications_
std::set<std::pair<Size, ResidueModification> > modifications_ protected
modified positions in a protein
rank_
UInt rank_ protected
the position(rank) where the hit appeared in the hit list
score_
double score_ protected
the score of the protein hit
sequence_
String sequence_ protected
the amino acid sequence of the protein hit