OpenMS: Product Class Reference
Product Class Reference
Metadata
Product meta information.
#include <OpenMS/METADATA/Product.h>
Public Member Functions
Product ()=default
Constructor.
Product (const Product &)=default
Copy constructor.
Product (Product &&)=default
Move constructor.
~Product () override=default
Destructor.
Product & operator= (const Product &)=default
Assignment operator.
Product & operator= (Product &&) &=default
Move assignment operator.
bool operator== (const Product &rhs) const
Equality operator.
bool operator!= (const Product &rhs) const
Equality operator.
double getMZ () const
returns the target m/z
void setMZ (double mz)
sets the target m/z
double getIsolationWindowLowerOffset () const
returns the lower offset from the target m/z
void setIsolationWindowLowerOffset (double bound)
sets the lower offset from the target m/z
double getIsolationWindowUpperOffset () const
returns the upper offset from the target m/z
void setIsolationWindowUpperOffset (double bound)
sets the upper offset from the target m/z
Public Member Functions inherited from CVTermList
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Protected Attributes
double mz_ = 0.0
double window_low_ = 0.0
double window_up_ = 0.0
Protected Attributes inherited from CVTermList
Map< String, std::vector< CVTerm > > cv_terms_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Product meta information.
This class describes the product isolation window for special scan types, such as MRM.
Constructor & Destructor Documentation
Product() [1/3]
Product () default
Constructor.
Product() [2/3]
Product (const Product &) default
Copy constructor.
Product() [3/3]
Product (Product &&) default
Move constructor.
~Product()
~Product () override default
Destructor.
Member Function Documentation
getIsolationWindowLowerOffset()
double getIsolationWindowLowerOffset () const
returns the lower offset from the target m/z
getIsolationWindowUpperOffset()
double getIsolationWindowUpperOffset () const
returns the upper offset from the target m/z
getMZ()
double getMZ () const
returns the target m/z
operator!=()
bool operator!= (const Product & rhs) const
Equality operator.
operator=() [1/2]
Product& operator= (const Product &) default
Assignment operator.
operator=() [2/2]
Product& operator= (Product &&) & default
Move assignment operator.
operator==()
bool operator== (const Product & rhs) const
Equality operator.
setIsolationWindowLowerOffset()
void setIsolationWindowLowerOffset (double bound)
sets the lower offset from the target m/z
setIsolationWindowUpperOffset()
void setIsolationWindowUpperOffset (double bound)
sets the upper offset from the target m/z
setMZ()
void setMZ (double mz)
sets the target m/z
Referenced by ChromatogramTools::convertSpectraToChromatograms(), ChromatogramExtractor::prepareSpectra_(), and ChromatogramExtractor::return_chromatogram().
Member Data Documentation
mz_
double mz_ = 0.0 protected
window_low_
double window_low_ = 0.0 protected
window_up_
double window_up_ = 0.0 protected