OpenMS: Software Class Reference
Software Class Reference
Metadata
Description of the software used for processing.
#include <OpenMS/METADATA/Software.h>
Public Member Functions
Software (const String &name="", const String &version="")
Constructor.
Software (const Software &)=default
Copy constructor.
Software (Software &&)=default
Move constructor.
~Software () override
Destructor.
Software & operator= (const Software &)=default
Assignment operator.
Software & operator= (Software &&) &=default
Move assignment operator.
bool operator== (const Software &rhs) const
Equality operator.
bool operator!= (const Software &rhs) const
Inequality operator.
bool operator< (const Software &rhs) const
Less-than operator (for sorting)
const String & getName () const
Returns the name of the software.
void setName (const String &name)
Sets the name of the software.
const String & getVersion () const
Returns the software version.
void setVersion (const String &version)
Sets the software version.
Public Member Functions inherited from CVTermList
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Protected Attributes
String name_
String version_
Protected Attributes inherited from CVTermList
Map< String, std::vector< CVTerm > > cv_terms_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Description of the software used for processing.
Constructor & Destructor Documentation
Software() [1/3]
Software (const String & name = "", const String & version = "") explicit
Constructor.
Software() [2/3]
Software (const Software &) default
Copy constructor.
Software() [3/3]
Software (Software &&) default
Move constructor.
~Software()
~Software () override
Destructor.
Member Function Documentation
getName()
const String& getName () const
Returns the name of the software.
getVersion()
const String& getVersion () const
Returns the software version.
operator!=()
bool operator!= (const Software & rhs) const
Inequality operator.
operator<()
bool operator< (const Software & rhs) const
Less-than operator (for sorting)
operator=() [1/2]
Software& operator= (const Software &) default
Assignment operator.
operator=() [2/2]
Software& operator= (Software &&) & default
Move assignment operator.
operator==()
bool operator== (const Software & rhs) const
Equality operator.
setName()
void setName (const String & name)
Sets the name of the software.
Referenced by XMassFile::load().
setVersion()
void setVersion (const String & version)
Sets the software version.
Referenced by XMassFile::load(), and NucleicAcidSearchEngine::registerIDMetaData_().
Member Data Documentation
name_
String name_ protected
version_
String version_ protected