OpenMS: SourceFile Class Reference
SourceFile Class Reference
Metadata
Description of a file location, used to store the origin of (meta) data.
#include <OpenMS/METADATA/SourceFile.h>
Public Types
enum ChecksumType { UNKNOWN_CHECKSUM, SHA1, MD5, SIZE_OF_CHECKSUMTYPE }
Type of the checksum.
Public Member Functions
SourceFile ()
Constructor.
SourceFile (const SourceFile &)=default
Copy constructor.
SourceFile (SourceFile &&)=default
Move constructor.
~SourceFile () override
Destructor.
SourceFile & operator= (const SourceFile &)=default
Assignment operator.
SourceFile & operator= (SourceFile &&) &=default
Move assignment operator.
bool operator== (const SourceFile &rhs) const
Equality operator.
bool operator!= (const SourceFile &rhs) const
Equality operator.
const String & getNameOfFile () const
returns the file name
void setNameOfFile (const String &name_of_file)
sets the file name
const String & getPathToFile () const
returns the file path
void setPathToFile (const String &path_path_to_file)
sets the file path
float getFileSize () const
returns the file size in MB
void setFileSize (float file_size)
sets the file size in MB
const String & getFileType () const
returns the file type
void setFileType (const String &file_type)
sets the file type
const String & getChecksum () const
returns the file's checksum
void setChecksum (const String &checksum, ChecksumType type)
sets the file's checksum
ChecksumType getChecksumType () const
returns the checksum type
const String & getNativeIDType () const
Returns the native ID type of the spectra.
void setNativeIDType (const String &type)
Sets the native ID type of the spectra.
const String & getNativeIDTypeAccession () const
Returns the nativeID of the spectra.
void setNativeIDTypeAccession (const String &accesssion)
Sets the native ID of the spectra.
Public Member Functions inherited from CVTermList
CVTermList ()=default
Defaults constructor.
CVTermList (const CVTermList &)=default
Copy constructor.
CVTermList (CVTermList &&) noexcept
Move constructor.
virtual ~CVTermList ()
Destructor.
CVTermList & operator= (const CVTermList &rhs) &=default
Assignment operator.
CVTermList & operator= (CVTermList &&) &=default
Move assignment operator.
void setCVTerms (const std::vector< CVTerm > &terms)
sets the CV terms
void replaceCVTerm (const CVTerm &cv_term)
replaces the specified CV term
void replaceCVTerms (const std::vector< CVTerm > &cv_terms, const String &accession)
replaces the specified CV terms using the given accession number
void replaceCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
replaces all cv terms with a map (can be obtained via getCVTerms)
void consumeCVTerms (const Map< String, std::vector< CVTerm > > &cv_term_map)
merges the given map into the member map, no duplicate checking
const Map< String, std::vector< CVTerm > > & getCVTerms () const
returns the accession string of the term
void addCVTerm (const CVTerm &term)
adds a CV term
bool operator== (const CVTermList &cv_term_list) const
equality operator
bool operator!= (const CVTermList &cv_term_list) const
inequality operator
bool hasCVTerm (const String &accession) const
checks whether the term has a value
bool empty () const
return true if no terms are available
Public Member Functions inherited from MetaInfoInterface
MetaInfoInterface ()
Constructor.
MetaInfoInterface (const MetaInfoInterface &rhs)
Copy constructor.
MetaInfoInterface (MetaInfoInterface &&) noexcept
Move constructor.
~MetaInfoInterface ()
Destructor.
MetaInfoInterface & operator= (const MetaInfoInterface &rhs)
Assignment operator.
MetaInfoInterface & operator= (MetaInfoInterface &&) noexcept
Move assignment operator.
bool operator== (const MetaInfoInterface &rhs) const
Equality operator.
bool operator!= (const MetaInfoInterface &rhs) const
Equality operator.
const DataValue & getMetaValue (const String &name, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to a string, or a default value (default: DataValue::EMPTY) if not found.
const DataValue & getMetaValue (UInt index, const DataValue &default_value=DataValue::EMPTY) const
Returns the value corresponding to an index, or a default value (default: DataValue::EMPTY) if not found.
bool metaValueExists (const String &name) const
Returns whether an entry with the given name exists.
bool metaValueExists (UInt index) const
Returns whether an entry with the given index exists.
void setMetaValue (const String &name, const DataValue &value)
Sets the DataValue corresponding to a name.
void setMetaValue (UInt index, const DataValue &value)
Sets the DataValue corresponding to an index.
void removeMetaValue (const String &name)
Removes the DataValue corresponding to name if it exists.
void removeMetaValue (UInt index)
Removes the DataValue corresponding to index if it exists.
void getKeys (std::vector< String > &keys) const
Fills the given vector with a list of all keys for which a value is set.
void getKeys (std::vector< UInt > &keys) const
Fills the given vector with a list of all keys for which a value is set.
bool isMetaEmpty () const
Returns if the MetaInfo is empty.
void clearMetaInfo ()
Removes all meta values.
Static Public Attributes
static const std::string NamesOfChecksumType [SIZE_OF_CHECKSUMTYPE]
Names of checksum types.
Protected Attributes
String name_of_file_
String path_to_file_
double file_size_
String file_type_
String checksum_
ChecksumType checksum_type_ = SourceFile::ChecksumType::UNKNOWN_CHECKSUM
String native_id_type_
String native_id_type_accession_
Protected Attributes inherited from CVTermList
Map< String, std::vector< CVTerm > > cv_terms_
Protected Attributes inherited from MetaInfoInterface
MetaInfo * meta_
Pointer to the MetaInfo object (0 by default)
Additional Inherited Members
Static Public Member Functions inherited from MetaInfoInterface
static MetaInfoRegistry & metaRegistry ()
Returns a reference to the MetaInfoRegistry.
Protected Member Functions inherited from MetaInfoInterface
void createIfNotExists_ ()
Creates the MetaInfo object if it does not exist.
Detailed Description
Description of a file location, used to store the origin of (meta) data.
Member Enumeration Documentation
ChecksumType
enum ChecksumType
Type of the checksum.
Enumerator
UNKNOWN_CHECKSUM
Unknown checksum type.
SHA1
Secure Hash Algorithm-1.
MD5
Message-Digest algorithm 5.
SIZE_OF_CHECKSUMTYPE
Constructor & Destructor Documentation
SourceFile() [1/3]
SourceFile ()
Constructor.
SourceFile() [2/3]
SourceFile (const SourceFile &) default
Copy constructor.
SourceFile() [3/3]
SourceFile (SourceFile &&) default
Move constructor.
~SourceFile()
~SourceFile () override
Destructor.
Member Function Documentation
getChecksum()
const String& getChecksum () const
returns the file's checksum
getChecksumType()
ChecksumType getChecksumType () const
returns the checksum type
getFileSize()
float getFileSize () const
returns the file size in MB
getFileType()
const String& getFileType () const
returns the file type
getNameOfFile()
const String& getNameOfFile () const
returns the file name
getNativeIDType()
const String& getNativeIDType () const
Returns the native ID type of the spectra.
getNativeIDTypeAccession()
const String& getNativeIDTypeAccession () const
Returns the nativeID of the spectra.
getPathToFile()
const String& getPathToFile () const
returns the file path
operator!=()
bool operator!= (const SourceFile & rhs) const
Equality operator.
operator=() [1/2]
SourceFile& operator= (const SourceFile &) default
Assignment operator.
operator=() [2/2]
SourceFile& operator= (SourceFile &&) & default
Move assignment operator.
operator==()
bool operator== (const SourceFile & rhs) const
Equality operator.
setChecksum()
void setChecksum (const String & checksum, ChecksumType type)
sets the file's checksum
setFileSize()
void setFileSize (float file_size)
sets the file size in MB
Referenced by XMassFile::load().
setFileType()
void setFileType (const String & file_type)
sets the file type
Referenced by XMassFile::load().
setNameOfFile()
void setNameOfFile (const String & name_of_file)
sets the file name
Referenced by XMassFile::load().
setNativeIDType()
void setNativeIDType (const String & type)
Sets the native ID type of the spectra.
setNativeIDTypeAccession()
void setNativeIDTypeAccession (const String & accesssion)
Sets the native ID of the spectra.
setPathToFile()
void setPathToFile (const String & path_path_to_file)
sets the file path
Referenced by XMassFile::load().
Member Data Documentation
checksum_
String checksum_ protected
checksum_type_
ChecksumType checksum_type_ = SourceFile::ChecksumType::UNKNOWN_CHECKSUM protected
file_size_
double file_size_ protected
file_type_
String file_type_ protected
name_of_file_
String name_of_file_ protected
NamesOfChecksumType
const std::string NamesOfChecksumType[SIZE_OF_CHECKSUMTYPE] static
Names of checksum types.
native_id_type_
String native_id_type_ protected
native_id_type_accession_
String native_id_type_accession_ protected
path_to_file_
String path_to_file_ protected