OpenMS: BaseLabeler Class Reference
BaseLabeler Class Reference abstract
Abstract base class for all kinds of labeling techniques.
#include <OpenMS/SIMULATION/LABELING/BaseLabeler.h>
Public Member Functions
BaseLabeler ()
constructor
~BaseLabeler () override
destructor
virtual Param getDefaultParameters () const
Returns the default parameters. Re-implement.
virtual void setRnd (SimTypes::MutableSimRandomNumberGeneratorPtr rng)
Set the random number generator.
virtual void preCheck (Param &param) const =0
Checks the (simulation) params passed if they are consistent with the labeling technique.
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Static Public Member Functions
static void registerChildren ()
register all derived classes here (implemented in file BaseLabeler_impl.h)
Labeling Hooks
ConsensusMap consensus_
SimTypes::MutableSimRandomNumberGeneratorPtr rng_
String channel_description_
virtual void setUpHook (SimTypes::FeatureMapSimVector &)=0
Hook to prepare the simulation process.
virtual void postDigestHook (SimTypes::FeatureMapSimVector &)=0
Labeling between digestion and rt simulation.
virtual void postRTHook (SimTypes::FeatureMapSimVector &)=0
Labeling after rt simulation.
virtual void postDetectabilityHook (SimTypes::FeatureMapSimVector &)=0
Labeling after detectability simulation.
virtual void postIonizationHook (SimTypes::FeatureMapSimVector &)=0
Labeling after ionization.
virtual void postRawMSHook (SimTypes::FeatureMapSimVector &)=0
Labeling after raw signal generation.
virtual void postRawTandemMSHook (SimTypes::FeatureMapSimVector &, SimTypes::MSSimExperiment &)=0
Labeling after Tandem MS (e.g. iTRAQ)
ConsensusMap & getConsensus ()
const String & getDescription () const
Get short description of the labeler (e.g., channels used)
String getChannelIntensityName (const Size channel_index) const
to ensure standardized meta value names across labelers for channel intensity
SimTypes::FeatureMapSim mergeProteinIdentificationsMaps_ (const SimTypes::FeatureMapSimVector &maps)
Creates an empty FeatureMap with the merged ProteinIdentifications from all FeatureMaps contained in maps.
void mergeProteinAccessions_ (Feature &target, const Feature &source) const
join all protein references of two features
void recomputeConsensus_ (const SimTypes::FeatureMapSim &simulated_features)
Based on the stored consensus recompute the associations for the passed features, assuming that the features where derived from the features stored in the consensus.
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
Abstract base class for all kinds of labeling techniques.
Constructor & Destructor Documentation
BaseLabeler()
BaseLabeler ()
constructor
~BaseLabeler()
~BaseLabeler () override
destructor
Member Function Documentation
getChannelIntensityName()
String getChannelIntensityName (const Size channel_index) const
to ensure standardized meta value names across labelers for channel intensity
Use this function to get the name of the meta value which holds intensity for channel channel_index
getConsensus()
ConsensusMap& getConsensus ()
getDefaultParameters()
virtual Param getDefaultParameters () const virtual
Returns the default parameters. Re-implement.
Re-implement if you derive a class and have to incorporate sub-algorithm default parameters.
getDescription()
const String& getDescription () const
Get short description of the labeler (e.g., channels used)
Used to add a short description to the labeling section within the INI file.
mergeProteinAccessions_()
void mergeProteinAccessions_ (Feature & target, const Feature & source) const protected
join all protein references of two features
When merging peptides from different channels, the protein accessions should remain intact. Usually joining features is based on peptide sequence, so all protein hits should be valid.
Parameters
target
source
mergeProteinIdentificationsMaps_()
SimTypes::FeatureMapSim mergeProteinIdentificationsMaps_ (const SimTypes::FeatureMapSimVector & maps) protected
Creates an empty FeatureMap with the merged ProteinIdentifications from all FeatureMaps contained in maps.
Parameters
maps Vector of FeatureMaps containing the features that will be merged
Returns
A FeatureMap containing all ProteinIdentifications of the input maps
postDetectabilityHook()
virtual void postDetectabilityHook (SimTypes::FeatureMapSimVector &) pure virtual
Labeling after detectability simulation.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
postDigestHook()
virtual void postDigestHook (SimTypes::FeatureMapSimVector &) pure virtual
Labeling between digestion and rt simulation.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
postIonizationHook()
virtual void postIonizationHook (SimTypes::FeatureMapSimVector &) pure virtual
Labeling after ionization.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
postRawMSHook()
virtual void postRawMSHook (SimTypes::FeatureMapSimVector &) pure virtual
Labeling after raw signal generation.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
postRawTandemMSHook()
virtual void postRawTandemMSHook (SimTypes::FeatureMapSimVector & , SimTypes::MSSimExperiment &) pure virtual
Labeling after Tandem MS (e.g. iTRAQ)
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
postRTHook()
virtual void postRTHook (SimTypes::FeatureMapSimVector &) pure virtual
Labeling after rt simulation.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
preCheck()
virtual void preCheck (Param & param) const pure virtual
Checks the (simulation) params passed if they are consistent with the labeling technique.
Parameters
param Param object containing the simulation parameters
Exceptions
Exception::InvalidParameter if the given parameters are not consistent with the labeling technique
Implemented in ITRAQLabeler, ICPLLabeler, O18Labeler, LabelFreeLabeler, and SILACLabeler.
recomputeConsensus_()
void recomputeConsensus_ (const SimTypes::FeatureMapSim & simulated_features) protected
Based on the stored consensus recompute the associations for the passed features, assuming that the features where derived from the features stored in the consensus.
Parameters
simulated_features FeatureMap containing features derived from the ones, stored in the consensus
registerChildren()
void registerChildren () static
register all derived classes here (implemented in file BaseLabeler_impl.h)
References LabelFreeLabeler::create(), O18Labeler::create(), ICPLLabeler::create(), SILACLabeler::create(), ITRAQLabeler::create(), LabelFreeLabeler::getProductName(), ICPLLabeler::getProductName(), O18Labeler::getProductName(), SILACLabeler::getProductName(), ITRAQLabeler::getProductName(), and Factory< FactoryProduct >::registerProduct().
setRnd()
virtual void setRnd (SimTypes::MutableSimRandomNumberGeneratorPtr rng) virtual
Set the random number generator.
Internally a pointer to the RNG is stored.
setUpHook()
virtual void setUpHook (SimTypes::FeatureMapSimVector &) pure virtual
Hook to prepare the simulation process.
Implemented in ITRAQLabeler, SILACLabeler, ICPLLabeler, O18Labeler, and LabelFreeLabeler.
Member Data Documentation
channel_description_
String channel_description_ protected
consensus_
ConsensusMap consensus_ protected
rng_
SimTypes::MutableSimRandomNumberGeneratorPtr rng_ protected