OpenMS: EmgScoring Class Reference
EmgScoring Class Reference
Scoring of an elution peak using an exponentially modified gaussian distribution model.
#include <OpenMS/TRANSFORMATIONS/FEATUREFINDER/EmgScoring.h>
Public Member Functions
EmgScoring ()
~EmgScoring ()
void setFitterParam (Param param)
Param getDefaults ()
template<typename SpectrumType , class TransitionT >
double calcElutionFitScore (MRMFeature &mrmfeature, MRMTransitionGroup< SpectrumType, TransitionT > &transition_group)
calculate the elution profile fit score
double elutionModelFit (ConvexHull2D::PointArrayType current_section, bool smooth_data)
Protected Member Functions
template<class LocalPeakType >
double fitRT_ (std::vector< LocalPeakType > &rt_input_data, InterpolationModel *&model)
template<class LocalPeakType >
void prepareFit_ (const ConvexHull2D::PointArrayType &current_section, std::vector< LocalPeakType > &data_to_fit, bool smooth_data)
Protected Attributes
EmgFitter1D fitter_emg1D_
Detailed Description
Scoring of an elution peak using an exponentially modified gaussian distribution model.
This class uses the original ideas from FeatureFinderAlgorithmMRM to construct an interface that allows scoring of chromatographic peaks.
Constructor & Destructor Documentation
EmgScoring()
EmgScoring () inline
~EmgScoring()
~EmgScoring () inline
Member Function Documentation
calcElutionFitScore()
double calcElutionFitScore (MRMFeature & mrmfeature, MRMTransitionGroup< SpectrumType, TransitionT > & transition_group) inline
calculate the elution profile fit score
References EmgScoring::elutionModelFit(), MRMTransitionGroup< ChromatogramType, TransitionType >::getChromatograms(), Feature::getConvexHulls(), MRMFeature::getFeature(), OpenMS::Constants::k, OPENMS_PRECONDITION, and MRMTransitionGroup< ChromatogramType, TransitionType >::size().
elutionModelFit()
double elutionModelFit (ConvexHull2D::PointArrayType current_section, bool smooth_data) inline
References EmgScoring::fitRT_(), and EmgScoring::prepareFit_().
Referenced by EmgScoring::calcElutionFitScore().
fitRT_()
double fitRT_ (std::vector< LocalPeakType > & rt_input_data, InterpolationModel *& model) inline protected
References EmgFitter1D::fit1d(), and EmgScoring::fitter_emg1D_.
Referenced by EmgScoring::elutionModelFit().
getDefaults()
Param getDefaults () inline
References EmgScoring::fitter_emg1D_, and DefaultParamHandler::getDefaults().
prepareFit_()
void prepareFit_ (const ConvexHull2D::PointArrayType & current_section, std::vector< LocalPeakType > & data_to_fit, bool smooth_data) inline protected
References GaussFilter::filter(), DefaultParamHandler::getParameters(), Peak1D::setIntensity(), Peak1D::setMZ(), and DefaultParamHandler::setParameters().
Referenced by EmgScoring::elutionModelFit().
setFitterParam()
void setFitterParam (Param param) inline
References EmgScoring::fitter_emg1D_, and DefaultParamHandler::setParameters().
Member Data Documentation
fitter_emg1D_
EmgFitter1D fitter_emg1D_ protected
Referenced by EmgScoring::fitRT_(), EmgScoring::getDefaults(), and EmgScoring::setFitterParam().