OpenMS: InterpolationModel Class Reference
InterpolationModel Class Reference
Analysis » FeatureFinder
Abstract class for 1D-models that are approximated using linear interpolation.
#include <OpenMS/TRANSFORMATIONS/FEATUREFINDER/InterpolationModel.h>
Public Types
typedef double IntensityType
typedef DPosition< 1 > PositionType
typedef double CoordinateType
typedef Math::LinearInterpolation< double > LinearInterpolation
Public Types inherited from BaseModel< 1 >
typedef double IntensityType
typedef double CoordinateType
typedef DPosition< D > PositionType
typedef DPeak< D >::Type PeakType
typedef std::vector< PeakType > SamplesType
Public Member Functions
InterpolationModel ()
Default constructor.
InterpolationModel (const InterpolationModel &source)
copy constructor
~InterpolationModel () override
destructor
virtual InterpolationModel & operator= (const InterpolationModel &source)
assignment operator
IntensityType getIntensity (const PositionType &pos) const override
access model predicted intensity at position pos
IntensityType getIntensity (CoordinateType coord) const
access model predicted intensity at position pos
const LinearInterpolation & getInterpolation () const
Returns the interpolation class.
CoordinateType getScalingFactor () const
get the scaling for the model
virtual void setOffset (CoordinateType offset)
set the offset of the model
void getSamples (SamplesType &cont) const override
get reasonable set of samples from the model (i.e. for printing)
virtual CoordinateType getCenter () const
"center" of the model, particular definition (depends on the derived model)
virtual void setSamples ()
set sample/supporting points of interpolation wrt params.
void setInterpolationStep (CoordinateType interpolation_step)
Set the interpolation step for the linear interpolation of the model.
void setScalingFactor (CoordinateType scaling)
Public Member Functions inherited from BaseModel< 1 >
BaseModel ()
Default constructor.
BaseModel (const BaseModel &source)
copy constructor
~BaseModel () override
Destructor.
virtual BaseModel & operator= (const BaseModel &source)
assignment operator
void registerChildren ()
void registerChildren ()
virtual IntensityType getIntensity (const PositionType &pos) const=0
access model predicted intensity at position pos
virtual bool isContained (const PositionType &pos) const
check if position pos is part of the model regarding the models cut-off.
void fillIntensity (PeakType &peak) const
Convenience function to set the intensity of a peak to the predicted intensity at its current position, calling virtual void getIntensity().
void fillIntensities (PeakIterator begin, PeakIterator end) const
Convenience function that applies fillIntensity() to an iterator range.
virtual IntensityType getCutOff () const
get cutoff value
virtual void setCutOff (IntensityType cut_off)
set cutoff value
virtual void getSamples (std::ostream &os)
fill stream with reasonable set of samples from the model (i.e. for printing)
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Protected Member Functions
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
Protected Member Functions inherited from BaseModel< 1 >
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
Protected Member Functions inherited from DefaultParamHandler
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes
LinearInterpolation interpolation_
CoordinateType interpolation_step_
CoordinateType scaling_
Protected Attributes inherited from BaseModel< 1 >
IntensityType cut_off_
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Additional Inherited Members
Static Public Member Functions inherited from BaseModel< 1 >
static void registerChildren ()
register all derived classes here (implemented in file BaseModel_impl.h)
Detailed Description
Abstract class for 1D-models that are approximated using linear interpolation.
Model wrapping LinearInterpolation for speed-up in calculation of predicted intensities Derived classes have to implement setSamples()
Parameters of this class are:
Name Type Default Restrictions Description
cutoff float 0.0 Low intensity cutoff of the model. Peaks below this intensity are not considered part of the model.
interpolation_step float 0.1 Sampling rate for the interpolation of the model function
intensity_scaling float 1.0 Scaling factor used to adjust the model distribution to the intensities of the data
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Member Typedef Documentation
CoordinateType
typedef double CoordinateType
IntensityType
typedef double IntensityType
LinearInterpolation
typedef Math::LinearInterpolation<double> LinearInterpolation
PositionType
typedef DPosition<1> PositionType
Constructor & Destructor Documentation
InterpolationModel() [1/2]
InterpolationModel () inline
Default constructor.
InterpolationModel() [2/2]
InterpolationModel (const InterpolationModel & source) inline
copy constructor
~InterpolationModel()
~InterpolationModel () inline override
destructor
Member Function Documentation
getCenter()
virtual CoordinateType getCenter () const inline virtual
"center" of the model, particular definition (depends on the derived model)
Reimplemented in IsotopeModel, ExtendedIsotopeModel, EGHModel, BiGaussModel, GaussModel, and EmgModel.
getIntensity() [1/2]
IntensityType getIntensity (const PositionType & pos) const inline override
access model predicted intensity at position pos
Referenced by MaxLikeliFitter1D::fitOffset_().
getIntensity() [2/2]
IntensityType getIntensity (CoordinateType coord) const inline
access model predicted intensity at position pos
getInterpolation()
const LinearInterpolation& getInterpolation () const inline
Returns the interpolation class.
Referenced by MaxLikeliFitter1D::fitOffset_().
getSamples()
void getSamples (SamplesType & cont) const inline override virtual
get reasonable set of samples from the model (i.e. for printing)
Implements BaseModel< 1 >.
getScalingFactor()
CoordinateType getScalingFactor () const inline
get the scaling for the model
A scaling factor of scaling means that the area under the model equals scaling. Default is 1.
operator=()
virtual InterpolationModel& operator= (const InterpolationModel & source) inline virtual
assignment operator
References InterpolationModel::interpolation_, InterpolationModel::interpolation_step_, BaseModel< D >::operator=(), and InterpolationModel::scaling_.
setInterpolationStep()
void setInterpolationStep (CoordinateType interpolation_step) inline
Set the interpolation step for the linear interpolation of the model.
For setting to take affect, call setSamples().
setOffset()
virtual void setOffset (CoordinateType offset) inline virtual
set the offset of the model
The whole model will be shifted to the new offset without being recomputed all over. Setting takes affect immediately.
Reimplemented in IsotopeModel, ExtendedIsotopeModel, EGHModel, BiGaussModel, GaussModel, and EmgModel.
Referenced by MaxLikeliFitter1D::fitOffset_().
setSamples()
virtual void setSamples () inline virtual
set sample/supporting points of interpolation wrt params.
Reimplemented in ExtendedIsotopeModel, EGHModel, BiGaussModel, GaussModel, and EmgModel.
setScalingFactor()
void setScalingFactor (CoordinateType scaling) inline
updateMembers_()
void updateMembers_ () inline override protected virtual
This method is used to update extra member variables at the end of the setParameters() method.
Also call it at the end of the derived classes' copy constructor and assignment operator.
The default implementation is empty.
Reimplemented from DefaultParamHandler.
Reimplemented in IsotopeModel.
References BaseModel< D >::updateMembers_().
Member Data Documentation
interpolation_
LinearInterpolation interpolation_ protected
Referenced by InterpolationModel::operator=().
interpolation_step_
CoordinateType interpolation_step_ protected
Referenced by InterpolationModel::operator=().
scaling_
CoordinateType scaling_ protected
Referenced by InterpolationModel::operator=().