OpenMS: IsotopeWaveletTransform< PeakType >::TransSpectrum Class Reference
IsotopeWaveletTransform< PeakType >::TransSpectrum Class Reference
Internally (only by GPUs) used data structure . It allows efficient data exchange between CPU and GPU and avoids unnecessary memory moves. The class is tailored on the isotope wavelet transform and is in general not applicable on similar - but different - situations.
#include <OpenMS/TRANSFORMATIONS/FEATUREFINDER/IsotopeWaveletTransform.h>
Public Member Functions
TransSpectrum ()
TransSpectrum (const MSSpectrum *reference)
virtual ~TransSpectrum ()
virtual void destroy ()
double getRT () const
double getMZ (const UInt i) const
double getRefIntensity (const UInt i) const
double getTransIntensity (const UInt i) const
void setTransIntensity (const UInt i, const double intens)
Size size () const
const MSSpectrum * getRefSpectrum ()
const MSSpectrum * getRefSpectrum () const
MSSpectrum::const_iterator MZBegin (const double mz) const
MSSpectrum::const_iterator MZEnd (const double mz) const
MSSpectrum::const_iterator end () const
MSSpectrum::const_iterator begin () const
Protected Attributes
const MSSpectrum * reference_
The reference spectrum.
std::vector< float > * trans_intens_
The intensities of the transform.
Friends
class IsotopeWaveletTransform
Detailed Description
template<typename PeakType>
class OpenMS::IsotopeWaveletTransform< PeakType >::TransSpectrum
Internally (only by GPUs) used data structure . It allows efficient data exchange between CPU and GPU and avoids unnecessary memory moves. The class is tailored on the isotope wavelet transform and is in general not applicable on similar - but different - situations.
Constructor & Destructor Documentation
TransSpectrum() [1/2]
TransSpectrum () inline
Default constructor
TransSpectrum() [2/2]
TransSpectrum (const MSSpectrum * reference) inline
Copy constructor
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_, and IsotopeWaveletTransform< PeakType >::TransSpectrum::trans_intens_.
~TransSpectrum()
virtual ~TransSpectrum () inline virtual
Destructor
References IsotopeWaveletTransform< PeakType >::TransSpectrum::trans_intens_.
Member Function Documentation
begin()
MSSpectrum::const_iterator begin () const inline
Attention: iterations will only performed over the reference spectrum. You will have to use the "distance"-function in order to get the corresponding entry of the transform.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
Referenced by IsotopeWaveletTransform< PeakType >::checkPositionForPlausibility_(), and IsotopeWaveletTransform< PeakType >::scoreThis_().
destroy()
virtual void destroy () inline virtual
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_, and IsotopeWaveletTransform< PeakType >::TransSpectrum::trans_intens_.
end()
MSSpectrum::const_iterator end () const inline
Attention: iterations will only performed over the reference spectrum. You will have to use the "distance"-function in order to get the corresponding entry of the transform.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
Referenced by IsotopeWaveletTransform< PeakType >::checkPositionForPlausibility_().
getMZ()
double getMZ (const UInt i) const inline
Returns the mass-over-charge ratio at index i.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
Referenced by IsotopeWaveletTransform< PeakType >::scoreThis_().
getRefIntensity()
double getRefIntensity (const UInt i) const inline
Returns the reference (non-transformed) intensity at index i.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
getRefSpectrum() [1/2]
const MSSpectrum* getRefSpectrum () inline
Returns a pointer to the reference spectrum.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
getRefSpectrum() [2/2]
const MSSpectrum* getRefSpectrum () const inline
Returns a pointer to the reference spectrum.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
getRT()
double getRT () const inline
Returns the RT value (not the index) of the associated scan.
References MSSpectrum::getRT(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
getTransIntensity()
double getTransIntensity (const UInt i) const inline
Returns the transformed intensity at index i.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::trans_intens_.
Referenced by IsotopeWaveletTransform< PeakType >::getAvIntens_(), IsotopeWaveletTransform< PeakType >::getSdIntens_(), and IsotopeWaveletTransform< PeakType >::scoreThis_().
MZBegin()
MSSpectrum::const_iterator MZBegin (const double mz) const inline
Attention: iterations will only performed over the reference spectrum. You will have to use the "distance"-function in order to get the corresponding entry of the transform.
References MSSpectrum::MZBegin(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
Referenced by IsotopeWaveletTransform< PeakType >::checkPositionForPlausibility_(), and IsotopeWaveletTransform< PeakType >::scoreThis_().
MZEnd()
MSSpectrum::const_iterator MZEnd (const double mz) const inline
Attention: iterations will only performed over the reference spectrum. You will have to use the "distance"-function in order to get the corresponding entry of the transform.
References MSSpectrum::MZEnd(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::reference_.
setTransIntensity()
void setTransIntensity (const UInt i, const double intens) inline
Stores the intensity value i of the transform at position i.
size()
Size size () const inline
Returns the size of spectra.
References IsotopeWaveletTransform< PeakType >::TransSpectrum::trans_intens_.
Referenced by IsotopeWaveletTransform< PeakType >::getAvIntens_(), IsotopeWaveletTransform< PeakType >::getSdIntens_(), and IsotopeWaveletTransform< PeakType >::scoreThis_().
Friends And Related Function Documentation
IsotopeWaveletTransform
friend class IsotopeWaveletTransform friend
Member Data Documentation
reference_
const MSSpectrum* reference_ protected
The reference spectrum.
Referenced by IsotopeWaveletTransform< PeakType >::TransSpectrum::begin(), IsotopeWaveletTransform< PeakType >::TransSpectrum::destroy(), IsotopeWaveletTransform< PeakType >::TransSpectrum::end(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getMZ(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getRefIntensity(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getRefSpectrum(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getRT(), IsotopeWaveletTransform< PeakType >::TransSpectrum::MZBegin(), IsotopeWaveletTransform< PeakType >::TransSpectrum::MZEnd(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::TransSpectrum().
trans_intens_
std::vector<float>* trans_intens_ protected
The intensities of the transform.
Referenced by IsotopeWaveletTransform< PeakType >::TransSpectrum::destroy(), IsotopeWaveletTransform< PeakType >::TransSpectrum::getTransIntensity(), IsotopeWaveletTransform< PeakType >::TransSpectrum::size(), IsotopeWaveletTransform< PeakType >::TransSpectrum::TransSpectrum(), and IsotopeWaveletTransform< PeakType >::TransSpectrum::~TransSpectrum().