OpenMS: PeakPickerIterative Class Reference
PeakPickerIterative Class Reference
Analysis » PeakPicking
This class implements a peak-picking algorithm for high-resolution MS data (specifically designed for TOF-MS data).
#include <OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerIterative.h>
Public Member Functions
PeakPickerIterative ()
Constructor.
void updateMembers_ () override
This method is used to update extra member variables at the end of the setParameters() method.
~PeakPickerIterative () override
Destructor.
void pick (const MSSpectrum &input, MSSpectrum &output)
void pickExperiment (const PeakMap &input, PeakMap &output)
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Member Functions inherited from ProgressLogger
ProgressLogger ()
Constructor.
~ProgressLogger ()
Destructor.
ProgressLogger (const ProgressLogger &other)
Copy constructor.
ProgressLogger & operator= (const ProgressLogger &other)
Assignment Operator.
void setLogType (LogType type) const
Sets the progress log that should be used. The default type is NONE!
LogType getLogType () const
Returns the type of progress log being used.
void startProgress (SignedSize begin, SignedSize end, const String &label) const
Initializes the progress display.
void setProgress (SignedSize value) const
Sets the current progress.
void endProgress () const
Ends the progress display.
void nextProgress () const
increment progress by 1 (according to range begin-end)
Private Member Functions
void pickRecenterPeaks_ (const MSSpectrum &input, std::vector< PeakCandidate > &PeakCandidates, SignalToNoiseEstimatorMedian< MSSpectrum > &snt)
Private Attributes
double signal_to_noise_
double peak_width_
double spacing_difference_
int sn_bin_count_
int nr_iterations_
double sn_win_len_
bool check_width_internally_
Additional Inherited Members
Public Types inherited from ProgressLogger
enum LogType { CMD, GUI, NONE }
Possible log types.
Protected Member Functions inherited from DefaultParamHandler
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Static Protected Member Functions inherited from ProgressLogger
static String logTypeToFactoryName_ (LogType type)
Return the name of the factory product used for this log type.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Protected Attributes inherited from ProgressLogger
LogType type_
time_t last_invoke_
ProgressLoggerImpl * current_logger_
Static Protected Attributes inherited from ProgressLogger
static int recursion_depth_
Detailed Description
This class implements a peak-picking algorithm for high-resolution MS data (specifically designed for TOF-MS data).
This peak-picking algorithm detects ion signals in profile data and reconstructs the corresponding peak shape by identifying the left and right borders of the peak. It reports the area under the peak as intensity and the weighted m/z values as the m/z value as well as left/right border. Furthermore, it next tries to improve the peak positioning iteratively using the m/z center computed in the last iteration. This allows for refinement in the peak boundaries and more accurate determination of peak center and borders.
Its approach is similar to the PeakPickerHiRes but additionally uses an iterative approach to find and re-center peaks.
First, it uses the PeakPickerHiRes to find seeds or candidate peaks.
Next it uses n iterations to re-center those peaks and compute left/right borders for each peak.
Finally it removes peaks that are within the borders of other peaks.
So far, this peak picker was mainly tested on high resolution TOF-MS data.
Note
The peaks must be sorted according to ascending m/z!
Constructor & Destructor Documentation
PeakPickerIterative()
PeakPickerIterative () inline
Constructor.
~PeakPickerIterative()
~PeakPickerIterative () inline override
Destructor.
Member Function Documentation
pick()
void pick (const MSSpectrum & input, MSSpectrum & output) inline
References SpectrumSettings::CENTROID, MSSpectrum::clear(), DefaultParamHandler::getDefaults(), MSSpectrum::getFloatDataArrays(), MSSpectrum::getMSLevel(), MSSpectrum::getName(), MSSpectrum::getRT(), OpenMS::Constants::k, OPENMS_LOG_DEBUG, PeakPickerHiRes::pick(), Peak1D::setIntensity(), MSSpectrum::setMSLevel(), Peak1D::setMZ(), MSSpectrum::setName(), DefaultParamHandler::setParameters(), MSSpectrum::setRT(), SpectrumSettings::setType(), Param::setValue(), OpenMS::sort_peaks_by_intensity(), and MSSpectrum::sortByPosition().
pickExperiment()
void pickExperiment (const PeakMap & input, PeakMap & output) inline
References MSExperiment::clear(), MSExperiment::resize(), and MSExperiment::size().
pickRecenterPeaks_()
void pickRecenterPeaks_ (const MSSpectrum & input, std::vector< PeakCandidate > & PeakCandidates, SignalToNoiseEstimatorMedian< MSSpectrum > & snt) inline private
References SignalToNoiseEstimator< Container >::getSignalToNoise(), and OpenMS::Constants::k.
updateMembers_()
void updateMembers_ () inline override virtual
This method is used to update extra member variables at the end of the setParameters() method.
Also call it at the end of the derived classes' copy constructor and assignment operator.
The default implementation is empty.
Reimplemented from DefaultParamHandler.
Member Data Documentation
check_width_internally_
bool check_width_internally_ private
nr_iterations_
int nr_iterations_ private
peak_width_
double peak_width_ private
signal_to_noise_
double signal_to_noise_ private
sn_bin_count_
int sn_bin_count_ private
sn_win_len_
double sn_win_len_ private
spacing_difference_
double spacing_difference_ private