OpenMS: INIFileEditorWindow Class Reference
INIFileEditorWindow Class Reference
shows the ParamEditor widget in a QMainWindow with a toolbar
#include <OpenMS/VISUAL/APPLICATIONS/INIFileEditorWindow.h>
Public Slots
bool openFile (const String &filename="")
loads the xml-file into a Param object and loads Param into ParamEditor
bool saveFile ()
saves the users changes in a xml-file if the Param object is valid
bool saveFileAs ()
like saveFile but with a file dialog to choose a filename
void updateWindowTitle (bool)
if the user changes data in ParamEditor the title shows a '*'
Public Member Functions
INIFileEditorWindow (QWidget *parent=nullptr)
menu is created here
void closeEvent (QCloseEvent *event) override
when user closes window a message box asks the user if he wants to save
Private Attributes
ParamEditor * editor_
ParamEditor object for visualization.
Param param_
Param object for storing data.
QString filename_
filename of xml-file to store the Param object
String current_path_
path used as next default location of the load/store dialogs
Detailed Description
shows the ParamEditor widget in a QMainWindow with a toolbar
Constructor & Destructor Documentation
INIFileEditorWindow()
INIFileEditorWindow (QWidget * parent = nullptr)
menu is created here
References INIFileEditorWindow::editor_, INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFile(), INIFileEditorWindow::saveFileAs(), and INIFileEditorWindow::updateWindowTitle().
Member Function Documentation
closeEvent()
void closeEvent (QCloseEvent * event) override
when user closes window a message box asks the user if he wants to save
References INIFileEditorWindow::editor_, ParamEditor::isModified(), and INIFileEditorWindow::saveFile().
openFile
bool openFile (const String & filename = "") slot
loads the xml-file into a Param object and loads Param into ParamEditor
References Param::clear(), INIFileEditorWindow::current_path_, INIFileEditorWindow::editor_, INIFileEditorWindow::filename_, ParamEditor::isModified(), ParamXMLFile::load(), ParamEditor::load(), OPENMS_LOG_ERROR, INIFileEditorWindow::param_, File::readable(), String::toQString(), and INIFileEditorWindow::updateWindowTitle().
Referenced by INIFileEditorWindow::INIFileEditorWindow(), and main().
saveFile
bool saveFile () slot
saves the users changes in a xml-file if the Param object is valid
References INIFileEditorWindow::editor_, INIFileEditorWindow::filename_, ParamEditor::isModified(), INIFileEditorWindow::param_, ParamXMLFile::store(), ParamEditor::store(), and INIFileEditorWindow::updateWindowTitle().
Referenced by INIFileEditorWindow::closeEvent(), and INIFileEditorWindow::INIFileEditorWindow().
saveFileAs
bool saveFileAs () slot
like saveFile but with a file dialog to choose a filename
References INIFileEditorWindow::current_path_, INIFileEditorWindow::editor_, INIFileEditorWindow::filename_, ParamEditor::isModified(), INIFileEditorWindow::param_, ParamXMLFile::store(), ParamEditor::store(), String::toQString(), and INIFileEditorWindow::updateWindowTitle().
Referenced by INIFileEditorWindow::INIFileEditorWindow().
updateWindowTitle
void updateWindowTitle (bool update) slot
if the user changes data in ParamEditor the title shows a '*'
References File::basename(), INIFileEditorWindow::current_path_, INIFileEditorWindow::filename_, and File::path().
Referenced by INIFileEditorWindow::INIFileEditorWindow(), INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFile(), and INIFileEditorWindow::saveFileAs().
Member Data Documentation
current_path_
String current_path_ private
path used as next default location of the load/store dialogs
Referenced by INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFileAs(), and INIFileEditorWindow::updateWindowTitle().
editor_
ParamEditor* editor_ private
ParamEditor object for visualization.
Referenced by INIFileEditorWindow::closeEvent(), INIFileEditorWindow::INIFileEditorWindow(), INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFile(), and INIFileEditorWindow::saveFileAs().
filename_
QString filename_ private
filename of xml-file to store the Param object
Referenced by INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFile(), INIFileEditorWindow::saveFileAs(), and INIFileEditorWindow::updateWindowTitle().
param_
Param param_ private
Param object for storing data.
Referenced by INIFileEditorWindow::openFile(), INIFileEditorWindow::saveFile(), and INIFileEditorWindow::saveFileAs().