OpenMS: TOPPASBase Class Reference
TOPPASBase Class Reference
Visual » TOPPAS
Main window of the TOPPAS tool.
#include <OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h>
Public Slots
void addTOPPASFile (const String &file_name, bool in_new_window=true)
opens the file in a new window
void openFileDialog ()
shows the dialog for opening files
void openExampleDialog ()
shows the dialog for opening example files
void newPipeline (const int id=-1)
shows the dialog for creating a new file (pass IDINITIALUNTITLED as id if its the first call)
void includePipeline ()
shows the dialog for including another workflow in the currently opened one
void saveCurrentPipelineAs ()
shows the dialog for saving the current file and updates the current tab caption
void savePipeline ()
saves the pipeline (determined by Qt's sender mechanism)
void exportAsImage ()
exports the current pipeline as image
void loadPipelineResourceFile ()
shows a file dialog for selecting the resource file to load
void savePipelineResourceFile ()
shows a file dialog for selecting the resource file to write to
void openOnlinePipelineRepository ()
opens the OpenMS Homepage to download example workflows
void preferencesDialog ()
shows the preferences dialog
void updateCurrentPath ()
changes the current path according to the currently active window/layer
void updateTabBar (QMdiSubWindow *w)
brings the tab corresponding to the active window in front
void showAboutDialog ()
Shows the 'About' dialog.
void showURL ()
shows the URL stored in the data of the sender QAction
void showStatusMessage (std::string msg, OpenMS::UInt time)
Shows a status message in the status bar.
void showCursorStatus (double x, double y)
shows x,y coordinates in the status bar
void closeFile ()
closes the active window
void updateToolBar ()
updates the toolbar
void runPipeline ()
Runs the pipeline of the current window.
void abortPipeline ()
Terminates the current pipeline.
void toolStarted ()
Called when a tool is started.
void toolFinished ()
Called when a tool is finished.
void toolCrashed ()
Called when a tool crashes.
void toolFailed ()
Called when a tool execution fails.
void outputVertexFinished (const String &file)
Called when a file was successfully written to an output vertex.
void updateTOPPOutputLog (const QString &out)
Called when a TOPP tool produces (error) output.
void showPipelineFinishedLogMessage ()
Called by the scene if the pipeline execution finishes successfully.
void saveToClipboard (TOPPASScene *scene)
Saves scene to the clipboard.
void sendClipboardContent ()
Sends the clipboard content to the sender of the connected signal.
void refreshParameters ()
Refreshes the parameters of the TOPP tools of the current workflow and stores an updated workflow including the current parameters.
void openFilesInTOPPView (QStringList all_files)
Open files in a new TOPPView instance.
void openToppasFile (QString filename)
Opens a toppas file.
Public Member Functions
TOPPASBase (QWidget *parent=nullptr)
Constructor.
~TOPPASBase () override
Destructor.
void loadPreferences (String filename="")
Loads the preferences from the filename given.
void savePreferences ()
stores the preferences (used when this window is closed)
void loadFiles (const StringList &list, QSplashScreen *splash_screen)
loads the files and updates the splash screen
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Static Public Member Functions
common functions used in TOPPAS and TOPPView
static TOPPASTreeView * createTOPPToolsTreeWidget (QWidget *parent_widget=nullptr)
Creates and fills a tree widget with all available tools.
static QString savePipelineAs (TOPPASWidget *w, QString current_path)
static QString loadPipelineResourceFile (TOPPASWidget *w, QString current_path)
Loads and sets the resources of the TOPPASWidget.
static QString savePipelineResourceFile (TOPPASWidget *w, QString current_path)
Saves the resources of the TOPPASWidget.
static QString refreshPipelineParameters (TOPPASWidget *tw, QString current_path)
Refreshes the TOPP tools parameters of the pipeline.
Protected Attributes
Toolbar
QToolBar * tool_bar_
QMdiArea * ws_
Main workspace.
QWebView * webview_
OpenMS homepage workflow browser.
QNetworkAccessManager * network_manager_
download .toppas files from homepage
QNetworkReply * network_reply_
the content of the network request
TOPPASTabBar * tab_bar_
Tab bar. The address of the corresponding window to a tab is stored as an int in tabData()
QTreeWidget * tools_tree_view_
Tree view of all available TOPP tools.
QListWidget * blocks_list_
List of ready analysis pipelines.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Tab bar slots
TOPPASLogWindow * log_
Log output window.
QTextEdit * desc_
Workflow Description window.
void closeByTab (int id)
Closes the window corresponding to the data of the tab with identifier id.
void focusByTab (int id)
Raises the window corresponding to the data of the tab with identifier id.
void updateMenu ()
enable/disable menu entries depending on the current state
void showAsWindow_ (TOPPASWidget *sw, const String &caption, const int special_id=-1)
Shows the widget as window in the workspace (the special_id is only used for the first untitled widget (to be able to auto-close it later)
void insertNewVertex_ (double x, double y, QTreeWidgetItem *item=nullptr)
Inserts a new TOPP tool in the current window at (x,y)
void insertNewVertexInCenter_ (QTreeWidgetItem *item)
Inserts the item in the middle of the current window.
void downloadTOPPASfromHomepage_ (const QUrl &url)
triggered when user clicks a link - if it ends in .TOPPAS we're done
void toppasFileDownloaded_ (QNetworkReply *r)
triggered when download of .toppas file is finished, so we can store & open it
void TOPPASreadyRead ()
debug...
void descriptionUpdated_ ()
user edited the workflow description
Status bar
QLabel * message_label_
Label for messages in the status bar.
String current_path_
String tmp_path_
The path for temporary files.
static int node_offset_ = 0
Offset counter for new inserted nodes (to avoid invisible stacking)
static qreal z_value_ = 42.0
z-value counter for new inserted nodes (new nodes should be on top)
TOPPASWidget * window_ (int id) const
returns the window with id id
TOPPASWidget * activeSubWindow_ () const
returns a pointer to the active TOPPASWidget (0 if none is active)
reimplemented Qt events
enum LogState { LS_NOTICE, LS_WARNING, LS_ERROR }
Log message states.
TOPPASScene * clipboard_scene_
The clipboard.
static const int IDINITIALUNTITLED = 1000
use this for the first call to newPipeline(), to ensure that the first empty (and unmodified) workspace is closed iff existing workflows are loaded
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *e) override
void showLogMessage_ (LogState state, const String &heading, const String &body)
Shows a log message in the log_ window.
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Detailed Description
Main window of the TOPPAS tool.
Member Enumeration Documentation
LogState
enum LogState protected
Log message states.
Enumerator
LS_NOTICE
Notice.
LS_WARNING
Warning.
LS_ERROR
Fatal error.
Constructor & Destructor Documentation
TOPPASBase()
TOPPASBase (QWidget * parent = nullptr)
Constructor.
References TOPPASBase::abortPipeline(), TOPPASTabBar::addTab(), TOPPASBase::closeByTab(), TOPPASBase::closeFile(), TOPPASBase::createTOPPToolsTreeWidget(), TOPPASBase::current_path_, DefaultParamHandler::defaults_, DefaultParamHandler::defaultsToParam_(), TOPPASBase::desc_, TOPPASBase::descriptionUpdated_(), TOPPASBase::exportAsImage(), TOPPASBase::focusByTab(), File::getTempDirectory(), File::getUniqueName(), Param::getValue(), TOPPASBase::includePipeline(), TOPPASBase::insertNewVertexInCenter_(), TOPPASBase::loadPipelineResourceFile(), TOPPASBase::loadPreferences(), TOPPASBase::log_, TOPPASBase::message_label_, TOPPASBase::network_manager_, TOPPASBase::newPipeline(), TOPPASBase::openExampleDialog(), TOPPASBase::openFileDialog(), TOPPASBase::openOnlinePipelineRepository(), DefaultParamHandler::param_, TOPPASBase::refreshParameters(), TOPPASTabBar::removeId(), TOPPASBase::runPipeline(), TOPPASBase::saveCurrentPipelineAs(), TOPPASBase::savePipeline(), TOPPASBase::savePipelineResourceFile(), TOPPASLogWindow::setMaxLength(), Param::setValidStrings(), Param::setValue(), TOPPASBase::showAboutDialog(), TOPPASBase::showURL(), TOPPASBase::tab_bar_, TOPPASBase::tmp_path_, TOPPASBase::tools_tree_view_, TOPPASBase::toppasFileDownloaded_(), String::toQString(), TOPPASBase::updateMenu(), TOPPASBase::updateTabBar(), and TOPPASBase::ws_.
~TOPPASBase()
~TOPPASBase () override
Destructor.
References File::getTempDirectory(), File::removeDirRecursively(), TOPPASBase::savePreferences(), and TOPPASBase::tmp_path_.
Member Function Documentation
abortPipeline
void abortPipeline () slot
Terminates the current pipeline.
References TOPPASScene::abortPipeline(), TOPPASBase::activeSubWindow_(), TOPPASWidget::getScene(), and TOPPASBase::updateMenu().
Referenced by TOPPASBase::TOPPASBase().
activeSubWindow_()
TOPPASWidget * activeSubWindow_ () const protected
returns a pointer to the active TOPPASWidget (0 if none is active)
References TOPPASBase::ws_.
Referenced by TOPPASBase::abortPipeline(), TOPPASBase::addTOPPASFile(), TOPPASBase::descriptionUpdated_(), TOPPASBase::exportAsImage(), TOPPASBase::insertNewVertex_(), TOPPASBase::insertNewVertexInCenter_(), TOPPASBase::keyPressEvent(), TOPPASBase::loadPipelineResourceFile(), TOPPASBase::refreshParameters(), TOPPASBase::runPipeline(), TOPPASBase::saveCurrentPipelineAs(), TOPPASBase::savePipeline(), TOPPASBase::savePipelineResourceFile(), and TOPPASBase::updateMenu().
addTOPPASFile
void addTOPPASFile (const String & file_name, bool in_new_window = true) slot
opens the file in a new window
References TOPPASBase::activeSubWindow_(), File::basename(), TOPPASBase::closeByTab(), TOPPASWidget::getScene(), TOPPASBase::IDINITIALUNTITLED, TOPPASScene::include(), TOPPASScene::load(), OPENMS_LOG_ERROR, TOPPASBase::outputVertexFinished(), TOPPASBase::showAsWindow_(), TOPPASBase::tmp_path_, TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), TOPPASBase::toolStarted(), String::toQString(), TOPPASBase::updateTOPPOutputLog(), TOPPASScene::verticesBegin(), TOPPASScene::verticesEnd(), TOPPASScene::wasChanged(), TOPPASBase::window_(), and TOPPASBase::ws_.
Referenced by TOPPASBase::includePipeline(), TOPPASBase::loadFiles(), TOPPASBase::openExampleDialog(), TOPPASBase::openFileDialog(), TOPPASBase::openToppasFile(), and TOPPASBase::showAsWindow_().
closeByTab
void closeByTab (int id) protected slot
Closes the window corresponding to the data of the tab with identifier id.
References TOPPASTabBar::removeId(), TOPPASBase::tab_bar_, TOPPASBase::updateMenu(), and TOPPASBase::window_().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::TOPPASBase().
closeEvent()
void closeEvent (QCloseEvent * event) override protected
References TOPPASWidget::getScene(), TOPPASScene::saveIfChanged(), and TOPPASBase::ws_.
closeFile
void closeFile () slot
closes the active window
References TOPPASBase::updateMenu(), and TOPPASBase::ws_.
Referenced by TOPPASBase::TOPPASBase().
createTOPPToolsTreeWidget()
TOPPASTreeView * createTOPPToolsTreeWidget (QWidget * parent_widget = nullptr) static
Creates and fills a tree widget with all available tools.
References ToolHandler::getTOPPToolList(), ToolHandler::getTypes(), ToolHandler::getUtilList(), and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
descriptionUpdated_
void descriptionUpdated_ () protected slot
user edited the workflow description
References TOPPASBase::activeSubWindow_(), TOPPASBase::desc_, TOPPASWidget::getScene(), TOPPASScene::setChanged(), and TOPPASScene::setDescription().
Referenced by TOPPASBase::TOPPASBase().
downloadTOPPASfromHomepage_
void downloadTOPPASfromHomepage_ (const QUrl & url) protected slot
triggered when user clicks a link - if it ends in .TOPPAS we're done
References TOPPASBase::LS_NOTICE, TOPPASBase::network_manager_, TOPPASBase::network_reply_, TOPPASBase::showLogMessage_(), and TOPPASBase::TOPPASreadyRead().
exportAsImage
void exportAsImage () slot
exports the current pipeline as image
References TOPPASBase::activeSubWindow_(), TOPPASBase::current_path_, TOPPASWidget::getScene(), TOPPASScene::setDescription(), and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
focusByTab
void focusByTab (int id) protected slot
Raises the window corresponding to the data of the tab with identifier id.
References TOPPASBase::desc_, TOPPASScene::getDescription(), TOPPASWidget::getScene(), and TOPPASBase::window_().
Referenced by TOPPASBase::TOPPASBase().
includePipeline
void includePipeline () slot
shows the dialog for including another workflow in the currently opened one
References TOPPASBase::addTOPPASFile(), TOPPASBase::current_path_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
insertNewVertex_
void insertNewVertex_ (double x, double y, QTreeWidgetItem * item = nullptr) protected slot
Inserts a new TOPP tool in the current window at (x,y)
References TOPPASBase::activeSubWindow_(), TOPPASScene::addVertex(), TOPPASScene::connectOutputVertexSignals(), TOPPASScene::connectToolVertexSignals(), TOPPASScene::connectVertexSignals(), TOPPASWidget::getScene(), TOPPASToolVertex::isToolReady(), TOPPASBase::outputVertexFinished(), TOPPASScene::setChanged(), tool_name, TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), TOPPASBase::tools_tree_view_, TOPPASBase::toolStarted(), TOPPASScene::topoSort(), TOPPASBase::updateTOPPOutputLog(), and TOPPASBase::z_value_.
Referenced by TOPPASBase::insertNewVertexInCenter_(), and TOPPASBase::showAsWindow_().
insertNewVertexInCenter_
void insertNewVertexInCenter_ (QTreeWidgetItem * item) protected slot
Inserts the item in the middle of the current window.
References TOPPASBase::activeSubWindow_(), TOPPASBase::insertNewVertex_(), TOPPASBase::node_offset_, and TOPPASBase::tools_tree_view_.
Referenced by TOPPASBase::TOPPASBase().
keyPressEvent()
void keyPressEvent (QKeyEvent * e) override protected
References TOPPASBase::activeSubWindow_(), TOPPASWidget::getScene(), and TOPPASScene::runPipeline().
loadFiles()
void loadFiles (const StringList & list, QSplashScreen * splash_screen)
loads the files and updates the splash screen
References TOPPASBase::addTOPPASFile().
Referenced by main().
loadPipelineResourceFile [1/2]
void loadPipelineResourceFile () slot
shows a file dialog for selecting the resource file to load
References TOPPASBase::activeSubWindow_(), TOPPASBase::current_path_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
loadPipelineResourceFile() [2/2]
QString loadPipelineResourceFile (TOPPASWidget * w, QString current_path) static
Loads and sets the resources of the TOPPASWidget.
References TOPPASWidget::getScene(), TOPPASResources::load(), and TOPPASScene::loadResources().
loadPreferences()
void loadPreferences (String filename = "")
Loads the preferences from the filename given.
If the filename is empty, the application name + ".ini" is used as filename
References File::exists(), Param::exists(), Param::getValue(), VersionInfo::getVersion(), ParamXMLFile::load(), DefaultParamHandler::param_, DefaultParamHandler::setParameters(), Param::setValue(), and DataValue::toString().
Referenced by main(), and TOPPASBase::TOPPASBase().
newPipeline
void newPipeline (const int id = -1) slot
shows the dialog for creating a new file (pass IDINITIALUNTITLED as id if its the first call)
References TOPPASBase::showAsWindow_(), TOPPASBase::tmp_path_, and TOPPASBase::ws_.
Referenced by main(), and TOPPASBase::TOPPASBase().
openExampleDialog
void openExampleDialog () slot
shows the dialog for opening example files
References TOPPASBase::addTOPPASFile(), and File::getOpenMSDataPath().
Referenced by TOPPASBase::TOPPASBase().
openFileDialog
void openFileDialog () slot
shows the dialog for opening files
References TOPPASBase::addTOPPASFile(), TOPPASBase::current_path_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
openFilesInTOPPView
void openFilesInTOPPView (QStringList all_files) slot
Open files in a new TOPPView instance.
References GUIHelpers::startTOPPView().
Referenced by TOPPASBase::showAsWindow_().
openOnlinePipelineRepository
void openOnlinePipelineRepository () slot
opens the OpenMS Homepage to download example workflows
Referenced by TOPPASBase::TOPPASBase().
openToppasFile
void openToppasFile (QString filename) slot
Opens a toppas file.
References TOPPASBase::addTOPPASFile().
outputVertexFinished
void outputVertexFinished (const String & file) slot
Called when a file was successfully written to an output vertex.
References TOPPASBase::LS_NOTICE, and TOPPASBase::showLogMessage_().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::insertNewVertex_().
preferencesDialog
void preferencesDialog () slot
shows the preferences dialog
References TOPPASBase::savePreferences().
refreshParameters
void refreshParameters () slot
Refreshes the parameters of the TOPP tools of the current workflow and stores an updated workflow including the current parameters.
References TOPPASBase::activeSubWindow_(), File::basename(), TOPPASBase::current_path_, TOPPASBase::refreshPipelineParameters(), TOPPASBase::tab_bar_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
refreshPipelineParameters()
QString refreshPipelineParameters (TOPPASWidget * tw, QString current_path) static
Refreshes the TOPP tools parameters of the pipeline.
References TOPPASWidget::getScene(), TOPPASScene::refreshParameters(), TOPPASBase::savePipelineAs(), TOPPASScene::setChanged(), TOPPASScene::ST_REFRESH_CHANGEINVALID, TOPPASScene::ST_REFRESH_NOCHANGE, TOPPASScene::ST_REFRESH_REMAINSINVALID, and TOPPASScene::updateEdgeColors().
Referenced by TOPPASBase::refreshParameters().
runPipeline
void runPipeline () slot
Runs the pipeline of the current window.
References TOPPASBase::activeSubWindow_(), TOPPASWidget::getScene(), and TOPPASScene::runPipeline().
Referenced by TOPPASBase::TOPPASBase().
saveCurrentPipelineAs
void saveCurrentPipelineAs () slot
shows the dialog for saving the current file and updates the current tab caption
References TOPPASBase::activeSubWindow_(), File::basename(), TOPPASBase::current_path_, TOPPASBase::savePipelineAs(), TOPPASBase::tab_bar_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
savePipeline
void savePipeline () slot
saves the pipeline (determined by Qt's sender mechanism)
References TOPPASBase::activeSubWindow_(), File::basename(), TOPPASBase::current_path_, TOPPASScene::getSaveFileName(), TOPPASWidget::getScene(), TOPPASBase::savePipelineAs(), TOPPASScene::store(), TOPPASBase::tab_bar_, and String::toQString().
Referenced by TOPPASBase::showAsWindow_(), and TOPPASBase::TOPPASBase().
savePipelineAs()
QString savePipelineAs (TOPPASWidget * w, QString current_path) static
Saves the workflow in the provided TOPPASWidget to a user defined location. Returns the full file name or "" if no valid one is selected.
References File::basename(), TOPPASWidget::getScene(), TOPPASScene::store(), and String::toQString().
Referenced by TOPPASBase::refreshPipelineParameters(), TOPPASBase::saveCurrentPipelineAs(), and TOPPASBase::savePipeline().
savePipelineResourceFile [1/2]
void savePipelineResourceFile () slot
shows a file dialog for selecting the resource file to write to
References TOPPASBase::activeSubWindow_(), TOPPASBase::current_path_, and String::toQString().
Referenced by TOPPASBase::TOPPASBase().
savePipelineResourceFile() [2/2]
QString savePipelineResourceFile (TOPPASWidget * w, QString current_path) static
Saves the resources of the TOPPASWidget.
References TOPPASScene::createResources(), TOPPASWidget::getScene(), and TOPPASResources::store().
savePreferences()
void savePreferences ()
stores the preferences (used when this window is closed)
References Param::copy(), Param::getValue(), VersionInfo::getVersion(), DefaultParamHandler::param_, Param::setValue(), and ParamXMLFile::store().
Referenced by TOPPASBase::preferencesDialog(), and TOPPASBase::~TOPPASBase().
saveToClipboard
void saveToClipboard (TOPPASScene * scene) slot
Saves scene to the clipboard.
References TOPPASBase::clipboard_scene_.
Referenced by TOPPASBase::showAsWindow_().
sendClipboardContent
void sendClipboardContent () slot
Sends the clipboard content to the sender of the connected signal.
References TOPPASBase::clipboard_scene_, and TOPPASScene::setClipboard().
Referenced by TOPPASBase::showAsWindow_().
showAboutDialog
void showAboutDialog () slot
Shows the 'About' dialog.
References QApplicationTOPP::showAboutDialog().
Referenced by TOPPASBase::TOPPASBase().
showAsWindow_
void showAsWindow_ (TOPPASWidget * sw, const String & caption, const int special_id = -1) protected slot
Shows the widget as window in the workspace (the special_id is only used for the first untitled widget (to be able to auto-close it later)
References TOPPASTabBar::addTab(), TOPPASBase::addTOPPASFile(), TOPPASBase::desc_, TOPPASScene::getDescription(), TOPPASWidget::getScene(), TOPPASWidget::getWindowId(), TOPPASBase::insertNewVertex_(), TOPPASBase::openFilesInTOPPView(), TOPPASBase::savePipeline(), TOPPASBase::saveToClipboard(), TOPPASBase::sendClipboardContent(), TOPPASTabBar::setCurrentId(), TOPPASWidget::setWindowId(), TOPPASBase::showCursorStatus(), TOPPASBase::showPipelineFinishedLogMessage(), TOPPASBase::showStatusMessage(), TOPPASBase::tab_bar_, String::toQString(), TOPPASBase::updateMenu(), TOPPASBase::updateTOPPOutputLog(), and TOPPASBase::ws_.
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::newPipeline().
showCursorStatus
void showCursorStatus (double x, double y) slot
shows x,y coordinates in the status bar
Referenced by TOPPASBase::showAsWindow_().
showLogMessage_()
void showLogMessage_ (TOPPASBase::LogState state, const String & heading, const String & body) protected
Shows a log message in the log_ window.
References DateTime::getTime(), TOPPASBase::log_, TOPPASBase::LS_ERROR, TOPPASBase::LS_NOTICE, TOPPASBase::LS_WARNING, DateTime::now(), and String::toQString().
Referenced by TOPPASBase::downloadTOPPASfromHomepage_(), TOPPASBase::outputVertexFinished(), TOPPASBase::showPipelineFinishedLogMessage(), TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), and TOPPASBase::toolStarted().
showPipelineFinishedLogMessage
void showPipelineFinishedLogMessage () slot
Called by the scene if the pipeline execution finishes successfully.
References TOPPASBase::LS_NOTICE, and TOPPASBase::showLogMessage_().
Referenced by TOPPASBase::showAsWindow_().
showStatusMessage
void showStatusMessage (std::string msg, OpenMS::UInt time) slot
Shows a status message in the status bar.
If time is 0 the status message is displayed until showStatusMessage is called with an empty message or a new message. Otherwise the message is displayed for time ms.
References TOPPASBase::message_label_.
Referenced by TOPPASBase::showAsWindow_().
showURL
void showURL () slot
shows the URL stored in the data of the sender QAction
References GUIHelpers::openURL().
Referenced by TOPPASBase::TOPPASBase().
toolCrashed
void toolCrashed () slot
Called when a tool crashes.
References TOPPASToolVertex::getName(), TOPPASToolVertex::getType(), TOPPASBase::LS_ERROR, TOPPASBase::showLogMessage_(), and TOPPASBase::updateMenu().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::insertNewVertex_().
toolFailed
void toolFailed () slot
Called when a tool execution fails.
References TOPPASToolVertex::getName(), TOPPASToolVertex::getType(), TOPPASBase::LS_ERROR, TOPPASBase::showLogMessage_(), and TOPPASBase::updateMenu().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::insertNewVertex_().
toolFinished
void toolFinished () slot
Called when a tool is finished.
References TOPPASToolVertex::getName(), TOPPASToolVertex::getType(), TOPPASBase::LS_NOTICE, TOPPASBase::showLogMessage_(), and TOPPASBase::updateMenu().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::insertNewVertex_().
toolStarted
void toolStarted () slot
Called when a tool is started.
References TOPPASToolVertex::getName(), TOPPASVertex::getTopoNr(), TOPPASToolVertex::getType(), TOPPASBase::LS_NOTICE, TOPPASBase::showLogMessage_(), and TOPPASBase::updateMenu().
Referenced by TOPPASBase::addTOPPASFile(), and TOPPASBase::insertNewVertex_().
toppasFileDownloaded_
void toppasFileDownloaded_ (QNetworkReply * r) protected slot
triggered when download of .toppas file is finished, so we can store & open it
Referenced by TOPPASBase::TOPPASBase().
TOPPASreadyRead
void TOPPASreadyRead () protected slot
debug...
References TOPPASBase::network_reply_, and OPENMS_LOG_DEBUG.
Referenced by TOPPASBase::downloadTOPPASfromHomepage_().
updateCurrentPath
void updateCurrentPath () slot
changes the current path according to the currently active window/layer
References TOPPASBase::current_path_, Param::getValue(), and DefaultParamHandler::param_.
updateMenu
void updateMenu () protected slot
enable/disable menu entries depending on the current state
References TOPPASBase::activeSubWindow_(), TOPPASWidget::getScene(), TOPPASScene::isPipelineRunning(), TOPPASBase::tab_bar_, and TOPPASScene::wasChanged().
Referenced by TOPPASBase::abortPipeline(), TOPPASBase::closeByTab(), TOPPASBase::closeFile(), TOPPASBase::showAsWindow_(), TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), TOPPASBase::toolStarted(), and TOPPASBase::TOPPASBase().
updateTabBar
void updateTabBar (QMdiSubWindow * w) slot
brings the tab corresponding to the active window in front
References TOPPASWidget::getWindowId(), TOPPASTabBar::setCurrentId(), and TOPPASBase::tab_bar_.
Referenced by TOPPASBase::TOPPASBase().
updateToolBar
void updateToolBar () slot
updates the toolbar
updateTOPPOutputLog
void updateTOPPOutputLog (const QString & out) slot
Called when a TOPP tool produces (error) output.
References TOPPASBase::log_.
Referenced by TOPPASBase::addTOPPASFile(), TOPPASBase::insertNewVertex_(), and TOPPASBase::showAsWindow_().
window_()
TOPPASWidget * window_ (int id) const protected
returns the window with id id
References TOPPASWidget::getWindowId(), and TOPPASBase::ws_.
Referenced by TOPPASBase::addTOPPASFile(), TOPPASBase::closeByTab(), and TOPPASBase::focusByTab().
Member Data Documentation
blocks_list_
QListWidget* blocks_list_ protected
List of ready analysis pipelines.
clipboard_scene_
TOPPASScene* clipboard_scene_ protected
The clipboard.
Referenced by TOPPASBase::saveToClipboard(), and TOPPASBase::sendClipboardContent().
current_path_
String current_path_ protected
The current path (used for loading and storing). Depending on the preferences this is static or changes with the current window/layer.
Referenced by TOPPASBase::exportAsImage(), TOPPASBase::includePipeline(), TOPPASBase::loadPipelineResourceFile(), TOPPASBase::openFileDialog(), TOPPASBase::refreshParameters(), TOPPASBase::saveCurrentPipelineAs(), TOPPASBase::savePipeline(), TOPPASBase::savePipelineResourceFile(), TOPPASBase::TOPPASBase(), and TOPPASBase::updateCurrentPath().
desc_
QTextEdit* desc_ protected
Workflow Description window.
Referenced by TOPPASBase::descriptionUpdated_(), TOPPASBase::focusByTab(), TOPPASBase::showAsWindow_(), and TOPPASBase::TOPPASBase().
IDINITIALUNTITLED
const int IDINITIALUNTITLED = 1000 static
use this for the first call to newPipeline(), to ensure that the first empty (and unmodified) workspace is closed iff existing workflows are loaded
Referenced by TOPPASBase::addTOPPASFile(), and main().
log_
TOPPASLogWindow* log_ protected
Log output window.
Referenced by TOPPASBase::showLogMessage_(), TOPPASBase::TOPPASBase(), and TOPPASBase::updateTOPPOutputLog().
message_label_
QLabel* message_label_ protected
Label for messages in the status bar.
Referenced by TOPPASBase::showStatusMessage(), and TOPPASBase::TOPPASBase().
network_manager_
QNetworkAccessManager* network_manager_ protected
download .toppas files from homepage
Referenced by TOPPASBase::downloadTOPPASfromHomepage_(), and TOPPASBase::TOPPASBase().
network_reply_
QNetworkReply* network_reply_ protected
the content of the network request
Referenced by TOPPASBase::downloadTOPPASfromHomepage_(), and TOPPASBase::TOPPASreadyRead().
node_offset_
int node_offset_ = 0 static protected
Offset counter for new inserted nodes (to avoid invisible stacking)
Referenced by TOPPASBase::insertNewVertexInCenter_().
tab_bar_
TOPPASTabBar* tab_bar_ protected
Tab bar. The address of the corresponding window to a tab is stored as an int in tabData()
Referenced by TOPPASBase::closeByTab(), TOPPASBase::refreshParameters(), TOPPASBase::saveCurrentPipelineAs(), TOPPASBase::savePipeline(), TOPPASBase::showAsWindow_(), TOPPASBase::TOPPASBase(), TOPPASBase::updateMenu(), and TOPPASBase::updateTabBar().
tmp_path_
String tmp_path_ protected
The path for temporary files.
Referenced by TOPPASBase::addTOPPASFile(), TOPPASBase::newPipeline(), TOPPASBase::TOPPASBase(), and TOPPASBase::~TOPPASBase().
tool_bar_
QToolBar* tool_bar_ protected
tools_tree_view_
QTreeWidget* tools_tree_view_ protected
Tree view of all available TOPP tools.
Referenced by TOPPASBase::insertNewVertex_(), TOPPASBase::insertNewVertexInCenter_(), and TOPPASBase::TOPPASBase().
webview_
QWebView* webview_ protected
OpenMS homepage workflow browser.
ws_
QMdiArea* ws_ protected
Main workspace.
Referenced by TOPPASBase::activeSubWindow_(), TOPPASBase::addTOPPASFile(), TOPPASBase::closeEvent(), TOPPASBase::closeFile(), TOPPASBase::newPipeline(), TOPPASBase::showAsWindow_(), TOPPASBase::TOPPASBase(), and TOPPASBase::window_().
z_value_
qreal z_value_ = 42.0 static protected
z-value counter for new inserted nodes (new nodes should be on top)
Referenced by TOPPASBase::insertNewVertex_().