OpenMS: TOPPViewBase Class Reference
TOPPViewBase Class Reference
Visual » TOPPView
Main window of TOPPView tool.
#include <OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h>
Public Slots
Toolbar slots
void setDrawMode1D (int)
void setIntensityMode (int)
void changeLayerFlag (bool)
void changeLabel (QAction *)
void changeUnassigned (QAction *)
void resetZoom ()
void toggleProjections ()
void loadFile (QString)
Loads a file given by the passed string.
Protected Slots
Layer manager and filter manager slots
void layerSelectionChange (int)
slot for layer manager selection change
void layerFilterVisibilityChange (bool)
Enables/disables the data filters for the current layer.
void layerContextMenu (const QPoint &pos)
slot for layer manager context menu
void logContextMenu (const QPoint &pos)
slot for log window context menu
void layerVisibilityChange (QListWidgetItem *item)
slot for layer manager visibility change (check box)
void filterContextMenu (const QPoint &pos)
slot for filter manager context menu
void filterEdit (QListWidgetItem *item)
slot for editing a filter
void layerEdit (QListWidgetItem *)
slot for editing the preferences of the current layer
void finishTOPPToolExecution (int exitCode, QProcess::ExitStatus exitStatus)
slot for the finished signal of the TOPP tools execution
void abortTOPPTool ()
aborts the execution of a TOPP tool
void rerunTOPPTool ()
returns the last invoked TOPP tool with the same parameters
void showSpectrumBrowser ()
shows the spectrum browser and updates it
void showSpectrumMetaData (int spectrum_index)
shows the spectrum metadata
Protected Attributes
dock widgets
QDockWidget * layer_dock_widget_
QDockWidget * views_dockwidget_
QDockWidget * filter_dock_widget_
Spectrum selection widgets
SpectraViewWidget * spectra_view_widget_
SpectraIdentificationViewWidget * spectra_identification_view_widget_
QListWidget * layers_view_
Layer management widget.
Filter widgets
QListWidget * filters_
QCheckBox * filters_check_box_
FileWatcher * watcher_
Watcher that tracks file changes (in order to update the data in the different views)
bool watcher_msgbox_
Holds the messageboxes for each layer that are currently popped up (to avoid popping them up again, if file changes again before the messagebox is closed)
bool zoom_together_
Stores whether the individual windows should zoom together (be linked) or not.
QAction * linkZoom_action_
QTextEdit * log_
Log output window.
Toolbar
QToolBar * tool_bar_
QButtonGroup * intensity_button_group_
QToolBar * tool_bar_1d_
QButtonGroup * draw_group_1d_
QToolBar * tool_bar_2d_peak_
QToolBar * tool_bar_2d_feat_
QToolBar * tool_bar_2d_cons_
QToolBar * tool_bar_2d_ident_
QAction * dm_precursors_2d_
QAction * dm_hull_2d_
QAction * dm_hulls_2d_
QToolButton * dm_label_2d_
QActionGroup * group_label_2d_
QToolButton * dm_unassigned_2d_
QActionGroup * group_unassigned_2d_
QAction * dm_elements_2d_
QAction * projections_2d_
QAction * dm_ident_2d_
EnhancedWorkspace * ws_
Main workspace.
EnhancedTabBar * tab_bar_
Tab bar. The address of the corresponding window to a tab is stored as an int in tabData()
Status bar
QLabel * message_label_
Label for messages in the status bar.
QLabel * mz_label_
m/z label for messages in the status bar
QLabel * rt_label_
RT label for messages in the status bar.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Friends
class TestTOPPView
Type definitions
typedef LayerData::FeatureMapType FeatureMapType
typedef LayerData::FeatureMapSharedPtrType FeatureMapSharedPtrType
typedef LayerData::ConsensusMapType ConsensusMapType
typedef LayerData::ConsensusMapSharedPtrType ConsensusMapSharedPtrType
typedef LayerData::ExperimentType ExperimentType
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType
typedef LayerData::ODExperimentSharedPtrType ODExperimentSharedPtrType
typedef ExperimentType::SpectrumType SpectrumType
Peak spectrum type.
TOPPViewBase (QWidget *parent=nullptr)
Constructor.
~TOPPViewBase () override
Destructor.
void addDataFile (const String &filename, bool show_options, bool add_to_recent, String caption="", UInt window_id=0, Size spectrum_id=0)
Opens and displays data from a file.
void addData (FeatureMapSharedPtrType feature_map, ConsensusMapSharedPtrType consensus_map, std::vector< PeptideIdentification > &peptides, ExperimentSharedPtrType peak_map, ODExperimentSharedPtrType on_disc_peak_map, LayerData::DataType data_type, bool show_as_1d, bool show_options, bool as_new_window=true, const String &filename="", const String &caption="", UInt window_id=0, Size spectrum_id=0)
Adds a peak or feature map to the viewer.
void loadFiles (const StringList &list, QSplashScreen *splash_screen)
Opens all the files in the string list.
void loadPreferences (String filename="")
Loads the preferences from the filename given.
void savePreferences ()
Stores the preferences (used when this window is closed)
Param getSpectrumParameters (UInt dim)
Returns the parameters for a SpectrumCanvas of dimension dim.
const LayerData * getCurrentLayer () const
Returns the active Layer data (0 if no layer is active)
EnhancedWorkspace * getWorkspace () const
returns a pointer to the EnhancedWorkspace containing SpectrumWidgets
SpectrumWidget * getActiveSpectrumWidget () const
returns a pointer to the active SpectrumWidget (0 if none is active)
Spectrum1DWidget * getActive1DWidget () const
returns a pointer to the active Spectrum1DWidget (0 the active window is no Spectrum1DWidget or there is no active window)
Spectrum2DWidget * getActive2DWidget () const
returns a pointer to the active Spectrum2DWidget (0 the active window is no Spectrum2DWidget or there is no active window)
Spectrum3DWidget * getActive3DWidget () const
returns a pointer to the active Spectrum3DWidget (0 the active window is no Spectrum2DWidget or there is no active window)
SpectrumCanvas * getActiveCanvas () const
returns a pointer to the active SpectrumCanvas (0 if none is active)
SpectraIdentificationViewWidget * getSpectraIdentificationViewWidget ()
returns a pointer to the SpectraIdentificationViewWidget
void showSpectrumWidgetInWindow (SpectrumWidget *sw, const String &caption)
Opens the provided spectrum widget in a new window.
void updateCurrentPath ()
changes the current path according to the currently active window/layer
void showURL ()
shows the URL stored in the data of the sender QAction
void openFileDialog ()
shows the file dialog for opening files
void openExampleDialog ()
shows the file dialog for opening example files
void showGoToDialog ()
shows the DB dialog for opening files
void preferencesDialog ()
shows the preferences dialog
void layerStatistics ()
Shows statistics (count,min,max,avg) about Intensity, Quality, Charge and meta data.
void editMetadata ()
lets the user edit the meta data of a layer
void layerActivated ()
gets called if a layer got activated
void layerZoomChanged ()
gets called when a layer changes in zoom
void linkZoom ()
link the zoom of individual windows
void layerDeactivated ()
gets called if a layer got deactivated
void closeFile ()
closes the active window
void updateToolBar ()
updates the toolbar
void updateLayerBar ()
adapts the layer bar to the active window
void updateViewBar ()
adapts view bar to the active window
void viewChanged (int)
changes the behavior according to the selected view in the spectra view bar and calls updateSpectraViewBar()
void viewTabwidgetDoubleClicked (int)
adds empty ID structure to allow manual annotations
void updateFilterBar ()
adapts the filter bar to the active window
void updateMenu ()
enabled/disabled menu entries depending on the current state
void updateTabBar (QMdiSubWindow *w)
brings the tab corresponding to the active window in front
void tileVertical ()
tile the open windows vertically
void tileHorizontal ()
tile the open windows horizontally
void showStatusMessage (std::string msg, OpenMS::UInt time)
Shows a status message in the status bar.
void showCursorStatus (double mz, double rt)
shows m/z and rt in the status bar
void showCursorStatusInvert (double mz, double rt)
shows m/z and rt in the status bar (inverting RT and m/z)
void showTOPPDialog ()
Apply TOPP tool.
void annotateWithID ()
Annotates current layer with ID data.
void showSpectrumGenerationDialog ()
Shows the theoretical spectrum generation dialog.
void showSpectrumAlignmentDialog ()
Shows the spectrum alignment dialog.
void showSpectrumAs1D (int index)
Shows the spectrum with index index of the active layer in 1D.
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices)
void showCurrentPeaksAs2D ()
Shows the current peak data of the active layer in 2D.
void showCurrentPeaksAs3D ()
Shows the current peak data of the active layer in 3D.
void showCurrentPeaksAsIonMobility ()
Shows the current peak data of the active layer as ion mobility.
void showCurrentPeaksAsDIA ()
Shows the current peak data of the active layer as DIA data.
void showAboutDialog ()
Shows the 'About' dialog.
void saveLayerAll ()
Saves the whole current layer data.
void saveLayerVisible ()
Saves the visible layer data.
void toggleGridLines ()
Toggles the grid lines.
void toggleAxisLegends ()
Toggles the axis legends.
void toggleInterestingMZs ()
Toggles drawing of interesting MZs.
void showPreferences ()
Shows current layer preferences.
void metadataFileDialog ()
dialog for inspecting database meta data
Tabbar slots
void closeByTab (int id)
Closes the window corresponding to the data of the tab with identifier id.
void enhancedWorkspaceWindowChanged (int id)
Raises the window corresponding to the data of the tab with identifier id.
void openRecentFile ()
Opens a file from the recent files menu.
void copyLayer (const QMimeData *data, QWidget *source, int id=-1)
Slot for drag-and-drop of layer manager to tabbar.
void updateProcessLog ()
Appends process output to log window.
void fileChanged_ (const String &)
Called if a data file has been externally changed.
void initializeDefaultParameters_ ()
Initializes the default parameters on TOPPView construction.
bool annotateMS1FromMassFingerprinting_ (const FeatureMap &identifications)
std::set< String > getFilenamesOfOpenFiles_ ()
unique list of files referenced by all layers
QStringList getFileList_ (const String &path_overwrite="")
Shows a dialog where the user can select files.
EnhancedTabBarWidgetInterface * window_ (int id) const
Returns the enhanced tabbar widget with id id.
Recent files
QStringList recent_files_
list of the recently opened files
std::vector< QAction * > recent_actions_
list of the recently opened files actions (menu entries)
void addRecentFile_ (const String &filename)
adds a Filename to the recent files
void updateRecentMenu_ ()
update the recent files menu
TOPP tool execution
struct {
Param param
String tool
String in
String out
String file_name
String layer_name
UInt window_id
Size spectrum_id
QProcess * process
QTime timer
bool visible
} topp_
Information needed for execution of TOPP tools.
void runTOPPTool_ ()
Runs the TOPP tool according to the information in topp_.
void checkPreferences_ ()
check if all available preferences get set by the .ini file. If there are some missing entries fill them with default values.
reimplemented Qt events
enum LogState { LS_NOTICE, LS_WARNING, LS_ERROR }
Log message states.
QMenu * add_2d_context_
Additional context menu for 2D layers.
String current_path_
QTabWidget * views_tabwidget_
Tabwidget that hold the different views on the loaded data.
TOPPViewIdentificationViewBehavior * identificationview_behavior_
TOPPView behavior for the identification view.
TOPPViewSpectraViewBehavior * spectraview_behavior_
TOPPView behavior for the spectra view.
static const String CAPTION_3D_SUFFIX_ = " (3D)"
Suffix appended to caption of tabs when layer is shown in 3D.
float estimateNoiseFromRandomMS1Scans (const ExperimentType &exp, UInt n_scans=10)
Estimates the noise by evaluating n_scans random scans of MS level 1. Assumes that 4/5 of intensities is noise.
void closeEvent (QCloseEvent *event) override
void showLogMessage_ (LogState state, const String &heading, const String &body)
Shows a log message in the log_ window.
void showTOPPDialog_ (bool visible)
Apply TOPP tool. If visible is true, only the visible data is used, otherwise the whole layer is used.
static bool containsMS1Scans (const ExperimentType &exp)
Returns true if contains at least one MS1 spectrum.
static bool containsIMData (const MSSpectrum &s)
Returns true if contains ion mobility data.
static bool hasMS1Zeros (const ExperimentType &exp)
Returns true of experiment has at least one exact zero valued peak in any of its MS1 spectra.
static bool hasPeptideIdentifications (const ExperimentType &map)
Returns true if the experiment map contains peptide identifications.
Additional Inherited Members
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Detailed Description
Main window of TOPPView tool.
Uses the default QMainWindow layout (see Qt documentation) with a central widget in the middle (consistent of a EnhancedTabBar and an EnhancedWorkspace) and multiple docked widgets around it (to the right and below) and multiple tool bars. On top and bottom are a menu bar and a status bar.
The main layout is using
Central Widget:
EnhancedTabBar: tab_bar_
EnhancedWorkspace: ws_
Docked to the right:
layer_dock_widget_
views_dockwidget_
filter_dock_widget_
Docked to the bottom:
log_bar (only connected through slots)
The views_dockwidget_ internally holds a tab widget views_tabwidget_ which holds the two different views on the data (spectra and identification view) which are implemented using identificationview_behavior_ and spectraview_behavior_.
Improvement:
Use DataRepository singleton to share data between TOPPView and the canvas classes (Hiwi)
Improvement:
For painting single mass traces with no width we currently paint each line twice (once going down, and then coming back up). This could be more efficient...
Improvement:
Keep spectrum browser widgets of all layers in memory in order to avoid rebuilding the entire tree view every time the active layer changes (Hiwi, Johannes)
Member Typedef Documentation
ConsensusMapSharedPtrType
typedef LayerData::ConsensusMapSharedPtrType ConsensusMapSharedPtrType
ConsensusMapType
typedef LayerData::ConsensusMapType ConsensusMapType
ExperimentSharedPtrType
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType
ExperimentType
typedef LayerData::ExperimentType ExperimentType
FeatureMapSharedPtrType
typedef LayerData::FeatureMapSharedPtrType FeatureMapSharedPtrType
FeatureMapType
typedef LayerData::FeatureMapType FeatureMapType
ODExperimentSharedPtrType
typedef LayerData::ODExperimentSharedPtrType ODExperimentSharedPtrType
SpectrumType
typedef ExperimentType::SpectrumType SpectrumType
Peak spectrum type.
Member Enumeration Documentation
LogState
enum LogState protected
Log message states.
Enumerator
LS_NOTICE
Notice.
LS_WARNING
Warning.
LS_ERROR
Fatal error.
Constructor & Destructor Documentation
TOPPViewBase()
TOPPViewBase (QWidget * parent = nullptr)
Constructor.
References EnhancedTabBar::addTab(), TOPPViewBase::annotateWithID(), TOPPViewBase::changeLabel(), TOPPViewBase::changeLayerFlag(), TOPPViewBase::changeUnassigned(), TOPPViewBase::closeByTab(), TOPPViewBase::closeFile(), TOPPViewBase::copyLayer(), TOPPViewBase::current_path_, DefaultParamHandler::defaultsToParam_(), Spectrum1DCanvas::DM_CONNECTEDLINES, TOPPViewBase::dm_elements_2d_, TOPPViewBase::dm_hull_2d_, TOPPViewBase::dm_hulls_2d_, TOPPViewBase::dm_ident_2d_, TOPPViewBase::dm_label_2d_, Spectrum1DCanvas::DM_PEAKS, TOPPViewBase::dm_precursors_2d_, TOPPViewBase::dm_unassigned_2d_, TOPPViewBase::draw_group_1d_, TOPPViewBase::editMetadata(), TOPPViewBase::enhancedWorkspaceWindowChanged(), TOPPViewBase::fileChanged_(), TOPPViewBase::filter_dock_widget_, TOPPViewBase::filterContextMenu(), TOPPViewBase::filterEdit(), TOPPViewBase::filters_, TOPPViewBase::filters_check_box_, Param::getValue(), TOPPViewBase::group_label_2d_, TOPPViewBase::group_unassigned_2d_, TOPPViewBase::identificationview_behavior_, SpectrumCanvas::IM_LOG, SpectrumCanvas::IM_NONE, SpectrumCanvas::IM_PERCENTAGE, SpectrumCanvas::IM_SNAP, TOPPViewBase::initializeDefaultParameters_(), TOPPViewBase::intensity_button_group_, TOPPViewBase::layer_dock_widget_, TOPPViewBase::layerContextMenu(), TOPPViewBase::layerEdit(), TOPPViewBase::layerFilterVisibilityChange(), TOPPViewBase::layers_view_, TOPPViewBase::layerSelectionChange(), TOPPViewBase::layerStatistics(), TOPPViewBase::layerVisibilityChange(), TOPPViewBase::linkZoom(), TOPPViewBase::linkZoom_action_, TOPPViewBase::loadPreferences(), TOPPViewBase::log_, TOPPViewBase::logContextMenu(), TOPPViewBase::message_label_, TOPPViewBase::metadataFileDialog(), TOPPViewBase::mz_label_, LayerData::NamesOfLabelType, TOPPViewBase::openExampleDialog(), TOPPViewBase::openFileDialog(), TOPPViewBase::openRecentFile(), DefaultParamHandler::param_, TOPPViewBase::preferencesDialog(), TOPPViewBase::projections_2d_, TOPPViewBase::recent_actions_, EnhancedTabBar::removeId(), TOPPViewBase::rerunTOPPTool(), TOPPViewBase::resetZoom(), TOPPViewBase::rt_label_, TOPPViewBase::saveLayerAll(), TOPPViewBase::saveLayerVisible(), TOPPViewBase::setDrawMode1D(), TOPPViewBase::setIntensityMode(), TOPPViewBase::showAboutDialog(), TOPPViewBase::showGoToDialog(), TOPPViewBase::showPreferences(), TOPPViewBase::showSpectrumAlignmentDialog(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::showSpectrumGenerationDialog(), TOPPViewBase::showSpectrumMetaData(), TOPPViewBase::showTOPPDialog(), TOPPViewBase::showURL(), LayerData::SIZE_OF_LABEL_TYPE, TOPPViewBase::spectra_identification_view_widget_, TOPPViewBase::spectra_view_widget_, TOPPViewBase::spectraview_behavior_, TOPPViewBase::tab_bar_, TOPPViewBase::tileHorizontal(), TOPPViewBase::tileVertical(), TOPPViewBase::toggleAxisLegends(), TOPPViewBase::toggleGridLines(), TOPPViewBase::toggleInterestingMZs(), TOPPViewBase::toggleProjections(), TOPPViewBase::tool_bar_, TOPPViewBase::tool_bar_1d_, TOPPViewBase::tool_bar_2d_cons_, TOPPViewBase::tool_bar_2d_feat_, TOPPViewBase::tool_bar_2d_ident_, TOPPViewBase::tool_bar_2d_peak_, TOPPViewBase::topp_, TOPPViewBase::updateCurrentPath(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateTabBar(), TOPPViewBase::updateToolBar(), TOPPViewBase::updateViewBar(), TOPPViewBase::viewChanged(), TOPPViewBase::views_dockwidget_, TOPPViewBase::views_tabwidget_, TOPPViewBase::viewTabwidgetDoubleClicked(), TOPPViewBase::watcher_, TOPPViewBase::ws_, and TOPPViewBase::zoom_together_.
~TOPPViewBase()
~TOPPViewBase () override
Destructor.
References TOPPViewBase::abortTOPPTool(), TOPPViewBase::identificationview_behavior_, TOPPViewBase::savePreferences(), and TOPPViewBase::spectraview_behavior_.
Member Function Documentation
abortTOPPTool
void abortTOPPTool () protected slot
aborts the execution of a TOPP tool
References TOPPViewBase::log_, TOPPViewBase::topp_, and TOPPViewBase::updateMenu().
Referenced by TOPPViewBase::~TOPPViewBase().
addData()
void addData (FeatureMapSharedPtrType feature_map, ConsensusMapSharedPtrType consensus_map, std::vector< PeptideIdentification > & peptides, ExperimentSharedPtrType peak_map, ODExperimentSharedPtrType on_disc_peak_map, LayerData::DataType data_type, bool show_as_1d, bool show_options, bool as_new_window = true, const String & filename = "", const String & caption = "", UInt window_id = 0, Size spectrum_id = 0)
Adds a peak or feature map to the viewer.
Parameters
feature_map The feature data (empty if not feature data)
consensus_map The consensus feature data (empty if not consensus feature data)
peptides The peptide identifications (empty if not ID data)
peak_map The peak data (empty if not peak data)
on_disc_peak_map The peak data managed on disc (empty if not peak data)
data_type Type of the data
show_as_1d Force dataset to be opened in 1D mode (even if it contains several spectra)
show_options If the options dialog should be shown (otherwise the defaults are used)
filename source file name (if the data came from a file)
caption Sets the layer name and window caption of the data. If unset the file name is used. If set, the file is not monitored for changes.
window_id in which window the file is opened if opened as a new layer (0 or default equals current
spectrum_id determines the spectrum to show in 1D view.
add filter
References Spectrum1DCanvas::activateSpectrum(), DataFilters::add(), SpectrumCanvas::addLayer(), Spectrum1DWidget::canvas(), SpectrumWidget::canvas(), TOPPViewOpenDialog::disableCutoff(), TOPPViewOpenDialog::disableDimension(), TOPPViewOpenDialog::disableLocation(), LayerData::DT_CONSENSUS, LayerData::DT_FEATURE, LayerData::DT_IDENT, TOPPViewBase::estimateNoiseFromRandomMS1Scans(), DataFilters::DataFilter::field, TOPPViewBase::getActiveSpectrumWidget(), SpectrumCanvas::getCurrentLayer(), SpectrumCanvas::getLayer(), SpectrumCanvas::getLayerCount(), TOPPViewOpenDialog::getMergeLayer(), LayerData::getPeakData(), TOPPViewBase::getSpectrumParameters(), Param::getValue(), DataFilters::GREATER_EQUAL, TOPPViewBase::hasMS1Zeros(), DataFilters::INTENSITY, TOPPViewOpenDialog::isCutoffEnabled(), TOPPViewOpenDialog::isDataDIA(), Spectrum2DCanvas::mergeIntoLayer(), LayerData::name, DataFilters::DataFilter::op, TOPPViewOpenDialog::openAsNewWindow(), DefaultParamHandler::param_, SpectrumCanvas::setFilters(), TOPPViewOpenDialog::setMergeLayers(), TOPPViewBase::showSpectrumWidgetInWindow(), LayerData::type, TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), DataFilters::DataFilter::value, TOPPViewOpenDialog::viewMapAs1D(), TOPPViewOpenDialog::viewMapAs2D(), TOPPViewBase::views_tabwidget_, TOPPViewBase::window_(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::addDataFile(), TOPPViewBase::copyLayer(), and TOPPViewBase::showSpectrumGenerationDialog().
addDataFile()
void addDataFile (const String & filename, bool show_options, bool add_to_recent, String caption = "", UInt window_id = 0, Size spectrum_id = 0)
Opens and displays data from a file.
Loads the data and adds it to the application by calling addData_()
Parameters
filename The file to open
show_options If the options dialog should be shown (otherwise the defaults are used)
caption Sets the layer name and window caption of the data. If unset the file name is used.
add_to_recent If the file should be added to the recent files after opening
window_id in which window the file is opened if opened as a new layer (0 or default equals current window).
spectrum_id determines the spectrum to show in 1D view.
References File::absolutePath(), TOPPViewBase::addData(), FileWatcher::addFile(), TOPPViewBase::addRecentFile_(), File::basename(), FileTypes::CONSENSUSXML, TOPPViewBase::containsMS1Scans(), LayerData::DT_CHROMATOGRAM, LayerData::DT_CONSENSUS, LayerData::DT_FEATURE, LayerData::DT_IDENT, LayerData::DT_PEAK, File::exists(), FileTypes::FEATUREXML, IndexedMzMLHandler::getNrChromatograms(), IndexedMzMLHandler::getNrSpectra(), IndexedMzMLHandler::getParsingSuccess(), FileHandler::getType(), Param::getValue(), ProgressLogger::GUI, FileTypes::IDXML, FileTypes::INI, OpenMS::Constants::k, ConsensusXMLFile::load(), MzIdentMLFile::load(), IdXMLFile::load(), FeatureXMLFile::load(), FileHandler::loadExperiment(), TOPPViewBase::LS_ERROR, TOPPViewBase::LS_WARNING, FileTypes::MZIDENTML, FileTypes::MZML, IndexedMzMLHandler::openFile(), OPENMS_LOG_INFO, DefaultParamHandler::param_, File::removeExtension(), TOPPViewBase::showLogMessage_(), FileTypes::typeToName(), FileTypes::UNKNOWN, TOPPViewBase::watcher_, and BaseException::what().
Referenced by TOPPViewBase::copyLayer(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::loadFile(), TOPPViewBase::loadFiles(), TOPPViewBase::openExampleDialog(), TOPPViewBase::openFileDialog(), and TOPPViewBase::openRecentFile().
addRecentFile_()
void addRecentFile_ (const String & filename) protected
adds a Filename to the recent files
References File::absolutePath(), Param::getValue(), DefaultParamHandler::param_, TOPPViewBase::recent_files_, String::toQString(), and TOPPViewBase::updateRecentMenu_().
Referenced by TOPPViewBase::addDataFile().
annotateMS1FromMassFingerprinting_()
bool annotateMS1FromMassFingerprinting_ (const FeatureMap & identifications) protected
add annotations from an AccurateMassSearch to an MS1 spectrum
Returns
true on success, otherwise false
References IDMapper::annotate(), LayerData::DT_PEAK, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), DefaultParamHandler::getParameters(), LayerData::getPeakDataMuteable(), TOPPViewBase::LS_NOTICE, DefaultParamHandler::setParameters(), Param::setValue(), TOPPViewBase::showLogMessage_(), and LayerData::type.
Referenced by TOPPViewBase::annotateWithID().
annotateWithID
void annotateWithID () slot
Annotates current layer with ID data.
References IDMapper::annotate(), TOPPViewBase::annotateMS1FromMassFingerprinting_(), TOPPViewBase::current_path_, LayerData::DT_FEATURE, LayerData::DT_PEAK, FileTypes::FEATUREXML, TOPPViewBase::getActiveCanvas(), LayerData::getConsensusMap(), SpectrumCanvas::getCurrentLayer(), DefaultParamHandler::getDefaults(), LayerData::getFeatureMap(), LayerData::getPeakDataMuteable(), FeatureMap::getProteinIdentifications(), FileHandler::getType(), FileTypes::IDXML, MzIdentMLFile::load(), IdXMLFile::load(), FeatureXMLFile::load(), TOPPViewBase::LS_NOTICE, FileTypes::MZIDENTML, DefaultParamHandler::setParameters(), Param::setValue(), TOPPViewBase::showLogMessage_(), String::toQString(), LayerData::type, TOPPViewBase::updateViewBar(), TOPPViewBase::views_tabwidget_, LayerData::visible, and BaseException::what().
Referenced by TOPPViewBase::TOPPViewBase().
changeLabel
void changeLabel (QAction * action) slot
References Spectrum2DWidget::canvas(), TOPPViewBase::dm_label_2d_, TOPPViewBase::getActive2DWidget(), TOPPViewBase::getCurrentLayer(), LayerData::L_INDEX, LayerData::L_NONE, LayerData::NamesOfLabelType, SpectrumCanvas::setLabel(), LayerData::SIZE_OF_LABEL_TYPE, and TOPPViewBase::updateToolBar().
Referenced by TOPPViewBase::TOPPViewBase().
changeLayerFlag
void changeLayerFlag (bool on) slot
References LayerData::C_ELEMENTS, TOPPViewBase::dm_elements_2d_, TOPPViewBase::dm_hull_2d_, TOPPViewBase::dm_hulls_2d_, TOPPViewBase::dm_ident_2d_, TOPPViewBase::dm_precursors_2d_, LayerData::F_HULL, LayerData::F_HULLS, TOPPViewBase::getActive2DWidget(), LayerData::I_PEPTIDEMZ, and LayerData::P_PRECURSORS.
Referenced by TOPPViewBase::TOPPViewBase().
changeUnassigned
void changeUnassigned (QAction * action) slot
References Spectrum2DWidget::canvas(), TOPPViewBase::dm_unassigned_2d_, LayerData::F_UNASSIGNED, TOPPViewBase::getActive2DWidget(), SpectrumCanvas::getLayerFlag(), LayerData::I_LABELS, LayerData::I_PEPTIDEMZ, SpectrumCanvas::setLayerFlag(), and TOPPViewBase::updateToolBar().
Referenced by TOPPViewBase::TOPPViewBase().
checkPreferences_()
void checkPreferences_ () protected
check if all available preferences get set by the .ini file. If there are some missing entries fill them with default values.
closeByTab
void closeByTab (int id) protected slot
Closes the window corresponding to the data of the tab with identifier id.
References TOPPViewBase::updateMenu(), and TOPPViewBase::window_().
Referenced by TOPPViewBase::TOPPViewBase().
closeEvent()
void closeEvent (QCloseEvent * event) override protected
References TOPPViewBase::ws_.
closeFile
void closeFile () slot
closes the active window
References TOPPViewBase::updateMenu(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::TOPPViewBase().
containsIMData()
bool containsIMData (const MSSpectrum & s) static
Returns true if contains ion mobility data.
References MSSpectrum::getFloatDataArrays().
Referenced by TOPPViewBase::showCurrentPeaksAsIonMobility().
containsMS1Scans()
bool containsMS1Scans (const ExperimentType & exp) static
Returns true if contains at least one MS1 spectrum.
References MSExperiment::size().
Referenced by TOPPViewBase::addDataFile(), TOPPViewBase::estimateNoiseFromRandomMS1Scans(), and TOPPViewBase::hasMS1Zeros().
copyLayer
void copyLayer (const QMimeData * data, QWidget * source, int id = -1) protected slot
Slot for drag-and-drop of layer manager to tabbar.
References TOPPViewBase::addData(), TOPPViewBase::addDataFile(), MSExperiment::addSpectrum(), LayerData::DT_CHROMATOGRAM, LayerData::filename, TOPPViewBase::getActiveCanvas(), LayerData::getConsensusMap(), SpectrumCanvas::getCurrentLayer(), LayerData::getFeatureMap(), LayerData::getOnDiscPeakData(), LayerData::getPeakData(), LayerData::getPeakDataMuteable(), SpectraViewWidget::getTreeWidget(), TOPPViewBase::layers_view_, TOPPViewBase::LS_ERROR, LayerData::name, LayerData::peptides, TOPPViewBase::showLogMessage_(), TOPPViewBase::spectra_view_widget_, LayerData::type, and BaseException::what().
Referenced by TOPPViewBase::showSpectrumWidgetInWindow(), and TOPPViewBase::TOPPViewBase().
editMetadata
void editMetadata () slot
lets the user edit the meta data of a layer
References TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), TOPPViewBase::LS_NOTICE, TOPPViewBase::showLogMessage_(), SpectrumCanvas::showMetaData(), and LayerData::visible.
Referenced by TOPPViewBase::TOPPViewBase().
enhancedWorkspaceWindowChanged
void enhancedWorkspaceWindowChanged (int id) protected slot
Raises the window corresponding to the data of the tab with identifier id.
References SpectrumWidget::canvas(), SpectrumCanvas::getCurrentLayer(), SpectrumCanvas::getLayerCount(), LayerData::getPeakData(), TOPPViewBase::hasPeptideIdentifications(), TOPPViewBase::views_tabwidget_, and TOPPViewBase::window_().
Referenced by TOPPViewBase::showSpectrumWidgetInWindow(), and TOPPViewBase::TOPPViewBase().
estimateNoiseFromRandomMS1Scans()
float estimateNoiseFromRandomMS1Scans (const ExperimentType & exp, UInt n_scans = 10)
Estimates the noise by evaluating n_scans random scans of MS level 1. Assumes that 4/5 of intensities is noise.
References TOPPViewBase::containsMS1Scans(), MSExperiment::end(), and MSExperiment::size().
Referenced by TOPPViewBase::addData().
fileChanged_
void fileChanged_ (const String & filename) protected slot
Called if a data file has been externally changed.
References FileWatcher::addFile(), SpectrumWidget::canvas(), LayerData::DT_CHROMATOGRAM, LayerData::DT_CONSENSUS, LayerData::DT_FEATURE, LayerData::DT_PEAK, LayerData::filename, LayerData::getConsensusMap(), LayerData::getFeatureMap(), SpectrumCanvas::getLayer(), SpectrumCanvas::getLayerCount(), LayerData::getPeakDataMuteable(), Param::getValue(), ConsensusXMLFile::load(), FileHandler::loadExperiment(), FileHandler::loadFeatures(), DefaultParamHandler::param_, FileWatcher::removeFile(), String::toQString(), LayerData::type, TOPPViewBase::updateFilterBar(), SpectrumCanvas::updateLayer(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), TOPPViewBase::watcher_, TOPPViewBase::watcher_msgbox_, BaseException::what(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::TOPPViewBase().
filterContextMenu
void filterContextMenu (const QPoint & pos) protected slot
slot for filter manager context menu
References DataFilters::add(), TOPPViewBase::filterEdit(), LayerData::filters, TOPPViewBase::filters_, TOPPViewBase::getActiveCanvas(), TOPPViewBase::getCurrentLayer(), SpectrumCanvas::getCurrentLayer(), LayerData::name, DataFilters::remove(), SpectrumCanvas::setFilters(), String::toQString(), and TOPPViewBase::updateFilterBar().
Referenced by TOPPViewBase::TOPPViewBase().
filterEdit
void filterEdit (QListWidgetItem * item) protected slot
slot for editing a filter
References LayerData::filters, TOPPViewBase::filters_, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), DataFilters::replace(), SpectrumCanvas::setFilters(), and TOPPViewBase::updateFilterBar().
Referenced by TOPPViewBase::filterContextMenu(), and TOPPViewBase::TOPPViewBase().
finishTOPPToolExecution
void finishTOPPToolExecution (int exitCode, QProcess::ExitStatus exitStatus) protected slot
slot for the finished signal of the TOPP tools execution
References TOPPViewBase::addDataFile(), Param::getValue(), TOPPViewBase::log_, TOPPViewBase::LS_ERROR, TOPPViewBase::LS_NOTICE, DefaultParamHandler::param_, File::readable(), File::remove(), TOPPViewBase::showLogMessage_(), TOPPViewBase::topp_, String::toQString(), DataValue::toString(), and TOPPViewBase::updateMenu().
Referenced by TOPPViewBase::runTOPPTool_().
getActive1DWidget()
Spectrum1DWidget * getActive1DWidget () const
returns a pointer to the active Spectrum1DWidget (0 the active window is no Spectrum1DWidget or there is no active window)
References TOPPViewBase::getActiveSpectrumWidget().
Referenced by TOPPViewBase::layerContextMenu(), TOPPViewBase::setDrawMode1D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showSpectrumAlignmentDialog(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::tileHorizontal(), TOPPViewBase::tileVertical(), TOPPViewBase::toggleInterestingMZs(), TOPPViewBase::updateMenu(), and TOPPViewBase::updateToolBar().
getActive2DWidget()
Spectrum2DWidget * getActive2DWidget () const
returns a pointer to the active Spectrum2DWidget (0 the active window is no Spectrum2DWidget or there is no active window)
References TOPPViewBase::getActiveSpectrumWidget().
Referenced by TOPPViewBase::changeLabel(), TOPPViewBase::changeLayerFlag(), TOPPViewBase::changeUnassigned(), TOPPViewBase::loadFiles(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::tileHorizontal(), TOPPViewBase::tileVertical(), TOPPViewBase::toggleProjections(), TOPPViewBase::updateToolBar(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
getActive3DWidget()
Spectrum3DWidget * getActive3DWidget () const
returns a pointer to the active Spectrum3DWidget (0 the active window is no Spectrum2DWidget or there is no active window)
References TOPPViewBase::getActiveSpectrumWidget().
Referenced by TOPPViewBase::loadFiles(), and TOPPViewBase::updateToolBar().
getActiveCanvas()
SpectrumCanvas * getActiveCanvas () const
returns a pointer to the active SpectrumCanvas (0 if none is active)
References SpectrumWidget::canvas(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::annotateMS1FromMassFingerprinting_(), TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::editMetadata(), TOPPViewBase::filterContextMenu(), TOPPViewBase::filterEdit(), TOPPViewBase::getCurrentLayer(), TOPPViewBase::layerContextMenu(), TOPPViewBase::layerEdit(), TOPPViewBase::layerFilterVisibilityChange(), TOPPViewBase::layerSelectionChange(), TOPPViewBase::layerVisibilityChange(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::loadFiles(), TOPPViewBase::rerunTOPPTool(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::saveLayerAll(), TOPPViewBase::saveLayerVisible(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), TOPPViewBase::showPreferences(), TOPPViewBase::showSpectrumMetaData(), TOPPViewBase::showTOPPDialog_(), TOPPViewBase::toggleGridLines(), TOPPViewBase::updateCurrentPath(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), and TOPPViewBase::updateViewBar().
getActiveSpectrumWidget()
SpectrumWidget * getActiveSpectrumWidget () const
returns a pointer to the active SpectrumWidget (0 if none is active)
References TOPPViewBase::ws_.
Referenced by TOPPViewBase::addData(), TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), TOPPViewBase::getActive3DWidget(), TOPPViewBase::layerContextMenu(), TOPPViewBase::layerStatistics(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::loadFiles(), TOPPViewBase::resetZoom(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::setIntensityMode(), TOPPViewBase::showGoToDialog(), TOPPViewBase::toggleAxisLegends(), TOPPViewBase::updateToolBar(), and TOPPViewBase::viewTabwidgetDoubleClicked().
getCurrentLayer()
const LayerData * getCurrentLayer () const
Returns the active Layer data (0 if no layer is active)
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::getCurrentLayer().
Referenced by TOPPViewBase::changeLabel(), TOPPViewBase::filterContextMenu(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::showTOPPDialog_(), TOPPViewBase::updateCurrentPath(), and TOPPViewBase::updateFilterBar().
getFileList_()
QStringList getFileList_ (const String & path_overwrite = "") protected
Shows a dialog where the user can select files.
References TOPPViewBase::current_path_, String::toQString(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::metadataFileDialog(), TOPPViewBase::openExampleDialog(), and TOPPViewBase::openFileDialog().
getFilenamesOfOpenFiles_()
std::set< String > getFilenamesOfOpenFiles_ () protected
unique list of files referenced by all layers
References SpectrumWidget::canvas(), LayerData::filename, SpectrumCanvas::getLayer(), SpectrumCanvas::getLayerCount(), and TOPPViewBase::ws_.
getSpectraIdentificationViewWidget()
SpectraIdentificationViewWidget * getSpectraIdentificationViewWidget ()
returns a pointer to the SpectraIdentificationViewWidget
References TOPPViewBase::spectra_identification_view_widget_.
getSpectrumParameters()
Param getSpectrumParameters (UInt dim)
Returns the parameters for a SpectrumCanvas of dimension dim.
References Param::copy(), Param::getValue(), DefaultParamHandler::param_, Param::setValue(), and DataValue::toString().
Referenced by TOPPViewBase::addData(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
getWorkspace()
EnhancedWorkspace * getWorkspace () const
returns a pointer to the EnhancedWorkspace containing SpectrumWidgets
References TOPPViewBase::ws_.
hasMS1Zeros()
bool hasMS1Zeros (const ExperimentType & exp) static
Returns true of experiment has at least one exact zero valued peak in any of its MS1 spectra.
References TOPPViewBase::containsMS1Scans(), and MSExperiment::size().
Referenced by TOPPViewBase::addData().
hasPeptideIdentifications()
bool hasPeptideIdentifications (const ExperimentType & map) static
Returns true if the experiment map contains peptide identifications.
References MSExperiment::empty(), and MSExperiment::size().
Referenced by TOPPViewBase::enhancedWorkspaceWindowChanged().
initializeDefaultParameters_()
void initializeDefaultParameters_ () protected
Initializes the default parameters on TOPPView construction.
References DefaultParamHandler::defaults_, DefaultParamHandler::getDefaults(), Param::insert(), Param::setMaxInt(), Param::setMinInt(), Param::setSectionDescription(), Param::setValidStrings(), Param::setValue(), and DefaultParamHandler::subsections_.
Referenced by TOPPViewBase::TOPPViewBase().
layerActivated
void layerActivated () slot
gets called if a layer got activated
References TOPPViewBase::updateCurrentPath(), TOPPViewBase::updateToolBar(), and TOPPViewBase::updateViewBar().
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
layerContextMenu
void layerContextMenu (const QPoint & pos) protected slot
slot for layer manager context menu
References Spectrum1DWidget::canvas(), Spectrum1DCanvas::flipLayer(), Spectrum1DCanvas::flippedLayersExist(), TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActiveCanvas(), TOPPViewBase::getActiveSpectrumWidget(), SpectrumCanvas::getLayer(), TOPPViewBase::layers_view_, LayerData::name, SpectrumCanvas::removeLayer(), SpectrumCanvas::setLayerName(), Spectrum1DCanvas::setMirrorModeActive(), SpectrumCanvas::showCurrentLayerPreferences(), TOPPViewBase::tab_bar_, String::toQString(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), and TOPPViewBase::updateViewBar().
Referenced by TOPPViewBase::TOPPViewBase().
layerDeactivated
void layerDeactivated () slot
gets called if a layer got deactivated
layerEdit
void layerEdit (QListWidgetItem *) protected slot
slot for editing the preferences of the current layer
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::showCurrentLayerPreferences().
Referenced by TOPPViewBase::TOPPViewBase().
layerFilterVisibilityChange
void layerFilterVisibilityChange (bool on) protected slot
Enables/disables the data filters for the current layer.
References SpectrumCanvas::changeLayerFilterState(), and TOPPViewBase::getActiveCanvas().
Referenced by TOPPViewBase::TOPPViewBase().
layerSelectionChange
void layerSelectionChange (int i) protected slot
slot for layer manager selection change
References SpectrumCanvas::activateLayer(), TOPPViewBase::getActiveCanvas(), and TOPPViewBase::updateFilterBar().
Referenced by TOPPViewBase::TOPPViewBase().
layerStatistics
void layerStatistics () slot
Shows statistics (count,min,max,avg) about Intensity, Quality, Charge and meta data.
References TOPPViewBase::getActiveSpectrumWidget(), SpectrumWidget::showStatistics(), and TOPPViewBase::updateFilterBar().
Referenced by TOPPViewBase::TOPPViewBase().
layerVisibilityChange
void layerVisibilityChange (QListWidgetItem * item) protected slot
slot for layer manager visibility change (check box)
References SpectrumCanvas::changeVisibility(), TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getLayer(), TOPPViewBase::layers_view_, and LayerData::visible.
Referenced by TOPPViewBase::TOPPViewBase().
layerZoomChanged
void layerZoomChanged () slot
gets called when a layer changes in zoom
References Spectrum1DWidget::canvas(), Spectrum2DWidget::canvas(), SpectrumWidget::canvas(), LayerData::DT_CHROMATOGRAM, TOPPViewBase::getActiveCanvas(), TOPPViewBase::getActiveSpectrumWidget(), TOPPViewBase::getCurrentLayer(), SpectrumCanvas::getCurrentLayer(), LayerData::getPeakData(), SpectrumCanvas::getVisibleArea(), DIntervalBase< D >::maxX(), DIntervalBase< D >::maxY(), DIntervalBase< D >::minX(), DIntervalBase< D >::minY(), DIntervalBase< D >::setMaxX(), DIntervalBase< D >::setMinX(), SpectrumCanvas::setVisibleArea(), LayerData::type, TOPPViewBase::ws_, and TOPPViewBase::zoom_together_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
linkZoom
void linkZoom () slot
link the zoom of individual windows
References TOPPViewBase::linkZoom_action_, and TOPPViewBase::zoom_together_.
Referenced by TOPPViewBase::TOPPViewBase().
loadFile
void loadFile (QString filename) slot
Loads a file given by the passed string.
References TOPPViewBase::addDataFile().
loadFiles()
void loadFiles (const StringList & list, QSplashScreen * splash_screen)
Opens all the files in the string list.
References TOPPViewBase::addDataFile(), TOPPViewBase::getActive2DWidget(), TOPPViewBase::getActive3DWidget(), TOPPViewBase::getActiveCanvas(), TOPPViewBase::getActiveSpectrumWidget(), SpectrumCanvas::getCurrentLayer(), LayerData::param, SpectrumCanvas::setCurrentLayerParameters(), and Param::setValue().
Referenced by main().
loadPreferences()
void loadPreferences (String filename = "")
Loads the preferences from the filename given.
If the filename is empty, the application name + ".ini" is used as filename
References Param::begin(), Param::copy(), Param::end(), File::exists(), Param::exists(), Param::getValue(), VersionInfo::getVersion(), ParamXMLFile::load(), DefaultParamHandler::param_, TOPPViewBase::recent_files_, DefaultParamHandler::setParameters(), Param::setValue(), Param::size(), String::toQString(), DataValue::toString(), and TOPPViewBase::updateRecentMenu_().
Referenced by main(), and TOPPViewBase::TOPPViewBase().
logContextMenu
void logContextMenu (const QPoint & pos) protected slot
slot for log window context menu
References TOPPViewBase::log_.
Referenced by TOPPViewBase::TOPPViewBase().
metadataFileDialog
void metadataFileDialog () slot
dialog for inspecting database meta data
References MetaDataBrowser::add(), TOPPViewBase::getFileList_(), FileHandler::getOptions(), FileHandler::loadExperiment(), PeakFileOptions::setMetadataOnly(), and BaseException::what().
Referenced by TOPPViewBase::TOPPViewBase().
openExampleDialog
void openExampleDialog () slot
shows the file dialog for opening example files
References TOPPViewBase::addDataFile(), TOPPViewBase::getFileList_(), and File::getOpenMSDataPath().
Referenced by TOPPViewBase::TOPPViewBase().
openFileDialog
void openFileDialog () slot
shows the file dialog for opening files
References TOPPViewBase::addDataFile(), and TOPPViewBase::getFileList_().
Referenced by TOPPViewBase::TOPPViewBase().
openRecentFile
void openRecentFile () protected slot
Opens a file from the recent files menu.
References TOPPViewBase::addDataFile().
Referenced by TOPPViewBase::TOPPViewBase().
preferencesDialog
void preferencesDialog () slot
shows the preferences dialog
References Param::getValue(), TOPPViewBase::LS_ERROR, DefaultParamHandler::param_, TOPPViewBase::savePreferences(), Param::setValue(), TOPPViewBase::showLogMessage_(), DataValue::toBool(), and DataValue::toQString().
Referenced by TOPPViewBase::TOPPViewBase().
rerunTOPPTool
void rerunTOPPTool () protected slot
returns the last invoked TOPP tool with the same parameters
References TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), TOPPViewBase::LS_NOTICE, File::remove(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showLogMessage_(), TOPPViewBase::topp_, and LayerData::visible.
Referenced by TOPPViewBase::TOPPViewBase().
resetZoom
void resetZoom () slot
References SpectrumWidget::canvas(), TOPPViewBase::getActiveSpectrumWidget(), and SpectrumCanvas::resetZoom().
Referenced by TOPPViewBase::TOPPViewBase().
runTOPPTool_()
void runTOPPTool_ () protected
Runs the TOPP tool according to the information in topp_.
References LayerData::chromatogram_flag_set(), LayerData::DT_CHROMATOGRAM, LayerData::DT_FEATURE, LayerData::DT_PEAK, File::findSiblingTOPPExecutable(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::getActiveCanvas(), TOPPViewBase::getActiveSpectrumWidget(), LayerData::getConsensusMap(), SpectrumCanvas::getCurrentLayer(), LayerData::getCurrentSpectrumIndex(), LayerData::getFeatureMap(), LayerData::getPeakData(), SpectrumCanvas::getVisibleConsensusData(), SpectrumCanvas::getVisibleFeatureData(), SpectrumCanvas::getVisiblePeakData(), SpectrumWidget::getWindowId(), ProgressLogger::GUI, TOPPViewBase::LS_ERROR, TOPPViewBase::LS_NOTICE, LayerData::name, LayerData::remove_chromatogram_flag(), ProgressLogger::setLogType(), TOPPViewBase::showLogMessage_(), ConsensusXMLFile::store(), FeatureXMLFile::store(), MzMLFile::store(), TOPPViewBase::topp_, String::toQString(), LayerData::type, TOPPViewBase::updateMenu(), TOPPViewBase::updateProcessLog(), and File::writable().
Referenced by TOPPViewBase::rerunTOPPTool(), and TOPPViewBase::showTOPPDialog_().
saveLayerAll
void saveLayerAll () slot
Saves the whole current layer data.
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::saveCurrentLayer().
Referenced by TOPPViewBase::TOPPViewBase().
saveLayerVisible
void saveLayerVisible () slot
Saves the visible layer data.
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::saveCurrentLayer().
Referenced by TOPPViewBase::TOPPViewBase().
savePreferences()
void savePreferences ()
Stores the preferences (used when this window is closed)
References Param::copy(), Param::getValue(), VersionInfo::getVersion(), DefaultParamHandler::param_, TOPPViewBase::recent_files_, Param::removeAll(), Param::setValue(), and ParamXMLFile::store().
Referenced by TOPPViewBase::preferencesDialog(), and TOPPViewBase::~TOPPViewBase().
setDrawMode1D
void setDrawMode1D (int index) slot
References Spectrum1DWidget::canvas(), TOPPViewBase::getActive1DWidget(), and Spectrum1DCanvas::setDrawMode().
Referenced by TOPPViewBase::showSpectrumGenerationDialog(), and TOPPViewBase::TOPPViewBase().
setIntensityMode
void setIntensityMode (int index) slot
References TOPPViewBase::getActiveSpectrumWidget(), TOPPViewBase::intensity_button_group_, and SpectrumWidget::setIntensityMode().
Referenced by TOPPViewBase::showCurrentPeaksAs3D(), and TOPPViewBase::TOPPViewBase().
showAboutDialog
void showAboutDialog () slot
Shows the 'About' dialog.
References QApplicationTOPP::showAboutDialog().
Referenced by TOPPViewBase::TOPPViewBase().
showCurrentPeaksAs2D
void showCurrentPeaksAs2D () slot
Shows the current peak data of the active layer in 2D.
References SpectrumCanvas::activeLayerIndex(), SpectrumCanvas::addLayer(), Spectrum2DWidget::canvas(), TOPPViewBase::CAPTION_3D_SUFFIX_, LayerData::filename, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), LayerData::getOnDiscPeakData(), LayerData::getPeakDataMuteable(), TOPPViewBase::getSpectrumParameters(), String::hasSuffix(), LayerData::name, String::prefix(), SpectrumCanvas::setLayerName(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showCurrentPeaksAs3D
void showCurrentPeaksAs3D () slot
Shows the current peak data of the active layer in 3D.
References SpectrumCanvas::activeLayerIndex(), SpectrumCanvas::addLayer(), Spectrum3DWidget::canvas(), TOPPViewBase::CAPTION_3D_SUFFIX_, LayerData::DT_PEAK, LayerData::filename, TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayerIndex(), SpectrumCanvas::getLayerCount(), LayerData::getPeakDataMuteable(), TOPPViewBase::getSpectrumParameters(), SpectrumCanvas::IM_SNAP, LayerData::isIonMobilityData(), TOPPViewBase::LS_NOTICE, LayerData::name, Spectrum3DCanvas::openglwidget(), TOPPViewBase::setIntensityMode(), SpectrumCanvas::setLayerName(), SpectrumCanvas::setVisibleArea(), Spectrum3DOpenGLCanvas::setYLabel(), TOPPViewBase::showLogMessage_(), TOPPViewBase::showSpectrumWidgetInWindow(), LayerData::type, TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showCurrentPeaksAsDIA
void showCurrentPeaksAsDIA () slot
Shows the current peak data of the active layer as DIA data.
References SpectrumCanvas::activeLayerIndex(), SpectrumCanvas::addLayer(), Spectrum2DWidget::canvas(), TOPPViewBase::CAPTION_3D_SUFFIX_, LayerData::filename, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), LayerData::getCurrentSpectrum(), LayerData::getOnDiscPeakData(), LayerData::getPeakData(), SpectrumSettings::getPrecursors(), TOPPViewBase::getSpectrumParameters(), String::hasSuffix(), LayerData::isDIAData(), OpenMS::Constants::k, LayerData::name, String::prefix(), SpectrumCanvas::setLayerName(), MSSpectrum::setMSLevel(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showCurrentPeaksAsIonMobility
void showCurrentPeaksAsIonMobility () slot
Shows the current peak data of the active layer as ion mobility.
References SpectrumCanvas::activeLayerIndex(), SpectrumCanvas::addLayer(), Spectrum2DWidget::canvas(), TOPPViewBase::CAPTION_3D_SUFFIX_, TOPPViewBase::containsIMData(), LayerData::filename, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getCurrentLayer(), LayerData::getCurrentSpectrum(), LayerData::getCurrentSpectrumIndex(), MSSpectrum::getFloatDataArrays(), TOPPViewBase::getSpectrumParameters(), String::hasSuffix(), SpectrumWidget::IM_MS_AXIS_TITLE, SpectrumWidget::IM_ONEKZERO_AXIS_TITLE, OpenMS::Constants::k, LayerData::name, String::prefix(), SpectrumCanvas::setLayerName(), AxisWidget::setLegend(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::updateFilterBar(), TOPPViewBase::updateLayerBar(), TOPPViewBase::updateMenu(), TOPPViewBase::updateViewBar(), TOPPViewBase::ws_, and SpectrumWidget::xAxis().
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showCursorStatus
void showCursorStatus (double mz, double rt) slot
shows m/z and rt in the status bar
References TOPPViewBase::message_label_, TOPPViewBase::mz_label_, String::number(), and TOPPViewBase::rt_label_.
Referenced by TOPPViewBase::showCursorStatusInvert(), and TOPPViewBase::showSpectrumWidgetInWindow().
showCursorStatusInvert
void showCursorStatusInvert (double mz, double rt) slot
shows m/z and rt in the status bar (inverting RT and m/z)
References TOPPViewBase::showCursorStatus().
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showGoToDialog
void showGoToDialog () slot
shows the DB dialog for opening files
References TOPPViewBase::getActiveSpectrumWidget(), and SpectrumWidget::showGoToDialog().
Referenced by TOPPViewBase::TOPPViewBase().
showLogMessage_()
void showLogMessage_ (TOPPViewBase::LogState state, const String & heading, const String & body) protected
Shows a log message in the log_ window.
References DateTime::getTime(), TOPPViewBase::log_, TOPPViewBase::LS_ERROR, TOPPViewBase::LS_NOTICE, TOPPViewBase::LS_WARNING, DateTime::now(), and String::toQString().
Referenced by TOPPViewBase::addDataFile(), TOPPViewBase::annotateMS1FromMassFingerprinting_(), TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::editMetadata(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::preferencesDialog(), TOPPViewBase::rerunTOPPTool(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showTOPPDialog_(), and TOPPViewBase::updateToolBar().
showPreferences
void showPreferences () slot
Shows current layer preferences.
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::showCurrentLayerPreferences().
Referenced by TOPPViewBase::TOPPViewBase().
showSpectrumAlignmentDialog
void showSpectrumAlignmentDialog () slot
Shows the spectrum alignment dialog.
References Spectrum1DWidget::canvas(), SpectrumAlignmentDialog::get1stLayerIndex(), SpectrumAlignmentDialog::get2ndLayerIndex(), TOPPViewBase::getActive1DWidget(), Spectrum1DCanvas::getAlignmentScore(), Spectrum1DCanvas::getAlignmentSize(), SpectrumAlignmentDialog::getTolerance(), SpectrumAlignmentDialog::isPPM(), Spectrum1DCanvas::mirrorModeActive(), Spectrum1DWidget::performAlignment(), and Param::setValue().
Referenced by TOPPViewBase::TOPPViewBase().
showSpectrumAs1D [1/2]
void showSpectrumAs1D (int index) slot
Shows the spectrum with index index of the active layer in 1D.
References TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), TOPPViewBase::identificationview_behavior_, TOPPViewSpectraViewBehavior::showSpectrumAs1D(), TOPPViewIdentificationViewBehavior::showSpectrumAs1D(), TOPPViewBase::spectra_identification_view_widget_, TOPPViewBase::spectra_view_widget_, and TOPPViewBase::spectraview_behavior_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
showSpectrumAs1D [2/2]
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices) slot
References TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), TOPPViewSpectraViewBehavior::showSpectrumAs1D(), TOPPViewBase::spectra_view_widget_, and TOPPViewBase::spectraview_behavior_.
showSpectrumBrowser
void showSpectrumBrowser () protected slot
shows the spectrum browser and updates it
References TOPPViewBase::updateViewBar(), and TOPPViewBase::views_dockwidget_.
showSpectrumGenerationDialog
void showSpectrumGenerationDialog () slot
Shows the theoretical spectrum generation dialog.
References TOPPViewBase::addData(), MSExperiment::addSpectrum(), Spectrum1DCanvas::DM_PEAKS, TOPPViewBase::draw_group_1d_, LayerData::DT_CHROMATOGRAM, AASequence::fromString(), AASequence::getMonoWeight(), TheoreticalSpectrumGenerationDialog::getParam(), TheoreticalSpectrumGenerationDialog::getSequence(), TheoreticalSpectrumGenerator::getSpectrum(), Param::getValue(), Precursor::setCharge(), TOPPViewBase::setDrawMode1D(), MSSpectrum::setMSLevel(), Peak1D::setMZ(), DefaultParamHandler::setParameters(), SpectrumSettings::setPrecursors(), Param::setValue(), DataValue::toBool(), and BaseException::what().
Referenced by TOPPViewBase::TOPPViewBase().
showSpectrumMetaData
void showSpectrumMetaData (int spectrum_index) protected slot
shows the spectrum metadata
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::showMetaData().
Referenced by TOPPViewBase::TOPPViewBase().
showSpectrumWidgetInWindow()
void showSpectrumWidgetInWindow (SpectrumWidget * sw, const String & caption)
Opens the provided spectrum widget in a new window.
References EnhancedTabBar::addTab(), SpectrumWidget::canvas(), TOPPViewBase::copyLayer(), TOPPViewBase::enhancedWorkspaceWindowChanged(), Spectrum2DWidget::getHorizontalProjection(), Spectrum2DWidget::getVerticalProjection(), SpectrumWidget::getWindowId(), TOPPViewBase::layerActivated(), TOPPViewBase::layerZoomChanged(), EnhancedTabBar::setCurrentId(), SpectrumWidget::setWindowId(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), TOPPViewBase::showCursorStatus(), TOPPViewBase::showCursorStatusInvert(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::showStatusMessage(), TOPPViewBase::tab_bar_, String::toQString(), TOPPViewBase::updateLayerBar(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::addData(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
showStatusMessage
void showStatusMessage (std::string msg, OpenMS::UInt time) slot
Shows a status message in the status bar.
If time is 0 the status message is displayed until showStatusMessage is called with an empty message or a new message. Otherwise the message is displayed for time ms.
References TOPPViewBase::message_label_.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
showTOPPDialog
void showTOPPDialog () slot
Apply TOPP tool.
References TOPPViewBase::showTOPPDialog_().
Referenced by TOPPViewBase::TOPPViewBase().
showTOPPDialog_()
void showTOPPDialog_ (bool visible) protected
Apply TOPP tool. If visible is true, only the visible data is used, otherwise the whole layer is used.
References TOPPViewBase::current_path_, TOPPViewBase::getActiveCanvas(), TOPPViewBase::getCurrentLayer(), SpectrumCanvas::getCurrentLayer(), ToolsDialog::getInput(), ToolsDialog::getOutput(), ToolsDialog::getTool(), File::getUniqueName(), Param::getValue(), TOPPViewBase::LS_ERROR, TOPPViewBase::LS_NOTICE, DefaultParamHandler::param_, TOPPViewBase::runTOPPTool_(), TOPPViewBase::showLogMessage_(), TOPPViewBase::topp_, DataValue::toString(), LayerData::visible, and File::writable().
Referenced by TOPPViewBase::showTOPPDialog().
showURL
void showURL () slot
shows the URL stored in the data of the sender QAction
References GUIHelpers::openURL().
Referenced by TOPPViewBase::TOPPViewBase().
tileHorizontal
void tileHorizontal () slot
tile the open windows horizontally
References TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::TOPPViewBase().
tileVertical
void tileVertical () slot
tile the open windows vertically
References TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::TOPPViewBase().
toggleAxisLegends
void toggleAxisLegends () slot
Toggles the axis legends.
References TOPPViewBase::getActiveSpectrumWidget(), and SpectrumWidget::showLegend().
Referenced by TOPPViewBase::TOPPViewBase().
toggleGridLines
void toggleGridLines () slot
Toggles the grid lines.
References TOPPViewBase::getActiveCanvas(), and SpectrumCanvas::showGridLines().
Referenced by TOPPViewBase::TOPPViewBase().
toggleInterestingMZs
void toggleInterestingMZs () slot
Toggles drawing of interesting MZs.
References TOPPViewBase::getActive1DWidget().
Referenced by TOPPViewBase::TOPPViewBase().
toggleProjections
void toggleProjections () slot
References TOPPViewBase::getActive2DWidget(), Spectrum2DWidget::projectionsVisible(), and Spectrum2DWidget::toggleProjections().
Referenced by TOPPViewBase::TOPPViewBase().
updateCurrentPath
void updateCurrentPath () slot
changes the current path according to the currently active window/layer
References TOPPViewBase::current_path_, TOPPViewBase::getActiveCanvas(), TOPPViewBase::getCurrentLayer(), Param::getValue(), DefaultParamHandler::param_, and File::path().
Referenced by TOPPViewBase::layerActivated(), and TOPPViewBase::TOPPViewBase().
updateFilterBar
void updateFilterBar () slot
adapts the filter bar to the active window
References LayerData::filters, TOPPViewBase::filters_, TOPPViewBase::filters_check_box_, TOPPViewBase::getActiveCanvas(), TOPPViewBase::getCurrentLayer(), SpectrumCanvas::getCurrentLayer(), SpectrumCanvas::getLayerCount(), DataFilters::isActive(), DataFilters::size(), and OpenMS::StringConversions::toString().
Referenced by TOPPViewBase::addData(), TOPPViewBase::fileChanged_(), TOPPViewBase::filterContextMenu(), TOPPViewBase::filterEdit(), TOPPViewBase::layerContextMenu(), TOPPViewBase::layerSelectionChange(), TOPPViewBase::layerStatistics(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and TOPPViewBase::TOPPViewBase().
updateLayerBar
void updateLayerBar () slot
adapts the layer bar to the active window
References SpectrumCanvas::activeLayerIndex(), LayerData::DT_CONSENSUS, LayerData::DT_FEATURE, LayerData::DT_PEAK, LayerData::filename, LayerData::flipped, TOPPViewBase::getActiveCanvas(), SpectrumCanvas::getLayer(), SpectrumCanvas::getLayerCount(), Param::getValue(), TOPPViewBase::layers_view_, LayerData::modified, LayerData::name, LayerData::param, String::toQString(), DataValue::toQString(), LayerData::type, and LayerData::visible.
Referenced by TOPPViewBase::addData(), TOPPViewBase::fileChanged_(), TOPPViewBase::layerContextMenu(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), TOPPViewBase::showSpectrumWidgetInWindow(), and TOPPViewBase::TOPPViewBase().
updateMenu
void updateMenu () slot
enabled/disabled menu entries depending on the current state
References Spectrum1DWidget::canvas(), TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActiveCanvas(), Spectrum1DCanvas::mirrorModeActive(), and TOPPViewBase::topp_.
Referenced by TOPPViewBase::abortTOPPTool(), TOPPViewBase::addData(), TOPPViewBase::closeByTab(), TOPPViewBase::closeFile(), TOPPViewBase::fileChanged_(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::layerContextMenu(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and TOPPViewBase::TOPPViewBase().
updateProcessLog
void updateProcessLog () protected slot
Appends process output to log window.
References TOPPViewBase::log_, and TOPPViewBase::topp_.
Referenced by TOPPViewBase::runTOPPTool_().
updateRecentMenu_()
void updateRecentMenu_ () protected
update the recent files menu
References Param::getValue(), DefaultParamHandler::param_, TOPPViewBase::recent_actions_, TOPPViewBase::recent_files_, and Param::setValue().
Referenced by TOPPViewBase::addRecentFile_(), and TOPPViewBase::loadPreferences().
updateTabBar
void updateTabBar (QMdiSubWindow * w) slot
brings the tab corresponding to the active window in front
References EnhancedTabBarWidgetInterface::getWindowId(), EnhancedTabBar::setCurrentId(), and TOPPViewBase::tab_bar_.
Referenced by TOPPViewBase::TOPPViewBase().
updateToolBar
void updateToolBar () slot
updates the toolbar
References LayerData::C_ELEMENTS, Spectrum1DWidget::canvas(), Spectrum2DWidget::canvas(), SpectrumWidget::canvas(), TOPPViewBase::dm_elements_2d_, TOPPViewBase::dm_hull_2d_, TOPPViewBase::dm_hulls_2d_, TOPPViewBase::dm_ident_2d_, TOPPViewBase::dm_label_2d_, TOPPViewBase::dm_precursors_2d_, TOPPViewBase::dm_unassigned_2d_, TOPPViewBase::draw_group_1d_, LayerData::DT_CONSENSUS, LayerData::DT_FEATURE, LayerData::DT_IDENT, LayerData::DT_PEAK, LayerData::F_HULL, LayerData::F_HULLS, LayerData::F_UNASSIGNED, TOPPViewBase::getActive1DWidget(), TOPPViewBase::getActive2DWidget(), TOPPViewBase::getActive3DWidget(), TOPPViewBase::getActiveSpectrumWidget(), SpectrumCanvas::getCurrentLayer(), Spectrum1DCanvas::getDrawMode(), SpectrumCanvas::getIntensityMode(), SpectrumCanvas::getLayerCount(), SpectrumCanvas::getLayerFlag(), LayerData::I_PEPTIDEMZ, TOPPViewBase::intensity_button_group_, LayerData::L_NONE, LayerData::label, TOPPViewBase::LS_ERROR, LayerData::P_PRECURSORS, TOPPViewBase::showLogMessage_(), TOPPViewBase::tool_bar_1d_, TOPPViewBase::tool_bar_2d_cons_, TOPPViewBase::tool_bar_2d_feat_, TOPPViewBase::tool_bar_2d_ident_, TOPPViewBase::tool_bar_2d_peak_, and LayerData::type.
Referenced by TOPPViewBase::changeLabel(), TOPPViewBase::changeUnassigned(), TOPPViewBase::layerActivated(), and TOPPViewBase::TOPPViewBase().
updateViewBar
void updateViewBar () slot
adapts view bar to the active window
References TOPPViewBase::getActiveCanvas(), SpectraViewWidget::getComboBox(), SpectrumCanvas::getCurrentLayer(), SpectraIdentificationViewWidget::getLayer(), SpectraIdentificationViewWidget::getTableWidget(), SpectraViewWidget::getTreeWidget(), TOPPViewBase::layers_view_, SpectraIdentificationViewWidget::setLayer(), TOPPViewBase::spectra_identification_view_widget_, TOPPViewBase::spectra_view_widget_, SpectraViewWidget::updateEntries(), and TOPPViewBase::views_tabwidget_.
Referenced by TOPPViewBase::addData(), TOPPViewBase::annotateWithID(), TOPPViewBase::fileChanged_(), TOPPViewBase::layerActivated(), TOPPViewBase::layerContextMenu(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), TOPPViewBase::showSpectrumBrowser(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
viewChanged
void viewChanged (int tab_index) slot
changes the behavior according to the selected view in the spectra view bar and calls updateSpectraViewBar()
References TOPPViewSpectraViewBehavior::activateBehavior(), TOPPViewIdentificationViewBehavior::activateBehavior(), TOPPViewSpectraViewBehavior::deactivateBehavior(), TOPPViewIdentificationViewBehavior::deactivateBehavior(), TOPPViewBase::filter_dock_widget_, TOPPViewBase::getActive2DWidget(), TOPPViewBase::identificationview_behavior_, TOPPViewBase::layer_dock_widget_, TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::spectra_identification_view_widget_, TOPPViewBase::spectra_view_widget_, TOPPViewBase::spectraview_behavior_, TOPPViewBase::updateViewBar(), and TOPPViewBase::views_tabwidget_.
Referenced by TOPPViewBase::TOPPViewBase().
viewTabwidgetDoubleClicked
void viewTabwidgetDoubleClicked (int tab_index) slot
adds empty ID structure to allow manual annotations
References TOPPViewIdentificationViewBehavior::activateBehavior(), TOPPViewSpectraViewBehavior::deactivateBehavior(), TOPPViewBase::filter_dock_widget_, TOPPViewBase::getActive2DWidget(), TOPPViewBase::getActiveSpectrumWidget(), TOPPViewBase::identificationview_behavior_, TOPPViewBase::layer_dock_widget_, TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::spectraview_behavior_, TOPPViewBase::updateViewBar(), and TOPPViewBase::views_tabwidget_.
Referenced by TOPPViewBase::TOPPViewBase().
window_()
EnhancedTabBarWidgetInterface * window_ (int id) const protected
Returns the enhanced tabbar widget with id id.
References EnhancedTabBarWidgetInterface::getWindowId(), and TOPPViewBase::ws_.
Referenced by TOPPViewBase::addData(), TOPPViewBase::closeByTab(), and TOPPViewBase::enhancedWorkspaceWindowChanged().
Friends And Related Function Documentation
TestTOPPView
friend class TestTOPPView friend
Member Data Documentation
add_2d_context_
QMenu* add_2d_context_ protected
Additional context menu for 2D layers.
CAPTION_3D_SUFFIX_
const String CAPTION_3D_SUFFIX_ = " (3D)" static private
Suffix appended to caption of tabs when layer is shown in 3D.
Referenced by TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
current_path_
String current_path_ protected
The current path (used for loading and storing). Depending on the preferences this is static or changes with the current window/layer.
Referenced by TOPPViewBase::annotateWithID(), TOPPViewBase::getFileList_(), TOPPViewBase::showTOPPDialog_(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateCurrentPath().
dm_elements_2d_
QAction* dm_elements_2d_ protected
Referenced by TOPPViewBase::changeLayerFlag(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_hull_2d_
QAction* dm_hull_2d_ protected
Referenced by TOPPViewBase::changeLayerFlag(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_hulls_2d_
QAction* dm_hulls_2d_ protected
Referenced by TOPPViewBase::changeLayerFlag(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_ident_2d_
QAction* dm_ident_2d_ protected
Referenced by TOPPViewBase::changeLayerFlag(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_label_2d_
QToolButton* dm_label_2d_ protected
Referenced by TOPPViewBase::changeLabel(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_precursors_2d_
QAction* dm_precursors_2d_ protected
Referenced by TOPPViewBase::changeLayerFlag(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
dm_unassigned_2d_
QToolButton* dm_unassigned_2d_ protected
Referenced by TOPPViewBase::changeUnassigned(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
draw_group_1d_
QButtonGroup* draw_group_1d_ protected
Referenced by TOPPViewBase::showSpectrumGenerationDialog(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
filter_dock_widget_
QDockWidget* filter_dock_widget_ protected
Referenced by TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
filters_
QListWidget* filters_ protected
Referenced by TOPPViewBase::filterContextMenu(), TOPPViewBase::filterEdit(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateFilterBar().
filters_check_box_
QCheckBox* filters_check_box_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateFilterBar().
group_label_2d_
QActionGroup* group_label_2d_ protected
Referenced by TOPPViewBase::TOPPViewBase().
group_unassigned_2d_
QActionGroup* group_unassigned_2d_ protected
Referenced by TOPPViewBase::TOPPViewBase().
identificationview_behavior_
TOPPViewIdentificationViewBehavior* identificationview_behavior_ protected
TOPPView behavior for the identification view.
Referenced by TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), TOPPViewBase::viewTabwidgetDoubleClicked(), and TOPPViewBase::~TOPPViewBase().
intensity_button_group_
QButtonGroup* intensity_button_group_ protected
Referenced by TOPPViewBase::setIntensityMode(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
layer_dock_widget_
QDockWidget* layer_dock_widget_ protected
Referenced by TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
layers_view_
QListWidget* layers_view_ protected
Layer management widget.
Referenced by TOPPViewBase::copyLayer(), TOPPViewBase::layerContextMenu(), TOPPViewBase::layerVisibilityChange(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::updateLayerBar(), and TOPPViewBase::updateViewBar().
linkZoom_action_
QAction* linkZoom_action_ protected
Referenced by TOPPViewBase::linkZoom(), and TOPPViewBase::TOPPViewBase().
log_
QTextEdit* log_ protected
Log output window.
Referenced by TOPPViewBase::abortTOPPTool(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::logContextMenu(), TOPPViewBase::showLogMessage_(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateProcessLog().
message_label_
QLabel* message_label_ protected
Label for messages in the status bar.
Referenced by TOPPViewBase::showCursorStatus(), TOPPViewBase::showStatusMessage(), and TOPPViewBase::TOPPViewBase().
mz_label_
QLabel* mz_label_ protected
m/z label for messages in the status bar
Referenced by TOPPViewBase::showCursorStatus(), and TOPPViewBase::TOPPViewBase().
projections_2d_
QAction* projections_2d_ protected
Referenced by TOPPViewBase::TOPPViewBase().
recent_actions_
std::vector<QAction*> recent_actions_ protected
list of the recently opened files actions (menu entries)
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateRecentMenu_().
recent_files_
QStringList recent_files_ protected
list of the recently opened files
Referenced by TOPPViewBase::addRecentFile_(), TOPPViewBase::loadPreferences(), TOPPViewBase::savePreferences(), and TOPPViewBase::updateRecentMenu_().
rt_label_
QLabel* rt_label_ protected
RT label for messages in the status bar.
Referenced by TOPPViewBase::showCursorStatus(), and TOPPViewBase::TOPPViewBase().
spectra_identification_view_widget_
SpectraIdentificationViewWidget* spectra_identification_view_widget_ protected
Referenced by TOPPViewBase::getSpectraIdentificationViewWidget(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::updateViewBar(), and TOPPViewBase::viewChanged().
spectra_view_widget_
SpectraViewWidget* spectra_view_widget_ protected
Referenced by TOPPViewBase::copyLayer(), TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::updateViewBar(), and TOPPViewBase::viewChanged().
spectraview_behavior_
TOPPViewSpectraViewBehavior* spectraview_behavior_ protected
TOPPView behavior for the spectra view.
Referenced by TOPPViewBase::showSpectrumAs1D(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::viewChanged(), TOPPViewBase::viewTabwidgetDoubleClicked(), and TOPPViewBase::~TOPPViewBase().
tab_bar_
EnhancedTabBar* tab_bar_ protected
Tab bar. The address of the corresponding window to a tab is stored as an int in tabData()
Referenced by TOPPViewBase::layerContextMenu(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateTabBar().
tool_bar_
QToolBar* tool_bar_ protected
Referenced by TOPPViewBase::TOPPViewBase().
tool_bar_1d_
QToolBar* tool_bar_1d_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
tool_bar_2d_cons_
QToolBar* tool_bar_2d_cons_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
tool_bar_2d_feat_
QToolBar* tool_bar_2d_feat_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
tool_bar_2d_ident_
QToolBar* tool_bar_2d_ident_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
tool_bar_2d_peak_
QToolBar* tool_bar_2d_peak_ protected
Referenced by TOPPViewBase::TOPPViewBase(), and TOPPViewBase::updateToolBar().
topp_
struct { ... } topp_
Information needed for execution of TOPP tools.
Referenced by TOPPViewBase::abortTOPPTool(), TOPPViewBase::finishTOPPToolExecution(), TOPPViewBase::rerunTOPPTool(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showTOPPDialog_(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::updateMenu(), and TOPPViewBase::updateProcessLog().
views_dockwidget_
QDockWidget* views_dockwidget_ protected
Referenced by TOPPViewBase::showSpectrumBrowser(), and TOPPViewBase::TOPPViewBase().
views_tabwidget_
QTabWidget* views_tabwidget_ protected
Tabwidget that hold the different views on the loaded data.
Referenced by TOPPViewBase::addData(), TOPPViewBase::annotateWithID(), TOPPViewBase::enhancedWorkspaceWindowChanged(), TOPPViewBase::TOPPViewBase(), TOPPViewBase::updateViewBar(), TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
watcher_
FileWatcher* watcher_ protected
Watcher that tracks file changes (in order to update the data in the different views)
Referenced by TOPPViewBase::addDataFile(), TOPPViewBase::fileChanged_(), and TOPPViewBase::TOPPViewBase().
watcher_msgbox_
bool watcher_msgbox_ protected
Holds the messageboxes for each layer that are currently popped up (to avoid popping them up again, if file changes again before the messagebox is closed)
Referenced by TOPPViewBase::fileChanged_().
ws_
EnhancedWorkspace* ws_ protected
Main workspace.
Referenced by TOPPViewBase::addData(), TOPPViewBase::closeEvent(), TOPPViewBase::closeFile(), TOPPViewBase::fileChanged_(), TOPPViewBase::getActiveCanvas(), TOPPViewBase::getActiveSpectrumWidget(), TOPPViewBase::getFileList_(), TOPPViewBase::getFilenamesOfOpenFiles_(), TOPPViewBase::getWorkspace(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), TOPPViewBase::showSpectrumWidgetInWindow(), TOPPViewBase::tileHorizontal(), TOPPViewBase::tileVertical(), TOPPViewBase::TOPPViewBase(), and TOPPViewBase::window_().
zoom_together_
bool zoom_together_ protected
Stores whether the individual windows should zoom together (be linked) or not.
Referenced by TOPPViewBase::layerZoomChanged(), TOPPViewBase::linkZoom(), and TOPPViewBase::TOPPViewBase().