OpenMS: ToolsDialog Class Reference
ToolsDialog Class Reference
Visual » Dialogs
TOPP tool selection dialog.
#include <OpenMS/VISUAL/DIALOGS/ToolsDialog.h>
Public Member Functions
ToolsDialog (QWidget *parent, String ini_file, String default_dir, LayerData::DataType layertype)
Constructor.
~ToolsDialog () override
Destructor.
String getOutput ()
to get the parameter name for output. Empty if no output was selected.
String getInput ()
to get the parameter name for input
String getTool ()
to get the currently selected tool-name
Protected Slots
void ok_ ()
if ok button pressed show the tool output in a new layer, a new window or standard output as messagebox
void setTool_ (int i)
Slot that handles changing of the tool.
void createINI_ ()
Slot that retrieves and displays the defaults.
void loadINI_ ()
loads an ini-file into the editor_
void storeINI_ ()
stores an ini-file from the editor_
Private Member Functions
void disable_ ()
Disables the ok button and input/output comboboxes.
void enable_ ()
Enables the ok button and input/output comboboxes.
Private Attributes
ParamEditor * editor_
ParamEditor for reading ini-files.
QLabel * tool_desc_
tools description label
QComboBox * tools_combo_
ComboBox for choosing a TOPP-tool.
QComboBox * input_combo_
for choosing an input parameter
QComboBox * output_combo_
for choosing an output parameter
Param arg_param_
Param for loading the ini-file.
Param vis_param_
Param for loading configuration information in the ParamEditor.
QPushButton * ok_button_
ok-button connected with slot ok_()
std::map< String, String > arg_map_
map for getting the parameter name from the full path in arg_param
String ini_file_
Location of the temporary INI file this dialog works on.
String default_dir_
default-dir of ini-file to open
QString filename_
name of ini-file
Detailed Description
TOPP tool selection dialog.
In the dialog, the user can
select a TOPP tool
select the options used for the input and output file
and set the parameters for the tool
This information can then be used to execute the tool.
The offered tools depend on the data type set in the constructor.
Constructor & Destructor Documentation
ToolsDialog()
ToolsDialog (QWidget * parent, String ini_file, String default_dir, LayerData::DataType layertype)
Constructor.
Parameters
parent Qt parent widget
ini_file The file name of the temporary INI file created by this dialog
default_dir The default directory for loading and storing INI files
layertype The type of data (determines the applicable tools)
~ToolsDialog()
~ToolsDialog () override
Destructor.
Member Function Documentation
createINI_
void createINI_ () protected slot
Slot that retrieves and displays the defaults.
disable_()
void disable_ () private
Disables the ok button and input/output comboboxes.
enable_()
void enable_ () private
Enables the ok button and input/output comboboxes.
getInput()
String getInput ()
to get the parameter name for input
Referenced by TOPPViewBase::showTOPPDialog_().
getOutput()
String getOutput ()
to get the parameter name for output. Empty if no output was selected.
Referenced by TOPPViewBase::showTOPPDialog_().
getTool()
String getTool ()
to get the currently selected tool-name
Referenced by TOPPViewBase::showTOPPDialog_().
loadINI_
void loadINI_ () protected slot
loads an ini-file into the editor_
ok_
void ok_ () protected slot
if ok button pressed show the tool output in a new layer, a new window or standard output as messagebox
setTool_
void setTool_ (int i) protected slot
Slot that handles changing of the tool.
storeINI_
void storeINI_ () protected slot
stores an ini-file from the editor_
Member Data Documentation
arg_map_
std::map<String, String> arg_map_ private
map for getting the parameter name from the full path in arg_param
arg_param_
Param arg_param_ private
Param for loading the ini-file.
default_dir_
String default_dir_ private
default-dir of ini-file to open
editor_
ParamEditor* editor_ private
ParamEditor for reading ini-files.
filename_
QString filename_ private
name of ini-file
ini_file_
String ini_file_ private
Location of the temporary INI file this dialog works on.
input_combo_
QComboBox* input_combo_ private
for choosing an input parameter
ok_button_
QPushButton* ok_button_ private
ok-button connected with slot ok_()
output_combo_
QComboBox* output_combo_ private
for choosing an output parameter
tool_desc_
QLabel* tool_desc_ private
tools description label
tools_combo_
QComboBox* tools_combo_ private
ComboBox for choosing a TOPP-tool.
vis_param_
Param vis_param_ private
Param for loading configuration information in the ParamEditor.