OpenMS: TOPPViewOpenDialog Class Reference
TOPPViewOpenDialog Class Reference
Visual » TOPPView
Dataset opening options for TOPPView.
#include <OpenMS/VISUAL/DIALOGS/TOPPViewOpenDialog.h>
Public Member Functions
TOPPViewOpenDialog (const String &data_name, bool as_window, bool as_2d, bool cutoff, QWidget *parent=nullptr)
Constructor.
~TOPPViewOpenDialog () override
Destructor.
bool viewMapAs2D () const
Returns true, if 2D mode is to be used for maps.
bool viewMapAs1D () const
Returns true, if 1D mode is to be used for maps.
bool isCutoffEnabled () const
Returns if the low intensity peaks should be hidden.
bool isDataDIA () const
Returns if the data is DIA / SWATH-MS data.
bool openAsNewWindow () const
Returns true, if the data should be opened in a new window.
Int getMergeLayer () const
Returns the index of the selected merge layer. If the option is not selected -1 is returned.
void disableDimension (bool as_2d)
Disables view dimension section and sets the selected option.
void disableCutoff (bool cutoff_on)
Disables cutoff section and sets the selected option.
void disableLocation (bool window)
Disables opening location section and sets the selected option.
void setMergeLayers (const Map< Size, String > &layers)
Sets the possible merge layers (index and name) and activates the option.
Protected Slots
void updateViewMode_ (QAbstractButton *button)
slot that disables 2D/3D options, when as layer is selected
Protected Attributes
bool map_as_2d_disabled_
Stores if this option is disabled, to avoid activating it in updateViewMode_()
Private Attributes
Ui::TOPPViewOpenDialogTemplate * ui_
Detailed Description
Dataset opening options for TOPPView.
Constructor & Destructor Documentation
TOPPViewOpenDialog()
TOPPViewOpenDialog (const String & data_name, bool as_window, bool as_2d, bool cutoff, QWidget * parent = nullptr)
Constructor.
~TOPPViewOpenDialog()
~TOPPViewOpenDialog () override
Destructor.
Member Function Documentation
disableCutoff()
void disableCutoff (bool cutoff_on)
Disables cutoff section and sets the selected option.
Referenced by TOPPViewBase::addData().
disableDimension()
void disableDimension (bool as_2d)
Disables view dimension section and sets the selected option.
Referenced by TOPPViewBase::addData().
disableLocation()
void disableLocation (bool window)
Disables opening location section and sets the selected option.
Referenced by TOPPViewBase::addData().
getMergeLayer()
Int getMergeLayer () const
Returns the index of the selected merge layer. If the option is not selected -1 is returned.
Referenced by TOPPViewBase::addData().
isCutoffEnabled()
bool isCutoffEnabled () const
Returns if the low intensity peaks should be hidden.
Referenced by TOPPViewBase::addData().
isDataDIA()
bool isDataDIA () const
Returns if the data is DIA / SWATH-MS data.
Referenced by TOPPViewBase::addData().
openAsNewWindow()
bool openAsNewWindow () const
Returns true, if the data should be opened in a new window.
Referenced by TOPPViewBase::addData().
setMergeLayers()
void setMergeLayers (const Map< Size, String > & layers)
Sets the possible merge layers (index and name) and activates the option.
It is deactivated by default and can be deactivated manually by passing an empty list.
Referenced by TOPPViewBase::addData().
updateViewMode_
void updateViewMode_ (QAbstractButton * button) protected slot
slot that disables 2D/3D options, when as layer is selected
viewMapAs1D()
bool viewMapAs1D () const
Returns true, if 1D mode is to be used for maps.
Referenced by TOPPViewBase::addData().
viewMapAs2D()
bool viewMapAs2D () const
Returns true, if 2D mode is to be used for maps.
Referenced by TOPPViewBase::addData().
Member Data Documentation
map_as_2d_disabled_
bool map_as_2d_disabled_ protected
Stores if this option is disabled, to avoid activating it in updateViewMode_()
ui_
Ui::TOPPViewOpenDialogTemplate* ui_ private