OpenMS: SpectrumAlignmentDialog Class Reference
SpectrumAlignmentDialog Class Reference
Visual » Dialogs
Lets the user select two spectra and set the parameters for the spectrum alignment.
#include <OpenMS/VISUAL/DIALOGS/SpectrumAlignmentDialog.h>
Public Member Functions
SpectrumAlignmentDialog (Spectrum1DWidget *parent)
Constructor.
~SpectrumAlignmentDialog ()
double getTolerance () const
bool isPPM () const
Int get1stLayerIndex ()
Returns the index of the selected non-flipped layer.
Int get2ndLayerIndex ()
Returns the index of the selected flipped layer.
Protected Attributes
std::vector< UInt > layer_indices_1_
Stores the layer indices of the layers in the left list (non-flipped layers)
std::vector< UInt > layer_indices_2_
Stores the layer indices of the layers in the right list (flipped layers)
Private Attributes
Ui::SpectrumAlignmentDialogTemplate * ui_
Detailed Description
Lets the user select two spectra and set the parameters for the spectrum alignment.
Constructor & Destructor Documentation
SpectrumAlignmentDialog()
SpectrumAlignmentDialog (Spectrum1DWidget * parent)
Constructor.
~SpectrumAlignmentDialog()
~SpectrumAlignmentDialog ()
Member Function Documentation
get1stLayerIndex()
Int get1stLayerIndex ()
Returns the index of the selected non-flipped layer.
Referenced by TOPPViewBase::showSpectrumAlignmentDialog().
get2ndLayerIndex()
Int get2ndLayerIndex ()
Returns the index of the selected flipped layer.
Referenced by TOPPViewBase::showSpectrumAlignmentDialog().
getTolerance()
double getTolerance () const
Referenced by TOPPViewBase::showSpectrumAlignmentDialog().
isPPM()
bool isPPM () const
Referenced by TOPPViewBase::showSpectrumAlignmentDialog().
Member Data Documentation
layer_indices_1_
std::vector<UInt> layer_indices_1_ protected
Stores the layer indices of the layers in the left list (non-flipped layers)
layer_indices_2_
std::vector<UInt> layer_indices_2_ protected
Stores the layer indices of the layers in the right list (flipped layers)
ui_
Ui::SpectrumAlignmentDialogTemplate* ui_ private