OpenMS: EnhancedTabBar Class Reference
EnhancedTabBar Class Reference
Visual
Convenience tab bar implementation.
#include <OpenMS/VISUAL/EnhancedTabBar.h>
Public Slots
void removeId (int id)
Remove the tab with identifier id.
Signals
void currentIdChanged (int id)
Signal that indicates that the current tab changed.
void aboutToCloseId (int id)
Signal that indicates that the tab with identifier id is about to be removed (double click or context menu)
void dropOnTab (const QMimeData *data, QWidget *source, int id)
Signal that is emitted, when a drag-and-drop action ends on a tab.
void dropOnWidget (const QMimeData *data, QWidget *source)
Signal that is emitted, when a drag-and-drop action ends on the unused space on the right side of the tabs.
Public Member Functions
EnhancedTabBar (QWidget *parent=nullptr)
Constructor.
~EnhancedTabBar () override
Destructor.
int addTab (const String &text, int id)
Adds a new tab with the name text and the identifier id.
void setCurrentId (int id)
Selects the tab with identifier id.
Reimplemented Qt events
void mouseDoubleClickEvent (QMouseEvent *e) override
void contextMenuEvent (QContextMenuEvent *e) override
void dragEnterEvent (QDragEnterEvent *e) override
void dropEvent (QDropEvent *e) override
int tabAt_ (const QPoint &pos)
Returns the QTabBar index of the tab at position pos. If there is no tab at that position -1 is returned.
void currentChanged_ (int id)
Slot that translates the currentChanged(int) signal to currentIdChanged(int)
Detailed Description
Convenience tab bar implementation.
This tab bar differs in several ways form the QTabBar:
you can close a tab by double-clicking it or through its context menu.
it works based on tab identifiers (a fixed id stored in tab data) rather than on tab indices, which might change when inserting or removing a tab.
it accepts all drag-and-drop actions and emits signals to handle them.
Constructor & Destructor Documentation
EnhancedTabBar()
EnhancedTabBar (QWidget * parent = nullptr)
Constructor.
~EnhancedTabBar()
~EnhancedTabBar () override
Destructor.
Member Function Documentation
aboutToCloseId
void aboutToCloseId (int id) signal
Signal that indicates that the tab with identifier id is about to be removed (double click or context menu)
addTab()
int addTab (const String & text, int id)
Adds a new tab with the name text and the identifier id.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow(), and TOPPViewBase::TOPPViewBase().
contextMenuEvent()
void contextMenuEvent (QContextMenuEvent * e) override protected
currentChanged_
void currentChanged_ (int id) protected slot
Slot that translates the currentChanged(int) signal to currentIdChanged(int)
currentIdChanged
void currentIdChanged (int id) signal
Signal that indicates that the current tab changed.
dragEnterEvent()
void dragEnterEvent (QDragEnterEvent * e) override protected
dropEvent()
void dropEvent (QDropEvent * e) override protected
dropOnTab
void dropOnTab (const QMimeData * data, QWidget * source, int id) signal
Signal that is emitted, when a drag-and-drop action ends on a tab.
dropOnWidget
void dropOnWidget (const QMimeData * data, QWidget * source) signal
Signal that is emitted, when a drag-and-drop action ends on the unused space on the right side of the tabs.
mouseDoubleClickEvent()
void mouseDoubleClickEvent (QMouseEvent * e) override protected
removeId
void removeId (int id) slot
Remove the tab with identifier id.
Referenced by TOPPViewBase::TOPPViewBase().
setCurrentId()
void setCurrentId (int id)
Selects the tab with identifier id.
Referenced by TOPPViewBase::showSpectrumWidgetInWindow(), and TOPPViewBase::updateTabBar().
tabAt_()
int tabAt_ (const QPoint & pos) protected
Returns the QTabBar index of the tab at position pos. If there is no tab at that position -1 is returned.