OpenMS: LayerData Class Reference
LayerData Class Reference
Visual » Spectrum visualization widgets
Class that stores the data for one layer.
#include <OpenMS/VISUAL/LayerData.h>
Type definitions
enum DataType {
DT_PEAK, DT_CHROMATOGRAM, DT_FEATURE, DT_CONSENSUS,
DT_IDENT, DT_UNKNOWN
}
enum Flags {
F_HULL, F_HULLS, F_UNASSIGNED, P_PRECURSORS,
P_PROJECTIONS, C_ELEMENTS, I_PEPTIDEMZ, I_LABELS,
SIZE_OF_FLAGS
}
Flags that determine which information is shown.
enum LabelType {
L_NONE, L_INDEX, L_META_LABEL, L_ID,
L_ID_ALL, SIZE_OF_LABEL_TYPE
}
Label used in visualization.
typedef FeatureMap FeatureMapType
Features.
typedef boost::shared_ptr< FeatureMap > FeatureMapSharedPtrType
SharedPtr on feature map.
typedef ConsensusMap ConsensusMapType
consensus features
typedef boost::shared_ptr< ConsensusMap > ConsensusMapSharedPtrType
SharedPtr on consensus features.
typedef PeakMap ExperimentType
Main data type (experiment)
typedef boost::shared_ptr< ExperimentType > ExperimentSharedPtrType
SharedPtr on MSExperiment.
typedef boost::shared_ptr< const ExperimentType > ConstExperimentSharedPtrType
typedef boost::shared_ptr< OnDiscMSExperiment > ODExperimentSharedPtrType
SharedPtr on On-Disc MSExperiment.
std::bitset< SIZE_OF_FLAGS > flags
Actual state of each flag.
bool visible
if this layer is visible
bool flipped
if this layer is flipped (1d mirror view)
DataType type
data type (peak or feature data)
String name
layer name
String filename
file name of the file the data comes from (if available)
std::vector< PeptideIdentification > peptides
peptide identifications
Param param
Layer parameters.
MultiGradient gradient
Gradient for 2D and 3D views.
DataFilters filters
Filters to apply before painting.
std::vector< Annotations1DContainer > annotations_1d
Annotations of all spectra of the experiment (1D view)
std::vector< QColor > peak_colors_1d
Peak colors of the currently shown spectrum.
bool modifiable
Flag that indicates if the layer data can be modified (so far used for features only)
bool modified
Flag that indicates that the layer data was modified since loading it.
LabelType label
Label type.
int peptide_id_index
Selected peptide id and hit index (-1 if none is selected)
int peptide_hit_index
static const std::string NamesOfLabelType [SIZE_OF_LABEL_TYPE]
Label names.
FeatureMapSharedPtrType features
feature data
ConsensusMapSharedPtrType consensus
consensus feature data
ExperimentSharedPtrType peaks
peak data
ODExperimentSharedPtrType on_disc_peaks
on disc peak data
ExperimentSharedPtrType chromatograms
chromatogram data
Size current_spectrum_
Index of the current spectrum.
ExperimentType::SpectrumType cached_spectrum_
Current cached spectrum.
LayerData ()
Default constructor.
const FeatureMapSharedPtrType & getFeatureMap () const
Returns a const reference to the current feature data.
FeatureMapSharedPtrType & getFeatureMap ()
Returns a const reference to the current feature data.
const ConsensusMapSharedPtrType & getConsensusMap () const
Returns a const reference to the consensus feature data.
ConsensusMapSharedPtrType & getConsensusMap ()
Returns current consensus map (mutable)
const ConstExperimentSharedPtrType getPeakData () const
Returns a const reference to the current in-memory peak data.
const ExperimentSharedPtrType & getPeakDataMuteable ()
Returns a mutable reference to the current in-memory peak data.
void setPeakData (ExperimentSharedPtrType p)
Set the current in-memory peak data.
void setOnDiscPeakData (ODExperimentSharedPtrType p)
Set the current on-disc data.
const ODExperimentSharedPtrType & getOnDiscPeakData () const
Returns a mutable reference to the on-disc data.
const ExperimentSharedPtrType & getChromatogramData () const
Returns a mutable reference to the current chromatogram data.
ExperimentSharedPtrType & getChromatogramData ()
Returns a mutable reference to the current chromatogram data.
const Annotations1DContainer & getCurrentAnnotations () const
Returns a const reference to the annotations of the current spectrum (1D view)
Annotations1DContainer & getCurrentAnnotations ()
Returns a mutable reference to the annotations of the current spectrum (1D view)
const Annotations1DContainer & getAnnotations (Size spectrum_index) const
Returns a const reference to the annotations of the current spectrum (1D view)
Annotations1DContainer & getAnnotations (Size spectrum_index)
Returns a mutable reference to the annotations of the current spectrum (1D view)
const ExperimentType::SpectrumType & getCurrentSpectrum () const
Returns a const reference to the current spectrum (1D view)
void sortCurrentSpectrumByPosition ()
const ExperimentType::SpectrumType getSpectrum (Size spectrum_idx) const
Returns a const-copy of the required spectrum which is guaranteed to be populated with raw data.
Size getCurrentSpectrumIndex () const
Get the index of the current spectrum (1D view)
void setCurrentSpectrumIndex (Size index)
Set the index of the current spectrum (1D view)
bool isIonMobilityData () const
Check whether the current layer should be represented as ion mobility.
void labelAsIonMobilityData () const
bool isDIAData () const
Check whether the current layer contains DIA (SWATH-MS) data.
void labelAsDIAData ()
Label the current layer as DIA (SWATH-MS) data.
bool chromatogram_flag_set () const
Check whether the current layer is a chromatogram.
void set_chromatogram_flag ()
set the chromatogram flag
void remove_chromatogram_flag ()
remove the chromatogram flag
void updateRanges ()
Update ranges of all data structures.
void synchronizePeakAnnotations ()
void removePeakAnnotationsFromPeptideHit (const std::vector< Annotation1DItem * > &selected_annotations)
remove peak annotations in the given list from the currently active PeptideHit
void updateCache_ ()
Update current cached spectrum for easy retrieval.
void updatePeptideHitAnnotations_ (PeptideHit &hit)
updates the PeakAnnotations in the current PeptideHit with manually changed annotations
Detailed Description
Class that stores the data for one layer.
The data for a layer can be peak data, feature data (feature, consensus), chromatogram or peptide identification data.
For 2D and 3D data, the data is generally accessible through getPeakData() while features are accessible through getFeatureMap() and getConsensusMap(). For 1D data, the current spectrum must be accessed through getCurrentSpectrum().
Peak data is stored using a shared pointer to an MSExperiment data structure as well as a shared pointer to a OnDiscMSExperiment data structure. Note that the actual data may not be in memory as this is not efficient for large files and therefore may have to be retrieved from disk on-demand.
Note
The spectrum for 1D viewing retrieved through getCurrentSpectrum() is a copy of the actual raw data and *different* from the one retrieved through getPeakData()[index]. Any changes to applied to getCurrentSpectrum() are non-persistent and will be gone the next time the cache is updated. Persistent changes can be applied to getPeakDataMuteable() and will be available on the next cache update.
Layer is mainly used as a member variable of SpectrumCanvas which holds a vector of LayerData objects.
Member Typedef Documentation
ConsensusMapSharedPtrType
typedef boost::shared_ptr<ConsensusMap> ConsensusMapSharedPtrType
SharedPtr on consensus features.
ConsensusMapType
typedef ConsensusMap ConsensusMapType
consensus features
ConstExperimentSharedPtrType
typedef boost::shared_ptr<const ExperimentType> ConstExperimentSharedPtrType
ExperimentSharedPtrType
typedef boost::shared_ptr<ExperimentType> ExperimentSharedPtrType
SharedPtr on MSExperiment.
ExperimentType
typedef PeakMap ExperimentType
Main data type (experiment)
FeatureMapSharedPtrType
typedef boost::shared_ptr<FeatureMap > FeatureMapSharedPtrType
SharedPtr on feature map.
FeatureMapType
typedef FeatureMap FeatureMapType
Features.
ODExperimentSharedPtrType
typedef boost::shared_ptr<OnDiscMSExperiment> ODExperimentSharedPtrType
SharedPtr on On-Disc MSExperiment.
Member Enumeration Documentation
DataType
enum DataType
Dataset types. Order in the enum determines the order in which layer types are drawn.
Enumerator
DT_PEAK
Spectrum profile or centroided data.
DT_CHROMATOGRAM
Chromatogram data.
DT_FEATURE
Feature data.
DT_CONSENSUS
Consensus feature data.
DT_IDENT
Peptide identification data.
DT_UNKNOWN
Undefined data type indicating an error.
Flags
enum Flags
Flags that determine which information is shown.
Enumerator
F_HULL
Features: Overall convex hull.
F_HULLS
Features: Convex hulls of single mass traces.
F_UNASSIGNED
Features: Unassigned peptide hits.
P_PRECURSORS
Peaks: Mark precursor peaks of MS/MS scans.
P_PROJECTIONS
Peaks: Show projections.
C_ELEMENTS
Consensus features: Show elements.
I_PEPTIDEMZ
Identifications: m/z source.
I_LABELS
Identifications: Show labels (not sequences)
SIZE_OF_FLAGS
LabelType
enum LabelType
Label used in visualization.
Enumerator
L_NONE
No label is displayed.
L_INDEX
The element number is used.
L_META_LABEL
The 'label' meta information is used.
L_ID
The best peptide hit of the first identification run is used.
L_ID_ALL
All peptide hits of the first identification run are used.
SIZE_OF_LABEL_TYPE
Constructor & Destructor Documentation
LayerData()
LayerData () inline
Default constructor.
References LayerData::annotations_1d.
Member Function Documentation
chromatogram_flag_set()
bool chromatogram_flag_set () const inline
Check whether the current layer is a chromatogram.
This is needed because type will *not* distinguish properly between chromatogram and spectra data. This is due to the fact that we store chromatograms for display in 1D in a data layer using MSSpectrum and so the layer looks like PEAK data to tools.
References LayerData::getPeakData().
Referenced by LayerData::remove_chromatogram_flag(), and TOPPViewBase::runTOPPTool_().
getAnnotations() [1/2]
Annotations1DContainer& getAnnotations (Size spectrum_index) inline
Returns a mutable reference to the annotations of the current spectrum (1D view)
References LayerData::annotations_1d.
getAnnotations() [2/2]
const Annotations1DContainer& getAnnotations (Size spectrum_index) const inline
Returns a const reference to the annotations of the current spectrum (1D view)
References LayerData::annotations_1d.
getChromatogramData() [1/2]
ExperimentSharedPtrType& getChromatogramData () inline
Returns a mutable reference to the current chromatogram data.
References LayerData::chromatograms.
getChromatogramData() [2/2]
const ExperimentSharedPtrType& getChromatogramData () const inline
Returns a mutable reference to the current chromatogram data.
References LayerData::chromatograms.
getConsensusMap() [1/2]
ConsensusMapSharedPtrType& getConsensusMap () inline
Returns current consensus map (mutable)
References LayerData::consensus.
getConsensusMap() [2/2]
const ConsensusMapSharedPtrType& getConsensusMap () const inline
Returns a const reference to the consensus feature data.
References LayerData::consensus.
Referenced by TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::fileChanged_(), and TOPPViewBase::runTOPPTool_().
getCurrentAnnotations() [1/2]
Annotations1DContainer& getCurrentAnnotations () inline
Returns a mutable reference to the annotations of the current spectrum (1D view)
References LayerData::annotations_1d, and LayerData::current_spectrum_.
getCurrentAnnotations() [2/2]
const Annotations1DContainer& getCurrentAnnotations () const inline
Returns a const reference to the annotations of the current spectrum (1D view)
References LayerData::annotations_1d, and LayerData::current_spectrum_.
getCurrentSpectrum()
const ExperimentType::SpectrumType& getCurrentSpectrum () const
Returns a const reference to the current spectrum (1D view)
Note
Only use this function to access the current spectrum for the 1D view
Referenced by TOPPViewBase::showCurrentPeaksAsDIA(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
getCurrentSpectrumIndex()
Size getCurrentSpectrumIndex () const inline
Get the index of the current spectrum (1D view)
References LayerData::current_spectrum_.
Referenced by TOPPViewBase::runTOPPTool_(), and TOPPViewBase::showCurrentPeaksAsIonMobility().
getFeatureMap() [1/2]
FeatureMapSharedPtrType& getFeatureMap () inline
Returns a const reference to the current feature data.
References LayerData::features.
getFeatureMap() [2/2]
const FeatureMapSharedPtrType& getFeatureMap () const inline
Returns a const reference to the current feature data.
References LayerData::features.
Referenced by TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::fileChanged_(), and TOPPViewBase::runTOPPTool_().
getOnDiscPeakData()
const ODExperimentSharedPtrType& getOnDiscPeakData () const inline
Returns a mutable reference to the on-disc data.
References LayerData::on_disc_peaks.
Referenced by TOPPViewBase::copyLayer(), TOPPViewBase::showCurrentPeaksAs2D(), and TOPPViewBase::showCurrentPeaksAsDIA().
getPeakData()
const ConstExperimentSharedPtrType getPeakData () const
Returns a const reference to the current in-memory peak data.
Note
Depending on the caching strategy (on-disk or in-memory), all or some spectra may have zero size and contain only meta data since peak data is cached on disk.
Do *not* use this function to access the current spectrum for the 1D view
Referenced by TOPPViewBase::addData(), LayerData::chromatogram_flag_set(), TOPPViewBase::copyLayer(), TOPPViewBase::enhancedWorkspaceWindowChanged(), LayerData::isDIAData(), LayerData::isIonMobilityData(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::runTOPPTool_(), and TOPPViewBase::showCurrentPeaksAsDIA().
getPeakDataMuteable()
const ExperimentSharedPtrType& getPeakDataMuteable () inline
Returns a mutable reference to the current in-memory peak data.
Note
Depending on the caching strategy (on-disk or in-memory), all or some spectra may have zero size and contain only meta data since peak data is cached on disk.
Do *not* use this function to access the current spectrum for the 1D view
References LayerData::peaks.
Referenced by TOPPViewBase::annotateMS1FromMassFingerprinting_(), TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::fileChanged_(), TOPPViewBase::showCurrentPeaksAs2D(), and TOPPViewBase::showCurrentPeaksAs3D().
getSpectrum()
const ExperimentType::SpectrumType getSpectrum (Size spectrum_idx) const inline
Returns a const-copy of the required spectrum which is guaranteed to be populated with raw data.
References LayerData::cached_spectrum_, LayerData::current_spectrum_, LayerData::on_disc_peaks, and LayerData::peaks.
isDIAData()
bool isDIAData () const inline
Check whether the current layer contains DIA (SWATH-MS) data.
References LayerData::getPeakData().
Referenced by TOPPViewBase::showCurrentPeaksAsDIA().
isIonMobilityData()
bool isIonMobilityData () const inline
Check whether the current layer should be represented as ion mobility.
References LayerData::getPeakData().
Referenced by TOPPViewBase::showCurrentPeaksAs3D().
labelAsDIAData()
void labelAsDIAData () inline
Label the current layer as DIA (SWATH-MS) data.
References LayerData::peaks.
labelAsIonMobilityData()
void labelAsIonMobilityData () const inline
References LayerData::peaks.
remove_chromatogram_flag()
void remove_chromatogram_flag () inline
remove the chromatogram flag
References LayerData::chromatogram_flag_set(), and LayerData::peaks.
Referenced by TOPPViewBase::runTOPPTool_().
removePeakAnnotationsFromPeptideHit()
void removePeakAnnotationsFromPeptideHit (const std::vector< Annotation1DItem * > & selected_annotations)
remove peak annotations in the given list from the currently active PeptideHit
set_chromatogram_flag()
void set_chromatogram_flag () inline
set the chromatogram flag
References LayerData::peaks.
setCurrentSpectrumIndex()
void setCurrentSpectrumIndex (Size index) inline
Set the index of the current spectrum (1D view)
References LayerData::current_spectrum_, and LayerData::updateCache_().
setOnDiscPeakData()
void setOnDiscPeakData (ODExperimentSharedPtrType p) inline
Set the current on-disc data.
References LayerData::on_disc_peaks.
setPeakData()
void setPeakData (ExperimentSharedPtrType p) inline
Set the current in-memory peak data.
References LayerData::peaks, and LayerData::updateCache_().
sortCurrentSpectrumByPosition()
void sortCurrentSpectrumByPosition () inline
References LayerData::cached_spectrum_, and MSSpectrum::sortByPosition().
synchronizePeakAnnotations()
void synchronizePeakAnnotations ()
updates the PeakAnnotations in the current PeptideHit with manually changed annotations if no PeptideIdentification or PeptideHit for the spectrum exist, it is generated
updateCache_()
void updateCache_ () private
Update current cached spectrum for easy retrieval.
Referenced by LayerData::setCurrentSpectrumIndex(), and LayerData::setPeakData().
updatePeptideHitAnnotations_()
void updatePeptideHitAnnotations_ (PeptideHit & hit) private
updates the PeakAnnotations in the current PeptideHit with manually changed annotations
updateRanges()
void updateRanges ()
Update ranges of all data structures.
Updates ranges of all tracked data structures (spectra, chromatograms, features etc).
Member Data Documentation
annotations_1d
std::vector<Annotations1DContainer> annotations_1d
Annotations of all spectra of the experiment (1D view)
Referenced by LayerData::getAnnotations(), LayerData::getCurrentAnnotations(), and LayerData::LayerData().
cached_spectrum_
ExperimentType::SpectrumType cached_spectrum_ private
Current cached spectrum.
Referenced by LayerData::getSpectrum(), and LayerData::sortCurrentSpectrumByPosition().
chromatograms
ExperimentSharedPtrType chromatograms private
chromatogram data
Referenced by LayerData::getChromatogramData().
consensus
ConsensusMapSharedPtrType consensus private
consensus feature data
Referenced by LayerData::getConsensusMap().
current_spectrum_
Size current_spectrum_ private
Index of the current spectrum.
Referenced by LayerData::getCurrentAnnotations(), LayerData::getCurrentSpectrumIndex(), LayerData::getSpectrum(), and LayerData::setCurrentSpectrumIndex().
features
FeatureMapSharedPtrType features private
feature data
Referenced by LayerData::getFeatureMap().
filename
String filename
file name of the file the data comes from (if available)
Referenced by TOPPViewBase::copyLayer(), TOPPViewBase::fileChanged_(), TOPPViewBase::getFilenamesOfOpenFiles_(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and TOPPViewBase::updateLayerBar().
filters
DataFilters filters
Filters to apply before painting.
Referenced by TOPPViewBase::filterContextMenu(), TOPPViewBase::filterEdit(), and TOPPViewBase::updateFilterBar().
flags
std::bitset<SIZE_OF_FLAGS> flags
Actual state of each flag.
flipped
bool flipped
if this layer is flipped (1d mirror view)
Referenced by TOPPViewBase::updateLayerBar().
gradient
MultiGradient gradient
Gradient for 2D and 3D views.
label
LabelType label
Label type.
Referenced by TOPPViewBase::updateToolBar().
modifiable
bool modifiable
Flag that indicates if the layer data can be modified (so far used for features only)
modified
bool modified
Flag that indicates that the layer data was modified since loading it.
Referenced by TOPPViewBase::updateLayerBar().
name
String name
layer name
Referenced by TOPPViewBase::addData(), TOPPViewBase::copyLayer(), TOPPViewBase::filterContextMenu(), TOPPViewBase::layerContextMenu(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and TOPPViewBase::updateLayerBar().
NamesOfLabelType
const std::string NamesOfLabelType[SIZE_OF_LABEL_TYPE] static
Label names.
Referenced by TOPPViewBase::changeLabel(), and TOPPViewBase::TOPPViewBase().
on_disc_peaks
ODExperimentSharedPtrType on_disc_peaks private
on disc peak data
Referenced by LayerData::getOnDiscPeakData(), LayerData::getSpectrum(), and LayerData::setOnDiscPeakData().
param
Param param
Layer parameters.
Referenced by TOPPViewBase::loadFiles(), and TOPPViewBase::updateLayerBar().
peak_colors_1d
std::vector<QColor> peak_colors_1d
Peak colors of the currently shown spectrum.
peaks
ExperimentSharedPtrType peaks private
peak data
Referenced by LayerData::getPeakDataMuteable(), LayerData::getSpectrum(), LayerData::labelAsDIAData(), LayerData::labelAsIonMobilityData(), LayerData::remove_chromatogram_flag(), LayerData::set_chromatogram_flag(), and LayerData::setPeakData().
peptide_hit_index
int peptide_hit_index
peptide_id_index
int peptide_id_index
Selected peptide id and hit index (-1 if none is selected)
peptides
std::vector<PeptideIdentification> peptides
peptide identifications
Referenced by TOPPViewBase::copyLayer().
type
DataType type
data type (peak or feature data)
Referenced by TOPPViewBase::addData(), TOPPViewBase::annotateMS1FromMassFingerprinting_(), TOPPViewBase::annotateWithID(), TOPPViewBase::copyLayer(), TOPPViewBase::fileChanged_(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::runTOPPTool_(), TOPPViewBase::showCurrentPeaksAs3D(), TOPPViewBase::updateLayerBar(), and TOPPViewBase::updateToolBar().
visible
bool visible
if this layer is visible
Referenced by TOPPViewBase::annotateWithID(), TOPPViewBase::editMetadata(), TOPPViewBase::layerVisibilityChange(), TOPPViewBase::rerunTOPPTool(), TOPPViewBase::showTOPPDialog_(), and TOPPViewBase::updateLayerBar().