OpenMS: MetaDataBrowser Class Reference
MetaDataBrowser Class Reference
Visual
A meta data visualization widget.
#include <OpenMS/VISUAL/MetaDataBrowser.h>
Public Slots
void setStatus (std::string status)
Set a list of error strings due to invalid date format.
Public Member Functions
MetaDataBrowser (bool editable=false, QWidget *parent=nullptr, bool modal=false)
Constructor with flag for edit mode.
void add (PeakMap &exp)
Adds a peak map.
void add (MSSpectrum &spectrum)
Adds a peak spectrum.
void add (FeatureMap &map)
Adds a feature map.
void add (Feature &feature)
Adds a feature.
void add (ConsensusFeature &feature)
Adds a consensus feature.
void add (ConsensusMap &map)
Adds a consensus map.
template<class MetaDataType >
void add (MetaDataType &meta_data_object)
A generic function to add data.
bool isEditable ()
Check if mode is editable or not.
Protected Slots
void showDetails_ ()
Raises the corresponding viewer from the widget stack according to the item selected in the tree.
void saveAll_ ()
Saves all changes and close explorer.
Friends
class ProteinIdentificationVisualizer
Defines friend classes that can use the functionality of the subclasses.
class PeptideIdentificationVisualizer
Visualizer for the different classes
std::string status_list_
A list of setting errors due to invalid formats.
bool editable_
Indicates the mode.
QStackedWidget * ws_
A widgetstack that keeps track of all widgets.
QPushButton * saveallbutton_
Save button.
QPushButton * closebutton_
Close Button.
QPushButton * cancelbutton_
Cancel Button.
QPushButton * undobutton_
Undo Button.
QTreeWidget * treeview_
The tree.
void visualize_ (ExperimentalSettings &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (SpectrumSettings &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (MetaInfoInterface &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Sample &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (HPLC &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Digestion &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Modification &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Tagging &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Gradient &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Software &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (ScanWindow &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (SourceFile &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (ContactPerson &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Instrument &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (IonSource &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (IonDetector &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (MassAnalyzer &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (DataProcessingPtr &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (ProteinIdentification &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (ProteinHit &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (PeptideHit &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Acquisition &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (AcquisitionInfo &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (MetaInfoDescription &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Precursor &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (Product &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (InstrumentSettings &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (PeptideIdentification &meta, QTreeWidgetItem *parent=nullptr)
void visualize_ (DocumentIdentifier &meta, QTreeWidgetItem *parent=nullptr)
template<typename ContainerType >
void visualizeAll_ (ContainerType &container, QTreeWidgetItem *parent)
Visualizes all elements of a container.
void connectVisualizer_ (BaseVisualizerGUI *ptr)
Connects the Signals of all visualiser classes with Slot setStatus()
void filterHits_ (double threshold, bool higher_better, int tree_item_id)
Filters hits according to a score threshold. Takes the score orientation into account.
void showAllHits_ (int tree_item_id)
Shows hits.
Detailed Description
A meta data visualization widget.
It contains a tree view showing all objects of the meta data to be viewed in hierarchical order.
The meta info data of the tree items are shown in the right part of the viewer, when they are selected in the tree.
If the data has been modified exec() returns true . Otherwise false is returned.
Improvement:
Add generic mechanism to add items to data vectors e.g. for Instrument - IonSource (Hiwi)
Constructor & Destructor Documentation
MetaDataBrowser()
MetaDataBrowser (bool editable = false, QWidget * parent = nullptr, bool modal = false)
Constructor with flag for edit mode.
Member Function Documentation
add() [1/7]
void add (ConsensusFeature & feature)
Adds a consensus feature.
add() [2/7]
void add (ConsensusMap & map)
Adds a consensus map.
add() [3/7]
void add (Feature & feature)
Adds a feature.
add() [4/7]
void add (FeatureMap & map) inline
Adds a feature map.
References FeatureMap::getProteinIdentifications(), and FeatureMap::getUnassignedPeptideIdentifications().
add() [5/7]
void add (MetaDataType & meta_data_object) inline
A generic function to add data.
The meta data information of all classes that for which a visualize_ method exists can be visualized.
add() [6/7]
void add (MSSpectrum & spectrum) inline
Adds a peak spectrum.
References MSSpectrum::getFloatDataArrays(), MSSpectrum::getIntegerDataArrays(), and MSSpectrum::getStringDataArrays().
add() [7/7]
void add (PeakMap & exp) inline
Adds a peak map.
Referenced by TOPPViewBase::metadataFileDialog().
connectVisualizer_()
void connectVisualizer_ (BaseVisualizerGUI * ptr) protected
Connects the Signals of all visualiser classes with Slot setStatus()
filterHits_()
void filterHits_ (double threshold, bool higher_better, int tree_item_id) protected
Filters hits according to a score threshold. Takes the score orientation into account.
isEditable()
bool isEditable ()
Check if mode is editable or not.
saveAll_
void saveAll_ () protected slot
Saves all changes and close explorer.
setStatus
void setStatus (std::string status) slot
Set a list of error strings due to invalid date format.
showAllHits_()
void showAllHits_ (int tree_item_id) protected
Shows hits.
showDetails_
void showDetails_ () protected slot
Raises the corresponding viewer from the widget stack according to the item selected in the tree.
visualize_() [1/29]
void visualize_ (Acquisition & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [2/29]
void visualize_ (AcquisitionInfo & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [3/29]
void visualize_ (ContactPerson & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [4/29]
void visualize_ (DataProcessingPtr & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [5/29]
void visualize_ (Digestion & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [6/29]
void visualize_ (DocumentIdentifier & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [7/29]
void visualize_ (ExperimentalSettings & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [8/29]
void visualize_ (Gradient & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [9/29]
void visualize_ (HPLC & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [10/29]
void visualize_ (Instrument & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [11/29]
void visualize_ (InstrumentSettings & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [12/29]
void visualize_ (IonDetector & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [13/29]
void visualize_ (IonSource & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [14/29]
void visualize_ (MassAnalyzer & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [15/29]
void visualize_ (MetaInfoDescription & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [16/29]
void visualize_ (MetaInfoInterface & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [17/29]
void visualize_ (Modification & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [18/29]
void visualize_ (PeptideHit & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [19/29]
void visualize_ (PeptideIdentification & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [20/29]
void visualize_ (Precursor & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [21/29]
void visualize_ (Product & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [22/29]
void visualize_ (ProteinHit & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [23/29]
void visualize_ (ProteinIdentification & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [24/29]
void visualize_ (Sample & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [25/29]
void visualize_ (ScanWindow & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [26/29]
void visualize_ (Software & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [27/29]
void visualize_ (SourceFile & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [28/29]
void visualize_ (SpectrumSettings & meta, QTreeWidgetItem * parent = nullptr) protected
visualize_() [29/29]
void visualize_ (Tagging & meta, QTreeWidgetItem * parent = nullptr) protected
visualizeAll_()
void visualizeAll_ (ContainerType & container, QTreeWidgetItem * parent) inline protected
Visualizes all elements of a container.
Friends And Related Function Documentation
PeptideIdentificationVisualizer
friend class PeptideIdentificationVisualizer friend
ProteinIdentificationVisualizer
friend class ProteinIdentificationVisualizer friend
Defines friend classes that can use the functionality of the subclasses.
Member Data Documentation
cancelbutton_
QPushButton* cancelbutton_ protected
Cancel Button.
closebutton_
QPushButton* closebutton_ protected
Close Button.
editable_
bool editable_ protected
Indicates the mode.
saveallbutton_
QPushButton* saveallbutton_ protected
Save button.
status_list_
std::string status_list_ protected
A list of setting errors due to invalid formats.
treeview_
QTreeWidget* treeview_ protected
The tree.
undobutton_
QPushButton* undobutton_ protected
Undo Button.
ws_
QStackedWidget* ws_ protected
A widgetstack that keeps track of all widgets.