OpenMS: Spectrum2DWidget Class Reference
Spectrum2DWidget Class Reference
Visual » Spectrum visualization widgets
Widget for 2D-visualization of peak map and feature map data.
#include <OpenMS/VISUAL/Spectrum2DWidget.h>
Public Types
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType
Main managed data type (experiment)
Public Types inherited from SpectrumWidget
typedef LayerData::ExperimentType ExperimentType
Main data type (experiment)
typedef LayerData::FeatureMapType FeatureMapType
Main data type (features)
typedef ExperimentType::SpectrumType SpectrumType
Spectrum type.
Public Slots
void recalculateAxes_ () override
void toggleProjections ()
Shows/hides the projections.
void updateProjections ()
Updates and shows the projections.
void showGoToDialog () override
Public Slots inherited from SpectrumWidget
void showStatistics ()
Shows statistics about the data (count, min, max, avg of intensity, charge, quality and meta data)
void showIntensityDistribution ()
Shows the intensity distribution of the current layer.
void showMetaDistribution (const String &name)
Shows the meta data distribution of value name of the current layer.
void updateAxes ()
Updates the axes by setting the right labels and calling recalculateAxes_();.
void updateHScrollbar (float min, float disp_min, float disp_max, float max)
Updates the horizontal scrollbar.
void updateVScrollbar (float min, float disp_min, float disp_max, float max)
Updates the vertical scrollbar.
virtual void showGoToDialog ()=0
Shows a goto dialog.
void changeLegendVisibility ()
Toggles the axis legend visibility.
Signals
void visibleAreaChanged (DRange< 2 > area)
Signal emitted whenever the visible area changes.
void showSpectrumAs1D (int index)
Requests to display the spectrum with index index in 1D.
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices)
void showCurrentPeaksAs3D ()
Requests to display all spectra as 1D.
Signals inherited from SpectrumWidget
void sendStatusMessage (std::string, OpenMS::UInt)
Emits a status message that should be displayed for time ms. If time is 0 the message should be displayed until the next message is emitted.
void sendCursorStatus (double mz=-1.0, double rt=-1.0)
Emitted when the cursor position changes (for displaying e.g. in status bar)
void aboutToBeDestroyed (int window_id)
Message about the destruction of this widget.
void openPreferences ()
Shows the main preferences dialog.
void dropReceived (const QMimeData *data, QWidget *source, int id)
Signal that is emitted, when a drag-and-drop action ends on this widget.
Public Member Functions
Spectrum2DWidget (const Param &preferences, QWidget *parent=nullptr)
Default constructor.
~Spectrum2DWidget () override
Destructor.
Spectrum2DCanvas * canvas ()
This method is overwritten to make the class specific members accessible.
const Spectrum1DWidget * getHorizontalProjection () const
const reference to the horizontal projection
const Spectrum1DWidget * getVerticalProjection () const
const reference to the vertical projection
bool projectionsVisible () const
Returns if one of the projections is visible (or both are visible)
Public Member Functions inherited from SpectrumWidget
SpectrumWidget (const Param &preferences, QWidget *parent=nullptr)
Default constructor.
~SpectrumWidget () override
Destructor.
SpectrumCanvas * canvas ()
Returns a pointer to canvas object.
SpectrumCanvas * canvas () const
virtual AxisWidget * xAxis ()
Returns a pointer to the x-axis axis widget.
virtual AxisWidget * yAxis ()
Returns a pointer to the y-axis axis widget.
Int getActionMode () const
Get the mouse action mode.
virtual bool isLegendShown () const
Returns if the axis labels are shown.
virtual void showLegend (bool show)
Shows/hides axis labels.
void setIntensityMode (SpectrumCanvas::IntensityModes mode)
Sets the intensity mode of the SpectrumCanvas.
virtual void hideAxes ()
Hides x-axis and y-axis.
virtual void saveAsImage ()
Saves the widget's content as image file.
Int getWindowId () override
getter for the EnhancedTabBar window id as defined in the interface
void setWindowId (Int window_id) override
setter for the EnhancedTabBar window id as defined in the interface
Public Member Functions inherited from EnhancedTabBarWidgetInterface
virtual ~EnhancedTabBarWidgetInterface ()
Destructor.
Protected Member Functions
Math::Histogram createIntensityDistribution_ () const override
creates the intensity distribution of the current layer
Math::Histogram createMetaDistribution_ (const String &name) const override
creates the meta data distribution of value name of the current layer
Protected Member Functions inherited from SpectrumWidget
void closeEvent (QCloseEvent *e) override
void setCanvas_ (SpectrumCanvas *canvas, UInt row=0, UInt col=2)
Adds the canvas, axes and scrollbars to the layout.
virtual void intensityModeChange_ ()
Switch between different intensity modes.
virtual void recalculateAxes_ ()=0
recalculates the Axis ticks
void correctAreaToObeyMinMaxRanges_ (SpectrumCanvas::AreaType &area)
correct given area X/Y-values if the values under-/overflow the min-/max values of the data
void dragEnterEvent (QDragEnterEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
Protected Attributes
Spectrum1DWidget * projection_vert_
Vertical projection widget.
Spectrum1DWidget * projection_horz_
Horizontal projection widget.
QGroupBox * projection_box_
Group box that shows information about the projections.
QLabel * projection_peaks_
Number of peaks of the projection.
QLabel * projection_sum_
Intensity sum of the projection.
QLabel * projection_max_
Intensity maximum of the projection.
QCheckBox * projections_auto_
Checkbox that indicates that projections should be automatically updated (with a slight delay)
QTimer * projections_timer_
Timer that triggers auto-update of projections.
Protected Attributes inherited from SpectrumWidget
SpectrumCanvas * canvas_
Pointer to the canvas widget.
QGridLayout * grid_
Main layout.
AxisWidget * y_axis_
Vertical axis.
AxisWidget * x_axis_
Horizontal axis.
QScrollBar * x_scrollbar_
Horizontal scrollbar.
QScrollBar * y_scrollbar_
Vertical scrollbar.
Int window_id_
Private Slots
void horizontalProjection (ExperimentSharedPtrType exp)
shows the horizontal projection with the given data and draw mode
void verticalProjection (ExperimentSharedPtrType exp)
shows the vertical projection with the given data and draw mode
void projectionInfo (int peaks, double intensity, double max)
shows projections information
void autoUpdateProjections ()
slot that monitors the visible area changes and triggers the update of projections
Additional Inherited Members
Static Public Attributes inherited from SpectrumWidget
static const char RT_AXIS_TITLE []
static const char MZ_AXIS_TITLE []
static const char INTENSITY_AXIS_TITLE []
static const char IM_MS_AXIS_TITLE []
static const char IM_ONEKZERO_AXIS_TITLE []
Detailed Description
Widget for 2D-visualization of peak map and feature map data.
The widget is composed of two scroll bars, two AxisWidget and a Spectrum2DCanvas as central widget.
The example image shows Spectrum2DWidget displaying a peak layer and a feature layer.
Member Typedef Documentation
ExperimentSharedPtrType
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType
Main managed data type (experiment)
Constructor & Destructor Documentation
Spectrum2DWidget()
Spectrum2DWidget (const Param & preferences, QWidget * parent = nullptr)
Default constructor.
~Spectrum2DWidget()
~Spectrum2DWidget () override
Destructor.
Member Function Documentation
autoUpdateProjections
void autoUpdateProjections () private slot
slot that monitors the visible area changes and triggers the update of projections
canvas()
Spectrum2DCanvas* canvas () inline
This method is overwritten to make the class specific members accessible.
Referenced by TOPPViewBase::changeLabel(), TOPPViewBase::changeUnassigned(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::showCurrentPeaksAs2D(), TOPPViewBase::showCurrentPeaksAsDIA(), TOPPViewBase::showCurrentPeaksAsIonMobility(), and TOPPViewBase::updateToolBar().
createIntensityDistribution_()
Math::Histogram createIntensityDistribution_ () const override protected virtual
creates the intensity distribution of the current layer
Implements SpectrumWidget.
createMetaDistribution_()
Math::Histogram createMetaDistribution_ (const String & name) const override protected virtual
creates the meta data distribution of value name of the current layer
Implements SpectrumWidget.
getHorizontalProjection()
const Spectrum1DWidget* getHorizontalProjection () const
const reference to the horizontal projection
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
getVerticalProjection()
const Spectrum1DWidget* getVerticalProjection () const
const reference to the vertical projection
Referenced by TOPPViewBase::showSpectrumWidgetInWindow().
horizontalProjection
void horizontalProjection (ExperimentSharedPtrType exp) private slot
shows the horizontal projection with the given data and draw mode
projectionInfo
void projectionInfo (int peaks, double intensity, double max) private slot
shows projections information
projectionsVisible()
bool projectionsVisible () const
Returns if one of the projections is visible (or both are visible)
Referenced by TOPPViewBase::toggleProjections().
recalculateAxes_
void recalculateAxes_ () override slot
showCurrentPeaksAs3D
void showCurrentPeaksAs3D () signal
Requests to display all spectra as 1D.
showGoToDialog
void showGoToDialog () override slot
showSpectrumAs1D [1/2]
void showSpectrumAs1D (int index) signal
Requests to display the spectrum with index index in 1D.
showSpectrumAs1D [2/2]
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices) signal
toggleProjections
void toggleProjections () slot
Shows/hides the projections.
Referenced by TOPPViewBase::toggleProjections().
updateProjections
void updateProjections () slot
Updates and shows the projections.
verticalProjection
void verticalProjection (ExperimentSharedPtrType exp) private slot
shows the vertical projection with the given data and draw mode
visibleAreaChanged
void visibleAreaChanged (DRange< 2 > area) signal
Signal emitted whenever the visible area changes.
Parameters
area The new visible area.
Member Data Documentation
projection_box_
QGroupBox* projection_box_ protected
Group box that shows information about the projections.
projection_horz_
Spectrum1DWidget* projection_horz_ protected
Horizontal projection widget.
projection_max_
QLabel* projection_max_ protected
Intensity maximum of the projection.
projection_peaks_
QLabel* projection_peaks_ protected
Number of peaks of the projection.
projection_sum_
QLabel* projection_sum_ protected
Intensity sum of the projection.
projection_vert_
Spectrum1DWidget* projection_vert_ protected
Vertical projection widget.
projections_auto_
QCheckBox* projections_auto_ protected
Checkbox that indicates that projections should be automatically updated (with a slight delay)
projections_timer_
QTimer* projections_timer_ protected
Timer that triggers auto-update of projections.