OpenMS: Spectrum1DWidget Class Reference
Spectrum1DWidget Class Reference
Visual » Spectrum visualization widgets
Widget for visualization of several spectra.
#include <OpenMS/VISUAL/Spectrum1DWidget.h>
Public Slots
void showGoToDialog () override
Public Slots inherited from SpectrumWidget
void showStatistics ()
Shows statistics about the data (count, min, max, avg of intensity, charge, quality and meta data)
void showIntensityDistribution ()
Shows the intensity distribution of the current layer.
void showMetaDistribution (const String &name)
Shows the meta data distribution of value name of the current layer.
void updateAxes ()
Updates the axes by setting the right labels and calling recalculateAxes_();.
void updateHScrollbar (float min, float disp_min, float disp_max, float max)
Updates the horizontal scrollbar.
void updateVScrollbar (float min, float disp_min, float disp_max, float max)
Updates the vertical scrollbar.
virtual void showGoToDialog ()=0
Shows a goto dialog.
void changeLegendVisibility ()
Toggles the axis legend visibility.
Signals
void visibleAreaChanged (double, double)
Is emitted whenever the visible area changes.
void showCurrentPeaksAs2D ()
Requests to display the whole spectrum in 2D view.
void showCurrentPeaksAs3D ()
Requests to display the whole spectrum in 3D view.
void showCurrentPeaksAsIonMobility ()
Requests to display the whole spectrum in ion mobility view.
void showCurrentPeaksAsDIA ()
Requests to display a full DIA window.
Signals inherited from SpectrumWidget
void sendStatusMessage (std::string, OpenMS::UInt)
Emits a status message that should be displayed for time ms. If time is 0 the message should be displayed until the next message is emitted.
void sendCursorStatus (double mz=-1.0, double rt=-1.0)
Emitted when the cursor position changes (for displaying e.g. in status bar)
void aboutToBeDestroyed (int window_id)
Message about the destruction of this widget.
void openPreferences ()
Shows the main preferences dialog.
void dropReceived (const QMimeData *data, QWidget *source, int id)
Signal that is emitted, when a drag-and-drop action ends on this widget.
Public Member Functions
Spectrum1DWidget (const Param &preferences, QWidget *parent=nullptr)
Default constructor.
~Spectrum1DWidget () override
Destructor.
Spectrum1DCanvas * canvas ()
This method is overwritten to make the class specific members accessible.
void hideAxes () override
Hides x-axis and y-axis.
void showLegend (bool show) override
Shows/hides axis labels.
void toggleMirrorView (bool mirror)
Switches to mirror view, displays another y-axis for the second spectrum.
void performAlignment (Size layer_index_1, Size layer_index_2, const Param &param)
Performs an alignment of the layers with layer_index_1 and layer_index_2.
void resetAlignment ()
Resets the alignment.
void saveAsImage () override
Saves the widget's content as image file.
virtual void renderForImage (QPainter &painter)
Public Member Functions inherited from SpectrumWidget
SpectrumWidget (const Param &preferences, QWidget *parent=nullptr)
Default constructor.
~SpectrumWidget () override
Destructor.
SpectrumCanvas * canvas ()
Returns a pointer to canvas object.
SpectrumCanvas * canvas () const
virtual AxisWidget * xAxis ()
Returns a pointer to the x-axis axis widget.
virtual AxisWidget * yAxis ()
Returns a pointer to the y-axis axis widget.
Int getActionMode () const
Get the mouse action mode.
virtual bool isLegendShown () const
Returns if the axis labels are shown.
void setIntensityMode (SpectrumCanvas::IntensityModes mode)
Sets the intensity mode of the SpectrumCanvas.
Int getWindowId () override
getter for the EnhancedTabBar window id as defined in the interface
void setWindowId (Int window_id) override
setter for the EnhancedTabBar window id as defined in the interface
Public Member Functions inherited from EnhancedTabBarWidgetInterface
virtual ~EnhancedTabBarWidgetInterface ()
Destructor.
Protected Member Functions
Math::Histogram createIntensityDistribution_ () const override
creates the intensity distribution of the current layer
Math::Histogram createMetaDistribution_ (const String &name) const override
creates the meta data distribution of value name of the current layer
void recalculateAxes_ () override
recalculates the Axis ticks
Protected Member Functions inherited from SpectrumWidget
void closeEvent (QCloseEvent *e) override
void setCanvas_ (SpectrumCanvas *canvas, UInt row=0, UInt col=2)
Adds the canvas, axes and scrollbars to the layout.
virtual void intensityModeChange_ ()
Switch between different intensity modes.
void correctAreaToObeyMinMaxRanges_ (SpectrumCanvas::AreaType &area)
correct given area X/Y-values if the values under-/overflow the min-/max values of the data
void dragEnterEvent (QDragEnterEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
Protected Attributes
AxisWidget * flipped_y_axis_
The second y-axis for the mirror view.
QSpacerItem * spacer_
Spacer between the two y-axes in mirror mode (needed when visualizing an alignment)
Protected Attributes inherited from SpectrumWidget
SpectrumCanvas * canvas_
Pointer to the canvas widget.
QGridLayout * grid_
Main layout.
AxisWidget * y_axis_
Vertical axis.
AxisWidget * x_axis_
Horizontal axis.
QScrollBar * x_scrollbar_
Horizontal scrollbar.
QScrollBar * y_scrollbar_
Vertical scrollbar.
Int window_id_
Additional Inherited Members
Public Types inherited from SpectrumWidget
typedef LayerData::ExperimentType ExperimentType
Main data type (experiment)
typedef LayerData::FeatureMapType FeatureMapType
Main data type (features)
typedef ExperimentType::SpectrumType SpectrumType
Spectrum type.
Static Public Attributes inherited from SpectrumWidget
static const char RT_AXIS_TITLE []
static const char MZ_AXIS_TITLE []
static const char INTENSITY_AXIS_TITLE []
static const char IM_MS_AXIS_TITLE []
static const char IM_ONEKZERO_AXIS_TITLE []
Detailed Description
Widget for visualization of several spectra.
The widget is composed of a scroll bar, an AxisWidget and a Spectrum1DCanvas as central widget.
The example image shows Spectrum1DWidget displaying a raw data layer and a peak data layer.
Constructor & Destructor Documentation
Spectrum1DWidget()
Spectrum1DWidget (const Param & preferences, QWidget * parent = nullptr)
Default constructor.
~Spectrum1DWidget()
~Spectrum1DWidget () override
Destructor.
Member Function Documentation
canvas()
Spectrum1DCanvas* canvas () inline
This method is overwritten to make the class specific members accessible.
Referenced by TOPPViewBase::addData(), TOPPViewBase::layerContextMenu(), TOPPViewBase::layerZoomChanged(), TOPPViewBase::setDrawMode1D(), TOPPViewBase::showSpectrumAlignmentDialog(), TOPPViewBase::updateMenu(), and TOPPViewBase::updateToolBar().
createIntensityDistribution_()
Math::Histogram createIntensityDistribution_ () const override protected virtual
creates the intensity distribution of the current layer
Implements SpectrumWidget.
createMetaDistribution_()
Math::Histogram createMetaDistribution_ (const String & name) const override protected virtual
creates the meta data distribution of value name of the current layer
Implements SpectrumWidget.
hideAxes()
void hideAxes () override virtual
Hides x-axis and y-axis.
Reimplemented from SpectrumWidget.
performAlignment()
void performAlignment (Size layer_index_1, Size layer_index_2, const Param & param)
Performs an alignment of the layers with layer_index_1 and layer_index_2.
Referenced by TOPPViewBase::showSpectrumAlignmentDialog().
recalculateAxes_()
void recalculateAxes_ () override protected virtual
recalculates the Axis ticks
Implements SpectrumWidget.
renderForImage()
virtual void renderForImage (QPainter & painter) virtual
resetAlignment()
void resetAlignment ()
Resets the alignment.
saveAsImage()
void saveAsImage () override virtual
Saves the widget's content as image file.
Reimplemented from SpectrumWidget.
showCurrentPeaksAs2D
void showCurrentPeaksAs2D () signal
Requests to display the whole spectrum in 2D view.
showCurrentPeaksAs3D
void showCurrentPeaksAs3D () signal
Requests to display the whole spectrum in 3D view.
showCurrentPeaksAsDIA
void showCurrentPeaksAsDIA () signal
Requests to display a full DIA window.
showCurrentPeaksAsIonMobility
void showCurrentPeaksAsIonMobility () signal
Requests to display the whole spectrum in ion mobility view.
showGoToDialog
void showGoToDialog () override slot
showLegend()
void showLegend (bool show) override virtual
Shows/hides axis labels.
Reimplemented from SpectrumWidget.
toggleMirrorView()
void toggleMirrorView (bool mirror)
Switches to mirror view, displays another y-axis for the second spectrum.
visibleAreaChanged
void visibleAreaChanged (double , double) signal
Is emitted whenever the visible area changes.
Member Data Documentation
flipped_y_axis_
AxisWidget* flipped_y_axis_ protected
The second y-axis for the mirror view.
spacer_
QSpacerItem* spacer_ protected
Spacer between the two y-axes in mirror mode (needed when visualizing an alignment)