OpenMS: SpectraIdentificationViewWidget Class Reference
SpectraIdentificationViewWidget Class Reference
Tabular visualization / selection of identified spectra.
#include <OpenMS/VISUAL/SpectraIdentificationViewWidget.h>
Signals
void spectrumSelected (int, int, int)
void spectrumDeselected (int)
void spectrumDoubleClicked (int)
void showSpectrumAs1D (int)
void showSpectrumMetaData (int)
void requestVisibleArea1D (double, double)
Public Member Functions
SpectraIdentificationViewWidget (const Param &preferences, QWidget *parent=nullptr)
Constructor.
~SpectraIdentificationViewWidget () override
Destructor.
void setLayer (LayerData *model)
set / get layer data
LayerData * getLayer ()
QTableWidget * getTableWidget ()
Access the table widget.
Public Member Functions inherited from DefaultParamHandler
DefaultParamHandler (const String &name)
Constructor with name that is displayed in error messages.
DefaultParamHandler (const DefaultParamHandler &rhs)
Copy constructor.
virtual ~DefaultParamHandler ()
Destructor.
virtual DefaultParamHandler & operator= (const DefaultParamHandler &rhs)
Assignment operator.
virtual bool operator== (const DefaultParamHandler &rhs) const
Equality operator.
void setParameters (const Param &param)
Sets the parameters.
const Param & getParameters () const
Non-mutable access to the parameters.
const Param & getDefaults () const
Non-mutable access to the default parameters.
const String & getName () const
Non-mutable access to the name.
void setName (const String &name)
Mutable access to the name.
const std::vector< String > & getSubsections () const
Non-mutable access to the registered subsections.
Public Attributes
bool ignore_update
Helper function to block outgoing signals.
Protected Slots
void updateEntries ()
Rebuild table entries.
Private Slots
void spectrumSelectionChange_ (QTableWidgetItem *, QTableWidgetItem *)
Emits spectrumSelected with the current spectrum index.
void exportEntries_ ()
Export table entries as csv.
void saveIDs_ ()
Saves the (potentially filtered) IDs as an idXML or mzIdentML file.
void updateData_ (QTableWidgetItem *item)
update PeptideIdentification / PeptideHits, when data in the table changes (status of checkboxes)
void headerContextMenu_ (const QPoint &)
Display header context menu.
void cellClicked_ (int row, int column)
Cell clicked in table_widget.
Private Member Functions
void addTextItemToBottomRow_ (const QString &text, Size column_index, const QColor &c)
void addIntItemToBottomRow_ (const Int i, Size column_index, const QColor &c)
void addDoubleItemToBottomRow_ (const double d, Size column_index, const QColor &c)
void addCheckboxItemToBottomRow_ (bool selected, Size column_index, const QColor &c)
Private Attributes
LayerData * layer_
QCheckBox * hide_no_identification_
QCheckBox * create_rows_for_commmon_metavalue_
QTableWidget * table_widget_
bool is_ms1_shown_
QTableWidget * fragment_window_
Additional Inherited Members
Protected Member Functions inherited from DefaultParamHandler
virtual void updateMembers_ ()
This method is used to update extra member variables at the end of the setParameters() method.
void defaultsToParam_ ()
Updates the parameters after the defaults have been set in the constructor.
Protected Attributes inherited from DefaultParamHandler
Param param_
Container for current parameters.
Param defaults_
Container for default parameters. This member should be filled in the constructor of derived classes!
std::vector< String > subsections_
Container for registered subsections. This member should be filled in the constructor of derived classes!
String error_name_
Name that is displayed in error messages during the parameter checking.
bool check_defaults_
If this member is set to false no checking if parameters in done;.
bool warn_empty_defaults_
If this member is set to false no warning is emitted when defaults are empty;.
Detailed Description
Tabular visualization / selection of identified spectra.
Parameters of this class are:
Name Type Default Restrictions Description
enzyme string Trypsin V8-E, leukocyte elastase, proline endopeptidase, glutamyl endopeptidase, Arg-C, Chymotrypsin, Chymotrypsin/P, Trypsin/P, Trypsin, Asp-N, Asp-N/B, Formic_acid, Lys-C, CNBr, Lys-C/P, PepsinA, TrypChymo, Asp-N_ambic, Lys-N, Arg-C/P, V8-DE, Glu-C+P, unspecific cleavage, proline-endopeptidase/HKR, Alpha-lytic protease, 2-iodobenzoate, Clostripain/P, elastase-trypsin-chymotrypsin, cyanogen-bromide, no cleavage, staphylococcal protease/D, iodosobenzoate, PepsinA + P Enzyme to use for digestion (select 'no cleavage' to skip digestion)
model string naive trained, naive The cleavage model to use for digestion. 'Trained' is based on a log likelihood model (see DOI:10.1021/pr060507u).
min_peptide_length int 3 min: 1 Minimum peptide length after digestion (shorter ones will be discarded)
model_trained:threshold float 0.5 min: -2.0 max: 4.0 Model threshold for calling a cleavage. Higher values increase the number of cleavages. -2 will give no cleavages, +4 almost full cleavage.
model_naive:missed_cleavages int 1 min: 0 Maximum number of missed cleavages considered. All possible resulting peptides will be created.
Note:
If a section name is documented, the documentation is displayed as tooltip.
Advanced parameter names are italic.
Constructor & Destructor Documentation
SpectraIdentificationViewWidget()
SpectraIdentificationViewWidget (const Param & preferences, QWidget * parent = nullptr)
Constructor.
~SpectraIdentificationViewWidget()
~SpectraIdentificationViewWidget () override
Destructor.
Member Function Documentation
addCheckboxItemToBottomRow_()
void addCheckboxItemToBottomRow_ (bool selected, Size column_index, const QColor & c) private
addDoubleItemToBottomRow_()
void addDoubleItemToBottomRow_ (const double d, Size column_index, const QColor & c) private
addIntItemToBottomRow_()
void addIntItemToBottomRow_ (const Int i, Size column_index, const QColor & c) private
addTextItemToBottomRow_()
void addTextItemToBottomRow_ (const QString & text, Size column_index, const QColor & c) private
cellClicked_
void cellClicked_ (int row, int column) private slot
Cell clicked in table_widget.
exportEntries_
void exportEntries_ () private slot
Export table entries as csv.
getLayer()
LayerData* getLayer ()
Referenced by TOPPViewBase::updateViewBar().
getTableWidget()
QTableWidget* getTableWidget ()
Access the table widget.
Referenced by TOPPViewBase::updateViewBar().
headerContextMenu_
void headerContextMenu_ (const QPoint &) private slot
Display header context menu.
requestVisibleArea1D
void requestVisibleArea1D (double , double) signal
saveIDs_
void saveIDs_ () private slot
Saves the (potentially filtered) IDs as an idXML or mzIdentML file.
setLayer()
void setLayer (LayerData * model)
set / get layer data
Referenced by TOPPViewBase::updateViewBar().
showSpectrumAs1D
void showSpectrumAs1D (int) signal
showSpectrumMetaData
void showSpectrumMetaData (int) signal
spectrumDeselected
void spectrumDeselected (int) signal
spectrumDoubleClicked
void spectrumDoubleClicked (int) signal
spectrumSelected
void spectrumSelected (int , int , int) signal
spectrumSelectionChange_
void spectrumSelectionChange_ (QTableWidgetItem * , QTableWidgetItem *) private slot
Emits spectrumSelected with the current spectrum index.
updateData_
void updateData_ (QTableWidgetItem * item) private slot
update PeptideIdentification / PeptideHits, when data in the table changes (status of checkboxes)
updateEntries
void updateEntries () protected slot
Rebuild table entries.
Member Data Documentation
create_rows_for_commmon_metavalue_
QCheckBox* create_rows_for_commmon_metavalue_ private
fragment_window_
QTableWidget* fragment_window_ private
hide_no_identification_
QCheckBox* hide_no_identification_ private
ignore_update
bool ignore_update
Helper function to block outgoing signals.
is_ms1_shown_
bool is_ms1_shown_ private
layer_
LayerData* layer_ private
table_widget_
QTableWidget* table_widget_ private