OpenMS: GUIHelpers Class Reference
GUIHelpers Class Reference
Visual
Class which holds static GUI-related helper functions.
#include <OpenMS/VISUAL/MISC/GUIHelpers.h>
Static Public Member Functions
static void openFolder (const QString &folder)
static void startTOPPView (const QStringList &args)
Open TOPPView (e.g. from within TOPPAS)
static void openURL (const QString &target)
Private Member Functions
GUIHelpers ()
private C'tor
Detailed Description
Class which holds static GUI-related helper functions.
Since all methods are static, the c'tor is private.
Constructor & Destructor Documentation
GUIHelpers()
GUIHelpers () private
private C'tor
Member Function Documentation
openFolder()
static void openFolder (const QString & folder) static
Open a folder in file explorer Will show a message box on failure
openURL()
static void openURL (const QString & target) static
Open a certain URL (in a browser) Will show a message box on failure
Referenced by TOPPASBase::showURL(), and TOPPViewBase::showURL().
startTOPPView()
static void startTOPPView (const QStringList & args) static
Open TOPPView (e.g. from within TOPPAS)
Referenced by TOPPASBase::openFilesInTOPPView().