OpenMS: SpectraViewWidget Class Reference
SpectraViewWidget Class Reference
Visual » Spectrum visualization widgets
Hierarchical visualization and selection of spectra.
#include <OpenMS/VISUAL/SpectraViewWidget.h>
Signals
void spectrumSelected (int)
void spectrumSelected (std::vector< int, std::allocator< int > > indices)
void spectrumDoubleClicked (int)
void spectrumDoubleClicked (std::vector< int, std::allocator< int > > indices)
void showSpectrumAs1D (int)
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices)
void showSpectrumMetaData (int)
Public Member Functions
SpectraViewWidget (QWidget *parent=nullptr)
Constructor.
~SpectraViewWidget () override
Destructor.
QTreeWidget * getTreeWidget ()
QComboBox * getComboBox ()
void updateEntries (const LayerData &cl)
Private Slots
void spectrumSearchText_ ()
searches for rows containing a search text (from spectra_search_box_); called when text search box is used
void spectrumBrowserHeaderContextMenu_ (const QPoint &)
void spectrumSelectionChange_ (QTreeWidgetItem *, QTreeWidgetItem *)
void searchAndShow_ ()
searches using text box and plots the spectrum
void spectrumDoubleClicked_ (QTreeWidgetItem *)
called upon double click; emits spectrumDoubleClicked() after some checking (opens a new Tab)
void spectrumContextMenu_ (const QPoint &)
Private Attributes
QLineEdit * spectra_search_box_
QComboBox * spectra_combo_box_
QTreeWidget * spectra_treewidget_
std::map< size_t, std::map< Precursor, std::vector< Size >, Precursor::MZLess > > map_precursor_to_chrom_idx_cache_
cache to store mapping of chromatogram precursors to chromatogram indices
Detailed Description
Hierarchical visualization and selection of spectra.
Constructor & Destructor Documentation
SpectraViewWidget()
SpectraViewWidget (QWidget * parent = nullptr)
Constructor.
~SpectraViewWidget()
~SpectraViewWidget () override
Destructor.
Member Function Documentation
getComboBox()
QComboBox* getComboBox ()
Referenced by TOPPViewBase::updateViewBar().
getTreeWidget()
QTreeWidget* getTreeWidget ()
Referenced by TOPPViewBase::copyLayer(), and TOPPViewBase::updateViewBar().
searchAndShow_
void searchAndShow_ () private slot
searches using text box and plots the spectrum
showSpectrumAs1D [1/2]
void showSpectrumAs1D (int) signal
showSpectrumAs1D [2/2]
void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices) signal
showSpectrumMetaData
void showSpectrumMetaData (int) signal
spectrumBrowserHeaderContextMenu_
void spectrumBrowserHeaderContextMenu_ (const QPoint &) private slot
spectrumContextMenu_
void spectrumContextMenu_ (const QPoint &) private slot
spectrumDoubleClicked [1/2]
void spectrumDoubleClicked (int) signal
spectrumDoubleClicked [2/2]
void spectrumDoubleClicked (std::vector< int, std::allocator< int > > indices) signal
spectrumDoubleClicked_
void spectrumDoubleClicked_ (QTreeWidgetItem *) private slot
called upon double click; emits spectrumDoubleClicked() after some checking (opens a new Tab)
spectrumSearchText_
void spectrumSearchText_ () private slot
searches for rows containing a search text (from spectra_search_box_); called when text search box is used
spectrumSelected [1/2]
void spectrumSelected (int) signal
spectrumSelected [2/2]
void spectrumSelected (std::vector< int, std::allocator< int > > indices) signal
spectrumSelectionChange_
void spectrumSelectionChange_ (QTreeWidgetItem * , QTreeWidgetItem *) private slot
updateEntries()
void updateEntries (const LayerData & cl)
Referenced by TOPPViewBase::updateViewBar().
Member Data Documentation
map_precursor_to_chrom_idx_cache_
std::map<size_t, std::map<Precursor, std::vector<Size>, Precursor::MZLess> > map_precursor_to_chrom_idx_cache_ private
cache to store mapping of chromatogram precursors to chromatogram indices
spectra_combo_box_
QComboBox* spectra_combo_box_ private
spectra_search_box_
QLineEdit* spectra_search_box_ private
spectra_treewidget_
QTreeWidget* spectra_treewidget_ private