OpenMS: TOPPViewSpectraViewBehavior Class Reference
TOPPViewSpectraViewBehavior Class Reference
Behavior of TOPPView in spectra view mode.
#include <OpenMS/VISUAL/TOPPViewSpectraViewBehavior.h>
Type definitions
typedef LayerData::FeatureMapType FeatureMapType
Feature map type.
typedef LayerData::FeatureMapSharedPtrType FeatureMapSharedPtrType
Feature map managed type.
typedef LayerData::ConsensusMapType ConsensusMapType
Consensus feature map type.
typedef LayerData::ConsensusMapSharedPtrType ConsensusMapSharedPtrType
Consensus map managed type.
typedef LayerData::ExperimentType ExperimentType
Peak map type.
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType
Main managed data type (experiment)
typedef ExperimentType::SpectrumType SpectrumType
Peak spectrum type.
TOPPViewBase * tv_
TOPPViewSpectraViewBehavior (TOPPViewBase *parent)
Construct the behaviour with its parent.
virtual void showSpectrumAs1D (int index)
Behavior for showSpectrumAs1D.
virtual void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices)
Behavior for showSpectrumAs1D.
virtual void activate1DSpectrum (int index)
Behavior for activate1DSpectrum.
virtual void activate1DSpectrum (std::vector< int, std::allocator< int > > indices)
Behavior for activate1DSpectrum.
virtual void deactivate1DSpectrum (int index)
Behavior for deactivate1DSpectrum.
virtual void activateBehavior ()
Slot for behavior activation.
virtual void deactivateBehavior ()
Slot for behavior deactivation.
Detailed Description
Behavior of TOPPView in spectra view mode.
Member Typedef Documentation
ConsensusMapSharedPtrType
typedef LayerData::ConsensusMapSharedPtrType ConsensusMapSharedPtrType private
Consensus map managed type.
ConsensusMapType
typedef LayerData::ConsensusMapType ConsensusMapType private
Consensus feature map type.
ExperimentSharedPtrType
typedef LayerData::ExperimentSharedPtrType ExperimentSharedPtrType private
Main managed data type (experiment)
ExperimentType
typedef LayerData::ExperimentType ExperimentType private
Peak map type.
FeatureMapSharedPtrType
typedef LayerData::FeatureMapSharedPtrType FeatureMapSharedPtrType private
Feature map managed type.
FeatureMapType
typedef LayerData::FeatureMapType FeatureMapType private
Feature map type.
SpectrumType
typedef ExperimentType::SpectrumType SpectrumType private
Peak spectrum type.
Constructor & Destructor Documentation
TOPPViewSpectraViewBehavior()
TOPPViewSpectraViewBehavior (TOPPViewBase * parent)
Construct the behaviour with its parent.
Member Function Documentation
activate1DSpectrum [1/2]
virtual void activate1DSpectrum (int index) virtual slot
Behavior for activate1DSpectrum.
activate1DSpectrum [2/2]
virtual void activate1DSpectrum (std::vector< int, std::allocator< int > > indices) virtual slot
Behavior for activate1DSpectrum.
activateBehavior
virtual void activateBehavior () virtual slot
Slot for behavior activation.
Referenced by TOPPViewBase::viewChanged().
deactivate1DSpectrum
virtual void deactivate1DSpectrum (int index) virtual slot
Behavior for deactivate1DSpectrum.
deactivateBehavior
virtual void deactivateBehavior () virtual slot
Slot for behavior deactivation.
Referenced by TOPPViewBase::viewChanged(), and TOPPViewBase::viewTabwidgetDoubleClicked().
showSpectrumAs1D [1/2]
virtual void showSpectrumAs1D (int index) virtual slot
Behavior for showSpectrumAs1D.
Referenced by TOPPViewBase::showSpectrumAs1D().
showSpectrumAs1D [2/2]
virtual void showSpectrumAs1D (std::vector< int, std::allocator< int > > indices) virtual slot
Behavior for showSpectrumAs1D.
Member Data Documentation
tv_
TOPPViewBase* tv_ private