OpenMS: TOPPASToolVertex Class Reference
TOPPASToolVertex Class Reference
Visual » TOPPAS
A vertex representing a TOPP tool.
#include <OpenMS/VISUAL/TOPPASToolVertex.h>
Classes
struct IOInfo
Stores the information for input/output files/lists.
Public Types
enum TOOLSTATUS {
TOOL_READY, TOOL_SCHEDULED, TOOL_RUNNING, TOOL_SUCCESS,
TOOL_CRASH, TOOLSTATUS_SIZE
}
current status of the vertex
Public Types inherited from TOPPASVertex
enum DFS_COLOR { DFS_WHITE, DFS_GRAY, DFS_BLACK }
The color of a vertex during depth-first search.
enum SUBSTREESTATUS { TV_ALLFINISHED, TV_UNFINISHED, TV_UNFINISHED_INBRANCH }
The color of a vertex during depth-first search.
typedef QList< TOPPASEdge * > EdgeContainer
The container for in/out edges.
typedef EdgeContainer::iterator EdgeIterator
A mutable iterator for in/out edges.
typedef EdgeContainer::const_iterator ConstEdgeIterator
A const iterator for in/out edges.
typedef std::map< Int, VertexRoundPackage > RoundPackage
typedef RoundPackage::const_iterator RoundPackageConstIt
typedef RoundPackage::iterator RoundPackageIt
typedef std::vector< RoundPackage > RoundPackages
all information a node needs to process all rounds
Public Slots
void executionFinished (int ec, QProcess::ExitStatus es)
Called when the execution of this tool has finished.
void forwardTOPPOutput ()
Called when the running TOPP tool produces output.
void toolStartedSlot ()
Called when the tool is started.
void toolFinishedSlot ()
Called when the tool has finished.
void toolCrashedSlot ()
Called when the tool has crashed.
void toolFailedSlot ()
Called when the tool has failed.
virtual void toolScheduledSlot ()
Called when the tool was scheduled for running.
void inEdgeHasChanged () override
Called by an incoming edge when it has changed.
void outEdgeHasChanged () override
Called by an outgoing edge when it has changed.
Public Slots inherited from TOPPASVertex
virtual void inEdgeHasChanged ()
Called by an incoming edge when it has changed.
virtual void outEdgeHasChanged ()
Called by an outgoing edge when it has changed.
Signals
void toolStarted ()
Emitted when the tool is started.
void toolFinished ()
Emitted when the tool is finished.
void toolCrashed ()
Emitted when the tool crashes.
void toolFailed (const QString &message="")
Emitted when the tool execution fails.
void toppOutputReady (const QString &out)
Emitted from forwardTOPPOutput() to forward the signal outside.
Signals inherited from TOPPASVertex
void clicked ()
Emitted when this item is clicked.
void released ()
Emitted when this item is released.
void hoveringEdgePosChanged (const QPointF &new_pos)
Emitted when the position of the hovering edge changes.
void newHoveringEdge (const QPointF &pos)
Emitted when a new out edge is supposed to be created.
void finishHoveringEdge ()
Emitted when the mouse is released after having dragged a new edge somewhere.
void somethingHasChanged ()
Emitted when something has changed.
void itemDragged (qreal dx, qreal dy)
Emitted when the item is dragged.
void parameterChanged (const bool invalidates_running_pipeline)
Public Member Functions
TOPPASToolVertex ()
Default constructor.
TOPPASToolVertex (const String &name, const String &type="")
Constructor.
TOPPASToolVertex (const TOPPASToolVertex &rhs)
Copy constructor.
~TOPPASToolVertex () override=default
Destructor.
TOPPASToolVertex & operator= (const TOPPASToolVertex &rhs)
Assignment operator.
String getName () const override
returns the name of the TOPP tool
const String & getType () const
Returns the type of the tool.
void getInputParameters (QVector< IOInfo > &input_infos) const
Fills input_infos with the required input file/list parameters together with their valid types.
void getOutputParameters (QVector< IOInfo > &output_infos) const
Fills output_infos with the required output file/list parameters together with their valid types.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QRectF boundingRect () const override
Returns the bounding rectangle of this item.
void setTopoNr (UInt nr) override
Sets the topological sort number (overridden in tool and output vertices)
void reset (bool reset_all_files=false) override
void setParam (const Param &param)
Sets the Param object of this tool.
const Param & getParam ()
Returns the Param object of this tool.
void run () override
Checks if all parent nodes have finished the tool execution and, if so, runs the tool.
bool updateCurrentOutputFileNames (const RoundPackages &pkg, String &error_message)
TOOLSTATUS getStatus () const
return if tool failed or is ready etc.
void editParam ()
Lets the user edit the parameters of the tool.
int numIterations ()
Returns the number of iterations this tool has to perform.
String getFullOutputDirectory () const
Returns the full directory (including preceding tmp path)
String getOutputDir () const
Returns the directory where this tool stores its output files.
void createDirs ()
Creates all necessary directories.
void openContainingFolder ()
Opens the folder where the file is contained.
void openInTOPPView ()
Opens the files in TOPPView.
bool refreshParameters ()
Refreshes the parameters of this tool, returns if their has been a change.
bool isToolReady () const
underlying TOPP tool found and parameters fetched?! (done in C'Tor)
void toggleBreakpoint ()
Toggle breakpoint.
virtual void emitToolStarted ()
Called when the QProcess in the queue is called: emits 'toolStarted()'.
bool invertRecylingMode () override
invert status of recycling (overriding base class)
Public Member Functions inherited from TOPPASVertex
TOPPASVertex ()
Default Constructor.
TOPPASVertex (const TOPPASVertex &rhs)
Copy constructor.
~TOPPASVertex () override=default
Destructor.
TOPPASVertex & operator= (const TOPPASVertex &rhs)
Assignment operator.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *, QWidget *, bool round_shape=true)
base paint method for all derived classes. should be called first in child-class paint
bool buildRoundPackages (RoundPackages &pkg, String &error_msg)
bool isUpstreamFinished () const
check if all upstream nodes are ready to go ('finished_' is true)
QPainterPath shape () const final
Returns a more precise shape.
ConstEdgeIterator outEdgesBegin () const
Returns begin() iterator of outgoing edges.
ConstEdgeIterator outEdgesEnd () const
Returns end() iterator of outgoing edges.
ConstEdgeIterator inEdgesBegin () const
Returns begin() iterator of incoming edges.
ConstEdgeIterator inEdgesEnd () const
Returns end() iterator of incoming edges.
Size incomingEdgesCount ()
Returns the number of incoming edges.
Size outgoingEdgesCount ()
Returns the number of outgoing edges.
void addInEdge (TOPPASEdge *edge)
Adds an incoming edge.
void addOutEdge (TOPPASEdge *edge)
Adds an outgoing edge.
void removeInEdge (TOPPASEdge *edge)
Removes an incoming edge.
void removeOutEdge (TOPPASEdge *edge)
Removes an outgoing edge.
DFS_COLOR getDFSColor ()
Returns the DFS color of this node.
void setDFSColor (DFS_COLOR color)
Sets the DFS color of this node.
TOPPASVertex::SUBSTREESTATUS getSubtreeStatus () const
Checks if all tools in the subtree below this node are finished.
bool isTopoSortMarked ()
Returns whether the vertex has been marked already (during topological sort)
void setTopoSortMarked (bool b)
(Un)marks the vertex (during topological sort)
UInt getTopoNr ()
Returns the topological sort number.
virtual void markUnreachable ()
Marks this node (and everything further downstream) as unreachable. Overridden behavior in mergers.
bool isReachable ()
Returns whether this node is reachable.
bool isFinished () const
Returns whether this node has already been processed during the current pipeline execution.
bool isRecyclingEnabled () const
get status of recycling
void setRecycling (const bool is_enabled)
set status of recycling
QStringList getFileNames (int param_index, int round) const
gets filenames for a certain output parameter (from this vertex), for a certain TOPPAS round
QStringList getFileNames () const
get all output files for all parameters for all rounds
const RoundPackages & getOutputFiles () const
bool allInputsReady ()
check if all upstream nodes are finished
reimplemented Qt events
String name_
The name of the tool.
String type_
The type of the tool, or "" if it does not have a type.
String tmp_path_
The temporary path.
Param param_
The parameters of the tool.
TOOLSTATUS status_ {TOOL_READY}
current status of the tool
bool tool_ready_ {true}
tool initialization status: if C'tor was successful in finding the TOPP tool, this is set to 'true'
bool breakpoint_set_ {false}
Breakpoint set?
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *e) override
TOPPASScene * getScene_ () const
get parent Scene
bool doesParamChangeInvalidate_ ()
determines if according to current status_, a parameter change would invalidate the pipeline status (e.g., because this node was already processed)
bool renameOutput_ ()
renames SUFFICES of the output files created by the TOPP tool by inspecting file content
bool initParam_ (const QString &old_ini_file="")
Initializes the parameters with standard values (from -write_ini), uses the parameters from the old_ini_file if given, returns if parameters have changed (if old_ini_file was given)
void getParameters_ (QVector< IOInfo > &io_infos, bool input_params) const
Fills io_infos with the required input/output file/list parameters. If input_params is true, input params are returned, otherwise output params.
void writeParam_ (const Param &param, const QString &ini_file)
Writes param to the ini_file.
QString toolnameWithWhitespacesForFancyWordWrapping_ (QPainter *painter, const QString &str)
Helper method for finding good boundaries for wrapping the tool name. Returns a string with whitespaces at the preferred boundaries.
void smartFileNames_ (std::vector< QStringList > &filenames)
Additional Inherited Members
Protected Member Functions inherited from TOPPASVertex
void mouseReleaseEvent (QGraphicsSceneMouseEvent *e) override
void mousePressEvent (QGraphicsSceneMouseEvent *e) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *e) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *e) override
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) override
virtual void moveNewEdgeTo_ (const QPointF &pos)
Moves the target pos of the edge which is just being created to pos.
String get3CharsNumber_ (UInt number) const
Returns a three character string (i.e. 001 instead of 1) for the given number.
void debugOut_ (const String &) const
Displays the debug output message, if TOPPAS_DEBUG is defined.
Protected Attributes inherited from TOPPASVertex
EdgeContainer in_edges_
The list of incoming edges.
EdgeContainer out_edges_
The list of outgoing edges.
bool edge_being_created_ {false}
Indicates whether a new out edge is currently being created.
QColor pen_color_ {Qt::black}
The color of the pen.
QColor brush_color_ { Qt::lightGray}
The color of the brush.
DFS_COLOR dfs_color_ {DFS_WHITE}
The DFS color of this node.
bool topo_sort_marked_ {false}
"marked" flag for topological sort
UInt topo_nr_
The number in a topological sort of the entire graph.
RoundPackages output_files_
Stores the current output file names for each output parameter.
int round_total_ {-1}
number of rounds this node will do ('Merge All' nodes will pass everything, thus do only one round)
int round_counter_ {0}
currently finished number of rounds (TODO: do we need that?)
bool finished_ {false}
Stores whether this node has already been processed during the current pipeline execution.
bool reachable_ {true}
Indicates whether this node is reachable (i.e. there is an input node somewhere further upstream)
bool allow_output_recycling_ {false}
shall subsequent tools be allowed to recycle the output of this node to match the number of rounds imposed by other parent nodes?
Detailed Description
A vertex representing a TOPP tool.
Besides TOPPASScene, this class contains most of the remaining functionality of TOPPAS regarding the execution of pipelines. Once a pipeline run is started from TOPPASScene, the execution is propagated from tool to tool and the TOPP tools are actually called from here.
Member Enumeration Documentation
TOOLSTATUS
enum TOOLSTATUS
current status of the vertex
Enumerator
TOOL_READY
TOOL_SCHEDULED
TOOL_RUNNING
TOOL_SUCCESS
TOOL_CRASH
TOOLSTATUS_SIZE
Constructor & Destructor Documentation
TOPPASToolVertex() [1/3]
TOPPASToolVertex ()
Default constructor.
TOPPASToolVertex() [2/3]
TOPPASToolVertex (const String & name, const String & type = "")
Constructor.
TOPPASToolVertex() [3/3]
TOPPASToolVertex (const TOPPASToolVertex & rhs)
Copy constructor.
~TOPPASToolVertex()
~TOPPASToolVertex () override default
Destructor.
Member Function Documentation
boundingRect()
QRectF boundingRect () const override virtual
Returns the bounding rectangle of this item.
Implements TOPPASVertex.
createDirs()
void createDirs ()
Creates all necessary directories.
doesParamChangeInvalidate_()
bool doesParamChangeInvalidate_ () protected
determines if according to current status_, a parameter change would invalidate the pipeline status (e.g., because this node was already processed)
editParam()
void editParam ()
Lets the user edit the parameters of the tool.
emitToolStarted()
virtual void emitToolStarted () virtual
Called when the QProcess in the queue is called: emits 'toolStarted()'.
executionFinished
void executionFinished (int ec, QProcess::ExitStatus es) slot
Called when the execution of this tool has finished.
forwardTOPPOutput
void forwardTOPPOutput () slot
Called when the running TOPP tool produces output.
getFullOutputDirectory()
String getFullOutputDirectory () const
Returns the full directory (including preceding tmp path)
getInputParameters()
void getInputParameters (QVector< IOInfo > & input_infos) const
Fills input_infos with the required input file/list parameters together with their valid types.
getName()
String getName () const override virtual
returns the name of the TOPP tool
Implements TOPPASVertex.
Referenced by TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), and TOPPASBase::toolStarted().
getOutputDir()
String getOutputDir () const
Returns the directory where this tool stores its output files.
getOutputParameters()
void getOutputParameters (QVector< IOInfo > & output_infos) const
Fills output_infos with the required output file/list parameters together with their valid types.
getParam()
const Param& getParam ()
Returns the Param object of this tool.
getParameters_()
void getParameters_ (QVector< IOInfo > & io_infos, bool input_params) const protected
Fills io_infos with the required input/output file/list parameters. If input_params is true, input params are returned, otherwise output params.
getScene_()
TOPPASScene* getScene_ () const protected
get parent Scene
getStatus()
TOOLSTATUS getStatus () const
return if tool failed or is ready etc.
getType()
const String& getType () const
Returns the type of the tool.
Referenced by TOPPASBase::toolCrashed(), TOPPASBase::toolFailed(), TOPPASBase::toolFinished(), and TOPPASBase::toolStarted().
inEdgeHasChanged
void inEdgeHasChanged () override slot
Called by an incoming edge when it has changed.
initParam_()
bool initParam_ (const QString & old_ini_file = "") protected
Initializes the parameters with standard values (from -write_ini), uses the parameters from the old_ini_file if given, returns if parameters have changed (if old_ini_file was given)
invertRecylingMode()
bool invertRecylingMode () override virtual
invert status of recycling (overriding base class)
Reimplemented from TOPPASVertex.
isToolReady()
bool isToolReady () const
underlying TOPP tool found and parameters fetched?! (done in C'Tor)
Referenced by TOPPASBase::insertNewVertex_().
mouseDoubleClickEvent()
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent * e) override protected
numIterations()
int numIterations ()
Returns the number of iterations this tool has to perform.
openContainingFolder()
void openContainingFolder ()
Opens the folder where the file is contained.
openInTOPPView()
void openInTOPPView ()
Opens the files in TOPPView.
operator=()
TOPPASToolVertex& operator= (const TOPPASToolVertex & rhs)
Assignment operator.
outEdgeHasChanged
void outEdgeHasChanged () override slot
Called by an outgoing edge when it has changed.
paint()
void paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override
refreshParameters()
bool refreshParameters ()
Refreshes the parameters of this tool, returns if their has been a change.
renameOutput_()
bool renameOutput_ () protected
renames SUFFICES of the output files created by the TOPP tool by inspecting file content
reset()
void reset (bool reset_all_files = false) override virtual
Resets the status
Parameters
reset_all_files Not used in this implementation, but in derived classes
Reimplemented from TOPPASVertex.
run()
void run () override virtual
Checks if all parent nodes have finished the tool execution and, if so, runs the tool.
Reimplemented from TOPPASVertex.
setParam()
void setParam (const Param & param)
Sets the Param object of this tool.
setTopoNr()
void setTopoNr (UInt nr) override virtual
Sets the topological sort number (overridden in tool and output vertices)
Reimplemented from TOPPASVertex.
smartFileNames_()
void smartFileNames_ (std::vector< QStringList > & filenames) protected
smart naming of round-based filenames when basename is not unique we take the preceding directory name
toggleBreakpoint()
void toggleBreakpoint ()
Toggle breakpoint.
toolCrashed
void toolCrashed () signal
Emitted when the tool crashes.
toolCrashedSlot
void toolCrashedSlot () slot
Called when the tool has crashed.
toolFailed
void toolFailed (const QString & message = "") signal
Emitted when the tool execution fails.
toolFailedSlot
void toolFailedSlot () slot
Called when the tool has failed.
toolFinished
void toolFinished () signal
Emitted when the tool is finished.
toolFinishedSlot
void toolFinishedSlot () slot
Called when the tool has finished.
toolnameWithWhitespacesForFancyWordWrapping_()
QString toolnameWithWhitespacesForFancyWordWrapping_ (QPainter * painter, const QString & str) protected
Helper method for finding good boundaries for wrapping the tool name. Returns a string with whitespaces at the preferred boundaries.
toolScheduledSlot
virtual void toolScheduledSlot () virtual slot
Called when the tool was scheduled for running.
toolStarted
void toolStarted () signal
Emitted when the tool is started.
toolStartedSlot
void toolStartedSlot () slot
Called when the tool is started.
toppOutputReady
void toppOutputReady (const QString & out) signal
Emitted from forwardTOPPOutput() to forward the signal outside.
updateCurrentOutputFileNames()
bool updateCurrentOutputFileNames (const RoundPackages & pkg, String & error_message)
Updates the vector containing the lists of current output files for all output parameters using the input files as guidance Returns true on success, on failure the error_message is filled
writeParam_()
void writeParam_ (const Param & param, const QString & ini_file) protected
Writes param to the ini_file.
Member Data Documentation
breakpoint_set_
bool breakpoint_set_ {false} protected
Breakpoint set?
name_
String name_ protected
The name of the tool.
param_
Param param_ protected
The parameters of the tool.
status_
TOOLSTATUS status_ {TOOL_READY} protected
current status of the tool
tmp_path_
String tmp_path_ protected
The temporary path.
tool_ready_
bool tool_ready_ {true} protected
tool initialization status: if C'tor was successful in finding the TOPP tool, this is set to 'true'
type_
String type_ protected
The type of the tool, or "" if it does not have a type.