OpenMS: MetaProSIPDecomposition Class Reference
MetaProSIPDecomposition Class Reference
Static Public Member Functions
static Int calculateDecompositionWeightsIsotopicPatterns (Size n_bins, const vector< double > &isotopic_intensities, const IsotopePatterns &patterns, MapRateToScoreType &map_rate_to_decomposition_weight, SIPPeptide &sip_peptide)
> Perform the decomposition
static IsotopePatterns calculateIsotopePatternsFor13CRange (const AASequence &peptide, Size additional_isotopes=5)
static Size getNumberOfLabelingElements (const String &labeling_element, const AASequence &peptide)
static IsotopePatterns calculateIsotopePatternsFor15NRange (const AASequence &peptide, Size additional_isotopes=5)
static IsotopePatterns calculateIsotopePatternsFor2HRange (const AASequence &peptide, Size additional_isotopes=5)
static IsotopePatterns calculateIsotopePatternsFor18ORange (const AASequence &peptide, Size additional_isotopes=5)
static IsotopePatterns calculateIsotopePatternsFor15NRangeOfAveraginePeptide (double mass)
static IsotopePatterns calculateIsotopePatternsFor13CRangeOfAveraginePeptide (double mass)
static IsotopePatterns calculateIsotopePatternsFor2HRangeOfAveraginePeptide (double mass)
static IsotopePatterns calculateIsotopePatternsFor18ORangeOfAveraginePeptide (double mass)
Member Function Documentation
calculateDecompositionWeightsIsotopicPatterns()
static Int calculateDecompositionWeightsIsotopicPatterns (Size n_bins, const vector< double > & isotopic_intensities, const IsotopePatterns & patterns, MapRateToScoreType & map_rate_to_decomposition_weight, SIPPeptide & sip_peptide) inline static
> Perform the decomposition
References SIPPeptide::charge, SIPPeptide::mass_diff, OpenMS::Math::mean(), SIPPeptide::mz_theo, SIPPeptide::reconstruction, SIPPeptide::reconstruction_monoistopic, SIPPeptide::RR, Peak1D::setIntensity(), Peak1D::setMZ(), and NonNegativeLeastSquaresSolver::solve().
calculateIsotopePatternsFor13CRange()
static IsotopePatterns calculateIsotopePatternsFor13CRange (const AASequence & peptide, Size additional_isotopes = 5) inline static
> Given a peptide sequence calculate the theoretical isotopic patterns given all incorporations rate (13C Version) > extend isotopic patterns by additional_isotopes to collect other element higher isotopes at 100% incorporation
References IsotopeDistribution::clear(), AASequence::fromString(), IsotopeDistribution::getContainer(), ElementDB::getElement(), AASequence::getFormula(), ElementDB::getInstance(), EmpiricalFormula::getIsotopeDistribution(), EmpiricalFormula::getNumberOf(), IsotopeDistribution::insert(), IsotopeDistribution::set(), Element::setIsotopeDistribution(), and AASequence::toUnmodifiedString().
calculateIsotopePatternsFor13CRangeOfAveraginePeptide()
static IsotopePatterns calculateIsotopePatternsFor13CRangeOfAveraginePeptide (double mass) inline static
References IsotopeDistribution::clear(), CoarseIsotopePatternGenerator::estimateFromPeptideWeight(), IsotopeDistribution::getContainer(), ElementDB::getElement(), ElementDB::getInstance(), IsotopeDistribution::insert(), and Element::setIsotopeDistribution().
calculateIsotopePatternsFor15NRange()
static IsotopePatterns calculateIsotopePatternsFor15NRange (const AASequence & peptide, Size additional_isotopes = 5) inline static
> Given a peptide sequence calculate the theoretical isotopic patterns given all incorporations rate (15C Version) > extend isotopic patterns by additional_isotopes to collect other element higher isotopes at 100% incorporation
References IsotopeDistribution::clear(), AASequence::fromString(), IsotopeDistribution::getContainer(), ElementDB::getElement(), AASequence::getFormula(), ElementDB::getInstance(), EmpiricalFormula::getIsotopeDistribution(), EmpiricalFormula::getNumberOf(), IsotopeDistribution::insert(), IsotopeDistribution::set(), Element::setIsotopeDistribution(), and AASequence::toUnmodifiedString().
calculateIsotopePatternsFor15NRangeOfAveraginePeptide()
static IsotopePatterns calculateIsotopePatternsFor15NRangeOfAveraginePeptide (double mass) inline static
References IsotopeDistribution::clear(), CoarseIsotopePatternGenerator::estimateFromPeptideWeight(), IsotopeDistribution::getContainer(), ElementDB::getElement(), ElementDB::getInstance(), IsotopeDistribution::insert(), and Element::setIsotopeDistribution().
calculateIsotopePatternsFor18ORange()
static IsotopePatterns calculateIsotopePatternsFor18ORange (const AASequence & peptide, Size additional_isotopes = 5) inline static
References IsotopeDistribution::clear(), AASequence::fromString(), IsotopeDistribution::getContainer(), ElementDB::getElement(), AASequence::getFormula(), ElementDB::getInstance(), EmpiricalFormula::getIsotopeDistribution(), EmpiricalFormula::getNumberOf(), IsotopeDistribution::insert(), IsotopeDistribution::set(), Element::setIsotopeDistribution(), and AASequence::toUnmodifiedString().
calculateIsotopePatternsFor18ORangeOfAveraginePeptide()
static IsotopePatterns calculateIsotopePatternsFor18ORangeOfAveraginePeptide (double mass) inline static
References IsotopeDistribution::clear(), CoarseIsotopePatternGenerator::estimateFromPeptideWeight(), IsotopeDistribution::getContainer(), ElementDB::getElement(), ElementDB::getInstance(), IsotopeDistribution::insert(), and Element::setIsotopeDistribution().
calculateIsotopePatternsFor2HRange()
static IsotopePatterns calculateIsotopePatternsFor2HRange (const AASequence & peptide, Size additional_isotopes = 5) inline static
References IsotopeDistribution::clear(), AASequence::fromString(), IsotopeDistribution::getContainer(), ElementDB::getElement(), AASequence::getFormula(), ElementDB::getInstance(), EmpiricalFormula::getIsotopeDistribution(), EmpiricalFormula::getNumberOf(), IsotopeDistribution::insert(), IsotopeDistribution::set(), Element::setIsotopeDistribution(), and AASequence::toUnmodifiedString().
calculateIsotopePatternsFor2HRangeOfAveraginePeptide()
static IsotopePatterns calculateIsotopePatternsFor2HRangeOfAveraginePeptide (double mass) inline static
References IsotopeDistribution::clear(), CoarseIsotopePatternGenerator::estimateFromPeptideWeight(), IsotopeDistribution::getContainer(), ElementDB::getElement(), ElementDB::getInstance(), IsotopeDistribution::insert(), and Element::setIsotopeDistribution().
getNumberOfLabelingElements()
static Size getNumberOfLabelingElements (const String & labeling_element, const AASequence & peptide) inline static
References AASequence::fromString(), ElementDB::getElement(), AASequence::getFormula(), ElementDB::getInstance(), EmpiricalFormula::getNumberOf(), and AASequence::toUnmodifiedString().