OpenMS: MetaProSIPXICExtraction Class Reference
MetaProSIPXICExtraction Class Reference
Static Public Member Functions
static vector< vector< double > > extractXICs (double seed_rt, vector< double > xic_mzs, double mz_toelrance_ppm, double rt_tolerance_s, const PeakMap &peak_map)
static vector< double > correlateXICsToMono (const vector< vector< double > > &xics)
static vector< double > extractXICsOfIsotopeTraces (Size element_count, double mass_diff, double mz_tolerance_ppm, double rt_tolerance_s, double seed_rt, double seed_mz, double seed_charge, const PeakMap &peak_map, const double min_corr_mono=-1.0)
Member Function Documentation
correlateXICsToMono()
static vector<double> correlateXICsToMono (const vector< vector< double > > & xics) inline static
References OpenMS::Math::pearsonCorrelationCoefficient().
extractXICs()
static vector<vector<double> > extractXICs (double seed_rt, vector< double > xic_mzs, double mz_toelrance_ppm, double rt_tolerance_s, const PeakMap & peak_map) inline static
References MSExperiment::areaBeginConst(), MSExperiment::areaEndConst(), AreaIterator< ValueT, ReferenceT, PointerT, SpectrumIteratorT, PeakIteratorT >::getRT(), OPENMS_LOG_WARN, and MSExperiment::RTBegin().
extractXICsOfIsotopeTraces()
static vector<double> extractXICsOfIsotopeTraces (Size element_count, double mass_diff, double mz_tolerance_ppm, double rt_tolerance_s, double seed_rt, double seed_mz, double seed_charge, const PeakMap & peak_map, const double min_corr_mono = -1.0) inline static
References OpenMS::Constants::k.