OpenMS: FLASHDeconv::PrecalcularedAveragine Struct Reference
FLASHDeconv::PrecalcularedAveragine Struct Reference
Public Member Functions
PrecalcularedAveragine (double m, double M, double delta, CoarseIsotopePatternGenerator *generator)
IsotopeDistribution get (double mass)
double getNorm (double mass)
Size getMostAbundantIndex (double mass)
void print (double mass)
Public Attributes
vector< IsotopeDistribution > isotopes
vector< double > norms
vector< Size > mostAbundantIndices
double massInterval
double minMass
Constructor & Destructor Documentation
PrecalcularedAveragine()
PrecalcularedAveragine (double m, double M, double delta, CoarseIsotopePatternGenerator * generator) inline
References CoarseIsotopePatternGenerator::estimateFromPeptideWeight(), OpenMS::Constants::k, OpenSwath::norm(), and IsotopeDistribution::trimRight().
Member Function Documentation
get()
IsotopeDistribution get (double mass) inline
Referenced by FLASHDeconv::getIsotopeCosineAndDetermineIsotopeIndex().
getMostAbundantIndex()
Size getMostAbundantIndex (double mass) inline
Referenced by FLASHDeconv::PeakGroup::updateMassesAndIntensity().
getNorm()
double getNorm (double mass) inline
Referenced by FLASHDeconv::getIsotopeCosineAndDetermineIsotopeIndex().
print()
void print (double mass) inline
References OpenMS::Constants::k.
Member Data Documentation
isotopes
vector<IsotopeDistribution> isotopes
massInterval
double massInterval
minMass
double minMass
mostAbundantIndices
vector<Size> mostAbundantIndices
norms
vector<double> norms