OpenMS: RIntegration Class Reference
RIntegration Class Reference
Static Public Member Functions
static bool checkRDependencies (const String &tmp_path, StringList package_names, const QString &executable=QString("R"))
Member Function Documentation
checkRDependencies()
static bool checkRDependencies (const String & tmp_path, StringList package_names, const QString & executable = QString("R")) inline static
References TextFile::addLine(), TextFile::begin(), TextFile::end(), OPENMS_LOG_ERROR, OPENMS_LOG_INFO, String::random(), TextFile::store(), and String::toQString().