OpenMS: DBsearchDeconvMass Class Reference
DBsearchDeconvMass Class Reference
Classes
struct Proteoform
struct PTM
struct PTMnode
Public Member Functions
DBsearchDeconvMass ()
DBsearchDeconvMass ()
Public Member Functions inherited from TOPPBase
TOPPBase (const String &name, const String &description, bool official=true, const std::vector< Citation > &citations={})
Constructor.
virtual ~TOPPBase ()
Destructor.
ExitCodes main (int argc, const char **argv)
Main routine of all TOPP applications.
Protected Member Functions
void registerOptionsAndFlags_ () override
Sets the valid command line options (with argument) and flags (without argument).
ExitCodes main_ (int, const char **) override
The actual "main" method. main_() is invoked by main().
void get_PTM_vectors (vector< PTMnode * > &ptmlist, vector< double > &PTM_masss_vec, vector< string > &PTM_str_vec)
string write_PTMlist_fromLinkedList (PTMnode *&ptm_node)
void read_FeatureFinderIntact_result_file (string deconvfilePath, vector< double > &mass_vec, vector< string > &file_lines, string col_name)
int get_index_of_tsv_header (string header_str, string col_name)
String write_proteoform_result (Proteoform &proteoform_node, double deconv_mass, vector< double > &ptm_mass, vector< string > &ptm_str)
String write_proteoform_result_perFeature (Proteoform &proteoform_node, vector< double > &ptm_mass, vector< string > &ptm_str)
int calNomialMass (double &mass)
void buildProteoformMap (string DBfilepath, vector< double > &ptm_masses, vector< Proteoform > &tree, multimap< double, Size > &multimap_proteoform)
void search_map (vector< Proteoform > &tree, multimap< double, Size > &multimap_proteoform, fstream &fs, double tolerance, vector< double > &ptm_mass, vector< string > &ptm_str, vector< double > &mass_vec, const vector< string > &dfile_vec)
void getMassesFromUNIMOD (string unimod_filepath, vector< PTM > &ptm_list, int multimod_limit)
void generatePTM_linkedlist (vector< PTM > &ptm_list, int max_num_ptm, vector< PTMnode * > &result)
void registerOptionsAndFlags_ () override
Sets the valid command line options (with argument) and flags (without argument).
ExitCodes main_ (int, const char **) override
The actual "main" method. main_() is invoked by main().
void get_PTM_vectors (vector< PTMnode * > &ptmlist, vector< double > &PTM_masss_vec, vector< string > &PTM_str_vec)
string write_PTMlist_fromLinkedList (PTMnode *&ptm_node)
void read_FeatureFinderIntact_result_file (string deconvfilePath, vector< double > &mass_vec, vector< string > &file_lines, string col_name)
int get_index_of_tsv_header (string header_str, string col_name)
String write_proteoform_result (Proteoform &proteoform_node, double deconv_mass, vector< double > &ptm_mass, vector< string > &ptm_str)
String write_proteoform_result_perFeature (Proteoform &proteoform_node, vector< double > &ptm_mass, vector< string > &ptm_str)
int calNomialMass (double &mass)
void buildProteoformMap (string DBfilepath, vector< double > &ptm_masses, vector< Proteoform > &tree, multimap< double, Size > &multimap_proteoform)
void search_map (vector< Proteoform > &tree, multimap< double, Size > &multimap_proteoform, fstream &fs, double tolerance, vector< double > &ptm_mass, vector< string > &ptm_str, vector< double > &mass_vec, const vector< string > &dfile_vec)
void getMassesFromUNIMOD (string unimod_filepath, vector< PTM > &ptm_list, int multimod_limit)
void generatePTM_linkedlist (vector< PTM > &ptm_list, int max_num_ptm, vector< PTMnode * > &result)
Protected Member Functions inherited from TOPPBase
String getParamArgument_ (const Param::ParamEntry &entry) const
Utility function that determines a suitable argument value for the given Param::ParamEntry.
std::vector< ParameterInformation > paramToParameterInformation_ (const Param &param) const
Translates the given parameter object into a vector of ParameterInformation, that can be utilized for cl parsing.
ParameterInformation paramEntryToParameterInformation_ (const Param::ParamEntry &entry, const String &argument="", const String &full_name="") const
Transforms a ParamEntry object to command line parameter (ParameterInformation).
void registerParamSubsectionsAsTOPPSubsections_ (const Param &param)
void registerFullParam_ (const Param &param)
Register command line parameters for all entries in a Param object.
void registerStringOption_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers a string option.
void setValidStrings_ (const String &name, const std::vector< String > &strings)
Sets the valid strings for a string option or a whole string list.
void setValidStrings_ (const String &name, const std::string vstrings[], int count)
Sets the valid strings for a string option or a whole string list.
void registerInputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers an input file option.
void registerOutputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers an output file option.
void setValidFormats_ (const String &name, const std::vector< String > &formats, const bool force_OpenMS_format=true)
Sets the formats for a input/output file option or for all members of an input/output file lists.
void registerDoubleOption_ (const String &name, const String &argument, double default_value, const String &description, bool required=true, bool advanced=false)
Registers a double option.
void setMinInt_ (const String &name, Int min)
Sets the minimum value for the integer parameter(can be a list of integers,too) name.
void setMaxInt_ (const String &name, Int max)
Sets the maximum value for the integer parameter(can be a list of integers,too) name.
void setMinFloat_ (const String &name, double min)
Sets the minimum value for the floating point parameter(can be a list of floating points,too) name.
void setMaxFloat_ (const String &name, double max)
Sets the maximum value for the floating point parameter(can be a list of floating points,too) name.
void registerIntOption_ (const String &name, const String &argument, Int default_value, const String &description, bool required=true, bool advanced=false)
Registers an integer option.
void registerIntList_ (const String &name, const String &argument, IntList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of integers option.
void registerDoubleList_ (const String &name, const String &argument, DoubleList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of doubles option.
void registerStringList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of strings option.
void registerInputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers a list of input files option.
void registerOutputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of output files option.
void registerFlag_ (const String &name, const String &description, bool advanced=false)
Registers a flag.
void registerSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file (usually from OpenMS algorithms).
void registerTOPPSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file originating from the TOPP tool itself.
void addEmptyLine_ ()
Adds an empty line between registered variables in the documentation.
String getStringOption_ (const String &name) const
Returns the value of a previously registered string option.
double getDoubleOption_ (const String &name) const
Returns the value of a previously registered double option.
Int getIntOption_ (const String &name) const
Returns the value of a previously registered integer option.
StringList getStringList_ (const String &name) const
Returns the value of a previously registered StringList.
IntList getIntList_ (const String &name) const
Returns the value of a previously registered IntList.
DoubleList getDoubleList_ (const String &name) const
Returns the value of a previously registered DoubleList.
bool getFlag_ (const String &name) const
Returns the value of a previously registered flag.
const ParameterInformation & findEntry_ (const String &name) const
Finds the entry in the parameters_ array that has the name name.
Param const & getParam_ () const
Return all parameters relevant to this TOPP tool.
void checkParam_ (const Param &param, const String &filename, const String &location) const
Checks top-level entries of param according to the information during registration.
void fileParamValidityCheck_ (String &filename, const String &param_name, const ParameterInformation &p) const
checks if an input file exists (respecting the flags)
void checkIfIniParametersAreApplicable_ (const Param &ini_params)
Checks if the parameters of the provided ini file are applicable to this tool.
void printUsage_ ()
Prints the tool-specific command line options and appends the common options.
void writeLog_ (const String &text) const
Writes a string to the log file and to std::cout.
void writeDebug_ (const String &text, UInt min_level) const
Writes a text to the log file and to std::cout if the debug level is at least min_level.
void writeDebug_ (const String &text, const Param &param, UInt min_level) const
Writes a String followed by a Param to the log file and to std::cout if the debug level is at least min_level.
String makeTempDirectory_ () const
Creates a unique temporary directory and returns its name (you have to clean it up yourself)
String makeAutoRemoveTempDirectory_ (Int keep_debug=2)
Creates a unique temporary directory and returns its name (will be cleaned up automatically if debug level is high enough)
void removeTempDirectory_ (const String &dirname, Int keep_debug=2) const
Removes a (temporary) directory.
ExitCodes runExternalProcess_ (const QString &executable, const QStringList &arguments, const QString &workdir="") const
Runs an external process via QProcess and reports its status in the logs.
const String & getIniLocation_ () const
Returns the location of the ini file where parameters are taken from. E.g. if the command line was TOPPTool -instance 17, then this will be "TOPPTool:17:". Note the ':' at the end.
const String & toolName_ () const
Returns the tool name.
void inputFileReadable_ (const String &filename, const String &param_name) const
Checks if an input file exists, is readable and is not empty.
void outputFileWritable_ (const String &filename, const String &param_name) const
Checks if an output file is writable.
bool parseRange_ (const String &text, double &low, double &high) const
Parses a range string ([a]:[b]) into two variables (doubles)
bool parseRange_ (const String &text, Int &low, Int &high) const
Parses a range string ([a]:[b]) into two variables (integers)
void addDataProcessing_ (ConsensusMap &map, const DataProcessing &dp) const
Data processing setter for consensus maps.
void addDataProcessing_ (FeatureMap &map, const DataProcessing &dp) const
Data processing setter for feature maps.
void addDataProcessing_ (PeakMap &map, const DataProcessing &dp) const
Data processing setter for peak maps.
DataProcessing getProcessingInfo_ (DataProcessing::ProcessingAction action) const
Returns the data processing information.
DataProcessing getProcessingInfo_ (const std::set< DataProcessing::ProcessingAction > &actions) const
Returns the data processing information.
bool writeCTD_ ()
Write common tool description (CTD) file.
Static Protected Member Functions
static bool compareNodeByMass (const PTMnode *a, const PTMnode *b)
static void printProgress (float progress)
static bool compareNodeByMass (const PTMnode *a, const PTMnode *b)
static void printProgress (float progress)
Protected Attributes
bool isAvgMass = false
Protected Attributes inherited from TOPPBase
String version_
Version string (if empty, the OpenMS/TOPP version is printed)
String verboseVersion_
Version string including additional revision/date time information. Note: This differs from version_ only if not provided by the user.
bool official_
Flag indicating if this an official TOPP tool.
std::vector< Citation > citations_
Papers, specific for this tool (will be shown in '–help')
ProgressLogger::LogType log_type_
Type of progress logging.
bool test_mode_
Test mode.
Int debug_level_
Debug level set by -debug.
Additional Inherited Members
Public Types inherited from TOPPBase
enum ExitCodes {
EXECUTION_OK, INPUT_FILE_NOT_FOUND, INPUT_FILE_NOT_READABLE, INPUT_FILE_CORRUPT,
INPUT_FILE_EMPTY, CANNOT_WRITE_OUTPUT_FILE, ILLEGAL_PARAMETERS, MISSING_PARAMETERS,
UNKNOWN_ERROR, EXTERNAL_PROGRAM_ERROR, PARSE_ERROR, INCOMPATIBLE_INPUT_DATA,
INTERNAL_ERROR, UNEXPECTED_RESULT
}
Exit codes.
Static Public Member Functions inherited from TOPPBase
static void setMaxNumberOfThreads (int num_threads)
Sets the maximal number of usable threads.
Static Protected Attributes inherited from TOPPBase
static String topp_ini_file_
.TOPP.ini file for storing system default parameters
static const Citation cite_openms_
The OpenMS citation.
Constructor & Destructor Documentation
DBsearchDeconvMass() [1/2]
DBsearchDeconvMass () inline
DBsearchDeconvMass() [2/2]
DBsearchDeconvMass () inline
Member Function Documentation
buildProteoformMap() [1/2]
void buildProteoformMap (string DBfilepath, vector< double > & ptm_masses, vector< Proteoform > & tree, multimap< double, Size > & multimap_proteoform) inline protected
References AASequence::fromString(), AASequence::getAverageWeight(), AASequence::getMonoWeight(), FASTAFile::load(), OPENMS_LOG_INFO, and AASequence::toString().
buildProteoformMap() [2/2]
void buildProteoformMap (string DBfilepath, vector< double > & ptm_masses, vector< Proteoform > & tree, multimap< double, Size > & multimap_proteoform) inline protected
References AASequence::fromString(), AASequence::getAverageWeight(), AASequence::getMonoWeight(), FASTAFile::load(), OPENMS_LOG_INFO, and AASequence::toString().
calNomialMass() [1/2]
int calNomialMass (double & mass) inline protected
calNomialMass() [2/2]
int calNomialMass (double & mass) inline protected
compareNodeByMass() [1/2]
static bool compareNodeByMass (const PTMnode * a, const PTMnode * b) inline static protected
compareNodeByMass() [2/2]
static bool compareNodeByMass (const PTMnode * a, const PTMnode * b) inline static protected
References DBsearchDeconvMass::PTMnode::mass.
generatePTM_linkedlist() [1/2]
void generatePTM_linkedlist (vector< PTM > & ptm_list, int max_num_ptm, vector< PTMnode * > & result) inline protected
generatePTM_linkedlist() [2/2]
void generatePTM_linkedlist (vector< PTM > & ptm_list, int max_num_ptm, vector< PTMnode * > & result) inline protected
get_index_of_tsv_header() [1/2]
int get_index_of_tsv_header (string header_str, string col_name) inline protected
get_index_of_tsv_header() [2/2]
int get_index_of_tsv_header (string header_str, string col_name) inline protected
get_PTM_vectors() [1/2]
void get_PTM_vectors (vector< PTMnode * > & ptmlist, vector< double > & PTM_masss_vec, vector< string > & PTM_str_vec) inline protected
get_PTM_vectors() [2/2]
void get_PTM_vectors (vector< PTMnode * > & ptmlist, vector< double > & PTM_masss_vec, vector< string > & PTM_str_vec) inline protected
getMassesFromUNIMOD() [1/2]
void getMassesFromUNIMOD (string unimod_filepath, vector< PTM > & ptm_list, int multimod_limit) inline protected
References OPENMS_LOG_INFO.
getMassesFromUNIMOD() [2/2]
void getMassesFromUNIMOD (string unimod_filepath, vector< PTM > & ptm_list, int multimod_limit) inline protected
References OpenMS::Internal::ClassTest::infile, OPENMS_LOG_INFO, and String::toDouble().
main_() [1/2]
ExitCodes main_ (int argc, const char ** argv) inline override protected virtual
The actual "main" method. main_() is invoked by main().
Implements TOPPBase.
References OPENMS_LOG_INFO.
main_() [2/2]
ExitCodes main_ (int argc, const char ** argv) inline override protected virtual
The actual "main" method. main_() is invoked by main().
Implements TOPPBase.
References OPENMS_LOG_INFO.
printProgress() [1/2]
static void printProgress (float progress) inline static protected
printProgress() [2/2]
static void printProgress (float progress) inline static protected
read_FeatureFinderIntact_result_file() [1/2]
void read_FeatureFinderIntact_result_file (string deconvfilePath, vector< double > & mass_vec, vector< string > & file_lines, string col_name) inline protected
References OpenMS::Internal::ClassTest::infile, and OPENMS_LOG_ERROR.
read_FeatureFinderIntact_result_file() [2/2]
void read_FeatureFinderIntact_result_file (string deconvfilePath, vector< double > & mass_vec, vector< string > & file_lines, string col_name) inline protected
References OpenMS::Internal::ClassTest::infile, and OPENMS_LOG_ERROR.
registerOptionsAndFlags_() [1/2]
void registerOptionsAndFlags_ () inline override protected virtual
Sets the valid command line options (with argument) and flags (without argument).
The options '-ini' '-log' '-instance' '-debug' and the flag '–help' are automatically registered.
Implements TOPPBase.
registerOptionsAndFlags_() [2/2]
void registerOptionsAndFlags_ () inline override protected virtual
Sets the valid command line options (with argument) and flags (without argument).
The options '-ini' '-log' '-instance' '-debug' and the flag '–help' are automatically registered.
Implements TOPPBase.
search_map() [1/2]
void search_map (vector< Proteoform > & tree, multimap< double, Size > & multimap_proteoform, fstream & fs, double tolerance, vector< double > & ptm_mass, vector< string > & ptm_str, vector< double > & mass_vec, const vector< string > & dfile_vec) inline protected
search_map() [2/2]
void search_map (vector< Proteoform > & tree, multimap< double, Size > & multimap_proteoform, fstream & fs, double tolerance, vector< double > & ptm_mass, vector< string > & ptm_str, vector< double > & mass_vec, const vector< string > & dfile_vec) inline protected
write_proteoform_result() [1/2]
String write_proteoform_result (Proteoform & proteoform_node, double deconv_mass, vector< double > & ptm_mass, vector< string > & ptm_str) inline protected
References DBsearchDeconvMass::Proteoform::accessions, DBsearchDeconvMass::Proteoform::mass, DBsearchDeconvMass::Proteoform::protein_mass, and DBsearchDeconvMass::Proteoform::PTM_index.
write_proteoform_result() [2/2]
String write_proteoform_result (Proteoform & proteoform_node, double deconv_mass, vector< double > & ptm_mass, vector< string > & ptm_str) inline protected
write_proteoform_result_perFeature() [1/2]
String write_proteoform_result_perFeature (Proteoform & proteoform_node, vector< double > & ptm_mass, vector< string > & ptm_str) inline protected
References DBsearchDeconvMass::Proteoform::accessions, DBsearchDeconvMass::Proteoform::mass, DBsearchDeconvMass::Proteoform::protein_mass, and DBsearchDeconvMass::Proteoform::PTM_index.
write_proteoform_result_perFeature() [2/2]
String write_proteoform_result_perFeature (Proteoform & proteoform_node, vector< double > & ptm_mass, vector< string > & ptm_str) inline protected
write_PTMlist_fromLinkedList() [1/2]
string write_PTMlist_fromLinkedList (PTMnode *& ptm_node) inline protected
References DBsearchDeconvMass::PTMnode::mass, DBsearchDeconvMass::PTM::name, DBsearchDeconvMass::PTM::numOfmod, DBsearchDeconvMass::PTMnode::prev, and DBsearchDeconvMass::PTMnode::ptm.
write_PTMlist_fromLinkedList() [2/2]
string write_PTMlist_fromLinkedList (PTMnode *& ptm_node) inline protected
Member Data Documentation
isAvgMass
bool isAvgMass = false protected