OpenMS: MetaProSIPReporting Class Reference
MetaProSIPReporting Class Reference
Static Public Member Functions
static void plotHeatMap (const String &output_dir, const String &tmp_path, const String &file_suffix, const String &file_extension, const vector< vector< double > > &binned_ria, vector< String > class_labels, Size debug_level=0, const QString &executable=QString("R"))
static void plotFilteredSpectra (const String &output_dir, const String &tmp_path, const String &file_suffix, const String &file_extension, const vector< SIPPeptide > &sip_peptides, Size debug_level=0, const QString &executable=QString("R"))
static void writeHTML (const String &qc_output_directory, const String &file_suffix, const String &file_extension, const vector< SIPPeptide > &sip_peptides)
static void plotScoresAndWeights (const String &output_dir, const String &tmp_path, const String &file_suffix, const String &file_extension, const vector< SIPPeptide > &sip_peptides, double score_plot_yaxis_min, Size debug_level=0, const QString &executable=QString("R"))
static void createQualityReport (const String &tmp_path, const String &qc_output_directory, const String &file_suffix, const String &file_extension, const vector< vector< SIPPeptide > > &sip_peptide_cluster, Size n_heatmap_bins, double score_plot_y_axis_min, bool report_natural_peptides, const QString &executable=QString("R"))
static void createCSVReport (vector< vector< SIPPeptide > > &sippeptide_cluster, ofstream &os, map< String, String > &proteinid_to_description)
static void createPeptideCentricCSVReport (const String &in_mzML, const String &file_extension, vector< vector< SIPPeptide > > &sippeptide_cluster, ofstream &os, map< String, String > &proteinid_to_description, String qc_output_directory, String file_suffix, bool report_natural_peptides)
Static Protected Member Functions
static void createBinnedPeptideRIAData_ (const Size n_heatmap_bins, const vector< vector< SIPPeptide > > &sip_clusters, vector< vector< double > > &binned_peptide_ria, vector< String > &cluster_labels)
Member Function Documentation
createBinnedPeptideRIAData_()
static void createBinnedPeptideRIAData_ (const Size n_heatmap_bins, const vector< vector< SIPPeptide > > & sip_clusters, vector< vector< double > > & binned_peptide_ria, vector< String > & cluster_labels) inline static protected
createCSVReport()
static void createCSVReport (vector< vector< SIPPeptide > > & sippeptide_cluster, ofstream & os, map< String, String > & proteinid_to_description) inline static
References SIPPeptide::accessions, OpenMS::Constants::k, OpenMS::Math::median(), String::NONE, String::number(), SIPPeptide::sequence, AASequence::toUnmodifiedString(), String::toUpper(), String::trim(), and SIPPeptide::unique.
createPeptideCentricCSVReport()
static void createPeptideCentricCSVReport (const String & in_mzML, const String & file_extension, vector< vector< SIPPeptide > > & sippeptide_cluster, ofstream & os, map< String, String > & proteinid_to_description, String qc_output_directory, String file_suffix, bool report_natural_peptides) inline static
References SIPPeptide::accessions, SIPPeptide::accumulated, SIPPeptide::charge, SIPPeptide::explained_TIC_fraction, SIPPeptide::feature_mz, SIPPeptide::feature_rt, SIPPeptide::feature_type, SIPPeptide::global_LR, SIPPeptide::incorporations, OpenMS::Constants::k, SIPPeptide::mz_theo, SIPPeptide::non_zero_decomposition_coefficients, String::NONE, String::number(), OPENMS_LOG_INFO, SIPPeptide::score, SIPPeptide::sequence, AASequence::toString(), String::toUpper(), String::trim(), and SIPPeptide::unique.
createQualityReport()
static void createQualityReport (const String & tmp_path, const String & qc_output_directory, const String & file_suffix, const String & file_extension, const vector< vector< SIPPeptide > > & sip_peptide_cluster, Size n_heatmap_bins, double score_plot_y_axis_min, bool report_natural_peptides, const QString & executable = QString("R")) inline static
References OPENMS_LOG_INFO.
plotFilteredSpectra()
static void plotFilteredSpectra (const String & output_dir, const String & tmp_path, const String & file_suffix, const String & file_extension, const vector< SIPPeptide > & sip_peptides, Size debug_level = 0, const QString & executable = QString("R")) inline static
References TextFile::addLine(), String::concatenate(), Peak1D::getIntensity(), Peak1D::getMZ(), TextFile::store(), and String::toQString().
plotHeatMap()
static void plotHeatMap (const String & output_dir, const String & tmp_path, const String & file_suffix, const String & file_extension, const vector< vector< double > > & binned_ria, vector< String > class_labels, Size debug_level = 0, const QString & executable = QString("R")) inline static
References TextFile::addLine(), String::concatenate(), TextFile::store(), and String::toQString().
plotScoresAndWeights()
static void plotScoresAndWeights (const String & output_dir, const String & tmp_path, const String & file_suffix, const String & file_extension, const vector< SIPPeptide > & sip_peptides, double score_plot_yaxis_min, Size debug_level = 0, const QString & executable = QString("R")) inline static
References TextFile::addLine(), String::concatenate(), TextFile::store(), and String::toQString().
writeHTML()
static void writeHTML (const String & qc_output_directory, const String & file_suffix, const String & file_extension, const vector< SIPPeptide > & sip_peptides) inline static
References SIPIncorporation::abundance, TextFile::addLine(), SIPIncorporation::correlation, OpenMS::Constants::k, String::number(), SIPIncorporation::rate, TextFile::store(), and String::toQString().