OpenMS: FLASHDeconv Class Reference
FLASHDeconv Class Reference
Classes
struct LogMzPeak
struct Parameter
struct PeakGroup
struct PrecalcularedAveragine
Public Member Functions
FLASHDeconv ()
Public Member Functions inherited from TOPPBase
TOPPBase (const String &name, const String &description, bool official=true, const std::vector< Citation > &citations={})
Constructor.
virtual ~TOPPBase ()
Destructor.
ExitCodes main (int argc, const char **argv)
Main routine of all TOPP applications.
Protected Member Functions
void registerOptionsAndFlags_ () override
Sets the valid command line options (with argument) and flags (without argument).
Parameter setParameter ()
ExitCodes main_ (int, const char **) override
The actual "main" method. main_() is invoked by main().
void findFeatures (vector< PeakGroup > &peakGroups, MSExperiment &mp, int &featureCntr, fstream &fsf, PrecalcularedAveragine &averagines, Parameter &param)
Protected Member Functions inherited from TOPPBase
String getParamArgument_ (const Param::ParamEntry &entry) const
Utility function that determines a suitable argument value for the given Param::ParamEntry.
std::vector< ParameterInformation > paramToParameterInformation_ (const Param &param) const
Translates the given parameter object into a vector of ParameterInformation, that can be utilized for cl parsing.
ParameterInformation paramEntryToParameterInformation_ (const Param::ParamEntry &entry, const String &argument="", const String &full_name="") const
Transforms a ParamEntry object to command line parameter (ParameterInformation).
void registerParamSubsectionsAsTOPPSubsections_ (const Param &param)
void registerFullParam_ (const Param &param)
Register command line parameters for all entries in a Param object.
void registerStringOption_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers a string option.
void setValidStrings_ (const String &name, const std::vector< String > &strings)
Sets the valid strings for a string option or a whole string list.
void setValidStrings_ (const String &name, const std::string vstrings[], int count)
Sets the valid strings for a string option or a whole string list.
void registerInputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers an input file option.
void registerOutputFile_ (const String &name, const String &argument, const String &default_value, const String &description, bool required=true, bool advanced=false)
Registers an output file option.
void setValidFormats_ (const String &name, const std::vector< String > &formats, const bool force_OpenMS_format=true)
Sets the formats for a input/output file option or for all members of an input/output file lists.
void registerDoubleOption_ (const String &name, const String &argument, double default_value, const String &description, bool required=true, bool advanced=false)
Registers a double option.
void setMinInt_ (const String &name, Int min)
Sets the minimum value for the integer parameter(can be a list of integers,too) name.
void setMaxInt_ (const String &name, Int max)
Sets the maximum value for the integer parameter(can be a list of integers,too) name.
void setMinFloat_ (const String &name, double min)
Sets the minimum value for the floating point parameter(can be a list of floating points,too) name.
void setMaxFloat_ (const String &name, double max)
Sets the maximum value for the floating point parameter(can be a list of floating points,too) name.
void registerIntOption_ (const String &name, const String &argument, Int default_value, const String &description, bool required=true, bool advanced=false)
Registers an integer option.
void registerIntList_ (const String &name, const String &argument, IntList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of integers option.
void registerDoubleList_ (const String &name, const String &argument, DoubleList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of doubles option.
void registerStringList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of strings option.
void registerInputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false, const StringList &tags=StringList())
Registers a list of input files option.
void registerOutputFileList_ (const String &name, const String &argument, StringList default_value, const String &description, bool required=true, bool advanced=false)
Registers a list of output files option.
void registerFlag_ (const String &name, const String &description, bool advanced=false)
Registers a flag.
void registerSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file (usually from OpenMS algorithms).
void registerTOPPSubsection_ (const String &name, const String &description)
Registers an allowed subsection in the INI file originating from the TOPP tool itself.
void addEmptyLine_ ()
Adds an empty line between registered variables in the documentation.
String getStringOption_ (const String &name) const
Returns the value of a previously registered string option.
double getDoubleOption_ (const String &name) const
Returns the value of a previously registered double option.
Int getIntOption_ (const String &name) const
Returns the value of a previously registered integer option.
StringList getStringList_ (const String &name) const
Returns the value of a previously registered StringList.
IntList getIntList_ (const String &name) const
Returns the value of a previously registered IntList.
DoubleList getDoubleList_ (const String &name) const
Returns the value of a previously registered DoubleList.
bool getFlag_ (const String &name) const
Returns the value of a previously registered flag.
const ParameterInformation & findEntry_ (const String &name) const
Finds the entry in the parameters_ array that has the name name.
Param const & getParam_ () const
Return all parameters relevant to this TOPP tool.
void checkParam_ (const Param &param, const String &filename, const String &location) const
Checks top-level entries of param according to the information during registration.
void fileParamValidityCheck_ (String &filename, const String &param_name, const ParameterInformation &p) const
checks if an input file exists (respecting the flags)
void checkIfIniParametersAreApplicable_ (const Param &ini_params)
Checks if the parameters of the provided ini file are applicable to this tool.
void printUsage_ ()
Prints the tool-specific command line options and appends the common options.
void writeLog_ (const String &text) const
Writes a string to the log file and to std::cout.
void writeDebug_ (const String &text, UInt min_level) const
Writes a text to the log file and to std::cout if the debug level is at least min_level.
void writeDebug_ (const String &text, const Param &param, UInt min_level) const
Writes a String followed by a Param to the log file and to std::cout if the debug level is at least min_level.
String makeTempDirectory_ () const
Creates a unique temporary directory and returns its name (you have to clean it up yourself)
String makeAutoRemoveTempDirectory_ (Int keep_debug=2)
Creates a unique temporary directory and returns its name (will be cleaned up automatically if debug level is high enough)
void removeTempDirectory_ (const String &dirname, Int keep_debug=2) const
Removes a (temporary) directory.
ExitCodes runExternalProcess_ (const QString &executable, const QStringList &arguments, const QString &workdir="") const
Runs an external process via QProcess and reports its status in the logs.
const String & getIniLocation_ () const
Returns the location of the ini file where parameters are taken from. E.g. if the command line was TOPPTool -instance 17, then this will be "TOPPTool:17:". Note the ':' at the end.
const String & toolName_ () const
Returns the tool name.
void inputFileReadable_ (const String &filename, const String &param_name) const
Checks if an input file exists, is readable and is not empty.
void outputFileWritable_ (const String &filename, const String &param_name) const
Checks if an output file is writable.
bool parseRange_ (const String &text, double &low, double &high) const
Parses a range string ([a]:[b]) into two variables (doubles)
bool parseRange_ (const String &text, Int &low, Int &high) const
Parses a range string ([a]:[b]) into two variables (integers)
void addDataProcessing_ (ConsensusMap &map, const DataProcessing &dp) const
Data processing setter for consensus maps.
void addDataProcessing_ (FeatureMap &map, const DataProcessing &dp) const
Data processing setter for feature maps.
void addDataProcessing_ (PeakMap &map, const DataProcessing &dp) const
Data processing setter for peak maps.
DataProcessing getProcessingInfo_ (DataProcessing::ProcessingAction action) const
Returns the data processing information.
DataProcessing getProcessingInfo_ (const std::set< DataProcessing::ProcessingAction > &actions) const
Returns the data processing information.
bool writeCTD_ ()
Write common tool description (CTD) file.
Static Protected Member Functions
static double getLogMz (double mz)
static int getNominalMass (double &m)
static double getBinValue (Size bin, double minV, double binWidth)
static Size getBinNumber (double v, double minV, double binWidth)
static void writeHeader (fstream &fs, fstream &fsf, bool featureOut=false)
static PrecalcularedAveragine getPrecalculatedAveragines (Parameter &param)
static vector< PeakGroup > Deconvolution (MSExperiment &map, Parameter &param, PrecalcularedAveragine &averagines, int &specCntr, int &qspecCntr, int &massCntr)
static void writeAnnotatedSpectra (vector< PeakGroup > &pgs, MSExperiment &map, fstream &fs)
static void writePeakGroup (PeakGroup &pg, Parameter &param, fstream &fs)
static void printProgress (float progress)
static vector< LogMzPeak > getLogMzPeaks (MSSpectrum &spec, const Parameter &param)
static vector< PeakGroup > getPeakGroupsFromSpectrum (vector< LogMzPeak > &logMzPeaks, double *filter, double **harmonicFilter, vector< vector< Size >> &prevMassBinVector, vector< double > &prevMinBinLogMassVector, PrecalcularedAveragine &averagines, const Parameter &param, int &specCntr)
static boost::dynamic_bitset getUnionMassBin (boost::dynamic_bitset<> &massBins, double &massBinMinValue, vector< vector< Size >> &prevMassBinVector, vector< double > &prevMassBinMinValue, const Parameter &param)
static vector< PeakGroup > getPeakGroupsWithMassBins (boost::dynamic_bitset<> &unionedMassBins, vector< LogMzPeak > &logMzPeaks, double &mzBinMinValue, double &massBinMinValue, float *sumLogIntensities, long *binOffsets, Byte **chargeRanges, const Parameter &param)
static boost::dynamic_bitset getMzBins (vector< LogMzPeak > &logMzPeaks, double &mzBinMinValue, Size &binNumber, double binWidth, float *intensities)
static Byte ** getMassBins (boost::dynamic_bitset<> &massBins, boost::dynamic_bitset<> &mzBins, double &massBinMinValue, float *sumLogIntensities, long *binOffsets, long **hBinOffsets, boost::dynamic_bitset<> &unionMassBins, float *intensities, const Parameter &param, double &minMass, double &maxMass)
static void printMasses (boost::dynamic_bitset<> &massBins, double &massBinMinValue, Byte *continuousChargePeakPairCount, const Parameter &param)
static void getInitialMassBins (boost::dynamic_bitset<> &massBins, boost::dynamic_bitset<> &mzBins, boost::dynamic_bitset<> &isQualified, float *signal, long **hBinOffsets, long *binOffsets, float *intensities, const Parameter &param)
static Byte ** getFinalMassBins (boost::dynamic_bitset<> &massBins, boost::dynamic_bitset<> &mzBins, boost::dynamic_bitset<> &isQualified, boost::dynamic_bitset<> &unionMassBins, float *sumLogIntensities, long *binOffsets, const Parameter &param, long &binStart, long &binEnd)
static vector< PeakGroup > scoreAndFilterPeakGroups (vector< PeakGroup > &peakGroups, PrecalcularedAveragine &averagines, const Parameter &param)
static void removeOverlappingPeakGroups (vector< PeakGroup > &pgs, double tol)
static void updatePerChargeIsotopeIntensity (double *perIsotopeIntensity, double *perChargeIntensity, PeakGroup &pg, const Parameter &param)
static double getIsotopeCosineAndDetermineIsotopeIndex (double mass, double *perIsotopeIntensities, int perIsotopeIntensitiesSize, PrecalcularedAveragine &averagines, int &offset)
static bool checkSpanDistribution (int *mins, int *maxs, int range, int threshold)
static double getChargeFitScore (double *perChargeIntensity, int range)
static bool checkChargeDistribution (double *perChargeIntensity, int range, int threshold)
static double getCosine (double *a, int &aStart, int &aEnd, IsotopeDistribution &b, int &bSize, double &bNorm, int offset=1)
static double getCosine (vector< double > &a, vector< double > &b, int off=0)
static void filterPeakGroupsByIntensity (vector< PeakGroup > &peakGroups, vector< double > &intensities, const Parameter &param)
Additional Inherited Members
Public Types inherited from TOPPBase
enum ExitCodes {
EXECUTION_OK, INPUT_FILE_NOT_FOUND, INPUT_FILE_NOT_READABLE, INPUT_FILE_CORRUPT,
INPUT_FILE_EMPTY, CANNOT_WRITE_OUTPUT_FILE, ILLEGAL_PARAMETERS, MISSING_PARAMETERS,
UNKNOWN_ERROR, EXTERNAL_PROGRAM_ERROR, PARSE_ERROR, INCOMPATIBLE_INPUT_DATA,
INTERNAL_ERROR, UNEXPECTED_RESULT
}
Exit codes.
Static Public Member Functions inherited from TOPPBase
static void setMaxNumberOfThreads (int num_threads)
Sets the maximal number of usable threads.
Protected Attributes inherited from TOPPBase
String version_
Version string (if empty, the OpenMS/TOPP version is printed)
String verboseVersion_
Version string including additional revision/date time information. Note: This differs from version_ only if not provided by the user.
bool official_
Flag indicating if this an official TOPP tool.
std::vector< Citation > citations_
Papers, specific for this tool (will be shown in '–help')
ProgressLogger::LogType log_type_
Type of progress logging.
bool test_mode_
Test mode.
Int debug_level_
Debug level set by -debug.
Static Protected Attributes inherited from TOPPBase
static String topp_ini_file_
.TOPP.ini file for storing system default parameters
static const Citation cite_openms_
The OpenMS citation.
Class Documentation
FLASHDeconv::Parameter
struct FLASHDeconv::Parameter
Class Members
double binWidth
int chargeRange
String fileName
vector< int > hCharges
double intensityThreshold
int jitter
int maxIsotopeCount
double maxMass
int maxMassCount
int maxMSLevel
int minCharge
double minChargeCosine
double minChargeCosineSpec
int minContinuousChargePeakCount
double minIsotopeCosine
double minIsotopeCosineSpec
double minMass
int minNumOverLappedScans
double minRTSpan
int numOverlappedScans
double RTwindow
int threads
double tolerance
int writeSpecTsv
Constructor & Destructor Documentation
FLASHDeconv()
FLASHDeconv () inline
Member Function Documentation
checkChargeDistribution()
static bool checkChargeDistribution (double * perChargeIntensity, int range, int threshold) inline static protected
References OpenMS::Constants::k.
checkSpanDistribution()
static bool checkSpanDistribution (int * mins, int * maxs, int range, int threshold) inline static protected
References OpenMS::Constants::k.
Deconvolution()
static vector<PeakGroup> Deconvolution (MSExperiment & map, Parameter & param, PrecalcularedAveragine & averagines, int & specCntr, int & qspecCntr, int & massCntr) inline static protected
References MSExperiment::begin(), FLASHDeconv::Parameter::chargeRange, MSExperiment::end(), FLASHDeconv::Parameter::hCharges, FLASHDeconv::Parameter::jitter, OpenMS::Constants::k, FLASHDeconv::Parameter::maxMSLevel, FLASHDeconv::Parameter::minCharge, and MSExperiment::size().
filterPeakGroupsByIntensity()
static void filterPeakGroupsByIntensity (vector< PeakGroup > & peakGroups, vector< double > & intensities, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::maxMassCount.
findFeatures()
void findFeatures (vector< PeakGroup > & peakGroups, MSExperiment & mp, int & featureCntr, fstream & fsf, PrecalcularedAveragine & averagines, Parameter & param) inline protected
References MSExperiment::addSpectrum(), MSExperiment::begin(), OpenMS::Constants::C13C12_MASSDIFF_U, FLASHDeconv::Parameter::chargeRange, Param::copy(), MSExperiment::end(), FLASHDeconv::Parameter::fileName, Param::insert(), FLASHDeconv::Parameter::maxIsotopeCount, FLASHDeconv::Parameter::minCharge, FLASHDeconv::Parameter::minChargeCosine, FLASHDeconv::Parameter::minIsotopeCosine, FLASHDeconv::Parameter::minRTSpan, FLASHDeconv::Parameter::numOverlappedScans, Param::remove(), MassTraceDetection::run(), DefaultParamHandler::setParameters(), Param::setValue(), and FLASHDeconv::Parameter::tolerance.
getBinNumber()
static Size getBinNumber (double v, double minV, double binWidth) inline static protected
getBinValue()
static double getBinValue (Size bin, double minV, double binWidth) inline static protected
getChargeFitScore()
static double getChargeFitScore (double * perChargeIntensity, int range) inline static protected
getCosine() [1/2]
static double getCosine (double * a, int & aStart, int & aEnd, IsotopeDistribution & b, int & bSize, double & bNorm, int offset = 1) inline static protected
getCosine() [2/2]
static double getCosine (vector< double > & a, vector< double > & b, int off = 0) inline static protected
getFinalMassBins()
static Byte** getFinalMassBins (boost::dynamic_bitset<> & massBins, boost::dynamic_bitset<> & mzBins, boost::dynamic_bitset<> & isQualified, boost::dynamic_bitset<> & unionMassBins, float * sumLogIntensities, long * binOffsets, const Parameter & param, long & binStart, long & binEnd) inline static protected
References FLASHDeconv::Parameter::chargeRange.
getInitialMassBins()
static void getInitialMassBins (boost::dynamic_bitset<> & massBins, boost::dynamic_bitset<> & mzBins, boost::dynamic_bitset<> & isQualified, float * signal, long ** hBinOffsets, long * binOffsets, float * intensities, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::chargeRange, FLASHDeconv::Parameter::hCharges, OpenMS::Constants::k, and FLASHDeconv::Parameter::minContinuousChargePeakCount.
getIsotopeCosineAndDetermineIsotopeIndex()
static double getIsotopeCosineAndDetermineIsotopeIndex (double mass, double * perIsotopeIntensities, int perIsotopeIntensitiesSize, PrecalcularedAveragine & averagines, int & offset) inline static protected
References FLASHDeconv::PrecalcularedAveragine::get(), and FLASHDeconv::PrecalcularedAveragine::getNorm().
getLogMz()
static double getLogMz (double mz) inline static protected
References OpenMS::Constants::PROTON_MASS_U.
getLogMzPeaks()
static vector<LogMzPeak> getLogMzPeaks (MSSpectrum & spec, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::intensityThreshold.
getMassBins()
static Byte** getMassBins (boost::dynamic_bitset<> & massBins, boost::dynamic_bitset<> & mzBins, double & massBinMinValue, float * sumLogIntensities, long * binOffsets, long ** hBinOffsets, boost::dynamic_bitset<> & unionMassBins, float * intensities, const Parameter & param, double & minMass, double & maxMass) inline static protected
References FLASHDeconv::Parameter::binWidth.
getMzBins()
static boost::dynamic_bitset getMzBins (vector< LogMzPeak > & logMzPeaks, double & mzBinMinValue, Size & binNumber, double binWidth, float * intensities) inline static protected
getNominalMass()
static int getNominalMass (double & m) inline static protected
getPeakGroupsFromSpectrum()
static vector<PeakGroup> getPeakGroupsFromSpectrum (vector< LogMzPeak > & logMzPeaks, double * filter, double ** harmonicFilter, vector< vector< Size >> & prevMassBinVector, vector< double > & prevMinBinLogMassVector, PrecalcularedAveragine & averagines, const Parameter & param, int & specCntr) inline static protected
References FLASHDeconv::Parameter::binWidth, FLASHDeconv::Parameter::chargeRange, FLASHDeconv::Parameter::hCharges, FLASHDeconv::Parameter::jitter, OpenMS::Constants::k, FLASHDeconv::Parameter::maxMass, FLASHDeconv::Parameter::minContinuousChargePeakCount, FLASHDeconv::Parameter::minMass, FLASHDeconv::Parameter::numOverlappedScans, and OpenMS::Math::round().
getPeakGroupsWithMassBins()
static vector<PeakGroup> getPeakGroupsWithMassBins (boost::dynamic_bitset<> & unionedMassBins, vector< LogMzPeak > & logMzPeaks, double & mzBinMinValue, double & massBinMinValue, float * sumLogIntensities, long * binOffsets, Byte ** chargeRanges, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::binWidth, OpenMS::Constants::C13C12_MASSDIFF_U, FLASHDeconv::Parameter::chargeRange, FLASHDeconv::PeakGroup::massBinIndex, FLASHDeconv::Parameter::maxIsotopeCount, FLASHDeconv::Parameter::minCharge, FLASHDeconv::PeakGroup::peaks, FLASHDeconv::PeakGroup::reserve(), and FLASHDeconv::Parameter::tolerance.
getPrecalculatedAveragines()
static PrecalcularedAveragine getPrecalculatedAveragines (Parameter & param) inline static protected
References FLASHDeconv::Parameter::maxIsotopeCount, and FLASHDeconv::Parameter::maxMass.
getUnionMassBin()
static boost::dynamic_bitset getUnionMassBin (boost::dynamic_bitset<> & massBins, double & massBinMinValue, vector< vector< Size >> & prevMassBinVector, vector< double > & prevMassBinMinValue, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::binWidth, and OpenMS::Math::round().
main_()
ExitCodes main_ (int argc, const char ** argv) inline override protected virtual
The actual "main" method. main_() is invoked by main().
Implements TOPPBase.
References MSExperiment::begin(), MSExperiment::end(), OpenMS::Internal::ClassTest::infile, MzMLFile::load(), ProgressLogger::setLogType(), and MSExperiment::size().
printMasses()
static void printMasses (boost::dynamic_bitset<> & massBins, double & massBinMinValue, Byte * continuousChargePeakPairCount, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::binWidth.
printProgress()
static void printProgress (float progress) inline static protected
registerOptionsAndFlags_()
void registerOptionsAndFlags_ () inline override protected virtual
Sets the valid command line options (with argument) and flags (without argument).
The options '-ini' '-log' '-instance' '-debug' and the flag '–help' are automatically registered.
Implements TOPPBase.
removeOverlappingPeakGroups()
static void removeOverlappingPeakGroups (vector< PeakGroup > & pgs, double tol) inline static protected
scoreAndFilterPeakGroups()
static vector<PeakGroup> scoreAndFilterPeakGroups (vector< PeakGroup > & peakGroups, PrecalcularedAveragine & averagines, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::chargeRange, FLASHDeconv::Parameter::maxIsotopeCount, FLASHDeconv::Parameter::maxMassCount, FLASHDeconv::Parameter::minChargeCosineSpec, FLASHDeconv::Parameter::minContinuousChargePeakCount, FLASHDeconv::Parameter::minIsotopeCosineSpec, and FLASHDeconv::Parameter::tolerance.
setParameter()
Parameter setParameter () inline protected
References FLASHDeconv::Parameter::binWidth, FLASHDeconv::Parameter::chargeRange, FLASHDeconv::Parameter::intensityThreshold, FLASHDeconv::Parameter::jitter, FLASHDeconv::Parameter::maxMass, FLASHDeconv::Parameter::maxMassCount, FLASHDeconv::Parameter::maxMSLevel, FLASHDeconv::Parameter::minCharge, FLASHDeconv::Parameter::minChargeCosine, FLASHDeconv::Parameter::minChargeCosineSpec, FLASHDeconv::Parameter::minContinuousChargePeakCount, FLASHDeconv::Parameter::minIsotopeCosine, FLASHDeconv::Parameter::minIsotopeCosineSpec, FLASHDeconv::Parameter::minMass, FLASHDeconv::Parameter::minRTSpan, FLASHDeconv::Parameter::RTwindow, FLASHDeconv::Parameter::threads, FLASHDeconv::Parameter::tolerance, and FLASHDeconv::Parameter::writeSpecTsv.
updatePerChargeIsotopeIntensity()
static void updatePerChargeIsotopeIntensity (double * perIsotopeIntensity, double * perChargeIntensity, PeakGroup & pg, const Parameter & param) inline static protected
References FLASHDeconv::Parameter::chargeRange, FLASHDeconv::PeakGroup::maxCharge, FLASHDeconv::Parameter::maxIsotopeCount, FLASHDeconv::Parameter::minCharge, FLASHDeconv::PeakGroup::minCharge, and FLASHDeconv::PeakGroup::peaks.
writeAnnotatedSpectra()
static void writeAnnotatedSpectra (vector< PeakGroup > & pgs, MSExperiment & map, fstream & fs) inline static protected
References MSExperiment::begin(), and MSExperiment::end().
writeHeader()
static void writeHeader (fstream & fs, fstream & fsf, bool featureOut = false) inline static protected
writePeakGroup()
static void writePeakGroup (PeakGroup & pg, Parameter & param, fstream & fs) inline static protected
References FLASHDeconv::PeakGroup::avgMass, FLASHDeconv::PeakGroup::chargeCosineScore, FLASHDeconv::Parameter::chargeRange, FLASHDeconv::Parameter::fileName, SpectrumSettings::getNativeID(), MSSpectrum::getRT(), FLASHDeconv::PeakGroup::intensity, FLASHDeconv::PeakGroup::isotopeCosineScore, FLASHDeconv::PeakGroup::massCntr, FLASHDeconv::PeakGroup::massIndex, FLASHDeconv::Parameter::minCharge, FLASHDeconv::PeakGroup::monoisotopicMass, FLASHDeconv::PeakGroup::peaks, FLASHDeconv::PeakGroup::spec, and FLASHDeconv::PeakGroup::specIndex.