OpenMS: MetaProSIPInterpolation Class Reference
MetaProSIPInterpolation Class Reference
Static Public Member Functions
static vector< RateScorePair > getHighPoints (double threshold, const MapRateToScoreType &rate2score, bool debug=false)
< Determine score maxima from rate to score distribution using derivatives from spline interpolation
Member Function Documentation
getHighPoints()
static vector<RateScorePair> getHighPoints (double threshold, const MapRateToScoreType & rate2score, bool debug = false) inline static
< Determine score maxima from rate to score distribution using derivatives from spline interpolation
References CubicSpline2d::derivatives(), CubicSpline2d::eval(), OPENMS_LOG_DEBUG, and RateScorePair::rate.
Referenced by MetaProSIPClustering::getRIAClusterCenter().